IACF: iipr::CGaussian2dFilterParams Class Reference
iipr::CGaussian2dFilterParams Class Reference
Basic implementation for the local operators with a rectangular kernel.
#include <CGaussian2dFilterParams.h>
Public Member Functions
CGaussian2dFilterParams ()
virtual double GetSigma1 () const
virtual void SetSigma1 (double sigma1)
virtual double GetSigma2 () const
virtual void SetSigma2 (double sigma2)
virtual double GetAngle () const
virtual void SetAngle (double sigma1)
virtual bool Serialize (iser::IArchive &archive)
Detailed Description
Basic implementation for the local operators with a rectangular kernel.
Definition at line 15 of file CGaussian2dFilterParams.h.
Constructor & Destructor Documentation
iipr::CGaussian2dFilterParams::CGaussian2dFilterParams ()
Member Function Documentation
virtual double iipr::CGaussian2dFilterParams::GetAngle () const [virtual]
Referenced by iipr::TGaussianProcessorComp< PixelType >::CreateKernel().
virtual double iipr::CGaussian2dFilterParams::GetSigma1 () const [virtual]
Referenced by iipr::TGaussianProcessorComp< PixelType >::CreateKernel().
virtual double iipr::CGaussian2dFilterParams::GetSigma2 () const [virtual]
Referenced by iipr::TGaussianProcessorComp< PixelType >::CreateKernel().
virtual bool iipr::CGaussian2dFilterParams::Serialize (iser::IArchive & archive) [virtual]
Implements iser::ISerializable.
virtual void iipr::CGaussian2dFilterParams::SetAngle (double sigma1) [virtual]
virtual void iipr::CGaussian2dFilterParams::SetSigma1 (double sigma1) [virtual]
virtual void iipr::CGaussian2dFilterParams::SetSigma2 (double sigma2) [virtual]
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Iacf/Include/iipr/CGaussian2dFilterParams.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy