IACF: iipr::CConvolutionKernel2d Class Reference
iipr::CConvolutionKernel2d Class Reference
Implementation of a general 2D convolution kernel.
#include <CConvolutionKernel2d.h>
Classes
struct KernelValue
Public Types
typedef std::vector< KernelValue > KernelValues
typedef
KernelValues::const_iterator Iterator
Public Member Functions
CConvolutionKernel2d ()
CConvolutionKernel2d (const imath::ISampledFunction2d &function)
bool IsValid () const
Return true if the kernel was succesfully initialized for a bitmap.
void InitForBitmap (const iimg::IBitmap &bitmap) const
Create kernel offsets with respect to image size.
Iterator Begin () const
Iterator End () const
double GetWeightsSum () const
i2d::CRectangle GetBoundingBox () const
Protected Attributes
KernelValues m_values
ibase::CSize m_kernelSize
double m_sumWeights
Detailed Description
Implementation of a general 2D convolution kernel.
Internally the kernel is represented by an array of filter weights and offset positions for fast access to the corresponding bitmap values.
For access and iterating through the kernel values you can use the Begin() and End() function, which returns an iterator/accessor.
Definition at line 24 of file CConvolutionKernel2d.h.
Member Typedef Documentation
typedef KernelValues::const_iterator iipr::CConvolutionKernel2d::Iterator
Definition at line 34 of file CConvolutionKernel2d.h.
typedef std::vector<KernelValue> iipr::CConvolutionKernel2d::KernelValues
Definition at line 33 of file CConvolutionKernel2d.h.
Constructor & Destructor Documentation
iipr::CConvolutionKernel2d::CConvolutionKernel2d ()
iipr::CConvolutionKernel2d::CConvolutionKernel2d (const imath::ISampledFunction2d & function)
Member Function Documentation
CConvolutionKernel2d::Iterator iipr::CConvolutionKernel2d::Begin () const [inline]
Definition at line 96 of file CConvolutionKernel2d.h.
References m_values.
CConvolutionKernel2d::Iterator iipr::CConvolutionKernel2d::End () const [inline]
Definition at line 102 of file CConvolutionKernel2d.h.
References m_values.
i2d::CRectangle iipr::CConvolutionKernel2d::GetBoundingBox () const [inline]
Definition at line 114 of file CConvolutionKernel2d.h.
References m_kernelSize.
double iipr::CConvolutionKernel2d::GetWeightsSum () const [inline]
Definition at line 108 of file CConvolutionKernel2d.h.
References m_sumWeights.
void iipr::CConvolutionKernel2d::InitForBitmap (const iimg::IBitmap & bitmap) const
Create kernel offsets with respect to image size.
Definition at line 68 of file CConvolutionKernel2d.h.
References iimg::IBitmap::GetLinesDifference(), istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), I_ASSERT, ibase::CSize::IsNull(), m_kernelSize, and m_values.
bool iipr::CConvolutionKernel2d::IsValid () const
Return true if the kernel was succesfully initialized for a bitmap.
Definition at line 63 of file CConvolutionKernel2d.h.
References m_values.
Member Data Documentation
ibase::CSize iipr::CConvolutionKernel2d::m_kernelSize [protected]
Definition at line 57 of file CConvolutionKernel2d.h.
Referenced by GetBoundingBox(), and InitForBitmap().
double iipr::CConvolutionKernel2d::m_sumWeights [protected]
Definition at line 59 of file CConvolutionKernel2d.h.
Referenced by GetWeightsSum().
KernelValues iipr::CConvolutionKernel2d::m_values [protected]
Definition at line 56 of file CConvolutionKernel2d.h.
Referenced by Begin(), End(), InitForBitmap(), and IsValid().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Iacf/Include/iipr/CConvolutionKernel2d.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy