IACF: iipr::TImageProcessorCompBase< ParameterType > Class Template Reference
iipr::TImageProcessorCompBase< ParameterType > Class Template Reference
Basic implementation for a simple bitmap processor.
#include <TImageProcessorCompBase.h>
Public Types
typedef
iproc::CSyncProcessorCompBase BaseClass
Public Member Functions
TImageProcessorCompBase ()
virtual I_END_COMPONENT int DoProcessing (const iprm::IParamsSet *paramsPtr, const istd::IPolymorphic *inputPtr, istd::IChangeable *outputPtr)
Protected Member Functions
virtual bool ProcessImage (const ParameterType *parameterPtr, const iimg::IBitmap &inputImage, iimg::IBitmap &outputImage)=0
Detailed Description
template<class ParameterType>
class iipr::TImageProcessorCompBase< ParameterType >
Basic implementation for a simple bitmap processor.
Definition at line 26 of file TImageProcessorCompBase.h.
Member Typedef Documentation
template<class ParameterType> typedef iproc::CSyncProcessorCompBase iipr::TImageProcessorCompBase< ParameterType >::BaseClass
Reimplemented from iproc::TSyncProcessorCompBase< Base, Interface >.
Reimplemented in iipr::CLocalDifferenceProcessorComp, iipr::CMovingAverageProcessorComp, iipr::TConvolutionProcessorComp< PixelType, ParameterType, Kernel >, iipr::TGaussianProcessorComp< PixelType >, iipr::TMorphoProcessorComp< PixelType, CompareFunction >, iipr::TUnaryTransformProcessorComp< PixelType, Predicate >, and iipr::TConvolutionProcessorComp< PixelType, iipr::CGaussian2dFilterParams, iipr::CGaussianKernel2d >.
Definition at line 29 of file TImageProcessorCompBase.h.
Constructor & Destructor Documentation
template<class ParameterType > iipr::TImageProcessorCompBase< ParameterType >::TImageProcessorCompBase () [inline]
Definition at line 62 of file TImageProcessorCompBase.h.
Member Function Documentation
template<class ParameterType > int iipr::TImageProcessorCompBase< ParameterType >::DoProcessing (const iprm::IParamsSet * paramsPtr, const istd::IPolymorphic * inputPtr, istd::IChangeable * outputPtr) [inline, virtual]
Definition at line 71 of file TImageProcessorCompBase.h.
References istd::IChangeable::CopyFrom(), istd::CString::FromNumber(), iprm::IParamsSet::GetParameter(), istd::TRetSmartPtr< Type, AccessAdapter >::IsValid(), NULL, iipr::TImageProcessorCompBase< ParameterType >::ProcessImage(), and ibase::TLoggerWrap< Base >::SendInfoMessage().
template<class ParameterType> virtual bool iipr::TImageProcessorCompBase< ParameterType >::ProcessImage (const ParameterType * parameterPtr, const iimg::IBitmap & inputImage, iimg::IBitmap & outputImage) [protected, pure virtual]
Implemented in iipr::CLocalDifferenceProcessorComp, iipr::CMovingAverageProcessorComp, iipr::TConvolutionProcessorComp< PixelType, ParameterType, Kernel >, iipr::TMorphoProcessorComp< PixelType, CompareFunction >, iipr::TUnaryTransformProcessorComp< PixelType, Predicate >, and iipr::TConvolutionProcessorComp< PixelType, iipr::CGaussian2dFilterParams, iipr::CGaussianKernel2d >.
Referenced by iipr::TImageProcessorCompBase< ParameterType >::DoProcessing().
The documentation for this class was generated from the following file:
E:/Work/Projects/Developement/Iacf/Include/iipr/TImageProcessorCompBase.h