IACF: iipr::TMorphoProcessorComp< PixelType, CompareFunction > Class Template Reference
iipr::TMorphoProcessorComp< PixelType, CompareFunction > Class Template Reference
Implementation of general morphological operator.
#include <TMorphoProcessorComp.h>
Public Types
typedef
iipr::TImageParamProcessorCompBase
< IMultidimensionalFilterParams > BaseClass
Protected Member Functions
virtual bool ParamProcessImage (const IMultidimensionalFilterParams *paramsPtr, const iimg::IBitmap &inputImage, iimg::IBitmap &outputImage)
Do image processing with some (optional) parameter set.
Detailed Description
template<typename PixelType, class CompareFunction>
class iipr::TMorphoProcessorComp< PixelType, CompareFunction >
Implementation of general morphological operator.
Definition at line 43 of file TMorphoProcessorComp.h.
Member Typedef Documentation
template<typename PixelType , class CompareFunction > typedef iipr::TImageParamProcessorCompBase<IMultidimensionalFilterParams> iipr::TMorphoProcessorComp< PixelType, CompareFunction >::BaseClass
Reimplemented from iipr::TImageParamProcessorCompBase< IMultidimensionalFilterParams >.
Definition at line 46 of file TMorphoProcessorComp.h.
Member Function Documentation
template<typename PixelType , class CompareFunction > bool iipr::TMorphoProcessorComp< PixelType, CompareFunction >::ParamProcessImage (const IMultidimensionalFilterParams * parameterPtr, const iimg::IBitmap & inputImage, iimg::IBitmap & outputImage) [inline, protected, virtual]
Do image processing with some (optional) parameter set.
Parameters:
parameterPtr extracted parameter set, it can be NULL.
inputImage input image should be processed.
outputImage output image, where processing results will be stored.
Implements iipr::TImageParamProcessorCompBase< IMultidimensionalFilterParams >.
Definition at line 63 of file TMorphoProcessorComp.h.
References iimg::CGeneralBitmap::CopyFrom(), imath::CVarVector::GetElementsCount(), iipr::IMultidimensionalFilterParams::GetFilterLengths(), iimg::IRasterImage::GetImageSize(), istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), iimg::TBitmapIterator2d< PixelType >::MoveTo(), NULL, iimg::TBitmapIterator2d< PixelType >::x, and iimg::TBitmapIterator2d< PixelType >::y.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Iacf/Include/iipr/TMorphoProcessorComp.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy