iipr::TImagePixelInterpolator< PixelComponentType > Class Template Reference
iipr::TImagePixelInterpolator< PixelComponentType > Class Template Reference
#include <TImagePixelInterpolator.h>
Public Types
typedef PixelComponentType PixelComponent
Public Member Functions
TImagePixelInterpolator (const iimg::IBitmap &image, int interpolationMode)
PixelComponentType GetInterpolatedValue (double x, double y, int componentIndex) const
Detailed Description
template<typename PixelComponentType>
class iipr::TImagePixelInterpolator< PixelComponentType >
Definition at line 24 of file TImagePixelInterpolator.h.
Member Typedef Documentation
template<typename PixelComponentType> typedef PixelComponentType iipr::TImagePixelInterpolator< PixelComponentType >::PixelComponent
Definition at line 27 of file TImagePixelInterpolator.h.
Constructor & Destructor Documentation
template<typename PixelComponentType > iipr::TImagePixelInterpolator< PixelComponentType >::TImagePixelInterpolator (const iimg::IBitmap & image, int interpolationMode)
Definition at line 51 of file TImagePixelInterpolator.h.
References iimg::IRasterImage::GetImageSize(), iimg::IBitmap::GetLinePtr(), iimg::IBitmap::GetLinesDifference(), iimg::IBitmap::GetPixelBitsCount(), istd::CIndex2d::GetX(), and istd::CIndex2d::GetY().
Member Function Documentation
template<typename PixelComponentType > TImagePixelInterpolator< PixelComponentType >::PixelComponent iipr::TImagePixelInterpolator< PixelComponentType >::GetInterpolatedValue (double x, double y, int componentIndex) const
Definition at line 64 of file TImagePixelInterpolator.h.
References iipr::IImageInterpolationParams::IM_BILINEAR.
The documentation for this class was generated from the following file:
Include/iipr/TImagePixelInterpolator.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy