IACF: iipr::TUnaryTransformProcessorComp< PixelType, Predicate > Class Template Reference
iipr::TUnaryTransformProcessorComp< PixelType, Predicate > Class Template Reference
Implementation of general morphological operator.
#include <TUnaryTransformProcessorComp.h>
Public Types
typedef
iipr::CImageProcessorCompBase BaseClass
Protected Member Functions
virtual bool ProcessImage (const iprm::IParamsSet *paramsPtr, const iimg::IBitmap &inputImage, iimg::IBitmap &outputImage)
Detailed Description
template<typename PixelType, class Predicate>
class iipr::TUnaryTransformProcessorComp< PixelType, Predicate >
Implementation of general morphological operator.
Definition at line 40 of file TUnaryTransformProcessorComp.h.
Member Typedef Documentation
template<typename PixelType , class Predicate > typedef iipr::CImageProcessorCompBase iipr::TUnaryTransformProcessorComp< PixelType, Predicate >::BaseClass
Reimplemented from iipr::CImageProcessorCompBase.
Definition at line 43 of file TUnaryTransformProcessorComp.h.
Member Function Documentation
template<typename PixelType , class Predicate > bool iipr::TUnaryTransformProcessorComp< PixelType, Predicate >::ProcessImage (const iprm::IParamsSet * paramsPtr, const iimg::IBitmap & inputImage, iimg::IBitmap & outputImage) [inline, protected, virtual]
Implements iipr::CImageProcessorCompBase.
Definition at line 60 of file TUnaryTransformProcessorComp.h.
References iimg::IBitmap::CreateBitmap(), iimg::IBitmap::GetComponentBitsCount(), iimg::TPixelAccessor< PixelType >::GetComponentsCount(), iimg::IRasterImage::GetImageSize(), iimg::IBitmap::GetPixelBitsCount(), and iimg::TBitmapIterator< PixelType >::IsValid().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Iacf/Include/iipr/TUnaryTransformProcessorComp.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy