IACF: iipr::TGaussianProcessorComp< PixelType > Class Template Reference
iipr::TGaussianProcessorComp< PixelType > Class Template Reference
Implementation of general gaussian filter.
#include <TGaussianProcessorComp.h>
Public Types
typedef
iipr::TConvolutionProcessorComp
< PixelType,
iipr::CGaussian2dFilterParams,
iipr::CGaussianKernel2d > BaseClass
Protected Member Functions
virtual iipr::CGaussianKernel2d * CreateKernel (const iipr::CGaussian2dFilterParams *paramsPtr)
Detailed Description
template<typename PixelType>
class iipr::TGaussianProcessorComp< PixelType >
Implementation of general gaussian filter.
Definition at line 19 of file TGaussianProcessorComp.h.
Member Typedef Documentation
template<typename PixelType > typedef iipr::TConvolutionProcessorComp< PixelType, iipr::CGaussian2dFilterParams, iipr::CGaussianKernel2d> iipr::TGaussianProcessorComp< PixelType >::BaseClass
Reimplemented from iipr::TConvolutionProcessorComp< PixelType, iipr::CGaussian2dFilterParams, iipr::CGaussianKernel2d >.
Definition at line 28 of file TGaussianProcessorComp.h.
Member Function Documentation
template<typename PixelType > iipr::CGaussianKernel2d * iipr::TGaussianProcessorComp< PixelType >::CreateKernel (const iipr::CGaussian2dFilterParams * paramsPtr) [inline, protected, virtual]
Implements iipr::TConvolutionProcessorComp< PixelType, iipr::CGaussian2dFilterParams, iipr::CGaussianKernel2d >.
Definition at line 39 of file TGaussianProcessorComp.h.
References iipr::CGaussian2dFilterParams::GetAngle(), iipr::CGaussian2dFilterParams::GetSigma1(), iipr::CGaussian2dFilterParams::GetSigma2(), and NULL.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Iacf/Include/iipr/TGaussianProcessorComp.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy