IACF: iipr::TConvolutionProcessorComp< PixelType, ParameterType, Kernel > Class Template Reference
iipr::TConvolutionProcessorComp< PixelType, ParameterType, Kernel > Class Template Reference
Implementation of general convolution operator.
#include <TConvolutionProcessorComp.h>
Public Types
typedef
iipr::TImageParamProcessorCompBase
< ParameterType > BaseClass
typedef
iipr::TLocalNeighborhood
< iimg::TBitmapIterator
< PixelType >, Kernel > Neighborhood
Protected Member Functions
virtual Kernel * CreateKernel (const ParameterType *paramsPtr)=0
virtual bool ParamProcessImage (const ParameterType *paramsPtr, const iimg::IBitmap &inputImage, iimg::IBitmap &outputImage)
Do image processing with some (optional) parameter set.
Detailed Description
template<typename PixelType, class ParameterType, class Kernel>
class iipr::TConvolutionProcessorComp< PixelType, ParameterType, Kernel >
Implementation of general convolution operator.
Definition at line 19 of file TConvolutionProcessorComp.h.
Member Typedef Documentation
template<typename PixelType, class ParameterType, class Kernel> typedef iipr::TImageParamProcessorCompBase<ParameterType> iipr::TConvolutionProcessorComp< PixelType, ParameterType, Kernel >::BaseClass
Reimplemented from iipr::TImageParamProcessorCompBase< ParameterType >.
Reimplemented in iipr::TGaussianProcessorComp< PixelType >.
Definition at line 22 of file TConvolutionProcessorComp.h.
template<typename PixelType, class ParameterType, class Kernel> typedef iipr::TLocalNeighborhood<iimg::TBitmapIterator<PixelType>, Kernel> iipr::TConvolutionProcessorComp< PixelType, ParameterType, Kernel >::Neighborhood
Definition at line 23 of file TConvolutionProcessorComp.h.
Member Function Documentation
template<typename PixelType, class ParameterType, class Kernel> virtual Kernel* iipr::TConvolutionProcessorComp< PixelType, ParameterType, Kernel >::CreateKernel (const ParameterType * paramsPtr) [protected, pure virtual]
Implemented in iipr::TGaussianProcessorComp< PixelType >.
Referenced by iipr::TConvolutionProcessorComp< PixelType, ParameterType, Kernel >::ParamProcessImage().
template<typename PixelType , class ParameterType, class Kernel > bool iipr::TConvolutionProcessorComp< PixelType, ParameterType, Kernel >::ParamProcessImage (const ParameterType * parameterPtr, const iimg::IBitmap & inputImage, iimg::IBitmap & outputImage) [inline, protected, virtual]
Do image processing with some (optional) parameter set.
Parameters:
parameterPtr extracted parameter set, it can be NULL.
inputImage input image should be processed.
outputImage output image, where processing results will be stored.
Implements iipr::TImageParamProcessorCompBase< ParameterType >.
Definition at line 40 of file TConvolutionProcessorComp.h.
References iimg::TBitmapIterator< PixelType >::AtEnd(), iipr::TLocalNeighborhood< BitmapIterator, Kernel >::Begin(), iipr::TConvolutionProcessorComp< PixelType, ParameterType, Kernel >::CreateKernel(), i2d::CRectangle::Expand(), i2d::CRectangle::GetHeight(), iimg::IRasterImage::GetImageSize(), i2d::CRectangle::GetWidth(), istd::TPointerBase< Type >::IsValid(), and NULL.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Iacf/Include/iipr/TConvolutionProcessorComp.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy