IACF: iipr::TGaussianKernel2d< PixelType, KernelType > Class Template Reference
iipr::TGaussianKernel2d< PixelType, KernelType > Class Template Reference
#include <TGaussianKernel2d.h>
Public Types
typedef iipr::TKernel2d
< PixelType, KernelType > BaseClass
Public Member Functions
TGaussianKernel2d ()
TGaussianKernel2d (double sigma1, double sigma2, double angle, const iimg::IBitmap *bitmapPtr=NULL)
Protected Member Functions
void CreateKernel (double sigma1, double sigma2, double angle)
Detailed Description
template<typename PixelType, typename KernelType>
class iipr::TGaussianKernel2d< PixelType, KernelType >
Definition at line 13 of file TGaussianKernel2d.h.
Member Typedef Documentation
template<typename PixelType , typename KernelType > typedef iipr::TKernel2d<PixelType, KernelType> iipr::TGaussianKernel2d< PixelType, KernelType >::BaseClass
Definition at line 16 of file TGaussianKernel2d.h.
Constructor & Destructor Documentation
template<typename PixelType , typename KernelType > iipr::TGaussianKernel2d< PixelType, KernelType >::TGaussianKernel2d () [inline]
Definition at line 27 of file TGaussianKernel2d.h.
References I_CRITICAL.
template<typename PixelType , typename KernelType > iipr::TGaussianKernel2d< PixelType, KernelType >::TGaussianKernel2d (double sigma1, double sigma2, double angle, const iimg::IBitmap * bitmapPtr = NULL) [inline]
Definition at line 34 of file TGaussianKernel2d.h.
References iipr::TGaussianKernel2d< PixelType, KernelType >::CreateKernel(), iipr::TKernel2d< PixelType, KernelType >::InitForBitmap(), and NULL.
Member Function Documentation
template<typename PixelType , typename KernelType > void iipr::TGaussianKernel2d< PixelType, KernelType >::CreateKernel (double sigma1, double sigma2, double angle) [inline, protected]
Definition at line 51 of file TGaussianKernel2d.h.
References iipr::TKernel2d< PixelType, KernelType >::m_kernelSize, iipr::TKernel2d< PixelType, KernelType >::m_sumWeights, and iipr::TKernel2d< PixelType, KernelType >::m_values.
Referenced by iipr::TGaussianKernel2d< PixelType, KernelType >::TGaussianKernel2d().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Iacf/Include/iipr/TGaussianKernel2d.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy