IACF: iipr::TFeaturesContainerWrap< BaseClass, FeatureInterface > Class Template Reference
iipr::TFeaturesContainerWrap< BaseClass, FeatureInterface > Class Template Reference
Basic implementation of a features container.
#include <TFeaturesContainerWrap.h>
Public Member Functions
virtual void ResetFeatures ()
virtual bool AddFeature (const iipr::IFeature *featurePtr, bool *isFullPtr=NULL)
virtual
iipr::IFeaturesContainer::Features GetFeatures () const
Protected Member Functions
virtual bool IsFeatureAccepted (const iipr::IFeature *featurePtr) const
Return true if the feature is accepted by the concrete container implementation.
Detailed Description
template<class BaseClass, class FeatureInterface>
class iipr::TFeaturesContainerWrap< BaseClass, FeatureInterface >
Basic implementation of a features container.
Definition at line 19 of file TFeaturesContainerWrap.h.
Member Function Documentation
template<class BaseClass , class FeatureInterface > bool iipr::TFeaturesContainerWrap< BaseClass, FeatureInterface >::AddFeature (const iipr::IFeature * featurePtr, bool * isFullPtr = NULL) [inline, virtual]
Definition at line 54 of file TFeaturesContainerWrap.h.
References iipr::TFeaturesContainerWrap< BaseClass, FeatureInterface >::IsFeatureAccepted(), NULL, and istd::TPointerVector< Pointer, AccessAdapter >::PushBack().
template<class BaseClass , class FeatureInterface > iipr::IFeaturesContainer::Features iipr::TFeaturesContainerWrap< BaseClass, FeatureInterface >::GetFeatures () const [inline, virtual]
Definition at line 71 of file TFeaturesContainerWrap.h.
References istd::TPointerVector< Pointer, AccessAdapter >::GetAt(), and istd::TPointerVector< Pointer, AccessAdapter >::GetCount().
template<class BaseClass , class FeatureInterface > bool iipr::TFeaturesContainerWrap< BaseClass, FeatureInterface >::IsFeatureAccepted (const iipr::IFeature * featurePtr) const [inline, protected, virtual]
Return true if the feature is accepted by the concrete container implementation.
Definition at line 86 of file TFeaturesContainerWrap.h.
References I_ASSERT, and NULL.
Referenced by iipr::TFeaturesContainerWrap< BaseClass, FeatureInterface >::AddFeature().
template<class BaseClass , class FeatureInterface > void iipr::TFeaturesContainerWrap< BaseClass, FeatureInterface >::ResetFeatures () [inline, virtual]
Definition at line 45 of file TFeaturesContainerWrap.h.
References istd::TPointerVector< Pointer, AccessAdapter >::Reset().
The documentation for this class was generated from the following file:
E:/Work/Projects/Developement/Iacf/Include/iipr/TFeaturesContainerWrap.h