IACF: ilolv::TOrderedPositionsQueue< Object, SizeBits > Struct Template Reference
ilolv::TOrderedPositionsQueue< Object, SizeBits > Struct Template Reference
#include <TOrderedPositionsQueue.h>
Classes
struct Element
Public Types
enum { MAX_SIZE = 1 << SizeBits, INDEX_MASK = MAX_SIZE - 1 }
Public Member Functions
bool IsEmpty () const
Check if this queue is empty.
void Reset ()
Remove all elements from this queue.
int Insert (I_DWORD position, const Object *objectPtr=NULL)
Insert new position to the queue.
int FindByPosition (I_DWORD position, int tolerance) const
Find element in queue using its position.
I_DWORD GetPositionAt (int index) const
const Object & GetObjectAt (int index) const
Object & GetObjectAt (int index)
I_DWORD GetBackPosition () const
Get front position.
const Object & GetBackObject () const
Get object at the front.
Object & GetBackObject ()
Get object at the front.
int GetBackIndex () const
int GetNextFrontIndex () const
void PopBack ()
Remove front position.
Static Public Member Functions
static int GetPrevIndex (int fifoIndex)
static int GetNextIndex (int fifoIndex)
Detailed Description
template<class Object, int SizeBits = 6>
struct ilolv::TOrderedPositionsQueue< Object, SizeBits >
Definition at line 13 of file TOrderedPositionsQueue.h.
Member Enumeration Documentation
template<class Object, int SizeBits = 6> anonymous enum
Enumerator:
MAX_SIZE
INDEX_MASK
Definition at line 16 of file TOrderedPositionsQueue.h.
Member Function Documentation
template<class Object , int SizeBits> int ilolv::TOrderedPositionsQueue< Object, SizeBits >::FindByPosition (I_DWORD position, int tolerance) const [inline]
Find element in queue using its position.
Definition at line 232 of file TOrderedPositionsQueue.h.
References ilolv::TOrderedPositionsQueue< Object, SizeBits >::GetNextIndex().
template<class Object , int SizeBits> int ilolv::TOrderedPositionsQueue< Object, SizeBits >::GetBackIndex () const [inline]
Definition at line 157 of file TOrderedPositionsQueue.h.
template<class Object , int SizeBits> Object & ilolv::TOrderedPositionsQueue< Object, SizeBits >::GetBackObject () [inline]
Get object at the front.
Definition at line 148 of file TOrderedPositionsQueue.h.
References I_ASSERT, ilolv::TOrderedPositionsQueue< Object, SizeBits >::IsEmpty(), and ilolv::TOrderedPositionsQueue< Object, SizeBits >::Element::object.
template<class Object , int SizeBits> const Object & ilolv::TOrderedPositionsQueue< Object, SizeBits >::GetBackObject () const [inline]
Get object at the front.
Definition at line 139 of file TOrderedPositionsQueue.h.
References I_ASSERT, ilolv::TOrderedPositionsQueue< Object, SizeBits >::IsEmpty(), and ilolv::TOrderedPositionsQueue< Object, SizeBits >::Element::object.
template<class Object , int SizeBits> I_DWORD ilolv::TOrderedPositionsQueue< Object, SizeBits >::GetBackPosition () const [inline]
Get front position.
Definition at line 130 of file TOrderedPositionsQueue.h.
References I_ASSERT, ilolv::TOrderedPositionsQueue< Object, SizeBits >::IsEmpty(), and ilolv::TOrderedPositionsQueue< Object, SizeBits >::Element::position.
template<class Object , int SizeBits> int ilolv::TOrderedPositionsQueue< Object, SizeBits >::GetNextFrontIndex () const [inline]
Definition at line 164 of file TOrderedPositionsQueue.h.
template<class Object , int SizeBits> int ilolv::TOrderedPositionsQueue< Object, SizeBits >::GetNextIndex (int fifoIndex) [inline, static]
Definition at line 189 of file TOrderedPositionsQueue.h.
References ilolv::TOrderedPositionsQueue< Object, SizeBits >::INDEX_MASK.
Referenced by ilolv::TOrderedPositionsQueue< Object, SizeBits >::FindByPosition(), ilolv::TOrderedPositionsQueue< Object, SizeBits >::Insert(), and ilolv::TOrderedPositionsQueue< Object, SizeBits >::PopBack().
template<class Object , int SizeBits> Object & ilolv::TOrderedPositionsQueue< Object, SizeBits >::GetObjectAt (int index) [inline]
Definition at line 123 of file TOrderedPositionsQueue.h.
References ilolv::TOrderedPositionsQueue< Object, SizeBits >::Element::object.
template<class Object , int SizeBits> const Object & ilolv::TOrderedPositionsQueue< Object, SizeBits >::GetObjectAt (int index) const [inline]
Definition at line 116 of file TOrderedPositionsQueue.h.
References ilolv::TOrderedPositionsQueue< Object, SizeBits >::Element::object.
template<class Object , int SizeBits> I_DWORD ilolv::TOrderedPositionsQueue< Object, SizeBits >::GetPositionAt (int index) const [inline]
Definition at line 109 of file TOrderedPositionsQueue.h.
References ilolv::TOrderedPositionsQueue< Object, SizeBits >::Element::position.
template<class Object , int SizeBits> int ilolv::TOrderedPositionsQueue< Object, SizeBits >::GetPrevIndex (int fifoIndex) [inline, static]
Definition at line 182 of file TOrderedPositionsQueue.h.
References ilolv::TOrderedPositionsQueue< Object, SizeBits >::INDEX_MASK.
Referenced by ilolv::TOrderedPositionsQueue< Object, SizeBits >::Insert().
template<class Object, int SizeBits> int ilolv::TOrderedPositionsQueue< Object, SizeBits >::Insert (I_DWORD position, const Object * objectPtr = NULL) [inline]
Insert new position to the queue.
Parameters:
position insertion position. Objects will be automatically sorted.
object inserted object.
Returns:
index or negative value if insertion failed.
Definition at line 198 of file TOrderedPositionsQueue.h.
References ilolv::TOrderedPositionsQueue< Object, SizeBits >::GetNextIndex(), ilolv::TOrderedPositionsQueue< Object, SizeBits >::GetPrevIndex(), NULL, ilolv::TOrderedPositionsQueue< Object, SizeBits >::Element::object, and ilolv::TOrderedPositionsQueue< Object, SizeBits >::Element::position.
template<class Object , int SizeBits> bool ilolv::TOrderedPositionsQueue< Object, SizeBits >::IsEmpty () const [inline]
Check if this queue is empty.
Definition at line 94 of file TOrderedPositionsQueue.h.
Referenced by ilolv::TOrderedPositionsQueue< Object, SizeBits >::GetBackObject(), ilolv::TOrderedPositionsQueue< Object, SizeBits >::GetBackPosition(), and ilolv::TOrderedPositionsQueue< Object, SizeBits >::PopBack().
template<class Object , int SizeBits> void ilolv::TOrderedPositionsQueue< Object, SizeBits >::PopBack () [inline]
Remove front position.
Definition at line 171 of file TOrderedPositionsQueue.h.
References ilolv::TOrderedPositionsQueue< Object, SizeBits >::GetNextIndex(), I_ASSERT, and ilolv::TOrderedPositionsQueue< Object, SizeBits >::IsEmpty().
template<class Object , int SizeBits> void ilolv::TOrderedPositionsQueue< Object, SizeBits >::Reset () [inline]
Remove all elements from this queue.
Definition at line 101 of file TOrderedPositionsQueue.h.
The documentation for this struct was generated from the following file:
E:/Work/Projects/Development/Iacf/Include/ilolv/TOrderedPositionsQueue.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy