Include/icomp/CComponentBase.h File Reference
CComponentBase.h File Reference
#include "istd/CClassInfo.h"
#include "icomp/IComponent.h"
#include "icomp/ICompositeComponent.h"
#include "icomp/IRealComponentStaticInfo.h"
#include "icomp/TInterfaceRegistrator.h"
#include "icomp/TAttribute.h"
#include "icomp/TMultiAttribute.h"
#include "icomp/TAttributeMember.h"
#include "icomp/TMultiAttributeMember.h"
#include "icomp/TReferenceMember.h"
#include "icomp/TMultiReferenceMember.h"
#include "icomp/TFactoryMember.h"
#include "icomp/TMultiFactoryMember.h"
#include "icomp/TAttributeStaticInfo.h"
#include "icomp/TComponentStaticInfo.h"
#include "icomp/TSubelementStaticInfo.h"
#include "icomp/CBaseComponentStaticInfo.h"
#include "icomp/CRelatedInfoRegistrator.h"
Classes
class icomp::CComponentBase
Base class for component implementation.
Namespaces
icomp
Package with interfaces and class used for components concept.
Macros
#define I_REGISTER_SUBELEMENT_INTERFACE_T(ElementName, InterfaceType, extractorFunction)
Register interface extractor for some subelement with template extractor function.
#define I_TFACT(interfaceType, member)
#define I_ASSIGN_BASE(member, id, description, isObligatory)
Used to assign value for single parameter (attribute, reference or factory).
#define I_ASSIGN_MULTI_BASE(member, id, description, isObligatory, defaultValue)
Used to assign value for multiply parameters (attributes, references or factories).
#define I_TASSIGN_BASE(member, id, description, isObligatory)
Used to assign value for single parameter with template type (attribute, reference or factory).
#define I_TASSIGN_MULTI_BASE(member, id, description, isObligatory, defaultValue)
Used to assign value for multiply parameters with template type (attributes, references or factories).
#define I_ASSIGN_TO(member, baseAttribute, isObligatory)
Used to assign value for overloaded attributes or references.
#define I_TASSIGN_TO(member, baseAttribute, isObligatory)
Used to assign value for overloaded attributes or references.
Functions
template<class Dest >
Dest * CompCastPtr (istd::IPolymorphic *objectPtr)
Cast to specified interface trying to use component interface query.
template<class Dest >
const Dest * CompCastPtr (const istd::IPolymorphic *objectPtr)
Cast to specified interface trying to use component interface query.
Macro Definition Documentation
#define I_ASSIGN_BASE (member, id, description, isObligatory)
Value:
static icomp::TAttributeStaticInfo<member##_AttrType> member##_Info(staticInfo, id, description, &member##_Default, isObligatory? member##_AttrType::DAF_OBLIGATORY: member##_AttrType::DAF_OPTIONAL, istd::CClassInfo::GetInfo<member##_Type::InterfaceType>());\
       if (componentPtr != NULL){\
              componentPtr->member.Init(componentPtr, member##_Info);\
       }
Used to assign value for single parameter (attribute, reference or factory).
Definition at line 299 of file CComponentBase.h.
#define I_ASSIGN_MULTI_BASE (member, id, description, isObligatory, defaultValue)
Value:
static member##_AttrType member##_Default(int(sizeof(member##_DefaultElements) / sizeof(member##_AttrType::ValueType)), member##_DefaultElements);\
    I_ASSIGN_BASE(member, id, description, isObligatory)
Used to assign value for multiply parameters (attributes, references or factories).
Definition at line 318 of file CComponentBase.h.
#define I_ASSIGN_TO (member, baseAttribute, isObligatory)
Value:
static icomp::CRelatedInfoRegistrator member##_Info(baseAttribute##_Info, icomp::IComponentStaticInfo::MGI_INTERFACES, istd::CClassInfo::GetInfo<member##_Type::InterfaceType>().GetName(), isObligatory? member##_AttrType::DAF_OBLIGATORY: member##_AttrType::DAF_OPTIONAL);\
       Q_UNUSED(member##_Info);\
       if (componentPtr != NULL){\
              componentPtr->member.Init(componentPtr, baseAttribute##_Info);\
       }
Used to assign value for overloaded attributes or references.
Definition at line 424 of file CComponentBase.h.
#define I_REGISTER_SUBELEMENT_INTERFACE_T (ElementName, InterfaceType, extractorFunction)
Value:
{\
              static icomp::TSubelementStaticInfo<CurrentComponentType>::Registrator<InterfaceType> staticRegistrator(\
                                   subelementInfo_##ElementName,\
                                   extractorFunction<InterfaceType>);\
              Q_UNUSED(staticRegistrator);\
       }
Register interface extractor for some subelement with template extractor function.
Parameters
ElementName name of subelement.
InterfaceType type of registered interface.
extractorFunction function returning pointer to casted type (must be 'InterfaceType* Foo(MyComponent& component)')".
Definition at line 183 of file CComponentBase.h.
#define I_TASSIGN_BASE (member, id, description, isObligatory)
Value:
static icomp::TAttributeStaticInfo<member##_AttrType> member##_Info(staticInfo, id, description, &member##_Default, isObligatory? member##_AttrType::DAF_OBLIGATORY: member##_AttrType::DAF_OPTIONAL, istd::CClassInfo::GetInfo<typename member##_Type::InterfaceType>());\
       if (componentPtr != NULL){\
              componentPtr->member.Init(componentPtr, member##_Info);\
       }
Used to assign value for single parameter with template type (attribute, reference or factory).
Definition at line 372 of file CComponentBase.h.
#define I_TASSIGN_MULTI_BASE (member, id, description, isObligatory, defaultValue)
Value:
static member##_AttrType member##_Default(int(sizeof(member##_DefaultElements) / sizeof(member##_AttrType::ValueType)), member##_DefaultElements);\
    I_TASSIGN_BASE(member, id, description, isObligatory)
Used to assign value for multiply parameters with template type (attributes, references or factories).
Definition at line 388 of file CComponentBase.h.
#define I_TASSIGN_TO (member, baseAttribute, isObligatory)
Value:
static icomp::CRelatedInfoRegistrator member##_Info(baseAttribute##_Info, icomp::IComponentStaticInfo::MGI_INTERFACES, istd::CClassInfo::GetInfo<typename member##_Type::InterfaceType>().GetName(), isObligatory? member##_AttrType::DAF_OBLIGATORY: member##_AttrType::DAF_OPTIONAL);\
       Q_UNUSED(member##_Info);\
       if (componentPtr != NULL){\
              componentPtr->member.Init(componentPtr, baseAttribute##_Info);\
       }
Used to assign value for overloaded attributes or references.
Definition at line 434 of file CComponentBase.h.
#define I_TFACT (interfaceType, member)
Value:
typedef icomp::TFactoryMember<interfaceType> member##_Type;\
       typedef typename icomp::TFactoryMember<interfaceType>::AttributeType member##_AttrType;\
       icomp::TFactoryMember<interfaceType> member;
Definition at line 282 of file CComponentBase.h.
Function Documentation
template<class Dest > Dest* CompCastPtr (istd::IPolymorphic * objectPtr)
Cast to specified interface trying to use component interface query.
It extends standard dynamic_cast functinality when you use composed components.
Definition at line 446 of file CComponentBase.h.
References icomp::IComponent::GetInterface(), icomp::IComponent::GetParentComponent(), and NULL.
template<class Dest > const Dest* CompCastPtr (const istd::IPolymorphic * objectPtr)
Cast to specified interface trying to use component interface query.
It extends standard dynamic_cast functinality when you use composed components. This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 471 of file CComponentBase.h.
References icomp::IComponent::GetInterface(), icomp::IComponent::GetParentComponent(), and NULL.
© 2007-2011 Witold Gantzke and Kirill Lepskiy