ACF: C:/Temp/Acf/Include/icomp/TReferenceMember.h File Reference
C:/Temp/Acf/Include/icomp/TReferenceMember.h File Reference
#include "icomp/TAttributeMember.h"
#include "icomp/CInterfaceManipBase.h"
#include "icomp/CReferenceAttribute.h"
Classes
class icomp::TReferenceMember< Interface >
Pointer to referenced component object.
Namespaces
namespace icomp
Package with interfaces and class used for components concept.
Functions
void operator* (const icomp::TReferenceMember< void > &)
template<class Interface >
Interface & operator* (const icomp::TReferenceMember< Interface > &ref)
Function Documentation
void operator* (const icomp::TReferenceMember< void > &) [inline]
Definition at line 142 of file TReferenceMember.h.
Referenced by icomp::TFactoryMember< Interface >::CreateComponent(), and icomp::TReferenceMember< Interface >::EnsureInitialized().
template<class Interface > Interface& operator* (const icomp::TReferenceMember< Interface > & ref) [inline]
Definition at line 148 of file TReferenceMember.h.
References icomp::TReferenceMember< Interface >::GetPtr().
© 2007-2011 Witold Gantzke and Kirill Lepskiy