ACF: imath::TMatrix< Width, Height, Element > Class Template Reference
imath::TMatrix< Width, Height, Element > Class Template Reference
Definition of mathematical matrix with fixed dimensions.
#include <TMatrix.h>
Public Types
enum MatrixInitMode {
MIM_ZERO, MIM_ONES, MIM_IDENTITY, MIM_UPPER_TRIANGLE,
MIM_DOWNER_TRIANLE
}
typedef istd::CIndex2d IndexType
typedef istd::CIndex2d SizesType
typedef Element ElementType
Public Member Functions
TMatrix ()
Create matrix without initialization.
TMatrix (MatrixInitMode mode)
Create matrix with initialization to some specified one.
TMatrix (const TMatrix &matrix)
Copy constructor.
void Reset ()
Set all matrix cells to zero.
void Clear ()
Set all matrix cells to zero.
bool IsDimensionsCountFixed () const
Check, if number dimensions is fixed.
int GetDimensionsCount () const
Get number of dimensions of this array.
bool SetDimensionsCount (int count)
Set number of dimensions of this array.
const SizesType & GetSizes () const
Get list of all sizes.
bool SetSizes (const SizesType &sizes)
Set list of all sizes.
int GetSize (int dimension) const
Get size of array for specified dimension.
bool SetSize (int dimension, int size)
Set size of array for specified dimension.
const ElementType & GetAt (const IndexType &index) const
Get element stored at specified index.
const ElementType & GetAt (int x, int y) const
Get element stored at specified index.
ElementType & GetAtRef (const IndexType &index)
Get reference to element stored at specified index.
ElementType & GetAtRef (int x, int y)
Get reference to element stored at specified index.
void SetAt (const IndexType &index, const ElementType &value)
Set element at specified index.
void SetAt (int x, int y, const ElementType &value)
Set element at specified index.
void InitToIdentity ()
Create identity matrix.
double GetMaxElement () const
double GetMinElement () const
void GetNegated (TMatrix< Width, Height, Element > &result)
Get result matrix with negated all elements.
void GetAdded (const TMatrix< Width, Height, Element > &matrix, TMatrix< Width, Height, Element > &result) const
Get sum of two matrices.
void GetSubstracted (const TMatrix< Width, Height, Element > &matrix, TMatrix< Width, Height, Element > &result) const
Get result of substraction of two matrices.
template<int SecondWidth>
void GetMultiplied (const TMatrix< SecondWidth, Width, Element > &matrix, TMatrix< SecondWidth, Height, Element > &result) const
Get result of multiplication of two matrices.
template<int SecondWidth>
TMatrix< SecondWidth, Height,
Element > GetMultiplied (const TMatrix< SecondWidth, Width, Element > &matrix) const
Get result of multiplication of two matrices.
void GetMultiplied (const TVector< Width, Element > &vector, TVector< Height, Element > &result) const
Get result of multiplication of this matrix and some vector.
TVector< Height, Element > GetMultiplied (const TVector< Width, Element > &vector) const
Get result of multiplication of this matrix and some vector.
void GetScaled (double value, TMatrix< Width, Height, Element > &result) const
Get result of multiplication of this matrix with scalar value.
void GetTransposed (TMatrix< Height, Width, Element > &result) const
Get transposed matrix.
TMatrix< Height, Width, Element > GetTransposed () const
Get transposed matrix.
void Transpose ()
Transpose matrix.
double GetFrobeniusNorm2 () const
double GetFrobeniusNorm () const
bool GetTriangleDecomposed (TMatrix< Width, Height, Element > &result, TMatrix< Height, Height, Element > *matrixQPtr=NULL, int maxColumns=-1, double minHhNorm=I_BIG_EPSILON) const
Transform matrix to upper triangle form using method of Householder reflexions.
void GetColumnVector (int columnIndex, TVector< Height, Element > &result)
Get single column as vector.
void GetRowVector (int rowIndex, TVector< Width, Element > &result)
Get single row as vector.
bool Serialize (iser::IArchive &archive)
TMatrix< Width, Height, Element > operator+ (const TMatrix< Width, Height, Element > &b) const
TMatrix< Width, Height, Element > operator- (const TMatrix< Width, Height, Element > &b) const
TMatrix< Width, Height, Element > operator- ()
template<int SecondWidth>
TMatrix< SecondWidth, Height,
Element > operator* (const TMatrix< SecondWidth, Width, Element > &b) const
TMatrix< Width, Height, Element > operator* (double value) const
bool operator== (const TMatrix< Width, Height, Element > &matrix) const
bool operator!= (const TMatrix< Width, Height, Element > &matrix) const
const ElementType & operator[] (const IndexType &index) const
ElementType & operator[] (const IndexType &index)
Detailed Description
template<int Width, int Height, typename Element = double>
class imath::TMatrix< Width, Height, Element >
Definition of mathematical matrix with fixed dimensions.
Definition at line 27 of file TMatrix.h.
Member Typedef Documentation
template<int Width, int Height, typename Element = double> typedef Element imath::TMatrix< Width, Height, Element >::ElementType
Definition at line 32 of file TMatrix.h.
template<int Width, int Height, typename Element = double> typedef istd::CIndex2d imath::TMatrix< Width, Height, Element >::IndexType
Definition at line 30 of file TMatrix.h.
template<int Width, int Height, typename Element = double> typedef istd::CIndex2d imath::TMatrix< Width, Height, Element >::SizesType
Definition at line 31 of file TMatrix.h.
Member Enumeration Documentation
template<int Width, int Height, typename Element = double> enum imath::TMatrix::MatrixInitMode
Enumerator:
MIM_ZERO All elements initialized to 0.
MIM_ONES All elements initialized to 1.
MIM_IDENTITY Identity matrix.
MIM_UPPER_TRIANGLE Upper triangle matrix.
MIM_DOWNER_TRIANLE Downer triangle matrix.
Definition at line 34 of file TMatrix.h.
Constructor & Destructor Documentation
template<int Width, int Height, typename Element > imath::TMatrix< Width, Height, Element >::TMatrix () [inline]
Create matrix without initialization.
Definition at line 404 of file TMatrix.h.
template<int Width, int Height, typename Element > imath::TMatrix< Width, Height, Element >::TMatrix (MatrixInitMode mode) [inline]
Create matrix with initialization to some specified one.
Definition at line 410 of file TMatrix.h.
References imath::TMatrix< Width, Height, Element >::MIM_IDENTITY, imath::TMatrix< Width, Height, Element >::MIM_ONES, imath::TMatrix< Width, Height, Element >::MIM_UPPER_TRIANGLE, and imath::TMatrix< Width, Height, Element >::MIM_ZERO.
template<int Width, int Height, typename Element > imath::TMatrix< Width, Height, Element >::TMatrix (const TMatrix< Width, Height, Element > & matrix) [inline]
Copy constructor.
Definition at line 472 of file TMatrix.h.
Member Function Documentation
template<int Width, int Height, typename Element > void imath::TMatrix< Width, Height, Element >::Clear () [inline]
Set all matrix cells to zero.
It makes the same as Reset() and is used for compatibility with other matrix implementations.
Definition at line 496 of file TMatrix.h.
References imath::TMatrix< Width, Height, Element >::Reset().
template<int Width, int Height, typename Element> void imath::TMatrix< Width, Height, Element >::GetAdded (const TMatrix< Width, Height, Element > & matrix, TMatrix< Width, Height, Element > & result) const [inline]
Get sum of two matrices.
Definition at line 682 of file TMatrix.h.
Referenced by imath::TMatrix< Width, Height, Element >::operator+().
template<int Width, int Height, typename Element > const TMatrix< Width, Height, Element >::ElementType & imath::TMatrix< Width, Height, Element >::GetAt (int x, int y) const [inline]
Get element stored at specified index.
Definition at line 582 of file TMatrix.h.
template<int Width, int Height, typename Element > const TMatrix< Width, Height, Element >::ElementType & imath::TMatrix< Width, Height, Element >::GetAt (const IndexType & index) const [inline]
Get element stored at specified index.
Definition at line 575 of file TMatrix.h.
Referenced by imath::TMatrix< Width, Height, Element >::GetTriangleDecomposed().
template<int Width, int Height, typename Element > TMatrix< Width, Height, Element >::ElementType & imath::TMatrix< Width, Height, Element >::GetAtRef (int x, int y) [inline]
Get reference to element stored at specified index.
Definition at line 596 of file TMatrix.h.
template<int Width, int Height, typename Element > TMatrix< Width, Height, Element >::ElementType & imath::TMatrix< Width, Height, Element >::GetAtRef (const IndexType & index) [inline]
Get reference to element stored at specified index.
Definition at line 589 of file TMatrix.h.
Referenced by imath::TMatrix< Width, Height, Element >::GetTriangleDecomposed().
template<int Width, int Height, typename Element> void imath::TMatrix< Width, Height, Element >::GetColumnVector (int columnIndex, TVector< Height, Element > & result) [inline]
Get single column as vector.
Definition at line 762 of file TMatrix.h.
References I_ASSERT.
template<int Width, int Height, typename Element > int imath::TMatrix< Width, Height, Element >::GetDimensionsCount () const [inline]
Get number of dimensions of this array.
It is provided for template implementations. It returns always 2.
Definition at line 510 of file TMatrix.h.
template<int Width, int Height, typename Element > double imath::TMatrix< Width, Height, Element >::GetFrobeniusNorm () const [inline]
Definition at line 755 of file TMatrix.h.
References imath::TMatrix< Width, Height, Element >::GetFrobeniusNorm2().
template<int Width, int Height, typename Element > double imath::TMatrix< Width, Height, Element >::GetFrobeniusNorm2 () const [inline]
Definition at line 740 of file TMatrix.h.
Referenced by imath::TMatrix< Width, Height, Element >::GetFrobeniusNorm().
template<int Width, int Height, typename Element > double imath::TMatrix< Width, Height, Element >::GetMaxElement () const [inline]
Definition at line 633 of file TMatrix.h.
template<int Width, int Height, typename Element > double imath::TMatrix< Width, Height, Element >::GetMinElement () const [inline]
Definition at line 652 of file TMatrix.h.
template<int Width, int Height, typename Element> TVector< Height, Element > imath::TMatrix< Width, Height, Element >::GetMultiplied (const TVector< Width, Element > & vector) const [inline]
Get result of multiplication of this matrix and some vector.
Definition at line 340 of file TMatrix.h.
References imath::TMatrix< Width, Height, Element >::GetMultiplied().
template<int Width, int Height, typename Element> void imath::TMatrix< Width, Height, Element >::GetMultiplied (const TVector< Width, Element > & vector, TVector< Height, Element > & result) const [inline]
Get result of multiplication of this matrix and some vector.
Definition at line 704 of file TMatrix.h.
template<int Width, int Height, typename Element = double> template<int SecondWidth> TMatrix<SecondWidth, Height, Element> imath::TMatrix< Width, Height, Element >::GetMultiplied (const TMatrix< SecondWidth, Width, Element > & matrix) const [inline]
Get result of multiplication of two matrices.
Definition at line 211 of file TMatrix.h.
template<int Width, int Height, typename Element = double> template<int SecondWidth> void imath::TMatrix< Width, Height, Element >::GetMultiplied (const TMatrix< SecondWidth, Width, Element > & matrix, TMatrix< SecondWidth, Height, Element > & result) const [inline]
Get result of multiplication of two matrices.
Definition at line 193 of file TMatrix.h.
Referenced by imath::TMatrix< Width, Height, Element >::GetMultiplied(), imath::TMatrix< 2, 2 >::GetMultiplied(), and imath::TMatrix< 2, 2 >::operator*().
template<int Width, int Height, typename Element> void imath::TMatrix< Width, Height, Element >::GetNegated (TMatrix< Width, Height, Element > & result) [inline]
Get result matrix with negated all elements.
Definition at line 671 of file TMatrix.h.
Referenced by imath::TMatrix< Width, Height, Element >::operator-().
template<int Width, int Height, typename Element> void imath::TMatrix< Width, Height, Element >::GetRowVector (int rowIndex, TVector< Width, Element > & result) [inline]
Get single row as vector.
Definition at line 773 of file TMatrix.h.
References I_ASSERT.
template<int Width, int Height, typename Element> void imath::TMatrix< Width, Height, Element >::GetScaled (double value, TMatrix< Width, Height, Element > & result) const [inline]
Get result of multiplication of this matrix with scalar value.
Definition at line 718 of file TMatrix.h.
Referenced by imath::TMatrix< Width, Height, Element >::operator*().
template<int Width, int Height, typename Element > int imath::TMatrix< Width, Height, Element >::GetSize (int dimension) const [inline]
Get size of array for specified dimension.
Definition at line 543 of file TMatrix.h.
template<int Width, int Height, typename Element > const TMatrix< Width, Height, Element >::SizesType & imath::TMatrix< Width, Height, Element >::GetSizes () const [inline]
Get list of all sizes.
Definition at line 524 of file TMatrix.h.
template<int Width, int Height, typename Element> void imath::TMatrix< Width, Height, Element >::GetSubstracted (const TMatrix< Width, Height, Element > & matrix, TMatrix< Width, Height, Element > & result) const [inline]
Get result of substraction of two matrices.
Definition at line 693 of file TMatrix.h.
Referenced by imath::TMatrix< Width, Height, Element >::operator-().
template<int Width, int Height, typename Element> TMatrix< Height, Width, Element > imath::TMatrix< Width, Height, Element >::GetTransposed () const [inline]
Get transposed matrix.
Definition at line 318 of file TMatrix.h.
Referenced by imath::TMatrix< Width, Height, Element >::Transpose().
template<int Width, int Height, typename Element> void imath::TMatrix< Width, Height, Element >::GetTransposed (TMatrix< Height, Width, Element > & result) const [inline]
Get transposed matrix.
Definition at line 729 of file TMatrix.h.
template<int Width, int Height, typename Element> bool imath::TMatrix< Width, Height, Element >::GetTriangleDecomposed (TMatrix< Width, Height, Element > & result, TMatrix< Height, Height, Element > * matrixQPtr = NULL, int maxColumns = -1, double minHhNorm = I_BIG_EPSILON) const [inline]
Transform matrix to upper triangle form using method of Householder reflexions.
Parameters:
result triangle matrix.
matrix2Ptr optional matrix will be transformed using the same reflexions. To realize QR decomposition you can use identity matrix.
maxColumns optional maximal number of transformed columns. If it is negative value whole matrix will be transformed.
minHhNorm minimal Hausholder reflexion vector length. If any reflexion vector is shorter this method fails.
Returns:
true if success.
Definition at line 784 of file TMatrix.h.
References imath::TMatrix< Width, Height, Element >::GetAt(), imath::TMatrix< Width, Height, Element >::GetAtRef(), istd::Min(), NULL, and imath::TMatrix< Width, Height, Element >::SetAt().
template<int Width, int Height, typename Element > void imath::TMatrix< Width, Height, Element >::InitToIdentity () [inline]
Create identity matrix.
Definition at line 617 of file TMatrix.h.
template<int Width, int Height, typename Element > bool imath::TMatrix< Width, Height, Element >::IsDimensionsCountFixed () const [inline]
Check, if number dimensions is fixed.
It is provided for template implementations. It returns always true.
Definition at line 503 of file TMatrix.h.
template<int Width, int Height, typename Element> bool imath::TMatrix< Width, Height, Element >::operator!= (const TMatrix< Width, Height, Element > & matrix) const [inline]
Definition at line 923 of file TMatrix.h.
template<int Width, int Height, typename Element > TMatrix< Width, Height, Element > imath::TMatrix< Width, Height, Element >::operator* (double value) const [inline]
Reimplemented in i2d::CMatrix2d.
Definition at line 384 of file TMatrix.h.
References imath::TMatrix< Width, Height, Element >::GetScaled().
template<int Width, int Height, typename Element = double> template<int SecondWidth> TMatrix<SecondWidth, Height, Element> imath::TMatrix< Width, Height, Element >::operator* (const TMatrix< SecondWidth, Width, Element > & b) const [inline]
Definition at line 291 of file TMatrix.h.
template<int Width, int Height, typename Element> TMatrix< Width, Height, Element > imath::TMatrix< Width, Height, Element >::operator+ (const TMatrix< Width, Height, Element > & b) const [inline]
Definition at line 351 of file TMatrix.h.
References imath::TMatrix< Width, Height, Element >::GetAdded().
template<int Width, int Height, typename Element> TMatrix< Width, Height, Element > imath::TMatrix< Width, Height, Element >::operator- () [inline]
Definition at line 373 of file TMatrix.h.
References imath::TMatrix< Width, Height, Element >::GetNegated().
template<int Width, int Height, typename Element> TMatrix< Width, Height, Element > imath::TMatrix< Width, Height, Element >::operator- (const TMatrix< Width, Height, Element > & b) const [inline]
Definition at line 362 of file TMatrix.h.
References imath::TMatrix< Width, Height, Element >::GetSubstracted().
template<int Width, int Height, typename Element> bool imath::TMatrix< Width, Height, Element >::operator== (const TMatrix< Width, Height, Element > & matrix) const [inline]
Definition at line 908 of file TMatrix.h.
template<int Width, int Height, typename Element > TMatrix< Width, Height, Element >::ElementType & imath::TMatrix< Width, Height, Element >::operator[] (const IndexType & index) [inline]
Definition at line 945 of file TMatrix.h.
template<int Width, int Height, typename Element > const TMatrix< Width, Height, Element >::ElementType & imath::TMatrix< Width, Height, Element >::operator[] (const IndexType & index) const [inline]
Definition at line 938 of file TMatrix.h.
template<int Width, int Height, typename Element > void imath::TMatrix< Width, Height, Element >::Reset () [inline]
Set all matrix cells to zero.
It makes the same as Clear() and is used for compatibility with other matrix implementations.
Definition at line 485 of file TMatrix.h.
Referenced by imath::TMatrix< Width, Height, Element >::Clear().
template<int Width, int Height, typename Element > bool imath::TMatrix< Width, Height, Element >::Serialize (iser::IArchive & archive) [inline]
Definition at line 866 of file TMatrix.h.
References iser::IArchive::BeginTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), and iser::IArchive::Process().
template<int Width, int Height, typename Element > void imath::TMatrix< Width, Height, Element >::SetAt (int x, int y, const ElementType & value) [inline]
Set element at specified index.
Definition at line 610 of file TMatrix.h.
template<int Width, int Height, typename Element > void imath::TMatrix< Width, Height, Element >::SetAt (const IndexType & index, const ElementType & value) [inline]
Set element at specified index.
Definition at line 603 of file TMatrix.h.
Referenced by imath::TMatrix< Width, Height, Element >::GetTriangleDecomposed().
template<int Width, int Height, typename Element > bool imath::TMatrix< Width, Height, Element >::SetDimensionsCount (int count) [inline]
Set number of dimensions of this array.
This is only dummy method, to provide methods compatibility with template implementations.
Parameters:
count number of dimensions will be set.
Returns:
true, if number of set dimensions equals 2, or false if isn't.
Definition at line 517 of file TMatrix.h.
template<int Width, int Height, typename Element > bool imath::TMatrix< Width, Height, Element >::SetSize (int dimension, int size) [inline]
Set size of array for specified dimension.
This is only dummy method, to provide methods compatibility with template implementations.
Returns:
true, if set dimension equals the template parameter, or false if isn't.
Definition at line 559 of file TMatrix.h.
template<int Width, int Height, typename Element > bool imath::TMatrix< Width, Height, Element >::SetSizes (const SizesType & sizes) [inline]
Set list of all sizes.
This is only dummy method, to provide methods compatibility with template implementations.
Returns:
true, if set dimensions equals the template parameters, or false if isn't.
Definition at line 536 of file TMatrix.h.
template<int Width, int Height, typename Element > void imath::TMatrix< Width, Height, Element >::Transpose () [inline]
Transpose matrix.
Definition at line 329 of file TMatrix.h.
References imath::TMatrix< Width, Height, Element >::GetTransposed().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/imath/TMatrix.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy