ACF: istd::CRange Class Reference
istd::CRange Class Reference
Main concepts and implementations
Implementation of a abstract range defined by two values - minimum and maximum.
#include <CRange.h>
Public Member Functions
CRange ()
Constructs an empty range object.
CRange (const CRange &range)
Copy constructor.
CRange (double minValue, double topValue)
Constructs a range object from two numbers.
bool IsValid () const
Return true if the bottom value is smaller or equal then the top value.
bool IsEmpty () const
Return true if the bottom value is equal to the top value.
double GetMinValue () const
Get the bottom value.
double & GetMinValueRef ()
Get reference to the bottom value.
void SetMinValue (double minValue)
Set the bottom value.
double GetMaxValue () const
Get the top value.
double & GetMaxValueRef ()
Get reference to the top value.
void SetMaxValue (double topValue)
Set the top value.
void Reset ()
Set this range to be empty.
double GetLength () const
Get length of this range.
CRange GetValidated () const
Get validated range, if it was invalid.
void GetValidated (CRange &result) const
Get validated range, if it was invalid.
void Validate ()
Force this range to be valid.
bool Contains (double value) const
Returns true, if value is in range between top and bottom.
bool Contains (const CRange &range) const
Returns true, if this range is inside of the range.
bool IsIntersectedBy (const CRange &range) const
Check if this range is intersected by other range.
CRange GetIntersection (const CRange &range) const
Get intersection with the second range.
void Intersection (const CRange &range)
Set this range to be intersection of two ranges.
CRange GetUnion (const CRange &range) const
Get union with the second range.
CRange GetUnion (double value) const
Get union with the second range.
void Unite (const CRange &range)
Set this range to be union of two ranges.
void Unite (double value)
Set this range to be union of two ranges.
CRange GetExpanded (const CRange &range) const
Get expanded range using the second range.
void Expand (const CRange &range)
Set this range to be expanded.
double GetNearestInside (double value) const
Get nearest value belonging to range.
double GetClipped (double value) const
Get value clipped to the range.
istd::CRange GetClipped (const istd::CRange &range) const
Get range clipped to the current range.
double GetValueFromAlpha (double alpha) const
Get value based on 'alpha' factor.
double GetAlphaFromValue (double value) const
Get value based on 'alpha' factor.
double GetMappedTo (double value, const istd::CRange &range) const
Returns the value, that corresponds the input value inputValue in the other range range.
CRange & operator= (const CRange &range)
bool operator== (const CRange &range) const
bool operator!= (const CRange &range) const
Static Public Member Functions
static const CRange & GetNull ()
Return null range.
static const CRange & GetInvalid ()
Return invalid range.
static CRange GetValid (double value1, double value2)
Return always valid range.
Detailed Description
Implementation of a abstract range defined by two values - minimum and maximum.
Definition at line 17 of file CRange.h.
Constructor & Destructor Documentation
istd::CRange::CRange ()
Constructs an empty range object.
IsEmpty() will return true for this object.
istd::CRange::CRange (const CRange & range)
Copy constructor.
istd::CRange::CRange (double minValue, double topValue)
Constructs a range object from two numbers.
Member Function Documentation
bool istd::CRange::Contains (double value) const [inline]
Returns true, if value is in range between top and bottom.
This range must be valid.
Definition at line 275 of file CRange.h.
References I_ASSERT, and IsValid().
bool istd::CRange::Contains (const CRange & range) const [inline]
Returns true, if this range is inside of the range.
Definition at line 283 of file CRange.h.
References I_ASSERT, and IsValid().
void istd::CRange::Expand (const CRange & range)
Set this range to be expanded.
Expanding operation calculate simple sum for each components separately.
double istd::CRange::GetAlphaFromValue (double value) const [inline]
Get value based on 'alpha' factor.
Parameters:
alpha alpha factor. If it is 0, minimum range value will be returned. If it is 1, maximum range value will be returned. Rest values are linear interpolated.
Definition at line 298 of file CRange.h.
References GetLength(), and GetMinValue().
double istd::CRange::GetClipped (double value) const
Get value clipped to the range.
istd::CRange istd::CRange::GetClipped (const istd::CRange & range) const
Get range clipped to the current range.
CRange istd::CRange::GetExpanded (const CRange & range) const
Get expanded range using the second range.
Expanding operation calculate simple sum for each components separately.
CRange istd::CRange::GetIntersection (const CRange & range) const
Get intersection with the second range.
const CRange & istd::CRange::GetInvalid () [inline, static]
Return invalid range.
Definition at line 324 of file CRange.h.
double istd::CRange::GetLength () const [inline]
Get length of this range.
Length is difference between top and bottom values.
Definition at line 269 of file CRange.h.
References IsValid().
Referenced by GetAlphaFromValue(), and GetValueFromAlpha().
double istd::CRange::GetMappedTo (double value, const istd::CRange & range) const
Returns the value, that corresponds the input value inputValue in the other range range.
It is the same as range.GetValueFromAlpha(GetAlphaFromValue(value)).
Parameters:
value value definde in this range. If it is equal to minimum value in this range, it will be mapped to minimum value of range. If it is equal to maximum value in this range, it will be mapped to maximum value of range. Rest values are linear interpolated.
Note:
This value must be in current range.
double istd::CRange::GetMaxValue () const [inline]
Get the top value.
Definition at line 257 of file CRange.h.
Referenced by i2d::CRectangle::GetBottom(), and i2d::CRectangle::GetRight().
double & istd::CRange::GetMaxValueRef () [inline]
Get reference to the top value.
Definition at line 263 of file CRange.h.
double istd::CRange::GetMinValue () const [inline]
Get the bottom value.
Definition at line 245 of file CRange.h.
Referenced by GetAlphaFromValue(), i2d::CRectangle::GetLeft(), i2d::CRectangle::GetTop(), and GetValueFromAlpha().
double & istd::CRange::GetMinValueRef () [inline]
Get reference to the bottom value.
Definition at line 251 of file CRange.h.
double istd::CRange::GetNearestInside (double value) const
Get nearest value belonging to range.
const CRange & istd::CRange::GetNull () [inline, static]
Return null range.
Definition at line 318 of file CRange.h.
CRange istd::CRange::GetUnion (const CRange & range) const
Get union with the second range.
CRange istd::CRange::GetUnion (double value) const
Get union with the second range.
static CRange istd::CRange::GetValid (double value1, double value2) [static]
Return always valid range.
CRange istd::CRange::GetValidated () const
Get validated range, if it was invalid.
Range is invalid if set min value is bigger than set max value. It returns range with smaller range value as minimum and bigger one as maximum.
void istd::CRange::GetValidated (CRange & result) const
Get validated range, if it was invalid.
Range is invalid if set min value is bigger than set max value. It returns range with smaller range value as minimum and bigger one as maximum.
double istd::CRange::GetValueFromAlpha (double alpha) const [inline]
Get value based on 'alpha' factor.
Parameters:
alpha alpha factor. If it is 0, minimum range value will be returned. If it is 1, maximum range value will be returned. Rest values are linear interpolated.
Definition at line 292 of file CRange.h.
References GetLength(), and GetMinValue().
void istd::CRange::Intersection (const CRange & range)
Set this range to be intersection of two ranges.
bool istd::CRange::IsEmpty () const [inline]
Return true if the bottom value is equal to the top value.
Definition at line 239 of file CRange.h.
bool istd::CRange::IsIntersectedBy (const CRange & range) const
Check if this range is intersected by other range.
Some range is intersected by another, if intercestion of this two ranges is not empty.
bool istd::CRange::IsValid () const [inline]
Return true if the bottom value is smaller or equal then the top value.
Definition at line 233 of file CRange.h.
Referenced by Contains(), and GetLength().
bool istd::CRange::operator!= (const CRange & range) const [inline]
Definition at line 310 of file CRange.h.
CRange& istd::CRange::operator= (const CRange & range)
bool istd::CRange::operator== (const CRange & range) const [inline]
Definition at line 304 of file CRange.h.
void istd::CRange::Reset ()
Set this range to be empty.
void istd::CRange::SetMaxValue (double topValue)
Set the top value.
void istd::CRange::SetMinValue (double minValue)
Set the bottom value.
void istd::CRange::Unite (const CRange & range)
Set this range to be union of two ranges.
void istd::CRange::Unite (double value)
Set this range to be union of two ranges.
void istd::CRange::Validate ()
Force this range to be valid.
Range is invalid if set min value is bigger than set max value. It set smaller range value as minimum and bigger one as maximum.
The documentation for this class was generated from the following file:
C:/Temp/Acf/Include/istd/CRange.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy