ifile::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx Class Reference
ifile::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx Class Reference
#include <TFileSerializerComp.h>
Public Types
typedef ReadArchive BaseClass
Public Member Functions
ReadArchiveEx (const QString &filePath, const TFileSerializerComp *loggerPtr)
Protected Member Functions
virtual bool IsLogConsumed (const istd::IInformationProvider::InformationCategory *, const int *flagsPtr=NULL) const
virtual bool SendLogMessage (istd::IInformationProvider::InformationCategory category, int id, const QString &message, const QString &messageSource, int flags=0) const
Detailed Description
template<class ReadArchive, class WriteArchive>
class ifile::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx
Definition at line 38 of file TFileSerializerComp.h.
Member Typedef Documentation
template<class ReadArchive , class WriteArchive > typedef ReadArchive ifile::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx::BaseClass
Definition at line 41 of file TFileSerializerComp.h.
Constructor & Destructor Documentation
template<class ReadArchive , class WriteArchive > ifile::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx::ReadArchiveEx (const QString & filePath, const TFileSerializerComp * loggerPtr) [inline]
Definition at line 43 of file TFileSerializerComp.h.
Member Function Documentation
template<class ReadArchive , class WriteArchive > virtual bool ifile::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx::IsLogConsumed (const istd::IInformationProvider::InformationCategory * , const int * flagsPtr = NULL) const [inline, protected, virtual]
Definition at line 51 of file TFileSerializerComp.h.
References istd::IInformationProvider::IC_INFO, ilog::TLoggerWrap< Base >::IsLogConsumed(), and NULL.
template<class ReadArchive , class WriteArchive > virtual bool ifile::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx::SendLogMessage (istd::IInformationProvider::InformationCategory category, int id, const QString & message, const QString & messageSource, int flags = 0) const [inline, protected, virtual]
Definition at line 59 of file TFileSerializerComp.h.
References ilog::TLoggerCompWrap< CFileTypeInfoComp >::DecorateMessage(), istd::IInformationProvider::IC_INFO, NULL, and ilog::TLoggerWrap< Base >::SendLogMessage().
The documentation for this class was generated from the following file:
Include/ifile/TFileSerializerComp.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy