ACF: iimg::TBitmapIterator< PixelType > Class Template Reference
iimg::TBitmapIterator< PixelType > Class Template Reference
Simple iterator for dimensionless iteration through bitmap pixels.
#include <TBitmapIterator.h>
Public Types
typedef TPixelAccessor< PixelType > PixelAccessor
typedef PixelType ValueType
Public Member Functions
TBitmapIterator (const iimg::IBitmap *bitmapPtr, const i2d::CRectangle *regionPtr=NULL)
Construct image iterator from a bitmap.
TBitmapIterator (const TBitmapIterator &iterator)
Construct image iterator from another interator.
const PixelAccessor & operator* () const
Access operator.
PixelAccessor & operator* ()
bool operator< (const TBitmapIterator &iterator)
bool operator> (const TBitmapIterator &iterator)
bool operator== (const TBitmapIterator &iterator)
TBitmapIterator operator++ (int)
TBitmapIterator & operator++ ()
TBitmapIterator operator-- (int)
TBitmapIterator & operator-- ()
TBitmapIterator & operator+= (int difference)
TBitmapIterator & operator-= (int difference)
TBitmapIterator operator+ (int difference) const
TBitmapIterator operator- (int difference) const
bool IsValid () const
Returns true if the index is valid in the image domain.
bool AtEnd () const
Returns true, if the index is out of the iteration boundaries.
void MoveTo (int x, int y)
Move iterator to the position (x, y).
void MoveTo (const istd::CIndex2d &index)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Detailed Description
template<typename PixelType>
class iimg::TBitmapIterator< PixelType >
Simple iterator for dimensionless iteration through bitmap pixels.
Definition at line 19 of file TBitmapIterator.h.
Member Typedef Documentation
template<typename PixelType> typedef TPixelAccessor<PixelType> iimg::TBitmapIterator< PixelType >::PixelAccessor
Definition at line 22 of file TBitmapIterator.h.
template<typename PixelType> typedef PixelType iimg::TBitmapIterator< PixelType >::ValueType
Definition at line 23 of file TBitmapIterator.h.
Constructor & Destructor Documentation
template<typename PixelType > iimg::TBitmapIterator< PixelType >::TBitmapIterator (const iimg::IBitmap * bitmapPtr, const i2d::CRectangle * regionPtr = NULL) [inline]
Construct image iterator from a bitmap.
Definition at line 92 of file TBitmapIterator.h.
References iimg::IRasterImage::GetImageSize(), i2d::CRectangle::GetIntersection(), iimg::IBitmap::GetLinePtr(), iimg::IBitmap::GetLinesDifference(), iimg::IBitmap::GetPixelBitsCount(), istd::CIndex2d::GetY(), I_ASSERT, and NULL.
template<typename PixelType > iimg::TBitmapIterator< PixelType >::TBitmapIterator (const TBitmapIterator< PixelType > & iterator) [inline]
Construct image iterator from another interator.
Definition at line 117 of file TBitmapIterator.h.
Member Function Documentation
template<typename PixelType > bool iimg::TBitmapIterator< PixelType >::AtEnd () const [inline]
Returns true, if the index is out of the iteration boundaries.
Definition at line 160 of file TBitmapIterator.h.
template<typename PixelType > bool iimg::TBitmapIterator< PixelType >::IsValid () const [inline]
Returns true if the index is valid in the image domain.
Definition at line 152 of file TBitmapIterator.h.
Referenced by iimg::TBitmapIterator< PixelType >::operator*().
template<typename PixelType > void iimg::TBitmapIterator< PixelType >::MoveTo (const istd::CIndex2d & index) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 174 of file TBitmapIterator.h.
References istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), and iimg::TBitmapIterator< PixelType >::MoveTo().
template<typename PixelType > void iimg::TBitmapIterator< PixelType >::MoveTo (int x, int y) [inline]
Move iterator to the position (x, y).
Definition at line 167 of file TBitmapIterator.h.
Referenced by iimg::TBitmapIterator< PixelType >::MoveTo().
template<typename PixelType > TBitmapIterator< PixelType >::PixelAccessor & iimg::TBitmapIterator< PixelType >::operator* () [inline]
Definition at line 141 of file TBitmapIterator.h.
References I_ASSERT, iimg::TBitmapIterator< PixelType >::IsValid(), and iimg::TPixelAccessor< PixelType >::SetPixelBuffer().
template<typename PixelType > const TBitmapIterator< PixelType >::PixelAccessor & iimg::TBitmapIterator< PixelType >::operator* () const [inline]
Access operator.
Definition at line 131 of file TBitmapIterator.h.
References I_ASSERT, iimg::TBitmapIterator< PixelType >::IsValid(), and iimg::TPixelAccessor< PixelType >::SetPixelBuffer().
template<typename PixelType > TBitmapIterator< PixelType > iimg::TBitmapIterator< PixelType >::operator+ (int difference) const [inline]
Definition at line 277 of file TBitmapIterator.h.
template<typename PixelType > TBitmapIterator< PixelType > & iimg::TBitmapIterator< PixelType >::operator++ () [inline]
Definition at line 219 of file TBitmapIterator.h.
template<typename PixelType > TBitmapIterator< PixelType > iimg::TBitmapIterator< PixelType >::operator++ (int) [inline]
Definition at line 208 of file TBitmapIterator.h.
template<typename PixelType > TBitmapIterator< PixelType > & iimg::TBitmapIterator< PixelType >::operator+= (int difference) [inline]
Definition at line 248 of file TBitmapIterator.h.
template<typename PixelType > TBitmapIterator< PixelType > iimg::TBitmapIterator< PixelType >::operator- (int difference) const [inline]
Definition at line 266 of file TBitmapIterator.h.
template<typename PixelType > TBitmapIterator< PixelType > & iimg::TBitmapIterator< PixelType >::operator-- () [inline]
Definition at line 239 of file TBitmapIterator.h.
template<typename PixelType > TBitmapIterator< PixelType > iimg::TBitmapIterator< PixelType >::operator-- (int) [inline]
Definition at line 228 of file TBitmapIterator.h.
template<typename PixelType > TBitmapIterator< PixelType > & iimg::TBitmapIterator< PixelType >::operator-= (int difference) [inline]
Definition at line 257 of file TBitmapIterator.h.
template<typename PixelType > bool iimg::TBitmapIterator< PixelType >::operator< (const TBitmapIterator< PixelType > & iterator) [inline]
Definition at line 181 of file TBitmapIterator.h.
References I_ASSERT.
template<typename PixelType > bool iimg::TBitmapIterator< PixelType >::operator== (const TBitmapIterator< PixelType > & iterator) [inline]
Definition at line 199 of file TBitmapIterator.h.
References I_ASSERT.
template<typename PixelType > bool iimg::TBitmapIterator< PixelType >::operator> (const TBitmapIterator< PixelType > & iterator) [inline]
Definition at line 190 of file TBitmapIterator.h.
References I_ASSERT.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iimg/TBitmapIterator.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy