ACF: isys::IFileSystem Class Reference
isys::IFileSystem Class Reference
[Defines access to operating system dependent implementation]
Defines some file system dependent operations.
#include <IFileSystem.h>
Public Member Functions
virtual istd::CString GetNormalizedPath (const istd::CString &path) const =0
Get normalized file path.
virtual istd::CString GetFileName (const istd::CString &filePath) const =0
Get file name of specified file path.
virtual istd::CString GetBaseFileName (const istd::CString &filePath) const =0
Get base file name (also without extension) of specified file path.
virtual istd::CString GetDirPath (const istd::CString &filePath) const =0
Get directory path of specified file path.
virtual bool HasExtension (const istd::CString &filePath, const istd::CString &extension) const =0
Check if file path has specified extension.
virtual bool IsPresent (const istd::CString &filePath) const =0
Check if some file is present.
virtual bool CreateFileCopy (const istd::CString &inputFile, const istd::CString &outputFile, bool overwriteExisting=false) const =0
Copy any file to another.
virtual bool RemoveFile (const istd::CString &filePath) const =0
Remove the file filePath from the file system.
virtual bool RemoveFolder (const istd::CString &directoryPath, bool ignoreNonEmpty=false) const =0
Remove the directory directoryPath from the file system.
virtual bool CreateFolder (const istd::CString &directoryPath) const =0
Create an empty directory.
Detailed Description
Defines some file system dependent operations.
Definition at line 20 of file IFileSystem.h.
Member Function Documentation
virtual bool isys::IFileSystem::CreateFileCopy (const istd::CString & inputFile, const istd::CString & outputFile, bool overwriteExisting = false) const [pure virtual]
Copy any file to another.
If the overwriteExisting is set on, the existing file will be overwritten.
Implemented in iqt::CFileSystem.
virtual bool isys::IFileSystem::CreateFolder (const istd::CString & directoryPath) const [pure virtual]
Create an empty directory.
Implemented in iqt::CFileSystem.
virtual istd::CString isys::IFileSystem::GetBaseFileName (const istd::CString & filePath) const [pure virtual]
Get base file name (also without extension) of specified file path.
For example for "C:\Test\blah.txt.gz" it should return "blah".
Implemented in iqt::CFileSystem, and isys::CFileSystemBase.
virtual istd::CString isys::IFileSystem::GetDirPath (const istd::CString & filePath) const [pure virtual]
Get directory path of specified file path.
For example for "C:\Test\blah.txt" it should return "C:\Test".
Implemented in iqt::CFileSystem, and isys::CFileSystemBase.
Referenced by ibase::TFileSerializerComp< ReadArchive, WriteArchive >::CheckTargetDirectory().
virtual istd::CString isys::IFileSystem::GetFileName (const istd::CString & filePath) const [pure virtual]
Get file name of specified file path.
For example for "C:\Test\blah.txt" it should return "blah.txt".
Implemented in iqt::CFileSystem, and isys::CFileSystemBase.
virtual istd::CString isys::IFileSystem::GetNormalizedPath (const istd::CString & path) const [pure virtual]
Get normalized file path.
For any path to the same file this function should return the same path. For example for "C:\Test\..\Test\blah.txt" it should return "C:\Test\blah.txt".
Implemented in iqt::CFileSystem, and isys::CFileSystemBase.
virtual bool isys::IFileSystem::HasExtension (const istd::CString & filePath, const istd::CString & extension) const [pure virtual]
Check if file path has specified extension.
Implemented in iqt::CFileSystem, and isys::CFileSystemBase.
virtual bool isys::IFileSystem::IsPresent (const istd::CString & filePath) const [pure virtual]
Check if some file is present.
Implemented in iqt::CFileSystem.
Referenced by ibase::TFileSerializerComp< ReadArchive, WriteArchive >::CheckInputFilePath(), ibase::TFileSerializerComp< ReadArchive, WriteArchive >::CheckTargetDirectory(), and ibase::TFileSerializerComp< ReadArchive, WriteArchive >::IsOperationSupported().
virtual bool isys::IFileSystem::RemoveFile (const istd::CString & filePath) const [pure virtual]
Remove the file filePath from the file system.
Implemented in iqt::CFileSystem.
virtual bool isys::IFileSystem::RemoveFolder (const istd::CString & directoryPath, bool ignoreNonEmpty = false) const [pure virtual]
Remove the directory directoryPath from the file system.
If ignoreNonEmpty flag set, all files in the directory will be also deleted, otherwise operation will be canceled and the function returns false.
Implemented in iqt::CFileSystem.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/isys/IFileSystem.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy