istd::TIndex< Dimensions > Class Template Reference
istd::TIndex< Dimensions > Class Template Reference
Multidimensional index used to addressing fixed-size array.
#include <TIndex.h>
Public Types
enum { DIMENSIONS = Dimensions }
typedef int IndexType
typedef int * Iterator
Public Member Functions
TIndex ()
Default constructor without member initialization.
TIndex (int value)
Constructor initializing all member to specified value.
TIndex (const TIndex &index)
Copy constructor.
bool IsValid () const
Check if this index is valid.
bool IsZero () const
Check if this index point at zero element.
bool IsSizeEmpty () const
Check if this index interpreted as size is empty.
void Reset ()
Reset this object.
void Clear ()
Set all components to 0.
bool IsDimensionsCountFixed () const
Check, if number dimensions is fixed.
int GetDimensionsCount () const
Get number of dimensions of this index.
bool SetDimensionsCount (int count) const
Set number of dimensions of this index.
int GetAt (int index) const
Get element stored at specified index.
void SetAt (int index, int value)
Set element at specified index.
void SetAllTo (int value)
Set all components to specified value.
bool IncreaseAt (int index)
Increase single component at specified position.
bool DecreaseAt (int index)
Decrease single component at specified position.
bool IsInside (const TIndex &boundaries) const
Check if index is inside boundaries.
bool Increase (const TIndex &boundaries)
Increase this index inside the boundaries.
bool Decrease (const TIndex &boundaries)
Decrese this index inside the boundaries.
int GetProductVolume () const
Get total number of elements if this index is treated as size.
Iterator Begin () const
Get begin value of element access iterator.
Iterator End () const
Get end value of element access iterator.
int operator[] (int index) const
int & operator[] (int index)
bool operator== (const TIndex &index) const
bool operator!= (const TIndex &index) const
TIndex operator+ (const TIndex &index) const
TIndex & operator+= (const TIndex &index)
TIndex operator- (const TIndex &index) const
TIndex & operator-= (const TIndex &index)
Static Public Member Functions
static const TIndex< Dimensions > & GetZero ()
Get global instance of zero index.
static const TIndex< Dimensions > & GetInvalid ()
Get global instance of invalid index.
Detailed Description
template<int Dimensions>
class istd::TIndex< Dimensions >
Multidimensional index used to addressing fixed-size array.
Definition at line 16 of file TIndex.h.
Member Typedef Documentation
template<int Dimensions> typedef int istd::TIndex< Dimensions >::IndexType
Definition at line 19 of file TIndex.h.
template<int Dimensions> typedef int* istd::TIndex< Dimensions >::Iterator
Definition at line 20 of file TIndex.h.
Member Enumeration Documentation
template<int Dimensions> anonymous enum
Enumerator:
DIMENSIONS
Definition at line 22 of file TIndex.h.
Constructor & Destructor Documentation
template<int Dimensions> istd::TIndex< Dimensions >::TIndex ()
Default constructor without member initialization.
Definition at line 424 of file TIndex.h.
template<int Dimensions> istd::TIndex< Dimensions >::TIndex (int value) [explicit]
Constructor initializing all member to specified value.
Definition at line 417 of file TIndex.h.
template<int Dimensions> istd::TIndex< Dimensions >::TIndex (const TIndex< Dimensions > & index)
Copy constructor.
Definition at line 433 of file TIndex.h.
Member Function Documentation
template<int Dimensions> TIndex< Dimensions >::Iterator istd::TIndex< Dimensions >::Begin () const [inline]
Get begin value of element access iterator.
Please refer to general description of ACF iterators, STL iterators or Qt iterators concept.
Definition at line 307 of file TIndex.h.
template<int Dimensions> void istd::TIndex< Dimensions >::Clear () [inline]
Set all components to 0.
Definition at line 256 of file TIndex.h.
template<int Dimensions> bool istd::TIndex< Dimensions >::Decrease (const TIndex< Dimensions > & boundaries)
Decrese this index inside the boundaries.
Returns:
false, if decrease wasn't possible (e.g. overflow).
Definition at line 488 of file TIndex.h.
References I_ASSERT.
template<int Dimensions> bool istd::TIndex< Dimensions >::DecreaseAt (int index) [inline]
Decrease single component at specified position.
Parameters:
index index of component should be increased. It must be valid.
Returns:
true if success. It is provided for template implementations. In this case it returns always true.
Definition at line 295 of file TIndex.h.
References I_ASSERT.
template<int Dimensions> TIndex< Dimensions >::Iterator istd::TIndex< Dimensions >::End () const [inline]
Get end value of element access iterator.
Please refer to general description of ACF iterators, STL iterators or Qt iterators concept.
Definition at line 314 of file TIndex.h.
template<int Dimensions> int istd::TIndex< Dimensions >::GetAt (int index) const [inline]
Get element stored at specified index.
Definition at line 263 of file TIndex.h.
References I_ASSERT.
template<int Dimensions> int istd::TIndex< Dimensions >::GetDimensionsCount () const [inline]
Get number of dimensions of this index.
Definition at line 196 of file TIndex.h.
Referenced by istd::TIndex< Dimensions >::operator+(), istd::TIndex< Dimensions >::operator+=(), istd::TIndex< Dimensions >::operator-(), and istd::TIndex< Dimensions >::operator-=().
template<int Dimensions> const TIndex< Dimensions > & istd::TIndex< Dimensions >::GetInvalid () [static]
Get global instance of invalid index.
Definition at line 535 of file TIndex.h.
template<int Dimensions> int istd::TIndex< Dimensions >::GetProductVolume () const
Get total number of elements if this index is treated as size.
Returns:
multiplication of all elements.
Definition at line 513 of file TIndex.h.
template<int Dimensions> const TIndex< Dimensions > & istd::TIndex< Dimensions >::GetZero () [static]
Get global instance of zero index.
Definition at line 528 of file TIndex.h.
template<int Dimensions> bool istd::TIndex< Dimensions >::Increase (const TIndex< Dimensions > & boundaries)
Increase this index inside the boundaries.
Returns:
false, if increase wasn't possible (e.g. overflow).
Definition at line 466 of file TIndex.h.
References I_ASSERT.
template<int Dimensions> bool istd::TIndex< Dimensions >::IncreaseAt (int index) [inline]
Increase single component at specified position.
Parameters:
index index of component should be increased. It must be valid.
Returns:
true if success. It is provided for template implementations. In this case it returns always true.
Definition at line 283 of file TIndex.h.
References I_ASSERT.
template<int Dimensions> bool istd::TIndex< Dimensions >::IsDimensionsCountFixed () const [inline]
Check, if number dimensions is fixed.
It is provided for template implementations. It returns always true.
Definition at line 189 of file TIndex.h.
template<int Dimensions> bool istd::TIndex< Dimensions >::IsInside (const TIndex< Dimensions > & boundaries) const
Check if index is inside boundaries.
Index is inside boundaries, if all its components are smaller than according boundary components.
Definition at line 451 of file TIndex.h.
References I_ASSERT.
Referenced by istd::TArray< Element, Dimensions >::GetAt(), istd::TArray< Element, Dimensions >::GetAtRef(), imath::CSampledFunction2d::GetSampleValue(), istd::TArray< Element, Dimensions >::Iterator::Iterator(), istd::TArray< Element, Dimensions >::SetAt(), and imath::CSampledFunction2d::SetSampleValue().
template<int Dimensions> bool istd::TIndex< Dimensions >::IsSizeEmpty () const [inline]
Check if this index interpreted as size is empty.
It means, it returns true, is some of components is less or equal 0.
Definition at line 236 of file TIndex.h.
template<int Dimensions> bool istd::TIndex< Dimensions >::IsValid () const [inline]
Check if this index is valid.
Index is valid, if all its components are bigger or equal 0.
Definition at line 210 of file TIndex.h.
template<int Dimensions> bool istd::TIndex< Dimensions >::IsZero () const [inline]
Check if this index point at zero element.
In other words, it checks if all components are 0.
Definition at line 223 of file TIndex.h.
template<int Dimensions> bool istd::TIndex< Dimensions >::operator!= (const TIndex< Dimensions > & index) const
Definition at line 351 of file TIndex.h.
template<int Dimensions> TIndex< Dimensions > istd::TIndex< Dimensions >::operator+ (const TIndex< Dimensions > & index) const
Definition at line 358 of file TIndex.h.
References istd::TIndex< Dimensions >::GetDimensionsCount(), and I_ASSERT.
template<int Dimensions> TIndex< Dimensions > & istd::TIndex< Dimensions >::operator+= (const TIndex< Dimensions > & index)
Definition at line 373 of file TIndex.h.
References istd::TIndex< Dimensions >::GetDimensionsCount(), and I_ASSERT.
template<int Dimensions> TIndex< Dimensions > istd::TIndex< Dimensions >::operator- (const TIndex< Dimensions > & index) const
Definition at line 386 of file TIndex.h.
References istd::TIndex< Dimensions >::GetDimensionsCount(), and I_ASSERT.
template<int Dimensions> TIndex< Dimensions > & istd::TIndex< Dimensions >::operator-= (const TIndex< Dimensions > & index)
Definition at line 401 of file TIndex.h.
References istd::TIndex< Dimensions >::GetDimensionsCount(), and I_ASSERT.
template<int Dimensions> bool istd::TIndex< Dimensions >::operator== (const TIndex< Dimensions > & index) const
Definition at line 338 of file TIndex.h.
template<int Dimensions> int istd::TIndex< Dimensions >::operator[] (int index) const [inline]
Definition at line 321 of file TIndex.h.
template<int Dimensions> int & istd::TIndex< Dimensions >::operator[] (int index) [inline]
Definition at line 328 of file TIndex.h.
References I_ASSERT.
template<int Dimensions> void istd::TIndex< Dimensions >::Reset () [inline]
Reset this object.
For this (fixed-size) implementation, it does the same as clear.
See also:
Clear()
Definition at line 249 of file TIndex.h.
template<int Dimensions> void istd::TIndex< Dimensions >::SetAllTo (int value)
Set all components to specified value.
Definition at line 442 of file TIndex.h.
template<int Dimensions> void istd::TIndex< Dimensions >::SetAt (int index, int value) [inline]
Set element at specified index.
Definition at line 273 of file TIndex.h.
References I_ASSERT.
template<int Dimensions> bool istd::TIndex< Dimensions >::SetDimensionsCount (int count) const [inline]
Set number of dimensions of this index.
It is provided to allows template implementations to use fixed-size or variable arrays.
Parameters:
count number of dimensions will be set.
Returns:
true, if number of set dimensions equals template parameter or false if isn't.
Definition at line 203 of file TIndex.h.
The documentation for this class was generated from the following file:
Include/istd/TIndex.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy