ACF: iser::IArchive Class Reference
iser::IArchive Class Reference
[Persistence concept., Main concepts and implementations]
Represent input/output persistence archive.
#include <IArchive.h>
Public Member Functions
virtual bool IsStoring () const =0
Check if this archive is loading or storing.
virtual bool IsTagSkippingSupported () const =0
Check if skiping to the end of tag on EndTag is supported.
virtual const IVersionInfo & GetVersionInfo () const =0
Get version of archived stream for specific versioning type.
virtual bool BeginTag (const CArchiveTag &tag)=0
Begin of archive tag.
virtual bool BeginMultiTag (const CArchiveTag &tag, const CArchiveTag &subTag, int &count)=0
Begin of archive tag containing set of subelements of the same type.
virtual bool EndTag (const CArchiveTag &tag)=0
End of archive tag.
virtual bool Process (bool &value)=0
Process primitive type.
virtual bool Process (char &value)=0
Process primitive type.
virtual bool Process (I_BYTE &value)=0
Process primitive type.
virtual bool Process (I_SBYTE &value)=0
Process primitive type.
virtual bool Process (I_WORD &value)=0
Process primitive type.
virtual bool Process (I_SWORD &value)=0
Process primitive type.
virtual bool Process (I_DWORD &value)=0
Process primitive type.
virtual bool Process (I_SDWORD &value)=0
Process primitive type.
virtual bool Process (I_QWORD &value)=0
Process primitive type.
virtual bool Process (I_SQWORD &value)=0
Process primitive type.
virtual bool Process (float &value)=0
Process primitive type.
virtual bool Process (double &value)=0
Process primitive type.
virtual bool Process (std::string &value)=0
Process primitive type.
virtual bool Process (istd::CString &value)=0
Process primitive type.
virtual bool ProcessData (void *dataPtr, int size)=0
Process binary data block.
virtual bool ProcessBits (void *dataPtr, int bitsCount, int bytesCount)=0
Process binary data block.
Detailed Description
Represent input/output persistence archive.
Definition at line 29 of file IArchive.h.
Member Function Documentation
virtual bool iser::IArchive::BeginMultiTag (const CArchiveTag & tag, const CArchiveTag & subTag, int & count) [pure virtual]
Begin of archive tag containing set of subelements of the same type.
See also:
BeginTag.
Parameters:
tag main tag.
subTag type of subelement tag.
count number of subelements. If it is read archive this value will be set. If it storing archive this is input value.
useTagSkipping flag signalling that support of tag skipping should be enabled.
Returns:
true if success. In this case you have to call EndTag after serializing of subelements.
Implemented in iqt::CSettingsReadArchive, iqt::CSettingsWriteArchive, iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CArchiveBase, iser::CXmlReadArchiveBase, and iser::CXmlWriteArchiveBase.
Referenced by iser::TVersionInfoSerializer< VersionInfo >::ReadVersion(), imath::TMathVectorWrap< Base >::Serialize(), imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::Serialize(), imath::TFastVector< MaxSize, Element >::Serialize(), icomp::TMultiAttribute< Value >::Serialize(), icmm::TComposedColor< Size >::Serialize(), ibase::TSerializableContainer< ItemClass, ContainerClass >::Serialize(), ibase::TMessageContainerWrap< Base >::Serialize(), ibase::TFactorisableContainer< InterfaceClass >::Serialize(), and iser::TVersionInfoSerializer< VersionInfo >::WriteVersion().
virtual bool iser::IArchive::BeginTag (const CArchiveTag & tag) [pure virtual]
Begin of archive tag.
Parameters:
tag tag object.
useTagSkipping flag signalling that support of tag skipping should be enabled.
Implemented in iqt::CSettingsReadArchive, iqt::CSettingsWriteArchive, iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBinaryReadArchiveBase, iser::CBinaryWriteArchiveBase, iser::CFileReadArchive, iser::CFileWriteArchive, iser::CXmlReadArchiveBase, and iser::CXmlWriteArchiveBase.
Referenced by iser::TVersionInfoSerializer< VersionInfo >::ReadVersion(), imath::TMatrix< Width, Height, Element >::Serialize(), imath::TMathVectorWrap< Base >::Serialize(), imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::Serialize(), imath::TFastVector< MaxSize, Element >::Serialize(), icomp::TMultiAttribute< Value >::Serialize(), icomp::TAttribute< Value >::Serialize(), icmm::TComposedColor< Size >::Serialize(), ibase::TSerializableContainer< ItemClass, ContainerClass >::Serialize(), ibase::TMessageContainerWrap< Base >::Serialize(), ibase::TFactorisableContainer< InterfaceClass >::Serialize(), ibase::TEnableableWrap< Base >::SerializeEnabled(), ibase::TNamedWrap< BaseClass >::SerializeName(), and iser::TVersionInfoSerializer< VersionInfo >::WriteVersion().
virtual bool iser::IArchive::EndTag (const CArchiveTag & tag) [pure virtual]
End of archive tag.
This method should be allways called after BeginTag is successfull called. If skipping of tag contains is supported, this will skip to the end of tag while archive reading. Otherwise you have to read contains of archive completely.
See also:
IsTagSkippingSupported.
Implemented in iqt::CSettingsReadArchive, iqt::CSettingsWriteArchive, iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBinaryReadArchiveBase, iser::CBinaryWriteArchiveBase, iser::CFileReadArchive, iser::CFileWriteArchive, iser::CXmlReadArchiveBase, and iser::CXmlWriteArchiveBase.
Referenced by iser::TVersionInfoSerializer< VersionInfo >::ReadVersion(), imath::TMatrix< Width, Height, Element >::Serialize(), imath::TMathVectorWrap< Base >::Serialize(), imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::Serialize(), imath::TFastVector< MaxSize, Element >::Serialize(), icomp::TMultiAttribute< Value >::Serialize(), icomp::TAttribute< Value >::Serialize(), icmm::TComposedColor< Size >::Serialize(), ibase::TSerializableContainer< ItemClass, ContainerClass >::Serialize(), ibase::TMessageContainerWrap< Base >::Serialize(), ibase::TFactorisableContainer< InterfaceClass >::Serialize(), ibase::TEnableableWrap< Base >::SerializeEnabled(), ibase::TNamedWrap< BaseClass >::SerializeName(), and iser::TVersionInfoSerializer< VersionInfo >::WriteVersion().
virtual const IVersionInfo& iser::IArchive::GetVersionInfo () const [pure virtual]
Get version of archived stream for specific versioning type.
Parameters:
versionId versioning type. It allows you to distinguish different version aspects. For example version number of framework cann differ from application version.
See also:
VersionId.
Implemented in iser::CReadArchiveBase, and iser::CWriteArchiveBase.
virtual bool iser::IArchive::IsStoring () const [pure virtual]
Check if this archive is loading or storing.
Implemented in iser::CReadArchiveBase, and iser::CWriteArchiveBase.
Referenced by iser::TVersionInfoSerializer< VersionInfo >::ReadVersion(), imath::TMatrix< Width, Height, Element >::Serialize(), imath::TMathVectorWrap< Base >::Serialize(), imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::Serialize(), imath::TFastVector< MaxSize, Element >::Serialize(), icomp::TMultiAttribute< Value >::Serialize(), icmm::TComposedColor< Size >::Serialize(), ibase::TSerializableContainer< ItemClass, ContainerClass >::Serialize(), ibase::TMessageContainerWrap< Base >::Serialize(), ibase::TFactorisableContainer< InterfaceClass >::Serialize(), and iser::TVersionInfoSerializer< VersionInfo >::WriteVersion().
virtual bool iser::IArchive::IsTagSkippingSupported () const [pure virtual]
Check if skiping to the end of tag on EndTag is supported.
See also:
EndTag.
Implemented in iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CArchiveBase, iser::CFileReadArchive, iser::CFileWriteArchive, iser::CXmlReadArchiveBase, and iser::CXmlWriteArchiveBase.
virtual bool iser::IArchive::Process (istd::CString & value) [pure virtual]
Process primitive type.
Implemented in iqt::CSettingsReadArchive, iqt::CSettingsWriteArchive, iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBinaryReadArchiveBase, iser::CBinaryWriteArchiveBase, iser::CXmlReadArchiveBase, and iser::CXmlWriteArchiveBase.
virtual bool iser::IArchive::Process (std::string & value) [pure virtual]
Process primitive type.
Implemented in iqt::CSettingsReadArchive, iqt::CSettingsWriteArchive, iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBinaryReadArchiveBase, iser::CBinaryWriteArchiveBase, iser::CXmlReadArchiveBase, and iser::CXmlWriteArchiveBase.
virtual bool iser::IArchive::Process (double & value) [pure virtual]
Process primitive type.
Implemented in iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBinaryReadArchiveBase, iser::CBinaryWriteArchiveBase, iser::CTextReadArchiveBase, and iser::CTextWriteArchiveBase.
virtual bool iser::IArchive::Process (float & value) [pure virtual]
Process primitive type.
Implemented in iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBinaryReadArchiveBase, iser::CBinaryWriteArchiveBase, iser::CTextReadArchiveBase, and iser::CTextWriteArchiveBase.
virtual bool iser::IArchive::Process (I_SQWORD & value) [pure virtual]
Process primitive type.
Implemented in iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBinaryReadArchiveBase, iser::CBinaryWriteArchiveBase, iser::CTextReadArchiveBase, and iser::CTextWriteArchiveBase.
virtual bool iser::IArchive::Process (I_QWORD & value) [pure virtual]
Process primitive type.
Implemented in iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBinaryReadArchiveBase, iser::CBinaryWriteArchiveBase, iser::CTextReadArchiveBase, and iser::CTextWriteArchiveBase.
virtual bool iser::IArchive::Process (I_SDWORD & value) [pure virtual]
Process primitive type.
Implemented in iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBinaryReadArchiveBase, iser::CBinaryWriteArchiveBase, iser::CTextReadArchiveBase, and iser::CTextWriteArchiveBase.
virtual bool iser::IArchive::Process (I_DWORD & value) [pure virtual]
Process primitive type.
Implemented in iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBinaryReadArchiveBase, iser::CBinaryWriteArchiveBase, iser::CTextReadArchiveBase, and iser::CTextWriteArchiveBase.
virtual bool iser::IArchive::Process (I_SWORD & value) [pure virtual]
Process primitive type.
Implemented in iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBinaryReadArchiveBase, iser::CBinaryWriteArchiveBase, iser::CTextReadArchiveBase, and iser::CTextWriteArchiveBase.
virtual bool iser::IArchive::Process (I_WORD & value) [pure virtual]
Process primitive type.
Implemented in iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBinaryReadArchiveBase, iser::CBinaryWriteArchiveBase, iser::CTextReadArchiveBase, and iser::CTextWriteArchiveBase.
virtual bool iser::IArchive::Process (I_SBYTE & value) [pure virtual]
Process primitive type.
Implemented in iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBinaryReadArchiveBase, iser::CBinaryWriteArchiveBase, iser::CTextReadArchiveBase, and iser::CTextWriteArchiveBase.
virtual bool iser::IArchive::Process (I_BYTE & value) [pure virtual]
Process primitive type.
Implemented in iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBinaryReadArchiveBase, iser::CBinaryWriteArchiveBase, iser::CTextReadArchiveBase, and iser::CTextWriteArchiveBase.
virtual bool iser::IArchive::Process (char & value) [pure virtual]
Process primitive type.
Implemented in iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBinaryReadArchiveBase, iser::CBinaryWriteArchiveBase, iser::CTextReadArchiveBase, and iser::CTextWriteArchiveBase.
virtual bool iser::IArchive::Process (bool & value) [pure virtual]
Process primitive type.
Implemented in iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBinaryReadArchiveBase, iser::CBinaryWriteArchiveBase, iser::CTextReadArchiveBase, and iser::CTextWriteArchiveBase.
Referenced by iser::TVersionInfoSerializer< VersionInfo >::ReadVersion(), imath::TVector< Size, Element >::Serialize(), imath::TMatrix< Width, Height, Element >::Serialize(), imath::TMathVectorWrap< Base >::Serialize(), imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::Serialize(), imath::TFastVector< MaxSize, Element >::Serialize(), icomp::TMultiAttribute< Value >::Serialize(), icomp::TAttribute< Value >::Serialize(), icmm::TComposedColor< Size >::Serialize(), ibase::TFactorisableContainer< InterfaceClass >::Serialize(), ibase::TEnableableWrap< Base >::SerializeEnabled(), ibase::TNamedWrap< BaseClass >::SerializeName(), and iser::TVersionInfoSerializer< VersionInfo >::WriteVersion().
virtual bool iser::IArchive::ProcessBits (void * dataPtr, int bitsCount, int bytesCount) [pure virtual]
Process binary data block.
Parameters:
dataPtr pointer to memory block.
bitsCount number of bits.
bytesCount size of memory block in bytes.
Implemented in iser::CBitMemoryReadArchive, iser::CBitMemoryWriteArchive, iser::CReadArchiveBase, and iser::CWriteArchiveBase.
virtual bool iser::IArchive::ProcessData (void * dataPtr, int size) [pure virtual]
Process binary data block.
Parameters:
dataPtr pointer to memory block.
size size of memory block in bytes.
Implemented in iqt::CNetworkWriteArchive, iqt::CXmlFileReadArchive, iqt::CXmlFileWriteArchive, iqt::CXslTransformationReadArchive, iqt::CXslTransformationWriteArchive, iser::CBitMemoryReadArchive, iser::CBitMemoryWriteArchive, iser::CFileReadArchive, iser::CFileWriteArchive, iser::CMemoryReadArchive, iser::CMemoryWriteArchive, iser::CTextReadArchiveBase, and iser::CTextWriteArchiveBase.
Referenced by ibase::TMsbWord< Size >::Serialize().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iser/IArchive.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy