istd::TChangeNotifier< Changeable > Class Template Reference
istd::TChangeNotifier< Changeable > Class Template Reference
Model/Observer concept | Main concepts and implementations | Set of helper classes.
Help class which provides the automatic update mechanism of the model.
#include <TChangeNotifier.h>
Public Types
typedef istd::TPointerBase
< Changeable > BaseClass
Public Member Functions
TChangeNotifier (Changeable *changeablePtr=NULL, int changeFlags=IChangeable::CF_MODEL, istd::IPolymorphic *updateParamsPtr=NULL)
TChangeNotifier (const TChangeNotifier &notifier)
virtual ~TChangeNotifier ()
void SetPtr (Changeable *changeablePtr)
Allow Attach to some 'changeable' pointer.
void Reset ()
Call update on attached object and detach it.
void Abort ()
Similiar like method Reset(), but update will be called with active flag CF_ABORTED.
const Changeable * operator-> () const
Method call operator returning slave 'changeable' pointer.
Changeable * operator-> ()
Method call operator returning slave 'changeable' pointer.
operator Changeable * () const
Access to slave 'changeable' pointer.
Public Member Functions inherited from istd::TPointerBase< Changeable >
TPointerBase (Changeable *ptr=NULL)
Construct and assign internal pointer.
void SetPtr (Changeable *ptr)
Set value of internal stored pointer.
void Reset ()
Set internal pointer value to NULL.
Changeable * GetPtr () const
Return access to internal stored pointer.
bool IsValid () const
Check if internal pointer not NULL.
void Swap (TPointerBase &ptr)
Swap two pointers.
Changeable & operator* () const
Get an access to object pointed at.
CastedType Cast () const
Changeable * operator-> () const
bool operator== (const TPointerBase< Changeable > &ptr) const
bool operator== (const Changeable *ptr) const
bool operator!= (const TPointerBase< Changeable > &ptr) const
bool operator!= (const Changeable *ptr) const
bool operator< (const TPointerBase< Changeable > &ptr) const
bool operator< (const Changeable *ptr) const
bool operator> (const TPointerBase< Changeable > &ptr) const
bool operator> (const Changeable *ptr) const
bool operator<= (const TPointerBase< Changeable > &ptr) const
bool operator<= (const Changeable *ptr) const
bool operator>= (const TPointerBase< Changeable > &ptr) const
bool operator>= (const Changeable *ptr) const
Additional Inherited Members
Protected Member Functions inherited from istd::TPointerBase< Changeable >
TPointerBase< Changeable > & operator= (const TPointerBase< Changeable > ptr)
Changeable *& GetPtrRef ()
Detailed Description
template<class Changeable>
class istd::TChangeNotifier< Changeable >
Help class which provides the automatic update mechanism of the model.
Definition at line 22 of file TChangeNotifier.h.
Member Typedef Documentation
template<class Changeable> typedef istd::TPointerBase<Changeable> istd::TChangeNotifier< Changeable >::BaseClass
Definition at line 25 of file TChangeNotifier.h.
Constructor & Destructor Documentation
template<class Changeable> istd::TChangeNotifier< Changeable >::TChangeNotifier (Changeable * changeablePtr = NULL, int changeFlags = IChangeable::CF_MODEL, istd::IPolymorphic * updateParamsPtr = NULL) explicit
Definition at line 65 of file TChangeNotifier.h.
References NULL.
template<class Changeable> istd::TChangeNotifier< Changeable >::TChangeNotifier (const TChangeNotifier< Changeable > & notifier)
Definition at line 77 of file TChangeNotifier.h.
References istd::TPointerBase< Changeable >::IsValid(), and istd::TPointerBase< Changeable >::operator->().
template<class Changeable > istd::TChangeNotifier< Changeable >::~TChangeNotifier () virtual
Definition at line 89 of file TChangeNotifier.h.
Member Function Documentation
template<class Changeable > void istd::TChangeNotifier< Changeable >::Abort () inline
Similiar like method Reset(), but update will be called with active flag CF_ABORTED.
It should be used only if you are sure, that no changes was done, or result will be ignored.
Definition at line 124 of file TChangeNotifier.h.
References istd::IChangeable::CF_ABORTED, and NULL.
template<class Changeable > istd::TChangeNotifier< Changeable >::operator Changeable * () const inline
Access to slave 'changeable' pointer.
Definition at line 155 of file TChangeNotifier.h.
template<class Changeable > const Changeable * istd::TChangeNotifier< Changeable >::operator-> () const inline
Method call operator returning slave 'changeable' pointer.
Definition at line 137 of file TChangeNotifier.h.
template<class Changeable > Changeable * istd::TChangeNotifier< Changeable >::operator-> () inline
Method call operator returning slave 'changeable' pointer.
Definition at line 146 of file TChangeNotifier.h.
template<class Changeable > void istd::TChangeNotifier< Changeable >::Reset () inline
Call update on attached object and detach it.
Definition at line 111 of file TChangeNotifier.h.
References NULL.
template<class Changeable> void istd::TChangeNotifier< Changeable >::SetPtr (Changeable * changeablePtr)
Allow Attach to some 'changeable' pointer.
Definition at line 96 of file TChangeNotifier.h.
References NULL.
Referenced by ifile::TFileSerializerComp< ReadArchive, WriteArchive >::LoadFromFile().
The documentation for this class was generated from the following file:
Include/istd/TChangeNotifier.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy