istd::CIndex2d Class Reference
istd::CIndex2d Class Reference
#include <CIndex2d.h>
Public Types
typedef TIndex< 2 > BaseClass
Public Member Functions
CIndex2d ()
CIndex2d (int x, int y)
CIndex2d (const TIndex< 2 > &index)
CIndex2d (const QPoint &point)
CIndex2d (const QSize &size)
int GetX () const
void SetX (int value)
int GetY () const
void SetY (int value)
bool operator< (const CIndex2d &index) const
bool operator> (const CIndex2d &index) const
bool operator<= (const CIndex2d &index) const
bool operator>= (const CIndex2d &index) const
operator QSize () const
CIndex2d & operator= (const TIndex< 2 > &index)
Detailed Description
Definition at line 17 of file CIndex2d.h.
Member Typedef Documentation
typedef TIndex<2> istd::CIndex2d::BaseClass
Reimplemented in ibase::CSize.
Definition at line 20 of file CIndex2d.h.
Constructor & Destructor Documentation
istd::CIndex2d::CIndex2d () [inline]
Definition at line 46 of file CIndex2d.h.
istd::CIndex2d::CIndex2d (int x, int y) [inline]
Definition at line 51 of file CIndex2d.h.
References istd::TIndex< 2 >::SetAt().
istd::CIndex2d::CIndex2d (const TIndex< 2 > & index) [inline]
Definition at line 58 of file CIndex2d.h.
istd::CIndex2d::CIndex2d (const QPoint & point) [inline]
Definition at line 63 of file CIndex2d.h.
References istd::TIndex< 2 >::SetAt().
istd::CIndex2d::CIndex2d (const QSize & size) [inline]
Definition at line 70 of file CIndex2d.h.
References istd::TIndex< 2 >::SetAt().
Member Function Documentation
int istd::CIndex2d::GetX () const [inline]
Definition at line 77 of file CIndex2d.h.
References istd::TIndex< 2 >::GetAt().
Referenced by i2d::CRect::CRect(), i2d::CVector2d::CVector2d(), iview::CScreenTransform::GetClientPosition(), i2d::CRect::IsInside(), operator QSize(), operator<(), i2d::CRect::SetLeftBottom(), i2d::CRect::SetLeftTop(), i2d::CRect::SetRightBottom(), i2d::CRect::SetRightTop(), i2d::CRect::Translate(), and i2d::CRect::Union().
int istd::CIndex2d::GetY () const [inline]
Definition at line 89 of file CIndex2d.h.
References istd::TIndex< 2 >::GetAt().
Referenced by i2d::CRect::CRect(), i2d::CVector2d::CVector2d(), iview::CScreenTransform::GetClientPosition(), i2d::CRect::IsInside(), operator QSize(), operator<(), i2d::CRect::SetLeftBottom(), i2d::CRect::SetLeftTop(), i2d::CRect::SetRightBottom(), i2d::CRect::SetRightTop(), i2d::CRect::Translate(), and i2d::CRect::Union().
istd::CIndex2d::operator QSize () const [inline]
Definition at line 143 of file CIndex2d.h.
References GetX(), and GetY().
bool istd::CIndex2d::operator< (const CIndex2d & index) const [inline]
Definition at line 101 of file CIndex2d.h.
References GetX(), and GetY().
bool istd::CIndex2d::operator<= (const CIndex2d & index) const [inline]
Definition at line 123 of file CIndex2d.h.
CIndex2d & istd::CIndex2d::operator= (const TIndex< 2 > & index) [inline]
Definition at line 135 of file CIndex2d.h.
bool istd::CIndex2d::operator> (const CIndex2d & index) const [inline]
Definition at line 117 of file CIndex2d.h.
bool istd::CIndex2d::operator>= (const CIndex2d & index) const [inline]
Definition at line 129 of file CIndex2d.h.
void istd::CIndex2d::SetX (int value) [inline]
Definition at line 83 of file CIndex2d.h.
References istd::TIndex< 2 >::SetAt().
void istd::CIndex2d::SetY (int value) [inline]
Definition at line 95 of file CIndex2d.h.
References istd::TIndex< 2 >::SetAt().
The documentation for this class was generated from the following file:
Include/istd/CIndex2d.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy