iview::CShapeBase Class Reference
iview::CShapeBase Class Reference abstract
#include <CShapeBase.h>
Public Types
enum ShapeTransformMode { STM_VIEW, STM_SHAPE, STM_COMBINE }
Describe how shape tranformation is interpreted.
typedef
imod::CSingleModelObserverBase BaseClass
Public Types inherited from imod::CSingleModelObserverBase
typedef imod::IModel ModelType
Public Types inherited from iview::IShape
enum ChangeFlags { CF_CALIB = 1 << 20 }
Public Types inherited from iview::ITouchable
enum TouchState {
TS_NONE, TS_INACTIVE, TS_TICKER, TS_DRAGGABLE,
TS_OTHER, TS_LAST = TS_OTHER
}
Enumeration for possible shape touch states.
Public Member Functions
CShapeBase ()
CShapeBase (const CShapeBase &shape)
virtual ~CShapeBase ()
virtual void SetVisible (bool state=true)
Make this shape visible.
virtual bool AssignToLayer (int layerType)
virtual void Invalidate (int changeFlags=0)
iview::IDisplay * GetDisplayPtr () const
Get access to currently connected display.
ShapeTransformMode GetTransformMode () const
Get shape transformation mode.
void SetTransformMode (ShapeTransformMode mode)
Set shape transformation mode.
virtual int GetLayerType () const
Get layer type of this shape object.
virtual i2d::CRect GetBoundingBox () const
Return bounding box in client window coordinates.
virtual const IColorSchema * GetUserColorSchema () const
Get color schema from view or user defined.
virtual void SetUserColorSchema (const IColorSchema *schemaPtr)
Set color schema to draw shape.
virtual bool IsVisible () const
Check, if this object is visible.
virtual bool IsDisplayAccepted (const IDisplay &display) const
Check if this object can be connected to this display.
virtual void OnConnectDisplay (IDisplay *displayPtr)
Called after display is connected.
virtual void OnDisconnectDisplay (IDisplay *displayPtr)
Called after display is disconnected.
virtual bool OnDisplayChange (int flags)
It informs about changes in display.
virtual ITouchable::TouchState IsTouched (istd::CIndex2d position) const
Check, if any shape is touched.
virtual QString GetShapeDescriptionAt (istd::CIndex2d position) const
Get description to shape at specified position.
virtual bool OnAttached (imod::IModel *modelPtr)
This call back function will be called, if an observable object is about to be attached.
virtual bool OnDetached (imod::IModel *modelPtr)
This call back function will be called, if an observable object is about to be detached.
virtual void OnUpdate (int changeFlags, istd::IPolymorphic *updateParamsPtr)
Public Member Functions inherited from imod::CSingleModelObserverBase
CSingleModelObserverBase ()
virtual ~CSingleModelObserverBase ()
imod::IModel * GetModelPtr () const
Get access to observed model.
void EnsureModelDetached ()
Make sure this observer is detached.
virtual bool IsModelAttached (const imod::IModel *modelPtr=NULL) const
Check if specified model is attached.
virtual void BeforeUpdate (imod::IModel *modelPtr, int updateFlags, istd::IPolymorphic *updateParamsPtr)
This function will be called before update of the observer contents occures.
virtual void AfterUpdate (imod::IModel *modelPtr, int updateFlags, istd::IPolymorphic *updateParamsPtr)
This function will be called after update of the observer contents occures.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Public Member Functions inherited from iview::IVisualizable
virtual void Draw (QPainter &drawContext) const =0
Draw this shape using draw context.
Protected Member Functions
i2d::CVector2d GetScreenPosition (const i2d::CVector2d &logPosition) const
Get screen position based on logical position.
i2d::CVector2d GetLogPosition (const i2d::CVector2d &screenPosition) const
Get logical position based on screen position.
virtual int GetDisplayChangesMask ()
Get display changes mask.
virtual void InvalidateBoundingBox ()
Invalidate bounding box.
bool IsDisplayConnected () const
Check if display is connected.
const IColorSchema & GetColorSchema () const
Get color schema for this shape.
i2d::CRect GetClientRect () const
Get display client rectangle.
bool IsBoundingBoxValid () const
void DisconnectDisplay ()
virtual const
iview::CScreenTransform & GetViewToScreenTransform () const
virtual i2d::CRect CalcBoundingBox () const =0
Calculate bounding box.
Protected Member Functions inherited from imod::CSingleModelObserverBase
void SetModelPtr (imod::IModel *modelPtr)
Set internal model pointer to specified value.
Detailed Description
Definition at line 16 of file CShapeBase.h.
Member Typedef Documentation
typedef imod::CSingleModelObserverBase iview::CShapeBase::BaseClass
Definition at line 21 of file CShapeBase.h.
Member Enumeration Documentation
enum iview::CShapeBase::ShapeTransformMode
Describe how shape tranformation is interpreted.
Enumerator
STM_VIEW
Shape transformation will be ignored, view transformation will be used.
STM_SHAPE
View transformation will be ignored, shape transformation will be used.
STM_COMBINE
Both transformation will be used, shape transformation will be used as local transformation.
Definition at line 26 of file CShapeBase.h.
Constructor & Destructor Documentation
iview::CShapeBase::CShapeBase ()
iview::CShapeBase::CShapeBase (const CShapeBase & shape)
virtual iview::CShapeBase::~CShapeBase () virtual
Member Function Documentation
virtual bool iview::CShapeBase::AssignToLayer (int layerType) virtual
Referenced by iqt2d::TViewExtenderCompBase< Base >::AddItemsToScene().
virtual i2d::CRect iview::CShapeBase::CalcBoundingBox () const protected pure virtual
Calculate bounding box.
You have to implement this method in your shapes implementations.
Implemented in iview::CTransformableRectangleShape, iview::CParallelogramShape, iview::CPolygonShape, iview::CAffineTransformation2dShape, iview::CLabelShape, iview::CPolylineShape, iview::CAnnulusShape, iview::CTubePolylineShape, iview::CRectangleShape, iview::CLineShape, iview::CArrowShape, iview::CNoneCalibrationShape, iview::CCircleShape, iview::CPinShape, iview::CImageShape, iview::CCenterPinShape, iview::CPerspectiveCalibrationBoundsShape, iview::CPolypointShape, iview::CSplineShape, and iview::COrientedCircleShape.
void iview::CShapeBase::DisconnectDisplay () protected
virtual i2d::CRect iview::CShapeBase::GetBoundingBox () const virtual
Return bounding box in client window coordinates.
You can store this bounding box for optimization, because about every change of transformation you will be informed by calling OnDisplayChange(int) method.
Implements iview::IShape.
i2d::CRect iview::CShapeBase::GetClientRect () const protected
Get display client rectangle.
It can be called only when display is connected
See Also
IsDisplayConnected().
const IColorSchema& iview::CShapeBase::GetColorSchema () const protected
Get color schema for this shape.
It can be called only when display is connected
See Also
IsDisplayConnected().
virtual int iview::CShapeBase::GetDisplayChangesMask () protected virtual
Get display changes mask.
Only changes there are in mask will be accepted, rest will be ignored.
Reimplemented in iview::CInteractiveShapeBase.
Referenced by iview::CInteractiveShapeBase::GetDisplayChangesMask().
iview::IDisplay* iview::CShapeBase::GetDisplayPtr () const
Get access to currently connected display.
Referenced by iview::CInteractiveShapeBase::GetEditMode(), and iview::CInteractiveShapeBase::GetKeysState().
virtual int iview::CShapeBase::GetLayerType () const virtual
Get layer type of this shape object.
See Also
IViewLayer::LayerType
Implements iview::IShape.
i2d::CVector2d iview::CShapeBase::GetLogPosition (const i2d::CVector2d & screenPosition) const protected
Get logical position based on screen position.
i2d::CVector2d iview::CShapeBase::GetScreenPosition (const i2d::CVector2d & logPosition) const protected
Get screen position based on logical position.
virtual QString iview::CShapeBase::GetShapeDescriptionAt (istd::CIndex2d position) const virtual
Get description to shape at specified position.
Implements iview::ITouchable.
Reimplemented in iview::CImageShape.
ShapeTransformMode iview::CShapeBase::GetTransformMode () const
Get shape transformation mode.
This mode describes which transformation will be used to display shape.
virtual const IColorSchema* iview::CShapeBase::GetUserColorSchema () const virtual
Get color schema from view or user defined.
Implements iview::IShape.
virtual const iview::CScreenTransform& iview::CShapeBase::GetViewToScreenTransform () const protected virtual
virtual void iview::CShapeBase::Invalidate (int changeFlags = 0) virtual
Reimplemented in iview::CPerspectiveCalibrationShape.
Referenced by iview::CTubePolylineShape::SetOrientationVisible().
virtual void iview::CShapeBase::InvalidateBoundingBox () protected virtual
Invalidate bounding box.
You can overload this method to provide validation of your internal attributes, because this method is called from Invalidate(int) and OnDisplayChange(int) methods. Please don't forget base method call in your implementations.
Reimplemented in iview::CParallelogramShape, iview::CTransformableRectangleShape, iview::CArrowShape, iview::CLineShape, and iview::CRectangleShape.
bool iview::CShapeBase::IsBoundingBoxValid () const protected
virtual bool iview::CShapeBase::IsDisplayAccepted (const IDisplay & display) const virtual
Check if this object can be connected to this display.
Implements iview::IVisualizable.
bool iview::CShapeBase::IsDisplayConnected () const protected
Check if display is connected.
virtual ITouchable::TouchState iview::CShapeBase::IsTouched (istd::CIndex2d position) const virtual
Check, if any shape is touched.
When shape is touched, it return also pointer to this shape.
Returns
touch state for the shape, or iview::IInteractiveShape::TS_NONE, when nothing found.
Implements iview::ITouchable.
Reimplemented in iview::CParallelogramShape, iview::CLabelShape, iview::CTubePolylineShape, iview::CTransformableRectangleShape, iview::CPolygonShape, iview::CAffineTransformation2dShape, iview::CAnnulusShape, iview::CImageShape, iview::CCircleShape, iview::CAnnulusSegmentShape, iview::CPolylineShape, iview::CArrowShape, iview::CLineShape, iview::CRectangleShape, iview::CNoneCalibrationShape, iview::CPinShape, and iview::CPerspectiveCalibrationBoundsShape.
virtual bool iview::CShapeBase::IsVisible () const virtual
Check, if this object is visible.
Implements iview::IVisualizable.
virtual bool iview::CShapeBase::OnAttached (imod::IModel * modelPtr) virtual
This call back function will be called, if an observable object is about to be attached.
This function returns a true, if observable object is accepted by the implementation logic of the observer, otherwise the function returns a false.
Reimplemented from imod::CSingleModelObserverBase.
Reimplemented in iview::CParallelogramShape, iview::CTransformableRectangleShape, iview::CLabelShape, iview::CInteractiveShapeBase, iview::CPolygonShape, iview::CAffineTransformation2dShape, iview::CAnnulusShape, iqtgui::TGuiObserverWrap< CViewProviderGuiComp, iview::CImageShape >, iview::CCircleShape, iview::CArrowShape, iview::CImageShape, iview::CLineShape, iview::CRectangleShape, iview::CAnnulusSegmentShape, iview::CPolylineShape, iview::CPinShape, iview::CPolypointShape, iview::COrientedCircleShape, and iview::CSplineShape.
virtual void iview::CShapeBase::OnConnectDisplay (IDisplay * displayPtr) virtual
Called after display is connected.
It can be called only, when display is accepted (
See Also
IsDisplayAccepted()).
Parameters
displayPtr an observer object, which should be informed about all shape changes.
Implements iview::IVisualizable.
virtual bool iview::CShapeBase::OnDetached (imod::IModel * modelPtr) virtual
This call back function will be called, if an observable object is about to be detached.
Reimplemented from imod::CSingleModelObserverBase.
Reimplemented in iview::CInteractiveShapeBase, and iqtgui::TGuiObserverWrap< CViewProviderGuiComp, iview::CImageShape >.
virtual void iview::CShapeBase::OnDisconnectDisplay (IDisplay * displayPtr) virtual
Called after display is disconnected.
Note, that this display must be previously connected.
Parameters
displayPtr a disconnected observer object.
Implements iview::IVisualizable.
virtual bool iview::CShapeBase::OnDisplayChange (int flags) virtual
It informs about changes in display.
It is called e.g. after view transformation change.
Returns
true, if this change follow shape changes.
Implements iview::IVisualizable.
virtual void iview::CShapeBase::OnUpdate (int changeFlags, istd::IPolymorphic * updateParamsPtr) virtual
Reimplemented from imod::CSingleModelObserverBase.
void iview::CShapeBase::SetTransformMode (ShapeTransformMode mode)
Set shape transformation mode.
This mode describes which transformation will be used to display shape.
virtual void iview::CShapeBase::SetUserColorSchema (const IColorSchema * schemaPtr) virtual
Set color schema to draw shape.
Implements iview::IShape.
virtual void iview::CShapeBase::SetVisible (bool state = true) virtual
Make this shape visible.
The documentation for this class was generated from the following file:
Include/iview/CShapeBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy