ACF: imod::TMultiModelObserverBase< ObjectClass > Class Template Reference
imod::TMultiModelObserverBase< ObjectClass > Class Template Reference
[Model/Observer concept]
Basic implementation of an multiple model observer.
#include <TMultiModelObserverBase.h>
Public Types
typedef CMultiModelObserverBase BaseClass
Public Member Functions
ObjectClass * GetObjectPtr (int objectIndex) const
virtual bool OnAttached (imod::IModel *modelPtr)
This call back function will be called, if an observable object is about to be attached.
Detailed Description
template<class ObjectClass>
class imod::TMultiModelObserverBase< ObjectClass >
Basic implementation of an multiple model observer.
Definition at line 21 of file TMultiModelObserverBase.h.
Member Typedef Documentation
template<class ObjectClass > typedef CMultiModelObserverBase imod::TMultiModelObserverBase< ObjectClass >::BaseClass
Definition at line 24 of file TMultiModelObserverBase.h.
Member Function Documentation
template<class ObjectClass > ObjectClass * imod::TMultiModelObserverBase< ObjectClass >::GetObjectPtr (int objectIndex) const [inline]
Definition at line 36 of file TMultiModelObserverBase.h.
References imod::CMultiModelObserverBase::GetModelCount(), imod::CMultiModelObserverBase::GetModelPtr(), and I_ASSERT.
template<class ObjectClass > bool imod::TMultiModelObserverBase< ObjectClass >::OnAttached (imod::IModel * modelPtr) [inline, virtual]
This call back function will be called, if an observable object is about to be attached.
This function returns a true, if observable object is accepted by the implementation logic of the observer, otherwise the function returns a false.
Reimplemented from imod::CMultiModelObserverBase.
Definition at line 48 of file TMultiModelObserverBase.h.
References NULL, and imod::CMultiModelObserverBase::OnAttached().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/imod/TMultiModelObserverBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy