ACF: istd::CFastBinaryIndex Class Reference
istd::CFastBinaryIndex Class Reference
#include <CFastBinaryIndex.h>
Classes
class Iterator
Public Types
enum { MAX_ELEMENTS_COUNT = 31 }
typedef int IndexType
Public Member Functions
CFastBinaryIndex ()
Default constructor without member initialization.
CFastBinaryIndex (int size, int value=0)
Constructor initializing all member to specified value.
CFastBinaryIndex (I_DWORD bits, int size, int dummy)
Constructor initializing all internal members.
CFastBinaryIndex (const CFastBinaryIndex &index)
Copy constructor.
bool IsValid () const
Check if this index is valid.
bool IsZero () const
Check if this index point at zero element.
void Reset ()
Reset this object.
void Clear ()
Set all components to 0 (false).
bool IsDimensionsCountFixed () const
Check, if number dimensions is fixed.
int GetDimensionsCount () const
Get number of dimensions of this index.
bool SetDimensionsCount (int count)
Set number of dimensions of this index.
int GetAt (int index) const
Get element stored at specified index.
void SetAt (int index, int value)
Set element at specified index.
I_DWORD GetBits () const
Get bit coded value of this index.
void SetAllTo (int value)
Set all components to specified value.
bool IncreaseAt (int index)
Increase single component at specified position.
bool DecreaseAt (int index)
Decrease single component at specified position.
int GetProductVolume () const
Get total number of elements if this index is treated as size.
bool IsInside (const CFastBinaryIndex &boundaries) const
Check if index is inside boundaries.
bool Increase (const CFastBinaryIndex &boundaries)
Increase this index inside the boundaries.
bool Decrease (const CFastBinaryIndex &boundaries)
Decrese this index inside the boundaries.
Iterator Begin () const
Get begin value of element access iterator.
Iterator End () const
Get end value of element access iterator.
int operator[] (int index) const
bool operator== (const CFastBinaryIndex &index) const
bool operator!= (const CFastBinaryIndex &index) const
Detailed Description
Definition at line 12 of file CFastBinaryIndex.h.
Member Typedef Documentation
typedef int istd::CFastBinaryIndex::IndexType
Definition at line 15 of file CFastBinaryIndex.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
MAX_ELEMENTS_COUNT
Definition at line 17 of file CFastBinaryIndex.h.
Constructor & Destructor Documentation
istd::CFastBinaryIndex::CFastBinaryIndex () [inline]
Default constructor without member initialization.
Definition at line 192 of file CFastBinaryIndex.h.
istd::CFastBinaryIndex::CFastBinaryIndex (int size, int value = 0) [inline, explicit]
Constructor initializing all member to specified value.
Definition at line 198 of file CFastBinaryIndex.h.
References SetAllTo().
istd::CFastBinaryIndex::CFastBinaryIndex (I_DWORD bits, int size, int dummy) [inline, explicit]
Constructor initializing all internal members.
Parameters:
bits bit coded value of this index. The index of higher set bit must be smaller than 'size' value.
size number of components of index.
dummy not used parameter using to distinguish between this constructor and the previous one.
Definition at line 206 of file CFastBinaryIndex.h.
References I_ASSERT, and istd::CBitManip::instance.
istd::CFastBinaryIndex::CFastBinaryIndex (const CFastBinaryIndex & index) [inline]
Copy constructor.
Definition at line 213 of file CFastBinaryIndex.h.
References I_ASSERT, and MAX_ELEMENTS_COUNT.
Member Function Documentation
CFastBinaryIndex::Iterator istd::CFastBinaryIndex::Begin () const [inline]
Get begin value of element access iterator.
Please refer to general description of ACF iterators, STL iterators or Qt iterators concept.
Definition at line 366 of file CFastBinaryIndex.h.
void istd::CFastBinaryIndex::Clear () [inline]
Set all components to 0 (false).
Definition at line 240 of file CFastBinaryIndex.h.
bool istd::CFastBinaryIndex::Decrease (const CFastBinaryIndex & boundaries) [inline]
Decrese this index inside the boundaries.
Returns:
in this implementation always false.
Definition at line 354 of file CFastBinaryIndex.h.
bool istd::CFastBinaryIndex::DecreaseAt (int index) [inline]
Decrease single component at specified position.
Parameters:
index index of component should be increased. It must be valid.
Returns:
true if bit at index was enabled and it was possible to realize increasing.
Definition at line 327 of file CFastBinaryIndex.h.
References I_ASSERT.
CFastBinaryIndex::Iterator istd::CFastBinaryIndex::End () const [inline]
Get end value of element access iterator.
Please refer to general description of ACF iterators, STL iterators or Qt iterators concept.
Definition at line 372 of file CFastBinaryIndex.h.
int istd::CFastBinaryIndex::GetAt (int index) const [inline]
Get element stored at specified index.
Definition at line 272 of file CFastBinaryIndex.h.
References I_ASSERT.
Referenced by istd::CFastBinaryIndex::Iterator::operator*(), and operator[]().
I_DWORD istd::CFastBinaryIndex::GetBits () const [inline]
Get bit coded value of this index.
Definition at line 295 of file CFastBinaryIndex.h.
int istd::CFastBinaryIndex::GetDimensionsCount () const [inline]
Get number of dimensions of this index.
Definition at line 253 of file CFastBinaryIndex.h.
int istd::CFastBinaryIndex::GetProductVolume () const [inline]
Get total number of elements if this index is treated as size.
Returns:
multiplication of all elements.
Definition at line 360 of file CFastBinaryIndex.h.
bool istd::CFastBinaryIndex::Increase (const CFastBinaryIndex & boundaries) [inline]
Increase this index inside the boundaries.
Returns:
in this implementation always false.
Definition at line 348 of file CFastBinaryIndex.h.
bool istd::CFastBinaryIndex::IncreaseAt (int index) [inline]
Increase single component at specified position.
Parameters:
index index of component should be increased. It must be valid.
Returns:
true if bit at index was disabled and it was possible to realize increasing.
Definition at line 312 of file CFastBinaryIndex.h.
References I_ASSERT.
bool istd::CFastBinaryIndex::IsDimensionsCountFixed () const [inline]
Check, if number dimensions is fixed.
It is provided for template implementations. It returns always true.
Definition at line 247 of file CFastBinaryIndex.h.
bool istd::CFastBinaryIndex::IsInside (const CFastBinaryIndex & boundaries) const [inline]
Check if index is inside boundaries.
Index is inside boundaries, if all its components are smaller than according boundary components.
Definition at line 342 of file CFastBinaryIndex.h.
bool istd::CFastBinaryIndex::IsValid () const [inline]
Check if this index is valid.
Index is valid, if all its components are bigger or equal 0. This method is provided for template compatibility with other imlementations. It returns always true.
Definition at line 221 of file CFastBinaryIndex.h.
bool istd::CFastBinaryIndex::IsZero () const [inline]
Check if this index point at zero element.
In other words, it checks if all components are 0.
Definition at line 227 of file CFastBinaryIndex.h.
bool istd::CFastBinaryIndex::operator!= (const CFastBinaryIndex & index) const [inline]
Definition at line 390 of file CFastBinaryIndex.h.
bool istd::CFastBinaryIndex::operator== (const CFastBinaryIndex & index) const [inline]
Definition at line 384 of file CFastBinaryIndex.h.
int istd::CFastBinaryIndex::operator[] (int index) const [inline]
Definition at line 378 of file CFastBinaryIndex.h.
References GetAt().
void istd::CFastBinaryIndex::Reset () [inline]
Reset this object.
For this implementation, it does the same as clear.
See also:
Clear()
Definition at line 233 of file CFastBinaryIndex.h.
void istd::CFastBinaryIndex::SetAllTo (int value) [inline]
Set all components to specified value.
Definition at line 301 of file CFastBinaryIndex.h.
Referenced by CFastBinaryIndex().
void istd::CFastBinaryIndex::SetAt (int index, int value) [inline]
Set element at specified index.
Definition at line 281 of file CFastBinaryIndex.h.
References I_ASSERT.
bool istd::CFastBinaryIndex::SetDimensionsCount (int count) [inline]
Set number of dimensions of this index.
It is provided to allows template implementations to use fixed-size or variable arrays.
Parameters:
count number of dimensions will be set.
Returns:
true, if number of set dimensions equals template parameter or false if isn't.
Definition at line 259 of file CFastBinaryIndex.h.
References MAX_ELEMENTS_COUNT.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/istd/CFastBinaryIndex.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy