iattr::TAttribute< Value > Class Template Reference
iattr::TAttribute< Value > Class Template Reference
Template implementation of an atomic attribute.
#include <TAttribute.h>
Public Types
typedef Value ValueType
typedef TAttribute< Value > AttributeType
typedef iattr::CAttributeBase BaseClass
Public Member Functions
TAttribute ()
TAttribute (iattr::IAttributesManager *attributeOwnerPtr, const std::string &attributeName, const std::string &attributeDescription, int attributeFlags, int changeFlags=0, const ValueType &defaultValue=ValueType())
const Value & GetValue () const
void SetValue (const Value &value)
void ResetValue ()
virtual const iser::IObject * GetDefaultAttributePtr () const
virtual const std::string & GetFactoryId () const
virtual bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
Static Public Member Functions
static const std::string & GetTypeName ()
Protected Attributes
Value m_value
istd::TDelPtr< AttributeType > m_defaultAttributeValuePtr
Detailed Description
template<typename Value>
class iattr::TAttribute< Value >
Template implementation of an atomic attribute.
Definition at line 23 of file TAttribute.h.
Member Typedef Documentation
template<typename Value > typedef TAttribute<Value> iattr::TAttribute< Value >::AttributeType
Definition at line 27 of file TAttribute.h.
template<typename Value > typedef iattr::CAttributeBase iattr::TAttribute< Value >::BaseClass
Reimplemented from iser::TCopySerializedWrap< iattr::IAttribute >.
Definition at line 28 of file TAttribute.h.
template<typename Value > typedef Value iattr::TAttribute< Value >::ValueType
Definition at line 26 of file TAttribute.h.
Constructor & Destructor Documentation
template<typename Value > iattr::TAttribute< Value >::TAttribute ()
Definition at line 69 of file TAttribute.h.
template<typename Value > iattr::TAttribute< Value >::TAttribute (iattr::IAttributesManager * attributeOwnerPtr, const std::string & attributeName, const std::string & attributeDescription, int attributeFlags, int changeFlags = 0, const ValueType & defaultValue = ValueType())
Definition at line 76 of file TAttribute.h.
References istd::TPointerBase< Type >::IsValid(), iattr::TAttribute< Value >::m_defaultAttributeValuePtr, and istd::TDelPtr< Type, Accessor >::SetPtr().
Member Function Documentation
template<typename Value > const iser::IObject * iattr::TAttribute< Value >::GetDefaultAttributePtr () const [virtual]
Definition at line 124 of file TAttribute.h.
template<typename Value > const std::string & iattr::TAttribute< Value >::GetFactoryId () const [virtual]
Reimplemented from iser::IObject.
Definition at line 133 of file TAttribute.h.
template<typename Value > const std::string & iattr::TAttribute< Value >::GetTypeName () [static]
Definition at line 160 of file TAttribute.h.
template<typename Value > const Value & iattr::TAttribute< Value >::GetValue () const
Definition at line 95 of file TAttribute.h.
template<typename Value > void iattr::TAttribute< Value >::ResetValue ()
Definition at line 113 of file TAttribute.h.
template<typename Value > bool iattr::TAttribute< Value >::Serialize (iser::IArchive & archive) [virtual]
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See also:
iser::IArchive
Implements iser::ISerializable.
Definition at line 142 of file TAttribute.h.
References iser::IArchive::BeginTag(), iser::IArchive::EndTag(), and iser::IArchive::Process().
template<typename Value > void iattr::TAttribute< Value >::SetValue (const Value & value)
Definition at line 102 of file TAttribute.h.
Member Data Documentation
template<typename Value > istd::TDelPtr<AttributeType> iattr::TAttribute< Value >::m_defaultAttributeValuePtr [mutable, protected]
Definition at line 59 of file TAttribute.h.
Referenced by iattr::TAttribute< Value >::TAttribute().
template<typename Value > Value iattr::TAttribute< Value >::m_value [protected]
Definition at line 57 of file TAttribute.h.
The documentation for this class was generated from the following file:
Include/iattr/TAttribute.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy