iqt2d::TSceneExtenderCompBase< Base > Class Template Reference
iqt2d::TSceneExtenderCompBase< Base > Class Template Reference
#include <TSceneExtenderCompBase.h>
Public Types
typedef Base BaseClass
Public Member Functions
virtual void AddItemsToScene (IViewProvider *providerPtr, int flags)
Called when items should be added to specified scene.
virtual void RemoveItemsFromScene (IViewProvider *providerPtr)
Called when items should be removed from specified scene.
Protected Types
typedef istd::TPointerVector
< iview::IShape > Shapes
typedef std::map
< IViewProvider *, Shapes > ShapesMap
Protected Member Functions
bool IsSceneIdSupported (int id) const
const ShapesMap & GetShapesMap () const
virtual void CreateShapes (int sceneId, Shapes &result)=0
Detailed Description
template<class Base>
class iqt2d::TSceneExtenderCompBase< Base >
Definition at line 23 of file TSceneExtenderCompBase.h.
Member Typedef Documentation
template<class Base> typedef Base iqt2d::TSceneExtenderCompBase< Base >::BaseClass
Reimplemented in iqt2d::CAnnulusSegmentParamsGuiComp, iqt2d::CAnnulusParamsGuiComp, iqt2d::CCircleParamsGuiComp, iqt2d::CLine2dParamsGuiComp, iqt2d::CQuadrangleParamsGuiComp, iqt2d::CRectangleParamsGuiComp, iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >, iqt2d::TShapeParamsGuiCompBase< Ui::CQuadrangleParamsGuiComp, iview::CInteractiveParallelogramShape, i2d::CQuadrangle >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusSegmentParamsGuiComp, iview::CInteractiveAnnulusSegmentShape, i2d::CAnnulusSegment >, iqt2d::TShapeParamsGuiCompBase< Ui::CRectangleParamsGuiComp, iview::CInteractiveRectangleShape, i2d::CRectangle >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusParamsGuiComp, iview::CInteractiveAnnulusShape, i2d::CAnnulus >, iqt2d::TShapeParamsGuiCompBase< Ui::CLine2dParamsGuiComp, iview::CInteractiveArrowShape, i2d::CLine2d >, and iqt2d::TShapeParamsGuiCompBase< Ui::CCircleParamsGuiComp, iview::CInteractiveCircleShape, i2d::CCircle >.
Definition at line 26 of file TSceneExtenderCompBase.h.
template<class Base> typedef istd::TPointerVector<iview::IShape> iqt2d::TSceneExtenderCompBase< Base >::Shapes [protected]
Reimplemented in iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >, iqt2d::TShapeParamsGuiCompBase< Ui::CQuadrangleParamsGuiComp, iview::CInteractiveParallelogramShape, i2d::CQuadrangle >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusSegmentParamsGuiComp, iview::CInteractiveAnnulusSegmentShape, i2d::CAnnulusSegment >, iqt2d::TShapeParamsGuiCompBase< Ui::CRectangleParamsGuiComp, iview::CInteractiveRectangleShape, i2d::CRectangle >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusParamsGuiComp, iview::CInteractiveAnnulusShape, i2d::CAnnulus >, iqt2d::TShapeParamsGuiCompBase< Ui::CLine2dParamsGuiComp, iview::CInteractiveArrowShape, i2d::CLine2d >, and iqt2d::TShapeParamsGuiCompBase< Ui::CCircleParamsGuiComp, iview::CInteractiveCircleShape, i2d::CCircle >.
Definition at line 39 of file TSceneExtenderCompBase.h.
template<class Base> typedef std::map<IViewProvider*, Shapes> iqt2d::TSceneExtenderCompBase< Base >::ShapesMap [protected]
Reimplemented in iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >, iqt2d::TShapeParamsGuiCompBase< Ui::CQuadrangleParamsGuiComp, iview::CInteractiveParallelogramShape, i2d::CQuadrangle >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusSegmentParamsGuiComp, iview::CInteractiveAnnulusSegmentShape, i2d::CAnnulusSegment >, iqt2d::TShapeParamsGuiCompBase< Ui::CRectangleParamsGuiComp, iview::CInteractiveRectangleShape, i2d::CRectangle >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusParamsGuiComp, iview::CInteractiveAnnulusShape, i2d::CAnnulus >, iqt2d::TShapeParamsGuiCompBase< Ui::CLine2dParamsGuiComp, iview::CInteractiveArrowShape, i2d::CLine2d >, and iqt2d::TShapeParamsGuiCompBase< Ui::CCircleParamsGuiComp, iview::CInteractiveCircleShape, i2d::CCircle >.
Definition at line 40 of file TSceneExtenderCompBase.h.
Member Function Documentation
template<class Base > void iqt2d::TSceneExtenderCompBase< Base >::AddItemsToScene (IViewProvider * providerPtr, int flags) [virtual]
Called when items should be added to specified scene.
Implements iqt2d::IViewExtender.
Definition at line 61 of file TSceneExtenderCompBase.h.
References iview::IShapeView::ConnectBackgroundShape(), iview::IShapeView::ConnectShape(), istd::TPointerVector< Pointer, AccessAdapter >::GetAt(), istd::TPointerVector< Pointer, AccessAdapter >::GetCount(), iqt2d::IViewProvider::GetView(), iqt2d::IViewProvider::GetViewId(), I_ASSERT, and NULL.
template<class Base> virtual void iqt2d::TSceneExtenderCompBase< Base >::CreateShapes (int sceneId, Shapes & result) [protected, pure virtual]
Implemented in iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >, iqt2d::TShapeParamsGuiCompBase< Ui::CQuadrangleParamsGuiComp, iview::CInteractiveParallelogramShape, i2d::CQuadrangle >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusSegmentParamsGuiComp, iview::CInteractiveAnnulusSegmentShape, i2d::CAnnulusSegment >, iqt2d::TShapeParamsGuiCompBase< Ui::CRectangleParamsGuiComp, iview::CInteractiveRectangleShape, i2d::CRectangle >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusParamsGuiComp, iview::CInteractiveAnnulusShape, i2d::CAnnulus >, iqt2d::TShapeParamsGuiCompBase< Ui::CLine2dParamsGuiComp, iview::CInteractiveArrowShape, i2d::CLine2d >, and iqt2d::TShapeParamsGuiCompBase< Ui::CCircleParamsGuiComp, iview::CInteractiveCircleShape, i2d::CCircle >.
template<class Base > const TSceneExtenderCompBase< Base >::ShapesMap & iqt2d::TSceneExtenderCompBase< Base >::GetShapesMap () const [protected]
Definition at line 146 of file TSceneExtenderCompBase.h.
template<class Base > bool iqt2d::TSceneExtenderCompBase< Base >::IsSceneIdSupported (int id) const [protected]
Definition at line 127 of file TSceneExtenderCompBase.h.
template<class Base > void iqt2d::TSceneExtenderCompBase< Base >::RemoveItemsFromScene (IViewProvider * providerPtr) [virtual]
Called when items should be removed from specified scene.
Implements iqt2d::IViewExtender.
Definition at line 95 of file TSceneExtenderCompBase.h.
References iview::IShapeObserver::DisconnectShape(), istd::TPointerVector< Pointer, AccessAdapter >::GetAt(), istd::TPointerVector< Pointer, AccessAdapter >::GetCount(), iqt2d::IViewProvider::GetView(), I_ASSERT, and NULL.
The documentation for this class was generated from the following file:
Include/iqt2d/TSceneExtenderCompBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy