ACF: istd::CVarIndex Class Reference
istd::CVarIndex Class Reference
Multidimensional index used to addressing index.
#include <CVarIndex.h>
Public Types
typedef int IndexType
typedef std::vector< int >
::iterator Iterator
Public Member Functions
CVarIndex ()
Default constructor without member initialization.
CVarIndex (int size, int value=0)
Constructor initializing all member to specified value.
CVarIndex (const CVarIndex &index)
Copy constructor.
template<int Dimensions>
CVarIndex (const TIndex< Dimensions > index)
Convert fixed-size index to this object.
bool IsZero () const
Check if this index point at zero element.
bool IsSizeEmpty () const
Check if this index interpreted as size is empty.
void Reset ()
Reset this object.
void Clear ()
Set all components to 0.
bool IsDimensionsCountFixed () const
Check, if number dimensions is fixed.
int GetDimensionsCount () const
Get number of dimensions of this index.
bool SetDimensionsCount (int count)
Set number of dimensions of this index.
int GetAt (int index) const
Get element stored at specified index.
void SetAt (int index, int value)
Set element at specified index.
void SetAllTo (int value)
Set all components to specified value.
bool IncreaseAt (int index)
Increase single component at specified position.
bool DecreaseAt (int index)
Decrease single component at specified position.
bool IsInside (const CVarIndex &boundaries) const
Check if index is inside boundaries.
bool Increase (const CVarIndex &boundaries)
Increase this index inside the boundaries.
bool Decrease (const CVarIndex &boundaries)
Decrese this index inside the boundaries.
int GetProductVolume () const
Get total number of elements if this index is treated as size.
int GetMinDimensionsCount () const
Get minimal number of dimensions needed to to represent this index.
Iterator Begin () const
Get begin value of element access iterator.
Iterator End () const
Get end value of element access iterator.
int operator[] (int index) const
Get access to single index components.
int & operator[] (int index)
Get access to single index components.
bool operator== (const CVarIndex &index) const
bool operator!= (const CVarIndex &index) const
bool operator< (const CVarIndex &index) const
bool operator> (const CVarIndex &index) const
bool operator<= (const CVarIndex &index) const
bool operator>= (const CVarIndex &index) const
CVarIndex & operator+= (const CVarIndex &index)
CVarIndex & operator-= (const CVarIndex &index)
Detailed Description
Multidimensional index used to addressing index.
Definition at line 17 of file CVarIndex.h.
Member Typedef Documentation
typedef int istd::CVarIndex::IndexType
Definition at line 20 of file CVarIndex.h.
typedef std::vector<int>::iterator istd::CVarIndex::Iterator
Definition at line 21 of file CVarIndex.h.
Constructor & Destructor Documentation
istd::CVarIndex::CVarIndex ()
Default constructor without member initialization.
istd::CVarIndex::CVarIndex (int size, int value = 0) [explicit]
Constructor initializing all member to specified value.
istd::CVarIndex::CVarIndex (const CVarIndex & index)
Copy constructor.
template<int Dimensions> istd::CVarIndex::CVarIndex (const TIndex< Dimensions > index) [inline]
Convert fixed-size index to this object.
Definition at line 329 of file CVarIndex.h.
Member Function Documentation
CVarIndex::Iterator istd::CVarIndex::Begin () const [inline]
Get begin value of element access iterator.
Please refer to general description of ACF iterators, STL iterators or Qt iterators concept.
Definition at line 274 of file CVarIndex.h.
void istd::CVarIndex::Clear ()
Set all components to 0.
bool istd::CVarIndex::Decrease (const CVarIndex & boundaries)
Decrese this index inside the boundaries.
Please note, that the number of dimensions for this index will not be changed and this operation can be unclear when number of dimensions differs from boundaries number of dimensions.
Returns:
false, if decrease wasn't possible (e.g. overflow).
Referenced by istd::TVarArray< Element >::Iterator::operator--().
bool istd::CVarIndex::DecreaseAt (int index) [inline]
Decrease single component at specified position.
Parameters:
index index of component should be increased. It must be valid.
Returns:
true if success. It is provided for template implementations. In this case it returns always true.
Definition at line 235 of file CVarIndex.h.
References I_ASSERT.
CVarIndex::Iterator istd::CVarIndex::End () const [inline]
Get end value of element access iterator.
Please refer to general description of ACF iterators, STL iterators or Qt iterators concept.
Definition at line 280 of file CVarIndex.h.
int istd::CVarIndex::GetAt (int index) const [inline]
Get element stored at specified index.
Definition at line 206 of file CVarIndex.h.
References I_ASSERT.
Referenced by GetMinDimensionsCount(), GetProductVolume(), and operator[]().
int istd::CVarIndex::GetDimensionsCount () const [inline]
Get number of dimensions of this index.
Definition at line 192 of file CVarIndex.h.
Referenced by istd::TVarArray< Element >::GetDimensionsCount(), istd::TVarArray< Element >::GetElementIndex(), GetMinDimensionsCount(), GetProductVolume(), istd::TVarArray< Element >::GetSize(), istd::TVarArray< Element >::SetSize(), and istd::TVarArray< Element >::UpdateElementsSize().
int istd::CVarIndex::GetMinDimensionsCount () const [inline]
Get minimal number of dimensions needed to to represent this index.
In other words this is index of last non-zero component + 1.
Definition at line 260 of file CVarIndex.h.
References GetAt(), and GetDimensionsCount().
int istd::CVarIndex::GetProductVolume () const [inline]
Get total number of elements if this index is treated as size.
Returns:
multiplication of all elements.
Definition at line 246 of file CVarIndex.h.
References GetAt(), and GetDimensionsCount().
bool istd::CVarIndex::Increase (const CVarIndex & boundaries)
Increase this index inside the boundaries.
Please note, that the number of dimensions for this index will not be changed and this operation can be unclear when number of dimensions differs from boundaries number of dimensions.
Returns:
false, if increase wasn't possible (e.g. overflow).
Referenced by istd::TVarArray< Element >::Iterator::operator++().
bool istd::CVarIndex::IncreaseAt (int index) [inline]
Increase single component at specified position.
Parameters:
index index of component should be increased. It must be valid.
Returns:
true if success. It is provided for template implementations. In this case it returns always true.
Definition at line 224 of file CVarIndex.h.
References I_ASSERT.
bool istd::CVarIndex::IsDimensionsCountFixed () const [inline]
Check, if number dimensions is fixed.
It is provided for template implementations. It returns always false.
Definition at line 186 of file CVarIndex.h.
bool istd::CVarIndex::IsInside (const CVarIndex & boundaries) const
Check if index is inside boundaries.
Index is inside boundaries, if all its components are smaller than according boundary components.
Referenced by istd::TVarArray< Element >::GetAt(), istd::TVarArray< Element >::Iterator::Iterator(), istd::TVarArray< Element >::Iterator::operator*(), istd::TVarArray< Element >::Iterator::operator->(), and istd::TVarArray< Element >::SetAt().
bool istd::CVarIndex::IsSizeEmpty () const
Check if this index interpreted as size is empty.
It means, it returns true, is some of components is less or equal 0.
bool istd::CVarIndex::IsZero () const
Check if this index point at zero element.
In other words, it checks if all components are 0.
bool istd::CVarIndex::operator!= (const CVarIndex & index) const
CVarIndex& istd::CVarIndex::operator+= (const CVarIndex & index)
CVarIndex& istd::CVarIndex::operator-= (const CVarIndex & index)
bool istd::CVarIndex::operator< (const CVarIndex & index) const [inline]
Definition at line 302 of file CVarIndex.h.
bool istd::CVarIndex::operator<= (const CVarIndex & index) const [inline]
Definition at line 314 of file CVarIndex.h.
bool istd::CVarIndex::operator== (const CVarIndex & index) const
Referenced by istd::TVarArray< Element >::Iterator::operator==().
bool istd::CVarIndex::operator> (const CVarIndex & index) const [inline]
Definition at line 308 of file CVarIndex.h.
bool istd::CVarIndex::operator>= (const CVarIndex & index) const [inline]
Definition at line 320 of file CVarIndex.h.
int & istd::CVarIndex::operator[] (int index) [inline]
Get access to single index components.
Definition at line 292 of file CVarIndex.h.
References I_ASSERT.
int istd::CVarIndex::operator[] (int index) const [inline]
Get access to single index components.
Definition at line 286 of file CVarIndex.h.
References GetAt().
void istd::CVarIndex::Reset ()
Reset this object.
For this (variable size) implementation, it set dimension size to 0.
Referenced by istd::TVarArray< Element >::Reset().
void istd::CVarIndex::SetAllTo (int value)
Set all components to specified value.
void istd::CVarIndex::SetAt (int index, int value) [inline]
Set element at specified index.
Definition at line 215 of file CVarIndex.h.
References I_ASSERT.
bool istd::CVarIndex::SetDimensionsCount (int count) [inline]
Set number of dimensions of this index.
It is provided to allows template implementations to use fixed-size or variable arrays.
Parameters:
count number of dimensions will be set.
Returns:
always true.
Definition at line 198 of file CVarIndex.h.
Referenced by istd::TVarArray< Element >::SetDimensionsCount().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/istd/CVarIndex.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy