iview::CPerspectiveCalibration Class Reference
iview::CPerspectiveCalibration Class Reference
Perspective calibration.
#include <CPerspectiveCalibration.h>
Public Member Functions
CPerspectiveCalibration ()
void Reset ()
Reset this calibration, set to be identity transform.
void SetCameraParams (const i2d::CVector2d &viewOpticalCenter, const i2d::CVector2d &pixelAngleTangents)
const i2d::CRectangle & GetBounds () const
Get logical coordinates bounds.
virtual void SetBounds (const i2d::CRectangle &bounds)
Set locical coordinates bounds.
const i3d::CVector3d & GetLogAxisGetX () const
virtual void SetLogAxisX (const i3d::CVector3d &value)
const i3d::CVector3d & GetLogAxisGetY () const
virtual void SetLogAxisY (const i3d::CVector3d &value)
const i3d::CVector3d & GetLogCenter () const
virtual void SetLogCenter (const i3d::CVector3d &value)
const i2d::CVector2d & GetViewCenter () const
void SetViewCenter (const i2d::CVector2d &center)
void ApplyLeft (const i2d::CAffine2d &transform)
void ResetAxes ()
bool DoCalibration (const i2d::CVector2d *logicalPoints, const i2d::CVector2d *viewPoints, int pointsCount)
Calculte calibration using set of two set of points.
virtual bool GetLogDerivative (const i2d::CVector2d &viewPosition, const i2d::CVector2d &viewDirection, double &result) const
bool operator== (const CPerspectiveCalibration &calib) const
bool operator!= (const CPerspectiveCalibration &calib) const
virtual int GetTransformationFlags () const
Get flags of describing type of this transformation.
virtual bool GetDistance (const i2d::CVector2d &origPos1, const i2d::CVector2d &origPos2, double &result, ExactnessMode mode=EM_NONE) const
Compute a shortness distance in transformed coordinations.
virtual bool GetPositionAt (const i2d::CVector2d &origPosition, i2d::CVector2d &result, ExactnessMode mode=EM_NONE) const
Get position after transformation.
virtual bool GetInvPositionAt (const i2d::CVector2d &transfPosition, i2d::CVector2d &result, ExactnessMode mode=EM_NONE) const
Get position after transformation.
virtual bool GetLocalTransform (const i2d::CVector2d &origPosition, i2d::CAffine2d &result, ExactnessMode mode=EM_NONE) const
Get local transformation (from original to transformed coordinate system) at some original position.
virtual bool GetLocalInvTransform (const i2d::CVector2d &transfPosition, i2d::CAffine2d &result, ExactnessMode mode=EM_NONE) const
Get local transformation (from transformed to original coordinate system) at some transformed position.
virtual bool GetInvValueAt (const i2d::CVector2d &argument, i2d::CVector2d &result) const
virtual i2d::CVector2d GetInvValueAt (const i2d::CVector2d &argument) const
virtual bool GetValueAt (const i2d::CVector2d &argument, i2d::CVector2d &result) const
virtual i2d::CVector2d GetValueAt (const i2d::CVector2d &argument) const
virtual bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
Public Member Functions inherited from i2d::CNoneCalibration2d
virtual const imath::IUnitInfo * GetArgumentUnitInfo () const
Get unit description of calibration input (transformation function argument).
virtual const imath::IUnitInfo * GetResultUnitInfo () const
Get unit description of calibration output (transformation function result).
virtual const ICalibration2d * CreateCombinedCalibration (const ICalibration2d &calibration) const
Create new calibration being combination of this calibration and the second one.
Public Member Functions inherited from imath::TISurjectFunction< CVector2d, CVector2d >
virtual bool GetInvValueAt (const CVector2d &argument, CVector2d &result) const =0
Get inverted function value.
virtual CVector2d GetInvValueAt (const CVector2d &argument) const =0
Get inverted function value.
Public Member Functions inherited from imath::TIMathFunction< CVector2d, CVector2d >
virtual bool GetValueAt (const CVector2d &argument, CVector2d &result) const =0
Get function value for specified argument value.
virtual CVector2d GetValueAt (const CVector2d &argument) const =0
Get function value for specified argument value.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Public Member Functions inherited from iser::ISerializable
virtual quint32 GetMinimalVersion (int versionId) const
Get minimal needed version to correct storing of this data.
Public Member Functions inherited from istd::IChangeable
virtual void BeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Starts the change transaction.
virtual void EndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Ends the change transaction.
virtual int GetSupportedOperations () const
Get set of flags for supported operations.
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Copy this object from another one.
virtual bool IsEqual (const IChangeable &object) const
Compare this object with another object.
virtual IChangeable * CloneMe (CompatibilityMode mode=CM_WITHOUT_REFS) const
Make a copy of this object.
virtual bool ResetData (CompatibilityMode mode=CM_WITHOUT_REFS)
Reset data to its default state.
Protected Member Functions
i2d::CVector2d GetNormPosition (const i2d::CVector2d &viewPosition) const
i2d::CVector2d GetViewPosition (const i2d::CVector2d &normPosition) const
bool CalcAllAxes (const i2d::CVector2d *logicalPoints, const i2d::CVector2d *viewPoints, int pointsCount, i3d::CVector3d &newAxisX, i3d::CVector3d &newAxisY, i3d::CVector3d &newCenter)
bool CalcAxes2d (const i2d::CVector2d *logicalPoints, const i2d::CVector2d *viewPoints, int pointsCount, i3d::CVector3d &newAxisX, i3d::CVector3d &newAxisY, i3d::CVector3d &newCenter)
bool CalcRotationOY (const i2d::CVector2d *logicalPoints, const i2d::CVector2d *viewPoints, int pointsCount, i3d::CVector3d &newAxisX, i3d::CVector3d &newAxisY, i3d::CVector3d &newCenter)
bool CalcRotationOX (const i2d::CVector2d *logicalPoints, const i2d::CVector2d *viewPoints, int pointsCount, i3d::CVector3d &newAxisX, i3d::CVector3d &newAxisY, i3d::CVector3d &newCenter)
Protected Member Functions inherited from istd::IChangeable
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for begin change event.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for end change event.
Additional Inherited Members
Public Types inherited from i2d::ITransformation2d
enum ExactnessMode { EM_NONE, EM_EXACT, EM_VISUAL, EM_ANY }
enum TransformationFlags {
TF_FORWARD = 1 << 0, TF_INVERTED = 1 << 1, TF_INJECTIVE = 1 << 2, TF_SURJECTIVE = 1 << 3,
TF_PRESERVE_NULL = 1 << 4, TF_PRESERVE_DISTANCE = 1 << 5, TF_PRESERVE_ANGLE = 1 << 6, TF_AFFINE = 1 << 7,
TF_CONTINUES = 1 << 8
}
Public Types inherited from imath::TIMathFunction< CVector2d, CVector2d >
typedef CVector2d ArgumentType
typedef CVector2d ResultType
Public Types inherited from istd::IChangeable
enum ChangeFlags {
CF_ACF_INTERNAL = 1 << 0, CF_MODEL = 1 << 1, CF_ABORTED = 1 << 2, CF_DELEGATED = 1 << 3,
CF_NO_UNDO = 1 << 5
}
enum SupportedOperations {
SO_NONE = 0, SO_OBSERVE = 1, SO_COPY = 2, SO_CLONE = 4,
SO_COMPARE = 8
}
Flags for supported operations.
enum CompatibilityMode { CM_STRICT, CM_WITHOUT_REFS, CM_WITH_REFS, CM_CONVERT }
Control how relationship betweeen objects are interpreted.
Static Public Member Functions inherited from i2d::CNoneCalibration2d
static const CNoneCalibration2d & GetInstance ()
Detailed Description
Perspective calibration.
This class describe a perspective calibration. You need this calibration when your logical coordination system is flat, but not orthogonal to camera axis. Please note, that logical coordination system represents only finite rectangle area, you can set using SetBounds(const i2d::CRectangle&) method.
Definition at line 25 of file CPerspectiveCalibration.h.
Constructor & Destructor Documentation
iview::CPerspectiveCalibration::CPerspectiveCalibration ()
Member Function Documentation
void iview::CPerspectiveCalibration::ApplyLeft (const i2d::CAffine2d & transform)
bool iview::CPerspectiveCalibration::CalcAllAxes (const i2d::CVector2d * logicalPoints, const i2d::CVector2d * viewPoints, int pointsCount, i3d::CVector3d & newAxisX, i3d::CVector3d & newAxisY, i3d::CVector3d & newCenter) protected
bool iview::CPerspectiveCalibration::CalcAxes2d (const i2d::CVector2d * logicalPoints, const i2d::CVector2d * viewPoints, int pointsCount, i3d::CVector3d & newAxisX, i3d::CVector3d & newAxisY, i3d::CVector3d & newCenter) protected
bool iview::CPerspectiveCalibration::CalcRotationOX (const i2d::CVector2d * logicalPoints, const i2d::CVector2d * viewPoints, int pointsCount, i3d::CVector3d & newAxisX, i3d::CVector3d & newAxisY, i3d::CVector3d & newCenter) protected
bool iview::CPerspectiveCalibration::CalcRotationOY (const i2d::CVector2d * logicalPoints, const i2d::CVector2d * viewPoints, int pointsCount, i3d::CVector3d & newAxisX, i3d::CVector3d & newAxisY, i3d::CVector3d & newCenter) protected
bool iview::CPerspectiveCalibration::DoCalibration (const i2d::CVector2d * logicalPoints, const i2d::CVector2d * viewPoints, int pointsCount)
Calculte calibration using set of two set of points.
const i2d::CRectangle & iview::CPerspectiveCalibration::GetBounds () const inline
Get logical coordinates bounds.
Definition at line 153 of file CPerspectiveCalibration.h.
virtual bool iview::CPerspectiveCalibration::GetDistance (const i2d::CVector2d & origPos1, const i2d::CVector2d & origPos2, double & result, ExactnessMode mode = EM_NONE) const virtual
Compute a shortness distance in transformed coordinations.
Parameters
origPos1 first position in original coordinates.
origPos2 second position in original coordinates.
result object where result distance between positions in transformed coordinates will be stored.
mode controls needed transformation exactness.
Returns
true, if calculation done correctly.
Reimplemented from i2d::CNoneCalibration2d.
virtual bool iview::CPerspectiveCalibration::GetInvPositionAt (const i2d::CVector2d & transfPosition, i2d::CVector2d & result, ExactnessMode mode = EM_NONE) const virtual
Get position after transformation.
Parameters
transfPosition position in transformed coordination system.
result result position (original coordination system).
mode controls needed transformation exactness.
Returns
true, if calculation done correctly.
Reimplemented from i2d::CNoneCalibration2d.
virtual bool iview::CPerspectiveCalibration::GetInvValueAt (const i2d::CVector2d & argument, i2d::CVector2d & result) const virtual
Reimplemented from i2d::CNoneCalibration2d.
virtual i2d::CVector2d iview::CPerspectiveCalibration::GetInvValueAt (const i2d::CVector2d & argument) const virtual
Reimplemented from i2d::CNoneCalibration2d.
virtual bool iview::CPerspectiveCalibration::GetLocalInvTransform (const i2d::CVector2d & transfPosition, i2d::CAffine2d & result, ExactnessMode mode = EM_NONE) const virtual
Get local transformation (from transformed to original coordinate system) at some transformed position.
Parameters
transfPosition position in transformed coordination system.
result inverse transformation for specified position.
mode controls needed transformation exactness.
Returns
true, if calculation done correctly.
Reimplemented from i2d::CNoneCalibration2d.
virtual bool iview::CPerspectiveCalibration::GetLocalTransform (const i2d::CVector2d & origPosition, i2d::CAffine2d & result, ExactnessMode mode = EM_NONE) const virtual
Get local transformation (from original to transformed coordinate system) at some original position.
Parameters
origPosition position in (original coordination system).
result transformation for specified position.
mode controls needed transformation exactness.
Returns
true, if calculation done correctly.
Reimplemented from i2d::CNoneCalibration2d.
const i3d::CVector3d & iview::CPerspectiveCalibration::GetLogAxisGetX () const inline
Definition at line 165 of file CPerspectiveCalibration.h.
const i3d::CVector3d & iview::CPerspectiveCalibration::GetLogAxisGetY () const inline
Definition at line 177 of file CPerspectiveCalibration.h.
const i3d::CVector3d & iview::CPerspectiveCalibration::GetLogCenter () const inline
Definition at line 189 of file CPerspectiveCalibration.h.
virtual bool iview::CPerspectiveCalibration::GetLogDerivative (const i2d::CVector2d & viewPosition, const i2d::CVector2d & viewDirection, double & result) const virtual
i2d::CVector2d iview::CPerspectiveCalibration::GetNormPosition (const i2d::CVector2d & viewPosition) const inline protected
Definition at line 221 of file CPerspectiveCalibration.h.
References i2d::CVector2d::GetX(), and i2d::CVector2d::GetY().
virtual bool iview::CPerspectiveCalibration::GetPositionAt (const i2d::CVector2d & origPosition, i2d::CVector2d & result, ExactnessMode mode = EM_NONE) const virtual
Get position after transformation.
Parameters
origPosition position in (original coordination system).
result result position (transformed coordination system).
mode controls needed transformation exactness.
Returns
true, if calculation done correctly.
Reimplemented from i2d::CNoneCalibration2d.
virtual int iview::CPerspectiveCalibration::GetTransformationFlags () const virtual
Get flags of describing type of this transformation.
Reimplemented from i2d::CNoneCalibration2d.
virtual bool iview::CPerspectiveCalibration::GetValueAt (const i2d::CVector2d & argument, i2d::CVector2d & result) const virtual
Reimplemented from i2d::CNoneCalibration2d.
virtual i2d::CVector2d iview::CPerspectiveCalibration::GetValueAt (const i2d::CVector2d & argument) const virtual
Reimplemented from i2d::CNoneCalibration2d.
const i2d::CVector2d & iview::CPerspectiveCalibration::GetViewCenter () const inline
Definition at line 201 of file CPerspectiveCalibration.h.
i2d::CVector2d iview::CPerspectiveCalibration::GetViewPosition (const i2d::CVector2d & normPosition) const inline protected
Definition at line 229 of file CPerspectiveCalibration.h.
References i2d::CVector2d::GetX(), and i2d::CVector2d::GetY().
bool iview::CPerspectiveCalibration::operator!= (const CPerspectiveCalibration & calib) const inline
Definition at line 213 of file CPerspectiveCalibration.h.
References operator==().
bool iview::CPerspectiveCalibration::operator== (const CPerspectiveCalibration & calib) const
Referenced by operator!=().
void iview::CPerspectiveCalibration::Reset ()
Reset this calibration, set to be identity transform.
void iview::CPerspectiveCalibration::ResetAxes ()
virtual bool iview::CPerspectiveCalibration::Serialize (iser::IArchive & archive) virtual
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See Also
iser::IArchive
Reimplemented from i2d::CNoneCalibration2d.
void iview::CPerspectiveCalibration::SetBounds (const i2d::CRectangle & bounds) inline virtual
Set locical coordinates bounds.
Definition at line 159 of file CPerspectiveCalibration.h.
void iview::CPerspectiveCalibration::SetCameraParams (const i2d::CVector2d & viewOpticalCenter, const i2d::CVector2d & pixelAngleTangents)
void iview::CPerspectiveCalibration::SetLogAxisX (const i3d::CVector3d & value) inline virtual
Definition at line 171 of file CPerspectiveCalibration.h.
void iview::CPerspectiveCalibration::SetLogAxisY (const i3d::CVector3d & value) inline virtual
Definition at line 183 of file CPerspectiveCalibration.h.
void iview::CPerspectiveCalibration::SetLogCenter (const i3d::CVector3d & value) inline virtual
Definition at line 195 of file CPerspectiveCalibration.h.
void iview::CPerspectiveCalibration::SetViewCenter (const i2d::CVector2d & center) inline
Definition at line 207 of file CPerspectiveCalibration.h.
The documentation for this class was generated from the following file:
Include/iview/CPerspectiveCalibration.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy