ACF: ibase::TLoggerWrap< Base > Class Template Reference
ibase::TLoggerWrap< Base > Class Template Reference
[Set of helper classes.]
Class wrapper implementing interface istd::ILogger sending log messages over ibase::IMessageConsumer.
#include <TLoggerWrap.h>
Public Member Functions
TLoggerWrap ()
virtual void SetLogPtr (ibase::IMessageConsumer *logPtr)
Install log.
virtual ibase::IMessageConsumer * GetLogPtr () const
Get log.
Protected Member Functions
bool SendInfoMessage (int id, const istd::CString &message, const istd::CString &messageSource=istd::CString(), int flags=0) const
Send info message to log.
bool SendWarningMessage (int id, const istd::CString &message, const istd::CString &messageSource=istd::CString(), int flags=0) const
Send warning message to log.
bool SendErrorMessage (int id, const istd::CString &message, const istd::CString &messageSource=istd::CString(), int flags=0) const
Send error message to log.
bool SendCriticalMessage (int id, const istd::CString &message, const istd::CString &messageSource=istd::CString(), int flags=0) const
Send critical message to log.
virtual bool IsLogConsumed (const MessageCategory *categoryPtr=NULL, const int *flagsPtr=NULL) const
Check if any log message is consumed.
virtual bool SendLogMessage (MessageCategory category, int id, const istd::CString &message, const istd::CString &messageSource, int flags=0) const
Send any message to log.
Detailed Description
template<class Base>
class ibase::TLoggerWrap< Base >
Class wrapper implementing interface istd::ILogger sending log messages over ibase::IMessageConsumer.
Access to interface ibase::IMessageConsumer must be registered by user. To register it use interface ibase::ILoggable implemented by this wrapper.
Definition at line 24 of file TLoggerWrap.h.
Constructor & Destructor Documentation
template<class Base > ibase::TLoggerWrap< Base >::TLoggerWrap () [inline]
Definition at line 105 of file TLoggerWrap.h.
Member Function Documentation
template<class Base > ibase::IMessageConsumer * ibase::TLoggerWrap< Base >::GetLogPtr () const [inline, virtual]
Get log.
Implements ibase::ILoggable.
Definition at line 121 of file TLoggerWrap.h.
template<class Base > bool ibase::TLoggerWrap< Base >::IsLogConsumed (const MessageCategory * categoryPtr = NULL, const int * flagsPtr = NULL) const [inline, protected, virtual]
Check if any log message is consumed.
Default implementation retuns false.
Reimplemented from istd::ILogger.
Definition at line 160 of file TLoggerWrap.h.
References NULL.
Referenced by ibase::TFileSerializerComp< ReadArchive, WriteArchive >::WriteArchiveEx::IsLogConsumed(), and ibase::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx::IsLogConsumed().
template<class Base > bool ibase::TLoggerWrap< Base >::SendCriticalMessage (int id, const istd::CString & message, const istd::CString & messageSource = istd::CString(), int flags = 0) const [inline, protected]
Send critical message to log.
See also:
ibase::IMessage for message meaning documentation.
Parameters:
id binary id identifying this message type for automatical processing.
message message text will be send.
messageSource optional human readable description of message source.
Definition at line 151 of file TLoggerWrap.h.
References istd::ILogger::MC_CRITICAL, and ibase::TLoggerWrap< Base >::SendLogMessage().
template<class Base > bool ibase::TLoggerWrap< Base >::SendErrorMessage (int id, const istd::CString & message, const istd::CString & messageSource = istd::CString(), int flags = 0) const [inline, protected]
Send error message to log.
See also:
ibase::IMessage for message meaning documentation.
Parameters:
id binary id identifying this message type for automatical processing.
message message text will be send.
messageSource source of the message
Definition at line 144 of file TLoggerWrap.h.
References istd::ILogger::MC_ERROR.
template<class Base > bool ibase::TLoggerWrap< Base >::SendInfoMessage (int id, const istd::CString & message, const istd::CString & messageSource = istd::CString(), int flags = 0) const [inline, protected]
Send info message to log.
See also:
ibase::IMessage for message meaning documentation.
Parameters:
id binary id identifying this message type for automatical processing.
message message text will be send.
messageSource source of the message
Definition at line 130 of file TLoggerWrap.h.
References istd::ILogger::MC_INFO.
template<class Base > bool ibase::TLoggerWrap< Base >::SendLogMessage (MessageCategory category, int id, const istd::CString & message, const istd::CString & messageSource, int flags = 0) const [inline, protected, virtual]
Send any message to log.
Default implementation do nothing.
Parameters:
category message category.
id binary id identifying this message type for automatical processing.
message message text will be send.
messageSource source of the message.
Returns:
true, if it was possible to send this message and it is 'consumed'.
Reimplemented from istd::ILogger.
Definition at line 169 of file TLoggerWrap.h.
References ibase::IMessageConsumer::AddMessage(), istd::ILogger::DecorateMessage(), and NULL.
Referenced by ibase::TLoggerWrap< Base >::SendCriticalMessage(), ibase::TFileSerializerComp< ReadArchive, WriteArchive >::WriteArchiveEx::SendLogMessage(), ibase::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx::SendLogMessage(), and ibase::TLoggerWrap< Base >::SendWarningMessage().
template<class Base > bool ibase::TLoggerWrap< Base >::SendWarningMessage (int id, const istd::CString & message, const istd::CString & messageSource = istd::CString(), int flags = 0) const [inline, protected]
Send warning message to log.
See also:
ibase::IMessage for message meaning documentation.
Parameters:
id binary id identifying this message type for automatical processing.
message message text will be send.
messageSource source of the message
Definition at line 137 of file TLoggerWrap.h.
References istd::ILogger::MC_WARNING, and ibase::TLoggerWrap< Base >::SendLogMessage().
template<class Base > void ibase::TLoggerWrap< Base >::SetLogPtr (ibase::IMessageConsumer * logPtr) [inline, virtual]
Install log.
Implements ibase::ILoggable.
Definition at line 114 of file TLoggerWrap.h.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/ibase/TLoggerWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy