icomp::TAttributeMemberBase< Attribute > Class Template Reference
icomp::TAttributeMemberBase< Attribute > Class Template Reference
Pointer to component attribute.
#include <TAttributeMember.h>
Public Types
typedef Attribute AttributeType
typedef Attribute::ValueType AttributeValueType
typedef void InterfaceType
Public Member Functions
TAttributeMemberBase ()
void Init (const IComponent *ownerPtr, const IRealAttributeStaticInfo &staticInfo)
Initialize this attribute.
bool IsValid () const
Check if this attribute is valid.
const Attribute * GetAttributePtr () const
Access to internal attribute pointer.
const AttributeValueType & GetOriginalValue () const
Get value of attribute.
const Attribute * operator-> () const
Access to internal attribute pointer.
const AttributeValueType & operator* () const
Get value of attribute.
Protected Member Functions
void SetAttribute (const Attribute *attributePtr)
bool InitInternal (const IComponent *ownerPtr, const IRealAttributeStaticInfo &staticInfo, const IComponent **definitionComponentPtr)
Internal initialize of attribute.
Detailed Description
template<typename Attribute>
class icomp::TAttributeMemberBase< Attribute >
Pointer to component attribute.
Definition at line 26 of file TAttributeMember.h.
Member Typedef Documentation
template<typename Attribute> typedef Attribute icomp::TAttributeMemberBase< Attribute >::AttributeType
Definition at line 29 of file TAttributeMember.h.
template<typename Attribute> typedef Attribute::ValueType icomp::TAttributeMemberBase< Attribute >::AttributeValueType
Definition at line 30 of file TAttributeMember.h.
template<typename Attribute> typedef void icomp::TAttributeMemberBase< Attribute >::InterfaceType
Definition at line 31 of file TAttributeMember.h.
Constructor & Destructor Documentation
template<typename Attribute > icomp::TAttributeMemberBase< Attribute >::TAttributeMemberBase ()
Definition at line 91 of file TAttributeMember.h.
Member Function Documentation
template<typename Attribute > const Attribute * icomp::TAttributeMemberBase< Attribute >::GetAttributePtr () const
Access to internal attribute pointer.
Definition at line 116 of file TAttributeMember.h.
template<typename Attribute > const TAttributeMemberBase< Attribute >::AttributeValueType & icomp::TAttributeMemberBase< Attribute >::GetOriginalValue () const
Get value of attribute.
The String attributes will not be translated.
Definition at line 125 of file TAttributeMember.h.
References NULL.
template<typename Attribute > void icomp::TAttributeMemberBase< Attribute >::Init (const IComponent * ownerPtr, const IRealAttributeStaticInfo & staticInfo)
Initialize this attribute.
Parameters
ownerPtr pointer to parent component of this attribute.
staticInfo static info structure creating this attribute.
Definition at line 99 of file TAttributeMember.h.
References NULL.
template<typename Attribute > bool icomp::TAttributeMemberBase< Attribute >::InitInternal (const IComponent * ownerPtr, const IRealAttributeStaticInfo & staticInfo, const IComponent ** definitionComponentPtr) protected
Internal initialize of attribute.
Parameters
ownerPtr pointer to parent component of this attribute.
staticInfo static info structure creating this attribute.
definitionComponentPtr optional pointer will be set with pointer to component defining this attribute. If this attribute was exported it will differ from parent component.
Definition at line 161 of file TAttributeMember.h.
References icomp::IComponentContext::GetAttribute(), icomp::IRealAttributeStaticInfo::GetAttributeId(), icomp::IComponent::GetComponentContext(), icomp::CComponentContext::GetHierarchyAddress(), icomp::IComponent::GetParentComponent(), and NULL.
template<typename Attribute > bool icomp::TAttributeMemberBase< Attribute >::IsValid () const
Check if this attribute is valid.
Definition at line 107 of file TAttributeMember.h.
References NULL.
template<typename Attribute > const TAttributeMemberBase< Attribute >::AttributeValueType & icomp::TAttributeMemberBase< Attribute >::operator* () const
Get value of attribute.
Access to object pointed by internal pointer or translated values for String.
Definition at line 143 of file TAttributeMember.h.
References NULL.
template<typename Attribute > const Attribute * icomp::TAttributeMemberBase< Attribute >::operator-> () const
Access to internal attribute pointer.
Definition at line 134 of file TAttributeMember.h.
template<typename Attribute> void icomp::TAttributeMemberBase< Attribute >::SetAttribute (const Attribute * attributePtr) protected
Definition at line 154 of file TAttributeMember.h.
The documentation for this class was generated from the following file:
Include/icomp/TAttributeMember.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy