ACF: istd::TCascadedMap< Key, Value > Class Template Reference
istd::TCascadedMap< Key, Value > Class Template Reference
Helper class used to manage list of many connected in cascade maps.
#include <TCascadedMap.h>
Public Member Functions
TCascadedMap ()
Default constructor.
TCascadedMap (const TCascadedMap< Key, Value > *parentPtr)
Constructor with assigning of parent map.
TCascadedMap (const TCascadedMap &map)
Copy constructor.
const TCascadedMap< Key, Value > * GetParent () const
Get access to parent map instance.
void SetParent (const TIMap< Key, Value > *parentPtr)
Set instance of parent map.
int FindLocalIndex (const KeyType &key) const
Find index index of specified key using local context only.
const ValueType * FindLocalElement (const KeyType &key) const
Find value element associated with specified key using local context only.
ValueType * FindLocalElement (const KeyType &key)
Find value element associated with specified key using local context only.
const KeyType & GetLocalKeyAt (int index) const
Get key value from local context at specified index.
KeyType & GetLocalKeyAt (int index)
Get key value from local context at specified index.
const ValueType & GetLocalValueAt (int index) const
Get mapped value from local context at specified index.
ValueType & GetLocalValueAt (int index)
Get mapped value from local context at specified index.
int GetLocalElementsCount () const
Get number of elements in local context.
bool InsertLocal (const KeyType &key, const ValueType &value)
Insert element in local context.
void ResetLocal ()
Removes all elements from local context.
void GetLocalKeys (Keys &result, bool doAppend=false) const
Get list of local keys stored in this map.
virtual int GetElementsCount () const
Get number of elements.
virtual ValueType & operator[] (const KeyType &key)
Element access operator.
virtual const ValueType & operator[] (const KeyType &key) const
Element access operator.
virtual int FindIndex (const KeyType &key) const
Find index index of specified key.
virtual const ValueType * FindElement (const KeyType &key) const
Find value element associated with specified key.
virtual void GetKeys (Keys &result, bool doAppend=false) const
Get list of keys stored in this map.
virtual const KeyType & GetKeyAt (int index) const
Get key value at specified index.
virtual const ValueType & GetValueAt (int index) const
Get mapped value at specified index.
Detailed Description
template<typename Key, typename Value>
class istd::TCascadedMap< Key, Value >
Helper class used to manage list of many connected in cascade maps.
Please note, that elements are accessed using its index. At this moment no element removing is supported. Local elements have begining indices.
Definition at line 23 of file TCascadedMap.h.
Constructor & Destructor Documentation
template<typename Key , typename Value > istd::TCascadedMap< Key, Value >::TCascadedMap () [inline]
Default constructor.
Definition at line 133 of file TCascadedMap.h.
template<typename Key , typename Value > istd::TCascadedMap< Key, Value >::TCascadedMap (const TCascadedMap< Key, Value > * parentPtr) [inline, explicit]
Constructor with assigning of parent map.
Definition at line 140 of file TCascadedMap.h.
template<typename Key , typename Value > istd::TCascadedMap< Key, Value >::TCascadedMap (const TCascadedMap< Key, Value > & map) [inline]
Copy constructor.
Definition at line 147 of file TCascadedMap.h.
Member Function Documentation
template<typename Key , typename Value > const TCascadedMap< Key, Value >::ValueType * istd::TCascadedMap< Key, Value >::FindElement (const KeyType & key) const [inline, virtual]
Find value element associated with specified key.
Returns:
pointer to associated value, or NULL if key not exists.
Implements istd::TIMap< Key, Value >.
Definition at line 346 of file TCascadedMap.h.
References istd::TCascadedMap< Key, Value >::FindIndex(), istd::TCascadedMap< Key, Value >::GetValueAt(), and NULL.
template<typename Key , typename Value > int istd::TCascadedMap< Key, Value >::FindIndex (const KeyType & key) const [inline, virtual]
Find index index of specified key.
Implements istd::TIMap< Key, Value >.
Definition at line 327 of file TCascadedMap.h.
References istd::TIMap< Key, Value >::FindIndex(), istd::TCascadedMap< Key, Value >::GetLocalElementsCount(), and NULL.
Referenced by istd::TCascadedMap< Key, Value >::FindElement().
template<typename Key , typename Value > TCascadedMap< Key, Value >::ValueType * istd::TCascadedMap< Key, Value >::FindLocalElement (const KeyType & key) [inline]
Find value element associated with specified key using local context only.
Returns:
pointer to associated value, or NULL if key not exists.
Definition at line 194 of file TCascadedMap.h.
References istd::TCascadedMap< Key, Value >::FindLocalIndex(), istd::TCascadedMap< Key, Value >::GetLocalValueAt(), and NULL.
template<typename Key , typename Value > const TCascadedMap< Key, Value >::ValueType * istd::TCascadedMap< Key, Value >::FindLocalElement (const KeyType & key) const [inline]
Find value element associated with specified key using local context only.
Returns:
pointer to associated value, or NULL if key not exists.
Definition at line 182 of file TCascadedMap.h.
References istd::TCascadedMap< Key, Value >::FindLocalIndex(), istd::TCascadedMap< Key, Value >::GetLocalValueAt(), and NULL.
template<typename Key , typename Value > int istd::TCascadedMap< Key, Value >::FindLocalIndex (const KeyType & key) const [inline]
Find index index of specified key using local context only.
Definition at line 170 of file TCascadedMap.h.
Referenced by istd::TCascadedMap< Key, Value >::FindLocalElement().
template<typename Key , typename Value > int istd::TCascadedMap< Key, Value >::GetElementsCount () const [inline, virtual]
Get number of elements.
Implements istd::TIMap< Key, Value >.
Definition at line 291 of file TCascadedMap.h.
References istd::TIMap< Key, Value >::GetElementsCount(), istd::TCascadedMap< Key, Value >::GetLocalElementsCount(), and NULL.
template<typename Key , typename Value > const TCascadedMap< Key, Value >::KeyType & istd::TCascadedMap< Key, Value >::GetKeyAt (int index) const [inline, virtual]
Get key value at specified index.
Implements istd::TIMap< Key, Value >.
Definition at line 369 of file TCascadedMap.h.
References istd::TIMap< Key, Value >::GetKeyAt(), istd::TCascadedMap< Key, Value >::GetLocalElementsCount(), istd::TCascadedMap< Key, Value >::GetLocalKeyAt(), I_ASSERT, and NULL.
template<typename Key , typename Value > void istd::TCascadedMap< Key, Value >::GetKeys (Keys & result, bool doAppend = false) const [inline, virtual]
Get list of keys stored in this map.
Parameters:
doAppend if it is true, list of keys will be appended to existing key list.
Implements istd::TIMap< Key, Value >.
Definition at line 358 of file TCascadedMap.h.
References istd::TIMap< Key, Value >::GetKeys(), istd::TCascadedMap< Key, Value >::GetLocalKeys(), and NULL.
template<typename Key , typename Value > int istd::TCascadedMap< Key, Value >::GetLocalElementsCount () const [inline]
Get number of elements in local context.
Definition at line 242 of file TCascadedMap.h.
Referenced by istd::TCascadedMap< Key, Value >::FindIndex(), istd::TCascadedMap< Key, Value >::GetElementsCount(), istd::TCascadedMap< Key, Value >::GetKeyAt(), and istd::TCascadedMap< Key, Value >::GetValueAt().
template<typename Key , typename Value > TCascadedMap< Key, Value >::KeyType & istd::TCascadedMap< Key, Value >::GetLocalKeyAt (int index) [inline]
Get key value from local context at specified index.
Definition at line 215 of file TCascadedMap.h.
References I_ASSERT.
template<typename Key , typename Value > const TCascadedMap< Key, Value >::KeyType & istd::TCascadedMap< Key, Value >::GetLocalKeyAt (int index) const [inline]
Get key value from local context at specified index.
Definition at line 206 of file TCascadedMap.h.
References I_ASSERT.
Referenced by istd::TCascadedMap< Key, Value >::GetKeyAt().
template<typename Key , typename Value > void istd::TCascadedMap< Key, Value >::GetLocalKeys (Keys & result, bool doAppend = false) const [inline]
Get list of local keys stored in this map.
Parameters:
doAppend if it is true, list of keys will be appended to existing key list.
Definition at line 274 of file TCascadedMap.h.
Referenced by istd::TCascadedMap< Key, Value >::GetKeys().
template<typename Key , typename Value > TCascadedMap< Key, Value >::ValueType & istd::TCascadedMap< Key, Value >::GetLocalValueAt (int index) [inline]
Get mapped value from local context at specified index.
Definition at line 224 of file TCascadedMap.h.
References I_ASSERT.
template<typename Key , typename Value > const TCascadedMap< Key, Value >::ValueType & istd::TCascadedMap< Key, Value >::GetLocalValueAt (int index) const [inline]
Get mapped value from local context at specified index.
Definition at line 233 of file TCascadedMap.h.
References I_ASSERT.
Referenced by istd::TCascadedMap< Key, Value >::FindLocalElement(), and istd::TCascadedMap< Key, Value >::GetValueAt().
template<typename Key , typename Value > const TCascadedMap< Key, Value > * istd::TCascadedMap< Key, Value >::GetParent () const [inline]
Get access to parent map instance.
Definition at line 156 of file TCascadedMap.h.
template<typename Key , typename Value > const TCascadedMap< Key, Value >::ValueType & istd::TCascadedMap< Key, Value >::GetValueAt (int index) const [inline, virtual]
Get mapped value at specified index.
Implements istd::TIMap< Key, Value >.
Definition at line 383 of file TCascadedMap.h.
References istd::TCascadedMap< Key, Value >::GetLocalElementsCount(), istd::TCascadedMap< Key, Value >::GetLocalValueAt(), istd::TIMap< Key, Value >::GetValueAt(), I_ASSERT, and NULL.
Referenced by istd::TCascadedMap< Key, Value >::FindElement().
template<typename Key , typename Value > bool istd::TCascadedMap< Key, Value >::InsertLocal (const KeyType & key, const ValueType & value) [inline]
Insert element in local context.
Definition at line 249 of file TCascadedMap.h.
template<typename Key , typename Value > const TCascadedMap< Key, Value >::ValueType & istd::TCascadedMap< Key, Value >::operator[] (const KeyType & key) const [inline, virtual]
Element access operator.
If key object not exists, it will be automatically created.
Implements istd::TIMap< Key, Value >.
Definition at line 320 of file TCascadedMap.h.
template<typename Key , typename Value > TCascadedMap< Key, Value >::ValueType & istd::TCascadedMap< Key, Value >::operator[] (const KeyType & key) [inline, virtual]
Element access operator.
If key object not exists, it will be automatically created.
Implements istd::TIMap< Key, Value >.
Definition at line 303 of file TCascadedMap.h.
template<typename Key , typename Value > void istd::TCascadedMap< Key, Value >::ResetLocal () [inline]
Removes all elements from local context.
Definition at line 266 of file TCascadedMap.h.
template<typename Key , typename Value > void istd::TCascadedMap< Key, Value >::SetParent (const TIMap< Key, Value > * parentPtr) [inline]
Set instance of parent map.
Definition at line 163 of file TCascadedMap.h.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/istd/TCascadedMap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy