ACF: istd::CStaticServicesProvider Class Reference
istd::CStaticServicesProvider Class Reference
[Defines access to operating system dependent implementation]
Manage list of global services.
#include <CStaticServicesProvider.h>
Classes
class Provider
Static Public Member Functions
static void InitServices (const IServicesProvider *parentPtr)
Set parent provider.
static bool RegisterService (const istd::CClassInfo &info, void *servicePtr)
Register service for specified ID.
static bool RegisterFactory (const istd::CClassInfo &info, const IVoidFactory *factoryPtr)
Register factory for specified ID.
template<class Service >
static bool RegisterService (Service *servicePtr)
Register service for specified ID.
template<class Interface >
static bool RegisterFactory (const TIFactory< Interface > *factoryPtr)
Register service for specified ID.
static void * GetService (const istd::CClassInfo &info)
static void * CreateService (const istd::CClassInfo &info)
static IServicesProvider & GetProviderInstance ()
Detailed Description
Manage list of global services.
Definition at line 23 of file CStaticServicesProvider.h.
Member Function Documentation
static void* istd::CStaticServicesProvider::CreateService (const istd::CClassInfo & info) [static]
Referenced by istd::CreateService().
static IServicesProvider& istd::CStaticServicesProvider::GetProviderInstance () [static]
static void* istd::CStaticServicesProvider::GetService (const istd::CClassInfo & info) [static]
Referenced by istd::GetService().
static void istd::CStaticServicesProvider::InitServices (const IServicesProvider * parentPtr) [static]
Set parent provider.
This provider will be used if this static service provider has no registered service for specified type.
template<class Interface > bool istd::CStaticServicesProvider::RegisterFactory (const TIFactory< Interface > * factoryPtr) [inline, static]
Register service for specified ID.
Definition at line 90 of file CStaticServicesProvider.h.
References RegisterFactory().
static bool istd::CStaticServicesProvider::RegisterFactory (const istd::CClassInfo & info, const IVoidFactory * factoryPtr) [static]
Register factory for specified ID.
Referenced by RegisterFactory().
template<class Service > bool istd::CStaticServicesProvider::RegisterService (Service * servicePtr) [inline, static]
Register service for specified ID.
Definition at line 81 of file CStaticServicesProvider.h.
References RegisterService().
static bool istd::CStaticServicesProvider::RegisterService (const istd::CClassInfo & info, void * servicePtr) [static]
Register service for specified ID.
Referenced by RegisterService().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/istd/CStaticServicesProvider.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy