ACF: iproc::TMemCachedProducerComp< Key, CacheObject > Class Template Reference
iproc::TMemCachedProducerComp< Key, CacheObject > Class Template Reference
Template implementation iproc::TILockedProducer buffering objects in memory cache.
#include <TMemCachedProducerComp.h>
Public Types
typedef icomp::CComponentBase BaseClass
typedef TILockedProducer< Key,
CacheObject > LockedProducerType
Public Member Functions
virtual const CacheObject * ProduceLockedObject (const Key &key)
Begin of accessing to cached element.
virtual void UnlockObject (const CacheObject *objectPtr)
End of accessing to cached element.
Protected Member Functions
void CleanElementList ()
Remove elements from list if cumulated weight is above defined maximum.
Detailed Description
template<class Key, class CacheObject>
class iproc::TMemCachedProducerComp< Key, CacheObject >
Template implementation iproc::TILockedProducer buffering objects in memory cache.
As a source of produced object instances some slave implementation is used.
Definition at line 20 of file TMemCachedProducerComp.h.
Member Typedef Documentation
template<class Key , class CacheObject > typedef icomp::CComponentBase iproc::TMemCachedProducerComp< Key, CacheObject >::BaseClass
Definition at line 25 of file TMemCachedProducerComp.h.
template<class Key , class CacheObject > typedef TILockedProducer<Key, CacheObject> iproc::TMemCachedProducerComp< Key, CacheObject >::LockedProducerType
Definition at line 26 of file TMemCachedProducerComp.h.
Member Function Documentation
template<class Key , class CacheObject > void iproc::TMemCachedProducerComp< Key, CacheObject >::CleanElementList () [inline, protected]
Remove elements from list if cumulated weight is above defined maximum.
Definition at line 122 of file TMemCachedProducerComp.h.
References I_ASSERT, and istd::Max().
Referenced by iproc::TMemCachedProducerComp< Key, CacheObject >::ProduceLockedObject(), and iproc::TMemCachedProducerComp< Key, CacheObject >::UnlockObject().
template<class Key , class CacheObject > const CacheObject * iproc::TMemCachedProducerComp< Key, CacheObject >::ProduceLockedObject (const Key & key) [inline, virtual]
Begin of accessing to cached element.
Returns:
cached object, if it was possible to produce it for specified key.
Implements iproc::TILockedProducer< Key, CacheObject >.
Definition at line 73 of file TMemCachedProducerComp.h.
References iproc::TMemCachedProducerComp< Key, CacheObject >::CleanElementList(), and NULL.
template<class Key , class CacheObject > void iproc::TMemCachedProducerComp< Key, CacheObject >::UnlockObject (const CacheObject * objectPtr) [inline, virtual]
End of accessing to cached element.
Implements iproc::TILockedProducer< Key, CacheObject >.
Definition at line 105 of file TMemCachedProducerComp.h.
References iproc::TMemCachedProducerComp< Key, CacheObject >::CleanElementList(), and I_ASSERT.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iproc/TMemCachedProducerComp.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy