i2d::CVector2d Class Reference
i2d::CVector2d Class Reference
Definition of position or mathematical vector on 2D plane.
#include <CVector2d.h>
Public Types
typedef imath::TVector< 2 > BaseClass
Public Types inherited from imath::TVector< 2 >
typedef double ElementType
typedef double Elements [Size]
Public Member Functions
CVector2d ()
Default constructor.
CVector2d (double x, double y)
Construct initializing elements to specified values.
CVector2d (const istd::CIndex2d &index)
CVector2d (const QPointF &point)
CVector2d (const imath::TVector< 2 > &vector)
Copy constructor.
double GetX () const
Get X position of this vector.
void SetX (double x)
Set X position of this vector.
double GetY () const
Get Y position of this vector.
void SetY (double y)
Set Y position of this vector.
void Init (double angle, double length=1.0)
Init this vector using angle and vector length.
CVector2d GetTranslated (const imath::TVector< 2 > &vector)
Get translated point.
CVector2d GetHorizontalTranslated (double offsetX) const
Get horizontal translated point.
CVector2d GetVerticalTranslated (double offsetY) const
Get vertical translated point.
double GetCrossProductZ (const imath::TVector< 2 > &vector) const
Return Z coordinate of two vectors cross product.
double GetAngle () const
Get angle of this vector.
CVector2d GetOrthogonal () const
Get orthogonal vector.
istd::CIndex2d ToIndex2d () const
Get vector converted to 2D index.
CVector2d GetNormalized (double length=1.0) const
Return normalized vector with the same direction and specified length.
CVector2d operator- () const
CVector2d operator+ (const imath::TVector< 2 > &vector) const
CVector2d operator- (const imath::TVector< 2 > &vector) const
CVector2d operator* (double scalar) const
CVector2d operator/ (double scalar) const
CVector2d & operator+= (const imath::TVector< 2 > &vector)
CVector2d & operator-= (const imath::TVector< 2 > &vector)
CVector2d & operator*= (double scalar)
CVector2d & operator/= (double scalar)
operator QPointF () const
Public Member Functions inherited from imath::TVector< 2 >
TVector ()
Create an uninitialized point.
TVector (const TVector< Size, double > &vector)
Copy constructor.
const double & GetElement (int i) const
Get element at specified i.
double & GetElementRef (int i)
Get reference to element at specified i.
void SetElement (int i, const double &value)
Set element at specified i.
void Reset ()
Set all coordinates to zero.
void Clear ()
Set all coordinates to zero.
const TVector< Size, double >
::Elements & GetElements () const
Get read-only access to internal element container.
TVector< Size, double >::Elements & GetElementsRef ()
Get access to internal element container.
void Translate (const TVector< Size, double > &vector)
Translate the point.
TVector< Size, double > GetTranslated (const TVector< Size, double > &vector)
Get translated point.
void GetTranslated (const TVector< Size, double > &vector, TVector< Size, double > &result)
/overloaded
void ScaledCumulate (const TVector< Size, double > &vector, doublescale)
Add second vector scaled by specified factor.
bool IsNull (doubletolerance=I_BIG_EPSILON) const
Check if this vector is null.
double GetDotProduct (const TVector< Size, double > &vector) const
Return dot product of two vectors.
double GetLength2 () const
Return euclidian length square.
double GetLength () const
Return euclidian length.
double GetDistance2 (const TVector< Size, double > &vector) const
Return distance square between two vectors.
double GetDistance (const TVector< Size, double > &vector) const
Return distance between two vectors.
double GetElementsSum () const
Get simple sum of all elements.
bool Normalize (doublelength=1.0)
Normalize vector to specified length.
bool GetNormalized (TVector< Size, double > &result, doublelength=1.0) const
Return normalized vector with the same direction and specified length.
void GetMinimal (const TVector< Size, double > &vector, TVector< Size, double > &result) const
Get vector with minimal elements values.
void GetMaximal (const TVector< Size, double > &vector, TVector< Size, double > &result) const
Get vector with maximal elements values.
bool Serialize (iser::IArchive &archive)
Serialize this vector to specified archive.
bool operator== (const TVector< Size, double > &vector) const
bool operator!= (const TVector< Size, double > &vector) const
bool operator< (const TVector< Size, double > &vector) const
bool operator> (const TVector< Size, double > &vector) const
bool operator<= (const TVector< Size, double > &vector) const
bool operator>= (const TVector< Size, double > &vector) const
TVector< Size, double > operator- () const
TVector< Size, double > operator- (const TVector< Size, double > &vector) const
TVector< Size, double > operator+ (const TVector< Size, double > &vector) const
TVector< Size, double > operator* (doublescalar) const
TVector< Size, double > operator/ (doublescalar) const
TVector< Size, double > & operator+= (const TVector< Size, double > &vector)
TVector< Size, double > & operator-= (const TVector< Size, double > &vector)
TVector< Size, double > & operator*= (doublescalar)
TVector< Size, double > & operator/= (doublescalar)
const double & operator[] (int i) const
double & operator[] (int i)
Static Public Member Functions
static const CVector2d & GetZero ()
Static Public Member Functions inherited from imath::TVector< 2 >
static int GetElementsCount ()
Get number of elements.
static bool SetElementsCount (int count)
Set number of elements.
static const TVector< Size,
double > & GetZero ()
Get vector with all coordinates set to 0.
Additional Inherited Members
Protected Attributes inherited from imath::TVector< 2 >
Elements m_elements
Detailed Description
Definition of position or mathematical vector on 2D plane.
Definition at line 24 of file CVector2d.h.
Member Typedef Documentation
typedef imath::TVector<2> i2d::CVector2d::BaseClass
Definition at line 27 of file CVector2d.h.
Constructor & Destructor Documentation
i2d::CVector2d::CVector2d () inline
Default constructor.
Please note, elements will be not initilized.
Definition at line 136 of file CVector2d.h.
Referenced by GetHorizontalTranslated(), GetVerticalTranslated(), operator*(), operator+(), operator-(), and operator/().
i2d::CVector2d::CVector2d (double x, double y) inline
Construct initializing elements to specified values.
Definition at line 141 of file CVector2d.h.
References imath::TVector< 2 >::operator[]().
i2d::CVector2d::CVector2d (const istd::CIndex2d & index) inline
Definition at line 154 of file CVector2d.h.
References istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), and imath::TVector< 2 >::operator[]().
i2d::CVector2d::CVector2d (const QPointF & point) inline
Definition at line 129 of file CVector2d.h.
References imath::TVector< 2 >::operator[]().
i2d::CVector2d::CVector2d (const imath::TVector< 2 > & vector) inline
Copy constructor.
Definition at line 148 of file CVector2d.h.
Member Function Documentation
double i2d::CVector2d::GetAngle () const inline
Get angle of this vector.
Definition at line 209 of file CVector2d.h.
References GetX(), and GetY().
double i2d::CVector2d::GetCrossProductZ (const imath::TVector< 2 > & vector) const inline
Return Z coordinate of two vectors cross product.
Definition at line 203 of file CVector2d.h.
References GetX(), and GetY().
Referenced by i2d::CLine2d::GetAlphaAndCastDistance(), and i2d::CLine2d::GetCutAlpha().
CVector2d i2d::CVector2d::GetHorizontalTranslated (double offsetX) const inline
Get horizontal translated point.
Definition at line 191 of file CVector2d.h.
References CVector2d(), GetX(), and GetY().
CVector2d i2d::CVector2d::GetNormalized (double length = 1.0) const
Return normalized vector with the same direction and specified length.
CVector2d i2d::CVector2d::GetOrthogonal () const
Get orthogonal vector.
CVector2d i2d::CVector2d::GetTranslated (const imath::TVector< 2 > & vector) inline
Get translated point.
Definition at line 185 of file CVector2d.h.
CVector2d i2d::CVector2d::GetVerticalTranslated (double offsetY) const inline
Get vertical translated point.
Definition at line 197 of file CVector2d.h.
References CVector2d(), GetX(), and GetY().
double i2d::CVector2d::GetX () const inline
Get X position of this vector.
Definition at line 161 of file CVector2d.h.
References imath::TVector< 2 >::operator[]().
Referenced by i3d::CVector3d::CVector3d(), GetAngle(), GetCrossProductZ(), i2d::CLine2d::GetCutXPos(), i2d::CLine2d::GetCutYPos(), GetHorizontalTranslated(), iview::CPerspectiveCalibration::GetNormPosition(), iview::CScreenTransform::GetScreenPosition(), GetVerticalTranslated(), iview::CPerspectiveCalibration::GetViewPosition(), iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnToolsButtonMenuActionTriggered(), operator*(), operator+(), operator-(), operator/(), and iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::UpdateGui().
double i2d::CVector2d::GetY () const inline
Get Y position of this vector.
Definition at line 173 of file CVector2d.h.
References imath::TVector< 2 >::operator[]().
Referenced by i3d::CVector3d::CVector3d(), GetAngle(), GetCrossProductZ(), i2d::CLine2d::GetCutXPos(), i2d::CLine2d::GetCutYPos(), GetHorizontalTranslated(), iview::CPerspectiveCalibration::GetNormPosition(), iview::CScreenTransform::GetScreenPosition(), GetVerticalTranslated(), iview::CPerspectiveCalibration::GetViewPosition(), iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnToolsButtonMenuActionTriggered(), operator*(), operator+(), operator-(), operator/(), and iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::UpdateGui().
const CVector2d & i2d::CVector2d::GetZero () inline static
Definition at line 295 of file CVector2d.h.
References imath::TVector< 2 >::GetZero().
void i2d::CVector2d::Init (double angle, double length = 1.0)
Init this vector using angle and vector length.
i2d::CVector2d::operator QPointF () const inline
Definition at line 287 of file CVector2d.h.
CVector2d i2d::CVector2d::operator* (double scalar) const inline
Definition at line 236 of file CVector2d.h.
References CVector2d(), GetX(), and GetY().
CVector2d & i2d::CVector2d::operator*= (double scalar) inline
Definition at line 271 of file CVector2d.h.
References imath::TVector< 2 >::operator*=().
CVector2d i2d::CVector2d::operator+ (const imath::TVector< 2 > & vector) const inline
Definition at line 222 of file CVector2d.h.
References CVector2d(), GetX(), and GetY().
CVector2d & i2d::CVector2d::operator+= (const imath::TVector< 2 > & vector) inline
Definition at line 254 of file CVector2d.h.
References imath::TVector< 2 >::operator+=().
CVector2d i2d::CVector2d::operator- () const inline
Definition at line 215 of file CVector2d.h.
References CVector2d(), GetX(), and GetY().
CVector2d i2d::CVector2d::operator- (const imath::TVector< 2 > & vector) const inline
Definition at line 229 of file CVector2d.h.
References CVector2d(), GetX(), and GetY().
CVector2d & i2d::CVector2d::operator-= (const imath::TVector< 2 > & vector) inline
Definition at line 263 of file CVector2d.h.
References imath::TVector< 2 >::operator-=().
CVector2d i2d::CVector2d::operator/ (double scalar) const inline
Definition at line 243 of file CVector2d.h.
References CVector2d(), GetX(), GetY(), and I_BIG_EPSILON.
CVector2d & i2d::CVector2d::operator/= (double scalar) inline
Definition at line 279 of file CVector2d.h.
References imath::TVector< 2 >::operator/=().
void i2d::CVector2d::SetX (double x) inline
Set X position of this vector.
Definition at line 167 of file CVector2d.h.
References imath::TVector< 2 >::operator[]().
Referenced by i2d::CMatrix2d::GetAxesLengths(), and iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnToolsButtonMenuActionTriggered().
void i2d::CVector2d::SetY (double y) inline
Set Y position of this vector.
Definition at line 179 of file CVector2d.h.
References imath::TVector< 2 >::operator[]().
Referenced by i2d::CMatrix2d::GetAxesLengths(), and iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnToolsButtonMenuActionTriggered().
istd::CIndex2d i2d::CVector2d::ToIndex2d () const
Get vector converted to 2D index.
The documentation for this class was generated from the following file:
Include/i2d/CVector2d.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy