icomp::TMultiAttribute< Value > Class Template Reference
icomp::TMultiAttribute< Value > Class Template Reference
Template implementation of multiple component attribute.
#include <TMultiAttribute.h>
Classes
struct Wrap
Public Types
enum DefaultAttributeFlags { DAF_OBLIGATORY = IAttributeStaticInfo::AF_OBLIGATORY | IAttributeStaticInfo::AF_NULLABLE | IAttributeStaticInfo::AF_MULTIPLE | IAttributeStaticInfo::AF_VALUE, DAF_OPTIONAL = IAttributeStaticInfo::AF_NULLABLE | IAttributeStaticInfo::AF_MULTIPLE | IAttributeStaticInfo::AF_VALUE }
typedef Value ValueType
typedef
iser::TCopySerializedWrap
< iser::IObject > BaseClass
Public Types inherited from iser::TCopySerializedWrap< iser::IObject >
typedef
istd::TUpdateManagerWrap
< iser::IObject > BaseClass
Public Types inherited from istd::TUpdateManagerWrap< iser::IObject >
typedef iser::IObject BaseClass
Public Types inherited from istd::IChangeable
enum ChangeFlags {
CF_ACF_INTERNAL = 1 << 0, CF_MODEL = 1 << 1, CF_ABORTED = 1 << 2, CF_DELEGATED = 1 << 3,
CF_NO_UNDO = 1 << 5
}
enum SupportedOperations {
SO_NONE = 0, SO_OBSERVE = 1, SO_COPY = 2, SO_CLONE = 4,
SO_COMPARE = 8
}
Flags for supported operations.
enum CompatibilityMode { CM_STRICT, CM_WITHOUT_REFS, CM_WITH_REFS, CM_CONVERT }
Control how relationship betweeen objects are interpreted.
Public Member Functions
TMultiAttribute ()
TMultiAttribute (const TMultiAttribute &attribute)
TMultiAttribute (int elementsCount, Value *valuesPtr)
Constructor.
virtual int GetValuesCount () const
virtual const Value & GetValueAt (int index) const
virtual void SetValueAt (int index, const Value &value)
virtual void InsertValue (const Value &value)
virtual void Reset ()
virtual int FindValue (const Value &value) const
QByteArray GetFactoryId () const
virtual bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
template<>
QByteArray GetTypeName ()
template<>
QByteArray GetTypeName ()
template<>
QByteArray GetTypeName ()
template<>
QByteArray GetTypeName ()
template<>
QByteArray GetTypeName ()
Public Member Functions inherited from iser::TCopySerializedWrap< iser::IObject >
virtual bool CopyFrom (const istd::IChangeable &object, istd::IChangeable::CompatibilityMode mode=BaseClass::CM_WITHOUT_REFS)
virtual bool IsEqual (const istd::IChangeable &object) const
Public Member Functions inherited from istd::TUpdateManagerWrap< iser::IObject >
TUpdateManagerWrap ()
virtual void BeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
virtual void EndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Public Member Functions inherited from iser::ISerializable
virtual quint32 GetMinimalVersion (int versionId) const
Get minimal needed version to correct storing of this data.
Public Member Functions inherited from istd::IChangeable
virtual int GetSupportedOperations () const
Get set of flags for supported operations.
virtual IChangeable * CloneMe (CompatibilityMode mode=CM_WITHOUT_REFS) const
Make a copy of this object.
virtual bool ResetData (CompatibilityMode mode=CM_WITHOUT_REFS)
Reset data to its default state.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Static Public Member Functions
static QByteArray GetTypeName ()
Protected Attributes
QVector< Wrap > m_values
Additional Inherited Members
Protected Member Functions inherited from istd::IChangeable
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for begin change event.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for end change event.
Detailed Description
template<typename Value>
class icomp::TMultiAttribute< Value >
Template implementation of multiple component attribute.
Definition at line 28 of file TMultiAttribute.h.
Member Typedef Documentation
template<typename Value> typedef iser::TCopySerializedWrap<iser::IObject> icomp::TMultiAttribute< Value >::BaseClass
Definition at line 32 of file TMultiAttribute.h.
template<typename Value> typedef Value icomp::TMultiAttribute< Value >::ValueType
Definition at line 31 of file TMultiAttribute.h.
Member Enumeration Documentation
template<typename Value> enum icomp::TMultiAttribute::DefaultAttributeFlags
Enumerator
DAF_OBLIGATORY
DAF_OPTIONAL
Definition at line 34 of file TMultiAttribute.h.
Constructor & Destructor Documentation
template<typename Value > icomp::TMultiAttribute< Value >::TMultiAttribute ()
Definition at line 84 of file TMultiAttribute.h.
template<typename Value > icomp::TMultiAttribute< Value >::TMultiAttribute (const TMultiAttribute< Value > & attribute)
Definition at line 91 of file TMultiAttribute.h.
template<typename Value> icomp::TMultiAttribute< Value >::TMultiAttribute (int elementsCount, Value * valuesPtr)
Constructor.
Parameters
elementsCount number of elements stored at valuesPtr.
valuesPtr pointer to array of elements.
Definition at line 99 of file TMultiAttribute.h.
References icomp::TMultiAttribute< Value >::m_values, and icomp::TMultiAttribute< Value >::Wrap::value.
Member Function Documentation
template<typename Value> int icomp::TMultiAttribute< Value >::FindValue (const Value & value) const virtual
Definition at line 154 of file TMultiAttribute.h.
References icomp::TMultiAttribute< Value >::Wrap::value.
template<typename Value > QByteArray icomp::TMultiAttribute< Value >::GetFactoryId () const virtual
Reimplemented from iser::IObject.
Definition at line 166 of file TMultiAttribute.h.
template<typename Value > QByteArray icomp::TMultiAttribute< Value >::GetTypeName () static
Definition at line 217 of file TMultiAttribute.h.
template<> QByteArray icomp::TMultiAttribute< int >::GetTypeName () inline
Definition at line 228 of file TMultiAttribute.h.
template<> QByteArray icomp::TMultiAttribute< double >::GetTypeName () inline
Definition at line 235 of file TMultiAttribute.h.
template<> QByteArray icomp::TMultiAttribute< bool >::GetTypeName () inline
Definition at line 242 of file TMultiAttribute.h.
template<> QByteArray icomp::TMultiAttribute< QString >::GetTypeName () inline
Definition at line 249 of file TMultiAttribute.h.
template<> QByteArray icomp::TMultiAttribute< QByteArray >::GetTypeName () inline
Definition at line 256 of file TMultiAttribute.h.
template<typename Value > const Value & icomp::TMultiAttribute< Value >::GetValueAt (int index) const virtual
Definition at line 118 of file TMultiAttribute.h.
template<typename Value > int icomp::TMultiAttribute< Value >::GetValuesCount () const virtual
Definition at line 111 of file TMultiAttribute.h.
template<typename Value> void icomp::TMultiAttribute< Value >::InsertValue (const Value & value) virtual
Definition at line 138 of file TMultiAttribute.h.
References icomp::TMultiAttribute< Value >::Wrap::value.
Referenced by icomp::CSimComponentContextBase::InsertMultiAttr().
template<typename Value > void icomp::TMultiAttribute< Value >::Reset () virtual
Definition at line 147 of file TMultiAttribute.h.
template<typename Value > bool icomp::TMultiAttribute< Value >::Serialize (iser::IArchive & archive) virtual
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See Also
iser::IArchive
Implements iser::ISerializable.
Definition at line 175 of file TMultiAttribute.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), NULL, and iser::IArchive::Process().
template<typename Value> void icomp::TMultiAttribute< Value >::SetValueAt (int index, const Value & value) virtual
Definition at line 128 of file TMultiAttribute.h.
Member Data Documentation
template<typename Value> QVector<Wrap> icomp::TMultiAttribute< Value >::m_values protected
Definition at line 77 of file TMultiAttribute.h.
Referenced by icomp::TMultiAttribute< Value >::TMultiAttribute().
The documentation for this class was generated from the following file:
Include/icomp/TMultiAttribute.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy