ACF: istd::TArray< Element, Dimensions >::Iterator Class Reference
istd::TArray< Element, Dimensions >::Iterator Class Reference
#include <TArray.h>
Public Types
typedef TIndex< Dimensions > BaseClass
Public Member Functions
Iterator (const Iterator &iterator)
Element & operator* ()
const Element & operator* () const
Element * operator-> ()
const Element * operator-> () const
Iterator & operator++ ()
Iterator operator++ (int)
Iterator & operator-- ()
Iterator operator-- (int)
Iterator & operator= (const Iterator &iterator)
bool operator== (const Iterator &iterator) const
bool operator!= (const Iterator &iterator) const
Protected Member Functions
Iterator (TArray *arrayPtr)
Friends
class TArray< Element, Dimensions >
Detailed Description
template<class Element, int Dimensions>
class istd::TArray< Element, Dimensions >::Iterator
Definition at line 27 of file TArray.h.
Member Typedef Documentation
template<class Element, int Dimensions> typedef TIndex<Dimensions> istd::TArray< Element, Dimensions >::Iterator::BaseClass
Definition at line 30 of file TArray.h.
Constructor & Destructor Documentation
template<class Element , int Dimensions> istd::TArray< Element, Dimensions >::Iterator::Iterator (const Iterator & iterator) [inline]
Definition at line 389 of file TArray.h.
template<class Element , int Dimensions> istd::TArray< Element, Dimensions >::Iterator::Iterator (TArray * arrayPtr) [inline, protected]
Definition at line 513 of file TArray.h.
References istd::TArray< Element, Dimensions >::GetSizes(), istd::TIndex< Dimensions >::IsInside(), and NULL.
Member Function Documentation
template<class Element , int Dimensions> bool istd::TArray< Element, Dimensions >::Iterator::operator!= (const Iterator & iterator) const [inline]
Definition at line 504 of file TArray.h.
References istd::TArray< Element, Dimensions >::Iterator::operator==().
template<class Element , int Dimensions> const Element & istd::TArray< Element, Dimensions >::Iterator::operator* () const [inline]
Definition at line 396 of file TArray.h.
References istd::TArray< Element, Dimensions >::GetAt(), istd::TArray< Element, Dimensions >::GetSizes(), I_ASSERT, istd::TIndex< Dimensions >::IsInside(), and NULL.
template<class Element , int Dimensions> Element & istd::TArray< Element, Dimensions >::Iterator::operator* () [inline]
Definition at line 406 of file TArray.h.
References istd::TArray< Element, Dimensions >::GetSizes(), I_ASSERT, istd::TIndex< Dimensions >::IsInside(), and NULL.
template<class Element , int Dimensions> TArray< Element, Dimensions >::Iterator istd::TArray< Element, Dimensions >::Iterator::operator++ (int) [inline]
Definition at line 447 of file TArray.h.
References istd::TArray< Element, Dimensions >::GetSizes(), istd::TIndex< Dimensions >::Increase(), and NULL.
template<class Element , int Dimensions> TArray< Element, Dimensions >::Iterator & istd::TArray< Element, Dimensions >::Iterator::operator++ () [inline]
Definition at line 436 of file TArray.h.
References istd::TArray< Element, Dimensions >::GetSizes(), istd::TIndex< Dimensions >::Increase(), and NULL.
template<class Element , int Dimensions> TArray< Element, Dimensions >::Iterator istd::TArray< Element, Dimensions >::Iterator::operator-- (int) [inline]
Definition at line 471 of file TArray.h.
References istd::TIndex< Dimensions >::Decrease(), istd::TArray< Element, Dimensions >::GetSizes(), and NULL.
template<class Element , int Dimensions> TArray< Element, Dimensions >::Iterator & istd::TArray< Element, Dimensions >::Iterator::operator-- () [inline]
Definition at line 460 of file TArray.h.
References istd::TIndex< Dimensions >::Decrease(), istd::TArray< Element, Dimensions >::GetSizes(), and NULL.
template<class Element , int Dimensions> const Element * istd::TArray< Element, Dimensions >::Iterator::operator-> () const [inline]
Definition at line 416 of file TArray.h.
References istd::TArray< Element, Dimensions >::GetAt(), istd::TArray< Element, Dimensions >::GetSizes(), I_ASSERT, istd::TIndex< Dimensions >::IsInside(), and NULL.
template<class Element , int Dimensions> Element * istd::TArray< Element, Dimensions >::Iterator::operator-> () [inline]
Definition at line 426 of file TArray.h.
References istd::TArray< Element, Dimensions >::GetSizes(), I_ASSERT, istd::TIndex< Dimensions >::IsInside(), and NULL.
template<class Element , int Dimensions> TArray< Element, Dimensions >::Iterator & istd::TArray< Element, Dimensions >::Iterator::operator= (const Iterator & iterator) [inline]
Definition at line 484 of file TArray.h.
template<class Element , int Dimensions> bool istd::TArray< Element, Dimensions >::Iterator::operator== (const Iterator & iterator) const [inline]
Definition at line 493 of file TArray.h.
References NULL, and istd::TIndex< Dimensions >::operator==().
Referenced by istd::TArray< Element, Dimensions >::Iterator::operator!=().
Friends And Related Function Documentation
template<class Element, int Dimensions> friend class TArray< Element, Dimensions > [friend]
Definition at line 51 of file TArray.h.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/istd/TArray.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy