iview::TViewImpl< Base > Class Template Reference
iview::TViewImpl< Base > Class Template Reference
#include <TViewImpl.h>
Public Member Functions
TViewImpl ()
void SetDefaultColorShema (const IColorShema *colorShemaPtr, bool releaseFlag=false)
Set default color shema object.
bool IsBackgroundBufferActive () const
void SetBackgroundBufferActive (bool state=true)
bool IsDoubleBufferActive () const
void SetDoubleBufferActive (bool state=true)
const iview::CDrawBuffer & GetBackgroundBuffer () const
iview::CDrawBuffer & GetBackgroundBuffer ()
const iview::CDrawBuffer & GetDoubleBuffer () const
iview::CDrawBuffer & GetDoubleBuffer ()
virtual const iview::IColorShema & GetDefaultColorShema () const
Protected Member Functions
virtual void DrawBuffers (QPaintDevice &nativeContext, const i2d::CRect &clipRect)
virtual void DrawToContext (QPaintDevice &nativeContext, QPainter &context, const i2d::CRect &invalidatedBox)
virtual void OnResize ()
Called if found that display area was resized.
void CheckResize ()
Check if size size was changed and invalidation and OnResize() should be done.
Protected Attributes
istd::TOptDelPtr< const
IColorShema > m_defaultColorShemaPtr
Detailed Description
template<class Base>
class iview::TViewImpl< Base >
Definition at line 23 of file TViewImpl.h.
Constructor & Destructor Documentation
template<class Base > iview::TViewImpl< Base >::TViewImpl ()
Definition at line 157 of file TViewImpl.h.
Member Function Documentation
template<class Base > void iview::TViewImpl< Base >::CheckResize () [protected]
Check if size size was changed and invalidation and OnResize() should be done.
Definition at line 272 of file TViewImpl.h.
template<class Base > void iview::TViewImpl< Base >::DrawBuffers (QPaintDevice & nativeContext, const i2d::CRect & clipRect) [protected, virtual]
Definition at line 168 of file TViewImpl.h.
References iview::CDrawBuffer::CopyRectTo(), iview::CDrawBuffer::Create(), iview::CDrawBuffer::GetDrawContext(), i2d::CRect::GetLeftTop(), i2d::CRect::Intersection(), iview::CDrawBuffer::IsCreated(), i2d::CRect::IsEmpty(), and i2d::CRect::Union().
template<class Base > void iview::TViewImpl< Base >::DrawToContext (QPaintDevice & nativeContext, QPainter & context, const i2d::CRect & invalidatedBox) [protected, virtual]
Definition at line 202 of file TViewImpl.h.
References iview::IColorShema::GetBrush(), iview::IColorShema::GetFont(), i2d::CRect::GetLeftTop(), iview::IColorShema::GetPen(), iqt::GetQRect(), I_ASSERT, i2d::CRect::IsEmpty(), iview::IColorShema::SB_BACKGROUND, iview::IColorShema::SB_NORMAL, iview::IColorShema::SF_NORMAL, and iview::IColorShema::SP_NORMAL.
template<class Base > const iview::CDrawBuffer & iview::TViewImpl< Base >::GetBackgroundBuffer () const [inline]
Definition at line 114 of file TViewImpl.h.
template<class Base > iview::CDrawBuffer & iview::TViewImpl< Base >::GetBackgroundBuffer () [inline]
Definition at line 121 of file TViewImpl.h.
template<class Base > const iview::IColorShema & iview::TViewImpl< Base >::GetDefaultColorShema () const [inline, virtual]
Definition at line 144 of file TViewImpl.h.
template<class Base > const iview::CDrawBuffer & iview::TViewImpl< Base >::GetDoubleBuffer () const [inline]
Definition at line 128 of file TViewImpl.h.
template<class Base > iview::CDrawBuffer & iview::TViewImpl< Base >::GetDoubleBuffer () [inline]
Definition at line 135 of file TViewImpl.h.
template<class Base > bool iview::TViewImpl< Base >::IsBackgroundBufferActive () const [inline]
Definition at line 86 of file TViewImpl.h.
template<class Base > bool iview::TViewImpl< Base >::IsDoubleBufferActive () const [inline]
Definition at line 100 of file TViewImpl.h.
template<class Base > void iview::TViewImpl< Base >::OnResize () [protected, virtual]
Called if found that display area was resized.
Definition at line 255 of file TViewImpl.h.
References iview::CDrawBuffer::IsCreated(), and iview::CDrawBuffer::Reset().
template<class Base > void iview::TViewImpl< Base >::SetBackgroundBufferActive (bool state = true) [inline]
Definition at line 93 of file TViewImpl.h.
template<class Base > void iview::TViewImpl< Base >::SetDefaultColorShema (const IColorShema * colorShemaPtr, bool releaseFlag = false) [inline]
Set default color shema object.
Parameters:
colorShemaPtr pointer to color shema object.
releaseFlag if its true, object will be automatically removed.
Definition at line 79 of file TViewImpl.h.
template<class Base > void iview::TViewImpl< Base >::SetDoubleBufferActive (bool state = true) [inline]
Definition at line 107 of file TViewImpl.h.
Member Data Documentation
template<class Base> istd::TOptDelPtr<const IColorShema> iview::TViewImpl< Base >::m_defaultColorShemaPtr [mutable, protected]
Definition at line 63 of file TViewImpl.h.
The documentation for this class was generated from the following file:
Include/iview/TViewImpl.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy