ibase::TModelObserverCompWrap< ObserverComponent > Class Template Reference
ibase::TModelObserverCompWrap< ObserverComponent > Class Template Reference
Implementation of component wrapper for model observer classes.
#include <TModelObserverCompWrap.h>
Public Types
typedef ObserverComponent BaseClass
Public Member Functions
I_TASSIGN_TO (m_defaultObjectCompPtr, m_defaultModelCompPtr, false)
Protected Member Functions
virtual void OnComponentCreated ()
virtual void OnComponentDestroyed ()
Detailed Description
template<class ObserverComponent>
class ibase::TModelObserverCompWrap< ObserverComponent >
Implementation of component wrapper for model observer classes.
Definition at line 19 of file TModelObserverCompWrap.h.
Member Typedef Documentation
template<class ObserverComponent> typedef ObserverComponent ibase::TModelObserverCompWrap< ObserverComponent >::BaseClass
Reimplemented in iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >, iqt2d::TPolygonBasedParamsGuiComp< iview::CTubePolylineShape, i2d::CTubePolyline >, iqt2d::TPolygonBasedParamsGuiComp< iview::CPolygonShape, i2d::CPolygon >, iqt2d::TPolygonBasedParamsGuiComp< iview::CPolylineShape, i2d::CPolyline >, ifilegui::CFileTreeViewGuiComp, ifilegui::CFileSystemExplorerGuiComp, iqt2d::CMultiBitmapViewComp, iqtprm::CSelectionParamGuiComp, iqtprm::COptionsManagerGuiComp, iqtprm::CButtonBasedSelectionParamGuiComp, iqtdoc::CDocumentMetaInfoEditorComp, iqtprm::CParamsManagerGuiCompBase, iqtgui::TDesignerGuiObserverCompBase< UI, Model, WidgetType >, iqtprm::CFileNameParamGuiComp, iqtgui::TDesignerGuiObserverCompBase< Ui::CFileTreeViewGuiComp, ifile::IFileNameParam >, iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CAnnulusSegment >, iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CLine2d >, iqtgui::TDesignerGuiObserverCompBase< Ui::COptionsManagerGuiComp, iprm::IOptionsManager >, iqtgui::TDesignerGuiObserverCompBase< Ui, PolygonBasedModel >, iqtgui::TDesignerGuiObserverCompBase< Ui::CImagePropertiesFrameComp, iimg::IBitmap >, iqtgui::TDesignerGuiObserverCompBase< Ui, ShapeModel >, iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CPolygon >, iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CRectangle >, iqtgui::TDesignerGuiObserverCompBase< Ui::CFilePreviewGuiComp, ifile::IFileNameParam >, iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::COrientedCircle >, iqtgui::TDesignerGuiObserverCompBase< Ui::CParamsManagerGuiCompBase, iprm::IParamsManager >, iqtgui::TDesignerGuiObserverCompBase< Ui::CFileListProviderGuiComp, ifile::IFileListProvider >, iqtgui::TDesignerGuiObserverCompBase< Ui::CSelectableGuiComp, iprm::ISelectionParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::COptionsListEditorGuiComp, iprm::IOptionsManager >, iqtgui::TDesignerGuiObserverCompBase< Ui::CButtonBasedSelectionParamGuiComp, iprm::ISelectionParam >, iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CTubePolyline >, iqtgui::TDesignerGuiObserverCompBase< Ui::CComposedParamsSetGuiComp, iprm::IParamsSet >, iqtgui::TDesignerGuiObserverCompBase< Ui::CVariableParamGuiComp, iprm::IVariableParam >, iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CAffineTransformation2d >, iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CAnnulus >, iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CPolyline >, iqtgui::TDesignerGuiObserverCompBase< Ui::CFileNameParamGuiComp, ifile::IFileNameParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::CTextLogGuiComp, ilog::IMessageContainer >, iqtgui::TDesignerGuiObserverCompBase< Ui::CNameParamGuiComp, iprm::INameParam >, iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CCircle >, iqtgui::TDesignerGuiObserverCompBase< Ui::CImagePropertyGuiComp, iimg::IBitmap >, iqtgui::TDesignerGuiObserverCompBase< Ui::CCheckableOptionsEditorComp, iprm::IOptionsManager >, iqtgui::TDesignerGuiObserverCompBase< Ui::CFileSystemExplorerGuiComp, ifile::IFileNameParam >, iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CQuadrangle >, iqtgui::TDesignerGuiObserverCompBase< Ui::CEnableableParamGuiComp, iprm::IEnableableParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::CShapeInfoGuiComp, IShapeStatusInfo >, iqtgui::TDesignerGuiObserverCompBase< Ui::CSelectionParamGuiComp, iprm::ISelectionParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::CSelectionParamIndexGuiComp, iprm::ISelectionParam >, iqtgui::CStatusGuiComp, iqtgui::TItemModelEditorCompBase< ItemWidgetClass >, iqtprm::CComposedParamsSetGuiComp, iqtprm::COptionsListEditorGuiComp, iqtgui::TItemModelEditorCompBase< QTableView >, ifilegui::CFilePreviewGuiComp, iqt2d::CImageViewComp, iqtprm::CVariableParamGuiComp, iqt2d::CAnnulusParamsGuiComp, iqt2d::CLine2dParamsGuiComp, iqt2d::CQuadrangleParamsGuiComp, iqtprm::CSelectableGuiComp, iqt2d::CAffineTransformationParamsGuiComp, iqt2d::CAnnulusSegmentParamsGuiComp, iqt2d::CCircleParamsGuiComp, iqt2d::COrientedCircleEditorComp, iqt2d::CRectangleParamsGuiComp, iqtgui::CTableBasedModelEditorComp, iloggui::CTextLogGuiComp, iqtprm::CEnableableParamGuiComp, iqtprm::CMultiParamsManagerGuiComp, iqtprm::CNameParamGuiComp, iqtprm::CSelectionParamIndexGuiComp, iqtprm::CCheckableOptionsEditorComp, ifilegui::CFileListProviderGuiComp, iqtgui::CImagePropertiesFrameComp, iqtgui::CImagePropertyGuiComp, iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui, ShapeModel > >, iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CAnnulus > >, iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CRectangle > >, iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CPolyline > >, iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CPolygon > >, iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui, PolygonBasedModel > >, iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CQuadrangle > >, iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CAnnulusSegment > >, iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::COrientedCircle > >, iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CCircle > >, iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CAffineTransformation2d > >, iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CLine2d > >, iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui, i2d::CTubePolyline > >, iqt2d::CPolylineParamsGuiComp, iqt2d::CTubePolylineParamsGuiComp, iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >, iview::CShapeInfoGuiComp, iqt2d::TShapeParamsGuiCompBase< Ui::CAffineTransformationParamsGui, iview::CAffineTransformation2dShape, i2d::CAffineTransformation2d >, iqt2d::TShapeParamsGuiCompBase< Ui::CLine2dParamsGuiComp, iview::CLineShape, i2d::CLine2d >, iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, iview::CTubePolylineShape, i2d::CTubePolyline >, iqt2d::TShapeParamsGuiCompBase< Ui::CRectangleParamsGuiComp, iview::CRectangleShape, i2d::CRectangle >, iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, PolygonBasedShape, PolygonBasedModel >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusParamsGuiComp, iview::CAnnulusShape, i2d::CAnnulus >, iqt2d::TShapeParamsGuiCompBase< Ui::COrientedCircleEditorComp, iview::COrientedCircleShape, i2d::COrientedCircle >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusSegmentParamsGuiComp, iview::CAnnulusSegmentShape, i2d::CAnnulusSegment >, iqt2d::TShapeParamsGuiCompBase< Ui::CCircleParamsGuiComp, iview::CCircleShape, i2d::CCircle >, iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, iview::CPolygonShape, i2d::CPolygon >, iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, iview::CPolylineShape, i2d::CPolyline >, iqt2d::TShapeParamsGuiCompBase< Ui::CQuadrangleParamsGuiComp, iview::CParallelogramShape, i2d::CQuadrangle >, iqt2d::CPolygonParamsGuiComp, iqtprm::CParamsManagerGuiComp, and iqtprm::CSelectableParamsSetGuiComp.
Definition at line 22 of file TModelObserverCompWrap.h.
Member Function Documentation
template<class ObserverComponent> ibase::TModelObserverCompWrap< ObserverComponent >::I_TASSIGN_TO (m_defaultObjectCompPtr , m_defaultModelCompPtr , false)
template<class ObserverComponent > void ibase::TModelObserverCompWrap< ObserverComponent >::OnComponentCreated () [protected, virtual]
Reimplemented in ifilegui::CFileTreeViewGuiComp.
Definition at line 46 of file TModelObserverCompWrap.h.
References icomp::CComponentContext::GetCompleteContextId(), icomp::IComponent::GetComponentContext(), icomp::IComponentContext::GetContextId(), I_IF_DEBUG, and NULL.
template<class ObserverComponent > void ibase::TModelObserverCompWrap< ObserverComponent >::OnComponentDestroyed () [protected, virtual]
Reimplemented in iqt2d::CMultiBitmapViewComp, and ifilegui::CFileTreeViewGuiComp.
Definition at line 96 of file TModelObserverCompWrap.h.
The documentation for this class was generated from the following file:
Include/ibase/TModelObserverCompWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy