iview::IIsomorphicCalibration Class Reference
iview::IIsomorphicCalibration Class Reference
This is common interface for all isomorphic calibrations.
#include <IIsomorphicCalibration.h>
Public Member Functions
virtual CalcStatus GetApplyToLog (const i2d::CVector2d &viewPosition, i2d::CVector2d &result) const =0
Transform position to logical coordination system.
virtual CalcStatus GetApplyToView (const i2d::CVector2d &logPosition, i2d::CVector2d &result) const =0
Transform position to view coordination system.
Detailed Description
This is common interface for all isomorphic calibrations.
This calibration can transform beetween view and isomorphic coordinate systems. Please note, that is only possible for simple calibration methods.
Definition at line 19 of file IIsomorphicCalibration.h.
Member Function Documentation
virtual CalcStatus iview::IIsomorphicCalibration::GetApplyToLog (const i2d::CVector2d & viewPosition, i2d::CVector2d & result) const [pure virtual]
Transform position to logical coordination system.
Parameters:
viewPos position in view coordination system.
Returns:
true, if it was possible to transform, otherwíse false.
Implemented in iview::CScaleCalibration, iview::CPerspectiveCalibration, iview::CAffiniteCalibration, and iview::CNoneCalibration.
Referenced by iview::TMultiPolylineCalibrationShape< SegmentData >::OnMouseButton(), and iview::TFramedViewBase< ViewBase >::OnMouseMove().
virtual CalcStatus iview::IIsomorphicCalibration::GetApplyToView (const i2d::CVector2d & logPosition, i2d::CVector2d & result) const [pure virtual]
Transform position to view coordination system.
Parameters:
logPos position in logical coordination system.
Returns:
true, if it was possible to transform, otherwise false.
Implemented in iview::CScaleCalibration, iview::CPerspectiveCalibration, iview::CAffiniteCalibration, and iview::CNoneCalibration.
Referenced by iview::TMultiPolylineCalibrationShape< SegmentData >::CalcBoundingBox(), iview::TMultiPolylineCalibrationShape< SegmentData >::DrawCurve(), iview::TMultiPolylineCalibrationShape< SegmentData >::DrawSelectionElements(), iview::TMultiPolylineCalibrationShape< SegmentData >::IsCurveTouched(), iview::TMultiPolylineCalibrationShape< SegmentData >::IsTouched(), iview::TMultiPolylineCalibrationShape< SegmentData >::OnMouseButton(), and iview::TMultiPolylineCalibrationShape< SegmentData >::TrySelectSegments().
The documentation for this class was generated from the following file:
Include/iview/IIsomorphicCalibration.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy