ACF: ibase::TLoggerCompWrap< Base > Class Template Reference
ibase::TLoggerCompWrap< Base > Class Template Reference
[Set of helper classes.]
Wrapper provider of log-functionality for component based implementations.
#include <TLoggerCompWrap.h>
Public Types
typedef ibase::TLoggerWrap< Base > BaseClass
Protected Member Functions
virtual void DecorateMessage (istd::ILogger::MessageCategory category, int id, int flags, istd::CString &message, istd::CString &messageSource) const
Decorate message parts before outputting.
virtual void OnComponentCreated ()
Detailed Description
template<class Base>
class ibase::TLoggerCompWrap< Base >
Wrapper provider of log-functionality for component based implementations.
Definition at line 23 of file TLoggerCompWrap.h.
Member Typedef Documentation
template<class Base> typedef ibase::TLoggerWrap<Base> ibase::TLoggerCompWrap< Base >::BaseClass
Reimplemented in ibase::CExternalFileConverterComp, ibase::CFileConvertOverProcessorComp, ibase::TFileSerializerComp< ReadArchive, WriteArchive >, icmpstr::CPackagesLoaderExtComp, icmpstr::CRegistryLoaderComp, icmpstr::CVisualRegistryComp, iproc::CIterativeProcessorComp, iproc::CModelBasedProcessingTriggerComp, iproc::TSupplierCompWrap< SupplierInterface, Product >, iproc::TSyncProcessorCompBase< Base, Interface >, iqt::CBitmapLoaderComp, iqt::CClipboardSerializerComp, iqt::CCopyProcessorComp, iqt::CFileInfoCopyComp, iqt::CPackagesLoaderComp, iqt::CProcessExecutorComp, iqt::CRegistriesManagerComp, iqt::CSettingsSerializerComp, iqt::CXslSerializerComp, iqtgui::CFileDialogLoaderComp, iqtmm::CFrameSeqVideoControllerComp, iqtmm::CMediaLoaderComp, iqtmm::CSvgBitmapLoaderComp, iqtproc::CDocumentProcessingCommandComp, iqtproc::CDocumentProcessingManagerComp, iqtproc::CDocumentProcessingManagerCompBase, ibase::TFileSerializerComp< iser::CXmlFileReadArchive, iser::CXmlFileWriteArchive >, icomp::TComponentWrap< iqt::CPackagesLoaderComp >, icomp::TSimComponentWrap< iqt::CPackagesLoaderComp >, and iproc::TSyncProcessorCompBase< iproc::IBitmapAcquisition >.
Definition at line 26 of file TLoggerCompWrap.h.
Member Function Documentation
template<class Base > void ibase::TLoggerCompWrap< Base >::DecorateMessage (istd::ILogger::MessageCategory category, int id, int flags, istd::CString & message, istd::CString & messageSource) const [inline, protected, virtual]
Decorate message parts before outputting.
Reimplemented from istd::ILogger.
Definition at line 54 of file TLoggerCompWrap.h.
References istd::ILogger::DecorateMessage(), icomp::CComponentContext::GetContextId(), and NULL.
template<class Base > void ibase::TLoggerCompWrap< Base >::OnComponentCreated () [inline, protected, virtual]
Reimplemented in iproc::CIterativeProcessorComp, iproc::CModelBasedProcessingTriggerComp, iproc::TSupplierCompWrap< SupplierInterface, Product >, iqt::CCopyProcessorComp, iqt::CPackagesLoaderComp, iqt::CRegistriesManagerComp, iqtgui::CFileDialogLoaderComp, and iqtproc::CDocumentProcessingManagerCompBase.
Definition at line 78 of file TLoggerCompWrap.h.
References ibase::TLoggerWrap< Base >::SetLogPtr().
Referenced by iproc::TSupplierCompWrap< SupplierInterface, Product >::OnComponentCreated().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/ibase/TLoggerCompWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy