i2d::TMultiPolyline< SegmentData >::CSegment Class Reference
i2d::TMultiPolyline< SegmentData >::CSegment Class Reference
#include <TMultiPolyline.h>
Public Member Functions
bool Serialize (iser::IArchive &archive)
CSegment operator+ (const CSegment &x) const
CSegment operator/ (double x) const
CSegment & operator/= (double x)
Detailed Description
template<class SegmentData>
class i2d::TMultiPolyline< SegmentData >::CSegment
Definition at line 54 of file TMultiPolyline.h.
Member Function Documentation
template<class SegmentData > CSegment i2d::TMultiPolyline< SegmentData >::CSegment::operator+ (const CSegment & x) const [inline]
Definition at line 74 of file TMultiPolyline.h.
References I_ASSERT.
template<class SegmentData > CSegment i2d::TMultiPolyline< SegmentData >::CSegment::operator/ (double x) const [inline]
Definition at line 86 of file TMultiPolyline.h.
template<class SegmentData > CSegment& i2d::TMultiPolyline< SegmentData >::CSegment::operator/= (double x) [inline]
Definition at line 93 of file TMultiPolyline.h.
References i2d::TMultiPolyline< SegmentData >::m_widthList.
template<class SegmentData > bool i2d::TMultiPolyline< SegmentData >::CSegment::Serialize (iser::IArchive & archive) [inline]
Definition at line 57 of file TMultiPolyline.h.
References iser::IArchive::BeginTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), i2d::TMultiPolyline< SegmentData >::m_data, i2d::TMultiPolyline< SegmentData >::m_selected, i2d::TMultiPolyline< SegmentData >::m_widthList, and iser::IArchive::Process().
The documentation for this class was generated from the following file:
Include/i2d/TMultiPolyline.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy