ACF: iqt2d::TShapeBase< GraphicsItemClass > Class Template Reference
iqt2d::TShapeBase< GraphicsItemClass > Class Template Reference
#include <TShapeBase.h>
Public Types
enum ColorSheme { SelectedColor, EditableColor, InactiveColor, DefaultColor = InactiveColor }
typedef GraphicsItemClass BaseClass
Public Member Functions
TShapeBase (bool isEditable=false, const ISceneProvider *providerPtr=NULL)
virtual void SetPen (int colorSheme, const QPen &pen)
virtual QPen GetPen (int colorSheme) const
virtual void SetBrush (int colorSheme, const QBrush &pen)
virtual QBrush GetBrush (int colorSheme) const
virtual void SwitchColorSheme (int colorSheme)
bool IsEditable () const
void SetEditable (bool isEditable)
const ISceneProvider * GetSceneProvider () const
template<>
void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *)
template<>
void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *)
Protected Member Functions
i2d::CVector2d GetPosFromLocal (const QPointF &position) const
Map position from local graphics item coordinates.
QPointF GetLocalFromPos (const i2d::CVector2d &position) const
Map position from local graphics item coordinates.
virtual void OnSelectionChanged (bool isSelected)
virtual void OnPositionChanged (const QPointF &position)
virtual QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=NULL)
Detailed Description
template<class GraphicsItemClass>
class iqt2d::TShapeBase< GraphicsItemClass >
Definition at line 26 of file TShapeBase.h.
Member Typedef Documentation
template<class GraphicsItemClass> typedef GraphicsItemClass iqt2d::TShapeBase< GraphicsItemClass >::BaseClass
Reimplemented in icmpstr::CRegistryElementShape, iqt2d::CAnnulusSegmentShape, iqt2d::CAnnulusShape, iqt2d::CCircleShape, iqt2d::CGripShape, iqt2d::CLine2dShape, iqt2d::CPosition2dShape, iqt2d::CQuadrangleShape, iqt2d::CRectangleShape, iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >, iqt2d::TObjectShapeBase< QGraphicsPathItem, i2d::CAnnulus >, iqt2d::TObjectShapeBase< QGraphicsRectItem, CVisualRegistryElement >, iqt2d::TObjectShapeBase< QGraphicsPathItem, i2d::CRectangle >, iqt2d::TObjectShapeBase< QGraphicsPathItem, i2d::CQuadrangle >, iqt2d::TObjectShapeBase< QGraphicsEllipseItem, i2d::CCircle >, and iqt2d::TObjectShapeBase< QGraphicsLineItem, i2d::CLine2d >.
Definition at line 29 of file TShapeBase.h.
Member Enumeration Documentation
template<class GraphicsItemClass> enum iqt2d::TShapeBase::ColorSheme
Enumerator:
SelectedColor Color for a selected shape.
EditableColor Color for a shape, that can be edited on the graphics view.
InactiveColor Color for a shape, that can not be edited on the graphics view.
DefaultColor Standard shape color.
Definition at line 31 of file TShapeBase.h.
Constructor & Destructor Documentation
template<class GraphicsItemClass > iqt2d::TShapeBase< GraphicsItemClass >::TShapeBase (bool isEditable = false, const ISceneProvider * providerPtr = NULL) [inline]
Definition at line 102 of file TShapeBase.h.
Member Function Documentation
template<class GraphicsItemClass > QBrush iqt2d::TShapeBase< GraphicsItemClass >::GetBrush (int colorSheme) const [inline, virtual]
Definition at line 150 of file TShapeBase.h.
template<class GraphicsItemClass > QPointF iqt2d::TShapeBase< GraphicsItemClass >::GetLocalFromPos (const i2d::CVector2d & position) const [inline, protected]
Map position from local graphics item coordinates.
Definition at line 218 of file TShapeBase.h.
References iqt::GetQPointF().
template<class GraphicsItemClass > QPen iqt2d::TShapeBase< GraphicsItemClass >::GetPen (int colorSheme) const [inline, virtual]
Definition at line 125 of file TShapeBase.h.
template<class GraphicsItemClass > i2d::CVector2d iqt2d::TShapeBase< GraphicsItemClass >::GetPosFromLocal (const QPointF & position) const [inline, protected]
Map position from local graphics item coordinates.
Definition at line 211 of file TShapeBase.h.
References iqt::GetCVector2d().
template<class GraphicsItemClass > const ISceneProvider * iqt2d::TShapeBase< GraphicsItemClass >::GetSceneProvider () const [inline]
Definition at line 202 of file TShapeBase.h.
template<class GraphicsItemClass > void iqt2d::TShapeBase< GraphicsItemClass >::hoverEnterEvent (QGraphicsSceneHoverEvent * event) [inline, protected, virtual]
Definition at line 290 of file TShapeBase.h.
References iqt2d::TShapeBase< GraphicsItemClass >::OnSelectionChanged().
template<class GraphicsItemClass > void iqt2d::TShapeBase< GraphicsItemClass >::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) [inline, protected, virtual]
Definition at line 299 of file TShapeBase.h.
template<class GraphicsItemClass > bool iqt2d::TShapeBase< GraphicsItemClass >::IsEditable () const [inline]
Definition at line 182 of file TShapeBase.h.
template<class GraphicsItemClass > QVariant iqt2d::TShapeBase< GraphicsItemClass >::itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant & value) [inline, protected, virtual]
Reimplemented in iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >, iqt2d::TObjectShapeBase< QGraphicsPathItem, i2d::CAnnulus >, iqt2d::TObjectShapeBase< QGraphicsRectItem, CVisualRegistryElement >, iqt2d::TObjectShapeBase< QGraphicsPathItem, i2d::CRectangle >, iqt2d::TObjectShapeBase< QGraphicsPathItem, i2d::CQuadrangle >, iqt2d::TObjectShapeBase< QGraphicsEllipseItem, i2d::CCircle >, and iqt2d::TObjectShapeBase< QGraphicsLineItem, i2d::CLine2d >.
Definition at line 245 of file TShapeBase.h.
References iqt::GetCRectangle(), iqt::GetCVector2d(), i2d::CRectangle::GetNearestPointTo(), iqt::GetQPointF(), NULL, and iqt2d::ISceneProvider::SF_FIXED_SIZE.
template<class GraphicsItemClass > void iqt2d::TShapeBase< GraphicsItemClass >::OnPositionChanged (const QPointF & position) [inline, protected, virtual]
Reimplemented in iqt2d::CGripShape, iqt2d::CPosition2dShape, iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >, iqt2d::TObjectShapeBase< QGraphicsPathItem, i2d::CAnnulus >, iqt2d::TObjectShapeBase< QGraphicsRectItem, CVisualRegistryElement >, iqt2d::TObjectShapeBase< QGraphicsPathItem, i2d::CRectangle >, iqt2d::TObjectShapeBase< QGraphicsPathItem, i2d::CQuadrangle >, iqt2d::TObjectShapeBase< QGraphicsEllipseItem, i2d::CCircle >, and iqt2d::TObjectShapeBase< QGraphicsLineItem, i2d::CLine2d >.
Definition at line 237 of file TShapeBase.h.
template<class GraphicsItemClass > void iqt2d::TShapeBase< GraphicsItemClass >::OnSelectionChanged (bool isSelected) [inline, protected, virtual]
Reimplemented in icmpstr::CRegistryElementShape, iqt2d::CGripShape, iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >, iqt2d::TObjectShapeBase< QGraphicsPathItem, i2d::CAnnulus >, iqt2d::TObjectShapeBase< QGraphicsRectItem, CVisualRegistryElement >, iqt2d::TObjectShapeBase< QGraphicsPathItem, i2d::CRectangle >, iqt2d::TObjectShapeBase< QGraphicsPathItem, i2d::CQuadrangle >, iqt2d::TObjectShapeBase< QGraphicsEllipseItem, i2d::CCircle >, and iqt2d::TObjectShapeBase< QGraphicsLineItem, i2d::CLine2d >.
Definition at line 225 of file TShapeBase.h.
Referenced by iqt2d::TShapeBase< GraphicsItemClass >::hoverEnterEvent().
template<> void iqt2d::TShapeBase< QAbstractGraphicsShapeItem >::paint (QPainter * , const QStyleOptionGraphicsItem * , QWidget *) [inline]
Definition at line 334 of file TShapeBase.h.
template<> void iqt2d::TShapeBase< QGraphicsItem >::paint (QPainter * , const QStyleOptionGraphicsItem * , QWidget *) [inline]
Definition at line 328 of file TShapeBase.h.
template<class GraphicsItemClass > void iqt2d::TShapeBase< GraphicsItemClass >::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = NULL) [inline, protected, virtual]
Reimplemented in icmpstr::CRegistryElementShape.
Definition at line 308 of file TShapeBase.h.
References NULL.
template<class GraphicsItemClass > void iqt2d::TShapeBase< GraphicsItemClass >::SetBrush (int colorSheme, const QBrush & pen) [inline, virtual]
Definition at line 136 of file TShapeBase.h.
template<class GraphicsItemClass > void iqt2d::TShapeBase< GraphicsItemClass >::SetEditable (bool isEditable) [inline]
Definition at line 189 of file TShapeBase.h.
template<class GraphicsItemClass > void iqt2d::TShapeBase< GraphicsItemClass >::SetPen (int colorSheme, const QPen & pen) [inline, virtual]
Definition at line 111 of file TShapeBase.h.
template<class GraphicsItemClass > void iqt2d::TShapeBase< GraphicsItemClass >::SwitchColorSheme (int colorSheme) [inline, virtual]
Definition at line 161 of file TShapeBase.h.
References NULL.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iqt2d/TShapeBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy