iview::TMultiPolylineCalibrationShape< SegmentData > Class Template Reference
iview::TMultiPolylineCalibrationShape< SegmentData > Class Template Reference
#include <TMultiPolylineCalibrationShape.h>
Public Types
typedef CPolylineCalibrationShape BaseClass
Public Member Functions
TMultiPolylineCalibrationShape ()
virtual bool IsOrientationVisible () const
virtual void SetOrientationVisible (bool state=true)
Set the orientation to be visible or not.
virtual bool IsAlwaysMovable () const
Check if in all edit modes is this shape draggable.
virtual void SetAlwaysMovable (bool state=true)
Set flag if in all edit modes is this shape draggable.
virtual bool OnMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag)
It is called, when mouse button is pushed down or up on this object.
virtual bool OnAttached (imod::IModel *modelPtr)
This call back function will be called, if an observable object is about to be attached.
virtual TouchState IsTouched (istd::CIndex2d position) const
Check, if any shape is touched.
virtual void SetSelected (bool selectFlag)
Inform that this object was selected or deselected.
virtual void CalcBoundingBox (i2d::CRect &result) const
Calculate bounding box.
Protected Member Functions
virtual void DrawCurve (QPainter &drawContext) const
virtual void DrawSelectionElements (QPainter &drawContext) const
virtual bool IsCurveTouched (istd::CIndex2d position) const
bool TrySelectSegments (iview::TMultiPolyline< SegmentData > &polyline, istd::CIndex2d position)
void CalculateRemovePoints (const iview::TMultiPolyline< SegmentData > &polyline, int segment, i2d::CVector2d &first, i2d::CVector2d &second) const
virtual void EnsureValidNodes () const
Detailed Description
template<class SegmentData>
class iview::TMultiPolylineCalibrationShape< SegmentData >
Definition at line 14 of file TMultiPolylineCalibrationShape.h.
Member Typedef Documentation
template<class SegmentData > typedef CPolylineCalibrationShape iview::TMultiPolylineCalibrationShape< SegmentData >::BaseClass
Reimplemented from iview::CPolylineCalibrationShape.
Definition at line 17 of file TMultiPolylineCalibrationShape.h.
Constructor & Destructor Documentation
template<class SegmentData > iview::TMultiPolylineCalibrationShape< SegmentData >::TMultiPolylineCalibrationShape ()
Definition at line 114 of file TMultiPolylineCalibrationShape.h.
Member Function Documentation
template<class SegmentData > void iview::TMultiPolylineCalibrationShape< SegmentData >::CalcBoundingBox (i2d::CRect & result) const [virtual]
Calculate bounding box.
You have to implement this method in your shapes implementations.
Reimplemented from iview::CPolygonCalibrationShape.
Definition at line 743 of file TMultiPolylineCalibrationShape.h.
References i2d::CRect::GetBottom(), i2d::ITransformation2d::GetInvPositionAt(), i2d::CRect::GetRight(), iview::CScreenTransform::GetScreenPosition(), NULL, i2d::CRect::Reset(), i2d::CRect::SetBottom(), i2d::CRect::SetRight(), and i2d::CRect::Union().
template<class SegmentData > void iview::TMultiPolylineCalibrationShape< SegmentData >::CalculateRemovePoints (const iview::TMultiPolyline< SegmentData > & polyline, int segment, i2d::CVector2d & first, i2d::CVector2d & second) const [protected]
Definition at line 794 of file TMultiPolylineCalibrationShape.h.
template<class SegmentData > void iview::TMultiPolylineCalibrationShape< SegmentData >::DrawCurve (QPainter & drawContext) const [protected, virtual]
Reimplemented from iview::CPolylineCalibrationShape.
Definition at line 294 of file TMultiPolylineCalibrationShape.h.
References imath::TVector< Size, Element >::GetDistance(), i2d::ITransformation2d::GetInvPositionAt(), i2d::CVector2d::GetOrthogonal(), iview::IColorShema::GetPen(), iview::CScreenTransform::GetScreenPosition(), I_ASSERT, I_EPSILON, NULL, iview::IColorShema::SP_NORMAL_DASH, iview::IColorShema::SP_SELECTED, and iview::IColorShema::SP_SELECTED_DASH.
template<class SegmentData > void iview::TMultiPolylineCalibrationShape< SegmentData >::DrawSelectionElements (QPainter & drawContext) const [protected, virtual]
Reimplemented from iview::CPolylineCalibrationShape.
Definition at line 382 of file TMultiPolylineCalibrationShape.h.
References iview::IColorShema::DrawTicker(), iview::ISelectable::EM_ADD, iview::ISelectable::EM_MOVE, iview::ISelectable::EM_NONE, iview::ISelectable::EM_REMOVE, i2d::ITransformation2d::GetInvPositionAt(), iview::CScreenTransform::GetScreenPosition(), NULL, iview::IColorShema::TT_DELETE, iview::IColorShema::TT_INSERT, iview::IColorShema::TT_MOVE, and iview::IColorShema::TT_SELECTED_INACTIVE.
template<class SegmentData > void iview::TMultiPolylineCalibrationShape< SegmentData >::EnsureValidNodes () const [protected, virtual]
Reimplemented from iview::CPolygonCalibrationShape.
Definition at line 806 of file TMultiPolylineCalibrationShape.h.
References imath::TVector< Size, Element >::GetDotProduct(), i2d::CVector2d::GetNormalized(), i2d::CVector2d::GetOrthogonal(), NULL, i2d::CVector2d::SetX(), and i2d::CVector2d::SetY().
template<class SegmentData > bool iview::TMultiPolylineCalibrationShape< SegmentData >::IsAlwaysMovable () const [inline, virtual]
Check if in all edit modes is this shape draggable.
Normally it is possible to drag this object only in EM_NONE mode.
Reimplemented from iview::CPolygonCalibrationShape.
Definition at line 100 of file TMultiPolylineCalibrationShape.h.
template<class SegmentData > bool iview::TMultiPolylineCalibrationShape< SegmentData >::IsCurveTouched (istd::CIndex2d position) const [protected, virtual]
Reimplemented from iview::CPolylineCalibrationShape.
Definition at line 466 of file TMultiPolylineCalibrationShape.h.
References iview::CScreenTransform::GetClientPosition(), i2d::CAffine2d::GetDeformMatrix(), imath::TVector< Size, Element >::GetDotProduct(), i2d::ITransformation2d::GetInvPositionAt(), iview::IColorShema::GetLogicalLineWidth(), i2d::CVector2d::GetOrthogonal(), I_ASSERT, and NULL.
template<class SegmentData > bool iview::TMultiPolylineCalibrationShape< SegmentData >::IsOrientationVisible () const [inline, virtual]
Reimplemented from iview::CPolylineCalibrationShape.
Definition at line 83 of file TMultiPolylineCalibrationShape.h.
template<class SegmentData > iview::ITouchable::TouchState iview::TMultiPolylineCalibrationShape< SegmentData >::IsTouched (istd::CIndex2d position) const [virtual]
Check, if any shape is touched.
When shape is touched, it return also pointer to this shape.
Returns:
touch state for the shape, or iview::IInteractiveShape::TS_NONE, when nothing found.
Reimplemented from iview::CPolygonCalibrationShape.
Definition at line 603 of file TMultiPolylineCalibrationShape.h.
References iview::ISelectable::EM_ADD, iview::ISelectable::EM_MOVE, iview::ISelectable::EM_NONE, iview::ISelectable::EM_REMOVE, iview::CTransformableRectangleCalibrationShape::EnsureValidNodes(), i2d::ITransformation2d::GetInvPositionAt(), iview::CScreenTransform::GetScreenPosition(), iview::IColorShema::GetTickerBox(), i2d::CRect::IsInside(), iview::CTransformableRectangleCalibrationShape::IsParallTouched(), iview::CTransformableRectangleCalibrationShape::IsTickerTouched(), NULL, iview::IColorShema::TT_DELETE, iview::IColorShema::TT_INSERT, and iview::IColorShema::TT_MOVE.
template<class SegmentData > bool iview::TMultiPolylineCalibrationShape< SegmentData >::OnAttached (imod::IModel * modelPtr) [virtual]
This call back function will be called, if an observable object is about to be attached.
This function returns a true, if observable object is accepted by the implementation logic of the observer, otherwise the function returns a false.
Reimplemented from iview::CPolylineCalibrationShape.
Definition at line 283 of file TMultiPolylineCalibrationShape.h.
References I_ASSERT, and NULL.
template<class SegmentData > bool iview::TMultiPolylineCalibrationShape< SegmentData >::OnMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag) [virtual]
It is called, when mouse button is pushed down or up on this object.
Parameters:
position - position of mouse pointer on client area (picture coords).
downFlag - true, if mouse button is pushed down, false if pushed up.
Returns:
true if this shape should get focus to catch all mouse movements.
Reimplemented from iview::CPolylineCalibrationShape.
Definition at line 124 of file TMultiPolylineCalibrationShape.h.
References iview::ISelectable::EM_ADD, iview::ISelectable::EM_MOVE, iview::ISelectable::EM_NONE, iview::ISelectable::EM_REMOVE, iview::CScreenTransform::GetClientPosition(), i2d::ITransformation2d::GetInvPositionAt(), i2d::ITransformation2d::GetPositionAt(), iview::CScreenTransform::GetScreenPosition(), iview::IColorShema::GetTickerBox(), i2d::CRect::IsInside(), NULL, iview::CTransformableRectangleCalibrationShape::OnMouseButton(), iview::IColorShema::TT_INSERT, and iview::IColorShema::TT_MOVE.
template<class SegmentData > void iview::TMultiPolylineCalibrationShape< SegmentData >::SetAlwaysMovable (bool state = true) [inline, virtual]
Set flag if in all edit modes is this shape draggable.
See also:
IsAlwaysMovable()
Reimplemented from iview::CPolygonCalibrationShape.
Definition at line 107 of file TMultiPolylineCalibrationShape.h.
template<class SegmentData > void iview::TMultiPolylineCalibrationShape< SegmentData >::SetOrientationVisible (bool state = true) [inline, virtual]
Set the orientation to be visible or not.
Parameters:
state if true, orientation will be visible.
Reimplemented from iview::CPolylineCalibrationShape.
Definition at line 90 of file TMultiPolylineCalibrationShape.h.
template<class SegmentData > void iview::TMultiPolylineCalibrationShape< SegmentData >::SetSelected (bool selectFlag) [virtual]
Inform that this object was selected or deselected.
Parameters:
selectFlag if true - selection, else deselection.
Reimplemented from iview::CInteractiveShapeBase.
Definition at line 724 of file TMultiPolylineCalibrationShape.h.
References NULL.
template<class SegmentData > bool iview::TMultiPolylineCalibrationShape< SegmentData >::TrySelectSegments (iview::TMultiPolyline< SegmentData > & polyline, istd::CIndex2d position) [protected]
Definition at line 518 of file TMultiPolylineCalibrationShape.h.
References iview::CScreenTransform::GetClientPosition(), i2d::CAffine2d::GetDeformMatrix(), imath::TVector< Size, Element >::GetDotProduct(), i2d::ITransformation2d::GetInvPositionAt(), iview::IColorShema::GetLogicalLineWidth(), i2d::CVector2d::GetOrthogonal(), and NULL.
The documentation for this class was generated from the following file:
Include/iview/TMultiPolylineCalibrationShape.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy