imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums > Class Template Reference
imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums > Class Template Reference
Base class for interpolated functions based on fulcrums in multi-dimesional grid.
#include <TFulcrumGridFunctionBase.h>
Public Types
enum ChangeFlags { CF_SORT_LAYERS = 1 << 29 }
typedef
istd::TCachedUpdateManagerWrap
< iser::ISerializable > BaseClass
typedef TIMathFunction
< Argument, Result > BaseClass2
typedef Fulcrums::ElementType FulcrumType
typedef Fulcrums::IndexType FulcrumIndex
typedef Fulcrums::SizesType FulcrumSizes
typedef TIMathFunction
< Argument, Result >
::ArgumentType ArgumentType
Public Types inherited from istd::TCachedUpdateManagerWrap< iser::ISerializable >
typedef TUpdateManagerWrap
< iser::ISerializable > BaseClass
Public Types inherited from istd::TUpdateManagerWrap< iser::ISerializable >
typedef iser::ISerializable BaseClass
Public Types inherited from istd::IChangeable
enum ChangeFlags {
CF_ACF_INTERNAL = 1 << 0, CF_MODEL = 1 << 1, CF_ABORTED = 1 << 2, CF_DELEGATED = 1 << 3,
CF_NO_UNDO = 1 << 5
}
enum SupportedOperations {
SO_NONE = 0, SO_OBSERVE = 1, SO_COPY = 2, SO_CLONE = 4,
SO_COMPARE = 8
}
Flags for supported operations.
enum CompatibilityMode { CM_STRICT, CM_WITHOUT_REFS, CM_WITH_REFS, CM_CONVERT }
Control how relationship betweeen objects are interpreted.
Public Types inherited from imath::TIMathFunction< Argument, Result >
typedef Argument ArgumentType
typedef Result ResultType
Public Member Functions
void Reset ()
Removes all fulcrum points.
FulcrumSizes GetGridSize () const
Return complete grid size.
int GetDimensionsCount () const
Get number of dimensions.
virtual bool SetDimensionsCount (int count)
Set number of dimensions.
int GetLayersCount (int dimension) const
Get number of fulcrum points used in this function.
virtual void SetLayersCount (int dimension, int count)
Set number of fulcrum layers at specified dimension.
double GetLayerPosition (int dimension, int layerIndex) const
Get position of specified layer of fulcrums.
virtual void SetLayerPosition (int dimension, int layerIndex, double position)
Set position of specified layer of fulcrums.
void GetFulcrumPosition (const FulcrumIndex &index, ArgumentType &result) const
Get position of node at specified grid index.
const FulcrumType & GetFulcrumAtIndex (const FulcrumIndex &index) const
Get value at specified index.
virtual void SetFulcrumAtIndex (const FulcrumIndex &index, const FulcrumType &value)
Set single fulcrum point.
int InsertLayer (int dimension, double position)
Inserts single fulcrum layer.
virtual void RemoveLayer (int dimension, int layerIndex)
Remove fulcrums at spacified layer.
virtual bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
Public Member Functions inherited from istd::TCachedUpdateManagerWrap< iser::ISerializable >
TCachedUpdateManagerWrap ()
Public Member Functions inherited from istd::TUpdateManagerWrap< iser::ISerializable >
TUpdateManagerWrap ()
virtual void BeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
virtual void EndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Public Member Functions inherited from iser::ISerializable
virtual quint32 GetMinimalVersion (int versionId) const
Get minimal needed version to correct storing of this data.
Public Member Functions inherited from istd::IChangeable
virtual int GetSupportedOperations () const
Get set of flags for supported operations.
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Copy this object from another one.
virtual bool IsEqual (const IChangeable &object) const
Compare this object with another object.
virtual IChangeable * CloneMe (CompatibilityMode mode=CM_WITHOUT_REFS) const
Make a copy of this object.
virtual bool ResetData (CompatibilityMode mode=CM_WITHOUT_REFS)
Reset data to its default state.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Public Member Functions inherited from imath::TIMathFunction< Argument, Result >
virtual bool GetValueAt (const Argument &argument, Result &result) const =0
Get function value for specified argument value.
virtual Result GetValueAt (const Argument &argument) const =0
Get function value for specified argument value.
Protected Member Functions
virtual void SortFulcrums ()
Sort fulcrums in this collection.
int FindLayerIndex (int dimension, double value) const
Find layer index of specified value for specified dimension.
Fulcrums::IndexType FindIndices (const ArgumentType &argument) const
Find indices of cuboid containing specified argument value.
virtual bool CalculateCache (int changeFlags)
Calculate cache.
Protected Member Functions inherited from istd::TCachedUpdateManagerWrap< iser::ISerializable >
bool EnsureCacheValid () const
Ensures cache is valid.
void InvalidateCache (int changeFlags=0)
Make cache invalid.
void SetCacheValid ()
Say that cache is valid.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Protected Member Functions inherited from istd::IChangeable
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for begin change event.
Detailed Description
template<class Argument, class Result, class Fulcrums>
class imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >
Base class for interpolated functions based on fulcrums in multi-dimesional grid.
This grid may be imagined as set of parallel layers for each dimension. Number of this layers and their position can be individually controlled. Plese note, that method SetDimensionsCount must be called manually to initialize number of input dimensions also for fixed-size arguments.
Parameters
Argument function argument type.
Result function result type.
Fulcrums array type used to stored fulcrums. It muss define following public typedefs
ElementType type of element stored in this array,
IndexType type of index used to address elements,
SizesType type using to represent array size. This type muss define public typedef IndexType.
Definition at line 36 of file TFulcrumGridFunctionBase.h.
Member Typedef Documentation
template<class Argument, class Result, class Fulcrums> typedef TIMathFunction<Argument, Result>::ArgumentType imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::ArgumentType
Definition at line 47 of file TFulcrumGridFunctionBase.h.
template<class Argument, class Result, class Fulcrums> typedef istd::TCachedUpdateManagerWrap<iser::ISerializable> imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::BaseClass
Definition at line 41 of file TFulcrumGridFunctionBase.h.
template<class Argument, class Result, class Fulcrums> typedef TIMathFunction<Argument, Result> imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::BaseClass2
Definition at line 42 of file TFulcrumGridFunctionBase.h.
template<class Argument, class Result, class Fulcrums> typedef Fulcrums::IndexType imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::FulcrumIndex
Definition at line 45 of file TFulcrumGridFunctionBase.h.
template<class Argument, class Result, class Fulcrums> typedef Fulcrums::SizesType imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::FulcrumSizes
Definition at line 46 of file TFulcrumGridFunctionBase.h.
template<class Argument, class Result, class Fulcrums> typedef Fulcrums::ElementType imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::FulcrumType
Definition at line 44 of file TFulcrumGridFunctionBase.h.
Member Enumeration Documentation
template<class Argument, class Result, class Fulcrums> enum imath::TFulcrumGridFunctionBase::ChangeFlags
Enumerator
CF_SORT_LAYERS
Definition at line 49 of file TFulcrumGridFunctionBase.h.
Member Function Documentation
template<class Argument , class Result , class Fulcrums > bool imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::CalculateCache (int changeFlags) protected virtual
Calculate cache.
It will be called, if cache was not valid and EnsureCacheValid() is called. Default implementation does nothing and is provided to ensure that base class for all derived classes implement this method.
Reimplemented from istd::TCachedUpdateManagerWrap< iser::ISerializable >.
Definition at line 531 of file TFulcrumGridFunctionBase.h.
template<class Argument , class Result , class Fulcrums > Fulcrums::IndexType imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::FindIndices (const ArgumentType & argument) const protected
Find indices of cuboid containing specified argument value.
Definition at line 514 of file TFulcrumGridFunctionBase.h.
template<class Argument , class Result , class Fulcrums > int imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::FindLayerIndex (int dimension, double value) const protected
Find layer index of specified value for specified dimension.
Parameters
dimension specifies dimension should be used.
value argument value.
Returns
biggest layer index, which position is smaller or equal than specified value or -1 if this value is smaller than first layer position.
Definition at line 485 of file TFulcrumGridFunctionBase.h.
template<class Argument , class Result , class Fulcrums > int imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::GetDimensionsCount () const inline
Get number of dimensions.
Definition at line 172 of file TFulcrumGridFunctionBase.h.
template<class Argument , class Result , class Fulcrums > const TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::FulcrumType & imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::GetFulcrumAtIndex (const FulcrumIndex & index) const
Get value at specified index.
Definition at line 278 of file TFulcrumGridFunctionBase.h.
template<class Argument , class Result , class Fulcrums > void imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::GetFulcrumPosition (const FulcrumIndex & index, ArgumentType & result) const
Get position of node at specified grid index.
Definition at line 258 of file TFulcrumGridFunctionBase.h.
template<class Argument , class Result , class Fulcrums > TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::FulcrumSizes imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::GetGridSize () const inline
Return complete grid size.
Definition at line 165 of file TFulcrumGridFunctionBase.h.
template<class Argument , class Result , class Fulcrums > double imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::GetLayerPosition (int dimension, int layerIndex) const inline
Get position of specified layer of fulcrums.
Definition at line 189 of file TFulcrumGridFunctionBase.h.
template<class Argument , class Result , class Fulcrums > int imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::GetLayersCount (int dimension) const inline
Get number of fulcrum points used in this function.
Definition at line 179 of file TFulcrumGridFunctionBase.h.
template<class Argument , class Result , class Fulcrums > int imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::InsertLayer (int dimension, double position)
Inserts single fulcrum layer.
Returns
index of added layer.
Definition at line 294 of file TFulcrumGridFunctionBase.h.
References I_BIG_EPSILON, and I_EPSILON.
template<class Argument , class Result , class Fulcrums > void imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::RemoveLayer (int dimension, int layerIndex) virtual
Remove fulcrums at spacified layer.
Definition at line 365 of file TFulcrumGridFunctionBase.h.
template<class Argument , class Result , class Fulcrums > void imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::Reset ()
Removes all fulcrum points.
Definition at line 206 of file TFulcrumGridFunctionBase.h.
template<class Argument , class Result , class Fulcrums > bool imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::Serialize (iser::IArchive & archive) virtual
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See Also
iser::IArchive
Implements iser::ISerializable.
Definition at line 396 of file TFulcrumGridFunctionBase.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), NULL, and iser::IArchive::Process().
template<class Argument , class Result , class Fulcrums > bool imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::SetDimensionsCount (int count) virtual
Set number of dimensions.
Please note, that depending on used array type for grid representation not all values must be supported.
Returns
true, if number of dimension was set or false otherwise.
Definition at line 217 of file TFulcrumGridFunctionBase.h.
template<class Argument , class Result , class Fulcrums > void imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::SetFulcrumAtIndex (const FulcrumIndex & index, const FulcrumType & value) virtual
Set single fulcrum point.
Definition at line 285 of file TFulcrumGridFunctionBase.h.
template<class Argument , class Result , class Fulcrums > void imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::SetLayerPosition (int dimension, int layerIndex, double position) virtual
Set position of specified layer of fulcrums.
Please note, that layer are sorted by its position during update. If you want to block update mechanism, use istd::TUpdateNotifier.
Definition at line 241 of file TFulcrumGridFunctionBase.h.
template<class Argument , class Result , class Fulcrums > void imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::SetLayersCount (int dimension, int count) virtual
Set number of fulcrum layers at specified dimension.
Please note, that this fulcrum velues will be not valid after this operation.
Definition at line 230 of file TFulcrumGridFunctionBase.h.
template<class Argument , class Result , class Fulcrums > void imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::SortFulcrums () protected virtual
Sort fulcrums in this collection.
Definition at line 474 of file TFulcrumGridFunctionBase.h.
The documentation for this class was generated from the following file:
Include/imath/TFulcrumGridFunctionBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy