ACF: iqtdoc::TQtDocumentManagerWrap< Base, Gui > Class Template Reference
iqtdoc::TQtDocumentManagerWrap< Base, Gui > Class Template Reference
Wrapper for general functionality of a Qt based document workspace.
#include <TQtDocumentManagerWrap.h>
Public Types
typedef Base BaseClass
Public Member Functions
virtual void OnRestoreSettings (const QSettings &settings)
virtual void OnSaveSettings (QSettings &settings) const
virtual int GetAllowedOperationFlags (const istd::IPolymorphic *viewPtr=NULL) const
virtual void FilePrint (int documentIndex=-1) const
virtual istd::CString GetSaveFilePath (const std::string &documentTypeId) const
Protected Member Functions
QString CreateFileDialogFilter (const std::string *documentTypeIdPtr=NULL, int flags=0) const
Creates the filter for the file selection dialog.
void UpdateLastDirectory (const QString &filePath) const
virtual QStringList GetOpenFilePathesFromDialog (const std::string *documentTypeIdPtr) const
Detailed Description
template<class Base, class Gui>
class iqtdoc::TQtDocumentManagerWrap< Base, Gui >
Wrapper for general functionality of a Qt based document workspace.
Definition at line 27 of file TQtDocumentManagerWrap.h.
Member Typedef Documentation
template<class Base, class Gui> typedef Base iqtdoc::TQtDocumentManagerWrap< Base, Gui >::BaseClass
Reimplemented in iqtdoc::CMultiDocumentWorkspaceGuiComp, and iqtdoc::CSingleDocumentWorkspaceGuiComp.
Definition at line 30 of file TQtDocumentManagerWrap.h.
Member Function Documentation
template<class Base , class Gui > QString iqtdoc::TQtDocumentManagerWrap< Base, Gui >::CreateFileDialogFilter (const std::string * documentTypeIdPtr = NULL, int flags = 0) const [inline, protected]
Creates the filter for the file selection dialog.
Parameters:
documentTypeIdPtr optional ID of document type if only filter for single document type should be created.
Definition at line 148 of file TQtDocumentManagerWrap.h.
References iqtgui::CFileDialogLoaderComp::AppendLoaderFilterList(), idoc::IDocumentTemplate::GetDocumentTypeIds(), idoc::IDocumentTemplate::GetFileLoader(), NULL, and iser::IFileTypeInfo::QF_NO_LOADING.
Referenced by iqtdoc::TQtDocumentManagerWrap< Base, Gui >::GetOpenFilePathesFromDialog(), and iqtdoc::TQtDocumentManagerWrap< Base, Gui >::GetSaveFilePath().
template<class Base , class Gui > void iqtdoc::TQtDocumentManagerWrap< Base, Gui >::FilePrint (int documentIndex = -1) const [inline, virtual]
Definition at line 102 of file TQtDocumentManagerWrap.h.
References I_ASSERT, NULL, and iqtdoc::IPrintable::Print().
template<class Base , class Gui > int iqtdoc::TQtDocumentManagerWrap< Base, Gui >::GetAllowedOperationFlags (const istd::IPolymorphic * viewPtr = NULL) const [inline, virtual]
Definition at line 85 of file TQtDocumentManagerWrap.h.
References NULL, and idoc::IDocumentManager::OF_FILE_PRINT.
template<class Base , class Gui > QStringList iqtdoc::TQtDocumentManagerWrap< Base, Gui >::GetOpenFilePathesFromDialog (const std::string * documentTypeIdPtr) const [inline, protected, virtual]
Definition at line 194 of file TQtDocumentManagerWrap.h.
References iqtdoc::TQtDocumentManagerWrap< Base, Gui >::CreateFileDialogFilter(), iser::IFileLoader::QF_FILE_ONLY, and iser::IFileTypeInfo::QF_NO_SAVING.
template<class Base , class Gui > istd::CString iqtdoc::TQtDocumentManagerWrap< Base, Gui >::GetSaveFilePath (const std::string & documentTypeId) const [inline, virtual]
Definition at line 133 of file TQtDocumentManagerWrap.h.
References iqtdoc::TQtDocumentManagerWrap< Base, Gui >::CreateFileDialogFilter(), iqt::GetCString(), NULL, iser::IFileLoader::QF_FILE_ONLY, iser::IFileTypeInfo::QF_NO_LOADING, and iqtdoc::TQtDocumentManagerWrap< Base, Gui >::UpdateLastDirectory().
template<class Base , class Gui > void iqtdoc::TQtDocumentManagerWrap< Base, Gui >::OnRestoreSettings (const QSettings & settings) [inline, virtual]
Reimplemented in iqtdoc::CMultiDocumentWorkspaceGuiComp.
Definition at line 63 of file TQtDocumentManagerWrap.h.
template<class Base , class Gui > void iqtdoc::TQtDocumentManagerWrap< Base, Gui >::OnSaveSettings (QSettings & settings) const [inline, virtual]
Reimplemented in iqtdoc::CMultiDocumentWorkspaceGuiComp.
Definition at line 76 of file TQtDocumentManagerWrap.h.
template<class Base , class Gui > void iqtdoc::TQtDocumentManagerWrap< Base, Gui >::UpdateLastDirectory (const QString & filePath) const [inline, protected]
Definition at line 185 of file TQtDocumentManagerWrap.h.
Referenced by iqtdoc::TQtDocumentManagerWrap< Base, Gui >::GetSaveFilePath().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iqtdoc/TQtDocumentManagerWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy