iview::TLayerBaseEx< Layer, View > Class Template Reference
iview::TLayerBaseEx< Layer, View > Class Template Reference
This is internal class to generate common implementation for diffrent layers implementations.
#include <TLayerBaseEx.h>
Public Types
typedef TLayerBase< Layer, View > BaseClass
Public Member Functions
TLayerBaseEx ()
virtual void SetVisible (bool state)
virtual i2d::CRect GetBoundingBox () const
virtual void OnAreaInvalidated (const i2d::CRect &prevArea, const i2d::CRect &newArea)
Protected Types
typedef ::std::map< IShape
*, i2d::CRect > ShapeMap
typedef ShapeMap::value_type ShapeMapElement
Protected Member Functions
bool OnChangeShapeElement (ShapeMapElement &element)
Internal invalidate shape method.
void DisconnectShapeElement (ShapeMap &map, ShapeMap::iterator iter)
Internal disconnect shape method.
void InvalidateBoundingBox ()
i2d::CRect & GetBoundingBoxRef () const
void SetBoundingBoxValid () const
virtual void CalcBoundingBox (i2d::CRect &result) const =0
Detailed Description
template<class Layer, class View = IShapeView>
class iview::TLayerBaseEx< Layer, View >
This is internal class to generate common implementation for diffrent layers implementations.
Template paramener must be derivate from iview::ILayer interface.
Definition at line 22 of file TLayerBaseEx.h.
Member Typedef Documentation
template<class Layer, class View = IShapeView> typedef TLayerBase<Layer, View> iview::TLayerBaseEx< Layer, View >::BaseClass
Reimplemented from iview::TLayerBase< Layer, View >.
Reimplemented in iview::CSelectableLayerBase, and iview::CLayerBase.
Definition at line 25 of file TLayerBaseEx.h.
template<class Layer, class View = IShapeView> typedef ::std::map<IShape*, i2d::CRect> iview::TLayerBaseEx< Layer, View >::ShapeMap [protected]
Definition at line 37 of file TLayerBaseEx.h.
template<class Layer, class View = IShapeView> typedef ShapeMap::value_type iview::TLayerBaseEx< Layer, View >::ShapeMapElement [protected]
Definition at line 38 of file TLayerBaseEx.h.
Constructor & Destructor Documentation
template<class Layer , class View > iview::TLayerBaseEx< Layer, View >::TLayerBaseEx ()
Definition at line 66 of file TLayerBaseEx.h.
Member Function Documentation
template<class Layer, class View = IShapeView> virtual void iview::TLayerBaseEx< Layer, View >::CalcBoundingBox (i2d::CRect & result) const [protected, pure virtual]
Implemented in iview::CSelectableLayerBase, and iview::CLayerBase.
template<class Layer , class View > void iview::TLayerBaseEx< Layer, View >::DisconnectShapeElement (ShapeMap & map, ShapeMap::iterator iter) [protected]
Internal disconnect shape method.
Definition at line 144 of file TLayerBaseEx.h.
References i2d::CRect::GetEmpty(), and iview::IVisualizable::OnDisconnectDisplay().
template<class Layer , class View > i2d::CRect iview::TLayerBaseEx< Layer, View >::GetBoundingBox () const [virtual]
Definition at line 88 of file TLayerBaseEx.h.
template<class Layer , class View > i2d::CRect & iview::TLayerBaseEx< Layer, View >::GetBoundingBoxRef () const [protected]
Definition at line 166 of file TLayerBaseEx.h.
template<class Layer , class View > void iview::TLayerBaseEx< Layer, View >::InvalidateBoundingBox () [protected]
Definition at line 158 of file TLayerBaseEx.h.
template<class Layer , class View > void iview::TLayerBaseEx< Layer, View >::OnAreaInvalidated (const i2d::CRect & prevArea, const i2d::CRect & newArea) [virtual]
Reimplemented from iview::TLayerBase< Layer, View >.
Definition at line 102 of file TLayerBaseEx.h.
References i2d::CRect::GetBottom(), i2d::CRect::GetLeft(), i2d::CRect::GetRight(), i2d::CRect::GetTop(), I_ASSERT, and i2d::CRect::IsEmpty().
template<class Layer , class View > bool iview::TLayerBaseEx< Layer, View >::OnChangeShapeElement (ShapeMapElement & element) [protected]
Internal invalidate shape method.
Definition at line 128 of file TLayerBaseEx.h.
References I_ASSERT, and NULL.
template<class Layer , class View > void iview::TLayerBaseEx< Layer, View >::SetBoundingBoxValid () const [protected]
Definition at line 174 of file TLayerBaseEx.h.
template<class Layer , class View > void iview::TLayerBaseEx< Layer, View >::SetVisible (bool state) [inline, virtual]
Reimplemented from iview::TLayerBase< Layer, View >.
Definition at line 77 of file TLayerBaseEx.h.
The documentation for this class was generated from the following file:
Include/iview/TLayerBaseEx.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy