i2d::TPolylineExPrimitive< SegmentData > Class Template Reference
i2d::TPolylineExPrimitive< SegmentData > Class Template Reference
#include <TPolylineExPrimitive.h>
Public Types
typedef CPolyline BaseClass
Public Member Functions
virtual const SegmentData & GetSegmentData (int segmentIndex) const
Get segment user data.
virtual void SetSegmentData (int segmentIndex, const SegmentData &data)
Set segment user data.
virtual bool RemoveSegment (int node, int segment)
Remove node and segment.
virtual bool InsertNode (const i2d::CVector2d &node)
Insert a node at the end of node table.
virtual bool InsertNode (int index, const i2d::CVector2d &node)
Insert a node at specified index.
virtual void Clear ()
Removes all nodes.
virtual void SetClosed (bool state=true)
Set polyline to be opened or closed.
virtual bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
Detailed Description
template<class SegmentData>
class i2d::TPolylineExPrimitive< SegmentData >
Definition at line 14 of file TPolylineExPrimitive.h.
Member Typedef Documentation
template<class SegmentData > typedef CPolyline i2d::TPolylineExPrimitive< SegmentData >::BaseClass
Reimplemented from i2d::CPolyline.
Definition at line 17 of file TPolylineExPrimitive.h.
Member Function Documentation
template<class SegmentData > void i2d::TPolylineExPrimitive< SegmentData >::Clear () [inline, virtual]
Removes all nodes.
Reimplemented from i2d::CPolygon.
Definition at line 146 of file TPolylineExPrimitive.h.
template<class SegmentData > const SegmentData & i2d::TPolylineExPrimitive< SegmentData >::GetSegmentData (int segmentIndex) const [inline, virtual]
Get segment user data.
Definition at line 46 of file TPolylineExPrimitive.h.
References I_ASSERT.
template<class SegmentData > bool i2d::TPolylineExPrimitive< SegmentData >::InsertNode (const i2d::CVector2d & node) [inline, virtual]
Insert a node at the end of node table.
Reimplemented from i2d::CPolygon.
Definition at line 83 of file TPolylineExPrimitive.h.
template<class SegmentData > bool i2d::TPolylineExPrimitive< SegmentData >::InsertNode (int index, const i2d::CVector2d & node) [inline, virtual]
Insert a node at specified index.
Reimplemented from i2d::CPolygon.
Definition at line 104 of file TPolylineExPrimitive.h.
template<class SegmentData > bool i2d::TPolylineExPrimitive< SegmentData >::RemoveSegment (int node, int segment) [inline, virtual]
Remove node and segment.
Definition at line 65 of file TPolylineExPrimitive.h.
References I_ASSERT.
template<class SegmentData > bool i2d::TPolylineExPrimitive< SegmentData >::Serialize (iser::IArchive & archive) [inline, virtual]
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See also:
iser::IArchive
Reimplemented from i2d::CPolygon.
Definition at line 177 of file TPolylineExPrimitive.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), and iser::IArchive::Process().
template<class SegmentData > void i2d::TPolylineExPrimitive< SegmentData >::SetClosed (bool state = true) [inline, virtual]
Set polyline to be opened or closed.
Reimplemented from i2d::CPolyline.
Definition at line 157 of file TPolylineExPrimitive.h.
template<class SegmentData > void i2d::TPolylineExPrimitive< SegmentData >::SetSegmentData (int segmentIndex, const SegmentData & data) [inline, virtual]
Set segment user data.
Definition at line 55 of file TPolylineExPrimitive.h.
References I_ASSERT.
The documentation for this class was generated from the following file:
Include/i2d/TPolylineExPrimitive.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy