i2d::CAffine2d Class Reference
i2d::CAffine2d Class Reference
This class defines an affine 2D transformation.
#include <CAffine2d.h>
Public Member Functions
CAffine2d ()
Constructor, parameters will be not initialized.
CAffine2d (const CAffine2d &transform)
Copy constructor, transformation data will be copied from the input object.
CAffine2d (const CMatrix2d &deform, const CVector2d &translation=CVector2d(0.0, 0.0))
Constructs a transform using specified deformation matrix and translation.
CAffine2d (const CVector2d &translation)
Constructs a transform with translation only.
const CVector2d & GetTranslation () const
Get translation part of this affine transformation.
void SetTranslation (const CVector2d &translation)
Set translation part of this affine transformation.
const CMatrix2d & GetDeformMatrix () const
Get rotation, skew and scale part of this affine transformation.
void SetDeformMatrix (const CMatrix2d &deform)
Set rotation, skew and scale part of this affine transformation.
CVector2d & GetTranslationRef ()
Get internal reference to the translation vector.
CMatrix2d & GetDeformMatrixRef ()
Get internal reference to the transformation matrix.
void Reset ()
Set to identity transformation.
void Reset (const CVector2d &translation)
Set this transformation to translation.
void Reset (const CVector2d &translation, double angle, double scale=1.0)
Set this transformation to a given translation, rotation and scaling.
void Reset (const CVector2d &translation, double angle, const CVector2d &scale)
Set this transformation to a given translation, rotation and both axis scaling.
CVector2d GetApply (const CVector2d &position) const
Calculate transformed position.
void GetApply (const CVector2d &position, CVector2d &result) const
Get position after this transformation.
CVector2d GetApplyToDelta (const CVector2d &delta) const
Get difference vector after this transformation.
void GetApplyToDelta (const CVector2d &delta, CVector2d &result) const
Get vector after this transformation.
CAffine2d GetApply (const CAffine2d &transform) const
Get combined transformation.
void GetApply (const CAffine2d &transform, CAffine2d &result) const
Get combined transformation.
void Apply (const CAffine2d &transform)
Combine this transformation with another transformation.
void ApplyLeft (const CAffine2d &transform)
Combine this transformation with another transformation on the left side.
CVector2d GetInvertedApply (const CVector2d &position) const
Inverted operation to GetApply().
bool GetInvertedApply (const CVector2d &position, CVector2d &result) const
Inverted operation to GetApply().
CAffine2d GetTranslated (const CVector2d &delta) const
Get some transformation combined with translation.
void GetTranslated (const CVector2d &delta, CAffine2d &result) const
Get some transformation combined with translation.
void Translate (const CVector2d &delta)
Combine this transformation with translation.
CAffine2d GetInverted () const
Get inverted transformation.
bool GetInverted (CAffine2d &result) const
Get inverted transformation.
bool Serialize (iser::IArchive &archive)
Serialize transformation parameters into/from archive.
bool operator== (const CAffine2d &transform) const
bool operator!= (const CAffine2d &transform) const
CAffine2d & operator= (const CAffine2d &transform)
Static Public Member Functions
static const CAffine2d & GetIdentity ()
Detailed Description
This class defines an affine 2D transformation.
Definition at line 17 of file CAffine2d.h.
Constructor & Destructor Documentation
i2d::CAffine2d::CAffine2d () inline
Constructor, parameters will be not initialized.
Definition at line 201 of file CAffine2d.h.
Referenced by GetTranslated().
i2d::CAffine2d::CAffine2d (const CAffine2d & transform) inline
Copy constructor, transformation data will be copied from the input object.
Definition at line 206 of file CAffine2d.h.
i2d::CAffine2d::CAffine2d (const CMatrix2d & deform, const CVector2d & translation = CVector2d(0.0, 0.0)) explicit
Constructs a transform using specified deformation matrix and translation.
i2d::CAffine2d::CAffine2d (const CVector2d & translation) explicit
Constructs a transform with translation only.
Member Function Documentation
void i2d::CAffine2d::Apply (const CAffine2d & transform)
Combine this transformation with another transformation.
Parameters
transform local transformation used on right side of transformation multiplication.
Referenced by iview::CScreenTransform::Apply().
void i2d::CAffine2d::ApplyLeft (const CAffine2d & transform)
Combine this transformation with another transformation on the left side.
Parameters
transform local transformation used on left side of transformation multiplication.
CVector2d i2d::CAffine2d::GetApply (const CVector2d & position) const inline
Calculate transformed position.
Definition at line 255 of file CAffine2d.h.
References i2d::CMatrix2d::GetMultiplied().
Referenced by iview::CScreenTransform::GetClientPosition().
void i2d::CAffine2d::GetApply (const CVector2d & position, CVector2d & result) const inline
Get position after this transformation.
Definition at line 264 of file CAffine2d.h.
References i2d::CMatrix2d::GetMultiplied().
CAffine2d i2d::CAffine2d::GetApply (const CAffine2d & transform) const
Get combined transformation.
Parameters
transform local transformation used on the right side of transformation multiplication.
Returns
combined transform.
void i2d::CAffine2d::GetApply (const CAffine2d & transform, CAffine2d & result) const
Get combined transformation.
Parameters
transform local transformation used on the right side of transformation multiplication.
Returns
combined transformation, it is equal to thisTranform * parameterTransform.
CVector2d i2d::CAffine2d::GetApplyToDelta (const CVector2d & delta) const inline
Get difference vector after this transformation.
Please note that the translation will be not considered for this transformation.
Definition at line 271 of file CAffine2d.h.
References i2d::CMatrix2d::GetMultiplied().
void i2d::CAffine2d::GetApplyToDelta (const CVector2d & delta, CVector2d & result) const inline
Get vector after this transformation.
Please note that the translation will be not considered for this transformation.
Definition at line 281 of file CAffine2d.h.
References i2d::CMatrix2d::GetMultiplied().
const CMatrix2d & i2d::CAffine2d::GetDeformMatrix () const inline
Get rotation, skew and scale part of this affine transformation.
Definition at line 227 of file CAffine2d.h.
Referenced by i2d::CParallelogram::GetDeformMatrix().
CMatrix2d & i2d::CAffine2d::GetDeformMatrixRef () inline
Get internal reference to the transformation matrix.
Definition at line 247 of file CAffine2d.h.
Referenced by GetTranslated().
const CAffine2d & i2d::CAffine2d::GetIdentity () inline static
Definition at line 342 of file CAffine2d.h.
CAffine2d i2d::CAffine2d::GetInverted () const inline
Get inverted transformation.
Definition at line 316 of file CAffine2d.h.
Referenced by iview::CScreenTransform::CalculateInvert().
bool i2d::CAffine2d::GetInverted (CAffine2d & result) const
Get inverted transformation.
CVector2d i2d::CAffine2d::GetInvertedApply (const CVector2d & position) const inline
Inverted operation to GetApply().
Definition at line 306 of file CAffine2d.h.
bool i2d::CAffine2d::GetInvertedApply (const CVector2d & position, CVector2d & result) const
Inverted operation to GetApply().
CAffine2d i2d::CAffine2d::GetTranslated (const CVector2d & delta) const inline
Get some transformation combined with translation.
Definition at line 287 of file CAffine2d.h.
References CAffine2d().
void i2d::CAffine2d::GetTranslated (const CVector2d & delta, CAffine2d & result) const inline
Get some transformation combined with translation.
Definition at line 293 of file CAffine2d.h.
References GetDeformMatrixRef(), and GetTranslationRef().
const CVector2d & i2d::CAffine2d::GetTranslation () const inline
Get translation part of this affine transformation.
Definition at line 215 of file CAffine2d.h.
CVector2d & i2d::CAffine2d::GetTranslationRef () inline
Get internal reference to the translation vector.
Definition at line 241 of file CAffine2d.h.
Referenced by GetTranslated().
bool i2d::CAffine2d::operator!= (const CAffine2d & transform) const inline
Definition at line 334 of file CAffine2d.h.
CAffine2d& i2d::CAffine2d::operator= (const CAffine2d & transform)
Referenced by iview::CScreenTransform::operator=().
bool i2d::CAffine2d::operator== (const CAffine2d & transform) const inline
Definition at line 328 of file CAffine2d.h.
void i2d::CAffine2d::Reset ()
Set to identity transformation.
Referenced by iview::CScreenTransform::Reset().
void i2d::CAffine2d::Reset (const CVector2d & translation)
Set this transformation to translation.
void i2d::CAffine2d::Reset (const CVector2d & translation, double angle, double scale = 1.0)
Set this transformation to a given translation, rotation and scaling.
void i2d::CAffine2d::Reset (const CVector2d & translation, double angle, const CVector2d & scale)
Set this transformation to a given translation, rotation and both axis scaling.
bool i2d::CAffine2d::Serialize (iser::IArchive & archive)
Serialize transformation parameters into/from archive.
void i2d::CAffine2d::SetDeformMatrix (const CMatrix2d & deform) inline
Set rotation, skew and scale part of this affine transformation.
Definition at line 233 of file CAffine2d.h.
Referenced by i2d::CParallelogram::SetDeformMatrix().
void i2d::CAffine2d::SetTranslation (const CVector2d & translation) inline
Set translation part of this affine transformation.
Definition at line 221 of file CAffine2d.h.
void i2d::CAffine2d::Translate (const CVector2d & delta) inline
Combine this transformation with translation.
Definition at line 300 of file CAffine2d.h.
The documentation for this class was generated from the following file:
Include/i2d/CAffine2d.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy