icomp::TReferenceMember< Interface > Class Template Reference
icomp::TReferenceMember< Interface > Class Template Reference
Pointer to referenced component object.
#include <TReferenceMember.h>
Public Types
typedef TAttributeMember
< CReferenceAttribute > BaseClass
typedef CInterfaceManipBase BaseClass2
typedef Interface InterfaceType
Public Types inherited from icomp::TAttributeMemberBase< CReferenceAttribute >
typedef CReferenceAttribute AttributeType
typedef
CReferenceAttribute::ValueType AttributeValueType
typedef void InterfaceType
Public Member Functions
TReferenceMember ()
void Init (const IComponent *ownerPtr, const IRealAttributeStaticInfo &staticInfo)
bool IsValid () const
Check if this reference can be resolved.
bool EnsureInitialized () const
Ensure that initlization process is closed.
Interface * GetPtr () const
Direct cccess to internal pointer.
Interface * operator-> () const
Access to internal pointer.
Public Member Functions inherited from icomp::TAttributeMemberBase< CReferenceAttribute >
TAttributeMemberBase ()
void Init (const IComponent *ownerPtr, const IRealAttributeStaticInfo &staticInfo)
Initialize this attribute.
bool IsValid () const
Check if this attribute is valid.
const CReferenceAttribute * GetAttributePtr () const
Access to internal attribute pointer.
const AttributeValueType & GetOriginalValue () const
Get value of attribute.
const CReferenceAttribute * operator-> () const
Access to internal attribute pointer.
const AttributeValueType & operator* () const
Get value of attribute.
Protected Member Functions
TReferenceMember (const TReferenceMember &ptr)
Protected Member Functions inherited from icomp::TAttributeMemberBase< CReferenceAttribute >
void SetAttribute (const CReferenceAttribute *attributePtr)
bool InitInternal (const IComponent *ownerPtr, const IRealAttributeStaticInfo &staticInfo, const IComponent **definitionComponentPtr)
Internal initialize of attribute.
Additional Inherited Members
Static Protected Member Functions inherited from icomp::CInterfaceManipBase
template<class Interface >
static Interface * ExtractInterface (IComponent *componentPtr, const QByteArray &subId="")
Extract interface from component.
Static Protected Member Functions inherited from istd::CIdManipBase
static bool SplitId (const QByteArray &complexId, QByteArray &baseId, QByteArray &subId)
Split component ID into separated ID's.
static QByteArray JoinId (const QByteArray &baseId, const QByteArray &subId)
Join base component ID and sub ID into composed component ID.
Detailed Description
template<class Interface>
class icomp::TReferenceMember< Interface >
Pointer to referenced component object.
Don't use direct this class, use macros I_REF and I_ASSIGN instead.
Definition at line 21 of file TReferenceMember.h.
Member Typedef Documentation
template<class Interface> typedef TAttributeMember<CReferenceAttribute> icomp::TReferenceMember< Interface >::BaseClass
Definition at line 26 of file TReferenceMember.h.
template<class Interface> typedef CInterfaceManipBase icomp::TReferenceMember< Interface >::BaseClass2
Definition at line 27 of file TReferenceMember.h.
template<class Interface> typedef Interface icomp::TReferenceMember< Interface >::InterfaceType
Definition at line 28 of file TReferenceMember.h.
Constructor & Destructor Documentation
template<class Interface > icomp::TReferenceMember< Interface >::TReferenceMember ()
Definition at line 70 of file TReferenceMember.h.
template<class Interface > icomp::TReferenceMember< Interface >::TReferenceMember (const TReferenceMember< Interface > & ptr) protected
Definition at line 142 of file TReferenceMember.h.
Member Function Documentation
template<class Interface > bool icomp::TReferenceMember< Interface >::EnsureInitialized () const
Ensure that initlization process is closed.
Do the same as IsValid(), for convinience only (to provide better code clarify).
Definition at line 93 of file TReferenceMember.h.
References icomp::IComponent::GetParentComponent(), icomp::ICompositeComponent::GetSubcomponent(), NULL, and operator*().
template<class Interface > Interface * icomp::TReferenceMember< Interface >::GetPtr () const
Direct cccess to internal pointer.
Definition at line 121 of file TReferenceMember.h.
Referenced by operator*().
template<class Interface > void icomp::TReferenceMember< Interface >::Init (const IComponent * ownerPtr, const IRealAttributeStaticInfo & staticInfo)
Definition at line 77 of file TReferenceMember.h.
References NULL.
template<class Interface > bool icomp::TReferenceMember< Interface >::IsValid () const
Check if this reference can be resolved.
It calls EnsureInitialized().
Definition at line 86 of file TReferenceMember.h.
template<class Interface > Interface * icomp::TReferenceMember< Interface >::operator-> () const
Access to internal pointer.
Definition at line 130 of file TReferenceMember.h.
References NULL.
The documentation for this class was generated from the following file:
Include/icomp/TReferenceMember.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy