iview::CCalibratedViewBase Class Reference
iview::CCalibratedViewBase Class Reference
Abstract base class for all calibrated view.
#include <CCalibratedViewBase.h>
Public Types
typedef CViewBase BaseClass
Public Types inherited from iview::CViewBase
enum ZoomMode {
ZM_RESET, ZM_ZOOM_IN, ZM_ZOOM_OUT, ZM_FIT,
ZM_FIT_COVER, ZM_FIT_UNPROP, ZM_FIT_H, ZM_FIT_V
}
Public Types inherited from iview::IShapeView
typedef IShapeObserver BaseClass
Public Types inherited from iview::ISelectable
enum MousePointerMode {
MPM_NONE, MPM_DEFAULT, MPM_DESELECT, MPM_POINTER,
MPM_WAIT, MPM_CROSS, MPM_HAND, MPM_DRAG,
MPM_SCREEN_MOVE, MPM_LAST = MPM_SCREEN_MOVE
}
Defines possible states of mouse pointer.
enum EditMode { EM_NONE = 0, EM_MOVE = 1, EM_ADD = 2, EM_REMOVE = 3 }
Describes standard edit modes.
typedef QSet< IInteractiveShape * > SelectedShapes
Public Types inherited from iview::ITouchable
enum TouchState {
TS_NONE, TS_INACTIVE, TS_TICKER, TS_DRAGGABLE,
TS_OTHER, TS_LAST = TS_OTHER
}
Enumeration for possible shape touch states.
Public Types inherited from istd::IChangeable
enum ChangeFlags {
CF_ACF_INTERNAL = 1 << 0, CF_MODEL = 1 << 1, CF_ABORTED = 1 << 2, CF_DELEGATED = 1 << 3,
CF_NO_UNDO = 1 << 5
}
enum SupportedOperations {
SO_NONE = 0, SO_OBSERVE = 1, SO_COPY = 2, SO_CLONE = 4,
SO_COMPARE = 8
}
Flags for supported operations.
enum CompatibilityMode { CM_STRICT, CM_WITHOUT_REFS, CM_WITH_REFS, CM_CONVERT }
Control how relationship betweeen objects are interpreted.
Public Member Functions
CCalibratedViewBase ()
void SetDisplayCalibration (const i2d::ICalibration2d *calibrationPtr)
Set calibration using to display logical coordinates.
virtual void SetGridVisible (bool state=true)
Set grid visibility state.
virtual void ConnectCalibrationShape (iview::IShape *shapePtr)
Connect visualisation shape for calibration object.
void SetMinGridDistance (double gridDistance)
Set minimal grid size.
void SetGridInMm (bool state=true)
Set if grid should be shown in milimeter.
const iview::IViewLayer & GetCalibrationLayer () const
void SetDefaultColorSchema (const IColorSchema *colorSchemaPtr, bool releaseFlag=false)
Set default color schema object.
bool IsBackgroundBufferActive () const
void SetBackgroundBufferActive (bool state=true)
bool IsDoubleBufferActive () const
void SetDoubleBufferActive (bool state=true)
const iview::CDrawBuffer & GetBackgroundBuffer () const
iview::CDrawBuffer & GetBackgroundBuffer ()
const iview::CDrawBuffer & GetDoubleBuffer () const
iview::CDrawBuffer & GetDoubleBuffer ()
virtual void OnResize ()
Called if found that display area was resized.
void CheckResize ()
Check if size size was changed and invalidation and OnResize() should be done.
virtual const iview::IColorSchema & GetDefaultColorSchema () const
virtual void UpdateAllShapes (int changeFlag)
Inform all shapes about changes.
virtual void InsertDefaultLayers ()
Insert default layers, when there is no one user layer.
virtual int InsertLayer (iview::IViewLayer *layerPtr, int index=-1, int layerType=IViewLayer::LT_NONE)
Insert layer to view.
virtual void RemoveLayer (int index)
Remove layer from view.
virtual bool IsGridVisible () const
Check if grid is visible.
virtual double GetMinGridDistance () const
Get minimal distance between grid lines.
virtual bool IsGridInMm () const
Check if grid should be shown in milimeter.
virtual const i2d::ICalibration2d * GetCalibration () const
Get access to transformation object, which transforms a local logical coordinate system to global one.
Public Member Functions inherited from iview::CViewBase
CViewBase ()
virtual ~CViewBase ()
virtual void SetZoom (ZoomMode zoom)
Set zoom.
virtual void SetEditMode (int mode)
Set edit mode.
virtual void SetScreenPosition (const i2d::CVector2d &client, istd::CIndex2d screen)
It sets position to become transformation of client point to specified screen position.
virtual const i2d::CRectangle & GetFitArea () const
Get area will be used to automatic fit the zoom to view size.
virtual void SetFitArea (const i2d::CRectangle &area)
Set area will be used to fit in some zoom modes.
virtual void SetViewDraggable (bool state=true)
Turn on/off possibility to move whole view transform.
virtual void SetMultiselectable (bool state=true)
Turn on/off possibility to select more shapes using control keys.
virtual void SetDraggable (bool state=true)
Turn on/off possibility to move more selected shapes, when one is moved.
virtual void AddViewEventObserver (iview::IViewEventObserver *listenerPtr)
Adds handler to catch view events.
virtual void RemoveViewEventObserver (iview::IViewEventObserver *listenerPtr)
Removes handler to catch view events.
int GetBackgroundLayerIndex () const
Get index of default background layer.
int GetInactiveLayerIndex () const
Get index of default inactive layer.
int GetActiveLayerIndex () const
Get index of default active layer.
IInteractiveShape * GetMouseShapePtr () const
Get shape under mouse pointer.
virtual void Update ()
Updates all invalidates shapes.
virtual bool IsViewDraggable () const
Check if is draggable mode.
virtual bool IsMultiselectable () const
Check, if it is possible to select more than one shape.
virtual int GetLayerIndex (const IViewLayer &layer) const
Get index of layer.
virtual int GetLayerIndex (int layerType) const
Get index of layer by type.
virtual int GetLayersCount () const
Get count of layer in this view.
virtual IViewLayer & GetLayer (int index) const
Get layer with the given index.
virtual bool ConnectShape (IShape *shapePtr)
Connect shape object to view.
virtual ISelectableLayer * GetFocusedLayerPtr () const
Get focused layer.
virtual void OnLayerShapeFocused (IInteractiveShape *shapePtr, ISelectableLayer *layerPtr)
Called when shape in layer get focus.
virtual void OnLayerShapeDefocused (IInteractiveShape *shapePtr, ISelectableLayer *layerPtr)
Called when shape in layer loose focus.
virtual void OnLayerInvalidated (const IViewLayer &layer, const i2d::CRect &prevArea, const i2d::CRect &newArea)
Inform that layer was invalidated.
virtual int GetSelectedShapesCount () const
Get count of selected shapes.
virtual void InsertSelectedShapes (SelectedShapes &result) const
Get set of selected shapes.
virtual void DeselectAllShapes ()
Set all shapes to be deselected.
virtual int GetKeysState () const
Get state of system keys.
virtual int GetEditMode () const
Get actual edit mode.
virtual void OnShapeFocused (IInteractiveShape *)
Called when shape get focus.
virtual void OnShapeDefocused (IInteractiveShape *)
Called when shape loose focus.
virtual TouchState IsTouched (istd::CIndex2d position) const
Check, if any shape is touched.
virtual QString GetShapeDescriptionAt (istd::CIndex2d position) const
Get description to shape at specified position.
virtual void SetTransform (const i2d::CAffine2d &transform)
Set a screen transformation.
virtual void UpdateMousePointer ()
Update mouse pointer.
virtual bool OnMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag)
It is called, when mouse button is pushed down or up on this object.
virtual bool OnMouseMove (istd::CIndex2d position)
It is called, when mouse is moved.
virtual IDisplay * GetParentDisplayPtr () const
Get parent object of this display.
virtual const
iview::CScreenTransform & GetTransform () const
Return a screen transformation.
virtual i2d::CRect GetBoundingBox () const
Get bounding box of all object in this display.
virtual const IColorSchema & GetColorSchema () const
Get color schema.
virtual void OnAreaInvalidated (const i2d::CRect &prevArea, const i2d::CRect &newArea)
Invalidate display area.
virtual void OnChangeShape (IShape *shapePtr)
Invalidate a shape.
virtual bool DisconnectShape (IShape *shapePtr)
Disconnect shape object from view.
virtual void OnShapeSelected (IInteractiveShape &shape, bool state=true)
It is called after change shape selection state.
virtual bool IsDraggable () const
Check if drag is enabled.
virtual void BeginDrag (const istd::CIndex2d &reference)
Called before dragging is begin.
virtual void SetDragPosition (const istd::CIndex2d &position)
Set new drag position.
virtual void EndDrag ()
Called after dragging.
Public Member Functions inherited from iview::IDisplay
virtual i2d::CRect GetClientRect () const =0
Get bounding box of client area.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Public Member Functions inherited from istd::IChangeable
virtual void BeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Starts the change transaction.
virtual void EndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Ends the change transaction.
virtual int GetSupportedOperations () const
Get set of flags for supported operations.
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Copy this object from another one.
virtual bool IsEqual (const IChangeable &object) const
Compare this object with another object.
virtual IChangeable * CloneMe (CompatibilityMode mode=CM_WITHOUT_REFS) const
Make a copy of this object.
virtual bool ResetData (CompatibilityMode mode=CM_WITHOUT_REFS)
Reset data to its default state.
Protected Member Functions
virtual void DrawBuffers (QPaintDevice &nativeContext, const i2d::CRect &clipRect)
virtual void DrawToContext (QPaintDevice &nativeContext, QPainter &context, const i2d::CRect &invalidatedBox)
Protected Member Functions inherited from iview::CViewBase
virtual void DrawLayers (QPainter &drawContext, int firstLayer, int lastLayer)
Draw Background layer.
int GetLastBackgroundLayerIndex ()
Get last background layer index.
void SetLastBackgroundLayerIndex (int index)
virtual bool CanBeMoved () const
This method is internal used to check, if drag mode is allowed.
void DisconnectAllShapes ()
Disconnect all shapes from this view.
virtual void InvalidateBackground ()
Invalidate whole backgroud buffer.
virtual void InvalidateBoundingBox ()
Invalidate bounding box.
virtual i2d::CRect CalcBoundingBox () const
Calculate bounding box of all shapes.
virtual MousePointerMode CalcMousePointer (istd::CIndex2d position) const
virtual void InvalidateMouseShape ()
Invalidate stored shape under mouse pointer.
virtual void CalcMouseShape () const
Calc shape under mouse pointer.
virtual bool IsBackgroundBufferValid () const
Check if background buffer is valid.
virtual void SetBackgroundBufferValid (bool state=true)
Set validate flag of background buffer.
const i2d::CRect & GetInvalidatedBox () const
Get bounding box of all invalidated rectangles.
void InvalidateBox (const i2d::CRect &rect)
Invalidate rectangle screen area.
void ResetInvalidatedBox ()
Reset invalidated box.
void SetKeysState (int state)
Set state of keys.
const Layers & GetLayers () const
Layers & GetLayers ()
virtual void SetMousePointer (MousePointerMode mode)=0
Set mouse pointer.
virtual void UpdateRectArea (const i2d::CRect &rect)=0
Start updating specified rectangle area.
Protected Member Functions inherited from istd::IChangeable
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for begin change event.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for end change event.
Additional Inherited Members
Protected Types inherited from iview::CViewBase
typedef QVector< IViewLayer * > Layers
Detailed Description
Abstract base class for all calibrated view.
Calibrated view implements i2d::ICalibrationProvider interface, and can automatically show calibration grid if supported.
Definition at line 27 of file CCalibratedViewBase.h.
Member Typedef Documentation
typedef CViewBase iview::CCalibratedViewBase::BaseClass
Definition at line 33 of file CCalibratedViewBase.h.
Constructor & Destructor Documentation
iview::CCalibratedViewBase::CCalibratedViewBase ()
Member Function Documentation
void iview::CCalibratedViewBase::CheckResize ()
Check if size size was changed and invalidation and OnResize() should be done.
virtual void iview::CCalibratedViewBase::ConnectCalibrationShape (iview::IShape * shapePtr) virtual
Connect visualisation shape for calibration object.
Reimplemented in iview::CViewport.
virtual void iview::CCalibratedViewBase::DrawBuffers (QPaintDevice & nativeContext, const i2d::CRect & clipRect) protected virtual
virtual void iview::CCalibratedViewBase::DrawToContext (QPaintDevice & nativeContext, QPainter & context, const i2d::CRect & invalidatedBox) protected virtual
const iview::CDrawBuffer& iview::CCalibratedViewBase::GetBackgroundBuffer () const
iview::CDrawBuffer& iview::CCalibratedViewBase::GetBackgroundBuffer ()
const i2d::ICalibration2d * iview::CCalibratedViewBase::GetCalibration () const inline virtual
Get access to transformation object, which transforms a local logical coordinate system to global one.
Returns
Pointer to transformation if it is accessible, or NULL.
Implements i2d::ICalibrationProvider.
Definition at line 195 of file CCalibratedViewBase.h.
const iview::IViewLayer & iview::CCalibratedViewBase::GetCalibrationLayer () const inline
Definition at line 169 of file CCalibratedViewBase.h.
virtual const iview::IColorSchema& iview::CCalibratedViewBase::GetDefaultColorSchema () const virtual
Implements iview::CViewBase.
const iview::CDrawBuffer& iview::CCalibratedViewBase::GetDoubleBuffer () const
iview::CDrawBuffer& iview::CCalibratedViewBase::GetDoubleBuffer ()
double iview::CCalibratedViewBase::GetMinGridDistance () const inline virtual
Get minimal distance between grid lines.
Implements iview::IVisualCalibrationInfo.
Definition at line 181 of file CCalibratedViewBase.h.
virtual void iview::CCalibratedViewBase::InsertDefaultLayers () virtual
Insert default layers, when there is no one user layer.
Reimplemented from iview::CViewBase.
virtual int iview::CCalibratedViewBase::InsertLayer (iview::IViewLayer * layerPtr, int index = -1, int layerType = IViewLayer::LT_NONE) virtual
Insert layer to view.
Parameters
layerPtr pointer to inserted layer.
index index of inserted layer. If equals -1, layer will be inserted after last existing layer.
layerType used to set standard layers.
See Also
iview::IShapeView::LayerType
Returns
index of this layer.
Reimplemented from iview::CViewBase.
bool iview::CCalibratedViewBase::IsBackgroundBufferActive () const
bool iview::CCalibratedViewBase::IsDoubleBufferActive () const
bool iview::CCalibratedViewBase::IsGridInMm () const inline virtual
Check if grid should be shown in milimeter.
Implements iview::IVisualCalibrationInfo.
Definition at line 187 of file CCalibratedViewBase.h.
bool iview::CCalibratedViewBase::IsGridVisible () const inline virtual
Check if grid is visible.
Implements iview::IVisualCalibrationInfo.
Definition at line 175 of file CCalibratedViewBase.h.
virtual void iview::CCalibratedViewBase::OnResize () virtual
Called if found that display area was resized.
Reimplemented in iview::CViewport.
virtual void iview::CCalibratedViewBase::RemoveLayer (int index) virtual
Remove layer from view.
Reimplemented from iview::CViewBase.
void iview::CCalibratedViewBase::SetBackgroundBufferActive (bool state = true)
void iview::CCalibratedViewBase::SetDefaultColorSchema (const IColorSchema * colorSchemaPtr, bool releaseFlag = false)
Set default color schema object.
Parameters
colorSchemaPtr pointer to color schema object.
releaseFlag if its true, object will be automatically removed.
void iview::CCalibratedViewBase::SetDisplayCalibration (const i2d::ICalibration2d * calibrationPtr)
Set calibration using to display logical coordinates.
void iview::CCalibratedViewBase::SetDoubleBufferActive (bool state = true)
void iview::CCalibratedViewBase::SetGridInMm (bool state = true) inline
Set if grid should be shown in milimeter.
Definition at line 160 of file CCalibratedViewBase.h.
References iview::CViewBase::SetBackgroundBufferValid().
void iview::CCalibratedViewBase::SetGridVisible (bool state = true) inline virtual
Set grid visibility state.
Definition at line 140 of file CCalibratedViewBase.h.
References iview::CViewBase::InvalidateBackground().
void iview::CCalibratedViewBase::SetMinGridDistance (double gridDistance) inline
Set minimal grid size.
It determines minimal distance between grid lines.
Definition at line 149 of file CCalibratedViewBase.h.
References iview::CViewBase::SetBackgroundBufferValid().
virtual void iview::CCalibratedViewBase::UpdateAllShapes (int changeFlag) virtual
Inform all shapes about changes.
Reimplemented from iview::CViewBase.
The documentation for this class was generated from the following file:
Include/iview/CCalibratedViewBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy