ACF: iimg::TBitmapIterator2d< PixelType > Class Template Reference
iimg::TBitmapIterator2d< PixelType > Class Template Reference
Help class for iteration through bitmap pixels.
#include <TBitmapIterator2d.h>
Classes
class XIterator
Implementation of an sub-iterator in x-direction.
class YIterator
Implementation of an sub-iterator in y-direction.
Public Types
typedef PixelType ValueType
Public Member Functions
TBitmapIterator2d (const iimg::IBitmap *bitmapPtr)
Construct image iterator from a bitmap.
TBitmapIterator2d (const TBitmapIterator2d &iterator)
Construct image iterator from another interator.
ValueType & operator* () const
Access operator.
bool operator< (const TBitmapIterator2d &iterator)
bool operator> (const TBitmapIterator2d &iterator)
bool operator== (const TBitmapIterator2d &iterator)
bool IsValid () const
Returns true if the index is valid in the image domain.
void MoveTo (int x, int y)
Move iterator to the position (x, y).
void MoveTo (const istd::CIndex2d &index)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Public Attributes
XIterator x
YIterator y
Detailed Description
template<typename PixelType>
class iimg::TBitmapIterator2d< PixelType >
Help class for iteration through bitmap pixels.
Definition at line 16 of file TBitmapIterator2d.h.
Member Typedef Documentation
template<typename PixelType> typedef PixelType iimg::TBitmapIterator2d< PixelType >::ValueType
Definition at line 19 of file TBitmapIterator2d.h.
Constructor & Destructor Documentation
template<typename PixelType > iimg::TBitmapIterator2d< PixelType >::TBitmapIterator2d (const iimg::IBitmap * bitmapPtr) [inline]
Construct image iterator from a bitmap.
Definition at line 108 of file TBitmapIterator2d.h.
References iimg::IRasterImage::GetImageSize(), iimg::IBitmap::GetLinePtr(), iimg::IBitmap::GetLinesDifference(), istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), I_ASSERT, and NULL.
template<typename PixelType > iimg::TBitmapIterator2d< PixelType >::TBitmapIterator2d (const TBitmapIterator2d< PixelType > & iterator) [inline]
Construct image iterator from another interator.
Definition at line 126 of file TBitmapIterator2d.h.
Member Function Documentation
template<typename PixelType > bool iimg::TBitmapIterator2d< PixelType >::IsValid () const [inline]
Returns true if the index is valid in the image domain.
Definition at line 148 of file TBitmapIterator2d.h.
Referenced by iimg::TBitmapIterator2d< PixelType >::operator*().
template<typename PixelType > void iimg::TBitmapIterator2d< PixelType >::MoveTo (const istd::CIndex2d & index) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 163 of file TBitmapIterator2d.h.
References istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), and iimg::TBitmapIterator2d< PixelType >::MoveTo().
template<typename PixelType > void iimg::TBitmapIterator2d< PixelType >::MoveTo (int x, int y) [inline]
Move iterator to the position (x, y).
Definition at line 156 of file TBitmapIterator2d.h.
Referenced by iimg::TBitmapIterator2d< PixelType >::MoveTo().
template<typename PixelType > TBitmapIterator2d< PixelType >::ValueType & iimg::TBitmapIterator2d< PixelType >::operator* () const [inline]
Access operator.
Definition at line 139 of file TBitmapIterator2d.h.
References I_ASSERT, and iimg::TBitmapIterator2d< PixelType >::IsValid().
template<typename PixelType > bool iimg::TBitmapIterator2d< PixelType >::operator< (const TBitmapIterator2d< PixelType > & iterator) [inline]
Definition at line 170 of file TBitmapIterator2d.h.
References I_ASSERT.
template<typename PixelType > bool iimg::TBitmapIterator2d< PixelType >::operator== (const TBitmapIterator2d< PixelType > & iterator) [inline]
Definition at line 188 of file TBitmapIterator2d.h.
References I_ASSERT.
template<typename PixelType > bool iimg::TBitmapIterator2d< PixelType >::operator> (const TBitmapIterator2d< PixelType > & iterator) [inline]
Definition at line 179 of file TBitmapIterator2d.h.
References I_ASSERT.
Member Data Documentation
template<typename PixelType> XIterator iimg::TBitmapIterator2d< PixelType >::x
Definition at line 94 of file TBitmapIterator2d.h.
template<typename PixelType> YIterator iimg::TBitmapIterator2d< PixelType >::y
Definition at line 95 of file TBitmapIterator2d.h.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iimg/TBitmapIterator2d.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy