ACF: imath::CFixedPointManip Class Reference
imath::CFixedPointManip Class Reference
Implementation of imath::IDoubleManip interface for fixed point arithmentic.
#include <CFixedPointManip.h>
Public Types
enum RoundingType { RT_NORMAL, RT_FLOOR, RT_CEIL, RT_LAST = RT_CEIL + 1 }
typedef CDoubleManip BaseClass
Public Member Functions
CFixedPointManip (int precision=1, RoundingType roundingType=RT_NORMAL)
int GetPrecision () const
Get fixed point precision.
void SetPrecision (int precision)
Set fixed point precision.
RoundingType GetRoundingType () const
Get type of rounding.
void SetRoundingType (RoundingType roundingType)
Set type of rounding.
virtual double GetRounded (const double &value) const
Get the nearest value rounded used this arithmetik.
virtual bool IsEqual (const double &value1, const double &value2) const
Compare two values and check, if there are equal.
virtual bool IsSmaller (const double &value1, const double &value2) const
Compare two values and check, if first one is smaller as the second.
virtual bool IsSmallerEqual (const double &value1, const double &value2) const
Compare two values and check, if first one is smaller or equal as the second.
virtual double GetSmallerValue (const double &value) const
Return biggest value smaller that specified one.
virtual double GetBiggerValue (const double &value) const
Return smallest value bigger that specified one.
virtual std::string GetString (const double &value) const
Get this value as string.
virtual bool GetParsed (const std::string &text, double &result) const
Get value converted from string.
Protected Types
typedef double(* RoundingFuntionPtr)(double value)
Protected Member Functions
virtual I_SDWORD GetInternalValue (double value) const
virtual double GetNormalValue (I_SDWORD intValue) const
std::string GetString (const double &value, int precision) const
Static Protected Member Functions
static double NormalRoundFuntion (double value)
Detailed Description
Implementation of imath::IDoubleManip interface for fixed point arithmentic.
Definition at line 15 of file CFixedPointManip.h.
Member Typedef Documentation
typedef CDoubleManip imath::CFixedPointManip::BaseClass
Reimplemented in imath::CComplexDoubleManip.
Definition at line 18 of file CFixedPointManip.h.
typedef double(* imath::CFixedPointManip::RoundingFuntionPtr)(double value) [protected]
Definition at line 69 of file CFixedPointManip.h.
Member Enumeration Documentation
enum imath::CFixedPointManip::RoundingType
Enumerator:
RT_NORMAL Normal mathematical rounding to the nearest value.
RT_FLOOR Rounding down.
RT_CEIL Rounding up.
RT_LAST
Definition at line 20 of file CFixedPointManip.h.
Constructor & Destructor Documentation
imath::CFixedPointManip::CFixedPointManip (int precision = 1, RoundingType roundingType = RT_NORMAL)
Member Function Documentation
double imath::CFixedPointManip::GetBiggerValue (const double & value) const [inline, virtual]
Return smallest value bigger that specified one.
Reimplemented from imath::CDoubleManip.
Definition at line 134 of file CFixedPointManip.h.
References GetInternalValue(), and GetNormalValue().
I_SDWORD imath::CFixedPointManip::GetInternalValue (double value) const [inline, protected, virtual]
Reimplemented in imath::CComplexDoubleManip.
Definition at line 142 of file CFixedPointManip.h.
Referenced by GetBiggerValue(), GetRounded(), GetSmallerValue(), IsEqual(), IsSmaller(), and IsSmallerEqual().
double imath::CFixedPointManip::GetNormalValue (I_SDWORD intValue) const [inline, protected, virtual]
Definition at line 150 of file CFixedPointManip.h.
Referenced by GetBiggerValue(), GetRounded(), and GetSmallerValue().
virtual bool imath::CFixedPointManip::GetParsed (const std::string & text, double & result) const [virtual]
Get value converted from string.
Parameters:
text input string.
result result value.
Returns:
true if success.
Reimplemented from imath::CDoubleManip.
Reimplemented in imath::CComplexDoubleManip.
int imath::CFixedPointManip::GetPrecision () const [inline]
Get fixed point precision.
Please note, that also negative values are allowed.
Definition at line 90 of file CFixedPointManip.h.
Referenced by imath::CComplexDoubleManip::SetPrecision(), and imath::CComplexDoubleManip::SetScaleFactor().
double imath::CFixedPointManip::GetRounded (const double & value) const [inline, virtual]
Get the nearest value rounded used this arithmetik.
Reimplemented from imath::CDoubleManip.
Definition at line 104 of file CFixedPointManip.h.
References GetInternalValue(), and GetNormalValue().
CFixedPointManip::RoundingType imath::CFixedPointManip::GetRoundingType () const [inline]
Get type of rounding.
Definition at line 96 of file CFixedPointManip.h.
double imath::CFixedPointManip::GetSmallerValue (const double & value) const [inline, virtual]
Return biggest value smaller that specified one.
Reimplemented from imath::CDoubleManip.
Definition at line 128 of file CFixedPointManip.h.
References GetInternalValue(), and GetNormalValue().
std::string imath::CFixedPointManip::GetString (const double & value, int precision) const [protected]
virtual std::string imath::CFixedPointManip::GetString (const double & value) const [virtual]
Get this value as string.
Parameters:
value value will be converted.
Reimplemented from imath::CDoubleManip.
Reimplemented in imath::CComplexDoubleManip.
bool imath::CFixedPointManip::IsEqual (const double & value1, const double & value2) const [inline, virtual]
Compare two values and check, if there are equal.
Parameters:
value1 first value.
value2 second value.
Reimplemented from imath::CDoubleManip.
Definition at line 110 of file CFixedPointManip.h.
References GetInternalValue().
bool imath::CFixedPointManip::IsSmaller (const double & value1, const double & value2) const [inline, virtual]
Compare two values and check, if first one is smaller as the second.
Parameters:
value1 first value.
value2 second value.
Reimplemented from imath::CDoubleManip.
Definition at line 116 of file CFixedPointManip.h.
References GetInternalValue().
bool imath::CFixedPointManip::IsSmallerEqual (const double & value1, const double & value2) const [inline, virtual]
Compare two values and check, if first one is smaller or equal as the second.
Parameters:
value1 first value.
value2 second value.
Reimplemented from imath::CDoubleManip.
Definition at line 122 of file CFixedPointManip.h.
References GetInternalValue().
static double imath::CFixedPointManip::NormalRoundFuntion (double value) [static, protected]
void imath::CFixedPointManip::SetPrecision (int precision)
Set fixed point precision.
Reimplemented in imath::CComplexDoubleManip.
Referenced by imath::CComplexDoubleManip::SetPrecision().
void imath::CFixedPointManip::SetRoundingType (RoundingType roundingType)
Set type of rounding.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/imath/CFixedPointManip.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy