idoc::TMultiPageDocumentWrap< Base > Class Template Reference
idoc::TMultiPageDocumentWrap< Base > Class Template Reference
Generic implementation of IMultiPageDocument interface.
#include <TMultiPageDocumentWrap.h>
Classes
struct Page
Public Types
typedef Base BaseClass
typedef CStandardDocumentMetaInfo BaseClass2
Public Types inherited from idoc::IDocumentMetaInfo
enum ChangeFlags { CF_METAINFO = 1 << 21 }
enum MetaInfoType {
MIT_TITLE, MIT_AUTHOR, MIT_CREATOR, MIT_DESCRIPTION,
MIT_CREATION_TIME, MIT_MODIFICATION_TIME, MIT_USER = 1024
}
typedef QSet< int > MetaInfoTypes
Public Types inherited from istd::IChangeable
enum ChangeFlags {
CF_ACF_INTERNAL = 1 << 0, CF_MODEL = 1 << 1, CF_ABORTED = 1 << 2, CF_DELEGATED = 1 << 3,
CF_NO_UNDO = 1 << 5
}
enum SupportedOperations {
SO_NONE = 0, SO_OBSERVE = 1, SO_COPY = 2, SO_CLONE = 4,
SO_COMPARE = 8
}
Flags for supported operations.
enum CompatibilityMode { CM_STRICT, CM_WITHOUT_REFS, CM_WITH_REFS, CM_CONVERT }
Control how relationship betweeen objects are interpreted.
Public Types inherited from iprm::IOptionsList
enum ChangeFlags { CF_OPTIONS_CHANGED = 1 << 18, CF_OPTION_RENAMED = 1 << 19 }
Flags for changes related to this interface.
enum OptionsFlags { SCF_NONE = 0, SCF_SUPPORT_UNIQUE_ID = 256, SFC_DISABLE_ALLOWED = 32 }
Flags for control constraints behavior.
Public Member Functions
virtual int GetPagesCount () const
virtual const istd::IChangeable & GetDocumentPage (int pageIndex) const
virtual const
idoc::IDocumentMetaInfo * GetPageMetaInfo (int pageIndex) const
virtual void ResetPages ()
virtual bool RemovePage (int pageIndex)
virtual const IDocumentMetaInfo & GetDocumentMetaInfo () const
virtual int GetOptionsFlags () const
Get constraints flags.
virtual int GetOptionsCount () const
Get number of managed options.
virtual QString GetOptionName (int index) const
Get name of specified option.
virtual QString GetOptionDescription (int index) const
Get human readable description for a option with the index index.
virtual QByteArray GetOptionId (int index) const
Get option ID.
virtual bool IsOptionEnabled (int index) const
Return true if the option is enabled and can be selected.
virtual bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
virtual bool CopyFrom (const istd::IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Copy this object from another one.
Public Member Functions inherited from idoc::CStandardDocumentMetaInfo
virtual MetaInfoTypes GetSupportedMetaInfoTypes (bool allowReadOnly=true) const
Get list of supported meta info types.
virtual QVariant GetMetaInfo (int metaInfoType) const
Get document's meta info.
virtual bool SetMetaInfo (int metaInfoType, const QVariant &metaInfo)
Set new document's meta information for a given meta type.
virtual QString GetMetaInfoName (int metaInfoType) const
Get a human readable name for a given meta information type.
virtual QString GetMetaInfoDescription (int metaInfoType) const
Get a human readable description for a given meta information type.
virtual bool IsMetaInfoWritable (int metaInfoType) const
Check if meta information can be changed.
virtual bool IsEqual (const IChangeable &object) const
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Public Member Functions inherited from istd::IChangeable
virtual void BeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Starts the change transaction.
virtual void EndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Ends the change transaction.
virtual int GetSupportedOperations () const
Get set of flags for supported operations.
virtual bool IsEqual (const IChangeable &object) const
Compare this object with another object.
virtual IChangeable * CloneMe (CompatibilityMode mode=CM_WITHOUT_REFS) const
Make a copy of this object.
virtual bool ResetData (CompatibilityMode mode=CM_WITHOUT_REFS)
Reset data to its default state.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Public Member Functions inherited from iser::ISerializable
virtual quint32 GetMinimalVersion (int versionId) const
Get minimal needed version to correct storing of this data.
Protected Types
typedef QVector< Page > Pages
Protected Member Functions
virtual bool SerializePage (iser::IArchive &archive, Page &pageItem)
Serialize a single page item into or from the archive.
Protected Member Functions inherited from istd::IChangeable
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for begin change event.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for end change event.
Protected Attributes
Pages m_documentPages
Detailed Description
template<class Base>
class idoc::TMultiPageDocumentWrap< Base >
Generic implementation of IMultiPageDocument interface.
Definition at line 26 of file TMultiPageDocumentWrap.h.
Member Typedef Documentation
template<class Base> typedef Base idoc::TMultiPageDocumentWrap< Base >::BaseClass
Definition at line 32 of file TMultiPageDocumentWrap.h.
template<class Base> typedef CStandardDocumentMetaInfo idoc::TMultiPageDocumentWrap< Base >::BaseClass2
Definition at line 33 of file TMultiPageDocumentWrap.h.
template<class Base> typedef QVector<Page> idoc::TMultiPageDocumentWrap< Base >::Pages protected
Definition at line 71 of file TMultiPageDocumentWrap.h.
Member Function Documentation
template<class Base > bool idoc::TMultiPageDocumentWrap< Base >::CopyFrom (const istd::IChangeable & object, CompatibilityMode mode = CM_WITHOUT_REFS) virtual
Copy this object from another one.
Default implementation in istd::IChangeable does nothing.
Reimplemented from istd::IChangeable.
Definition at line 234 of file TMultiPageDocumentWrap.h.
References istd::IChangeable::CopyFrom(), idoc::TMultiPageDocumentWrap< Base >::m_documentPages, and NULL.
template<class Base > const IDocumentMetaInfo & idoc::TMultiPageDocumentWrap< Base >::GetDocumentMetaInfo () const virtual
Definition at line 133 of file TMultiPageDocumentWrap.h.
template<class Base > const istd::IChangeable & idoc::TMultiPageDocumentWrap< Base >::GetDocumentPage (int pageIndex) const virtual
Definition at line 89 of file TMultiPageDocumentWrap.h.
template<class Base > QString idoc::TMultiPageDocumentWrap< Base >::GetOptionDescription (int index) const virtual
Get human readable description for a option with the index index.
Implements iprm::IOptionsList.
Definition at line 166 of file TMultiPageDocumentWrap.h.
template<class Base > QByteArray idoc::TMultiPageDocumentWrap< Base >::GetOptionId (int index) const virtual
Get option ID.
The option ID must be unique, if flag SCF_SUPPORT_UNIQUE_ID is set.
See Also
OptionsFlags
Implements iprm::IOptionsList.
Definition at line 173 of file TMultiPageDocumentWrap.h.
template<class Base > QString idoc::TMultiPageDocumentWrap< Base >::GetOptionName (int index) const virtual
Get name of specified option.
Implements iprm::IOptionsList.
Definition at line 156 of file TMultiPageDocumentWrap.h.
References idoc::IDocumentMetaInfo::MIT_TITLE.
template<class Base > int idoc::TMultiPageDocumentWrap< Base >::GetOptionsCount () const virtual
Get number of managed options.
Implements iprm::IOptionsList.
Definition at line 149 of file TMultiPageDocumentWrap.h.
template<class Base > int idoc::TMultiPageDocumentWrap< Base >::GetOptionsFlags () const virtual
Get constraints flags.
The flags describes how the constraints object mantainance
Implements iprm::IOptionsList.
Definition at line 142 of file TMultiPageDocumentWrap.h.
template<class Base > const idoc::IDocumentMetaInfo * idoc::TMultiPageDocumentWrap< Base >::GetPageMetaInfo (int pageIndex) const virtual
Definition at line 100 of file TMultiPageDocumentWrap.h.
template<class Base > int idoc::TMultiPageDocumentWrap< Base >::GetPagesCount () const virtual
Definition at line 82 of file TMultiPageDocumentWrap.h.
template<class Base > bool idoc::TMultiPageDocumentWrap< Base >::IsOptionEnabled (int index) const virtual
Return true if the option is enabled and can be selected.
Implements iprm::IOptionsList.
Definition at line 180 of file TMultiPageDocumentWrap.h.
template<class Base > bool idoc::TMultiPageDocumentWrap< Base >::RemovePage (int pageIndex) virtual
Definition at line 119 of file TMultiPageDocumentWrap.h.
template<class Base > void idoc::TMultiPageDocumentWrap< Base >::ResetPages () virtual
Definition at line 110 of file TMultiPageDocumentWrap.h.
template<class Base > bool idoc::TMultiPageDocumentWrap< Base >::Serialize (iser::IArchive & archive) virtual
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See Also
iser::IArchive
Reimplemented from idoc::CStandardDocumentMetaInfo.
Definition at line 189 of file TMultiPageDocumentWrap.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), and NULL.
template<class Base > bool idoc::TMultiPageDocumentWrap< Base >::SerializePage (iser::IArchive & archive, Page & pageItem) protected virtual
Serialize a single page item into or from the archive.
Definition at line 274 of file TMultiPageDocumentWrap.h.
References iser::IArchive::BeginTag(), iser::IArchive::EndTag(), istd::TTransPtr< Type >::GetPtr(), NULL, idoc::TMultiPageDocumentWrap< Base >::Page::pageMetaInfo, idoc::TMultiPageDocumentWrap< Base >::Page::pagePtr, iser::ISerializable::Serialize(), and idoc::CStandardDocumentMetaInfo::Serialize().
Member Data Documentation
template<class Base> Pages idoc::TMultiPageDocumentWrap< Base >::m_documentPages protected
Definition at line 73 of file TMultiPageDocumentWrap.h.
Referenced by idoc::TMultiPageDocumentWrap< Base >::CopyFrom().
The documentation for this class was generated from the following file:
Include/idoc/TMultiPageDocumentWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy