ACF: icomp::CSimComponentContextBase Class Reference
icomp::CSimComponentContextBase Class Reference
#include <CSimComponentContextBase.h>
Public Types
typedef istd::TIFactory
< icomp::IComponent > ComponentsFactory
Public Member Functions
CSimComponentContextBase (const IComponentStaticInfo *infoPtr)
bool SetAttr (const std::string &attributeId, const iser::IObject *attributePtr)
Set named attribute.
bool SetRef (const std::string &referenceId, IComponent *componentPtr)
Set named reference to some component.
bool InsertMultiRef (const std::string &referenceId, IComponent *componentPtr)
Set named reference to some component.
bool SetFactory (const std::string &factoryId, const ComponentsFactory *factoryPtr)
Set factory of component instance.
void SetBoolAttr (const std::string &attributeId, bool value)
Set instance of bool attribute.
void SetIntAttr (const std::string &attributeId, int value)
Set instance of int attribute.
void SetDoubleAttr (const std::string &attributeId, double value)
Set instance of double attribute.
void SetStringAttr (const std::string &attributeId, const istd::CString &value)
Set instance of istd::CString attribute.
template<class Attribute >
bool SetSingleAttr (const std::string &attributeId, const Attribute &attribute)
Set instance of simple attribute.
template<class Attribute >
bool InsertMultiAttr (const std::string &attributeId, const Attribute &attribute)
Insert new attribute to multi attributes.
virtual const IRegistryElement & GetRegistryElement () const
Get access to component registry element object.
virtual const
IComponentStaticInfo & GetStaticInfo () const
Get component static info associated with this context.
virtual const IComponentContext * GetParentContext () const
Get access to parent component context.
virtual const iser::IObject * GetAttribute (const std::string &attributeId, int *definitionLevelPtr=NULL) const
Get attribute using its ID.
Protected Types
typedef std::map< std::string,
IComponent * > ComponentsMap
typedef std::map< std::string,
const ComponentsFactory * > FactoriesMap
Protected Member Functions
template<class AttrType >
bool IsAttributeTypeCorrect (const std::string &attributeId)
Check if attribute type is corrected.
Protected Attributes
ComponentsMap m_componentsMap
FactoriesMap m_factoriesMap
Detailed Description
Definition at line 24 of file CSimComponentContextBase.h.
Member Typedef Documentation
typedef istd::TIFactory<icomp::IComponent> icomp::CSimComponentContextBase::ComponentsFactory
Definition at line 27 of file CSimComponentContextBase.h.
typedef std::map<std::string, IComponent*> icomp::CSimComponentContextBase::ComponentsMap [protected]
Definition at line 134 of file CSimComponentContextBase.h.
typedef std::map< std::string, const ComponentsFactory* > icomp::CSimComponentContextBase::FactoriesMap [protected]
Definition at line 137 of file CSimComponentContextBase.h.
Constructor & Destructor Documentation
icomp::CSimComponentContextBase::CSimComponentContextBase (const IComponentStaticInfo * infoPtr) [explicit]
Member Function Documentation
virtual const iser::IObject* icomp::CSimComponentContextBase::GetAttribute (const std::string & attributeId, int * definitionLevelPtr = NULL) const [virtual]
Get attribute using its ID.
Parameters:
attributeId ID of attribute.
definitionLevelPtr optional return value. This will be set to number parents you have to iterate to get component where this attribute was defined. If this attribute was defined in actual component it equals 0.
Implements icomp::IComponentContext.
virtual const IComponentContext* icomp::CSimComponentContextBase::GetParentContext () const [virtual]
Get access to parent component context.
Implements icomp::IComponentContext.
virtual const IRegistryElement& icomp::CSimComponentContextBase::GetRegistryElement () const [virtual]
Get access to component registry element object.
State of the component context is based on this registry element (part of registry document describing component) and context parent.
Implements icomp::IComponentContext.
virtual const IComponentStaticInfo& icomp::CSimComponentContextBase::GetStaticInfo () const [virtual]
Get component static info associated with this context.
Implements icomp::IComponentContext.
template<class Attribute > bool icomp::CSimComponentContextBase::InsertMultiAttr (const std::string & attributeId, const Attribute & attribute) [inline]
Insert new attribute to multi attributes.
Parameters:
attributeId ID of attribute (multiattribute).
attribute single attribute value.
Definition at line 90 of file CSimComponentContextBase.h.
References icomp::IRegistryElement::AttributeInfo::attributePtr, icomp::CRegistryElement::GetAttributeInfo(), istd::CClassInfo::GetName(), istd::TPointerBase< Type >::GetPtr(), I_ASSERT, icomp::CRegistryElement::InsertAttributeInfo(), icomp::TMultiAttribute< Value >::InsertValue(), IsAttributeTypeCorrect(), istd::TPointerBase< Type >::IsValid(), NULL, and istd::TDelPtr< Type, Accessor >::SetPtr().
bool icomp::CSimComponentContextBase::InsertMultiRef (const std::string & referenceId, IComponent * componentPtr)
Set named reference to some component.
template<class AttrType > bool icomp::CSimComponentContextBase::IsAttributeTypeCorrect (const std::string & attributeId) [inline, protected]
Check if attribute type is corrected.
Definition at line 149 of file CSimComponentContextBase.h.
References icomp::IComponentStaticInfo::GetAttributeInfo(), icomp::IAttributeStaticInfo::GetAttributeTypeName(), and NULL.
Referenced by InsertMultiAttr(), and SetSingleAttr().
bool icomp::CSimComponentContextBase::SetAttr (const std::string & attributeId, const iser::IObject * attributePtr)
Set named attribute.
Parameters:
attributeId ID of attribute.
attributePtr pointer to attribute instance. It will be automatically deleted.
Referenced by SetSingleAttr().
void icomp::CSimComponentContextBase::SetBoolAttr (const std::string & attributeId, bool value)
Set instance of bool attribute.
void icomp::CSimComponentContextBase::SetDoubleAttr (const std::string & attributeId, double value)
Set instance of double attribute.
bool icomp::CSimComponentContextBase::SetFactory (const std::string & factoryId, const ComponentsFactory * factoryPtr)
Set factory of component instance.
void icomp::CSimComponentContextBase::SetIntAttr (const std::string & attributeId, int value)
Set instance of int attribute.
bool icomp::CSimComponentContextBase::SetRef (const std::string & referenceId, IComponent * componentPtr)
Set named reference to some component.
template<class Attribute > bool icomp::CSimComponentContextBase::SetSingleAttr (const std::string & attributeId, const Attribute & attribute) [inline]
Set instance of simple attribute.
Definition at line 77 of file CSimComponentContextBase.h.
References I_ASSERT, IsAttributeTypeCorrect(), and SetAttr().
void icomp::CSimComponentContextBase::SetStringAttr (const std::string & attributeId, const istd::CString & value)
Set instance of istd::CString attribute.
Member Data Documentation
ComponentsMap icomp::CSimComponentContextBase::m_componentsMap [protected]
Definition at line 135 of file CSimComponentContextBase.h.
FactoriesMap icomp::CSimComponentContextBase::m_factoriesMap [protected]
Definition at line 138 of file CSimComponentContextBase.h.
Referenced by icomp::TSimComponentWrap< Base >::CreateSubcomponent().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/icomp/CSimComponentContextBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy