iqtgui::TContainerGuiCompBase< GuiCompBase > Class Template Reference
iqtgui::TContainerGuiCompBase< GuiCompBase > Class Template Reference
#include <TContainerGuiCompBase.h>
Public Types
enum DesignType {
DT_SIMPLE, DT_TOOL_BOX, DT_TAB_WIDGET, DT_STACK,
DT_SPLITTER
}
typedef GuiCompBase BaseClass
typedef
imod::CMultiModelDispatcherBase BaseClass2
Public Member Functions
I_REGISTER_SUBELEMENT (PageModel)
I_REGISTER_SUBELEMENT_INTERFACE_T (PageModel, iprm::ISelectionParam, ExtractPageModel)
I_REGISTER_SUBELEMENT_INTERFACE_T (PageModel, iprm::IOptionsList, ExtractPageModel)
I_REGISTER_SUBELEMENT_INTERFACE_T (PageModel, iser::ISerializable, ExtractPageModel)
I_REGISTER_SUBELEMENT_INTERFACE_T (PageModel, imod::IModel, ExtractPageModel)
I_REGISTER_SUBELEMENT_INTERFACE_T (PageModel, istd::IChangeable, ExtractPageModel)
I_ASSIGN_TO (m_slaveWidgetsModelCompPtr, m_slaveWidgetsVisualCompPtr, false)
I_ASSIGN_TO (m_pageActivatorsModelCompPtr, m_pageActivatorsCompPtr, false)
TContainerGuiCompBase ()
Protected Member Functions
virtual int GetPagesCount () const =0
Get the number of the pages in the UI container.
virtual iqtgui::IGuiObject * GetPageGuiComponent (int pageIndex) const =0
Get the UI component for a given page.
int GetCurrentPageIndex () const
Get the index of the currently active page in the container widget.
virtual QWidget * GetGuiContainerPtr () const
Get page container widget.
virtual bool CreateContainerGui (QWidget &parentWidget)
Create container GUI in some parent widget.
virtual int GetCurrentPage (QWidget &containerWidget) const
Get currently active page in the container.
virtual bool SetCurrentPage (QWidget &containerWidget, int pageIndex) const
Set active page in the container.
virtual QString GetPageTitle (QWidget &containerWidget, int pageIndex) const
Set the page title.
virtual void SetPageTitle (QWidget &containerWidget, int pageIndex, const QString &pageTitle) const
Set the page title.
virtual void SetPageIcon (QWidget &containerWidget, int pageIndex, const QIcon &pageIcon) const
Set the page icon.
virtual void SetPageToolTip (QWidget &containerWidget, int pageIndex, const QString &pageToolTip) const
Set the page tool tip.
virtual int AddPageToContainerWidget (QWidget &containerWidget, iqtgui::IGuiObject &pageGui, const QString &pageTitle) const
Add a new page to the widget container.
virtual bool SetPageEnabled (QWidget &containerWidget, int pageIndex, bool isPageEnabled=true) const
Set page enabled/disabled.
virtual bool SetPageIconSize (QWidget &containerWidget, const QSize &pageIconSize) const
Set the size page icon.
QString GetPageGuiName (const iqtgui::IGuiObject &pageGui) const
Get the name corresponding to a page GUI element.
bool CreatePage (QWidget *containerWidgetPtr, int guiIndex)
Create a page in the page container widget.
void UpdateVisualElements ()
Update visual status of the page elements.
virtual void OnGuiCreated ()
virtual void OnGuiDestroyed ()
virtual void OnComponentCreated ()
virtual void OnComponentDestroyed ()
virtual void OnModelChanged (int modelId, int changeFlags, istd::IPolymorphic *updateParamsPtr)
Detailed Description
template<class GuiCompBase>
class iqtgui::TContainerGuiCompBase< GuiCompBase >
Definition at line 25 of file TContainerGuiCompBase.h.
Member Typedef Documentation
template<class GuiCompBase > typedef GuiCompBase iqtgui::TContainerGuiCompBase< GuiCompBase >::BaseClass
Definition at line 30 of file TContainerGuiCompBase.h.
template<class GuiCompBase > typedef imod::CMultiModelDispatcherBase iqtgui::TContainerGuiCompBase< GuiCompBase >::BaseClass2
Definition at line 31 of file TContainerGuiCompBase.h.
Member Enumeration Documentation
template<class GuiCompBase > enum iqtgui::TContainerGuiCompBase::DesignType
Enumerator:
DT_SIMPLE
DT_TOOL_BOX
DT_TAB_WIDGET
DT_STACK
DT_SPLITTER
Definition at line 33 of file TContainerGuiCompBase.h.
Constructor & Destructor Documentation
template<class GuiCompBase > iqtgui::TContainerGuiCompBase< GuiCompBase >::TContainerGuiCompBase ()
Definition at line 230 of file TContainerGuiCompBase.h.
Member Function Documentation
template<class GuiCompBase > int iqtgui::TContainerGuiCompBase< GuiCompBase >::AddPageToContainerWidget (QWidget & containerWidget, iqtgui::IGuiObject & pageGui, const QString & pageTitle) const [protected, virtual]
Add a new page to the widget container.
Definition at line 386 of file TContainerGuiCompBase.h.
References iqtgui::IGuiObject::CreateGui(), iqtgui::IGuiObject::GetWidget(), and NULL.
template<class GuiCompBase > bool iqtgui::TContainerGuiCompBase< GuiCompBase >::CreateContainerGui (QWidget & parentWidget) [protected, virtual]
Create container GUI in some parent widget.
Definition at line 258 of file TContainerGuiCompBase.h.
References NULL.
template<class GuiCompBase > bool iqtgui::TContainerGuiCompBase< GuiCompBase >::CreatePage (QWidget * containerWidgetPtr, int guiIndex) [protected]
Create a page in the page container widget.
Definition at line 512 of file TContainerGuiCompBase.h.
References NULL.
template<class GuiCompBase > int iqtgui::TContainerGuiCompBase< GuiCompBase >::GetCurrentPage (QWidget & containerWidget) const [protected, virtual]
Get currently active page in the container.
Definition at line 330 of file TContainerGuiCompBase.h.
template<class GuiCompBase > int iqtgui::TContainerGuiCompBase< GuiCompBase >::GetCurrentPageIndex () const [protected]
Get the index of the currently active page in the container widget.
Definition at line 239 of file TContainerGuiCompBase.h.
References NULL.
template<class GuiCompBase > QWidget * iqtgui::TContainerGuiCompBase< GuiCompBase >::GetGuiContainerPtr () const [protected, virtual]
Get page container widget.
Definition at line 251 of file TContainerGuiCompBase.h.
template<class GuiCompBase > virtual iqtgui::IGuiObject* iqtgui::TContainerGuiCompBase< GuiCompBase >::GetPageGuiComponent (int pageIndex) const [protected, pure virtual]
Get the UI component for a given page.
template<class GuiCompBase > QString iqtgui::TContainerGuiCompBase< GuiCompBase >::GetPageGuiName (const iqtgui::IGuiObject & pageGui) const [protected]
Get the name corresponding to a page GUI element.
Definition at line 501 of file TContainerGuiCompBase.h.
template<class GuiCompBase > virtual int iqtgui::TContainerGuiCompBase< GuiCompBase >::GetPagesCount () const [protected, pure virtual]
Get the number of the pages in the UI container.
template<class GuiCompBase > QString iqtgui::TContainerGuiCompBase< GuiCompBase >::GetPageTitle (QWidget & containerWidget, int pageIndex) const [protected, virtual]
Set the page title.
Definition at line 344 of file TContainerGuiCompBase.h.
References NULL.
template<class GuiCompBase > iqtgui::TContainerGuiCompBase< GuiCompBase >::I_ASSIGN_TO (m_slaveWidgetsModelCompPtr , m_slaveWidgetsVisualCompPtr , false)
template<class GuiCompBase > iqtgui::TContainerGuiCompBase< GuiCompBase >::I_ASSIGN_TO (m_pageActivatorsModelCompPtr , m_pageActivatorsCompPtr , false)
template<class GuiCompBase > iqtgui::TContainerGuiCompBase< GuiCompBase >::I_REGISTER_SUBELEMENT (PageModel)
template<class GuiCompBase > iqtgui::TContainerGuiCompBase< GuiCompBase >::I_REGISTER_SUBELEMENT_INTERFACE_T (PageModel , iprm::ISelectionParam , ExtractPageModel)
template<class GuiCompBase > iqtgui::TContainerGuiCompBase< GuiCompBase >::I_REGISTER_SUBELEMENT_INTERFACE_T (PageModel , iprm::IOptionsList , ExtractPageModel)
template<class GuiCompBase > iqtgui::TContainerGuiCompBase< GuiCompBase >::I_REGISTER_SUBELEMENT_INTERFACE_T (PageModel , iser::ISerializable , ExtractPageModel)
template<class GuiCompBase > iqtgui::TContainerGuiCompBase< GuiCompBase >::I_REGISTER_SUBELEMENT_INTERFACE_T (PageModel , imod::IModel , ExtractPageModel)
template<class GuiCompBase > iqtgui::TContainerGuiCompBase< GuiCompBase >::I_REGISTER_SUBELEMENT_INTERFACE_T (PageModel , istd::IChangeable , ExtractPageModel)
template<class GuiCompBase > void iqtgui::TContainerGuiCompBase< GuiCompBase >::OnComponentCreated () [protected, virtual]
Definition at line 614 of file TContainerGuiCompBase.h.
References NULL.
template<class GuiCompBase > void iqtgui::TContainerGuiCompBase< GuiCompBase >::OnComponentDestroyed () [protected, virtual]
Definition at line 642 of file TContainerGuiCompBase.h.
References NULL.
template<class GuiCompBase > void iqtgui::TContainerGuiCompBase< GuiCompBase >::OnGuiCreated () [protected, virtual]
Definition at line 581 of file TContainerGuiCompBase.h.
template<class GuiCompBase > void iqtgui::TContainerGuiCompBase< GuiCompBase >::OnGuiDestroyed () [protected, virtual]
Definition at line 595 of file TContainerGuiCompBase.h.
References iqtgui::IGuiObject::DestroyGui(), and NULL.
template<class GuiCompBase > void iqtgui::TContainerGuiCompBase< GuiCompBase >::OnModelChanged (int modelId, int changeFlags, istd::IPolymorphic * updateParamsPtr) [protected, virtual]
Implements imod::CMultiModelDispatcherBase.
Definition at line 655 of file TContainerGuiCompBase.h.
template<class GuiCompBase > bool iqtgui::TContainerGuiCompBase< GuiCompBase >::SetCurrentPage (QWidget & containerWidget, int pageIndex) const [protected, virtual]
Set active page in the container.
Definition at line 337 of file TContainerGuiCompBase.h.
template<class GuiCompBase > bool iqtgui::TContainerGuiCompBase< GuiCompBase >::SetPageEnabled (QWidget & containerWidget, int pageIndex, bool isPageEnabled = true) const [protected, virtual]
Set page enabled/disabled.
Definition at line 463 of file TContainerGuiCompBase.h.
References NULL.
template<class GuiCompBase > void iqtgui::TContainerGuiCompBase< GuiCompBase >::SetPageIcon (QWidget & containerWidget, int pageIndex, const QIcon & pageIcon) const [protected, virtual]
Set the page icon.
Definition at line 366 of file TContainerGuiCompBase.h.
References NULL.
template<class GuiCompBase > bool iqtgui::TContainerGuiCompBase< GuiCompBase >::SetPageIconSize (QWidget & containerWidget, const QSize & pageIconSize) const [protected, virtual]
Set the size page icon.
Definition at line 494 of file TContainerGuiCompBase.h.
template<class GuiCompBase > void iqtgui::TContainerGuiCompBase< GuiCompBase >::SetPageTitle (QWidget & containerWidget, int pageIndex, const QString & pageTitle) const [protected, virtual]
Set the page title.
Definition at line 356 of file TContainerGuiCompBase.h.
References NULL.
template<class GuiCompBase > void iqtgui::TContainerGuiCompBase< GuiCompBase >::SetPageToolTip (QWidget & containerWidget, int pageIndex, const QString & pageToolTip) const [protected, virtual]
Set the page tool tip.
Definition at line 376 of file TContainerGuiCompBase.h.
References NULL.
template<class GuiCompBase > void iqtgui::TContainerGuiCompBase< GuiCompBase >::UpdateVisualElements () [protected]
Update visual status of the page elements.
Definition at line 541 of file TContainerGuiCompBase.h.
References iqtgui::IVisualStatusProvider::GetStatusIcon(), iqtgui::IVisualStatusProvider::GetStatusText(), and NULL.
The documentation for this class was generated from the following file:
Include/iqtgui/TContainerGuiCompBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy