iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel > Class Template Reference
iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel > Class Template Reference
#include <TPolygonBasedParamsGuiComp.h>
Classes
class CPolygonParamsGuiItemDelegate
Internal item delegate class for input validation.
Public Types
enum CellIndex { CI_X, CI_Y, CI_LAST = CI_Y }
Cell index.
typedef
iqt2d::TShapeParamsGuiCompBase
< Ui::CPolygonParamsGuiComp,
PolygonBasedShape,
PolygonBasedModel > BaseClass
Public Types inherited from iqtgui::TGuiComponentBase< QWidget >
typedef CGuiComponentBase BaseClass
Public Types inherited from iqtgui::CGuiComponentBase
typedef icomp::CComponentBase BaseClass
Public Types inherited from imod::TSingleModelObserverBase< PolygonBasedModel >
typedef CSingleModelObserverBase BaseClass
typedef PolygonBasedModel ModelType
Public Types inherited from imod::CSingleModelObserverBase
typedef imod::IModel ModelType
Public Types inherited from imod::IModelEditor
enum ChangeFlags { CF_INIT_EDITOR = 1 << 4 }
Public Types inherited from iqt2d::IViewExtender
enum SceneFlags { SF_BACKGROUND = 1, SF_DIRECT = 2 }
Standard flags for items .
Public Member Functions
virtual void UpdateModel () const
Updates model from editor.
Public Member Functions inherited from iqtgui::TGuiComponentBase< QWidget >
TGuiComponentBase ()
virtual QWidget * GetQtWidget () const
Public Member Functions inherited from iqtgui::CGuiComponentBase
I_REGISTER_SUBELEMENT_INTERFACE_T (VisualStatus, IVisualStatus, ExtractVisualStatus)
I_REGISTER_SUBELEMENT_INTERFACE_T (VisualStatus, istd::IChangeable, ExtractVisualStatus)
I_REGISTER_SUBELEMENT_INTERFACE_T (VisualStatus, imod::IModel, ExtractVisualStatus)
CGuiComponentBase ()
bool IsGuiShown () const
virtual bool IsGuiCreated () const
Inform if GUI was initilized.
virtual bool CreateGui (QWidget *parentPtr)
Initialize GUI and connect it to the parent.
virtual bool DestroyGui ()
Release GUI and disconnect it from parent.
virtual QWidget * GetWidget () const
Get access to internal QWidget object.
virtual void OnTryClose (bool *ignoredPtr=NULL)
Called on trying to close application.
Public Member Functions inherited from icomp::CComponentBase
CComponentBase ()
Create component and assign it to specific context.
virtual const ICompositeComponent * GetParentComponent (bool ownerOnly=false) const
Get parent of this component.
virtual void * GetInterface (const istd::CClassInfo &interfaceType, const QByteArray &subId="")
Get access to specified component interface.
virtual const IComponentContext * GetComponentContext () const
Get access to component context describing all application-specified component information loaded from components registry.
virtual void SetComponentContext (const icomp::IComponentContext *contextPtr, const ICompositeComponent *parentPtr, bool isParentOwner)
Set component context of this component.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Public Member Functions inherited from imod::TSingleModelObserverBase< PolygonBasedModel >
TSingleModelObserverBase ()
PolygonBasedModel * GetObjectPtr () const
bool AttachOrSetObject (PolygonBasedModel *objectPtr)
Attach to model of object or set object pointer, if no connection is possible.
Public Member Functions inherited from imod::CSingleModelObserverBase
CSingleModelObserverBase ()
virtual ~CSingleModelObserverBase ()
imod::IModel * GetModelPtr () const
Get access to observed model.
void EnsureModelDetached ()
Make sure this observer is detached.
virtual bool IsModelAttached (const imod::IModel *modelPtr=NULL) const
Check if specified model is attached.
virtual void BeforeUpdate (imod::IModel *modelPtr, int updateFlags, istd::IPolymorphic *updateParamsPtr)
This function will be called before update of the observer contents occures.
Protected Types
enum MenuAction {
ActionFlipHorizontally, ActionFlipVertically, ActionRotateClockwise, ActionRotateCounterclockwise,
ActionReverseLine
}
Protected Member Functions
QTableWidget * GetNodeTable ()
Get the table with the node data.
virtual void OnInsertNode ()
virtual void OnRemoveNode ()
virtual void OnCopyData ()
virtual void OnPasteData ()
virtual void OnGuiModelAttached ()
Called when model is attached and GUI is created.
virtual void OnGuiModelDetached ()
Called when model is detached or GUI is destroyed.
virtual void UpdateGui (int updateFlags=0)
Do update of the model GUI.
virtual void OnGuiCreated ()
Called just after GUI is initialized.
void UpdateToolsMenuButton ()
Enable or disable the Tools button depending on model type and dynamically build its menu.
void OnToolsButtonMenuActionTriggered (QAction *action)
Protected Member Functions inherited from iqtgui::CGuiComponentBase
virtual bool OnKeyPressed (QKeyEvent *event)
Called from widget event filter when key is pressed.
virtual void OnRetranslate ()
Called when non-GUI elements (like commands) should be retranslated.
void SetStatusIcon (const QIcon &icon)
Set status icon;.
void SetStatusText (const QString &text)
Set status text;.
virtual bool eventFilter (QObject *sourcePtr, QEvent *eventPtr)
Protected Member Functions inherited from icomp::CComponentBase
bool IsComponentActive () const
Check if component is active.
virtual const
icomp::IRealComponentStaticInfo & GetComponentStaticInfo () const =0
Get access to static info of this component.
Protected Member Functions inherited from imod::TSingleModelObserverBase< PolygonBasedModel >
virtual PolygonBasedModel * CastFromModel (imod::IModel *modelPtr) const
Protected Member Functions inherited from imod::CSingleModelObserverBase
void SetModelPtr (imod::IModel *modelPtr)
Set internal model pointer to specified value.
virtual void OnUpdate (int updateFlags, istd::IPolymorphic *updateParamsPtr)
Additional Inherited Members
Static Protected Member Functions inherited from icomp::CComponentBase
static const
icomp::IRealComponentStaticInfo & InitStaticInfo (IComponent *componentPtr)
static QByteArray GetComponentId (const icomp::IComponentContext *componentContextPtr, const QByteArray &contextId=QByteArray())
Protected Attributes inherited from iqtgui::CGuiComponentBase
imod::TModelWrap< VisualStatus > m_visualStatus
Detailed Description
template<class PolygonBasedShape, class PolygonBasedModel>
class iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >
Definition at line 38 of file TPolygonBasedParamsGuiComp.h.
Member Typedef Documentation
template<class PolygonBasedShape, class PolygonBasedModel> typedef iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, PolygonBasedShape, PolygonBasedModel> iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::BaseClass
Definition at line 69 of file TPolygonBasedParamsGuiComp.h.
Member Enumeration Documentation
template<class PolygonBasedShape, class PolygonBasedModel> enum iqt2d::TPolygonBasedParamsGuiComp::CellIndex
Cell index.
Enumerator
CI_X
Index of the table cell for the X coordinate of the polygon node.
CI_Y
Index of the table cell for the X coordinate of the polygon node.
CI_LAST
Last used cell index.
Definition at line 48 of file TPolygonBasedParamsGuiComp.h.
template<class PolygonBasedShape, class PolygonBasedModel> enum iqt2d::TPolygonBasedParamsGuiComp::MenuAction protected
Enumerator
ActionFlipHorizontally
ActionFlipVertically
ActionRotateClockwise
ActionRotateCounterclockwise
ActionReverseLine
Definition at line 124 of file TPolygonBasedParamsGuiComp.h.
Member Function Documentation
template<class PolygonBasedShape , class PolygonBasedModel > QTableWidget * iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::GetNodeTable () protected
Get the table with the node data.
Definition at line 165 of file TPolygonBasedParamsGuiComp.h.
template<class PolygonBasedShape , class PolygonBasedModel > void iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnCopyData () protected virtual
Definition at line 195 of file TPolygonBasedParamsGuiComp.h.
References iser::CMemoryWriteArchive::GetBuffer(), iser::CMemoryWriteArchive::GetBufferSize(), and NULL.
template<class PolygonBasedShape , class PolygonBasedModel > void iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnGuiCreated () protected virtual
Called just after GUI is initialized.
Reimplemented from iqtgui::TDesignerGuiObserverCompBase< Ui, PolygonBasedModel >.
Definition at line 298 of file TPolygonBasedParamsGuiComp.h.
template<class PolygonBasedShape , class PolygonBasedModel > void iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnGuiModelAttached () protected virtual
Called when model is attached and GUI is created.
Reimplemented from iqtgui::TGuiObserverWrap< iqtgui::TDesignerGuiCompBase< Ui, QWidget >, imod::TSingleModelObserverBase< PolygonBasedModel > >.
Definition at line 253 of file TPolygonBasedParamsGuiComp.h.
template<class PolygonBasedShape , class PolygonBasedModel > void iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnGuiModelDetached () protected virtual
Called when model is detached or GUI is destroyed.
Reimplemented from iqtgui::TGuiObserverWrap< iqtgui::TDesignerGuiCompBase< Ui, QWidget >, imod::TSingleModelObserverBase< PolygonBasedModel > >.
Definition at line 264 of file TPolygonBasedParamsGuiComp.h.
template<class PolygonBasedShape , class PolygonBasedModel > void iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnInsertNode () protected virtual
Reimplemented in iqt2d::CTubePolylineParamsGuiComp.
Definition at line 172 of file TPolygonBasedParamsGuiComp.h.
template<class PolygonBasedShape , class PolygonBasedModel > void iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnPasteData () protected virtual
Definition at line 216 of file TPolygonBasedParamsGuiComp.h.
References NULL.
template<class PolygonBasedShape , class PolygonBasedModel > void iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnRemoveNode () protected virtual
Definition at line 237 of file TPolygonBasedParamsGuiComp.h.
template<class PolygonBasedShape , class PolygonBasedModel > void iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnToolsButtonMenuActionTriggered (QAction * action) protected
Definition at line 347 of file TPolygonBasedParamsGuiComp.h.
References i2d::CPolygon::GetCenter(), i2d::CPolygon::GetNode(), i2d::CPolygon::GetNodesCount(), i2d::CVector2d::GetX(), i2d::CVector2d::GetY(), NULL, i2d::CAffineTransformation2d::Reset(), i2d::CPolygon::SetNode(), i2d::CVector2d::SetX(), i2d::CVector2d::SetY(), and i2d::CPolygon::Transform().
template<class PolygonBasedShape , class PolygonBasedModel > void iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::UpdateGui (int updateFlags = 0) protected virtual
Do update of the model GUI.
Reimplemented from iqtgui::TGuiObserverWrap< iqtgui::TDesignerGuiCompBase< Ui, QWidget >, imod::TSingleModelObserverBase< PolygonBasedModel > >.
Reimplemented in iqt2d::CTubePolylineParamsGuiComp.
Definition at line 275 of file TPolygonBasedParamsGuiComp.h.
References i2d::CPolygon::GetNode(), i2d::CPolygon::GetNodesCount(), i2d::CVector2d::GetX(), i2d::CVector2d::GetY(), and NULL.
template<class PolygonBasedShape , class PolygonBasedModel > void iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::UpdateModel () const virtual
Updates model from editor.
This method will be called only if GUI is connected and model is attached.
Reimplemented from iqtgui::TGuiObserverWrap< iqtgui::TDesignerGuiCompBase< Ui, QWidget >, imod::TSingleModelObserverBase< PolygonBasedModel > >.
Reimplemented in iqt2d::CTubePolylineParamsGuiComp.
Definition at line 136 of file TPolygonBasedParamsGuiComp.h.
References i2d::CPolygon::CopyFrom(), i2d::CPolygon::InsertNode(), i2d::CPolygon::IsEqual(), and NULL.
template<class PolygonBasedShape , class PolygonBasedModel > void iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::UpdateToolsMenuButton () protected
Enable or disable the Tools button depending on model type and dynamically build its menu.
Definition at line 318 of file TPolygonBasedParamsGuiComp.h.
References NULL.
The documentation for this class was generated from the following file:
Include/iqt2d/TPolygonBasedParamsGuiComp.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy