ibase::TSerializableContainer< ItemClass > Class Template Reference
ibase::TSerializableContainer< ItemClass > Class Template Reference abstract
Common implementation for an abstract serializable container.
#include <TSerializableContainer.h>
Public Types
typedef TContainer< ItemClass > BaseClass
Public Types inherited from ibase::TContainer< ItemClass >
enum ChangeFlags { CF_ELEMENT_ADDED = 1 << 21, CF_ELEMENT_REMOVED = 1 << 22, CF_RESET = 1 << 23 }
Public Types inherited from istd::IChangeable
enum ChangeFlags {
CF_ACF_INTERNAL = 1 << 0, CF_MODEL = 1 << 1, CF_ABORTED = 1 << 2, CF_DELEGATED = 1 << 3,
CF_NO_UNDO = 1 << 5
}
enum SupportedOperations {
SO_NONE = 0, SO_OBSERVE = 1, SO_COPY = 2, SO_CLONE = 4,
SO_COMPARE = 8
}
Flags for supported operations.
enum CompatibilityMode { CM_STRICT, CM_WITHOUT_REFS, CM_WITH_REFS, CM_CONVERT }
Control how relationship betweeen objects are interpreted.
Public Member Functions
virtual bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
Public Member Functions inherited from ibase::TContainer< ItemClass >
const ItemClass & GetAt (int index) const
ItemClass & GetAt (int index)
ItemClass & PushBack (const ItemClass &item)
ItemClass & PushFront (const ItemClass &item)
ItemClass & InsertAt (const ItemClass &item, int index)
void PopBack ()
void PopFront ()
void RemoveAt (int index)
virtual void Reset ()
TContainer & operator= (const TContainer &container)
virtual int GetItemsCount () const
Returns number of elements in the container.
virtual bool IsEmpty () const
Returns a true if container is empty, otherwise a false.
virtual bool IsIndexValid (int index) const
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Public Member Functions inherited from istd::IChangeable
virtual void BeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Starts the change transaction.
virtual void EndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Ends the change transaction.
virtual int GetSupportedOperations () const
Get set of flags for supported operations.
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Copy this object from another one.
virtual bool IsEqual (const IChangeable &object) const
Compare this object with another object.
virtual IChangeable * CloneMe (CompatibilityMode mode=CM_WITHOUT_REFS) const
Make a copy of this object.
virtual bool ResetData (CompatibilityMode mode=CM_WITHOUT_REFS)
Reset data to its default state.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Public Member Functions inherited from iser::ISerializable
virtual quint32 GetMinimalVersion (int versionId) const
Get minimal needed version to correct storing of this data.
Protected Member Functions
virtual bool SerializeItem (ItemClass &item, iser::IArchive &archive)=0
Serialize a single item in the container.
Protected Member Functions inherited from istd::IChangeable
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for begin change event.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for end change event.
Additional Inherited Members
Protected Types inherited from ibase::TContainer< ItemClass >
typedef QList< ItemClass > Items
Protected Attributes inherited from ibase::TContainer< ItemClass >
Items m_items
Detailed Description
template<typename ItemClass>
class ibase::TSerializableContainer< ItemClass >
Common implementation for an abstract serializable container.
Derived class must only reimplement the SerializeItem().
Definition at line 21 of file TSerializableContainer.h.
Member Typedef Documentation
template<typename ItemClass> typedef TContainer<ItemClass> ibase::TSerializableContainer< ItemClass >::BaseClass
Definition at line 24 of file TSerializableContainer.h.
Member Function Documentation
template<typename ItemClass > bool ibase::TSerializableContainer< ItemClass >::Serialize (iser::IArchive & archive) virtual
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See Also
iser::IArchive
Implements iser::ISerializable.
Reimplemented in ibase::TFactorisableContainer< InterfaceClass >.
Definition at line 44 of file TSerializableContainer.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), and NULL.
template<typename ItemClass> virtual bool ibase::TSerializableContainer< ItemClass >::SerializeItem (ItemClass & item, iser::IArchive & archive) protected pure virtual
Serialize a single item in the container.
Implemented in ibase::TFactorisableContainer< InterfaceClass >.
The documentation for this class was generated from the following file:
Include/ibase/TSerializableContainer.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy