ACF: ibase::TEnableableWrap< Base > Class Template Reference
ibase::TEnableableWrap< Base > Class Template Reference
[Set of helper classes.]
Basic implementation of IEnabled interface.
#include <TEnableableWrap.h>
Public Types
typedef Base BaseClass
Public Member Functions
TEnableableWrap ()
virtual bool IsEnabled () const
virtual bool IsEnablingAllowed () const
virtual void SetEnabled (bool isEnabled=true)
Protected Member Functions
virtual bool SerializeEnabled (iser::IArchive &archive)
Serialize state of enable flag.
Detailed Description
template<class Base>
class ibase::TEnableableWrap< Base >
Basic implementation of IEnabled interface.
Definition at line 23 of file TEnableableWrap.h.
Member Typedef Documentation
template<class Base> typedef Base ibase::TEnableableWrap< Base >::BaseClass
Reimplemented in iqtgui::CHierarchicalCommand.
Definition at line 26 of file TEnableableWrap.h.
Constructor & Destructor Documentation
template<class Base > ibase::TEnableableWrap< Base >::TEnableableWrap () [inline]
Definition at line 49 of file TEnableableWrap.h.
Member Function Documentation
template<class Base > bool ibase::TEnableableWrap< Base >::IsEnabled () const [inline, virtual]
Definition at line 58 of file TEnableableWrap.h.
template<class Base > bool ibase::TEnableableWrap< Base >::IsEnablingAllowed () const [inline, virtual]
Definition at line 65 of file TEnableableWrap.h.
Referenced by ibase::TEnableableWrap< Base >::SetEnabled().
template<class Base > bool ibase::TEnableableWrap< Base >::SerializeEnabled (iser::IArchive & archive) [inline, protected, virtual]
Serialize state of enable flag.
Definition at line 85 of file TEnableableWrap.h.
References iser::IArchive::BeginTag(), iser::IArchive::EndTag(), and iser::IArchive::Process().
template<class Base > void ibase::TEnableableWrap< Base >::SetEnabled (bool isEnabled = true) [inline, virtual]
Reimplemented in iqtgui::CHierarchicalCommand.
Definition at line 72 of file TEnableableWrap.h.
References ibase::TEnableableWrap< Base >::IsEnablingAllowed().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/ibase/TEnableableWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy