iview::CDrawBuffer Class Reference
iview::CDrawBuffer Class Reference
#include <CDrawBuffer.h>
Public Types
typedef QPixmap BaseClass
Public Member Functions
CDrawBuffer ()
void Reset ()
Reset state of this bitmap.
bool IsCreated () const
Check, if bitmap was created.
void Create (const QPaintDevice &device, ibase::CSize size)
Create new buffer with the given size.
void CopyRectTo (const i2d::CRect &source, QPainter &drawContext, istd::CIndex2d contextPos) const
Copy rectangle area to specified draw context.
void CopyRectTo (const i2d::CRect &source, QPaintDevice &device, istd::CIndex2d devicePos) const
Copy rectangle area to specified native paint device.
QPainter & GetDrawContext ()
Get used painter for drawing operations.
Protected Member Functions
void EnsureDrawContext ()
Detailed Description
Definition at line 20 of file CDrawBuffer.h.
Member Typedef Documentation
typedef QPixmap iview::CDrawBuffer::BaseClass
Definition at line 23 of file CDrawBuffer.h.
Constructor & Destructor Documentation
iview::CDrawBuffer::CDrawBuffer () [inline]
Definition at line 69 of file CDrawBuffer.h.
Member Function Documentation
void iview::CDrawBuffer::CopyRectTo (const i2d::CRect & source, QPainter & drawContext, istd::CIndex2d contextPos) const
Copy rectangle area to specified draw context.
It is used for native-compatible template implementation in iview::TViewImpl.
void iview::CDrawBuffer::CopyRectTo (const i2d::CRect & source, QPaintDevice & device, istd::CIndex2d devicePos) const
Copy rectangle area to specified native paint device.
It is used for native-compatible template implementation in iview::TViewImpl.
void iview::CDrawBuffer::Create (const QPaintDevice & device, ibase::CSize size)
Create new buffer with the given size.
void iview::CDrawBuffer::EnsureDrawContext () [protected]
Referenced by GetDrawContext().
QPainter & iview::CDrawBuffer::GetDrawContext () [inline]
Get used painter for drawing operations.
Definition at line 74 of file CDrawBuffer.h.
References EnsureDrawContext(), and istd::TPointerBase< Type >::IsValid().
bool iview::CDrawBuffer::IsCreated () const
Check, if bitmap was created.
void iview::CDrawBuffer::Reset ()
Reset state of this bitmap.
The documentation for this class was generated from the following file:
Include/iview/CDrawBuffer.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy