icmm::CRgb Class Reference
icmm::CRgb Class Reference
Primitive for representation of RGB color value.
#include <CRgb.h>
Public Types
enum ComponentIndex { CI_RED, CI_GREEN, CI_BLUE, CI_LAST = CI_BLUE }
typedef TComposedColor< 3 > BaseClass
Public Member Functions
CRgb (double r=0.0, double g=0.0, double b=0.0)
CRgb (const CRgb &color)
double GetRed () const
void SetRed (double value)
double GetGreen () const
void SetGreen (double value)
double GetBlue () const
void SetBlue (double value)
bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
CRgb operator+ (const CRgb &color) const
CRgb operator- (const CRgb &color) const
CRgb operator* (const CRgb &color) const
CRgb operator/ (const CRgb &color) const
CRgb operator* (double value) const
CRgb operator/ (double value) const
const CRgb & operator= (const CRgb &color)
const CRgb & operator+= (const CRgb &color)
const CRgb & operator-= (const CRgb &color)
const CRgb & operator*= (const CRgb &color)
const CRgb & operator/= (const CRgb &color)
const CRgb & operator*= (double value)
const CRgb & operator/= (double value)
Detailed Description
Primitive for representation of RGB color value.
Please note, that normal components values are in range [0, 1].
Definition at line 18 of file CRgb.h.
Member Typedef Documentation
typedef TComposedColor<3> icmm::CRgb::BaseClass
Reimplemented from icmm::TComposedColor< 3 >.
Definition at line 21 of file CRgb.h.
Member Enumeration Documentation
enum icmm::CRgb::ComponentIndex
Enumerator:
CI_RED
CI_GREEN
CI_BLUE
CI_LAST
Definition at line 23 of file CRgb.h.
Constructor & Destructor Documentation
icmm::CRgb::CRgb (double r = 0.0, double g = 0.0, double b = 0.0) [inline]
Definition at line 67 of file CRgb.h.
References CI_BLUE, CI_GREEN, CI_RED, and imath::TVector< Size >::SetElement().
icmm::CRgb::CRgb (const CRgb & color) [inline]
Definition at line 75 of file CRgb.h.
Member Function Documentation
double icmm::CRgb::GetBlue () const [inline]
Definition at line 110 of file CRgb.h.
References CI_BLUE, and imath::TVector< Size >::GetElement().
double icmm::CRgb::GetGreen () const [inline]
Definition at line 98 of file CRgb.h.
References CI_GREEN, and imath::TVector< Size >::GetElement().
double icmm::CRgb::GetRed () const [inline]
Definition at line 86 of file CRgb.h.
References CI_RED, and imath::TVector< Size >::GetElement().
CRgb icmm::CRgb::operator* (const CRgb & color) const
CRgb icmm::CRgb::operator* (double value) const
Reimplemented from icmm::TComposedColor< 3 >.
const CRgb & icmm::CRgb::operator*= (const CRgb & color) [inline]
Definition at line 148 of file CRgb.h.
References icmm::TComposedColor< 3 >::operator*=().
const CRgb & icmm::CRgb::operator*= (double value) [inline]
Reimplemented from icmm::TComposedColor< 3 >.
Definition at line 164 of file CRgb.h.
References icmm::TComposedColor< 3 >::operator*=().
CRgb icmm::CRgb::operator+ (const CRgb & color) const
const CRgb & icmm::CRgb::operator+= (const CRgb & color) [inline]
Definition at line 132 of file CRgb.h.
References icmm::TComposedColor< 3 >::operator+=().
CRgb icmm::CRgb::operator- (const CRgb & color) const
const CRgb & icmm::CRgb::operator-= (const CRgb & color) [inline]
Definition at line 140 of file CRgb.h.
References icmm::TComposedColor< 3 >::operator-=().
CRgb icmm::CRgb::operator/ (const CRgb & color) const
CRgb icmm::CRgb::operator/ (double value) const
Reimplemented from icmm::TComposedColor< 3 >.
const CRgb & icmm::CRgb::operator/= (const CRgb & color) [inline]
Definition at line 156 of file CRgb.h.
References icmm::TComposedColor< 3 >::operator/=().
const CRgb & icmm::CRgb::operator/= (double value) [inline]
Reimplemented from icmm::TComposedColor< 3 >.
Definition at line 172 of file CRgb.h.
References icmm::TComposedColor< 3 >::operator/=().
const CRgb & icmm::CRgb::operator= (const CRgb & color) [inline]
Definition at line 124 of file CRgb.h.
References icmm::TComposedColor< 3 >::operator=().
bool icmm::CRgb::Serialize (iser::IArchive & archive) [virtual]
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See also:
iser::IArchive
Reimplemented from icmm::TComposedColor< 3 >.
void icmm::CRgb::SetBlue (double value) [inline]
Definition at line 116 of file CRgb.h.
References CI_BLUE, and imath::TVector< Size >::SetElement().
void icmm::CRgb::SetGreen (double value) [inline]
Definition at line 104 of file CRgb.h.
References CI_GREEN, and imath::TVector< Size >::SetElement().
void icmm::CRgb::SetRed (double value) [inline]
Definition at line 92 of file CRgb.h.
References CI_RED, and imath::TVector< Size >::SetElement().
The documentation for this class was generated from the following file:
Include/icmm/CRgb.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy