iattr::TMultiAttribute< Value > Class Template Reference
iattr::TMultiAttribute< Value > Class Template Reference
Template implementation of multiple attribute.
#include <TMultiAttribute.h>
Public Types
typedef Value ValueType
typedef iattr::CAttributeBase BaseClass
typedef std::vector< ValueType > ValueList
typedef ValueList::iterator iterator
typedef ValueList::const_iterator const_iterator
Public Member Functions
TMultiAttribute ()
Default constructor.
TMultiAttribute (iattr::IAttributesManager *attributeOwnerPtr, const std::string &attributeId, const std::string &attributeDescription, int attributeFlags, int changeFlags=0, int elementsCount=0, Value *valuesPtr=NULL)
Constructor.
void SetValues (const ValueList &valueList)
template<class ContainerImpl >
void SetValues (typename ContainerImpl::const_iterator begin, typename ContainerImpl::const_iterator end)
Set value list to the attribute.
const ValueList & GetValues () const
Get all values.
virtual int GetValuesCount () const
Get number of values in the multi attribute.
virtual Value GetValueAt (int index) const
Get value at the index index.
virtual void SetValueAt (int index, const Value &value)
Set value at the index index to new value value.
virtual void InsertValue (const Value &value)
Insert new value into container.
virtual void ResetValues ()
Remove all values from the container.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
const std::string & GetFactoryId () const
virtual bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
Static Public Member Functions
static const std::string & GetTypeName ()
Protected Attributes
std::vector< Value > m_values
Detailed Description
template<typename Value>
class iattr::TMultiAttribute< Value >
Template implementation of multiple attribute.
Definition at line 28 of file TMultiAttribute.h.
Member Typedef Documentation
template<typename Value > typedef iattr::CAttributeBase iattr::TMultiAttribute< Value >::BaseClass
Reimplemented from iser::TCopySerializedWrap< iattr::IAttribute >.
Definition at line 32 of file TMultiAttribute.h.
template<typename Value > typedef ValueList::const_iterator iattr::TMultiAttribute< Value >::const_iterator
Definition at line 35 of file TMultiAttribute.h.
template<typename Value > typedef ValueList::iterator iattr::TMultiAttribute< Value >::iterator
Definition at line 34 of file TMultiAttribute.h.
template<typename Value > typedef std::vector<ValueType> iattr::TMultiAttribute< Value >::ValueList
Definition at line 33 of file TMultiAttribute.h.
template<typename Value > typedef Value iattr::TMultiAttribute< Value >::ValueType
Definition at line 31 of file TMultiAttribute.h.
Constructor & Destructor Documentation
template<typename Value > iattr::TMultiAttribute< Value >::TMultiAttribute ()
Default constructor.
Definition at line 124 of file TMultiAttribute.h.
template<typename Value > iattr::TMultiAttribute< Value >::TMultiAttribute (iattr::IAttributesManager * attributeOwnerPtr, const std::string & attributeId, const std::string & attributeDescription, int attributeFlags, int changeFlags = 0, int elementsCount = 0, Value * valuesPtr = NULL)
Constructor.
Parameters:
attributeOwnerPtr Owner of the attrbiute.
attributeId Unique ID of the attrbiute.
attributeId Attribute description.
changeFlags Change flags for model update notification.
elementsCount Number of elements stored at valuesPtr.
valuesPtr Pointer to array of elements.
Definition at line 130 of file TMultiAttribute.h.
References iattr::TMultiAttribute< Value >::m_values.
Member Function Documentation
template<typename Value > TMultiAttribute< Value >::iterator iattr::TMultiAttribute< Value >::begin ()
Definition at line 226 of file TMultiAttribute.h.
template<typename Value > TMultiAttribute< Value >::const_iterator iattr::TMultiAttribute< Value >::begin () const
Definition at line 233 of file TMultiAttribute.h.
template<typename Value > TMultiAttribute< Value >::iterator iattr::TMultiAttribute< Value >::end ()
Definition at line 240 of file TMultiAttribute.h.
template<typename Value > TMultiAttribute< Value >::const_iterator iattr::TMultiAttribute< Value >::end () const
Definition at line 247 of file TMultiAttribute.h.
template<typename Value > const std::string & iattr::TMultiAttribute< Value >::GetFactoryId () const [virtual]
Reimplemented from iser::IObject.
Definition at line 256 of file TMultiAttribute.h.
template<typename Value > const std::string & iattr::TMultiAttribute< Value >::GetTypeName () [static]
Definition at line 307 of file TMultiAttribute.h.
template<typename Value > Value iattr::TMultiAttribute< Value >::GetValueAt (int index) const [virtual]
Get value at the index index.
Definition at line 184 of file TMultiAttribute.h.
References I_ASSERT.
template<typename Value > const TMultiAttribute< Value >::ValueList & iattr::TMultiAttribute< Value >::GetValues () const
Get all values.
Definition at line 170 of file TMultiAttribute.h.
template<typename Value > int iattr::TMultiAttribute< Value >::GetValuesCount () const [virtual]
Get number of values in the multi attribute.
Definition at line 177 of file TMultiAttribute.h.
template<typename Value > void iattr::TMultiAttribute< Value >::InsertValue (const Value & value) [virtual]
Insert new value into container.
Definition at line 208 of file TMultiAttribute.h.
template<typename Value > void iattr::TMultiAttribute< Value >::ResetValues () [virtual]
Remove all values from the container.
Definition at line 215 of file TMultiAttribute.h.
template<typename Value > bool iattr::TMultiAttribute< Value >::Serialize (iser::IArchive & archive) [virtual]
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See also:
iser::IArchive
Implements iser::ISerializable.
Definition at line 265 of file TMultiAttribute.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), and iser::IArchive::Process().
template<typename Value > void iattr::TMultiAttribute< Value >::SetValueAt (int index, const Value & value) [virtual]
Set value at the index index to new value value.
Definition at line 194 of file TMultiAttribute.h.
References I_ASSERT.
template<typename Value > void iattr::TMultiAttribute< Value >::SetValues (const ValueList & valueList)
Definition at line 147 of file TMultiAttribute.h.
template<typename Value > template<class ContainerImpl > void iattr::TMultiAttribute< Value >::SetValues (typename ContainerImpl::const_iterator begin, typename ContainerImpl::const_iterator end)
Set value list to the attribute.
Definition at line 155 of file TMultiAttribute.h.
Member Data Documentation
template<typename Value > std::vector<Value> iattr::TMultiAttribute< Value >::m_values [protected]
Definition at line 114 of file TMultiAttribute.h.
Referenced by iattr::TMultiAttribute< Value >::TMultiAttribute().
The documentation for this class was generated from the following file:
Include/iattr/TMultiAttribute.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy