iview::CScreenTransform Class Reference
iview::CScreenTransform Class Reference
#include <CScreenTransform.h>
Public Types
typedef i2d::CAffine2d BaseClass
Public Member Functions
CScreenTransform ()
Default constructor.
CScreenTransform (const CScreenTransform &transform)
Copy constructor.
CScreenTransform (const i2d::CAffine2d &transform)
Constructs CScreenTransform using i2d::CAffine2d object.
i2d::CVector2d GetClientPosition (istd::CIndex2d position) const
Return position of point in logical coordinates.
istd::CIndex2d GetScreenPosition (const i2d::CVector2d &position) const
Return position of point in screen coordinates.
const i2d::CAffine2d & GetInverted () const
Return reference to invert transformation.
void Reset ()
void Reset (const i2d::CVector2d &position)
void Reset (const i2d::CVector2d &position, double angle, double scale=1.0)
void Reset (const i2d::CVector2d &position, double angle, const i2d::CVector2d &scale)
void GetApply (const i2d::CAffine2d &transform, CScreenTransform &result) const
void Apply (const i2d::CAffine2d &transform)
void ApplyLeft (const i2d::CAffine2d &transform)
i2d::CAffine2d & operator= (const i2d::CAffine2d &transform)
Public Member Functions inherited from i2d::CAffine2d
CAffine2d ()
Constructor, parameters will be not initialized.
CAffine2d (const CAffine2d &transform)
Copy constructor, transformation data will be copied from the input object.
CAffine2d (const CMatrix2d &deform, const CVector2d &translation=CVector2d(0.0, 0.0))
Constructs a transform using specified deformation matrix and translation.
CAffine2d (const CVector2d &translation)
Constructs a transform with translation only.
const CVector2d & GetTranslation () const
Get translation part of this affine transformation.
void SetTranslation (const CVector2d &translation)
Set translation part of this affine transformation.
const CMatrix2d & GetDeformMatrix () const
Get rotation, skew and scale part of this affine transformation.
void SetDeformMatrix (const CMatrix2d &deform)
Set rotation, skew and scale part of this affine transformation.
CVector2d & GetTranslationRef ()
Get internal reference to the translation vector.
CMatrix2d & GetDeformMatrixRef ()
Get internal reference to the transformation matrix.
void Reset ()
Set to identity transformation.
void Reset (const CVector2d &translation)
Set this transformation to translation.
void Reset (const CVector2d &translation, double angle, double scale=1.0)
Set this transformation to a given translation, rotation and scaling.
void Reset (const CVector2d &translation, double angle, const CVector2d &scale)
Set this transformation to a given translation, rotation and both axis scaling.
CVector2d GetApply (const CVector2d &position) const
Calculate transformed position.
void GetApply (const CVector2d &position, CVector2d &result) const
Get position after this transformation.
CVector2d GetApplyToDelta (const CVector2d &delta) const
Get difference vector after this transformation.
void GetApplyToDelta (const CVector2d &delta, CVector2d &result) const
Get vector after this transformation.
CAffine2d GetApply (const CAffine2d &transform) const
Get combined transformation.
void GetApply (const CAffine2d &transform, CAffine2d &result) const
Get combined transformation.
void Apply (const CAffine2d &transform)
Combine this transformation with another transformation.
void ApplyLeft (const CAffine2d &transform)
Combine this transformation with another transformation on the left side.
CVector2d GetInvertedApply (const CVector2d &position) const
Inverted operation to GetApply().
bool GetInvertedApply (const CVector2d &position, CVector2d &result) const
Inverted operation to GetApply().
CAffine2d GetTranslated (const CVector2d &delta) const
Get some transformation combined with translation.
void GetTranslated (const CVector2d &delta, CAffine2d &result) const
Get some transformation combined with translation.
void Translate (const CVector2d &delta)
Combine this transformation with translation.
CAffine2d GetInverted () const
Get inverted transformation.
bool GetInverted (CAffine2d &result) const
Get inverted transformation.
bool Serialize (iser::IArchive &archive)
Serialize transformation parameters into/from archive.
bool operator== (const CAffine2d &transform) const
bool operator!= (const CAffine2d &transform) const
CAffine2d & operator= (const CAffine2d &transform)
Protected Member Functions
void CalculateInvert ()
Additional Inherited Members
Static Public Member Functions inherited from i2d::CAffine2d
static const CAffine2d & GetIdentity ()
Detailed Description
Definition at line 12 of file CScreenTransform.h.
Member Typedef Documentation
typedef i2d::CAffine2d iview::CScreenTransform::BaseClass
Definition at line 15 of file CScreenTransform.h.
Constructor & Destructor Documentation
iview::CScreenTransform::CScreenTransform () inline
Default constructor.
Note, that members will be not initialize.
Definition at line 67 of file CScreenTransform.h.
iview::CScreenTransform::CScreenTransform (const CScreenTransform & transform) inline
Copy constructor.
Definition at line 72 of file CScreenTransform.h.
iview::CScreenTransform::CScreenTransform (const i2d::CAffine2d & transform) inline
Constructs CScreenTransform using i2d::CAffine2d object.
Definition at line 79 of file CScreenTransform.h.
References CalculateInvert().
Member Function Documentation
void iview::CScreenTransform::Apply (const i2d::CAffine2d & transform) inline
Definition at line 140 of file CScreenTransform.h.
References i2d::CAffine2d::Apply(), and CalculateInvert().
void iview::CScreenTransform::ApplyLeft (const i2d::CAffine2d & transform)
void iview::CScreenTransform::CalculateInvert () inline protected
Definition at line 158 of file CScreenTransform.h.
References i2d::CAffine2d::GetInverted().
Referenced by Apply(), CScreenTransform(), operator=(), and Reset().
void iview::CScreenTransform::GetApply (const i2d::CAffine2d & transform, CScreenTransform & result) const
Referenced by GetScreenPosition().
i2d::CVector2d iview::CScreenTransform::GetClientPosition (istd::CIndex2d position) const inline
Return position of point in logical coordinates.
Definition at line 86 of file CScreenTransform.h.
References i2d::CAffine2d::GetApply(), istd::CIndex2d::GetX(), and istd::CIndex2d::GetY().
const i2d::CAffine2d & iview::CScreenTransform::GetInverted () const inline
Return reference to invert transformation.
Definition at line 164 of file CScreenTransform.h.
istd::CIndex2d iview::CScreenTransform::GetScreenPosition (const i2d::CVector2d & position) const inline
Return position of point in screen coordinates.
Definition at line 97 of file CScreenTransform.h.
References GetApply(), i2d::CVector2d::GetX(), and i2d::CVector2d::GetY().
i2d::CAffine2d & iview::CScreenTransform::operator= (const i2d::CAffine2d & transform) inline
Definition at line 148 of file CScreenTransform.h.
References CalculateInvert(), and i2d::CAffine2d::operator=().
void iview::CScreenTransform::Reset () inline
Definition at line 108 of file CScreenTransform.h.
References CalculateInvert(), and i2d::CAffine2d::Reset().
void iview::CScreenTransform::Reset (const i2d::CVector2d & position) inline
Definition at line 116 of file CScreenTransform.h.
References CalculateInvert(), and i2d::CAffine2d::Reset().
void iview::CScreenTransform::Reset (const i2d::CVector2d & position, double angle, double scale = 1.0) inline
Definition at line 124 of file CScreenTransform.h.
References CalculateInvert(), and i2d::CAffine2d::Reset().
void iview::CScreenTransform::Reset (const i2d::CVector2d & position, double angle, const i2d::CVector2d & scale) inline
Definition at line 132 of file CScreenTransform.h.
References CalculateInvert(), and i2d::CAffine2d::Reset().
The documentation for this class was generated from the following file:
Include/iview/CScreenTransform.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy