iview::CViewBase Class Reference
iview::CViewBase Class Reference
#include <CViewBase.h>
Public Types
enum ZoomMode {
ZM_RESET, ZM_ZOOM_IN, ZM_ZOOM_OUT, ZM_FIT,
ZM_FIT_COVER, ZM_FIT_UNPROP, ZM_FIT_H, ZM_FIT_V,
ZM_FIT_BACKGROUND
}
typedef ILogicalView BaseClass
Public Member Functions
CViewBase ()
virtual ~CViewBase ()
virtual void SetZoom (ZoomMode zoom)
Set zoom.
virtual void SetEditMode (int mode)
Set edit mode.
virtual void UpdateAllShapes (int changeFlag)
Inform all shapes about changes.
virtual void SetScreenPosition (const i2d::CVector2d &client, istd::CIndex2d screen)
It sets position to become transformation of client point to specified screen position.
virtual const i2d::CRectangle & GetFitArea () const
Get area will be used to automatic fit the zoom to view size.
virtual void SetFitArea (const i2d::CRectangle &area)
Set area will be used to fit in some zoom modes.
virtual void SetViewDraggable (bool state=true)
Turn on/off possibility to move whole view transform.
virtual void SetMultiselectable (bool state=true)
Turn on/off possibility to select more shapes using control keys.
virtual void SetDraggable (bool state=true)
Turn on/off possibility to move more selected shapes, when one is moved.
virtual void AddViewEventObserver (iview::IViewEventObserver *listenerPtr)
Adds handler to catch view events.
virtual void RemoveViewEventObserver (iview::IViewEventObserver *listenerPtr)
Removes handler to catch view events.
virtual void InsertDefaultLayers ()
Insert default layers, when there is no one user layer.
IInteractiveShape * GetMouseShapePtr () const
Get shape under mouse pointer.
virtual const i2d::CAffine2d & GetLogToViewTransform () const
Get logical units to view transformation.
virtual void SetLogToViewTransform (const i2d::CAffine2d &transform)
Set logical to view units transformation.
virtual const
iview::CScreenTransform & GetLogToScreenTransform () const
Get a direct transformation from logical units to screen pixels.
virtual void Update ()
Updates all invalidates shapes.
virtual bool IsViewDraggable () const
Check if is draggable mode.
virtual bool IsMultiselectable () const
Check, if it is possible to select more than one shape.
virtual int InsertLayer (ILayer *layerPtr, int index=-1, int layerType=LT_NONE)
Insert layer to view.
virtual int GetLayerIndex (const ILayer &layer) const
Get index of layer.
virtual void RemoveLayer (int index)
Remove layer from view.
virtual int GetLayersCount () const
Get count of layer in this view.
virtual ILayer & GetLayer (int index) const
Get layer with the given index.
virtual void ConnectShape (IShape *shapePtr, int layerIndex=-1)
Connect shape object to view.
virtual void ConnectBackgroundShape (iview::IShape *shapePtr)
Connect shape to default background layer.
virtual void ConnectInactiveShape (iview::IShape *shapePtr)
Connect shape to default inactive layer.
virtual void ConnectActiveShape (iview::IInteractiveShape *shapePtr)
Connect shape to default active layer.
virtual ISelectableLayer * GetFocusedLayerPtr () const
Get focused layer.
virtual void OnShapeFocused (IInteractiveShape *shapePtr, ISelectableLayer *layerPtr)
Called when shape in layer get focus.
virtual void OnShapeDefocused (IInteractiveShape *shapePtr, ISelectableLayer *layerPtr)
Called when shape in layer loose focus.
virtual void OnLayerInvalidated (const ILayer &layer, const i2d::CRect &prevArea, const i2d::CRect &newArea)
Inform that layer was invalidated.
virtual int GetSelectedShapesCount () const
Get count of selected shapes.
virtual void InsertSelectedShapes (SelectedShapes &result) const
Get set of selected shapes.
virtual void DeselectAllShapes ()
Set all shapes to be deselected.
virtual int GetKeysState () const
Get state of system keys.
virtual int GetEditMode () const
Get actual edit mode.
virtual TouchState IsTouched (istd::CIndex2d position) const
Check, if any shape is touched.
virtual void SetTransform (const i2d::CAffine2d &transform)
Set a screen transformation.
virtual void UpdateMousePointer ()
Update mouse pointer.
virtual bool OnMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag)
It is called, when mouse button is pushed down or up on this object.
virtual bool OnMouseMove (istd::CIndex2d position)
It is called, when mouse is moved.
virtual IDisplay * GetParentDisplayPtr () const
Get parent object of this display.
virtual const
iview::CScreenTransform & GetTransform () const
Return a screen transformation.
virtual i2d::CRect GetBoundingBox () const
Get bounding box of all object in this display.
virtual const IColorShema & GetColorShema () const
Get color shema.
virtual void OnAreaInvalidated (const i2d::CRect &prevArea, const i2d::CRect &newArea)
Invalidate display area.
virtual void OnChangeShape (IShape *shapePtr)
Invalidate a shape.
virtual void DisconnectShape (IShape *shapePtr)
Disconnect shape object from view.
virtual void OnShapeSelected (IInteractiveShape &shape, bool state=true)
It is called after change shape selection state.
virtual bool IsDraggable () const
Check if drag is enabled.
virtual void BeginDrag (const i2d::CVector2d &reference)
Called before dragging is begin.
virtual void SetDragPosition (const i2d::CVector2d &position)
Set new drag position.
virtual void EndDrag ()
Called after dragging.
virtual const IColorShema & GetDefaultColorShema () const =0
Protected Types
typedef std::vector< ILayer * > Layers
Protected Member Functions
virtual void DrawLayers (QPainter &drawContext, int firstLayer, int lastLayer)
Draw Background layer.
int GetLastBackgroundLayerIndex ()
Get last background layer index.
void SetLastBackgroundLayerIndex (int index)
int GetBackgroundLayerIndex () const
Get index of default background layer.
int GetInactiveLayerIndex () const
Get index of default inactive layer.
int GetActiveLayerIndex () const
Get index of default active layer.
void CalcInternalTransforms ()
Calculate internal transformations.
virtual bool CanBeMoved () const
This method is internal used to check, if drag mode is allowed.
void DisconnectAllShapes ()
Disconnect all shapes from this view.
virtual void InvalidateBackground ()
Invalidate whole backgroud buffer.
virtual void InvalidateBoundingBox ()
Invalidate bounding box.
virtual void CalcBoundingBox () const
Calculate bounding box of all shapes.
virtual MousePointerMode CalcMousePointer (istd::CIndex2d position) const
virtual void InvalidateMouseShape ()
Invalidate stored shape under mouse pointer.
virtual void CalcMouseShape () const
Calc shape under mouse pointer.
virtual bool IsBackgroundBufferValid () const
Check if background buffer is valid.
virtual void SetBackgroundBufferValid (bool state=true)
Set validate flag of background buffer.
const i2d::CRect & GetInvalidatedBox () const
Get bounding box of all invalidated rectangles.
void InvalidateBox (const i2d::CRect &rect)
Invalidate rectangle screen area.
void ResetInvalidatedBox ()
Reset invalidated box.
void SetKeysState (int state)
Set state of keys.
const Layers & GetLayers () const
Layers & GetLayers ()
virtual void SetMousePointer (MousePointerMode mode)=0
Set mouse pointer.
virtual void UpdateRectArea (const i2d::CRect &rect)=0
Start updating specified rectangle area.
Detailed Description
Definition at line 31 of file CViewBase.h.
Member Typedef Documentation
typedef ILogicalView iview::CViewBase::BaseClass
Reimplemented from iview::IShapeView.
Reimplemented in iview::CConsoleWidget, and iview::CCalibratedViewBase.
Definition at line 37 of file CViewBase.h.
typedef std::vector<ILayer*> iview::CViewBase::Layers [protected]
Definition at line 187 of file CViewBase.h.
Member Enumeration Documentation
enum iview::CViewBase::ZoomMode
Enumerator:
ZM_RESET
ZM_ZOOM_IN
ZM_ZOOM_OUT
ZM_FIT
ZM_FIT_COVER
ZM_FIT_UNPROP
ZM_FIT_H
ZM_FIT_V
ZM_FIT_BACKGROUND
Definition at line 39 of file CViewBase.h.
Constructor & Destructor Documentation
iview::CViewBase::CViewBase ()
virtual iview::CViewBase::~CViewBase () [virtual]
Member Function Documentation
virtual void iview::CViewBase::AddViewEventObserver (iview::IViewEventObserver * listenerPtr) [virtual]
Adds handler to catch view events.
virtual void iview::CViewBase::BeginDrag (const i2d::CVector2d & reference) [virtual]
Called before dragging is begin.
It set also reference value for dragging position.
Implements iview::IDraggable.
virtual void iview::CViewBase::CalcBoundingBox () const [protected, virtual]
Calculate bounding box of all shapes.
Referenced by GetBoundingBox().
void iview::CViewBase::CalcInternalTransforms () [protected]
Calculate internal transformations.
virtual MousePointerMode iview::CViewBase::CalcMousePointer (istd::CIndex2d position) const [protected, virtual]
virtual void iview::CViewBase::CalcMouseShape () const [protected, virtual]
Calc shape under mouse pointer.
Referenced by GetMouseShapePtr().
virtual bool iview::CViewBase::CanBeMoved () const [protected, virtual]
This method is internal used to check, if drag mode is allowed.
Normally it return IsViewDraggable(), but in derived class you can change its implementation to avoid dragging.
virtual void iview::CViewBase::ConnectActiveShape (iview::IInteractiveShape * shapePtr) [virtual]
Connect shape to default active layer.
Implements iview::IShapeView.
virtual void iview::CViewBase::ConnectBackgroundShape (iview::IShape * shapePtr) [virtual]
Connect shape to default background layer.
Implements iview::IShapeView.
virtual void iview::CViewBase::ConnectInactiveShape (iview::IShape * shapePtr) [virtual]
Connect shape to default inactive layer.
Implements iview::IShapeView.
virtual void iview::CViewBase::ConnectShape (IShape * shapePtr, int layerIndex = -1) [virtual]
Connect shape object to view.
Parameters:
shape a shape object.
active if true, shape will be active, if false it will be only visible.
Returns:
true, if it was possible to connect this shape.
Implements iview::IShapeView.
virtual void iview::CViewBase::DeselectAllShapes () [virtual]
Set all shapes to be deselected.
Implements iview::ISelectable.
void iview::CViewBase::DisconnectAllShapes () [protected]
Disconnect all shapes from this view.
virtual void iview::CViewBase::DisconnectShape (IShape * shapePtr) [virtual]
Disconnect shape object from view.
This shape had to be connected using ConnectShape.
Returns:
true, if it was possible to disconnect this shape.
Implements iview::IShapeObserver.
virtual void iview::CViewBase::DrawLayers (QPainter & drawContext, int firstLayer, int lastLayer) [protected, virtual]
Draw Background layer.
Standard implementation draws background shape, but it is also possible to use this method to display additional visual elements like a grid or rulers.
virtual void iview::CViewBase::EndDrag () [virtual]
Called after dragging.
Implements iview::IDraggable.
int iview::CViewBase::GetActiveLayerIndex () const [inline, protected]
Get index of default active layer.
Definition at line 527 of file CViewBase.h.
int iview::CViewBase::GetBackgroundLayerIndex () const [inline, protected]
Get index of default background layer.
Definition at line 515 of file CViewBase.h.
i2d::CRect iview::CViewBase::GetBoundingBox () const [inline, virtual]
Get bounding box of all object in this display.
Implements iview::IDisplay.
Definition at line 469 of file CViewBase.h.
References CalcBoundingBox().
const IColorShema & iview::CViewBase::GetColorShema () const [inline, virtual]
Get color shema.
Implements iview::IDisplay.
Definition at line 479 of file CViewBase.h.
References GetDefaultColorShema().
virtual const IColorShema& iview::CViewBase::GetDefaultColorShema () const [pure virtual]
Implemented in iview::TViewImpl< iview::CCalibratedViewBase >.
Referenced by GetColorShema().
virtual int iview::CViewBase::GetEditMode () const [virtual]
Get actual edit mode.
Implements iview::ISelectable.
const i2d::CRectangle & iview::CViewBase::GetFitArea () const [inline, virtual]
Get area will be used to automatic fit the zoom to view size.
See also:
SetZoom(ZoomMode)
Definition at line 365 of file CViewBase.h.
virtual ISelectableLayer* iview::CViewBase::GetFocusedLayerPtr () const [virtual]
Get focused layer.
Implements iview::IShapeView.
int iview::CViewBase::GetInactiveLayerIndex () const [inline, protected]
Get index of default inactive layer.
Definition at line 521 of file CViewBase.h.
const i2d::CRect & iview::CViewBase::GetInvalidatedBox () const [inline, protected]
Get bounding box of all invalidated rectangles.
Definition at line 550 of file CViewBase.h.
int iview::CViewBase::GetKeysState () const [inline, virtual]
Get state of system keys.
Implements iview::ISelectable.
Definition at line 487 of file CViewBase.h.
int iview::CViewBase::GetLastBackgroundLayerIndex () [inline, protected]
Get last background layer index.
Definition at line 503 of file CViewBase.h.
ILayer & iview::CViewBase::GetLayer (int index) const [inline, virtual]
Get layer with the given index.
Implements iview::IShapeView.
Definition at line 439 of file CViewBase.h.
References GetLayersCount(), I_ASSERT, InsertDefaultLayers(), and NULL.
virtual int iview::CViewBase::GetLayerIndex (const ILayer & layer) const [virtual]
Get index of layer.
Returns:
layer index, or -1 if not found.
Implements iview::IShapeView.
const CViewBase::Layers & iview::CViewBase::GetLayers () const [inline, protected]
Definition at line 574 of file CViewBase.h.
CViewBase::Layers & iview::CViewBase::GetLayers () [inline, protected]
Definition at line 580 of file CViewBase.h.
int iview::CViewBase::GetLayersCount () const [inline, virtual]
Get count of layer in this view.
Implements iview::IShapeView.
Definition at line 433 of file CViewBase.h.
Referenced by GetLayer().
const iview::CScreenTransform & iview::CViewBase::GetLogToScreenTransform () const [inline, virtual]
Get a direct transformation from logical units to screen pixels.
Implements iview::ILogicalCoords.
Definition at line 413 of file CViewBase.h.
const i2d::CAffine2d & iview::CViewBase::GetLogToViewTransform () const [inline, virtual]
Get logical units to view transformation.
This transformation converts logical units to view coordinate system. Please note, that it is only affine transformation, not a calibration. You can use it as a calibration only, when linear transformation is enough. To get transformation to convert logical units to screen pixel, use GetLogToScreenTransform().
Implements iview::ILogicalCoords.
Definition at line 407 of file CViewBase.h.
IInteractiveShape * iview::CViewBase::GetMouseShapePtr () const [inline]
Get shape under mouse pointer.
Returns:
shape under mouse pointer, or NULL if there is no shape.
Definition at line 395 of file CViewBase.h.
References CalcMouseShape().
IDisplay * iview::CViewBase::GetParentDisplayPtr () const [inline, virtual]
Get parent object of this display.
If this display is root, it returns NULL.
Implements iview::IDisplay.
Definition at line 457 of file CViewBase.h.
References NULL.
virtual int iview::CViewBase::GetSelectedShapesCount () const [virtual]
Get count of selected shapes.
Implements iview::ISelectable.
const iview::CScreenTransform & iview::CViewBase::GetTransform () const [inline, virtual]
Return a screen transformation.
This transformation converts view units to screen units.
See also:
iview::ILogicalView::GetLogToViewTransform(), iview::ILogicalView::GetLogToScreenTransform()
Implements iview::IDisplay.
Definition at line 463 of file CViewBase.h.
virtual void iview::CViewBase::InsertDefaultLayers () [virtual]
Insert default layers, when there is no one user layer.
Reimplemented in iview::CCalibratedViewBase.
Referenced by GetLayer().
virtual int iview::CViewBase::InsertLayer (ILayer * layerPtr, int index = -1, int layerType = LT_NONE) [virtual]
Insert layer to view.
Parameters:
layerPtr pointer to inserted layer.
index index of inserted layer. If equals -1, layer will be inserted after layst existing layer.
layerType used to set standard layers.
See also:
iview::IShapeView::LayerType
Returns:
index of this layer.
Implements iview::IShapeView.
Reimplemented in iview::CCalibratedViewBase.
virtual void iview::CViewBase::InsertSelectedShapes (SelectedShapes & result) const [virtual]
Get set of selected shapes.
Implements iview::ISelectable.
virtual void iview::CViewBase::InvalidateBackground () [protected, virtual]
Invalidate whole backgroud buffer.
By next call Update() backgroud buffer will be full repainted.
Referenced by iview::CCalibratedViewBase::SetCalibrationPtr(), and iview::CCalibratedViewBase::SetGridVisible().
virtual void iview::CViewBase::InvalidateBoundingBox () [protected, virtual]
Invalidate bounding box.
void iview::CViewBase::InvalidateBox (const i2d::CRect & rect) [inline, protected]
Invalidate rectangle screen area.
It added this area to other invalidated areas.
Definition at line 556 of file CViewBase.h.
References i2d::CRect::Union().
virtual void iview::CViewBase::InvalidateMouseShape () [protected, virtual]
Invalidate stored shape under mouse pointer.
bool iview::CViewBase::IsBackgroundBufferValid () const [inline, protected, virtual]
Check if background buffer is valid.
Definition at line 533 of file CViewBase.h.
bool iview::CViewBase::IsDraggable () const [inline, virtual]
Check if drag is enabled.
Implements iview::IDraggable.
Definition at line 495 of file CViewBase.h.
bool iview::CViewBase::IsMultiselectable () const [inline, virtual]
Check, if it is possible to select more than one shape.
Implements iview::IShapeView.
Definition at line 427 of file CViewBase.h.
virtual TouchState iview::CViewBase::IsTouched (istd::CIndex2d position) const [virtual]
Check, if any shape is touched.
When shape is touched, it return also pointer to this shape.
Returns:
touch state for the shape, or iview::IInteractiveShape::TS_NONE, when nothing found.
Implements iview::ITouchable.
bool iview::CViewBase::IsViewDraggable () const [inline, virtual]
Check if is draggable mode.
If this function return true, user can move a view by dragging.
Implements iview::IShapeView.
Definition at line 421 of file CViewBase.h.
virtual void iview::CViewBase::OnAreaInvalidated (const i2d::CRect & prevArea, const i2d::CRect & newArea) [virtual]
Invalidate display area.
Parameters:
prevArea previous area used to display object.
newArea new area used to display object.
Implements iview::IDisplay.
virtual void iview::CViewBase::OnChangeShape (IShape * shapePtr) [virtual]
Invalidate a shape.
When you call Update, all invalidated shapes will be repainted.
Returns:
true, if it was possible to invalidate this shape.
Implements iview::IShapeObserver.
virtual void iview::CViewBase::OnLayerInvalidated (const ILayer & layer, const i2d::CRect & prevArea, const i2d::CRect & newArea) [virtual]
Inform that layer was invalidated.
Implements iview::IShapeView.
virtual bool iview::CViewBase::OnMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag) [virtual]
It is called, when mouse button is pushed down or up on this object.
Parameters:
position - position of mouse pointer on client area (picture coords).
downFlag - true, if mouse button is pushed down, false if pushed up.
Returns:
true if this shape should get focus to catch all mouse movements.
Implements iview::IMouseActionObserver.
virtual bool iview::CViewBase::OnMouseMove (istd::CIndex2d position) [virtual]
It is called, when mouse is moved.
Only objects with focus receive this event.
Parameters:
position - position of mouse pointer on client area (picture coords).
Returns:
true if this shape should hold focus to catch longer all mouse movements.
Implements iview::IMouseActionObserver.
virtual void iview::CViewBase::OnShapeDefocused (IInteractiveShape * shapePtr, ISelectableLayer * layerPtr) [virtual]
Called when shape in layer loose focus.
Implements iview::IShapeView.
virtual void iview::CViewBase::OnShapeFocused (IInteractiveShape * shapePtr, ISelectableLayer * layerPtr) [virtual]
Called when shape in layer get focus.
Implements iview::IShapeView.
virtual void iview::CViewBase::OnShapeSelected (IInteractiveShape & shape, bool state = true) [virtual]
It is called after change shape selection state.
Implements iview::ISelectable.
virtual void iview::CViewBase::RemoveLayer (int index) [virtual]
Remove layer from view.
Implements iview::IShapeView.
Reimplemented in iview::CCalibratedViewBase.
virtual void iview::CViewBase::RemoveViewEventObserver (iview::IViewEventObserver * listenerPtr) [virtual]
Removes handler to catch view events.
void iview::CViewBase::ResetInvalidatedBox () [inline, protected]
Reset invalidated box.
Definition at line 562 of file CViewBase.h.
References i2d::CRect::Reset().
void iview::CViewBase::SetBackgroundBufferValid (bool state = true) [inline, protected, virtual]
Set validate flag of background buffer.
Definition at line 539 of file CViewBase.h.
References iview::IDisplay::GetClientRect().
Referenced by iview::CCalibratedViewBase::SetGridInMm(), and iview::CCalibratedViewBase::SetMinGridDistance().
void iview::CViewBase::SetDraggable (bool state = true) [inline, virtual]
Turn on/off possibility to move more selected shapes, when one is moved.
Definition at line 389 of file CViewBase.h.
virtual void iview::CViewBase::SetDragPosition (const i2d::CVector2d & position) [virtual]
Set new drag position.
It must be enclosed using BeginDrag() and EndDrag() methods.
Implements iview::IDraggable.
virtual void iview::CViewBase::SetEditMode (int mode) [virtual]
Set edit mode.
Implements iview::IShapeView.
void iview::CViewBase::SetFitArea (const i2d::CRectangle & area) [inline, virtual]
Set area will be used to fit in some zoom modes.
See also:
SetZoom(ZoomMode)
Definition at line 371 of file CViewBase.h.
void iview::CViewBase::SetKeysState (int state) [inline, protected]
Set state of keys.
Definition at line 568 of file CViewBase.h.
void iview::CViewBase::SetLastBackgroundLayerIndex (int index) [inline, protected]
Definition at line 509 of file CViewBase.h.
virtual void iview::CViewBase::SetLogToViewTransform (const i2d::CAffine2d & transform) [virtual]
Set logical to view units transformation.
Implements iview::ILogicalView.
virtual void iview::CViewBase::SetMousePointer (MousePointerMode mode) [protected, pure virtual]
Set mouse pointer.
You have to implement it in your iview::CViewBase implementations.
Implemented in iview::CConsoleWidget.
void iview::CViewBase::SetMultiselectable (bool state = true) [inline, virtual]
Turn on/off possibility to select more shapes using control keys.
Definition at line 383 of file CViewBase.h.
virtual void iview::CViewBase::SetScreenPosition (const i2d::CVector2d & client, istd::CIndex2d screen) [virtual]
It sets position to become transformation of client point to specified screen position.
virtual void iview::CViewBase::SetTransform (const i2d::CAffine2d & transform) [virtual]
Set a screen transformation.
See also:
GetTransform()
Implements iview::IShapeView.
void iview::CViewBase::SetViewDraggable (bool state = true) [inline, virtual]
Turn on/off possibility to move whole view transform.
Definition at line 377 of file CViewBase.h.
virtual void iview::CViewBase::SetZoom (ZoomMode zoom) [virtual]
Set zoom.
virtual void iview::CViewBase::Update () [virtual]
Updates all invalidates shapes.
Implements iview::IShapeView.
virtual void iview::CViewBase::UpdateAllShapes (int changeFlag) [virtual]
Inform all shapes about changes.
Reimplemented in iview::CCalibratedViewBase.
virtual void iview::CViewBase::UpdateMousePointer () [virtual]
Update mouse pointer.
Implements iview::IShapeView.
virtual void iview::CViewBase::UpdateRectArea (const i2d::CRect & rect) [protected, pure virtual]
Start updating specified rectangle area.
Implemented in iview::CConsoleWidget.
The documentation for this class was generated from the following file:
Include/iview/CViewBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy