ACF: iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject > Class Template Reference
iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject > Class Template Reference
#include <TMorphLockedProducerBase.h>
Public Member Functions
TMorphLockedProducerBase ()
double GetMaxCumulatedWeight () const
void SetMaxCumulatedWeight (double value)
virtual const CacheObject * ProduceLockedObject (const Key &key)
Begin of accessing to cached element.
virtual void UnlockObject (const CacheObject *objectPtr)
End of accessing to cached element.
Protected Member Functions
void CleanElementList ()
Remove elements from list if cumulated weight is above defined maximum.
virtual double CalcCacheObject (const Key &key, const SourceObject &source, CacheObject &cache) const =0
Calculate cache object from source object.
virtual const SourceObject * LockSourceObject (const Key &key)=0
virtual void UnlockSourceObject (const Key &key, const SourceObject *sourcePtr)=0
Detailed Description
template<class Key, class CacheObject, class SourceObject>
class iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >
Definition at line 19 of file TMorphLockedProducerBase.h.
Constructor & Destructor Documentation
template<class Key , class CacheObject , class SourceObject > iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::TMorphLockedProducerBase () [inline]
Definition at line 76 of file TMorphLockedProducerBase.h.
Member Function Documentation
template<class Key , class CacheObject , class SourceObject > virtual double iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::CalcCacheObject (const Key & key, const SourceObject & source, CacheObject & cache) const [protected, pure virtual]
Calculate cache object from source object.
Returns:
positive weight value if succeded of negative value (-1) if failed.
Referenced by iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::ProduceLockedObject().
template<class Key , class CacheObject , class SourceObject > void iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::CleanElementList () [inline, protected]
Remove elements from list if cumulated weight is above defined maximum.
Definition at line 165 of file TMorphLockedProducerBase.h.
Referenced by iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::ProduceLockedObject(), and iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::SetMaxCumulatedWeight().
template<class Key , class CacheObject , class SourceObject > double iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::GetMaxCumulatedWeight () const [inline]
Definition at line 83 of file TMorphLockedProducerBase.h.
template<class Key , class CacheObject , class SourceObject > virtual const SourceObject* iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::LockSourceObject (const Key & key) [protected, pure virtual]
Referenced by iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::ProduceLockedObject().
template<class Key , class CacheObject , class SourceObject > const CacheObject * iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::ProduceLockedObject (const Key & key) [inline, virtual]
Begin of accessing to cached element.
Returns:
cached object, if it was possible to produce it for specified key.
Implements iproc::TILockedProducer< Key, CacheObject >.
Definition at line 101 of file TMorphLockedProducerBase.h.
References iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::CalcCacheObject(), iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::CleanElementList(), istd::TPointerBase< Type >::IsValid(), iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::LockSourceObject(), NULL, and iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::UnlockSourceObject().
template<class Key , class CacheObject , class SourceObject > void iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::SetMaxCumulatedWeight (double value) [inline]
Definition at line 90 of file TMorphLockedProducerBase.h.
References iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::CleanElementList().
template<class Key , class CacheObject , class SourceObject > void iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::UnlockObject (const CacheObject * objectPtr) [inline, virtual]
End of accessing to cached element.
Implements iproc::TILockedProducer< Key, CacheObject >.
Definition at line 146 of file TMorphLockedProducerBase.h.
template<class Key , class CacheObject , class SourceObject > virtual void iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::UnlockSourceObject (const Key & key, const SourceObject * sourcePtr) [protected, pure virtual]
Referenced by iproc::TMorphLockedProducerBase< Key, CacheObject, SourceObject >::ProduceLockedObject().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iproc/TMorphLockedProducerBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy