icomp::TAttribute< Value > Class Template Reference
icomp::TAttribute< Value > Class Template Reference
Template implementation of single component attribute.
#include <TAttribute.h>
Public Types
enum DefaultAttributeFlags { DAF_OBLIGATORY = IAttributeStaticInfo::AF_OBLIGATORY | IAttributeStaticInfo::AF_NULLABLE | IAttributeStaticInfo::AF_SINGLE | IAttributeStaticInfo::AF_VALUE, DAF_OPTIONAL = IAttributeStaticInfo::AF_NULLABLE | IAttributeStaticInfo::AF_SINGLE | IAttributeStaticInfo::AF_VALUE }
typedef Value ValueType
typedef
iser::TCopySerializedWrap
< iser::IObject > BaseClass
Public Types inherited from iser::TCopySerializedWrap< iser::IObject >
typedef
istd::TUpdateManagerWrap
< iser::IObject > BaseClass
Public Types inherited from istd::TUpdateManagerWrap< iser::IObject >
typedef iser::IObject BaseClass
Public Types inherited from istd::IChangeable
enum ChangeFlags {
CF_ACF_INTERNAL = 1 << 0, CF_MODEL = 1 << 1, CF_ABORTED = 1 << 2, CF_DELEGATED = 1 << 3,
CF_NO_UNDO = 1 << 5
}
enum SupportedOperations {
SO_NONE = 0, SO_OBSERVE = 1, SO_COPY = 2, SO_CLONE = 4,
SO_COMPARE = 8
}
Flags for supported operations.
enum CompatibilityMode { CM_STRICT, CM_WITHOUT_REFS, CM_WITH_REFS, CM_CONVERT }
Control how relationship betweeen objects are interpreted.
Public Member Functions
TAttribute ()
TAttribute (const TAttribute &attribute)
TAttribute (const Value &value)
virtual const Value & GetValue () const
virtual void SetValue (const Value &value)
virtual QByteArray GetFactoryId () const
virtual bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
template<>
QByteArray GetTypeName ()
template<>
QByteArray GetTypeName ()
template<>
QByteArray GetTypeName ()
template<>
QByteArray GetTypeName ()
template<>
QByteArray GetTypeName ()
Public Member Functions inherited from iser::TCopySerializedWrap< iser::IObject >
virtual bool CopyFrom (const istd::IChangeable &object, istd::IChangeable::CompatibilityMode mode=BaseClass::CM_WITHOUT_REFS)
virtual bool IsEqual (const istd::IChangeable &object) const
Public Member Functions inherited from istd::TUpdateManagerWrap< iser::IObject >
TUpdateManagerWrap ()
virtual void BeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
virtual void EndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Public Member Functions inherited from iser::ISerializable
virtual quint32 GetMinimalVersion (int versionId) const
Get minimal needed version to correct storing of this data.
Public Member Functions inherited from istd::IChangeable
virtual int GetSupportedOperations () const
Get set of flags for supported operations.
virtual IChangeable * CloneMe (CompatibilityMode mode=CM_WITHOUT_REFS) const
Make a copy of this object.
virtual bool ResetData (CompatibilityMode mode=CM_WITHOUT_REFS)
Reset data to its default state.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Static Public Member Functions
static QByteArray GetTypeName ()
Protected Attributes
Value m_value
Additional Inherited Members
Protected Member Functions inherited from istd::IChangeable
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for begin change event.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for end change event.
Detailed Description
template<typename Value>
class icomp::TAttribute< Value >
Template implementation of single component attribute.
Definition at line 25 of file TAttribute.h.
Member Typedef Documentation
template<typename Value> typedef iser::TCopySerializedWrap<iser::IObject> icomp::TAttribute< Value >::BaseClass
Definition at line 29 of file TAttribute.h.
template<typename Value> typedef Value icomp::TAttribute< Value >::ValueType
Definition at line 28 of file TAttribute.h.
Member Enumeration Documentation
template<typename Value> enum icomp::TAttribute::DefaultAttributeFlags
Enumerator
DAF_OBLIGATORY
DAF_OPTIONAL
Definition at line 31 of file TAttribute.h.
Constructor & Destructor Documentation
template<typename Value > icomp::TAttribute< Value >::TAttribute ()
Definition at line 62 of file TAttribute.h.
template<typename Value > icomp::TAttribute< Value >::TAttribute (const TAttribute< Value > & attribute)
Definition at line 77 of file TAttribute.h.
template<typename Value> icomp::TAttribute< Value >::TAttribute (const Value & value) explicit
Definition at line 69 of file TAttribute.h.
Member Function Documentation
template<typename Value > QByteArray icomp::TAttribute< Value >::GetFactoryId () const virtual
Reimplemented from iser::IObject.
Reimplemented in icomp::CFactoryAttribute, and icomp::CReferenceAttribute.
Definition at line 101 of file TAttribute.h.
template<typename Value > QByteArray icomp::TAttribute< Value >::GetTypeName () static
Definition at line 129 of file TAttribute.h.
template<> QByteArray icomp::TAttribute< int >::GetTypeName () inline
Definition at line 136 of file TAttribute.h.
template<> QByteArray icomp::TAttribute< double >::GetTypeName () inline
Definition at line 143 of file TAttribute.h.
template<> QByteArray icomp::TAttribute< bool >::GetTypeName () inline
Definition at line 150 of file TAttribute.h.
template<> QByteArray icomp::TAttribute< QString >::GetTypeName () inline
Definition at line 157 of file TAttribute.h.
template<> QByteArray icomp::TAttribute< QByteArray >::GetTypeName () inline
Definition at line 164 of file TAttribute.h.
template<typename Value > const Value & icomp::TAttribute< Value >::GetValue () const virtual
Definition at line 85 of file TAttribute.h.
template<typename Value > bool icomp::TAttribute< Value >::Serialize (iser::IArchive & archive) virtual
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See Also
iser::IArchive
Implements iser::ISerializable.
Definition at line 110 of file TAttribute.h.
References iser::IArchive::BeginTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), NULL, and iser::IArchive::Process().
template<typename Value> void icomp::TAttribute< Value >::SetValue (const Value & value) virtual
Definition at line 92 of file TAttribute.h.
Member Data Documentation
template<typename Value> Value icomp::TAttribute< Value >::m_value protected
Definition at line 55 of file TAttribute.h.
The documentation for this class was generated from the following file:
Include/icomp/TAttribute.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy