iview::CTransformableRectangleCalibrationShape Class Reference
iview::CTransformableRectangleCalibrationShape Class Reference
#include <CTransformableRectangleCalibrationShape.h>
Public Types
typedef CCalibrationShapeBase BaseClass
Public Member Functions
CTransformableRectangleCalibrationShape ()
virtual bool IsEditableRotation ()
Check, if rotation is editable.
virtual void SetEditableRotation (bool state=true)
virtual bool IsEditableWidth ()
Check, if width is editable.
virtual void SetEditableWidth (bool state=true)
virtual bool IsEditableHeight ()
Check, if height is editable.
virtual void SetEditableHeight (bool state=true)
virtual bool IsProportionalScaled () const
Check, if both axis will be scaled proportional.
virtual void SetProportionalScaled (bool state=true)
virtual void InvalidateBoundingBox ()
Invalidate bounding box.
virtual TouchState IsTouched (istd::CIndex2d position) const
Check, if any shape is touched.
virtual void Draw (QPainter &drawContext) const
Draw this shape using draw context.
virtual bool OnAttached (imod::IModel *modelPtr)
This call back function will be called, if an observable object is about to be attached.
virtual bool OnMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag)
It is called, when mouse button is pushed down or up on this object.
virtual bool OnMouseMove (istd::CIndex2d position)
It is called, when mouse is moved.
Protected Types
enum EditNode {
EN_NODE1 = 0, EN_NODE2, EN_NODE3, EN_NODE4,
EN_CENTER, EN_MIDDLE12, EN_MIDDLE23, EN_MIDDLE34,
EN_MIDDLE41, EN_ROTATION1, EN_ROTATION2, EN_LAST = EN_ROTATION2
}
enum MouseMode {
MM_NONE, MM_ROTATION1, MM_ROTATION2, MM_WIDTH1,
MM_WIDTH2, MM_HEIGHT1, MM_HEIGHT2, MM_SIZE1,
MM_SIZE2, MM_SIZE3, MM_SIZE4
}
Protected Member Functions
void CalcNodes (const i2d::CAffine2d &parallTransform) const
void ResetNodes () const
bool AreNodesValid () const
const istd::CIndex2d * GetNodes () const
virtual void EnsureValidNodes () const
i2d::CAffine2d CalcMoveTransform (i2d::CVector2d position, const i2d::CAffine2d &transform)
virtual bool IsTickerTouched (istd::CIndex2d position) const
virtual bool IsFigureTouched (istd::CIndex2d position) const
virtual void DrawTickers (QPainter &drawContext) const
virtual void DrawFigure (QPainter &drawContext) const
bool IsParallTouched (const i2d::CAffine2d &parallTransform, istd::CIndex2d position) const
i2d::CAffine2d CalcScaleTransform (const i2d::CVector2d &center, const i2d::CVector2d &isPos, const i2d::CVector2d &shouldPos)
i2d::CAffine2d CalcSizeTransform (const i2d::CVector2d &center, const i2d::CVector2d &isPos, const i2d::CVector2d &shouldPos)
i2d::CAffine2d CalcRotatedTransform (const i2d::CVector2d &center, const i2d::CVector2d &isPos, const i2d::CVector2d &shouldPos)
virtual void CalcBoundingBox (i2d::CRect &result) const
Calculate bounding box.
virtual void BeginLogDrag (const i2d::CVector2d &reference)
virtual void SetLogDragPosition (const i2d::CVector2d &position)
Protected Attributes
MouseMode m_mouseMode
i2d::CVector2d m_referencePosition
Detailed Description
Definition at line 15 of file CTransformableRectangleCalibrationShape.h.
Member Typedef Documentation
typedef CCalibrationShapeBase iview::CTransformableRectangleCalibrationShape::BaseClass
Reimplemented from iview::CCalibrationShapeBase.
Reimplemented in iview::CPolygonCalibrationShape, iview::TMultiPolylineCalibrationShape< SegmentData >, and iview::CPolylineCalibrationShape.
Definition at line 18 of file CTransformableRectangleCalibrationShape.h.
Member Enumeration Documentation
enum iview::CTransformableRectangleCalibrationShape::EditNode [protected]
Enumerator:
EN_NODE1
EN_NODE2
EN_NODE3
EN_NODE4
EN_CENTER
EN_MIDDLE12
EN_MIDDLE23
EN_MIDDLE34
EN_MIDDLE41
EN_ROTATION1
EN_ROTATION2
EN_LAST
Definition at line 61 of file CTransformableRectangleCalibrationShape.h.
enum iview::CTransformableRectangleCalibrationShape::MouseMode [protected]
Enumerator:
MM_NONE
MM_ROTATION1
MM_ROTATION2
MM_WIDTH1
MM_WIDTH2
MM_HEIGHT1
MM_HEIGHT2
MM_SIZE1
MM_SIZE2
MM_SIZE3
MM_SIZE4
Definition at line 77 of file CTransformableRectangleCalibrationShape.h.
Constructor & Destructor Documentation
iview::CTransformableRectangleCalibrationShape::CTransformableRectangleCalibrationShape ()
Member Function Documentation
bool iview::CTransformableRectangleCalibrationShape::AreNodesValid () const [inline, protected]
Definition at line 201 of file CTransformableRectangleCalibrationShape.h.
virtual void iview::CTransformableRectangleCalibrationShape::BeginLogDrag (const i2d::CVector2d & reference) [protected, virtual]
Implements iview::CInteractiveShapeBase.
Reimplemented in iview::CPolygonCalibrationShape.
virtual void iview::CTransformableRectangleCalibrationShape::CalcBoundingBox (i2d::CRect & result) const [protected, virtual]
Calculate bounding box.
You have to implement this method in your shapes implementations.
Implements iview::CInteractiveShapeBase.
Reimplemented in iview::CPolygonCalibrationShape, and iview::TMultiPolylineCalibrationShape< SegmentData >.
i2d::CAffine2d iview::CTransformableRectangleCalibrationShape::CalcMoveTransform (i2d::CVector2d position, const i2d::CAffine2d & transform) [protected]
void iview::CTransformableRectangleCalibrationShape::CalcNodes (const i2d::CAffine2d & parallTransform) const [protected]
i2d::CAffine2d iview::CTransformableRectangleCalibrationShape::CalcRotatedTransform (const i2d::CVector2d & center, const i2d::CVector2d & isPos, const i2d::CVector2d & shouldPos) [protected]
i2d::CAffine2d iview::CTransformableRectangleCalibrationShape::CalcScaleTransform (const i2d::CVector2d & center, const i2d::CVector2d & isPos, const i2d::CVector2d & shouldPos) [protected]
i2d::CAffine2d iview::CTransformableRectangleCalibrationShape::CalcSizeTransform (const i2d::CVector2d & center, const i2d::CVector2d & isPos, const i2d::CVector2d & shouldPos) [protected]
virtual void iview::CTransformableRectangleCalibrationShape::Draw (QPainter & drawContext) const [virtual]
Draw this shape using draw context.
Implements iview::IVisualizable.
Reimplemented in iview::CPolygonCalibrationShape.
virtual void iview::CTransformableRectangleCalibrationShape::DrawFigure (QPainter & drawContext) const [protected, virtual]
virtual void iview::CTransformableRectangleCalibrationShape::DrawTickers (QPainter & drawContext) const [protected, virtual]
virtual void iview::CTransformableRectangleCalibrationShape::EnsureValidNodes () const [protected, virtual]
Reimplemented in iview::TMultiPolylineCalibrationShape< SegmentData >, and iview::CPolygonCalibrationShape.
Referenced by iview::TMultiPolylineCalibrationShape< SegmentData >::IsTouched().
const istd::CIndex2d * iview::CTransformableRectangleCalibrationShape::GetNodes () const [inline, protected]
Definition at line 208 of file CTransformableRectangleCalibrationShape.h.
virtual void iview::CTransformableRectangleCalibrationShape::InvalidateBoundingBox () [virtual]
Invalidate bounding box.
You can overload this method to provide validation of your internal attributes, because this method is called from Invalidate(int) and OnDisplayChange(int) methods. Please don't forget base method call in your implementations.
Reimplemented from iview::TShapeBase< IInteractiveShape >.
bool iview::CTransformableRectangleCalibrationShape::IsEditableHeight () [inline, virtual]
Check, if height is editable.
Definition at line 171 of file CTransformableRectangleCalibrationShape.h.
bool iview::CTransformableRectangleCalibrationShape::IsEditableRotation () [inline, virtual]
Check, if rotation is editable.
Definition at line 143 of file CTransformableRectangleCalibrationShape.h.
bool iview::CTransformableRectangleCalibrationShape::IsEditableWidth () [inline, virtual]
Check, if width is editable.
Definition at line 157 of file CTransformableRectangleCalibrationShape.h.
virtual bool iview::CTransformableRectangleCalibrationShape::IsFigureTouched (istd::CIndex2d position) const [protected, virtual]
bool iview::CTransformableRectangleCalibrationShape::IsParallTouched (const i2d::CAffine2d & parallTransform, istd::CIndex2d position) const [protected]
Referenced by iview::TMultiPolylineCalibrationShape< SegmentData >::IsTouched().
bool iview::CTransformableRectangleCalibrationShape::IsProportionalScaled () const [inline, virtual]
Check, if both axis will be scaled proportional.
Definition at line 185 of file CTransformableRectangleCalibrationShape.h.
virtual bool iview::CTransformableRectangleCalibrationShape::IsTickerTouched (istd::CIndex2d position) const [protected, virtual]
Reimplemented in iview::CPolygonCalibrationShape, and iview::CPolylineCalibrationShape.
Referenced by iview::TMultiPolylineCalibrationShape< SegmentData >::IsTouched().
virtual TouchState iview::CTransformableRectangleCalibrationShape::IsTouched (istd::CIndex2d position) const [virtual]
Check, if any shape is touched.
When shape is touched, it return also pointer to this shape.
Returns:
touch state for the shape, or iview::IInteractiveShape::TS_NONE, when nothing found.
Implements iview::ITouchable.
Reimplemented in iview::TMultiPolylineCalibrationShape< SegmentData >, and iview::CPolygonCalibrationShape.
virtual bool iview::CTransformableRectangleCalibrationShape::OnAttached (imod::IModel * modelPtr) [virtual]
This call back function will be called, if an observable object is about to be attached.
This function returns a true, if observable object is accepted by the implementation logic of the observer, otherwise the function returns a false.
Reimplemented from iview::CInteractiveShapeBase.
Reimplemented in iview::CPolygonCalibrationShape, iview::TMultiPolylineCalibrationShape< SegmentData >, and iview::CPolylineCalibrationShape.
virtual bool iview::CTransformableRectangleCalibrationShape::OnMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag) [virtual]
It is called, when mouse button is pushed down or up on this object.
Parameters:
position - position of mouse pointer on client area (picture coords).
downFlag - true, if mouse button is pushed down, false if pushed up.
Returns:
true if this shape should get focus to catch all mouse movements.
Reimplemented from iview::CInteractiveShapeBase.
Reimplemented in iview::CPolygonCalibrationShape, iview::TMultiPolylineCalibrationShape< SegmentData >, and iview::CPolylineCalibrationShape.
Referenced by iview::TMultiPolylineCalibrationShape< SegmentData >::OnMouseButton().
virtual bool iview::CTransformableRectangleCalibrationShape::OnMouseMove (istd::CIndex2d position) [virtual]
It is called, when mouse is moved.
Only objects with focus receive this event.
Parameters:
position - position of mouse pointer on client area (picture coords).
Returns:
true if this shape should hold focus to catch longer all mouse movements.
Reimplemented from iview::CInteractiveShapeBase.
Reimplemented in iview::CPolygonCalibrationShape.
void iview::CTransformableRectangleCalibrationShape::ResetNodes () const [protected]
void iview::CTransformableRectangleCalibrationShape::SetEditableHeight (bool state = true) [inline, virtual]
Definition at line 178 of file CTransformableRectangleCalibrationShape.h.
void iview::CTransformableRectangleCalibrationShape::SetEditableRotation (bool state = true) [inline, virtual]
Definition at line 150 of file CTransformableRectangleCalibrationShape.h.
void iview::CTransformableRectangleCalibrationShape::SetEditableWidth (bool state = true) [inline, virtual]
Definition at line 164 of file CTransformableRectangleCalibrationShape.h.
virtual void iview::CTransformableRectangleCalibrationShape::SetLogDragPosition (const i2d::CVector2d & position) [protected, virtual]
Implements iview::CInteractiveShapeBase.
Reimplemented in iview::CPolygonCalibrationShape.
void iview::CTransformableRectangleCalibrationShape::SetProportionalScaled (bool state = true) [inline, virtual]
Definition at line 192 of file CTransformableRectangleCalibrationShape.h.
Member Data Documentation
MouseMode iview::CTransformableRectangleCalibrationShape::m_mouseMode [protected]
Definition at line 92 of file CTransformableRectangleCalibrationShape.h.
i2d::CVector2d iview::CTransformableRectangleCalibrationShape::m_referencePosition [protected]
Reimplemented in iview::CPolygonCalibrationShape.
Definition at line 93 of file CTransformableRectangleCalibrationShape.h.
The documentation for this class was generated from the following file:
Include/iview/CTransformableRectangleCalibrationShape.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy