icmm::CVarColor Class Reference
icmm::CVarColor Class Reference
Generic color implementation with variable number of color components.
#include <CVarColor.h>
Public Types
typedef imath::CVarVector BaseClass
Public Types inherited from imath::CVarVector
typedef QVector< double > Elements
Public Types inherited from istd::IChangeable
enum ChangeFlags {
CF_ACF_INTERNAL = 1 << 0, CF_MODEL = 1 << 1, CF_ABORTED = 1 << 2, CF_DELEGATED = 1 << 3,
CF_NO_UNDO = 1 << 5
}
enum SupportedOperations {
SO_NONE = 0, SO_OBSERVE = 1, SO_COPY = 2, SO_CLONE = 4,
SO_COMPARE = 8
}
Flags for supported operations.
enum CompatibilityMode { CM_STRICT, CM_WITHOUT_REFS, CM_WITH_REFS, CM_CONVERT }
Control how relationship betweeen objects are interpreted.
Public Member Functions
CVarColor ()
Default constructor.
CVarColor (int componentsCount, double value=0)
Constructor with explicit initialization of number of elements.
CVarColor (const CVarColor &color)
Copy constructor.
template<int Size>
CVarColor (const imath::TVector< Size > &vector)
Template conversion constructor.
void GetRounded (const imath::IDoubleManip &manipulator, CVarColor &result)
Get color after components value rounding with specified precision.
bool IsRoundedEqual (const CVarColor &color, const imath::IDoubleManip &manipulator) const
Check if two values are equal after rounding.
bool IsSimilar (const CVarColor &color, double tolerance=I_BIG_EPSILON) const
Allows to compare two colors with tolerance.
bool IsNormalized () const
Check if this color value is normalized.
void Normalize ()
Make this color to be normalized.
void GetNormalized (CVarColor &result) const
Get normalized color.
CVarColor operator+ (const CVarColor &color) const
CVarColor operator- (const CVarColor &color) const
CVarColor operator* (const CVarColor &color) const
CVarColor operator/ (const CVarColor &color) const
CVarColor operator* (double value) const
CVarColor operator/ (double value) const
const CVarColor & operator= (const CVarColor &color)
const CVarColor & operator+= (const CVarColor &color)
const CVarColor & operator-= (const CVarColor &color)
const CVarColor & operator*= (const CVarColor &color)
const CVarColor & operator/= (const CVarColor &color)
const CVarColor & operator*= (double value)
const CVarColor & operator/= (double value)
bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
Public Member Functions inherited from imath::CVarVector
CVarVector ()
Create the vector without components.
CVarVector (int componentsCount, double value=0)
Create vector and initialize number of components.
CVarVector (const CVarVector &vector)
Copy constructor.
template<int Size>
CVarVector (const TVector< Size, double > &vector)
bool IsEmpty () const
Get true, if the element ist is empty.
int GetElementsCount () const
Get number of elements.
bool SetElementsCount (int count, double value=0)
Set number of elements.
double GetElement (int index) const
Get element at specified index.
double & GetElementRef (int index)
Get reference to element at specified index.
void SetElement (int index, double value)
Set element at specified index.
void Reset ()
Set size to zero.
void Reset (int elementsCount, double value)
Set number of elements and set all elements to specified value.
void Clear ()
Set all coordinates to zero.
void SetElementsFrom (const CVarVector &vector, double expansionValue=0)
Set elemenents from other vector without resizing.
const Elements & GetElements () const
Get read-only access to internal element container.
Elements & GetElementsRef ()
Get access to internal element container.
bool EnsureElementsCount (int count, double value=0)
Ensure, that number of elements is at least the specified value.
void Translate (const CVarVector &vector)
Translate the point.
CVarVector GetTranslated (const CVarVector &vector)
Get translated point.
void GetTranslated (const CVarVector &vector, CVarVector &result)
/overloaded
void ScaledCumulate (const CVarVector &vector, double scale)
Add second vector scaled by specified factor.
bool IsNull (double tolerance=I_BIG_EPSILON) const
Check if this vector is null.
double GetDotProduct (const CVarVector &vector) const
Return dot product of two vectors.
double GetLength2 () const
Return euclidian length square.
double GetLength () const
Return euclidian length.
double GetDistance2 (const CVarVector &vector) const
Return distance square between two vectors.
double GetDistance (const CVarVector &vector) const
Return distance between two vectors.
double GetElementsSum () const
Get simple sum of all elements.
bool Normalize (double length=1.0)
Normalize vector to specified length.
bool GetNormalized (CVarVector &result, double length=1.0) const
Return normalized vector with the same direction and specified length.
void GetMinimal (const CVarVector &vector, CVarVector &result) const
Get vector with minimal elements values.
void GetMaximal (const CVarVector &vector, CVarVector &result) const
Get vector with maximal elements values.
bool Serialize (iser::IArchive &archive)
Serialize this vector to specified archive.
bool operator== (const CVarVector &vector) const
bool operator!= (const CVarVector &vector) const
bool operator< (const CVarVector &vector) const
bool operator> (const CVarVector &vector) const
bool operator<= (const CVarVector &vector) const
bool operator>= (const CVarVector &vector) const
CVarVector operator- () const
CVarVector operator+ (const CVarVector &vector) const
CVarVector operator- (const CVarVector &vector) const
CVarVector operator* (double scalar) const
CVarVector operator/ (double scalar) const
CVarVector & operator+= (const CVarVector &vector)
CVarVector & operator-= (const CVarVector &vector)
CVarVector & operator*= (double scalar)
CVarVector & operator/= (double scalar)
CVarVector & operator= (const CVarVector &vector)
double operator[] (int i) const
double & operator[] (int i)
Public Member Functions inherited from iser::ISerializable
virtual quint32 GetMinimalVersion (int versionId) const
Get minimal needed version to correct storing of this data.
Public Member Functions inherited from istd::IChangeable
virtual void BeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Starts the change transaction.
virtual void EndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Ends the change transaction.
virtual int GetSupportedOperations () const
Get set of flags for supported operations.
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Copy this object from another one.
virtual bool IsEqual (const IChangeable &object) const
Compare this object with another object.
virtual IChangeable * CloneMe (CompatibilityMode mode=CM_WITHOUT_REFS) const
Make a copy of this object.
virtual bool ResetData (CompatibilityMode mode=CM_WITHOUT_REFS)
Reset data to its default state.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Additional Inherited Members
Protected Member Functions inherited from istd::IChangeable
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for begin change event.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for end change event.
Detailed Description
Generic color implementation with variable number of color components.
The dimension of used colorspace can be set at the construction time of CVarColor object,
Definition at line 23 of file CVarColor.h.
Member Typedef Documentation
typedef imath::CVarVector icmm::CVarColor::BaseClass
Definition at line 26 of file CVarColor.h.
Constructor & Destructor Documentation
icmm::CVarColor::CVarColor ()
Default constructor.
It set number of elements to 0.
icmm::CVarColor::CVarColor (int componentsCount, double value = 0) explicit
Constructor with explicit initialization of number of elements.
icmm::CVarColor::CVarColor (const CVarColor & color)
Copy constructor.
template<int Size> icmm::CVarColor::CVarColor (const imath::TVector< Size > & vector) inline
Template conversion constructor.
Definition at line 48 of file CVarColor.h.
Member Function Documentation
void icmm::CVarColor::GetNormalized (CVarColor & result) const
Get normalized color.
Normalized values have all components in the range [0, 1].
void icmm::CVarColor::GetRounded (const imath::IDoubleManip & manipulator, CVarColor & result)
Get color after components value rounding with specified precision.
Parameters
manipulator manipulator object used to round single components.
result result object.
bool icmm::CVarColor::IsNormalized () const inline
Check if this color value is normalized.
Normalized values have all components in the range [0, 1].
Definition at line 121 of file CVarColor.h.
References imath::CVarVector::GetElement(), and imath::CVarVector::GetElementsCount().
bool icmm::CVarColor::IsRoundedEqual (const CVarColor & color, const imath::IDoubleManip & manipulator) const
Check if two values are equal after rounding.
Parameters
color second color to comparision.
manipulator value manipulator used to round single components.
bool icmm::CVarColor::IsSimilar (const CVarColor & color, double tolerance = I_BIG_EPSILON) const inline
Allows to compare two colors with tolerance.
Definition at line 115 of file CVarColor.h.
References imath::CVarVector::GetDistance().
void icmm::CVarColor::Normalize ()
Make this color to be normalized.
Normalized values have all components in the range [0, 1].
CVarColor icmm::CVarColor::operator* (const CVarColor & color) const inline
Definition at line 157 of file CVarColor.h.
CVarColor icmm::CVarColor::operator* (double value) const inline
Definition at line 177 of file CVarColor.h.
References imath::CVarVector::GetElement(), imath::CVarVector::GetElementsCount(), and imath::CVarVector::SetElement().
const CVarColor& icmm::CVarColor::operator*= (const CVarColor & color)
const CVarColor & icmm::CVarColor::operator*= (double value) inline
Definition at line 205 of file CVarColor.h.
References imath::CVarVector::operator*=().
CVarColor icmm::CVarColor::operator+ (const CVarColor & color) const inline
Definition at line 137 of file CVarColor.h.
const CVarColor& icmm::CVarColor::operator+= (const CVarColor & color)
CVarColor icmm::CVarColor::operator- (const CVarColor & color) const inline
Definition at line 147 of file CVarColor.h.
const CVarColor& icmm::CVarColor::operator-= (const CVarColor & color)
CVarColor icmm::CVarColor::operator/ (const CVarColor & color) const inline
Definition at line 167 of file CVarColor.h.
CVarColor icmm::CVarColor::operator/ (double value) const inline
Definition at line 191 of file CVarColor.h.
References imath::CVarVector::GetElement(), imath::CVarVector::GetElementsCount(), and imath::CVarVector::SetElement().
const CVarColor& icmm::CVarColor::operator/= (const CVarColor & color)
const CVarColor & icmm::CVarColor::operator/= (double value) inline
Definition at line 213 of file CVarColor.h.
References imath::CVarVector::operator/=().
const CVarColor& icmm::CVarColor::operator= (const CVarColor & color)
bool icmm::CVarColor::Serialize (iser::IArchive & archive) virtual
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See Also
iser::IArchive
Implements iser::ISerializable.
The documentation for this class was generated from the following file:
Include/icmm/CVarColor.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy