ACF: imath::TMathVectorWrap< Base > Class Template Reference
imath::TMathVectorWrap< Base > Class Template Reference
Implementation of mathematical vector with carthesian operations over elements container (vector).
#include <TMathVectorWrap.h>
Public Types
typedef Base BaseClass
Public Member Functions
TMathVectorWrap ()
Create an uninitialized point.
TMathVectorWrap (const Base &vector)
Copy constructor.
void Clear ()
Set all coordinates to zero.
void Translate (const TMathVectorWrap< Base > &vector)
Translate the point.
TMathVectorWrap< Base > GetTranslated (const TMathVectorWrap< Base > &vector)
Get translated point.
void GetTranslated (const TMathVectorWrap< Base > &vector, TMathVectorWrap< Base > &result)
/overloaded
bool IsNull (typename Base::ElementType tolerance=I_BIG_EPSILON) const
Check if this vector is null.
Base::ElementType GetDotProduct (const TMathVectorWrap< Base > &vector) const
Return dot product of two vectors.
Base::ElementType GetLength2 () const
Return euclidian length square.
Base::ElementType GetLength () const
Return euclidian length.
Base::ElementType GetDistance2 (const TMathVectorWrap< Base > &vector) const
Return distance square between two vectors.
Base::ElementType GetDistance (const TMathVectorWrap< Base > &vector) const
Return distance between two vectors.
bool Normalize (typename Base::ElementType length=1.0)
Normalize vector to specified length.
bool GetNormalized (TMathVectorWrap< Base > &result, typename Base::ElementType length=1.0) const
Return normalized vector with the same direction and specified length.
bool Serialize (iser::IArchive &archive)
Serialize this vector to specified archive.
bool operator== (const TMathVectorWrap< Base > &vector) const
bool operator!= (const TMathVectorWrap< Base > &vector) const
bool operator< (const TMathVectorWrap< Base > &vector) const
bool operator> (const TMathVectorWrap< Base > &vector) const
bool operator<= (const TMathVectorWrap< Base > &vector) const
bool operator>= (const TMathVectorWrap< Base > &vector) const
TMathVectorWrap< Base > operator- () const
TMathVectorWrap< Base > operator+ (const TMathVectorWrap< Base > &vector) const
TMathVectorWrap< Base > operator- (const TMathVectorWrap< Base > &vector) const
TMathVectorWrap< Base > operator* (typename Base::ElementType scalar) const
TMathVectorWrap< Base > operator/ (typename Base::ElementType scalar) const
TMathVectorWrap< Base > & operator= (const TMathVectorWrap< Base > &vector)
TMathVectorWrap< Base > & operator+= (const TMathVectorWrap< Base > &vector)
TMathVectorWrap< Base > & operator-= (const TMathVectorWrap< Base > &vector)
TMathVectorWrap< Base > & operator*= (typename Base::ElementType scalar)
TMathVectorWrap< Base > & operator/= (typename Base::ElementType scalar)
operator Base () const
Detailed Description
template<typename Base>
class imath::TMathVectorWrap< Base >
Implementation of mathematical vector with carthesian operations over elements container (vector).
Definition at line 21 of file TMathVectorWrap.h.
Member Typedef Documentation
template<typename Base> typedef Base imath::TMathVectorWrap< Base >::BaseClass
Definition at line 24 of file TMathVectorWrap.h.
Constructor & Destructor Documentation
template<typename Base > imath::TMathVectorWrap< Base >::TMathVectorWrap () [inline]
Create an uninitialized point.
Definition at line 131 of file TMathVectorWrap.h.
template<typename Base > imath::TMathVectorWrap< Base >::TMathVectorWrap (const Base & vector) [inline]
Copy constructor.
Definition at line 137 of file TMathVectorWrap.h.
Member Function Documentation
template<typename Base > void imath::TMathVectorWrap< Base >::Clear () [inline]
Set all coordinates to zero.
Definition at line 146 of file TMathVectorWrap.h.
template<typename Base > Base::ElementType imath::TMathVectorWrap< Base >::GetDistance (const TMathVectorWrap< Base > & vector) const [inline]
Return distance between two vectors.
Definition at line 222 of file TMathVectorWrap.h.
References imath::TMathVectorWrap< Base >::GetDistance2().
template<typename Base > Base::ElementType imath::TMathVectorWrap< Base >::GetDistance2 (const TMathVectorWrap< Base > & vector) const [inline]
Return distance square between two vectors.
Definition at line 215 of file TMathVectorWrap.h.
Referenced by imath::TMathVectorWrap< Base >::GetDistance().
template<typename Base > Base::ElementType imath::TMathVectorWrap< Base >::GetDotProduct (const TMathVectorWrap< Base > & vector) const [inline]
Return dot product of two vectors.
Definition at line 187 of file TMathVectorWrap.h.
References istd::Min().
Referenced by imath::TMathVectorWrap< Base >::GetLength2().
template<typename Base > Base::ElementType imath::TMathVectorWrap< Base >::GetLength () const [inline]
Return euclidian length.
Definition at line 208 of file TMathVectorWrap.h.
References imath::TMathVectorWrap< Base >::GetLength2().
Referenced by imath::TMathVectorWrap< Base >::GetNormalized(), and imath::TMathVectorWrap< Base >::Normalize().
template<typename Base > Base::ElementType imath::TMathVectorWrap< Base >::GetLength2 () const [inline]
Return euclidian length square.
Definition at line 201 of file TMathVectorWrap.h.
References imath::TMathVectorWrap< Base >::GetDotProduct().
Referenced by imath::TMathVectorWrap< Base >::GetLength(), and imath::TMathVectorWrap< Base >::IsNull().
template<typename Base > bool imath::TMathVectorWrap< Base >::GetNormalized (TMathVectorWrap< Base > & result, typename Base::ElementType length = 1.0) const [inline]
Return normalized vector with the same direction and specified length.
Parameters:
length new vector length.
Returns:
true, if normalization successed.
Definition at line 490 of file TMathVectorWrap.h.
References imath::TMathVectorWrap< Base >::GetLength(), and I_BIG_EPSILON.
template<typename Base > void imath::TMathVectorWrap< Base >::GetTranslated (const TMathVectorWrap< Base > & vector, TMathVectorWrap< Base > & result) [inline]
/overloaded
Definition at line 173 of file TMathVectorWrap.h.
template<typename Base > TMathVectorWrap< Base > imath::TMathVectorWrap< Base >::GetTranslated (const TMathVectorWrap< Base > & vector) [inline]
Get translated point.
Definition at line 166 of file TMathVectorWrap.h.
template<typename Base > bool imath::TMathVectorWrap< Base >::IsNull (typename Base::ElementType tolerance = I_BIG_EPSILON) const [inline]
Check if this vector is null.
Definition at line 180 of file TMathVectorWrap.h.
References imath::TMathVectorWrap< Base >::GetLength2().
template<typename Base > bool imath::TMathVectorWrap< Base >::Normalize (typename Base::ElementType length = 1.0) [inline]
Normalize vector to specified length.
Parameters:
length new vector length.
Returns:
true, if normalization successed.
Definition at line 469 of file TMathVectorWrap.h.
References imath::TMathVectorWrap< Base >::GetLength(), and I_BIG_EPSILON.
template<typename Base > imath::TMathVectorWrap< Base >::operator Base () const [inline]
Definition at line 544 of file TMathVectorWrap.h.
template<typename Base > bool imath::TMathVectorWrap< Base >::operator!= (const TMathVectorWrap< Base > & vector) const [inline]
Definition at line 248 of file TMathVectorWrap.h.
References imath::TMathVectorWrap< Base >::operator==().
template<typename Base > TMathVectorWrap< Base > imath::TMathVectorWrap< Base >::operator* (typename Base::ElementType scalar) const [inline]
Definition at line 437 of file TMathVectorWrap.h.
template<typename Base > TMathVectorWrap< Base > & imath::TMathVectorWrap< Base >::operator*= (typename Base::ElementType scalar) [inline]
Definition at line 368 of file TMathVectorWrap.h.
template<typename Base > TMathVectorWrap< Base > imath::TMathVectorWrap< Base >::operator+ (const TMathVectorWrap< Base > & vector) const [inline]
Definition at line 407 of file TMathVectorWrap.h.
References istd::Min().
template<typename Base > TMathVectorWrap< Base > & imath::TMathVectorWrap< Base >::operator+= (const TMathVectorWrap< Base > & vector) [inline]
Definition at line 344 of file TMathVectorWrap.h.
References istd::Min().
template<typename Base > TMathVectorWrap< Base > imath::TMathVectorWrap< Base >::operator- (const TMathVectorWrap< Base > & vector) const [inline]
Definition at line 422 of file TMathVectorWrap.h.
References istd::Min().
template<typename Base > TMathVectorWrap< Base > imath::TMathVectorWrap< Base >::operator- () const [inline]
Definition at line 392 of file TMathVectorWrap.h.
template<typename Base > TMathVectorWrap< Base > & imath::TMathVectorWrap< Base >::operator-= (const TMathVectorWrap< Base > & vector) [inline]
Definition at line 356 of file TMathVectorWrap.h.
References istd::Min().
template<typename Base > TMathVectorWrap< Base > imath::TMathVectorWrap< Base >::operator/ (typename Base::ElementType scalar) const [inline]
Definition at line 452 of file TMathVectorWrap.h.
template<typename Base > TMathVectorWrap< Base > & imath::TMathVectorWrap< Base >::operator/= (typename Base::ElementType scalar) [inline]
Definition at line 380 of file TMathVectorWrap.h.
template<typename Base > bool imath::TMathVectorWrap< Base >::operator< (const TMathVectorWrap< Base > & vector) const [inline]
Definition at line 255 of file TMathVectorWrap.h.
References istd::Min().
template<typename Base > bool imath::TMathVectorWrap< Base >::operator<= (const TMathVectorWrap< Base > & vector) const [inline]
Definition at line 295 of file TMathVectorWrap.h.
References istd::Min().
template<typename Base > TMathVectorWrap< Base > & imath::TMathVectorWrap< Base >::operator= (const TMathVectorWrap< Base > & vector) [inline]
Definition at line 335 of file TMathVectorWrap.h.
template<typename Base > bool imath::TMathVectorWrap< Base >::operator== (const TMathVectorWrap< Base > & vector) const [inline]
Definition at line 231 of file TMathVectorWrap.h.
Referenced by imath::TMathVectorWrap< Base >::operator!=().
template<typename Base > bool imath::TMathVectorWrap< Base >::operator> (const TMathVectorWrap< Base > & vector) const [inline]
Definition at line 275 of file TMathVectorWrap.h.
References istd::Min().
template<typename Base > bool imath::TMathVectorWrap< Base >::operator>= (const TMathVectorWrap< Base > & vector) const [inline]
Definition at line 315 of file TMathVectorWrap.h.
References istd::Min().
template<typename Base > bool imath::TMathVectorWrap< Base >::Serialize (iser::IArchive & archive) [inline]
Serialize this vector to specified archive.
Definition at line 512 of file TMathVectorWrap.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), and iser::IArchive::Process().
template<typename Base > void imath::TMathVectorWrap< Base >::Translate (const TMathVectorWrap< Base > & vector) [inline]
Translate the point.
Definition at line 156 of file TMathVectorWrap.h.
References istd::Min().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/imath/TMathVectorWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy