ACF: iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass > Class Template Reference
iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass > Class Template Reference
#include <TObjectShapeBase.h>
Public Types
typedef TShapeBase
< GraphicsItemClass > BaseClass
typedef
imod::TSingleModelObserverBase
< ObjectClass > BaseClass2
Public Member Functions
TObjectShapeBase (bool isEditable=false, const ISceneProvider *providerPtr=NULL)
Protected Member Functions
virtual void OnSelectionChanged (bool isSelected)
virtual void OnPositionChanged (const QPointF &position)
virtual QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
virtual void mousePressEvent (QGraphicsSceneMouseEvent *eventPtr)
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *eventPtr)
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *eventPtr)
virtual void AfterUpdate (imod::IModel *modelPtr, int updateFlags, istd::IPolymorphic *updateParamsPtr)
This function will be called after update of the observer contents occures.
virtual void UpdateGraphicsItem (const ObjectClass &object)=0
Detailed Description
template<class GraphicsItemClass, class ObjectClass>
class iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >
Definition at line 24 of file TObjectShapeBase.h.
Member Typedef Documentation
template<class GraphicsItemClass, class ObjectClass> typedef TShapeBase<GraphicsItemClass> iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >::BaseClass
Reimplemented from imod::TSingleModelObserverBase< ObjectClass >.
Reimplemented in icmpstr::CRegistryElementShape, iqt2d::CAnnulusSegmentShape, iqt2d::CAnnulusShape, iqt2d::CCircleShape, iqt2d::CLine2dShape, iqt2d::CQuadrangleShape, and iqt2d::CRectangleShape.
Definition at line 29 of file TObjectShapeBase.h.
template<class GraphicsItemClass, class ObjectClass> typedef imod::TSingleModelObserverBase<ObjectClass> iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >::BaseClass2
Definition at line 30 of file TObjectShapeBase.h.
Constructor & Destructor Documentation
template<class GraphicsItemClass , class ObjectClass > iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >::TObjectShapeBase (bool isEditable = false, const ISceneProvider * providerPtr = NULL) [inline]
Definition at line 63 of file TObjectShapeBase.h.
References iqt2d::TShapeBase< GraphicsItemClass >::EditableColor, iqt2d::TShapeBase< GraphicsItemClass >::InactiveColor, iqt2d::TShapeBase< GraphicsItemClass >::SelectedColor, iqt2d::TShapeBase< GraphicsItemClass >::SetPen(), and iqt2d::TShapeBase< GraphicsItemClass >::SwitchColorSheme().
Member Function Documentation
template<class GraphicsItemClass , class ObjectClass > void iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >::AfterUpdate (imod::IModel * modelPtr, int updateFlags, istd::IPolymorphic * updateParamsPtr) [inline, protected, virtual]
This function will be called after update of the observer contents occures.
Reimplemented from imod::CSingleModelObserverBase.
Definition at line 166 of file TObjectShapeBase.h.
References imod::TSingleModelObserverBase< ObjectClass >::GetObjectPtr(), I_ASSERT, NULL, and iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >::UpdateGraphicsItem().
template<class GraphicsItemClass , class ObjectClass > QVariant iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >::itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant & value) [inline, protected, virtual]
Reimplemented from iqt2d::TShapeBase< GraphicsItemClass >.
Definition at line 122 of file TObjectShapeBase.h.
References iqt2d::TShapeBase< GraphicsItemClass >::itemChange().
template<class GraphicsItemClass , class ObjectClass > void iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * eventPtr) [inline, protected, virtual]
Reimplemented in icmpstr::CRegistryElementShape.
Definition at line 155 of file TObjectShapeBase.h.
References istd::TChangeNotifier< Changeable >::Reset().
template<class GraphicsItemClass , class ObjectClass > void iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >::mousePressEvent (QGraphicsSceneMouseEvent * eventPtr) [inline, protected, virtual]
Definition at line 133 of file TObjectShapeBase.h.
References imod::TSingleModelObserverBase< ObjectClass >::GetObjectPtr(), iqt2d::TShapeBase< GraphicsItemClass >::IsEditable(), and istd::TChangeNotifier< Changeable >::SetPtr().
template<class GraphicsItemClass , class ObjectClass > void iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >::mouseReleaseEvent (QGraphicsSceneMouseEvent * eventPtr) [inline, protected, virtual]
Definition at line 146 of file TObjectShapeBase.h.
References istd::TChangeNotifier< Changeable >::Reset().
template<class GraphicsItemClass , class ObjectClass > void iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >::OnPositionChanged (const QPointF & position) [inline, protected, virtual]
Reimplemented from iqt2d::TShapeBase< GraphicsItemClass >.
Definition at line 106 of file TObjectShapeBase.h.
References i2d::IObject2d::GetCenter(), iqt::GetCVector2d(), imod::TSingleModelObserverBase< ObjectClass >::GetObjectPtr(), i2d::IObject2d::MoveCenterTo(), NULL, and iqt2d::TShapeBase< GraphicsItemClass >::OnPositionChanged().
template<class GraphicsItemClass , class ObjectClass > void iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >::OnSelectionChanged (bool isSelected) [inline, protected, virtual]
Reimplemented from iqt2d::TShapeBase< GraphicsItemClass >.
Reimplemented in icmpstr::CRegistryElementShape.
Definition at line 89 of file TObjectShapeBase.h.
References iqt2d::TShapeBase< GraphicsItemClass >::EditableColor, iqt2d::TShapeBase< GraphicsItemClass >::InactiveColor, iqt2d::TShapeBase< GraphicsItemClass >::IsEditable(), iqt2d::TShapeBase< GraphicsItemClass >::SelectedColor, and iqt2d::TShapeBase< GraphicsItemClass >::SwitchColorSheme().
template<class GraphicsItemClass, class ObjectClass> virtual void iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >::UpdateGraphicsItem (const ObjectClass & object) [protected, pure virtual]
Implemented in iqt2d::CAnnulusSegmentShape, iqt2d::CAnnulusShape, iqt2d::CLine2dShape, iqt2d::CQuadrangleShape, and iqt2d::CRectangleShape.
Referenced by iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >::AfterUpdate().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iqt2d/TObjectShapeBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy