icomp::CCompositeComponent Class Reference
icomp::CCompositeComponent Class Reference
#include <CCompositeComponent.h>
Public Member Functions
CCompositeComponent ()
virtual ~CCompositeComponent ()
template<class InterfaceType >
InterfaceType * GetComponentInterface (const QByteArray &subId="")
Get interface implemented by this composite component.
bool EnsureAutoInitComponentsCreated () const
Make sure, all components with flag 'AutoInit' are initialized.
virtual IComponent * GetSubcomponent (const QByteArray &componentId) const
Get access to subcomponent using its ID.
virtual const IComponentContext * GetSubcomponentContext (const QByteArray &componentId) const
Get access to context of subcomponent using its ID.
virtual IComponent * CreateSubcomponent (const QByteArray &componentId) const
Create instance of subcomponent using its ID.
virtual void OnSubcomponentDeleted (const IComponent *subcomponentPtr)
Called if subcomponent is removed from memory.
virtual const ICompositeComponent * GetParentComponent (bool ownerOnly=false) const
Get parent of this component.
virtual void * GetInterface (const istd::CClassInfo &interfaceType, const QByteArray &subId="")
Get access to specified component interface.
virtual const IComponentContext * GetComponentContext () const
Get access to component context describing all application-specified component information loaded from components registry.
virtual void SetComponentContext (const icomp::IComponentContext *contextPtr, const ICompositeComponent *parentPtr, bool isParentOwner)
Set component context of this component.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Protected Types
typedef istd::TDelPtr
< icomp::IComponent > ComponentPtr
typedef istd::TDelPtr
< icomp::IComponentContext > ContextPtr
Protected Member Functions
bool CreateSubcomponentInfo (const QByteArray &componentId, ContextPtr &subContextPtr, ComponentPtr *subComponentPtr, bool isOwned) const
Create information objects and subcomponent.
Additional Inherited Members
Static Public Member Functions inherited from istd::CIdManipBase
static bool SplitId (const QByteArray &complexId, QByteArray &baseId, QByteArray &subId)
Split component ID into separated ID's.
static QByteArray JoinId (const QByteArray &baseId, const QByteArray &subId)
Join base component ID and sub ID into composed component ID.
Static Protected Member Functions inherited from icomp::CInterfaceManipBase
template<class Interface >
static Interface * ExtractInterface (IComponent *componentPtr, const QByteArray &subId="")
Extract interface from component.
Detailed Description
Definition at line 25 of file CCompositeComponent.h.
Member Typedef Documentation
typedef istd::TDelPtr<icomp::IComponent> icomp::CCompositeComponent::ComponentPtr protected
Definition at line 61 of file CCompositeComponent.h.
typedef istd::TDelPtr<icomp::IComponentContext> icomp::CCompositeComponent::ContextPtr protected
Definition at line 62 of file CCompositeComponent.h.
Constructor & Destructor Documentation
icomp::CCompositeComponent::CCompositeComponent ()
virtual icomp::CCompositeComponent::~CCompositeComponent () virtual
Member Function Documentation
virtual IComponent* icomp::CCompositeComponent::CreateSubcomponent (const QByteArray & componentId) const virtual
Create instance of subcomponent using its ID.
Implements icomp::ICompositeComponent.
bool icomp::CCompositeComponent::CreateSubcomponentInfo (const QByteArray & componentId, ContextPtr & subContextPtr, ComponentPtr * subComponentPtr, bool isOwned) const protected
Create information objects and subcomponent.
Parameters
componentId ID of subcomponent.
subContextPtr pointer to subcomponent context will be set to new context object if needed.
subComponentPtr optional pointer to subcomponent will be set to new component object.
isOwned true, if created component will be owned by this component and should delegate its destroy event.
Returns
true if success.
bool icomp::CCompositeComponent::EnsureAutoInitComponentsCreated () const
Make sure, all components with flag 'AutoInit' are initialized.
Returns
true, if there were components needed to be initialized.
virtual const IComponentContext* icomp::CCompositeComponent::GetComponentContext () const virtual
Get access to component context describing all application-specified component information loaded from components registry.
Implements icomp::IComponent.
template<class InterfaceType > InterfaceType * icomp::CCompositeComponent::GetComponentInterface (const QByteArray & subId = "") inline
Get interface implemented by this composite component.
Definition at line 118 of file CCompositeComponent.h.
References GetInterface().
Referenced by ipackage::CComponentAccessor::GetComponentInterface().
virtual void* icomp::CCompositeComponent::GetInterface (const istd::CClassInfo & interfaceType, const QByteArray & subId = "") virtual
Get access to specified component interface.
Parameters
interfaceType requested interface.
subId some additional ID to identify subelement of this component.
Implements icomp::IComponent.
Referenced by GetComponentInterface().
virtual const ICompositeComponent* icomp::CCompositeComponent::GetParentComponent (bool ownerOnly = false) const virtual
Get parent of this component.
Parent is component who created this component. Parent component can be also owner of this component. It means manages life time of this componenent.
Parameters
ownerOnly indicate, that parent should be returned only if it owns this component.
Returns
pointer to parent component or NULL if parent is not accessible.
Implements icomp::IComponent.
virtual IComponent* icomp::CCompositeComponent::GetSubcomponent (const QByteArray & componentId) const virtual
Get access to subcomponent using its ID.
Implements icomp::ICompositeComponent.
virtual const IComponentContext* icomp::CCompositeComponent::GetSubcomponentContext (const QByteArray & componentId) const virtual
Get access to context of subcomponent using its ID.
Please note, that this does'n create component instance.
Implements icomp::ICompositeComponent.
virtual void icomp::CCompositeComponent::OnSubcomponentDeleted (const IComponent * subcomponentPtr) virtual
Called if subcomponent is removed from memory.
Parameters
subcomponentPtr pointer to component beeing removed. It cannot be NULL.
Implements icomp::ICompositeComponent.
virtual void icomp::CCompositeComponent::SetComponentContext (const icomp::IComponentContext * contextPtr, const ICompositeComponent * parentPtr, bool isParentOwner) virtual
Set component context of this component.
Parameters
contextPtr new value of component context. It can be also NULL. Please avoid to use this method, it is designed for internal use only.
parentPtr pointer to parent component, or NULL if this component has no parent.
isParentOwner indicate, that life cycle of this component is controller by its parent.
Implements icomp::IComponent.
The documentation for this class was generated from the following file:
Include/icomp/CCompositeComponent.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy