ACF: istd::TVarArray< Element > Class Template Reference
istd::TVarArray< Element > Class Template Reference
Multidimensional array with fixed number of dimensions.
#include <TVarArray.h>
Classes
class Iterator
Public Types
typedef CVarIndex IndexType
typedef CVarIndex SizesType
typedef Element ElementType
Public Member Functions
TVarArray ()
TVarArray (const TVarArray &array)
void Reset ()
Removes all elements and set all sizes to 1.
bool IsDimensionsCountFixed () const
Check, if number dimensions is fixed.
int GetDimensionsCount () const
Get number of dimensions of this array.
bool SetDimensionsCount (int count)
Set number of dimensions of this array.
const SizesType & GetSizes () const
Get list of all sizes.
void SetSizes (const SizesType &sizes)
Set list of all sizes.
int GetSize (int dimension) const
Get size of array for specified dimension.
void SetSize (int dimension, int size)
Set size of array for specified dimension.
const Element & GetAt (const IndexType &index) const
Get element stored at specified index.
void SetAt (const IndexType &index, const Element &value)
Set element at specified index.
Iterator Begin () const
Get begin value of element access iterator.
const Iterator & End () const
Get end value of element access iterator.
const Element & operator[] (const IndexType &index) const
Element & operator[] (const IndexType &index)
int GetElementIndex (const IndexType &index) const
Get index of element in one dimensional array.
Protected Member Functions
void UpdateElementsSize ()
Update size of elements to size changes.
Detailed Description
template<class Element>
class istd::TVarArray< Element >
Multidimensional array with fixed number of dimensions.
Definition at line 21 of file TVarArray.h.
Member Typedef Documentation
template<class Element > typedef Element istd::TVarArray< Element >::ElementType
Definition at line 26 of file TVarArray.h.
template<class Element > typedef CVarIndex istd::TVarArray< Element >::IndexType
Definition at line 24 of file TVarArray.h.
template<class Element > typedef CVarIndex istd::TVarArray< Element >::SizesType
Definition at line 25 of file TVarArray.h.
Constructor & Destructor Documentation
template<class Element > istd::TVarArray< Element >::TVarArray () [inline]
Definition at line 281 of file TVarArray.h.
template<class Element > istd::TVarArray< Element >::TVarArray (const TVarArray< Element > & array) [inline]
Definition at line 287 of file TVarArray.h.
Member Function Documentation
template<class Element > TVarArray< Element >::Iterator istd::TVarArray< Element >::Begin () const [inline]
Get begin value of element access iterator.
Please refer to general description of ACF iterators, STL iterators or Qt iterators concept.
Definition at line 225 of file TVarArray.h.
template<class Element > const TVarArray< Element >::Iterator & istd::TVarArray< Element >::End () const [inline]
Get end value of element access iterator.
Please refer to general description of ACF iterators, STL iterators or Qt iterators concept.
Definition at line 232 of file TVarArray.h.
template<class Element > const Element & istd::TVarArray< Element >::GetAt (const IndexType & index) const [inline]
Get element stored at specified index.
Definition at line 199 of file TVarArray.h.
References istd::TVarArray< Element >::GetElementIndex(), I_ASSERT, and istd::CVarIndex::IsInside().
Referenced by istd::TVarArray< Element >::Iterator::operator*(), istd::TVarArray< Element >::Iterator::operator->(), and istd::TVarArray< Element >::operator[]().
template<class Element > int istd::TVarArray< Element >::GetDimensionsCount () const [inline]
Get number of dimensions of this array.
Definition at line 164 of file TVarArray.h.
References istd::CVarIndex::GetDimensionsCount().
template<class Element > int istd::TVarArray< Element >::GetElementIndex (const IndexType & index) const [inline]
Get index of element in one dimensional array.
Definition at line 256 of file TVarArray.h.
References istd::CVarIndex::GetDimensionsCount(), I_ASSERT, and istd::Min().
Referenced by istd::TVarArray< Element >::GetAt(), istd::TVarArray< Element >::operator[](), and istd::TVarArray< Element >::SetAt().
template<class Element > int istd::TVarArray< Element >::GetSize (int dimension) const [inline]
Get size of array for specified dimension.
Definition at line 189 of file TVarArray.h.
References istd::CVarIndex::GetDimensionsCount(), and I_ASSERT.
template<class Element > const TVarArray< Element >::SizesType & istd::TVarArray< Element >::GetSizes () const [inline]
Get list of all sizes.
Definition at line 182 of file TVarArray.h.
Referenced by istd::TVarArray< Element >::Iterator::Iterator(), istd::TVarArray< Element >::Iterator::operator*(), istd::TVarArray< Element >::Iterator::operator++(), istd::TVarArray< Element >::Iterator::operator--(), and istd::TVarArray< Element >::Iterator::operator->().
template<class Element > bool istd::TVarArray< Element >::IsDimensionsCountFixed () const [inline]
Check, if number dimensions is fixed.
It is provided for template implementations. It returns always false.
Definition at line 157 of file TVarArray.h.
template<class Element > Element & istd::TVarArray< Element >::operator[] (const IndexType & index) [inline]
Definition at line 246 of file TVarArray.h.
References istd::TVarArray< Element >::GetElementIndex(), and I_ASSERT.
template<class Element > const Element & istd::TVarArray< Element >::operator[] (const IndexType & index) const [inline]
Definition at line 239 of file TVarArray.h.
References istd::TVarArray< Element >::GetAt().
template<class Element > void istd::TVarArray< Element >::Reset () [inline]
Removes all elements and set all sizes to 1.
Definition at line 294 of file TVarArray.h.
References istd::CVarIndex::Reset().
template<class Element > void istd::TVarArray< Element >::SetAt (const IndexType & index, const Element & value) [inline]
Set element at specified index.
Definition at line 211 of file TVarArray.h.
References istd::TVarArray< Element >::GetElementIndex(), I_ASSERT, and istd::CVarIndex::IsInside().
template<class Element > bool istd::TVarArray< Element >::SetDimensionsCount (int count) [inline]
Set number of dimensions of this array.
Parameters:
count number of dimensions will be set.
Returns:
always true.
Definition at line 171 of file TVarArray.h.
References istd::CVarIndex::SetDimensionsCount(), and istd::TVarArray< Element >::UpdateElementsSize().
template<class Element > void istd::TVarArray< Element >::SetSize (int dimension, int size) [inline]
Set size of array for specified dimension.
Please note, that it can make all elements invalid.
Definition at line 312 of file TVarArray.h.
References istd::CVarIndex::GetDimensionsCount(), I_ASSERT, and istd::TVarArray< Element >::UpdateElementsSize().
template<class Element > void istd::TVarArray< Element >::SetSizes (const SizesType & sizes) [inline]
Set list of all sizes.
Definition at line 303 of file TVarArray.h.
References istd::TVarArray< Element >::UpdateElementsSize().
template<class Element > void istd::TVarArray< Element >::UpdateElementsSize () [inline, protected]
Update size of elements to size changes.
Definition at line 326 of file TVarArray.h.
References istd::CVarIndex::GetDimensionsCount().
Referenced by istd::TVarArray< Element >::SetDimensionsCount(), istd::TVarArray< Element >::SetSize(), and istd::TVarArray< Element >::SetSizes().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/istd/TVarArray.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy