ACF: iqtgui::TRestorableGuiWrap< Gui > Class Template Reference
iqtgui::TRestorableGuiWrap< Gui > Class Template Reference
[Set of helper classes.]
A wrapper for saving/restoring of GUI component states in the application settings.
#include <TRestorableGuiWrap.h>
Public Types
typedef Gui BaseClass
Protected Member Functions
virtual void OnRestoreSettings (const QSettings &settings)=0
virtual void OnSaveSettings (QSettings &settings) const =0
virtual bool CreateGui (QWidget *parentPtr)
virtual bool DestroyGui ()
Detailed Description
template<class Gui>
class iqtgui::TRestorableGuiWrap< Gui >
A wrapper for saving/restoring of GUI component states in the application settings.
Definition at line 21 of file TRestorableGuiWrap.h.
Member Typedef Documentation
template<class Gui> typedef Gui iqtgui::TRestorableGuiWrap< Gui >::BaseClass
Reimplemented in iqtdoc::CMainWindowGuiComp, iqtdoc::CMultiDocumentWorkspaceGuiComp, iqtdoc::CSingleDocumentWorkspaceGuiComp, iqtgui::CComposedGuiComp, iqtgui::CSimpleMainWindowGuiComp, iqtdoc::TQtDocumentManagerWrap< idoc::CMultiDocumentManagerBase, iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QMdiArea > > >, and iqtdoc::TQtDocumentManagerWrap< idoc::CSingleDocumentManagerBase, iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QWidget > > >.
Definition at line 24 of file TRestorableGuiWrap.h.
Member Function Documentation
template<class Gui > bool iqtgui::TRestorableGuiWrap< Gui >::CreateGui (QWidget * parentPtr) [inline, protected, virtual]
Definition at line 47 of file TRestorableGuiWrap.h.
References iqtgui::TRestorableGuiWrap< Gui >::OnRestoreSettings().
template<class Gui > bool iqtgui::TRestorableGuiWrap< Gui >::DestroyGui () [inline, protected, virtual]
Definition at line 60 of file TRestorableGuiWrap.h.
References iqtgui::TRestorableGuiWrap< Gui >::OnSaveSettings().
template<class Gui> virtual void iqtgui::TRestorableGuiWrap< Gui >::OnRestoreSettings (const QSettings & settings) [protected, pure virtual]
Implemented in iqtdoc::CMultiDocumentWorkspaceGuiComp, iqtgui::CComposedGuiComp, iqtgui::CSimpleMainWindowGuiComp, iqtdoc::TQtDocumentManagerWrap< idoc::CMultiDocumentManagerBase, iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QMdiArea > > >, and iqtdoc::TQtDocumentManagerWrap< idoc::CSingleDocumentManagerBase, iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QWidget > > >.
Referenced by iqtgui::TRestorableGuiWrap< Gui >::CreateGui().
template<class Gui> virtual void iqtgui::TRestorableGuiWrap< Gui >::OnSaveSettings (QSettings & settings) const [protected, pure virtual]
Implemented in iqtdoc::CMultiDocumentWorkspaceGuiComp, iqtgui::CComposedGuiComp, iqtgui::CSimpleMainWindowGuiComp, iqtdoc::TQtDocumentManagerWrap< idoc::CMultiDocumentManagerBase, iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QMdiArea > > >, and iqtdoc::TQtDocumentManagerWrap< idoc::CSingleDocumentManagerBase, iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QWidget > > >.
Referenced by iqtgui::TRestorableGuiWrap< Gui >::DestroyGui().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iqtgui/TRestorableGuiWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy