ACF: iproc::TFileCachedProducerCompBase< Key, CacheObject > Class Template Reference
iproc::TFileCachedProducerCompBase< Key, CacheObject > Class Template Reference
Template base implementation iproc::TILockedProducer caching (buffering) objects using file system.
#include <TFileCachedProducerCompBase.h>
Public Types
typedef icomp::CComponentBase BaseClass
typedef TILockedProducer< Key,
CacheObject > LockedProducerType
Public Member Functions
virtual const CacheObject * ProduceLockedObject (const Key &key)
Begin of accessing to cached element.
virtual void UnlockObject (const CacheObject *objectPtr)
End of accessing to cached element.
Protected Member Functions
bool PushKeyBack (const Key &key)
void CleanFileList ()
Removes cache files if there is too many of them.
virtual void OnCacheFileSaved (const Key &key, const istd::CString &cacheFilePath)
virtual void OnCacheFileRemoved (const Key &key, const istd::CString &cacheFilePath)
virtual istd::CString CalcCacheFilePath (const Key &key) const =0
Calculate unique file path of temporary file cache object.
virtual int GetMaxCachedFilesCount () const =0
Get number of maximal cached files.
Detailed Description
template<class Key, class CacheObject>
class iproc::TFileCachedProducerCompBase< Key, CacheObject >
Template base implementation iproc::TILockedProducer caching (buffering) objects using file system.
Please note, that no memory caching is done - if you ask second time of existing (locked) object, second instance will be created and loaded.
Definition at line 27 of file TFileCachedProducerCompBase.h.
Member Typedef Documentation
template<class Key , class CacheObject > typedef icomp::CComponentBase iproc::TFileCachedProducerCompBase< Key, CacheObject >::BaseClass
Definition at line 32 of file TFileCachedProducerCompBase.h.
template<class Key , class CacheObject > typedef TILockedProducer<Key, CacheObject> iproc::TFileCachedProducerCompBase< Key, CacheObject >::LockedProducerType
Definition at line 33 of file TFileCachedProducerCompBase.h.
Member Function Documentation
template<class Key , class CacheObject > virtual istd::CString iproc::TFileCachedProducerCompBase< Key, CacheObject >::CalcCacheFilePath (const Key & key) const [protected, pure virtual]
Calculate unique file path of temporary file cache object.
Referenced by iproc::TFileCachedProducerCompBase< Key, CacheObject >::ProduceLockedObject(), and iproc::TFileCachedProducerCompBase< Key, CacheObject >::PushKeyBack().
template<class Key , class CacheObject > void iproc::TFileCachedProducerCompBase< Key, CacheObject >::CleanFileList () [inline, protected]
Removes cache files if there is too many of them.
Definition at line 184 of file TFileCachedProducerCompBase.h.
References iproc::TFileCachedProducerCompBase< Key, CacheObject >::GetMaxCachedFilesCount(), I_ASSERT, iproc::TFileCachedProducerCompBase< Key, CacheObject >::OnCacheFileRemoved(), and istd::CString::ToString().
template<class Key , class CacheObject > virtual int iproc::TFileCachedProducerCompBase< Key, CacheObject >::GetMaxCachedFilesCount () const [protected, pure virtual]
Get number of maximal cached files.
Referenced by iproc::TFileCachedProducerCompBase< Key, CacheObject >::CleanFileList().
template<class Key , class CacheObject > void iproc::TFileCachedProducerCompBase< Key, CacheObject >::OnCacheFileRemoved (const Key & key, const istd::CString & cacheFilePath) [inline, protected, virtual]
Definition at line 215 of file TFileCachedProducerCompBase.h.
Referenced by iproc::TFileCachedProducerCompBase< Key, CacheObject >::CleanFileList().
template<class Key , class CacheObject > void iproc::TFileCachedProducerCompBase< Key, CacheObject >::OnCacheFileSaved (const Key & key, const istd::CString & cacheFilePath) [inline, protected, virtual]
Definition at line 209 of file TFileCachedProducerCompBase.h.
Referenced by iproc::TFileCachedProducerCompBase< Key, CacheObject >::ProduceLockedObject().
template<class Key , class CacheObject > const CacheObject * iproc::TFileCachedProducerCompBase< Key, CacheObject >::ProduceLockedObject (const Key & key) [inline, virtual]
Begin of accessing to cached element.
Returns:
cached object, if it was possible to produce it for specified key.
Implements iproc::TILockedProducer< Key, CacheObject >.
Definition at line 86 of file TFileCachedProducerCompBase.h.
References iproc::TFileCachedProducerCompBase< Key, CacheObject >::CalcCacheFilePath(), istd::TPointerBase< Type >::GetPtr(), I_ASSERT, istd::CString::IsEmpty(), istd::TPointerBase< Type >::IsValid(), NULL, iproc::TFileCachedProducerCompBase< Key, CacheObject >::OnCacheFileSaved(), istd::TDelPtr< Type, Accessor >::PopPtr(), iser::IFileLoader::QF_NAMED_ONLY, iser::IFileTypeInfo::QF_NO_SAVING, and iser::IFileLoader::StateOk.
template<class Key , class CacheObject > bool iproc::TFileCachedProducerCompBase< Key, CacheObject >::PushKeyBack (const Key & key) [inline, protected]
Definition at line 167 of file TFileCachedProducerCompBase.h.
References iproc::TFileCachedProducerCompBase< Key, CacheObject >::CalcCacheFilePath(), and istd::CString::IsEmpty().
template<class Key , class CacheObject > void iproc::TFileCachedProducerCompBase< Key, CacheObject >::UnlockObject (const CacheObject * objectPtr) [inline, virtual]
End of accessing to cached element.
Implements iproc::TILockedProducer< Key, CacheObject >.
Definition at line 145 of file TFileCachedProducerCompBase.h.
References I_ASSERT, and NULL.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iproc/TFileCachedProducerCompBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy