icomp::TAttributeStaticInfo< Attribute > Class Template Reference
icomp::TAttributeStaticInfo< Attribute > Class Template Reference
#include <TAttributeStaticInfo.h>
Public Member Functions
TAttributeStaticInfo (icomp::CBaseComponentStaticInfo &staticInfo, const std::string &id, const std::string &description, const Attribute *defaultValuePtr, int flags, const istd::CClassInfo &relatedInterfaceInfo)
virtual const std::string & GetAttributeId () const
Get ID of this attribute.
virtual void AddRelatedMetaId (int metaGroupId, const std::string &id, int flags)
Add related interface to this attribute info.
virtual const std::string & GetAttributeDescription () const
Get description of this attribute.
virtual const iser::IObject * GetAttributeDefaultValue () const
Get default attribute value.
virtual const std::string & GetAttributeTypeName () const
Return attribute type description.
virtual IComponentStaticInfo::Ids GetRelatedMetaIds (int metaGroupId, int flags, int flagsMask) const
Get related meta information.
virtual int GetAttributeFlags () const
Get flags of this attribute.
Detailed Description
template<class Attribute>
class icomp::TAttributeStaticInfo< Attribute >
Definition at line 19 of file TAttributeStaticInfo.h.
Constructor & Destructor Documentation
template<class Attribute > icomp::TAttributeStaticInfo< Attribute >::TAttributeStaticInfo (icomp::CBaseComponentStaticInfo & staticInfo, const std::string & id, const std::string & description, const Attribute * defaultValuePtr, int flags, const istd::CClassInfo & relatedInterfaceInfo)
Definition at line 56 of file TAttributeStaticInfo.h.
References istd::CClassInfo::GetName(), istd::CClassInfo::IsValid(), istd::CClassInfo::IsVoid(), icomp::IComponentStaticInfo::MGI_INTERFACES, and icomp::CBaseComponentStaticInfo::RegisterAttributeInfo().
Member Function Documentation
template<class Attribute > void icomp::TAttributeStaticInfo< Attribute >::AddRelatedMetaId (int metaGroupId, const std::string & id, int flags) [virtual]
Add related interface to this attribute info.
Parameters:
relatedInterfaceInfo specify interface.
flags set of flags defined in icomp::IAttributeStaticInfo::AttributeFlags.
Implements icomp::IRealAttributeStaticInfo.
Definition at line 86 of file TAttributeStaticInfo.h.
References I_ASSERT, and icomp::IComponentStaticInfo::MGI_INTERFACES.
template<class Attribute > const iser::IObject * icomp::TAttributeStaticInfo< Attribute >::GetAttributeDefaultValue () const [virtual]
Get default attribute value.
Returns:
pointer to default attribute value, if set. Elsewhere it returns NULL.
Implements icomp::IAttributeStaticInfo.
Definition at line 118 of file TAttributeStaticInfo.h.
template<class Attribute > const std::string & icomp::TAttributeStaticInfo< Attribute >::GetAttributeDescription () const [virtual]
Get description of this attribute.
Implements icomp::IAttributeStaticInfo.
Definition at line 111 of file TAttributeStaticInfo.h.
template<class Attribute > int icomp::TAttributeStaticInfo< Attribute >::GetAttributeFlags () const [virtual]
Get flags of this attribute.
Implements icomp::IAttributeStaticInfo.
Definition at line 157 of file TAttributeStaticInfo.h.
template<class Attribute > const std::string & icomp::TAttributeStaticInfo< Attribute >::GetAttributeId () const [virtual]
Get ID of this attribute.
Implements icomp::IRealAttributeStaticInfo.
Definition at line 79 of file TAttributeStaticInfo.h.
template<class Attribute > const std::string & icomp::TAttributeStaticInfo< Attribute >::GetAttributeTypeName () const [virtual]
Return attribute type description.
Implements icomp::IAttributeStaticInfo.
Definition at line 125 of file TAttributeStaticInfo.h.
template<class Attribute > IComponentStaticInfo::Ids icomp::TAttributeStaticInfo< Attribute >::GetRelatedMetaIds (int metaGroupId, int flags, int flagsMask) const [virtual]
Get related meta information.
This information in normally used by references and factories to provide information about related interfaces.
Implements icomp::IAttributeStaticInfo.
Definition at line 132 of file TAttributeStaticInfo.h.
The documentation for this class was generated from the following file:
Include/icomp/TAttributeStaticInfo.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy