imath::CSampledFunction2d Class Reference
imath::CSampledFunction2d Class Reference
Implementation of the resampled 2D-function.
#include <CSampledFunction2d.h>
Public Member Functions
CSampledFunction2d ()
CSampledFunction2d (const CSampledFunction2d &function2d)
CSampledFunction2d (const imath::ISampledFunction2d &function2d)
CSampledFunction2d (const istd::CIndex2d &size, double defaultValue=0)
void Reset ()
bool CreateGrid2d (const istd::CIndex2d &size, double defaultValue=0)
istd::CIndex2d GetGridSize2d () const
double GetSampleValue (const istd::CIndex2d &index) const
void SetSampleValue (const istd::CIndex2d &index, double value)
virtual bool CreateFunction (double *dataPtr, const ArgumentType &sizes)
Create function from input data.
virtual int GetTotalSamplesCount () const
Get number of samples stored in this container.
virtual int GetGridSize (int dimensionIndex) const
Get number of samples for specified dimension.
virtual istd::CRange GetLogicalRange (int dimensionIndex) const
Get logical grid position range for specified dimension.
virtual istd::CRange GetResultValueRange (int dimensionIndex, int resultDimension=-1) const
Get range of result value for the given axis.
virtual bool GetValueAt (const ArgumentType &argument, ResultType &result) const
virtual ResultType GetValueAt (const ArgumentType &argument) const
Public Member Functions inherited from imath::TISampledFunction< ArgumentDimensions, ResultDimensions >
virtual int GetArgumentDimensionality () const
Get the number of argument components.
virtual int GetResultDimensionality () const
Get the number of result components.
Public Member Functions inherited from imath::TIMathFunction< istd::TIndex< ArgumentDimensions >, TVector< ResultDimensions > >
virtual bool GetValueAt (const istd::TIndex< ArgumentDimensions > &argument, TVector< ResultDimensions > &result) const =0
Get function value for specified argument value.
virtual TVector< ResultDimensions > GetValueAt (const istd::TIndex< ArgumentDimensions > &argument) const =0
Get function value for specified argument value.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Public Member Functions inherited from istd::IChangeable
virtual void BeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Starts the change transaction.
virtual void EndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Ends the change transaction.
virtual int GetSupportedOperations () const
Get set of flags for supported operations.
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Copy this object from another one.
virtual bool IsEqual (const IChangeable &object) const
Compare this object with another object.
virtual IChangeable * CloneMe (CompatibilityMode mode=CM_WITHOUT_REFS) const
Make a copy of this object.
Additional Inherited Members
Public Types inherited from imath::TISampledFunction< ArgumentDimensions, ResultDimensions >
typedef imath::TIMathFunction
< istd::TIndex
< ArgumentDimensions >
, imath::TVector
< ResultDimensions > > BaseClass
typedef BaseClass::ArgumentType ArgumentType
Public Types inherited from imath::TIMathFunction< istd::TIndex< ArgumentDimensions >, TVector< ResultDimensions > >
typedef istd::TIndex
< ArgumentDimensions > ArgumentType
typedef TVector< ResultDimensions > ResultType
Public Types inherited from istd::IChangeable
enum ChangeFlags {
CF_ACF_INTERNAL = 1 << 0, CF_MODEL = 1 << 1, CF_ABORTED = 1 << 2, CF_DELEGATED = 1 << 3,
CF_NO_UNDO = 1 << 5
}
enum SupportedOperations {
SO_NONE = 0, SO_OBSERVE = 1, SO_COPY = 2, SO_CLONE = 4,
SO_COMPARE = 8
}
Flags for supported operations.
enum CompatibilityMode { CM_STRICT, CM_WITHOUT_REFS, CM_WITH_REFS, CM_CONVERT }
Control how relationship betweeen objects are interpreted.
Protected Member Functions inherited from istd::IChangeable
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for begin change event.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for end change event.
Detailed Description
Implementation of the resampled 2D-function.
Definition at line 18 of file CSampledFunction2d.h.
Constructor & Destructor Documentation
imath::CSampledFunction2d::CSampledFunction2d ()
imath::CSampledFunction2d::CSampledFunction2d (const CSampledFunction2d & function2d)
imath::CSampledFunction2d::CSampledFunction2d (const imath::ISampledFunction2d & function2d)
imath::CSampledFunction2d::CSampledFunction2d (const istd::CIndex2d & size, double defaultValue = 0)
Member Function Documentation
virtual bool imath::CSampledFunction2d::CreateFunction (double * dataPtr, const ArgumentType & sizes) virtual
Create function from input data.
Implements imath::TISampledFunction< ArgumentDimensions, ResultDimensions >.
bool imath::CSampledFunction2d::CreateGrid2d (const istd::CIndex2d & size, double defaultValue = 0)
virtual int imath::CSampledFunction2d::GetGridSize (int dimensionIndex) const virtual
Get number of samples for specified dimension.
Implements imath::TISampledFunction< ArgumentDimensions, ResultDimensions >.
istd::CIndex2d imath::CSampledFunction2d::GetGridSize2d () const inline
Definition at line 52 of file CSampledFunction2d.h.
References istd::TArray< Element, Dimensions >::GetSizes().
virtual istd::CRange imath::CSampledFunction2d::GetLogicalRange (int dimensionIndex) const virtual
Get logical grid position range for specified dimension.
Logical position describes
Implements imath::TISampledFunction< ArgumentDimensions, ResultDimensions >.
virtual istd::CRange imath::CSampledFunction2d::GetResultValueRange (int dimensionIndex, int resultDimension = -1) const virtual
Get range of result value for the given axis.
Optionally some result dimension can be also specified.
Parameters
dimensionIndex index of argument dimension.
resultDimension optional index of result dimension, it can be negative if all dimensions are meaned.
Returns
range of possible values, or invalid range if it is unknown.
Implements imath::TISampledFunction< ArgumentDimensions, ResultDimensions >.
double imath::CSampledFunction2d::GetSampleValue (const istd::CIndex2d & index) const inline
Definition at line 58 of file CSampledFunction2d.h.
References istd::TArray< Element, Dimensions >::GetAt(), istd::TArray< Element, Dimensions >::GetSizes(), and istd::TIndex< Dimensions >::IsInside().
virtual int imath::CSampledFunction2d::GetTotalSamplesCount () const virtual
Get number of samples stored in this container.
Implements imath::TISampledFunction< ArgumentDimensions, ResultDimensions >.
virtual bool imath::CSampledFunction2d::GetValueAt (const ArgumentType & argument, ResultType & result) const virtual
virtual ResultType imath::CSampledFunction2d::GetValueAt (const ArgumentType & argument) const virtual
void imath::CSampledFunction2d::Reset ()
void imath::CSampledFunction2d::SetSampleValue (const istd::CIndex2d & index, double value) inline
Definition at line 66 of file CSampledFunction2d.h.
References istd::TArray< Element, Dimensions >::GetSizes(), istd::TIndex< Dimensions >::IsInside(), and istd::TArray< Element, Dimensions >::SetAt().
The documentation for this class was generated from the following file:
Include/imath/CSampledFunction2d.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy