ilog::TLoggerWrap< Base > Class Template Reference
ilog::TLoggerWrap< Base > Class Template Reference
Class wrapper implementing interface istd::ILogger sending log messages over ilog::IMessageConsumer.
#include <TLoggerWrap.h>
Public Member Functions
TLoggerWrap ()
virtual void SetLogPtr (ilog::IMessageConsumer *logPtr)
Install log.
virtual ilog::IMessageConsumer * GetLogPtr () const
Get log.
virtual void SetTracingEnabled (bool trace)
Enable/disable tracing.
virtual bool IsTracingEnabled () const
Returns true if tracing enabled.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Protected Member Functions
bool SendInfoMessage (int id, const QString &message, const QString &messageSource=QString(), int flags=0) const
Send info message to log.
bool SendWarningMessage (int id, const QString &message, const QString &messageSource=QString(), int flags=0) const
Send warning message to log.
bool SendErrorMessage (int id, const QString &message, const QString &messageSource=QString(), int flags=0) const
Send error message to log.
bool SendCriticalMessage (int id, const QString &message, const QString &messageSource=QString(), int flags=0) const
Send critical message to log.
bool SendInfoMessageOnce (int id, const QString &message, const QString &messageSource=QString(), int flags=0) const
Send once info message to log.
bool SendWarningMessageOnce (int id, const QString &message, const QString &messageSource=QString(), int flags=0) const
Send once warning message to log.
bool SendErrorMessageOnce (int id, const QString &message, const QString &messageSource=QString(), int flags=0) const
Send once error message to log.
bool SendCriticalMessageOnce (int id, const QString &message, const QString &messageSource=QString(), int flags=0) const
Send once critical message to log.
virtual bool IsLogConsumed (const istd::IInformationProvider::InformationCategory *categoryPtr=NULL, const int *flagsPtr=NULL) const
Check if any log message is consumed.
virtual bool SendLogMessage (istd::IInformationProvider::InformationCategory category, int id, const QString &message, const QString &messageSource, int flags=0) const
Send any message to log.
Protected Member Functions inherited from istd::ILogger
virtual void DecorateMessage (IInformationProvider::InformationCategory category, int id, int flags, QString &message, QString &messageSource) const
Decorate message parts before outputting.
Detailed Description
template<class Base>
class ilog::TLoggerWrap< Base >
Class wrapper implementing interface istd::ILogger sending log messages over ilog::IMessageConsumer.
Access to interface ilog::IMessageConsumer must be registered by user. To register it use interface ilog::ILoggable implemented by this wrapper.
Definition at line 24 of file TLoggerWrap.h.
Constructor & Destructor Documentation
template<class Base > ilog::TLoggerWrap< Base >::TLoggerWrap ()
Definition at line 165 of file TLoggerWrap.h.
Member Function Documentation
template<class Base > ilog::IMessageConsumer * ilog::TLoggerWrap< Base >::GetLogPtr () const inline virtual
Get log.
Implements ilog::ILoggable.
Definition at line 182 of file TLoggerWrap.h.
template<class Base > bool ilog::TLoggerWrap< Base >::IsLogConsumed (const istd::IInformationProvider::InformationCategory * categoryPtr = NULL, const int * flagsPtr = NULL) const protected virtual
Check if any log message is consumed.
Default implementation retuns false.
Reimplemented from istd::ILogger.
Definition at line 307 of file TLoggerWrap.h.
References NULL.
Referenced by ifile::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx::IsLogConsumed(), and ifile::TFileSerializerComp< ReadArchive, WriteArchive >::WriteArchiveEx::IsLogConsumed().
template<class Base > bool ilog::TLoggerWrap< Base >::IsTracingEnabled () const virtual
Returns true if tracing enabled.
Implements ilog::ILoggable.
Definition at line 198 of file TLoggerWrap.h.
template<class Base > bool ilog::TLoggerWrap< Base >::SendCriticalMessage (int id, const QString & message, const QString & messageSource = QString(), int flags = 0) const protected
Send critical message to log.
See Also
istd::IInformationProvider for message meaning documentation.
Parameters
id binary id identifying this message type for automatic processing.
message message text will be send.
messageSource optional human readable description of message source.
Definition at line 228 of file TLoggerWrap.h.
References istd::IInformationProvider::IC_CRITICAL.
template<class Base > bool ilog::TLoggerWrap< Base >::SendCriticalMessageOnce (int id, const QString & message, const QString & messageSource = QString(), int flags = 0) const protected
Send once critical message to log.
Agains to SendCriticalMessage the message will be sent only first time.
See Also
istd::IInformationProvider for message meaning documentation.
Parameters
id binary id identifying this message type for automatic processing.
message message text will be send.
messageSource optional human readable description of message source.
Definition at line 288 of file TLoggerWrap.h.
template<class Base > bool ilog::TLoggerWrap< Base >::SendErrorMessage (int id, const QString & message, const QString & messageSource = QString(), int flags = 0) const protected
Send error message to log.
See Also
istd::IInformationProvider for message meaning documentation.
Parameters
id binary id identifying this message type for automatic processing.
message message text will be send.
messageSource source of the message
Definition at line 221 of file TLoggerWrap.h.
References istd::IInformationProvider::IC_ERROR.
template<class Base > bool ilog::TLoggerWrap< Base >::SendErrorMessageOnce (int id, const QString & message, const QString & messageSource = QString(), int flags = 0) const protected
Send once error message to log.
Agains to SendErrorMessage the message will be sent only first time.
See Also
istd::IInformationProvider for message meaning documentation.
Parameters
id binary id identifying this message type for automatic processing.
message message text will be send.
messageSource source of the message
Definition at line 270 of file TLoggerWrap.h.
template<class Base > bool ilog::TLoggerWrap< Base >::SendInfoMessage (int id, const QString & message, const QString & messageSource = QString(), int flags = 0) const protected
Send info message to log.
See Also
istd::IInformationProvider for message meaning documentation.
Parameters
id binary id identifying this message type for automatic processing.
message message text will be send.
messageSource source of the message
Definition at line 207 of file TLoggerWrap.h.
References istd::IInformationProvider::IC_INFO.
template<class Base > bool ilog::TLoggerWrap< Base >::SendInfoMessageOnce (int id, const QString & message, const QString & messageSource = QString(), int flags = 0) const protected
Send once info message to log.
Agains to SendInfoMessage the message will be sent only first time.
See Also
istd::IInformationProvider for message meaning documentation.
Parameters
id binary id identifying this message type for automatic processing.
message message text will be send.
messageSource source of the message
Definition at line 235 of file TLoggerWrap.h.
template<class Base > bool ilog::TLoggerWrap< Base >::SendLogMessage (istd::IInformationProvider::InformationCategory category, int id, const QString & message, const QString & messageSource, int flags = 0) const protected virtual
Send any message to log.
Default implementation do nothing.
Parameters
category message category.
id binary id identifying this message type for automatical processing.
message message text will be send.
messageSource source of the message.
Returns
true, if it was possible to send this message and it is 'consumed'.
Reimplemented from istd::ILogger.
Definition at line 316 of file TLoggerWrap.h.
References NULL.
Referenced by ifile::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx::SendLogMessage(), and ifile::TFileSerializerComp< ReadArchive, WriteArchive >::WriteArchiveEx::SendLogMessage().
template<class Base > bool ilog::TLoggerWrap< Base >::SendWarningMessage (int id, const QString & message, const QString & messageSource = QString(), int flags = 0) const protected
Send warning message to log.
See Also
istd::IInformationProvider for message meaning documentation.
Parameters
id binary id identifying this message type for automatic processing.
message message text will be send.
messageSource source of the message
Definition at line 214 of file TLoggerWrap.h.
References istd::IInformationProvider::IC_WARNING.
template<class Base > bool ilog::TLoggerWrap< Base >::SendWarningMessageOnce (int id, const QString & message, const QString & messageSource = QString(), int flags = 0) const protected
Send once warning message to log.
Agains to SendWarningMessage the message will be sent only first time.
See Also
istd::IInformationProvider for message meaning documentation.
Parameters
id binary id identifying this message type for automatic processing.
message message text will be send.
messageSource source of the message
Definition at line 252 of file TLoggerWrap.h.
template<class Base > void ilog::TLoggerWrap< Base >::SetLogPtr (ilog::IMessageConsumer * logPtr) inline virtual
Install log.
Implements ilog::ILoggable.
Definition at line 175 of file TLoggerWrap.h.
template<class Base > void ilog::TLoggerWrap< Base >::SetTracingEnabled (bool trace) virtual
Enable/disable tracing.
Implements ilog::ILoggable.
Definition at line 191 of file TLoggerWrap.h.
The documentation for this class was generated from the following file:
Include/ilog/TLoggerWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy