iqt2d::IViewProvider Class Reference
iqt2d::IViewProvider Class Reference abstract
Interface for GUI objects managing view.
#include <IViewProvider.h>
Public Member Functions
virtual int GetViewId () const =0
Get ID indentifing this view.
virtual iview::IShapeView * GetView () const =0
Called when items should be removed from specified view.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Detailed Description
Interface for GUI objects managing view.
Definition at line 24 of file IViewProvider.h.
Member Function Documentation
virtual iview::IShapeView* iqt2d::IViewProvider::GetView () const pure virtual
Called when items should be removed from specified view.
Implemented in iqt2d::CMultiBitmapViewComp::CSingleView, and iqt2d::CViewProviderGuiComp.
Referenced by iqt2d::TViewExtenderCompBase< Base >::AddItemsToScene(), iqt2d::TViewExtenderCompBase< Base >::RemoveItemsFromScene(), and iqt2d::TViewExtenderCompBase< Base >::UpdateAllViews().
virtual int iqt2d::IViewProvider::GetViewId () const pure virtual
Get ID indentifing this view.
Typically this ID is 0 for first view, 1 for the second etc.
Implemented in iqt2d::CMultiBitmapViewComp::CSingleView, and iqt2d::CViewProviderGuiComp.
Referenced by iqt2d::TViewExtenderCompBase< Base >::AddItemsToScene().
The documentation for this class was generated from the following file:
Include/iqt2d/IViewProvider.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy