ACF: icomp::TInterfaceRegistrator< Interface > Class Template Reference
icomp::TInterfaceRegistrator< Interface > Class Template Reference
Simple helper class providing registration of template-specified interface.
#include <TInterfaceRegistrator.h>
Public Member Functions
TInterfaceRegistrator (CBaseComponentStaticInfo &staticInfo)
template<>
TInterfaceRegistrator (CBaseComponentStaticInfo &)
template<>
void * InterfaceExtractor (IComponent &)
Static Protected Member Functions
static void * InterfaceExtractor (IComponent &component)
Detailed Description
template<class Interface>
class icomp::TInterfaceRegistrator< Interface >
Simple helper class providing registration of template-specified interface.
Definition at line 18 of file TInterfaceRegistrator.h.
Constructor & Destructor Documentation
template<class Interface > icomp::TInterfaceRegistrator< Interface >::TInterfaceRegistrator (CBaseComponentStaticInfo & staticInfo) [inline]
Definition at line 31 of file TInterfaceRegistrator.h.
References istd::CClassInfo::GetName(), istd::CClassInfo::IsVoid(), and icomp::CBaseComponentStaticInfo::RegisterInterfaceExtractor().
template<> icomp::TInterfaceRegistrator< void >::TInterfaceRegistrator (CBaseComponentStaticInfo &) [inline]
Definition at line 42 of file TInterfaceRegistrator.h.
Member Function Documentation
template<> void * icomp::TInterfaceRegistrator< void >::InterfaceExtractor (IComponent &) [inline]
Definition at line 59 of file TInterfaceRegistrator.h.
References NULL.
template<class Interface > void * icomp::TInterfaceRegistrator< Interface >::InterfaceExtractor (IComponent & component) [inline, static, protected]
Definition at line 50 of file TInterfaceRegistrator.h.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/icomp/TInterfaceRegistrator.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy