ACF: iqtdoc::CMainWindowGuiComp Class Reference
iqtdoc::CMainWindowGuiComp Class Reference
Standard main window component for any document based application.
#include <CMainWindowGuiComp.h>
Public Types
enum GroupId { GI_APPLICATION = 0x200, GI_DOCUMENT, GI_UNDO, GI_RECENT_FILE }
typedef
iqtgui::CSimpleMainWindowGuiComp BaseClass
typedef
imod::TSingleModelObserverBase
< idoc::IDocumentManager > BaseClass2
Public Member Functions
I_ASSIGN_TO (m_documentManagerModelCompPtr, m_documentManagerCompPtr, true)
I_ASSIGN_TO (m_documentManagerCommandsCompPtr, m_documentManagerCompPtr, false)
CMainWindowGuiComp ()
virtual bool OnAttached (imod::IModel *modelPtr)
This call back function will be called, if an observable object is about to be attached.
virtual bool OnDetached (imod::IModel *modelPtr)
This call back function will be called, if an observable object is about to be detached.
Protected Slots
void OnNew ()
void OnOpen ()
void OnSave ()
void OnSaveAs ()
void OnPrint ()
void OnOpenDocument (const std::string *documentTypeIdPtr=NULL)
void OnQuit ()
void OnUndo ()
void OnRedo ()
void OnFullScreen ()
void OnCopyPathToClippboard ()
void OnOpenDocumentFolder ()
Protected Member Functions
virtual bool OpenFile (const istd::CString &fileName)
virtual void OnActiveViewChanged ()
virtual void OnActiveDocumentChanged ()
virtual void OnDragEnterEvent (QDragEnterEvent *dragEnterEventPtr)
virtual void OnDropEvent (QDropEvent *dropEventPtr)
void SetupNewCommand ()
bool HasDocumentTemplate () const
void UpdateUndoMenu ()
void OnNewDocument (const std::string &documentTypeId)
virtual bool SerializeRecentFileList (iser::IArchive &archive)
virtual void UpdateRecentFileList (const idoc::IDocumentManager::FileToTypeMap &fileToTypeMap)
virtual void RemoveFromRecentFileList (const istd::CString &filePath)
template<class Archive >
bool SerializeRecentFiles ()
virtual void UpdateFixedCommands (iqtgui::CHierarchicalCommand &fixedCommands)
virtual void UpdateViewCommands (iqtgui::CHierarchicalCommand &viewCommand)
virtual void UpdateToolsCommands (iqtgui::CHierarchicalCommand &toolsCommand)
virtual void UpdateMenuActions (iqtgui::CHierarchicalCommand &menuCommands)
virtual void OnGuiCreated ()
Called just after GUI is initialized.
virtual void OnGuiDestroyed ()
Called just before GUI is released.
virtual void OnRetranslate ()
Called when non-GUI elements (like commands) should be retranslated.
virtual void OnUpdate (int updateFlags, istd::IPolymorphic *updateParamsPtr)
virtual bool eventFilter (QObject *sourcePtr, QEvent *eventPtr)
virtual void OnComponentCreated ()
virtual void OnComponentDestroyed ()
Detailed Description
Standard main window component for any document based application.
Definition at line 32 of file CMainWindowGuiComp.h.
Member Typedef Documentation
typedef iqtgui::CSimpleMainWindowGuiComp iqtdoc::CMainWindowGuiComp::BaseClass
Reimplemented from iqtgui::CSimpleMainWindowGuiComp.
Definition at line 39 of file CMainWindowGuiComp.h.
typedef imod::TSingleModelObserverBase<idoc::IDocumentManager> iqtdoc::CMainWindowGuiComp::BaseClass2
Definition at line 40 of file CMainWindowGuiComp.h.
Member Enumeration Documentation
enum iqtdoc::CMainWindowGuiComp::GroupId
Enumerator:
GI_APPLICATION
GI_DOCUMENT
GI_UNDO
GI_RECENT_FILE
Reimplemented from iqtgui::CSimpleMainWindowGuiComp.
Definition at line 52 of file CMainWindowGuiComp.h.
Constructor & Destructor Documentation
iqtdoc::CMainWindowGuiComp::CMainWindowGuiComp ()
Member Function Documentation
virtual bool iqtdoc::CMainWindowGuiComp::eventFilter (QObject * sourcePtr, QEvent * eventPtr) [protected, virtual]
Reimplemented from iqtgui::CGuiComponentBase.
bool iqtdoc::CMainWindowGuiComp::HasDocumentTemplate () const [protected]
iqtdoc::CMainWindowGuiComp::I_ASSIGN_TO (m_documentManagerCommandsCompPtr , m_documentManagerCompPtr , false)
iqtdoc::CMainWindowGuiComp::I_ASSIGN_TO (m_documentManagerModelCompPtr , m_documentManagerCompPtr , true)
virtual void iqtdoc::CMainWindowGuiComp::OnActiveDocumentChanged () [protected, virtual]
virtual void iqtdoc::CMainWindowGuiComp::OnActiveViewChanged () [protected, virtual]
virtual bool iqtdoc::CMainWindowGuiComp::OnAttached (imod::IModel * modelPtr) [virtual]
This call back function will be called, if an observable object is about to be attached.
This function returns a true, if observable object is accepted by the implementation logic of the observer, otherwise the function returns a false.
Reimplemented from imod::TSingleModelObserverBase< idoc::IDocumentManager >.
virtual void iqtdoc::CMainWindowGuiComp::OnComponentCreated () [protected, virtual]
Reimplemented from iqtgui::CGuiComponentBase.
virtual void iqtdoc::CMainWindowGuiComp::OnComponentDestroyed () [protected, virtual]
Reimplemented from icomp::CComponentBase.
void iqtdoc::CMainWindowGuiComp::OnCopyPathToClippboard () [protected, slot]
virtual bool iqtdoc::CMainWindowGuiComp::OnDetached (imod::IModel * modelPtr) [virtual]
This call back function will be called, if an observable object is about to be detached.
Reimplemented from imod::TSingleModelObserverBase< idoc::IDocumentManager >.
virtual void iqtdoc::CMainWindowGuiComp::OnDragEnterEvent (QDragEnterEvent * dragEnterEventPtr) [protected, virtual]
virtual void iqtdoc::CMainWindowGuiComp::OnDropEvent (QDropEvent * dropEventPtr) [protected, virtual]
void iqtdoc::CMainWindowGuiComp::OnFullScreen () [protected, slot]
virtual void iqtdoc::CMainWindowGuiComp::OnGuiCreated () [protected, virtual]
Called just after GUI is initialized.
Reimplemented from iqtgui::CSimpleMainWindowGuiComp.
virtual void iqtdoc::CMainWindowGuiComp::OnGuiDestroyed () [protected, virtual]
Called just before GUI is released.
Reimplemented from iqtgui::CSimpleMainWindowGuiComp.
void iqtdoc::CMainWindowGuiComp::OnNew () [protected, slot]
void iqtdoc::CMainWindowGuiComp::OnNewDocument (const std::string & documentTypeId) [protected]
void iqtdoc::CMainWindowGuiComp::OnOpen () [protected, slot]
void iqtdoc::CMainWindowGuiComp::OnOpenDocument (const std::string * documentTypeIdPtr = NULL) [protected, slot]
void iqtdoc::CMainWindowGuiComp::OnOpenDocumentFolder () [protected, slot]
void iqtdoc::CMainWindowGuiComp::OnPrint () [protected, slot]
void iqtdoc::CMainWindowGuiComp::OnQuit () [protected, slot]
void iqtdoc::CMainWindowGuiComp::OnRedo () [protected, slot]
virtual void iqtdoc::CMainWindowGuiComp::OnRetranslate () [protected, virtual]
Called when non-GUI elements (like commands) should be retranslated.
Reimplemented from iqtgui::CSimpleMainWindowGuiComp.
void iqtdoc::CMainWindowGuiComp::OnSave () [protected, slot]
void iqtdoc::CMainWindowGuiComp::OnSaveAs () [protected, slot]
void iqtdoc::CMainWindowGuiComp::OnUndo () [protected, slot]
virtual void iqtdoc::CMainWindowGuiComp::OnUpdate (int updateFlags, istd::IPolymorphic * updateParamsPtr) [protected, virtual]
Reimplemented from imod::CSingleModelObserverBase.
virtual bool iqtdoc::CMainWindowGuiComp::OpenFile (const istd::CString & fileName) [protected, virtual]
virtual void iqtdoc::CMainWindowGuiComp::RemoveFromRecentFileList (const istd::CString & filePath) [protected, virtual]
virtual bool iqtdoc::CMainWindowGuiComp::SerializeRecentFileList (iser::IArchive & archive) [protected, virtual]
Referenced by SerializeRecentFiles().
template<class Archive > bool iqtdoc::CMainWindowGuiComp::SerializeRecentFiles () [inline, protected]
Definition at line 229 of file CMainWindowGuiComp.h.
References ibase::IApplicationInfo::AA_APPLICATION_NAME, ibase::IApplicationInfo::AA_COMPANY_NAME, iqt::GetQString(), and SerializeRecentFileList().
void iqtdoc::CMainWindowGuiComp::SetupNewCommand () [protected]
virtual void iqtdoc::CMainWindowGuiComp::UpdateFixedCommands (iqtgui::CHierarchicalCommand & fixedCommands) [protected, virtual]
Reimplemented from iqtgui::CSimpleMainWindowGuiComp.
virtual void iqtdoc::CMainWindowGuiComp::UpdateMenuActions (iqtgui::CHierarchicalCommand & menuCommands) [protected, virtual]
Reimplemented from iqtgui::CSimpleMainWindowGuiComp.
virtual void iqtdoc::CMainWindowGuiComp::UpdateRecentFileList (const idoc::IDocumentManager::FileToTypeMap & fileToTypeMap) [protected, virtual]
virtual void iqtdoc::CMainWindowGuiComp::UpdateToolsCommands (iqtgui::CHierarchicalCommand & toolsCommand) [protected, virtual]
Reimplemented from iqtgui::CSimpleMainWindowGuiComp.
void iqtdoc::CMainWindowGuiComp::UpdateUndoMenu () [protected]
virtual void iqtdoc::CMainWindowGuiComp::UpdateViewCommands (iqtgui::CHierarchicalCommand & viewCommand) [protected, virtual]
Reimplemented from iqtgui::CSimpleMainWindowGuiComp.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iqtdoc/CMainWindowGuiComp.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy