ifile::TFileSerializerComp< ReadArchive, WriteArchive >::WriteArchiveEx Class Reference
ifile::TFileSerializerComp< ReadArchive, WriteArchive >::WriteArchiveEx Class Reference
#include <TFileSerializerComp.h>
Public Types
typedef WriteArchive BaseClass
Public Member Functions
WriteArchiveEx (const QString &filePath, const iser::IVersionInfo *infoPtr, const TFileSerializerComp *loggerPtr)
Protected Member Functions
virtual bool IsLogConsumed (const istd::IInformationProvider::InformationCategory *, const int *flagsPtr=NULL) const
virtual bool SendLogMessage (istd::IInformationProvider::InformationCategory category, int id, const QString &message, const QString &messageSource, int flags=0) const
Detailed Description
template<class ReadArchive, class WriteArchive>
class ifile::TFileSerializerComp< ReadArchive, WriteArchive >::WriteArchiveEx
Definition at line 77 of file TFileSerializerComp.h.
Member Typedef Documentation
template<class ReadArchive , class WriteArchive > typedef WriteArchive ifile::TFileSerializerComp< ReadArchive, WriteArchive >::WriteArchiveEx::BaseClass
Definition at line 80 of file TFileSerializerComp.h.
Constructor & Destructor Documentation
template<class ReadArchive , class WriteArchive > ifile::TFileSerializerComp< ReadArchive, WriteArchive >::WriteArchiveEx::WriteArchiveEx (const QString & filePath, const iser::IVersionInfo * infoPtr, const TFileSerializerComp * loggerPtr) [inline]
Definition at line 82 of file TFileSerializerComp.h.
Member Function Documentation
template<class ReadArchive , class WriteArchive > virtual bool ifile::TFileSerializerComp< ReadArchive, WriteArchive >::WriteArchiveEx::IsLogConsumed (const istd::IInformationProvider::InformationCategory * , const int * flagsPtr = NULL) const [inline, protected, virtual]
Definition at line 90 of file TFileSerializerComp.h.
References istd::IInformationProvider::IC_INFO, ilog::TLoggerWrap< Base >::IsLogConsumed(), and NULL.
template<class ReadArchive , class WriteArchive > virtual bool ifile::TFileSerializerComp< ReadArchive, WriteArchive >::WriteArchiveEx::SendLogMessage (istd::IInformationProvider::InformationCategory category, int id, const QString & message, const QString & messageSource, int flags = 0) const [inline, protected, virtual]
Definition at line 98 of file TFileSerializerComp.h.
References ilog::TLoggerCompWrap< CFileTypeInfoComp >::DecorateMessage(), NULL, and ilog::TLoggerWrap< Base >::SendLogMessage().
The documentation for this class was generated from the following file:
Include/ifile/TFileSerializerComp.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy