ACF: iqtgui::TGuiObserverWrap< Gui, Observer > Class Template Reference
iqtgui::TGuiObserverWrap< Gui, Observer > Class Template Reference
[Set of helper classes.]
Join functionality of iqtgui::IGuiObject interface and imod::IObserver.
#include <TGuiObserverWrap.h>
Classes
class UpdateBlocker
Public Member Functions
TGuiObserverWrap ()
virtual bool OnAttached (imod::IModel *modelPtr)
virtual bool OnDetached (imod::IModel *modelPtr)
Protected Member Functions
virtual void SetUpdateFilter (int updateFlags)
Sets update flags for the editor.
virtual void OnGuiModelShown ()
Called when model is attached and GUI is shown.
virtual void OnGuiModelHidden ()
Called when model is detached or GUI is hidden.
virtual void OnGuiModelAttached ()
Called when model is attached and GUI is created.
virtual void OnGuiModelDetached ()
Called when model is detached or GUI is destroyed.
bool IsUpdateBlocked () const
Check if GUI updating is blocked.
virtual void UpdateEditor (int updateFlags=0)
Updates editor with model data.
virtual void UpdateModel () const
Updates model from editor.
virtual void OnGuiShown ()
virtual void OnGuiHidden ()
virtual void OnGuiCreated ()
virtual void OnGuiDestroyed ()
virtual void AfterUpdate (imod::IModel *modelPtr, int updateFlags, istd::IPolymorphic *updateParamsPtr)
virtual bool IsReadOnly () const
Returns true if the model data can be changed.
virtual void SetReadOnly (bool state)
Set flag that the model data can be changed.
Detailed Description
template<class Gui, class Observer>
class iqtgui::TGuiObserverWrap< Gui, Observer >
Join functionality of iqtgui::IGuiObject interface and imod::IObserver.
Definition at line 20 of file TGuiObserverWrap.h.
Constructor & Destructor Documentation
template<class Gui , class Observer > iqtgui::TGuiObserverWrap< Gui, Observer >::TGuiObserverWrap () [inline]
Definition at line 111 of file TGuiObserverWrap.h.
Member Function Documentation
template<class Gui , class Observer > void iqtgui::TGuiObserverWrap< Gui, Observer >::AfterUpdate (imod::IModel * modelPtr, int updateFlags, istd::IPolymorphic * updateParamsPtr) [inline, protected, virtual]
Reimplemented in iqtgui::CLogGuiComp.
Definition at line 278 of file TGuiObserverWrap.h.
References I_ASSERT, and NULL.
template<class Gui , class Observer > bool iqtgui::TGuiObserverWrap< Gui, Observer >::IsReadOnly () const [inline, protected, virtual]
Returns true if the model data can be changed.
Implements imod::IModelEditor.
Definition at line 304 of file TGuiObserverWrap.h.
template<class Gui , class Observer > bool iqtgui::TGuiObserverWrap< Gui, Observer >::IsUpdateBlocked () const [inline, protected]
Check if GUI updating is blocked.
Definition at line 202 of file TGuiObserverWrap.h.
Referenced by iqtgui::TGuiObserverWrap< Gui, Observer >::OnDetached(), iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiModelAttached(), and iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiModelDetached().
template<class Gui , class Observer > bool iqtgui::TGuiObserverWrap< Gui, Observer >::OnAttached (imod::IModel * modelPtr) [inline, virtual]
Reimplemented in iqt2d::CAnnulusParamsGuiComp, iqt2d::CAnnulusSegmentParamsGuiComp, iqt2d::CCircleParamsGuiComp, iqt2d::CLine2dParamsGuiComp, iqt2d::CQuadrangleParamsGuiComp, iqt2d::CRectangleParamsGuiComp, and iqtprm::CComposedParamsSetGuiComp.
Definition at line 124 of file TGuiObserverWrap.h.
References NULL, and iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiModelAttached().
template<class Gui , class Observer > bool iqtgui::TGuiObserverWrap< Gui, Observer >::OnDetached (imod::IModel * modelPtr) [inline, virtual]
Reimplemented in iqt2d::CAnnulusParamsGuiComp, iqt2d::CAnnulusSegmentParamsGuiComp, iqt2d::CCircleParamsGuiComp, iqt2d::CImageViewComp, iqt2d::CLine2dParamsGuiComp, iqt2d::CQuadrangleParamsGuiComp, iqt2d::CRectangleParamsGuiComp, iqtprm::CComposedParamsSetGuiComp, and iqtprm::CVariableParamGuiComp.
Definition at line 137 of file TGuiObserverWrap.h.
References iqtgui::TGuiObserverWrap< Gui, Observer >::IsUpdateBlocked(), iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiModelDetached(), and iqtgui::TGuiObserverWrap< Gui, Observer >::UpdateModel().
template<class Gui , class Observer > void iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiCreated () [inline, protected, virtual]
Reimplemented in icmpstr::CAttributeEditorComp, icmpstr::CPackageOverviewComp, icmpstr::CRegistryPropEditorComp, iqt2d::CAnnulusParamsGuiComp, iqt2d::CAnnulusSegmentParamsGuiComp, iqt2d::CImageViewComp, iqtgui::CFileSystemExplorerGuiComp, iqtgui::CLogGuiComp, iqtgui::CObjectPreviewGuiComp, iqtmm::CPlaybackControllerGuiComp, iqtprm::CComposedParamsSetGuiComp, iqtprm::CFileNameParamGuiComp, iqtprm::CSelectableGuiComp, iqtprm::CSelectionParamGuiComp, and iqtprm::CVariableParamGuiComp.
Definition at line 254 of file TGuiObserverWrap.h.
References NULL, and iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiModelAttached().
template<class Gui , class Observer > void iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiDestroyed () [inline, protected, virtual]
Reimplemented in icmpstr::CAttributeEditorComp, iqt2d::CAnnulusParamsGuiComp, iqt2d::CAnnulusSegmentParamsGuiComp, iqt2d::CImageViewComp, iqtgui::CObjectPreviewGuiComp, iqtprm::CComposedParamsSetGuiComp, iqtprm::CSelectionParamGuiComp, and iqtprm::CVariableParamGuiComp.
Definition at line 265 of file TGuiObserverWrap.h.
References NULL, and iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiModelDetached().
template<class Gui , class Observer > void iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiHidden () [inline, protected, virtual]
Definition at line 243 of file TGuiObserverWrap.h.
References NULL, and iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiModelHidden().
template<class Gui , class Observer > void iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiModelAttached () [inline, protected, virtual]
Called when model is attached and GUI is created.
Reimplemented in icmpstr::CRegistryPropEditorComp, iqt2d::CCircleParamsGuiComp, iqt2d::CLine2dParamsGuiComp, iqt2d::CQuadrangleParamsGuiComp, iqt2d::CRectangleParamsGuiComp, iqtgui::CLogGuiComp, iqtprm::CFileNameParamGuiComp, iqtprm::CParamsManagerGuiComp, and iqtprm::CSelectableGuiComp.
Definition at line 177 of file TGuiObserverWrap.h.
References imod::IModelEditor::CF_INIT_EDITOR, I_ASSERT, iqtgui::TGuiObserverWrap< Gui, Observer >::IsUpdateBlocked(), NULL, and iqtgui::TGuiObserverWrap< Gui, Observer >::UpdateEditor().
Referenced by iqtgui::TGuiObserverWrap< Gui, Observer >::OnAttached(), and iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiCreated().
template<class Gui , class Observer > void iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiModelDetached () [inline, protected, virtual]
Called when model is detached or GUI is destroyed.
Reimplemented in icmpstr::CAttributeEditorComp, icmpstr::CRegistryPropEditorComp, iqt2d::CCircleParamsGuiComp, iqt2d::CLine2dParamsGuiComp, iqt2d::CQuadrangleParamsGuiComp, iqt2d::CRectangleParamsGuiComp, iqtgui::CObjectPreviewGuiComp, iqtprm::CParamsManagerGuiComp, and iqtprm::CSelectableGuiComp.
Definition at line 191 of file TGuiObserverWrap.h.
References iqtgui::TGuiObserverWrap< Gui, Observer >::IsUpdateBlocked(), NULL, and iqtgui::TGuiObserverWrap< Gui, Observer >::UpdateModel().
Referenced by iqtgui::TGuiObserverWrap< Gui, Observer >::OnDetached(), and iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiDestroyed().
template<class Gui , class Observer > void iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiModelHidden () [inline, protected, virtual]
Called when model is detached or GUI is hidden.
Definition at line 171 of file TGuiObserverWrap.h.
Referenced by iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiHidden().
template<class Gui , class Observer > void iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiModelShown () [inline, protected, virtual]
Called when model is attached and GUI is shown.
Definition at line 165 of file TGuiObserverWrap.h.
Referenced by iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiShown().
template<class Gui , class Observer > void iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiShown () [inline, protected, virtual]
Definition at line 225 of file TGuiObserverWrap.h.
References NULL, and iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiModelShown().
template<class Gui , class Observer > void iqtgui::TGuiObserverWrap< Gui, Observer >::SetReadOnly (bool state) [inline, protected, virtual]
Set flag that the model data can be changed.
Returns:
true, if this feature is supported.
Implements imod::IModelEditor.
Definition at line 311 of file TGuiObserverWrap.h.
template<class Gui , class Observer > void iqtgui::TGuiObserverWrap< Gui, Observer >::SetUpdateFilter (int updateFlags) [inline, protected, virtual]
Sets update flags for the editor.
GUI editor will ignore all update events, which not matches the previously set filter.
Definition at line 158 of file TGuiObserverWrap.h.
template<class Gui , class Observer > void iqtgui::TGuiObserverWrap< Gui, Observer >::UpdateEditor (int updateFlags = 0) [inline, protected, virtual]
Updates editor with model data.
This method will be called only if GUI is connected.
Parameters:
updateFlags the same as changeFlag in istd::IChangeable.
Implements imod::IModelEditor.
Reimplemented in icmpstr::CAttributeEditorComp, icmpstr::CPackageOverviewComp, icmpstr::CRegistryPropEditorComp, iqt2d::CAnnulusParamsGuiComp, iqt2d::CAnnulusSegmentParamsGuiComp, iqt2d::CCircleParamsGuiComp, iqt2d::CImageViewComp, iqt2d::CLine2dParamsGuiComp, iqt2d::CQuadrangleParamsGuiComp, iqt2d::CRectangleParamsGuiComp, iqtgui::CFileSystemExplorerGuiComp, iqtgui::CImagePropertiesFrameComp, iqtgui::CImagePropertyGuiComp, iqtgui::CObjectPreviewGuiComp, iqtmm::CPlaybackControllerGuiComp, iqtprm::CComposedParamsSetGuiComp, iqtprm::CFileNameParamGuiComp, iqtprm::CParamsManagerGuiComp, iqtprm::CSelectableGuiComp, iqtprm::CSelectionParamGuiComp, iqtprm::CSelectionParamIndexGuiComp, and iqtprm::CVariableParamGuiComp.
Definition at line 211 of file TGuiObserverWrap.h.
Referenced by iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiModelAttached().
template<class Gui , class Observer > void iqtgui::TGuiObserverWrap< Gui, Observer >::UpdateModel () const [inline, protected, virtual]
Updates model from editor.
This method will be called only if GUI is connected and model is attached.
Implements imod::IModelEditor.
Reimplemented in icmpstr::CAttributeEditorComp, icmpstr::CRegistryPropEditorComp, iqt2d::CAnnulusParamsGuiComp, iqt2d::CAnnulusSegmentParamsGuiComp, iqt2d::CCircleParamsGuiComp, iqt2d::CImageViewComp, iqt2d::CLine2dParamsGuiComp, iqt2d::CQuadrangleParamsGuiComp, iqt2d::CRectangleParamsGuiComp, iqtgui::CFileSystemExplorerGuiComp, iqtgui::CImagePropertiesFrameComp, iqtgui::CImagePropertyGuiComp, iqtgui::CObjectPreviewGuiComp, iqtmm::CPlaybackControllerGuiComp, iqtprm::CComposedParamsSetGuiComp, iqtprm::CFileNameParamGuiComp, iqtprm::CParamsManagerGuiComp, iqtprm::CSelectableGuiComp, iqtprm::CSelectionParamGuiComp, iqtprm::CSelectionParamIndexGuiComp, and iqtprm::CVariableParamGuiComp.
Definition at line 217 of file TGuiObserverWrap.h.
Referenced by iqtgui::TGuiObserverWrap< Gui, Observer >::OnDetached(), and iqtgui::TGuiObserverWrap< Gui, Observer >::OnGuiModelDetached().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iqtgui/TGuiObserverWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy