icomp::ICompositeComponent Class Reference
icomp::ICompositeComponent Class Reference abstract
Component concept
Composite component interface.
#include <ICompositeComponent.h>
Public Member Functions
virtual IComponent * GetSubcomponent (const QByteArray &componentId) const =0
Get access to subcomponent using its ID.
virtual const IComponentContext * GetSubcomponentContext (const QByteArray &componentId) const =0
Get access to context of subcomponent using its ID.
virtual IComponent * CreateSubcomponent (const QByteArray &componentId) const =0
Create instance of subcomponent using its ID.
virtual void OnSubcomponentDeleted (const IComponent *subcomponentPtr)=0
Called if subcomponent is removed from memory.
Public Member Functions inherited from icomp::IComponent
virtual const ICompositeComponent * GetParentComponent (bool ownerOnly=false) const =0
Get parent of this component.
virtual void * GetInterface (const istd::CClassInfo &interfaceType, const QByteArray &subId="")=0
Get access to specified component interface.
virtual const IComponentContext * GetComponentContext () const =0
Get access to component context describing all application-specified component information loaded from components registry.
virtual void SetComponentContext (const icomp::IComponentContext *contextPtr, const ICompositeComponent *parentPtr, bool isParentOwner)=0
Set component context of this component.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Detailed Description
Composite component interface.
Composite component extends component funtionality providing manangement and access to subcomponents. Please note, that subId for icomp::IComponent::GetInterface will be associated with subcomponent for composed components.
Definition at line 19 of file ICompositeComponent.h.
Member Function Documentation
virtual IComponent* icomp::ICompositeComponent::CreateSubcomponent (const QByteArray & componentId) const pure virtual
Create instance of subcomponent using its ID.
Implemented in icomp::CCompositeComponent, and icomp::TSimComponentWrap< Base >.
Referenced by icomp::TComponentCloneWrap< BaseClass >::CloneMe(), icomp::TMultiFactoryMember< Interface >::CreateComponent(), and icomp::TFactoryMember< Interface >::CreateComponent().
virtual IComponent* icomp::ICompositeComponent::GetSubcomponent (const QByteArray & componentId) const pure virtual
Get access to subcomponent using its ID.
Implemented in icomp::CCompositeComponent, and icomp::TSimComponentWrap< Base >.
Referenced by icomp::TMultiReferenceMember< Interface >::EnsureInitialized(), and icomp::TReferenceMember< Interface >::EnsureInitialized().
virtual const IComponentContext* icomp::ICompositeComponent::GetSubcomponentContext (const QByteArray & componentId) const pure virtual
Get access to context of subcomponent using its ID.
Please note, that this does'n create component instance.
Implemented in icomp::CCompositeComponent, and icomp::TSimComponentWrap< Base >.
virtual void icomp::ICompositeComponent::OnSubcomponentDeleted (const IComponent * subcomponentPtr) pure virtual
Called if subcomponent is removed from memory.
Parameters
subcomponentPtr pointer to component beeing removed. It cannot be NULL.
Implemented in icomp::CCompositeComponent, and icomp::TSimComponentWrap< Base >.
Referenced by icomp::TComponentWrap< Component >::~TComponentWrap().
The documentation for this class was generated from the following file:
Include/icomp/ICompositeComponent.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy