iview::IColorShema Class Reference
iview::IColorShema Class Reference
Defines set of standard pens, brushes and simple management of unions.
#include <IColorShema.h>
Public Types
enum StandardPen {
SP_NORMAL, SP_SELECTED, SP_SELECTED_TICKER, SP_TICKER,
SP_IMPORTANT, SP_ORIENT_DARK, SP_ORIENT_BRIGHT, SP_NORMAL_DASH,
SP_SELECTED_DASH, SP_GUIDELINE1, SP_GUIDELINE2, SP_GUIDELINE3,
SP_BLACK, SP_WHITE, SP_RED, SP_GREEN,
SP_BLUE, SP_CYAN, SP_YELLOW, SP_MAGENTA,
SP_LAST = SP_MAGENTA
}
enum StandardBrush {
SB_NORMAL, SB_SELECTED, SB_TICKER, SB_SELECTED_TICKER,
SB_IMPORTANT, SB_BACKGROUND, SB_HALF_TRANSPARENT, SB_HALF_TRANSPARENT2,
SB_TRANSPARENT, SB_LAST = SB_TRANSPARENT
}
enum StandardFont { SF_NORMAL = 0, SF_LAST = SF_NORMAL }
enum StandardPensSet { SPS_NORMAL = 0, SPS_LAST = SPS_NORMAL }
enum TickerType {
TT_SMALL, TT_INACTIVE_SMALL, TT_SELECTED_INACTIVE_SMALL, TT_NORMAL,
TT_INACTIVE, TT_SELECTED_INACTIVE, TT_MOVE, TT_MOVE_CENTER,
TT_INSERT, TT_DELETE, TT_ROTATE, TT_SKEW,
TT_CHECKBOX_ON, TT_CHECKBOX_OFF, TT_LAST = TT_CHECKBOX_OFF
}
Defines a type of ticker.
typedef std::vector< const QPen * > PensPtrSet
Public Member Functions
virtual void Assign (const IColorShema &colorShema)=0
virtual const QPen & GetPen (StandardPen penType) const =0
virtual void SetPen (StandardPen penType, const QPen &pen)=0
virtual const QBrush & GetBrush (StandardBrush brushType) const =0
virtual void SetBrush (StandardBrush brushType, const QBrush &brush)=0
virtual const QFont & GetFont (StandardFont fontType) const =0
virtual void SetFont (StandardFont fontType, const QFont &font)=0
virtual const PensPtrSet & GetPensPtrSet (StandardPensSet pensSetType) const =0
virtual void SetPensPtrSet (StandardPensSet pensSetType, const PensPtrSet &pensSet)=0
virtual void DrawTicker (QPainter &drawContext, istd::CIndex2d point, TickerType tickerType) const =0
Draw a ticker.
virtual const i2d::CRect & GetTickerBox (TickerType tickerType) const =0
Get bounding box of ticker in position (0, 0).
virtual int GetLogicalLineWidth () const =0
Return width of line.
Detailed Description
Defines set of standard pens, brushes and simple management of unions.
Definition at line 32 of file IColorShema.h.
Member Typedef Documentation
typedef std::vector<const QPen*> iview::IColorShema::PensPtrSet
Definition at line 132 of file IColorShema.h.
Member Enumeration Documentation
enum iview::IColorShema::StandardBrush
Enumerator:
SB_NORMAL
SB_SELECTED
SB_TICKER
SB_SELECTED_TICKER
SB_IMPORTANT
SB_BACKGROUND
SB_HALF_TRANSPARENT
SB_HALF_TRANSPARENT2
SB_TRANSPARENT
SB_LAST
Definition at line 59 of file IColorShema.h.
enum iview::IColorShema::StandardFont
Enumerator:
SF_NORMAL
SF_LAST
Definition at line 72 of file IColorShema.h.
enum iview::IColorShema::StandardPen
Enumerator:
SP_NORMAL
SP_SELECTED
SP_SELECTED_TICKER
SP_TICKER
SP_IMPORTANT
SP_ORIENT_DARK
SP_ORIENT_BRIGHT
SP_NORMAL_DASH
SP_SELECTED_DASH
SP_GUIDELINE1
SP_GUIDELINE2
SP_GUIDELINE3
SP_BLACK
SP_WHITE
SP_RED
SP_GREEN
SP_BLUE
SP_CYAN
SP_YELLOW
SP_MAGENTA
SP_LAST
Definition at line 35 of file IColorShema.h.
enum iview::IColorShema::StandardPensSet
Enumerator:
SPS_NORMAL
SPS_LAST
Definition at line 77 of file IColorShema.h.
enum iview::IColorShema::TickerType
Defines a type of ticker.
Enumerator:
TT_SMALL
Small ticker.
TT_INACTIVE_SMALL
Inactive small ticker.
TT_SELECTED_INACTIVE_SMALL
Selected inactive small ticker.
TT_NORMAL
Normal (default active) ticker.
TT_INACTIVE
Inactive ticker.
TT_SELECTED_INACTIVE
Selected inactive ticker.
TT_MOVE
Ticker used to move object.
TT_MOVE_CENTER
Ticker used to move center pins.
TT_INSERT
Ticker used to add node.
TT_DELETE
Ticker used to delete node.
TT_ROTATE
Ticker used to rotate object.
TT_SKEW
Ticker used to skew object.
TT_CHECKBOX_ON
Ticker used to checkbox, when it is on.
TT_CHECKBOX_OFF
Ticker used to checkbox, when it is off.
TT_LAST
Max value.
Definition at line 84 of file IColorShema.h.
Member Function Documentation
virtual void iview::IColorShema::Assign (const IColorShema & colorShema) [pure virtual]
Implemented in iview::CColorShemaBase.
virtual void iview::IColorShema::DrawTicker (QPainter & drawContext, istd::CIndex2d point, TickerType tickerType) const [pure virtual]
Draw a ticker.
Implemented in iview::CColorShemaBase.
Referenced by iview::TMultiPolylineCalibrationShape< SegmentData >::DrawSelectionElements().
virtual const QBrush& iview::IColorShema::GetBrush (StandardBrush brushType) const [pure virtual]
Implemented in iview::CColorShema.
Referenced by iview::TViewImpl< Base >::DrawToContext().
virtual const QFont& iview::IColorShema::GetFont (StandardFont fontType) const [pure virtual]
Implemented in iview::CColorShema.
Referenced by iview::TViewImpl< Base >::DrawToContext().
virtual int iview::IColorShema::GetLogicalLineWidth () const [pure virtual]
Return width of line.
This value is used to check, if user touched a line. It doesn't depend on screen transform.
Implemented in iview::CColorShemaBase.
Referenced by iview::TMultiPolylineCalibrationShape< SegmentData >::IsCurveTouched(), and iview::TMultiPolylineCalibrationShape< SegmentData >::TrySelectSegments().
virtual const QPen& iview::IColorShema::GetPen (StandardPen penType) const [pure virtual]
Implemented in iview::CColorShema.
Referenced by iview::TMultiPolylineCalibrationShape< SegmentData >::DrawCurve(), and iview::TViewImpl< Base >::DrawToContext().
virtual const PensPtrSet& iview::IColorShema::GetPensPtrSet (StandardPensSet pensSetType) const [pure virtual]
Implemented in iview::CColorShema.
virtual const i2d::CRect& iview::IColorShema::GetTickerBox (TickerType tickerType) const [pure virtual]
Get bounding box of ticker in position (0, 0).
Implemented in iview::CColorShemaBase.
Referenced by iview::TMultiPolylineCalibrationShape< SegmentData >::IsTouched(), and iview::TMultiPolylineCalibrationShape< SegmentData >::OnMouseButton().
virtual void iview::IColorShema::SetBrush (StandardBrush brushType, const QBrush & brush) [pure virtual]
Implemented in iview::CColorShema.
virtual void iview::IColorShema::SetFont (StandardFont fontType, const QFont & font) [pure virtual]
Implemented in iview::CColorShema.
virtual void iview::IColorShema::SetPen (StandardPen penType, const QPen & pen) [pure virtual]
Implemented in iview::CColorShema.
virtual void iview::IColorShema::SetPensPtrSet (StandardPensSet pensSetType, const PensPtrSet & pensSet) [pure virtual]
Implemented in iview::CColorShema.
The documentation for this class was generated from the following file:
Include/iview/IColorShema.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy