istd::TRange< ValueType > Class Template Reference
istd::TRange< ValueType > Class Template Reference
Implementation of a abstract range defined by two values - minimum and maximum.
#include <TRange.h>
Public Member Functions
TRange ()
Constructs an empty range object.
TRange (const TRange &range)
Copy constructor.
TRange (ValueType minValue, ValueType maxValue)
Constructs a range object from two numbers.
bool IsValid () const
Return true if the bottom value is smaller or equal then the top value.
bool IsEmpty () const
Return true if the bottom value is equal to the top value.
bool IsValidNonEmpty () const
Return true if the range is valid and it is not empty.
ValueType GetMinValue () const
Get the bottom value.
ValueType & GetMinValueRef ()
Get reference to the bottom value.
void SetMinValue (ValueType minValue)
Set the bottom value.
ValueType GetMaxValue () const
Get the top value.
ValueType & GetMaxValueRef ()
Get reference to the top value.
void SetMaxValue (ValueType maxValue)
Set the top value.
void Reset ()
Set this range to be empty.
ValueType GetLength () const
Get length of this range.
TRange GetValidated () const
Get validated range, if it was invalid.
void GetValidated (TRange &result) const
Get validated range, if it was invalid.
void Validate ()
Force this range to be valid.
bool Contains (ValueType value) const
Returns true, if value is in range between top and bottom.
bool Contains (const TRange &range) const
Returns true, if this range is inside of the range.
bool IsIntersectedBy (const TRange &range) const
Check if this range is intersected by other range.
bool IsOutsideOf (const TRange &range) const
Check if this range is outside of the given range.
TRange GetTranslated (ValueType offset) const
Get translated position range.
void Translate (ValueType offset)
Translated position of this range.
TRange GetIntersection (const TRange &range) const
Get intersection with the second range.
void Intersection (const TRange &range)
Set this range to be intersection of two ranges.
TRange GetUnion (const TRange &range) const
Get union with the second range.
TRange GetUnion (double value) const
Get union with the second range.
void Unite (const TRange &range)
Set this range to be union of two ranges.
void Unite (double value)
Set this range to be union of two ranges.
TRange GetExpanded (const TRange &range) const
Get expanded range using the second range.
void Expand (const TRange &range)
Set this range to be expanded.
ValueType GetNearestInside (ValueType value) const
Get nearest value belonging to range.
ValueType GetClipped (ValueType value) const
Get value clipped to the range.
TRange GetClipped (const TRange &range) const
Get range clipped to the current range.
ValueType GetValueFromAlpha (double alpha) const
Get value based on 'alpha' factor.
double GetAlphaFromValue (ValueType value) const
Get value based on 'alpha' factor.
ValueType GetMappedTo (ValueType value, const TRange &range) const
Returns the value, that corresponds the input value inputValue in the other range range.
TRange GetApply (const TRange &range) const
Get a combined range.
TRange GetInvertApply (const TRange &range) const
TRange GetInverted () const
void SetInterpolated (const TRange &first, const TRange &second, double alpha)
Set this range to be linear interpolated using two other ranges and adjast alpha value.
TRange & operator= (const TRange &range)
bool operator== (const TRange &range) const
bool operator!= (const TRange &range) const
TRange operator* (double value) const
TRange operator/ (double value) const
TRange & operator*= (double value)
TRange & operator/= (double value)
Static Public Member Functions
static const TRange & GetNull ()
Return null range.
static const TRange & GetInvalid ()
Return invalid range.
static TRange GetValid (ValueType value1, ValueType value2)
Return always valid range.
Detailed Description
template<typename ValueType>
class istd::TRange< ValueType >
Implementation of a abstract range defined by two values - minimum and maximum.
Definition at line 17 of file TRange.h.
Constructor & Destructor Documentation
template<typename ValueType > istd::TRange< ValueType >::TRange ()
Constructs an empty range object.
IsEmpty() will return true for this object.
Definition at line 281 of file TRange.h.
template<typename ValueType > istd::TRange< ValueType >::TRange (const TRange< ValueType > & range)
Copy constructor.
Definition at line 289 of file TRange.h.
template<typename ValueType> istd::TRange< ValueType >::TRange (ValueType minValue, ValueType maxValue)
Constructs a range object from two numbers.
Definition at line 297 of file TRange.h.
Member Function Documentation
template<typename ValueType> bool istd::TRange< ValueType >::Contains (ValueType value) const inline
Returns true, if value is in range between top and bottom.
This range must be valid.
Definition at line 407 of file TRange.h.
Referenced by i2d::CRect::IsInside().
template<typename ValueType> bool istd::TRange< ValueType >::Contains (const TRange< ValueType > & range) const inline
Returns true, if this range is inside of the range.
Definition at line 416 of file TRange.h.
References istd::TRange< ValueType >::IsValid().
template<typename ValueType > void istd::TRange< ValueType >::Expand (const TRange< ValueType > & range) inline
Set this range to be expanded.
Expanding operation calculate simple sum for each components separately.
Definition at line 557 of file TRange.h.
Referenced by i2d::CRect::Expand().
template<typename ValueType> double istd::TRange< ValueType >::GetAlphaFromValue (ValueType value) const inline
Get value based on 'alpha' factor.
Parameters
alpha alpha factor. If it is 0, minimum range value will be returned. If it is 1, maximum range value will be returned. Rest values are linear interpolated.
Definition at line 618 of file TRange.h.
template<typename ValueType > TRange< ValueType > istd::TRange< ValueType >::GetApply (const TRange< ValueType > & range) const
Get a combined range.
It calculates combined range. Range [0, 1] is neutral element of this operation.
Definition at line 632 of file TRange.h.
template<typename ValueType> ValueType istd::TRange< ValueType >::GetClipped (ValueType value) const
Get value clipped to the range.
Definition at line 580 of file TRange.h.
template<typename ValueType> TRange< ValueType > istd::TRange< ValueType >::GetClipped (const TRange< ValueType > & range) const
Get range clipped to the current range.
Definition at line 594 of file TRange.h.
References istd::TRange< ValueType >::GetMaxValue(), istd::TRange< ValueType >::GetMinValue(), istd::TRange< ValueType >::SetMaxValue(), and istd::TRange< ValueType >::SetMinValue().
template<typename ValueType > TRange< ValueType > istd::TRange< ValueType >::GetExpanded (const TRange< ValueType > & range) const inline
Get expanded range using the second range.
Expanding operation calculate simple sum for each components separately.
Definition at line 550 of file TRange.h.
template<typename ValueType > TRange< ValueType > istd::TRange< ValueType >::GetIntersection (const TRange< ValueType > & range) const inline
Get intersection with the second range.
Definition at line 455 of file TRange.h.
template<typename ValueType > const TRange< ValueType > & istd::TRange< ValueType >::GetInvalid () inline static
Return invalid range.
Definition at line 766 of file TRange.h.
template<typename ValueType > TRange< ValueType > istd::TRange< ValueType >::GetInvertApply (const TRange< ValueType > & range) const
Definition at line 643 of file TRange.h.
template<typename ValueType > TRange< ValueType > istd::TRange< ValueType >::GetInverted () const
Definition at line 656 of file TRange.h.
template<typename ValueType > ValueType istd::TRange< ValueType >::GetLength () const inline
Get length of this range.
Length is difference between top and bottom values.
Definition at line 376 of file TRange.h.
Referenced by i2d::CRect::GetCenter(), i2d::CRect::GetHeight(), istd::TRange< ValueType >::GetMappedTo(), i2d::CRect::GetRectangle(), i2d::CRect::GetSize(), and i2d::CRect::GetWidth().
template<typename ValueType> ValueType istd::TRange< ValueType >::GetMappedTo (ValueType value, const TRange< ValueType > & range) const inline
Returns the value, that corresponds the input value inputValue in the other range range.
It is the same as range.GetValueFromAlpha(GetAlphaFromValue(value)).
Parameters
value value definde in this range. If it is equal to minimum value in this range, it will be mapped to minimum value of range. If it is equal to maximum value in this range, it will be mapped to maximum value of range. Rest values are linear interpolated.
Note
This value must be in current range.
Definition at line 625 of file TRange.h.
References istd::TRange< ValueType >::GetLength(), and istd::TRange< ValueType >::GetMinValue().
template<typename ValueType > ValueType istd::TRange< ValueType >::GetMaxValue () const inline
Get the top value.
Definition at line 347 of file TRange.h.
Referenced by istd::TRanges< ValueType >::GetAsList(), i2d::CRect::GetBottom(), i2d::CRectangle::GetBottom(), istd::TRange< ValueType >::GetClipped(), i2d::CRect::GetLeftBottom(), i2d::CRect::GetRight(), i2d::CRectangle::GetRight(), i2d::CRect::GetRightBottom(), i2d::CRect::GetRightTop(), istd::TRanges< ValueType >::IsInside(), i2d::CRect::Translate(), and istd::TRanges< ValueType >::Union().
template<typename ValueType > ValueType & istd::TRange< ValueType >::GetMaxValueRef () inline
Get reference to the top value.
Definition at line 354 of file TRange.h.
template<typename ValueType > ValueType istd::TRange< ValueType >::GetMinValue () const inline
Get the bottom value.
Definition at line 326 of file TRange.h.
Referenced by istd::TRanges< ValueType >::GetAsList(), i2d::CRect::GetCenter(), istd::TRange< ValueType >::GetClipped(), i2d::CRect::GetLeft(), i2d::CRectangle::GetLeft(), i2d::CRect::GetLeftBottom(), i2d::CRect::GetLeftTop(), istd::TRange< ValueType >::GetMappedTo(), i2d::CRect::GetRectangle(), i2d::CRect::GetRightTop(), i2d::CRect::GetTop(), i2d::CRectangle::GetTop(), istd::TRanges< ValueType >::IsInside(), i2d::CRect::Translate(), and istd::TRanges< ValueType >::Union().
template<typename ValueType > ValueType & istd::TRange< ValueType >::GetMinValueRef () inline
Get reference to the bottom value.
Definition at line 333 of file TRange.h.
template<typename ValueType> ValueType istd::TRange< ValueType >::GetNearestInside (ValueType value) const inline
Get nearest value belonging to range.
Definition at line 565 of file TRange.h.
template<typename ValueType > const TRange< ValueType > & istd::TRange< ValueType >::GetNull () inline static
Return null range.
Definition at line 759 of file TRange.h.
template<typename ValueType> TRange< ValueType > istd::TRange< ValueType >::GetTranslated (ValueType offset) const inline
Get translated position range.
Translation adds the offset value to minimal and mavimal values.
Definition at line 440 of file TRange.h.
template<typename ValueType > TRange< ValueType > istd::TRange< ValueType >::GetUnion (const TRange< ValueType > & range) const
Get union with the second range.
Definition at line 482 of file TRange.h.
References istd::TRange< ValueType >::IsValid().
template<typename ValueType > TRange< ValueType > istd::TRange< ValueType >::GetUnion (double value) const
Get union with the second range.
Definition at line 499 of file TRange.h.
template<typename ValueType> TRange< ValueType > istd::TRange< ValueType >::GetValid (ValueType value1, ValueType value2) inline static
Return always valid range.
Definition at line 750 of file TRange.h.
template<typename ValueType > TRange< ValueType > istd::TRange< ValueType >::GetValidated () const inline
Get validated range, if it was invalid.
Range is invalid if set min value is bigger than set max value. It returns range with smaller range value as minimum and bigger one as maximum.
Definition at line 383 of file TRange.h.
template<typename ValueType > void istd::TRange< ValueType >::GetValidated (TRange< ValueType > & result) const inline
Get validated range, if it was invalid.
Range is invalid if set min value is bigger than set max value. It returns range with smaller range value as minimum and bigger one as maximum.
Definition at line 392 of file TRange.h.
References istd::TRange< ValueType >::SetMaxValue(), and istd::TRange< ValueType >::SetMinValue().
template<typename ValueType > ValueType istd::TRange< ValueType >::GetValueFromAlpha (double alpha) const inline
Get value based on 'alpha' factor.
Parameters
alpha alpha factor. If it is 0, minimum range value will be returned. If it is 1, maximum range value will be returned. Rest values are linear interpolated.
Definition at line 611 of file TRange.h.
template<typename ValueType > void istd::TRange< ValueType >::Intersection (const TRange< ValueType > & range)
Set this range to be intersection of two ranges.
Definition at line 467 of file TRange.h.
Referenced by i2d::CRect::Intersection().
template<typename ValueType > bool istd::TRange< ValueType >::IsEmpty () const inline
Return true if the bottom value is equal to the top value.
Definition at line 312 of file TRange.h.
Referenced by i2d::CRect::IsEmpty(), and istd::TRanges< ValueType >::Union().
template<typename ValueType > bool istd::TRange< ValueType >::IsIntersectedBy (const TRange< ValueType > & range) const inline
Check if this range is intersected by other range.
Some range is intersected by another, if intercestion of this two ranges is not empty.
Definition at line 426 of file TRange.h.
template<typename ValueType > bool istd::TRange< ValueType >::IsOutsideOf (const TRange< ValueType > & range) const inline
Check if this range is outside of the given range.
Definition at line 433 of file TRange.h.
Referenced by i2d::CRect::IsOutside().
template<typename ValueType > bool istd::TRange< ValueType >::IsValid () const inline
Return true if the bottom value is smaller or equal then the top value.
Definition at line 305 of file TRange.h.
Referenced by istd::TRange< ValueType >::Contains(), istd::TRange< ValueType >::GetUnion(), i2d::CRect::Intersection(), i2d::CRect::IsValid(), and istd::TRange< ValueType >::Unite().
template<typename ValueType > bool istd::TRange< ValueType >::IsValidNonEmpty () const inline
Return true if the range is valid and it is not empty.
Definition at line 319 of file TRange.h.
Referenced by i2d::CRect::IsValidNonEmpty().
template<typename ValueType > bool istd::TRange< ValueType >::operator!= (const TRange< ValueType > & range) const inline
Definition at line 686 of file TRange.h.
template<typename ValueType > TRange< ValueType > istd::TRange< ValueType >::operator* (double value) const inline
Definition at line 704 of file TRange.h.
template<typename ValueType > TRange< ValueType > & istd::TRange< ValueType >::operator*= (double value) inline
Definition at line 728 of file TRange.h.
template<typename ValueType > TRange< ValueType > istd::TRange< ValueType >::operator/ (double value) const inline
Definition at line 716 of file TRange.h.
template<typename ValueType > TRange< ValueType > & istd::TRange< ValueType >::operator/= (double value) inline
Definition at line 738 of file TRange.h.
template<typename ValueType > TRange< ValueType > & istd::TRange< ValueType >::operator= (const TRange< ValueType > & range) inline
Definition at line 694 of file TRange.h.
template<typename ValueType > bool istd::TRange< ValueType >::operator== (const TRange< ValueType > & range) const inline
Definition at line 679 of file TRange.h.
template<typename ValueType > void istd::TRange< ValueType >::Reset ()
Set this range to be empty.
Definition at line 368 of file TRange.h.
Referenced by i2d::CRect::Reset().
template<typename ValueType > void istd::TRange< ValueType >::SetInterpolated (const TRange< ValueType > & first, const TRange< ValueType > & second, double alpha)
Set this range to be linear interpolated using two other ranges and adjast alpha value.
Definition at line 669 of file TRange.h.
template<typename ValueType> void istd::TRange< ValueType >::SetMaxValue (ValueType maxValue) inline
Set the top value.
Definition at line 361 of file TRange.h.
Referenced by istd::TRange< ValueType >::GetClipped(), istd::TRange< ValueType >::GetValidated(), i2d::CRect::SetBottom(), i2d::CRect::SetLeftBottom(), i2d::CRect::SetRight(), i2d::CRect::SetRightBottom(), i2d::CRect::SetRightTop(), and i2d::CRect::Translate().
template<typename ValueType> void istd::TRange< ValueType >::SetMinValue (ValueType minValue) inline
Set the bottom value.
Definition at line 340 of file TRange.h.
Referenced by istd::TRange< ValueType >::GetClipped(), istd::TRange< ValueType >::GetValidated(), i2d::CRect::SetLeft(), i2d::CRect::SetLeftBottom(), i2d::CRect::SetLeftTop(), i2d::CRect::SetRightTop(), i2d::CRect::SetTop(), and i2d::CRect::Translate().
template<typename ValueType> void istd::TRange< ValueType >::Translate (ValueType offset) inline
Translated position of this range.
Translation adds the offset value to minimal and mavimal values.
Definition at line 447 of file TRange.h.
template<typename ValueType > void istd::TRange< ValueType >::Unite (const TRange< ValueType > & range)
Set this range to be union of two ranges.
Definition at line 511 of file TRange.h.
References istd::TRange< ValueType >::IsValid().
Referenced by i2d::CRect::GetUnion(), and i2d::CRect::Union().
template<typename ValueType > void istd::TRange< ValueType >::Unite (double value)
Set this range to be union of two ranges.
Definition at line 531 of file TRange.h.
template<typename ValueType > void istd::TRange< ValueType >::Validate () inline
Force this range to be valid.
Range is invalid if set min value is bigger than set max value. It set smaller range value as minimum and bigger one as maximum.
Definition at line 400 of file TRange.h.
The documentation for this class was generated from the following file:
Include/istd/TRange.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy