i2d::TDataNodePolyline< NodeData > Class Template Reference
i2d::TDataNodePolyline< NodeData > Class Template Reference
Generic polyline implementation with additional information stored for each node.
#include <TDataNodePolyline.h>
Public Types
typedef CDataNodePolylineBase BaseClass
Public Types inherited from i2d::CDataNodePolylineBase
typedef CPolyline BaseClass
Public Types inherited from i2d::CPolyline
typedef CPolygon BaseClass
Public Types inherited from i2d::IObject2d
enum ChangeFlags { CF_OBJECT_POSITION = 1 << 20 }
Public Types inherited from istd::IChangeable
enum ChangeFlags {
CF_ACF_INTERNAL = 1 << 0, CF_MODEL = 1 << 1, CF_ABORTED = 1 << 2, CF_DELEGATED = 1 << 3,
CF_NO_UNDO = 1 << 5
}
enum SupportedOperations {
SO_NONE = 0, SO_OBSERVE = 1, SO_COPY = 2, SO_CLONE = 4,
SO_COMPARE = 8
}
Flags for supported operations.
enum CompatibilityMode { CM_STRICT, CM_WITHOUT_REFS, CM_WITH_REFS, CM_CONVERT }
Control how relationship betweeen objects are interpreted.
Public Member Functions
const NodeData & GetTNodeData (int nodeIndex) const
Get user data from the given node.
NodeData & GetTNodeDataRef (int nodeIndex)
Get reference of user data in the given node.
virtual const iser::ISerializable & GetNodeData (int nodeIndex) const
Get user data from the given node.
virtual iser::ISerializable & GetNodeDataRef (int nodeIndex)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
virtual void Clear ()
Removes all nodes.
virtual bool InsertNode (const i2d::CVector2d &node)
Insert a node at the end of node table.
virtual bool InsertNode (int index, const i2d::CVector2d &node)
Insert a node at specified index.
virtual bool RemoveNode (int index)
Remove a node at specified index.
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Public Member Functions inherited from i2d::CDataNodePolylineBase
virtual bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
Public Member Functions inherited from i2d::CPolyline
CPolyline ()
virtual bool IsClosed () const
virtual void SetClosed (bool state=true)
Set polyline to be opened or closed.
virtual int GetSegmentsCount () const
Return number of line segments.
virtual i2d::CLine2d GetSegmentLine (int segmentIndex) const
Return number of line segments.
virtual double GetLength () const
Get length of this polyline.
virtual i2d::CVector2d GetKneeVector (int nodeIndex) const
Return vector for knee, that has the same angle to both neighbor segments.
virtual int GetSupportedOperations () const
Get set of flags for supported operations.
virtual istd::IChangeable * CloneMe (CompatibilityMode mode=CM_WITHOUT_REFS) const
Make a copy of this object.
Public Member Functions inherited from i2d::CPolygon
CPolygon ()
virtual int GetNodesCount () const
Return size of node table.
virtual const i2d::CVector2d & GetNode (int index) const
Return node at specified index.
virtual void SetNode (int index, const i2d::CVector2d &node)
Set node at specified index.
virtual double GetOutlineLength () const
Get outline length of this polygon.
virtual CVector2d GetCenter () const
Returns center of this 2D-object.
virtual void MoveCenterTo (const CVector2d &position)
Move object to position position.
virtual i2d::CRectangle GetBoundingBox () const
Calculate bounding box (the same as above but returns result directly).
virtual bool Transform (const ITransformation2d &transformation, ITransformation2d::ExactnessMode mode=ITransformation2d::EM_NONE, double *errorFactorPtr=NULL)
Transform this object using some transformation.
virtual bool InvTransform (const ITransformation2d &transformation, ITransformation2d::ExactnessMode mode=ITransformation2d::EM_NONE, double *errorFactorPtr=NULL)
Do inverse transformation of this object.
virtual bool GetTransformed (const ITransformation2d &transformation, IObject2d &result, ITransformation2d::ExactnessMode mode=ITransformation2d::EM_NONE, double *errorFactorPtr=NULL) const
Calulate transformation of the object into second one.
virtual bool GetInvTransformed (const ITransformation2d &transformation, IObject2d &result, ITransformation2d::ExactnessMode mode=ITransformation2d::EM_NONE, double *errorFactorPtr=NULL) const
Calulate inverse transformation of the object into second one.
virtual bool IsEqual (const IChangeable &object) const
Public Member Functions inherited from i2d::CObject2dBase
CObject2dBase ()
CObject2dBase (const CObject2dBase &object2d)
virtual const ICalibration2d * GetCalibration () const
Get access to transformation object, which transforms a local logical coordinate system to global one.
virtual void SetCalibration (const ICalibration2d *calibrationPtr, bool releaseFlag=false)
Set calibration of this object.
virtual bool CopyFrom (const istd::IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Copy this object from another one.
Public Member Functions inherited from iser::ISerializable
virtual quint32 GetMinimalVersion (int versionId) const
Get minimal needed version to correct storing of this data.
Public Member Functions inherited from istd::IChangeable
virtual void BeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Starts the change transaction.
virtual void EndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Ends the change transaction.
virtual bool IsEqual (const IChangeable &object) const
Compare this object with another object.
virtual bool ResetData (CompatibilityMode mode=CM_WITHOUT_REFS)
Reset data to its default state.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Protected Member Functions
virtual void SetNodesCount (int count)
Set new nodes count.
Protected Member Functions inherited from istd::IChangeable
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for begin change event.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for end change event.
Detailed Description
template<class NodeData>
class i2d::TDataNodePolyline< NodeData >
Generic polyline implementation with additional information stored for each node.
Note
Template parameter NodeData must be derived from iser::ISerializable.
Definition at line 20 of file TDataNodePolyline.h.
Member Typedef Documentation
template<class NodeData> typedef CDataNodePolylineBase i2d::TDataNodePolyline< NodeData >::BaseClass
Definition at line 23 of file TDataNodePolyline.h.
Member Function Documentation
template<class NodeData > void i2d::TDataNodePolyline< NodeData >::Clear () inline virtual
Removes all nodes.
Reimplemented from i2d::CPolygon.
Definition at line 103 of file TDataNodePolyline.h.
template<class NodeData > bool i2d::TDataNodePolyline< NodeData >::CopyFrom (const IChangeable & object, CompatibilityMode mode = CM_WITHOUT_REFS) virtual
Reimplemented from i2d::CPolyline.
Definition at line 145 of file TDataNodePolyline.h.
References i2d::CObject2dBase::CopyFrom(), i2d::CPolygon::GetNode(), i2d::CPolygon::GetNodesCount(), and NULL.
template<class NodeData > const iser::ISerializable & i2d::TDataNodePolyline< NodeData >::GetNodeData (int nodeIndex) const inline virtual
Get user data from the given node.
Implements i2d::CDataNodePolylineBase.
Definition at line 81 of file TDataNodePolyline.h.
template<class NodeData > iser::ISerializable & i2d::TDataNodePolyline< NodeData >::GetNodeDataRef (int nodeIndex) inline virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Implements i2d::CDataNodePolylineBase.
Definition at line 91 of file TDataNodePolyline.h.
template<class NodeData > const NodeData & i2d::TDataNodePolyline< NodeData >::GetTNodeData (int nodeIndex) const inline
Get user data from the given node.
Definition at line 59 of file TDataNodePolyline.h.
template<class NodeData > NodeData & i2d::TDataNodePolyline< NodeData >::GetTNodeDataRef (int nodeIndex) inline
Get reference of user data in the given node.
Definition at line 69 of file TDataNodePolyline.h.
template<class NodeData > bool i2d::TDataNodePolyline< NodeData >::InsertNode (const i2d::CVector2d & node) inline virtual
Insert a node at the end of node table.
Reimplemented from i2d::CPolygon.
Reimplemented in i2d::CTubePolylineComp.
Definition at line 112 of file TDataNodePolyline.h.
template<class NodeData > bool i2d::TDataNodePolyline< NodeData >::InsertNode (int index, const i2d::CVector2d & node) inline virtual
Insert a node at specified index.
Reimplemented from i2d::CPolygon.
Reimplemented in i2d::CTubePolylineComp.
Definition at line 121 of file TDataNodePolyline.h.
template<class NodeData > bool i2d::TDataNodePolyline< NodeData >::RemoveNode (int index) virtual
Remove a node at specified index.
Reimplemented from i2d::CPolygon.
Definition at line 132 of file TDataNodePolyline.h.
template<class NodeData > void i2d::TDataNodePolyline< NodeData >::SetNodesCount (int nodesCount) protected virtual
Set new nodes count.
Reimplemented from i2d::CPolygon.
Reimplemented in i2d::CTubePolylineComp.
Definition at line 175 of file TDataNodePolyline.h.
The documentation for this class was generated from the following file:
Include/i2d/TDataNodePolyline.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy