ACF: ibase::TNamedWrap< BaseClass > Class Template Reference
ibase::TNamedWrap< BaseClass > Class Template Reference
[Set of helper classes.]
Template based implementation of a named object.
#include <TNamedWrap.h>
Public Member Functions
virtual const istd::CString & GetName () const
virtual void SetName (const istd::CString &name)
virtual bool IsNameFixed () const
Protected Member Functions
virtual bool SerializeName (iser::IArchive &archive)
Protected Attributes
istd::CString m_name
Detailed Description
template<class BaseClass>
class ibase::TNamedWrap< BaseClass >
Template based implementation of a named object.
This class is a pseudo-implementation of istd::INamed interface.
Definition at line 26 of file TNamedWrap.h.
Member Function Documentation
template<class BaseClass > const istd::CString & ibase::TNamedWrap< BaseClass >::GetName () const [inline, virtual]
Definition at line 45 of file TNamedWrap.h.
References ibase::TNamedWrap< BaseClass >::m_name.
Referenced by iqtgui::CSimpleMainWindowGuiComp::CreateMenu().
template<class BaseClass > bool ibase::TNamedWrap< BaseClass >::IsNameFixed () const [inline, virtual]
Definition at line 63 of file TNamedWrap.h.
template<class BaseClass > bool ibase::TNamedWrap< BaseClass >::SerializeName (iser::IArchive & archive) [inline, protected, virtual]
Definition at line 72 of file TNamedWrap.h.
References iser::IArchive::BeginTag(), iser::IArchive::EndTag(), ibase::TNamedWrap< BaseClass >::m_name, and iser::IArchive::Process().
template<class BaseClass > void ibase::TNamedWrap< BaseClass >::SetName (const istd::CString & name) [inline, virtual]
Reimplemented in iqtgui::CHierarchicalCommand.
Definition at line 52 of file TNamedWrap.h.
References ibase::TNamedWrap< BaseClass >::m_name.
Member Data Documentation
template<class BaseClass> istd::CString ibase::TNamedWrap< BaseClass >::m_name [protected]
Definition at line 38 of file TNamedWrap.h.
Referenced by ibase::TNamedWrap< BaseClass >::GetName(), ibase::TNamedWrap< BaseClass >::SerializeName(), and ibase::TNamedWrap< BaseClass >::SetName().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/ibase/TNamedWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy