icmm::CCmyk Class Reference
icmm::CCmyk Class Reference
Primitive for representation of CMYK color value.
#include <CCmyk.h>
Public Types
enum ComponentIndex {
CI_CYAN, CI_MAGENTA, CI_YELLOW, CI_BLACK,
CI_LAST = CI_BLACK
}
typedef TComposedColor< 4 > BaseClass
Public Types inherited from icmm::TComposedColor< 4 >
typedef imath::TVector< Size > BaseClass
typedef BaseClass::Elements Elements
Public Types inherited from imath::TVector< Size >
typedef double ElementType
typedef double Elements [Size]
Public Types inherited from istd::IChangeable
enum ChangeFlags {
CF_ACF_INTERNAL = 1 << 0, CF_MODEL = 1 << 1, CF_ABORTED = 1 << 2, CF_DELEGATED = 1 << 3,
CF_NO_UNDO = 1 << 5
}
enum SupportedOperations {
SO_NONE = 0, SO_OBSERVE = 1, SO_COPY = 2, SO_CLONE = 4,
SO_COMPARE = 8
}
Flags for supported operations.
enum CompatibilityMode { CM_STRICT, CM_WITHOUT_REFS, CM_WITH_REFS, CM_CONVERT }
Control how relationship betweeen objects are interpreted.
Public Member Functions
CCmyk (double c=0.0, double m=0.0, double y=0.0, double k=0.0)
CCmyk (const CCmyk &color)
double GetC () const
void SetC (double value)
double GetM () const
void SetM (double value)
double GetY () const
void SetY (double value)
double GetK () const
void SetK (double value)
bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
CCmyk operator+ (const CCmyk &color) const
CCmyk operator- (const CCmyk &color) const
CCmyk operator* (const CCmyk &color) const
CCmyk operator/ (const CCmyk &color) const
CCmyk operator* (double value) const
CCmyk operator/ (double value) const
const CCmyk & operator= (const CCmyk &color)
const CCmyk & operator+= (const CCmyk &color)
const CCmyk & operator-= (const CCmyk &color)
const CCmyk & operator*= (const CCmyk &color)
const CCmyk & operator/= (const CCmyk &color)
const CCmyk & operator*= (double value)
const CCmyk & operator/= (double value)
Public Member Functions inherited from icmm::TComposedColor< 4 >
TComposedColor ()
TComposedColor (const BaseClass &value)
TComposedColor (const imath::CVarVector &vector)
void GetRounded (const imath::IDoubleManip &manipulator, TComposedColor< Size > &result)
Get color after components value rounding with specified precision.
bool IsRoundedEqual (const TComposedColor< Size > &color, const imath::IDoubleManip &manipulator) const
Check if two values are equal after rounding.
bool IsSimilar (const TComposedColor< Size > &color, double tolerance=I_BIG_EPSILON) const
Allows to compare two colors with tolerance.
bool IsNormalized () const
Check if this color value is normalized.
void Normalize ()
Make this color to be normalized.
void GetNormalized (TComposedColor< Size > &result) const
Get normalized color.
TComposedColor< Size > operator+ (const TComposedColor< Size > &color) const
TComposedColor< Size > operator- (const TComposedColor< Size > &color) const
TComposedColor< Size > operator* (const TComposedColor< Size > &color) const
TComposedColor< Size > operator* (double value) const
TComposedColor< Size > operator/ (const TComposedColor< Size > &color) const
TComposedColor< Size > operator/ (double value) const
const TComposedColor< Size > & operator= (const TComposedColor< Size > &color)
const TComposedColor< Size > & operator= (double colorValue)
const TComposedColor< Size > & operator+= (const TComposedColor< Size > &color)
const TComposedColor< Size > & operator-= (const TComposedColor< Size > &color)
const TComposedColor< Size > & operator*= (const TComposedColor< Size > &color)
const TComposedColor< Size > & operator*= (double value)
const TComposedColor< Size > & operator/= (const TComposedColor< Size > &color)
const TComposedColor< Size > & operator/= (double value)
Public Member Functions inherited from imath::TVector< Size >
TVector ()
Create an uninitialized point.
TVector (const TVector< Size, double > &vector)
Copy constructor.
const double & GetElement (int i) const
Get element at specified i.
double & GetElementRef (int i)
Get reference to element at specified i.
void SetElement (int i, const double &value)
Set element at specified i.
void Reset ()
Set all coordinates to zero.
void Clear ()
Set all coordinates to zero.
const TVector< Size, double >
::Elements & GetElements () const
Get read-only access to internal element container.
TVector< Size, double >::Elements & GetElementsRef ()
Get access to internal element container.
void Translate (const TVector< Size, double > &vector)
Translate the point.
TVector< Size, double > GetTranslated (const TVector< Size, double > &vector)
Get translated point.
void GetTranslated (const TVector< Size, double > &vector, TVector< Size, double > &result)
/overloaded
void ScaledCumulate (const TVector< Size, double > &vector, doublescale)
Add second vector scaled by specified factor.
bool IsNull (doubletolerance=I_BIG_EPSILON) const
Check if this vector is null.
double GetDotProduct (const TVector< Size, double > &vector) const
Return dot product of two vectors.
double GetLength2 () const
Return euclidian length square.
double GetLength () const
Return euclidian length.
double GetDistance2 (const TVector< Size, double > &vector) const
Return distance square between two vectors.
double GetDistance (const TVector< Size, double > &vector) const
Return distance between two vectors.
double GetElementsSum () const
Get simple sum of all elements.
bool Normalize (doublelength=1.0)
Normalize vector to specified length.
bool GetNormalized (TVector< Size, double > &result, doublelength=1.0) const
Return normalized vector with the same direction and specified length.
void GetMinimal (const TVector< Size, double > &vector, TVector< Size, double > &result) const
Get vector with minimal elements values.
void GetMaximal (const TVector< Size, double > &vector, TVector< Size, double > &result) const
Get vector with maximal elements values.
bool Serialize (iser::IArchive &archive)
Serialize this vector to specified archive.
bool operator== (const TVector< Size, double > &vector) const
bool operator!= (const TVector< Size, double > &vector) const
bool operator< (const TVector< Size, double > &vector) const
bool operator> (const TVector< Size, double > &vector) const
bool operator<= (const TVector< Size, double > &vector) const
bool operator>= (const TVector< Size, double > &vector) const
TVector< Size, double > operator- () const
TVector< Size, double > operator- (const TVector< Size, double > &vector) const
TVector< Size, double > operator+ (const TVector< Size, double > &vector) const
TVector< Size, double > operator* (doublescalar) const
TVector< Size, double > operator/ (doublescalar) const
TVector< Size, double > & operator+= (const TVector< Size, double > &vector)
TVector< Size, double > & operator-= (const TVector< Size, double > &vector)
TVector< Size, double > & operator*= (doublescalar)
TVector< Size, double > & operator/= (doublescalar)
const double & operator[] (int i) const
double & operator[] (int i)
Public Member Functions inherited from iser::ISerializable
virtual quint32 GetMinimalVersion (int versionId) const
Get minimal needed version to correct storing of this data.
Public Member Functions inherited from istd::IChangeable
virtual void BeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Starts the change transaction.
virtual void EndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Ends the change transaction.
virtual int GetSupportedOperations () const
Get set of flags for supported operations.
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Copy this object from another one.
virtual bool IsEqual (const IChangeable &object) const
Compare this object with another object.
virtual IChangeable * CloneMe (CompatibilityMode mode=CM_WITHOUT_REFS) const
Make a copy of this object.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Additional Inherited Members
Static Public Member Functions inherited from imath::TVector< Size >
static int GetElementsCount ()
Get number of elements.
static bool SetElementsCount (int count)
Set number of elements.
static const TVector< Size,
double > & GetZero ()
Get vector with all coordinates set to 0.
Protected Member Functions inherited from istd::IChangeable
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for begin change event.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for end change event.
Protected Attributes inherited from imath::TVector< Size >
Elements m_elements
Detailed Description
Primitive for representation of CMYK color value.
Please note, that normal components values are in range [0, 1].
Definition at line 18 of file CCmyk.h.
Member Typedef Documentation
typedef TComposedColor<4> icmm::CCmyk::BaseClass
Definition at line 21 of file CCmyk.h.
Member Enumeration Documentation
enum icmm::CCmyk::ComponentIndex
Enumerator
CI_CYAN
CI_MAGENTA
CI_YELLOW
CI_BLACK
CI_LAST
Definition at line 23 of file CCmyk.h.
Constructor & Destructor Documentation
icmm::CCmyk::CCmyk (double c = 0.0, double m = 0.0, double y = 0.0, double k = 0.0) inline
Definition at line 70 of file CCmyk.h.
References CI_BLACK, CI_CYAN, CI_MAGENTA, CI_YELLOW, and imath::TVector< Size >::SetElement().
icmm::CCmyk::CCmyk (const CCmyk & color) inline
Definition at line 79 of file CCmyk.h.
Member Function Documentation
double icmm::CCmyk::GetC () const inline
Definition at line 90 of file CCmyk.h.
References CI_CYAN, and imath::TVector< Size >::GetElement().
double icmm::CCmyk::GetK () const inline
Definition at line 126 of file CCmyk.h.
References CI_BLACK, and imath::TVector< Size >::GetElement().
double icmm::CCmyk::GetM () const inline
Definition at line 102 of file CCmyk.h.
References CI_MAGENTA, and imath::TVector< Size >::GetElement().
double icmm::CCmyk::GetY () const inline
Definition at line 114 of file CCmyk.h.
References CI_YELLOW, and imath::TVector< Size >::GetElement().
CCmyk icmm::CCmyk::operator* (const CCmyk & color) const
CCmyk icmm::CCmyk::operator* (double value) const
const CCmyk & icmm::CCmyk::operator*= (const CCmyk & color) inline
Definition at line 164 of file CCmyk.h.
References icmm::TComposedColor< 4 >::operator*=().
const CCmyk & icmm::CCmyk::operator*= (double value) inline
Definition at line 180 of file CCmyk.h.
References icmm::TComposedColor< 4 >::operator*=().
CCmyk icmm::CCmyk::operator+ (const CCmyk & color) const
const CCmyk & icmm::CCmyk::operator+= (const CCmyk & color) inline
Definition at line 148 of file CCmyk.h.
References icmm::TComposedColor< 4 >::operator+=().
CCmyk icmm::CCmyk::operator- (const CCmyk & color) const
const CCmyk & icmm::CCmyk::operator-= (const CCmyk & color) inline
Definition at line 156 of file CCmyk.h.
References icmm::TComposedColor< 4 >::operator-=().
CCmyk icmm::CCmyk::operator/ (const CCmyk & color) const
CCmyk icmm::CCmyk::operator/ (double value) const
const CCmyk & icmm::CCmyk::operator/= (const CCmyk & color) inline
Definition at line 172 of file CCmyk.h.
References icmm::TComposedColor< 4 >::operator/=().
const CCmyk & icmm::CCmyk::operator/= (double value) inline
Definition at line 188 of file CCmyk.h.
References icmm::TComposedColor< 4 >::operator/=().
const CCmyk & icmm::CCmyk::operator= (const CCmyk & color) inline
Definition at line 140 of file CCmyk.h.
References icmm::TComposedColor< 4 >::operator=().
bool icmm::CCmyk::Serialize (iser::IArchive & archive) virtual
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See Also
iser::IArchive
Reimplemented from icmm::TComposedColor< 4 >.
void icmm::CCmyk::SetC (double value) inline
Definition at line 96 of file CCmyk.h.
References CI_CYAN, and imath::TVector< Size >::SetElement().
void icmm::CCmyk::SetK (double value) inline
Definition at line 132 of file CCmyk.h.
References CI_BLACK, and imath::TVector< Size >::SetElement().
void icmm::CCmyk::SetM (double value) inline
Definition at line 108 of file CCmyk.h.
References CI_MAGENTA, and imath::TVector< Size >::SetElement().
void icmm::CCmyk::SetY (double value) inline
Definition at line 120 of file CCmyk.h.
References CI_YELLOW, and imath::TVector< Size >::SetElement().
The documentation for this class was generated from the following file:
Include/icmm/CCmyk.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy