istd::IChangeable Class Reference
istd::IChangeable Class Reference
Common interface for model objects, which can be changed.
#include <IChangeable.h>
Public Types
enum ChangeFlags {
CF_ACF_INTERNAL = 1 << 0, CF_MODEL = 1 << 1, CF_ABORTED = 1 << 2, CF_DELEGATED = 1 << 3,
CF_NO_UNDO = 1 << 5
}
enum SupportedOperations {
SO_NONE = 0, SO_OBSERVE = 1, SO_COPY = 2, SO_CLONE = 4,
SO_COMPARE = 8
}
Flags for supported operations.
enum CompatibilityMode { CM_STRICT, CM_WITHOUT_REFS, CM_WITH_REFS, CM_CONVERT }
Control how relationship betweeen objects are interpreted.
Public Member Functions
virtual void BeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=0)
Starts the change transaction.
virtual void EndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=0)
Ends the change transaction.
virtual int GetSupportedOperations () const
Get set of flags for supported operations.
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Copy this object from another one.
virtual bool IsEqual (const IChangeable &object) const
Compare this object with another object.
virtual IChangeable * CloneMe (CompatibilityMode mode=CM_WITHOUT_REFS) const
Make a copy of this object.
Protected Member Functions
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for begin change event.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for end change event.
Detailed Description
Common interface for model objects, which can be changed.
Model changes are executed in two steps: begin and end. The caller can also put some flags and additional data to the update functions, to control the update logic.
Definition at line 18 of file IChangeable.h.
Member Enumeration Documentation
enum istd::IChangeable::ChangeFlags
Enumerator:
CF_ACF_INTERNAL
Internal ACF flag.
Indicate that internal update is done.
CF_MODEL
Indicate that data model is changed.
CF_ABORTED
Indicate, that update was aborted by user.
CF_DELEGATED
Change flag indicate that this change was delegated (is indirect) for example from agregated object.
CF_NO_UNDO
Used to avoid adding of changes to undo list.
Reimplemented in iprm::IParamsManager, imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >, icomp::IRegistry, icomp::IRegistryElement, idoc::IDocumentManager, ilog::IMessageContainer, iprm::IOptionsList, i2d::IObject2d, ibase::CDelegatedProgressManager, iprm::ISelectionParam, ibase::TContainer< ItemClass >, iimg::CReflectedBitmapBase, ibase::TContainer< QPair< istd::TSmartPtr< InterfaceClass >, QByteArray > >, idoc::IDocumentMetaInfo, iprm::IOptionsManager, and ibase::ICommandsProvider.
Definition at line 21 of file IChangeable.h.
enum istd::IChangeable::CompatibilityMode
Control how relationship betweeen objects are interpreted.
It is also used to define how objects are copied.
Enumerator:
CM_STRICT
If external references are different this object are not compatible and cannot be compared or copied.
Copy without references to external objects only if objects are compatible.
CM_WITHOUT_REFS
External references are simple ignored.
Copy without references to external objects.
CM_WITH_REFS
External references are part of object integrity.
For comparation external references must be equal, for copy operations they will be copied.
CM_CONVERT
Data of object are interpreted in context of external references.
For comparation the meaning of object (e.g. after transformation using externals) will be compared. Copying will converting the data to be compatible according to existing references to external objects.
Definition at line 82 of file IChangeable.h.
enum istd::IChangeable::SupportedOperations
Flags for supported operations.
This flags can be combined.
Enumerator:
SO_NONE
No operations are supported.
SO_OBSERVE
Observing of this object via observer-observable pattern.
SO_COPY
Copying from other object.
SO_CLONE
Creating of copy of this object.
SO_COMPARE
Comparsion with another object.
Definition at line 50 of file IChangeable.h.
Member Function Documentation
void istd::IChangeable::BeginChanges (int changeFlags, istd::IPolymorphic * changeParamsPtr = 0) [inline, virtual]
Starts the change transaction.
Note:
Please note that the changeFlags and changeParamsPtr must not be identical with the corresponded parameters in EndChanges().
See also:
EndChanges()
Reimplemented in istd::CChangeDelegator, istd::TUpdateManagerWrap< iser::ISerializable >, istd::TUpdateManagerWrap< iimg::CBitmap >, istd::TUpdateManagerWrap< iser::IObject >, istd::TUpdateManagerWrap< iimg::CGeneralBitmap >, istd::TUpdateManagerWrap< ibase::ICommandsProvider >, istd::TChangeBinder< IHierarchicalMessageContainer, CChangeDelegator >, istd::TChangeBinder< ibase::IHierarchicalCommand, CChangeDelegator >, and istd::TChangeBinder< Base, CChangeDelegator >.
Definition at line 164 of file IChangeable.h.
References OnBeginChanges().
IChangeable * istd::IChangeable::CloneMe (CompatibilityMode mode = CM_WITHOUT_REFS) const [inline, virtual]
Make a copy of this object.
Returns:
new instance or NULL, if this operation is not supported.
Reimplemented in i2d::CRectangle, i2d::CLine2d, i2d::CAffineTransformation2d, i2d::CPolygon, i2d::CCircle, i2d::CSplineSegment, i2d::CAnnulus, iimg::CBitmap, i2d::CQuadrangle, i2d::CParallelogram, i2d::CPolypoint, i2d::CPolyline, i2d::CPosition2d, ilog::CMessage, i2d::CSpline, iimg::CBitmapDocument, i2d::CAnnulusSegment, iimg::CGeneralBitmap, ilog::TExtMessage< Element >, i2d::COrientedCircle, imod::TModelWrap< iimg::CBitmap >, and imod::TModelWrap< ibase::ICommandsProvider >.
Definition at line 194 of file IChangeable.h.
References NULL.
bool istd::IChangeable::CopyFrom (const IChangeable & object, CompatibilityMode mode = CM_WITHOUT_REFS) [inline, virtual]
Copy this object from another one.
Default implementation in istd::IChangeable do nothing.
Reimplemented in i2d::CAffineTransformation2d, ilog::CMessageContainer, iimg::CBitmap, ilog::CMessage, iser::CReaderVersionInfo, i2d::CObject2dBase, iimg::CBitmapDocument, iimg::CGeneralBitmap, ilog::TExtMessage< Element >, iser::TCopySerializedWrap< iimg::CBitmap >, iser::TCopySerializedWrap< iser::IObject >, and iser::TCopySerializedWrap< ibase::ICommandsProvider >.
Definition at line 182 of file IChangeable.h.
void istd::IChangeable::EndChanges (int changeFlags, istd::IPolymorphic * changeParamsPtr = 0) [inline, virtual]
Ends the change transaction.
Note:
Please note that the changeFlags and changeParamsPtr must not be identical with the corresponded parameters in BeginChanges().
See also:
BeginChanges()
Reimplemented in istd::CChangeDelegator, istd::TUpdateManagerWrap< iser::ISerializable >, istd::TUpdateManagerWrap< iimg::CBitmap >, istd::TUpdateManagerWrap< iser::IObject >, istd::TUpdateManagerWrap< iimg::CGeneralBitmap >, istd::TUpdateManagerWrap< ibase::ICommandsProvider >, istd::TChangeBinder< IHierarchicalMessageContainer, CChangeDelegator >, istd::TChangeBinder< ibase::IHierarchicalCommand, CChangeDelegator >, and istd::TChangeBinder< Base, CChangeDelegator >.
Definition at line 170 of file IChangeable.h.
References OnEndChanges().
int istd::IChangeable::GetSupportedOperations () const [inline, virtual]
Get set of flags for supported operations.
See also:
SupportedOperations
Reimplemented in i2d::CRectangle, i2d::CLine2d, i2d::CPolygon, i2d::CCircle, i2d::CSplineSegment, i2d::CAnnulus, iimg::CBitmap, i2d::CQuadrangle, i2d::CParallelogram, i2d::CPolypoint, i2d::CPolyline, i2d::CPosition2d, i2d::CSpline, i2d::CAnnulusSegment, iimg::CGeneralBitmap, i2d::COrientedCircle, imod::TModelWrap< iimg::CBitmap >, and imod::TModelWrap< ibase::ICommandsProvider >.
Definition at line 176 of file IChangeable.h.
References SO_NONE.
bool istd::IChangeable::IsEqual (const IChangeable & object) const [inline, virtual]
Compare this object with another object.
Parameters:
object Object to be compared
Returns:
true if the objects are identical and false otherwise.
Reimplemented in i2d::CPosition2d, iser::TCopySerializedWrap< iimg::CBitmap >, iser::TCopySerializedWrap< iser::IObject >, and iser::TCopySerializedWrap< ibase::ICommandsProvider >.
Definition at line 188 of file IChangeable.h.
void istd::IChangeable::OnBeginChanges (int changeFlags, istd::IPolymorphic * changeParamsPtr) [inline, protected, virtual]
Callback function for begin change event.
Please note, that in some cases no following OnEndChanges can be called.
Reimplemented in imod::TModelWrap< iimg::CBitmap >, and imod::TModelWrap< ibase::ICommandsProvider >.
Definition at line 202 of file IChangeable.h.
Referenced by BeginChanges().
void istd::IChangeable::OnEndChanges (int changeFlags, istd::IPolymorphic * changeParamsPtr) [inline, protected, virtual]
Callback function for end change event.
Reimplemented in iqtdoc::CMultiDocumentWorkspaceGuiComp, iqtdoc::CSingleDocumentWorkspaceGuiComp, ibase::CDelegatedProgressManager, iqtgui::CProgressManagerGuiComp, istd::TCachedUpdateManagerWrap< iser::ISerializable >, istd::TCachedUpdateManagerWrap< iimg::CGeneralBitmap >, imod::TModelWrap< iimg::CBitmap >, imod::TModelWrap< ibase::ICommandsProvider >, and iimg::CBitmapSurface.
Definition at line 207 of file IChangeable.h.
Referenced by EndChanges().
The documentation for this class was generated from the following file:
Include/istd/IChangeable.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy