iqtgui::CHierarchicalCommand Class Reference
iqtgui::CHierarchicalCommand Class Reference
Implementation of hierarchical command based on QAction from Qt.
#include <CHierarchicalCommand.h>
Public Types
typedef QAction BaseClass
typedef iprm::CEnableableParam BaseClass2
typedef iprm::CNameParam BaseClass3
Public Types inherited from istd::IChangeable
enum ChangeFlags {
CF_ACF_INTERNAL = 1 << 0, CF_MODEL = 1 << 1, CF_ABORTED = 1 << 2, CF_DELEGATED = 1 << 3,
CF_NO_UNDO = 1 << 5
}
enum SupportedOperations {
SO_NONE = 0, SO_OBSERVE = 1, SO_COPY = 2, SO_CLONE = 4,
SO_COMPARE = 8
}
Flags for supported operations.
enum CompatibilityMode { CM_STRICT, CM_WITHOUT_REFS, CM_WITH_REFS, CM_CONVERT }
Control how relationship betweeen objects are interpreted.
Public Types inherited from istd::THierarchicalBase< ibase::IHierarchicalCommand >
typedef istd::TChangeDelegator
< ibase::IHierarchicalCommand > BaseClass
Public Types inherited from istd::TChangeDelegator< ibase::IHierarchicalCommand >
typedef istd::TChangeBinder
< ibase::IHierarchicalCommand,
CChangeDelegator > BaseClass
Public Types inherited from istd::TChangeBinder< ibase::IHierarchicalCommand, CChangeDelegator >
typedef ibase::IHierarchicalCommand BaseClass
typedef CChangeDelegator BaseClass2
Public Types inherited from istd::TIHierarchical< Interface >
enum HierarchicalFlags { HF_CHILDS_SUPPORTED = 0x01, HF_PARENT_SUPPORTED = 0x02 }
Flags describing supported features of this hierarchical graph.
typedef Interface InterfaceType
Public Types inherited from istd::CChangeDelegator
typedef istd::IChangeable BaseClass
Public Member Functions
CHierarchicalCommand (const QString &name="", int priority=100, int staticFlags=CF_GLOBAL_MENU, int groupId=GI_NORMAL)
void SetPriority (int priority)
void SetStaticFlags (int flags)
void SetGroupId (int groupId)
void ResetChilds ()
Reset list of childs.
void InsertChild (CHierarchicalCommand *commandPtr, bool releaseFlag=false, int index=-1)
Insert command to child list.
void RemoveChild (int index)
Remove child at specified index.
void JoinLinkFrom (const ibase::IHierarchicalCommand *rootPtr)
Joint the second root as links.
void SetVisuals (const QString &name, const QString &shortName, const QString &description, const QIcon &icon=QIcon())
Set all visual elements of this command.
virtual int GetPriority () const
virtual int GetGroupId () const
virtual int GetStaticFlags () const
virtual bool Execute (istd::IPolymorphic *contextPtr)
virtual int GetChildsCount () const
Get number of childs.
virtual ibase::ICommand * GetChild (int index) const
Get child value.
virtual void SetName (const QString &name)
Set the object name.
virtual bool SetEnabled (bool isEnabled=true)
Set something to isEnabled state.
virtual bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
Public Member Functions inherited from iprm::CEnableableParam
CEnableableParam (bool isEnabled=true)
virtual bool IsEnabled () const
Return a true, if something is enabled.
virtual bool IsEnablingAllowed () const
Return a true, if something can be enabled.
Public Member Functions inherited from iser::ISerializable
virtual quint32 GetMinimalVersion (int versionId) const
Get minimal needed version to correct storing of this data.
Public Member Functions inherited from istd::IChangeable
virtual int GetSupportedOperations () const
Get set of flags for supported operations.
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Copy this object from another one.
virtual bool IsEqual (const IChangeable &object) const
Compare this object with another object.
virtual IChangeable * CloneMe (CompatibilityMode mode=CM_WITHOUT_REFS) const
Make a copy of this object.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Public Member Functions inherited from iprm::CNameParam
virtual const QString & GetName () const
Get the object name.
virtual bool IsNameFixed () const
Return true, if the name setting is enabled.
Public Member Functions inherited from istd::THierarchicalBase< ibase::IHierarchicalCommand >
THierarchicalBase ()
virtual void SetParentPtr (typename ibase::IHierarchicalCommand::InterfaceType *parentPtr)
virtual int GetHierarchicalFlags () const
virtual typename
ibase::IHierarchicalCommand::InterfaceType * GetParent () const
Public Member Functions inherited from istd::TChangeDelegator< ibase::IHierarchicalCommand >
TChangeDelegator ()
TChangeDelegator (istd::IChangeable *slavePtr)
Public Member Functions inherited from istd::TChangeBinder< ibase::IHierarchicalCommand, CChangeDelegator >
virtual void BeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
virtual void EndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Public Member Functions inherited from istd::CChangeDelegator
CChangeDelegator ()
CChangeDelegator (istd::IChangeable *slavePtr)
virtual void SetSlavePtr (istd::IChangeable *slavePtr)
Gets the slave object pointer.
virtual istd::IChangeable * GetSlavePtr () const
Sets the slave object pointer.
Protected Slots
void OnTriggered ()
Protected Member Functions
int FindTheSameCommand (const ibase::IHierarchicalCommand &command) const
Find the same command in child list.
int FindInsertingIndex (int priority) const
Find index where element with specified priority should be inserted.
Protected Member Functions inherited from istd::IChangeable
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for begin change event.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for end change event.
Additional Inherited Members
Protected Attributes inherited from iprm::CNameParam
QString m_name
Protected Attributes inherited from istd::THierarchicalBase< ibase::IHierarchicalCommand >
typename
ibase::IHierarchicalCommand::InterfaceType * m_parentPtr
Detailed Description
Implementation of hierarchical command based on QAction from Qt.
Definition at line 29 of file CHierarchicalCommand.h.
Member Typedef Documentation
typedef QAction iqtgui::CHierarchicalCommand::BaseClass
Definition at line 38 of file CHierarchicalCommand.h.
typedef iprm::CEnableableParam iqtgui::CHierarchicalCommand::BaseClass2
Definition at line 39 of file CHierarchicalCommand.h.
typedef iprm::CNameParam iqtgui::CHierarchicalCommand::BaseClass3
Definition at line 40 of file CHierarchicalCommand.h.
Constructor & Destructor Documentation
iqtgui::CHierarchicalCommand::CHierarchicalCommand (const QString & name = "", int priority = 100, int staticFlags = CF_GLOBAL_MENU, int groupId = GI_NORMAL) explicit
Member Function Documentation
virtual bool iqtgui::CHierarchicalCommand::Execute (istd::IPolymorphic * contextPtr) virtual
int iqtgui::CHierarchicalCommand::FindInsertingIndex (int priority) const protected
Find index where element with specified priority should be inserted.
int iqtgui::CHierarchicalCommand::FindTheSameCommand (const ibase::IHierarchicalCommand & command) const protected
Find the same command in child list.
Parameters
command command will be used as search template.
Returns
index of found child or negative value, if no child is found.
virtual ibase::ICommand* iqtgui::CHierarchicalCommand::GetChild (int index) const virtual
Get child value.
Reimplemented from istd::THierarchicalBase< ibase::IHierarchicalCommand >.
Referenced by iqtgui::CCommandTools::CreateMenu().
virtual int iqtgui::CHierarchicalCommand::GetChildsCount () const virtual
Get number of childs.
For single direction graph when only parent connection is stored it will be always 0. To check if this feature is supported check HF_CHILDS_SUPPORTED in flags.
Reimplemented from istd::THierarchicalBase< ibase::IHierarchicalCommand >.
Referenced by iqtgui::CCommandTools::CreateMenu().
virtual int iqtgui::CHierarchicalCommand::GetGroupId () const virtual
Referenced by iqtgui::CCommandTools::CreateMenu().
virtual int iqtgui::CHierarchicalCommand::GetPriority () const virtual
virtual int iqtgui::CHierarchicalCommand::GetStaticFlags () const virtual
Referenced by iqtgui::CCommandTools::CreateMenu().
void iqtgui::CHierarchicalCommand::InsertChild (CHierarchicalCommand * commandPtr, bool releaseFlag = false, int index = -1)
Insert command to child list.
Please note, this pointer is not owned by this container and will not be removed.
Parameters
commandPtr pointer to child command instance. It cannot be NULL.
releaseFlag if true, command instance will be automatically removed.
index index position of command to be inserted. Negative value indicate end of collection. Please note, that position can be other in merged tree.
void iqtgui::CHierarchicalCommand::JoinLinkFrom (const ibase::IHierarchicalCommand * rootPtr)
Joint the second root as links.
Parameters
rootPtr pointer to root of commands tree. It cannot be NULL.
void iqtgui::CHierarchicalCommand::OnTriggered () protected slot
void iqtgui::CHierarchicalCommand::RemoveChild (int index)
Remove child at specified index.
void iqtgui::CHierarchicalCommand::ResetChilds ()
Reset list of childs.
virtual bool iqtgui::CHierarchicalCommand::Serialize (iser::IArchive & archive) virtual
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See Also
iser::IArchive
Reimplemented from iprm::CEnableableParam.
virtual bool iqtgui::CHierarchicalCommand::SetEnabled (bool isEnabled = true) virtual
Set something to isEnabled state.
The method returns true if the changing of the enabling status was allowed, otherwise false.
Reimplemented from iprm::CEnableableParam.
void iqtgui::CHierarchicalCommand::SetGroupId (int groupId)
virtual void iqtgui::CHierarchicalCommand::SetName (const QString & name) virtual
Set the object name.
Reimplemented from iprm::CNameParam.
void iqtgui::CHierarchicalCommand::SetPriority (int priority)
void iqtgui::CHierarchicalCommand::SetStaticFlags (int flags)
void iqtgui::CHierarchicalCommand::SetVisuals (const QString & name, const QString & shortName, const QString & description, const QIcon & icon = QIcon())
Set all visual elements of this command.
This method is designed to use in OnRetranslate() implementation and that's why it uses Qt QString.
Parameters
name general name, used in menus.
shortName short version of name used in toolbars.
description description used as tool tip.
icon icon shown in menus and toolbars.
The documentation for this class was generated from the following file:
Include/iqtgui/CHierarchicalCommand.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy