ACF: imath::TVarVector< Element > Class Template Reference
imath::TVarVector< Element > Class Template Reference
Simple implementation of variable-size vector.
#include <TVarVector.h>
Public Types
typedef Element ElementType
typedef std::vector< Element > Elements
Public Member Functions
TVarVector ()
Create the vector without components.
TVarVector (int componentsCount, const Element &value=Element())
Create vector and initialize number of components.
TVarVector (const TVarVector< Element > &vector)
Copy constructor.
template<int Size>
TVarVector (const TVector< Size, Element > &vector)
int GetElementsCount () const
Get number of elements.
bool SetElementsCount (int size, const Element &value=Element())
Set number of elements.
const Element & GetElement (int i) const
Get element at specified i.
Element & GetElementRef (int i)
Get reference to element at specified i.
void SetElement (int i, const Element &value)
Set element at specified i.
void Reset ()
Set size to zero.
void Reset (int elementsCount, const Element &value)
Set number of elements and set all elements to specified value.
void Clear ()
Set all coordinates to zero.
void SetElementsFrom (const TVarVector &vector, const Element &expansionValue=Element())
Set elemenents from other vector without resizing.
const Elements & GetElements () const
Get read-only access to internal element container.
Elements & GetElementsRef ()
Get access to internal element container.
void Translate (const TVarVector< Element > &vector)
Translate the point.
TVarVector< Element > GetTranslated (const TVarVector< Element > &vector)
Get translated point.
void GetTranslated (const TVarVector< Element > &vector, TVarVector< Element > &result)
/overloaded
void ScaledCumulate (const TVarVector< Element > &vector, Element scale)
Add second vector scaled by specified factor.
bool IsNull (Element tolerance=I_BIG_EPSILON) const
Check if this vector is null.
Element GetDotProduct (const TVarVector< Element > &vector) const
Return dot product of two vectors.
Element GetLength2 () const
Return euclidian length square.
Element GetLength () const
Return euclidian length.
Element GetDistance2 (const TVarVector< Element > &vector) const
Return distance square between two vectors.
Element GetDistance (const TVarVector< Element > &vector) const
Return distance between two vectors.
Element GetElementsSum () const
Get simple sum of all elements.
bool Normalize (Element length=1.0)
Normalize vector to specified length.
bool GetNormalized (TVarVector< Element > &result, Element length=1.0) const
Return normalized vector with the same direction and specified length.
void GetMinimal (const TVarVector< Element > &vector, TVarVector< Element > &result) const
Get vector with minimal elements values.
void GetMaximal (const TVarVector< Element > &vector, TVarVector< Element > &result) const
Get vector with maximal elements values.
bool Serialize (iser::IArchive &archive)
Serialize this vector to specified archive.
bool operator== (const TVarVector< Element > &vector) const
bool operator!= (const TVarVector< Element > &vector) const
bool operator< (const TVarVector< Element > &vector) const
bool operator> (const TVarVector< Element > &vector) const
bool operator<= (const TVarVector< Element > &vector) const
bool operator>= (const TVarVector< Element > &vector) const
TVarVector< Element > operator- () const
TVarVector< Element > operator+ (const TVarVector< Element > &vector) const
TVarVector< Element > operator- (const TVarVector< Element > &vector) const
TVarVector< Element > operator* (Element scalar) const
TVarVector< Element > operator/ (Element scalar) const
TVarVector< Element > & operator+= (const TVarVector< Element > &vector)
TVarVector< Element > & operator-= (const TVarVector< Element > &vector)
TVarVector< Element > & operator*= (Element scalar)
TVarVector< Element > & operator/= (Element scalar)
const Element & operator[] (int i) const
Element & operator[] (int i)
Detailed Description
template<class Element = double>
class imath::TVarVector< Element >
Simple implementation of variable-size vector.
Definition at line 21 of file TVarVector.h.
Member Typedef Documentation
template<class Element = double> typedef std::vector<Element> imath::TVarVector< Element >::Elements
Definition at line 25 of file TVarVector.h.
template<class Element = double> typedef Element imath::TVarVector< Element >::ElementType
Definition at line 24 of file TVarVector.h.
Constructor & Destructor Documentation
template<class Element > imath::TVarVector< Element >::TVarVector () [inline]
Create the vector without components.
Definition at line 222 of file TVarVector.h.
template<class Element> imath::TVarVector< Element >::TVarVector (int componentsCount, const Element & value = Element()) [inline, explicit]
Create vector and initialize number of components.
Definition at line 228 of file TVarVector.h.
template<class Element> imath::TVarVector< Element >::TVarVector (const TVarVector< Element > & vector) [inline]
Copy constructor.
Definition at line 235 of file TVarVector.h.
template<class Element = double> template<int Size> imath::TVarVector< Element >::TVarVector (const TVector< Size, Element > & vector) [inline]
Definition at line 43 of file TVarVector.h.
Member Function Documentation
template<class Element > void imath::TVarVector< Element >::Clear () [inline]
Set all coordinates to zero.
Definition at line 290 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount().
template<class Element> Element imath::TVarVector< Element >::GetDistance (const TVarVector< Element > & vector) const [inline]
Return distance between two vectors.
Definition at line 408 of file TVarVector.h.
References imath::TVarVector< Element >::GetDistance2().
template<class Element> Element imath::TVarVector< Element >::GetDistance2 (const TVarVector< Element > & vector) const [inline]
Return distance square between two vectors.
Definition at line 401 of file TVarVector.h.
Referenced by imath::TVarVector< Element >::GetDistance().
template<class Element> Element imath::TVarVector< Element >::GetDotProduct (const TVarVector< Element > & vector) const [inline]
Return dot product of two vectors.
Definition at line 371 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount(), and I_ASSERT.
Referenced by imath::TVarVector< Element >::GetLength2().
template<class Element > const Element & imath::TVarVector< Element >::GetElement (int i) const [inline]
Get element at specified i.
Definition at line 262 of file TVarVector.h.
References imath::TVarVector< Element >::operator[]().
Referenced by imath::TVarVector< Element >::GetMaximal(), and imath::TVarVector< Element >::GetMinimal().
template<class Element > Element & imath::TVarVector< Element >::GetElementRef (int i) [inline]
Get reference to element at specified i.
Definition at line 269 of file TVarVector.h.
References imath::TVarVector< Element >::operator[]().
template<class Element > const TVarVector< Element >::Elements & imath::TVarVector< Element >::GetElements () const [inline]
Get read-only access to internal element container.
Definition at line 312 of file TVarVector.h.
Referenced by imath::TVarMatrix< Element >::TVarMatrix().
template<class Element > int imath::TVarVector< Element >::GetElementsCount () const [inline]
Get number of elements.
Definition at line 244 of file TVarVector.h.
Referenced by imath::TVarVector< Element >::Clear(), imath::TVarVector< Element >::GetDotProduct(), imath::TVarVector< Element >::GetMaximal(), imath::TVarVector< Element >::GetMinimal(), imath::TVarVector< Element >::GetNormalized(), icmm::TColorGradient< GradientFunction >::GetValueAt(), imath::TVarVector< Element >::Normalize(), imath::TVarVector< Element >::operator*(), imath::TVarVector< Element >::operator*=(), imath::TVarVector< Element >::operator+(), imath::TVarVector< Element >::operator+=(), imath::TVarVector< Element >::operator-(), imath::TVarVector< Element >::operator-=(), imath::TVarVector< Element >::operator/(), imath::TVarVector< Element >::operator/=(), imath::TVarVector< Element >::operator[](), imath::TVarVector< Element >::Reset(), imath::TVarVector< Element >::ScaledCumulate(), imath::TVarVector< Element >::Serialize(), imath::TVarVector< Element >::SetElementsFrom(), icmm::TComposedColor< Size >::TComposedColor(), imath::TVarVector< Element >::Translate(), and imath::TVarMatrix< Element >::TVarMatrix().
template<class Element > TVarVector< Element >::Elements & imath::TVarVector< Element >::GetElementsRef () [inline]
Get access to internal element container.
Definition at line 319 of file TVarVector.h.
template<class Element > Element imath::TVarVector< Element >::GetElementsSum () const [inline]
Get simple sum of all elements.
Definition at line 643 of file TVarVector.h.
template<class Element > Element imath::TVarVector< Element >::GetLength () const [inline]
Return euclidian length.
Definition at line 394 of file TVarVector.h.
References imath::TVarVector< Element >::GetLength2().
Referenced by imath::TVarVector< Element >::GetNormalized(), and imath::TVarVector< Element >::Normalize().
template<class Element > Element imath::TVarVector< Element >::GetLength2 () const [inline]
Return euclidian length square.
Definition at line 387 of file TVarVector.h.
References imath::TVarVector< Element >::GetDotProduct().
Referenced by imath::TVarVector< Element >::GetLength(), and imath::TVarVector< Element >::IsNull().
template<class Element> void imath::TVarVector< Element >::GetMaximal (const TVarVector< Element > & vector, TVarVector< Element > & result) const [inline]
Get vector with maximal elements values.
Definition at line 691 of file TVarVector.h.
References imath::TVarVector< Element >::GetElement(), imath::TVarVector< Element >::GetElementsCount(), istd::Max(), istd::Min(), imath::TVarVector< Element >::SetElement(), and imath::TVarVector< Element >::SetElementsCount().
template<class Element> void imath::TVarVector< Element >::GetMinimal (const TVarVector< Element > & vector, TVarVector< Element > & result) const [inline]
Get vector with minimal elements values.
Definition at line 678 of file TVarVector.h.
References imath::TVarVector< Element >::GetElement(), imath::TVarVector< Element >::GetElementsCount(), istd::Min(), imath::TVarVector< Element >::SetElement(), and imath::TVarVector< Element >::SetElementsCount().
template<class Element> bool imath::TVarVector< Element >::GetNormalized (TVarVector< Element > & result, Element length = 1.0) const [inline]
Return normalized vector with the same direction and specified length.
Parameters:
length new vector length.
Returns:
true, if normalization successed.
Definition at line 704 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount(), imath::TVarVector< Element >::GetLength(), and I_BIG_EPSILON.
template<class Element> void imath::TVarVector< Element >::GetTranslated (const TVarVector< Element > & vector, TVarVector< Element > & result) [inline]
/overloaded
Definition at line 345 of file TVarVector.h.
template<class Element> TVarVector< Element > imath::TVarVector< Element >::GetTranslated (const TVarVector< Element > & vector) [inline]
Get translated point.
Definition at line 338 of file TVarVector.h.
template<class Element> bool imath::TVarVector< Element >::IsNull (Element tolerance = I_BIG_EPSILON) const [inline]
Check if this vector is null.
Definition at line 364 of file TVarVector.h.
References imath::TVarVector< Element >::GetLength2().
template<class Element> bool imath::TVarVector< Element >::Normalize (Element length = 1.0) [inline]
Normalize vector to specified length.
Parameters:
length new vector length.
Returns:
true, if normalization successed.
Definition at line 656 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount(), imath::TVarVector< Element >::GetLength(), and I_BIG_EPSILON.
template<class Element> bool imath::TVarVector< Element >::operator!= (const TVarVector< Element > & vector) const [inline]
Definition at line 424 of file TVarVector.h.
template<class Element> TVarVector< Element > imath::TVarVector< Element >::operator* (Element scalar) const [inline]
Reimplemented in icmm::CVarColor.
Definition at line 569 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount(), and I_ASSERT.
template<class Element> TVarVector< Element > & imath::TVarVector< Element >::operator*= (Element scalar) [inline]
Reimplemented in icmm::CVarColor.
Definition at line 487 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount().
Referenced by icmm::CVarColor::operator*=().
template<class Element> TVarVector< Element > imath::TVarVector< Element >::operator+ (const TVarVector< Element > & vector) const [inline]
Definition at line 529 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount(), and I_ASSERT.
template<class Element> TVarVector< Element > & imath::TVarVector< Element >::operator+= (const TVarVector< Element > & vector) [inline]
Definition at line 459 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount(), and I_ASSERT.
template<class Element> TVarVector< Element > imath::TVarVector< Element >::operator- (const TVarVector< Element > & vector) const [inline]
Definition at line 549 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount(), and I_ASSERT.
template<class Element > TVarVector< Element > imath::TVarVector< Element >::operator- () const [inline]
Definition at line 511 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount(), and I_ASSERT.
template<class Element> TVarVector< Element > & imath::TVarVector< Element >::operator-= (const TVarVector< Element > & vector) [inline]
Definition at line 473 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount(), and I_ASSERT.
template<class Element> TVarVector< Element > imath::TVarVector< Element >::operator/ (Element scalar) const [inline]
Reimplemented in icmm::CVarColor.
Definition at line 587 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount(), and I_ASSERT.
template<class Element> TVarVector< Element > & imath::TVarVector< Element >::operator/= (Element scalar) [inline]
Reimplemented in icmm::CVarColor.
Definition at line 499 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount().
Referenced by icmm::CVarColor::operator/=().
template<class Element> bool imath::TVarVector< Element >::operator< (const TVarVector< Element > & vector) const [inline]
Definition at line 431 of file TVarVector.h.
template<class Element> bool imath::TVarVector< Element >::operator<= (const TVarVector< Element > & vector) const [inline]
Definition at line 445 of file TVarVector.h.
template<class Element> bool imath::TVarVector< Element >::operator== (const TVarVector< Element > & vector) const [inline]
Definition at line 417 of file TVarVector.h.
template<class Element> bool imath::TVarVector< Element >::operator> (const TVarVector< Element > & vector) const [inline]
Definition at line 438 of file TVarVector.h.
template<class Element> bool imath::TVarVector< Element >::operator>= (const TVarVector< Element > & vector) const [inline]
Definition at line 452 of file TVarVector.h.
template<class Element > Element & imath::TVarVector< Element >::operator[] (int i) [inline]
Definition at line 615 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount(), and I_ASSERT.
template<class Element > const Element & imath::TVarVector< Element >::operator[] (int i) const [inline]
Definition at line 605 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount(), and I_ASSERT.
Referenced by imath::TVarVector< Element >::GetElement(), imath::TVarVector< Element >::GetElementRef(), and imath::TVarVector< Element >::SetElement().
template<class Element> void imath::TVarVector< Element >::Reset (int elementsCount, const Element & value) [inline]
Set number of elements and set all elements to specified value.
Definition at line 300 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount().
template<class Element > void imath::TVarVector< Element >::Reset () [inline]
Set size to zero.
Definition at line 283 of file TVarVector.h.
template<class Element> void imath::TVarVector< Element >::ScaledCumulate (const TVarVector< Element > & vector, Element scale) [inline]
Add second vector scaled by specified factor.
It is equal of Translate(vector * scale) but can be faster implemented.
Definition at line 352 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount(), and I_ASSERT.
template<class Element > bool imath::TVarVector< Element >::Serialize (iser::IArchive & archive) [inline]
Serialize this vector to specified archive.
Reimplemented in icmm::CVarColor.
Definition at line 728 of file TVarVector.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), iser::IArchive::EndTag(), imath::TVarVector< Element >::GetElementsCount(), iser::IArchive::IsStoring(), and iser::IArchive::Process().
template<class Element> void imath::TVarVector< Element >::SetElement (int i, const Element & value) [inline]
Set element at specified i.
Definition at line 276 of file TVarVector.h.
References imath::TVarVector< Element >::operator[]().
Referenced by imath::TVarVector< Element >::GetMaximal(), imath::TVarVector< Element >::GetMinimal(), icmm::CVarColor::operator*(), icmm::CVarColor::operator/(), and imath::TVarVector< Element >::SetElementsFrom().
template<class Element> bool imath::TVarVector< Element >::SetElementsCount (int size, const Element & value = Element()) [inline]
Set number of elements.
Returns:
always true, this value is provided for template implementations.
Definition at line 251 of file TVarVector.h.
References I_ASSERT.
Referenced by imath::TVarMatrix< Element >::GetColumnVector(), imath::TVarVector< Element >::GetMaximal(), imath::TVarVector< Element >::GetMinimal(), and imath::TVarMatrix< Element >::GetRowVector().
template<class Element> void imath::TVarVector< Element >::SetElementsFrom (const TVarVector< Element > & vector, const Element & expansionValue = Element()) [inline]
Set elemenents from other vector without resizing.
Parameters:
vector source of element values will be copied.
expansionValue if actual vector has more elements than vector, rest will be replaced with this value.
Definition at line 627 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount(), istd::Min(), and imath::TVarVector< Element >::SetElement().
template<class Element> void imath::TVarVector< Element >::Translate (const TVarVector< Element > & vector) [inline]
Translate the point.
Definition at line 326 of file TVarVector.h.
References imath::TVarVector< Element >::GetElementsCount(), and I_ASSERT.
The documentation for this class was generated from the following file:
E:/Work/Projects/Developement/Acf/Include/imath/TVarVector.h