ACF: icomp::IRealAttributeStaticInfo Class Reference
icomp::IRealAttributeStaticInfo Class Reference
Interface adding to attribute static info functionality existing only for real attributes.
#include <IRealAttributeStaticInfo.h>
Public Member Functions
virtual const std::string & GetAttributeId () const =0
Get ID of this attribute.
virtual void AddRelatedMetaId (int metaGroupId, const std::string &id, int flags)=0
Add related interface to this attribute info.
Detailed Description
Interface adding to attribute static info functionality existing only for real attributes.
Definition at line 18 of file IRealAttributeStaticInfo.h.
Member Function Documentation
virtual void icomp::IRealAttributeStaticInfo::AddRelatedMetaId (int metaGroupId, const std::string & id, int flags) [pure virtual]
Add related interface to this attribute info.
Parameters:
relatedInterfaceInfo specify interface.
flags set of flags defined in icomp::IAttributeStaticInfo::AttributeFlags.
Implemented in icomp::TAttributeStaticInfo< Attribute >.
Referenced by icomp::CRelatedInfoRegistrator::CRelatedInfoRegistrator().
virtual const std::string& icomp::IRealAttributeStaticInfo::GetAttributeId () const [pure virtual]
Get ID of this attribute.
Implemented in icomp::TAttributeStaticInfo< Attribute >.
Referenced by icomp::TMultiAttributeMember< Attribute >::Init(), and icomp::TAttributeMember< Attribute >::Init().
The documentation for this class was generated from the following file:
C:/Temp/Acf/Include/icomp/IRealAttributeStaticInfo.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy