iview::CInteractiveShapeBase Class Reference
iview::CInteractiveShapeBase Class Reference abstract
#include <CInteractiveShapeBase.h>
Public Types
typedef CShapeBase BaseClass
Public Types inherited from iview::CShapeBase
enum ShapeTransformMode { STM_VIEW, STM_SHAPE, STM_COMBINE }
Describe how shape tranformation is interpreted.
typedef
imod::CSingleModelObserverBase BaseClass
Public Types inherited from imod::CSingleModelObserverBase
typedef imod::IModel ModelType
Public Types inherited from iview::IShape
enum ChangeFlags { CF_CALIB = 1 << 20 }
Public Types inherited from iview::ITouchable
enum TouchState {
TS_NONE, TS_INACTIVE, TS_TICKER, TS_DRAGGABLE,
TS_OTHER, TS_LAST = TS_OTHER
}
Enumeration for possible shape touch states.
Public Member Functions
CInteractiveShapeBase ()
CInteractiveShapeBase (const CInteractiveShapeBase &shape)
virtual ~CInteractiveShapeBase ()
virtual bool IsEditablePosition () const
virtual void SetEditablePosition (bool state=true)
virtual bool IsSelected () const
Check, if this shape is selected.
virtual void SetSelected (bool selectFlag=true)
Inform that this object was selected or deselected.
virtual bool OnMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag)
It is called, when mouse button is pushed down or up on this object.
virtual bool OnMouseMove (istd::CIndex2d position)
It is called, when mouse is moved.
virtual bool IsDraggable () const
Check if drag is enabled.
virtual void BeginDrag (const istd::CIndex2d &position)
Called before dragging is begin.
virtual void SetDragPosition (const istd::CIndex2d &position)
Set new drag position.
virtual void EndDrag ()
Called after dragging.
virtual bool OnAttached (imod::IModel *modelPtr)
This call back function will be called, if an observable object is about to be attached.
virtual bool OnDetached (imod::IModel *modelPtr)
This call back function will be called, if an observable object is about to be detached.
Public Member Functions inherited from iview::CShapeBase
CShapeBase ()
CShapeBase (const CShapeBase &shape)
virtual ~CShapeBase ()
virtual void SetVisible (bool state=true)
Make this shape visible.
virtual bool AssignToLayer (int layerType)
virtual void Invalidate (int changeFlags=0)
iview::IDisplay * GetDisplayPtr () const
Get access to currently connected display.
ShapeTransformMode GetTransformMode () const
Get shape transformation mode.
void SetTransformMode (ShapeTransformMode mode)
Set shape transformation mode.
virtual int GetLayerType () const
Get layer type of this shape object.
virtual i2d::CRect GetBoundingBox () const
Return bounding box in client window coordinates.
virtual const IColorSchema * GetUserColorSchema () const
Get color schema from view or user defined.
virtual void SetUserColorSchema (const IColorSchema *schemaPtr)
Set color schema to draw shape.
virtual bool IsVisible () const
Check, if this object is visible.
virtual bool IsDisplayAccepted (const IDisplay &display) const
Check if this object can be connected to this display.
virtual void OnConnectDisplay (IDisplay *displayPtr)
Called after display is connected.
virtual void OnDisconnectDisplay (IDisplay *displayPtr)
Called after display is disconnected.
virtual bool OnDisplayChange (int flags)
It informs about changes in display.
virtual ITouchable::TouchState IsTouched (istd::CIndex2d position) const
Check, if any shape is touched.
virtual QString GetShapeDescriptionAt (istd::CIndex2d position) const
Get description to shape at specified position.
virtual void OnUpdate (int changeFlags, istd::IPolymorphic *updateParamsPtr)
Public Member Functions inherited from imod::CSingleModelObserverBase
CSingleModelObserverBase ()
virtual ~CSingleModelObserverBase ()
imod::IModel * GetModelPtr () const
Get access to observed model.
void EnsureModelDetached ()
Make sure this observer is detached.
virtual bool IsModelAttached (const imod::IModel *modelPtr=NULL) const
Check if specified model is attached.
virtual void BeforeUpdate (imod::IModel *modelPtr, int updateFlags, istd::IPolymorphic *updateParamsPtr)
This function will be called before update of the observer contents occures.
virtual void AfterUpdate (imod::IModel *modelPtr, int updateFlags, istd::IPolymorphic *updateParamsPtr)
This function will be called after update of the observer contents occures.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Public Member Functions inherited from iview::IVisualizable
virtual void Draw (QPainter &drawContext) const =0
Draw this shape using draw context.
Protected Member Functions
void BeginModelChanges ()
void EndModelChanges ()
void UpdateModelChanges ()
int GetKeysState () const
Get actual keys state.
int GetEditMode () const
Get actual edit mode.
void DrawText (QPainter &drawContext, istd::CIndex2d point, const QString &text) const
Draw text on a given position.
virtual int GetDisplayChangesMask ()
Get display changes mask.
virtual void BeginLogDrag (const i2d::CVector2d &reference)=0
virtual void SetLogDragPosition (const i2d::CVector2d &position)=0
Protected Member Functions inherited from iview::CShapeBase
i2d::CVector2d GetScreenPosition (const i2d::CVector2d &logPosition) const
Get screen position based on logical position.
i2d::CVector2d GetLogPosition (const i2d::CVector2d &screenPosition) const
Get logical position based on screen position.
virtual void InvalidateBoundingBox ()
Invalidate bounding box.
bool IsDisplayConnected () const
Check if display is connected.
const IColorSchema & GetColorSchema () const
Get color schema for this shape.
i2d::CRect GetClientRect () const
Get display client rectangle.
bool IsBoundingBoxValid () const
void DisconnectDisplay ()
virtual const
iview::CScreenTransform & GetViewToScreenTransform () const
virtual i2d::CRect CalcBoundingBox () const =0
Calculate bounding box.
Protected Member Functions inherited from imod::CSingleModelObserverBase
void SetModelPtr (imod::IModel *modelPtr)
Set internal model pointer to specified value.
Detailed Description
Definition at line 23 of file CInteractiveShapeBase.h.
Member Typedef Documentation
typedef CShapeBase iview::CInteractiveShapeBase::BaseClass
Definition at line 29 of file CInteractiveShapeBase.h.
Constructor & Destructor Documentation
iview::CInteractiveShapeBase::CInteractiveShapeBase ()
iview::CInteractiveShapeBase::CInteractiveShapeBase (const CInteractiveShapeBase & shape)
virtual iview::CInteractiveShapeBase::~CInteractiveShapeBase () virtual
Member Function Documentation
virtual void iview::CInteractiveShapeBase::BeginDrag (const istd::CIndex2d & reference) virtual
Called before dragging is begin.
It set also reference value for dragging position.
Implements iview::IDraggable.
virtual void iview::CInteractiveShapeBase::BeginLogDrag (const i2d::CVector2d & reference) protected pure virtual
Implemented in iview::CTransformableRectangleShape, iview::CParallelogramShape, iview::CAffineTransformation2dShape, iview::CPolygonShape, iview::CLineShape, iview::CArrowShape, iview::CRectangleShape, iview::CPinShape, and iview::CPerspectiveCalibrationBoundsShape.
void iview::CInteractiveShapeBase::BeginModelChanges () protected
void iview::CInteractiveShapeBase::DrawText (QPainter & drawContext, istd::CIndex2d point, const QString & text) const protected
Draw text on a given position.
virtual void iview::CInteractiveShapeBase::EndDrag () virtual
Called after dragging.
Implements iview::IDraggable.
void iview::CInteractiveShapeBase::EndModelChanges () protected
int iview::CInteractiveShapeBase::GetDisplayChangesMask () inline protected virtual
Get display changes mask.
Only changes there are in mask will be accepted, rest will be ignored.
Reimplemented from iview::CShapeBase.
Definition at line 136 of file CInteractiveShapeBase.h.
References iview::CF_EDIT_MODE, and iview::CShapeBase::GetDisplayChangesMask().
int iview::CInteractiveShapeBase::GetEditMode () const inline protected
Get actual edit mode.
Note, that display must be connected to use this method.
Definition at line 122 of file CInteractiveShapeBase.h.
References iview::ISelectable::EM_NONE, iview::CShapeBase::GetDisplayPtr(), iview::ISelectable::GetEditMode(), and NULL.
int iview::CInteractiveShapeBase::GetKeysState () const inline protected
Get actual keys state.
Note, that display must be connected to use this method.
Definition at line 110 of file CInteractiveShapeBase.h.
References iview::CShapeBase::GetDisplayPtr(), iview::ISelectable::GetKeysState(), and NULL.
virtual bool iview::CInteractiveShapeBase::IsDraggable () const virtual
Check if drag is enabled.
Implements iview::IDraggable.
Reimplemented in iview::CPolygonShape.
bool iview::CInteractiveShapeBase::IsEditablePosition () const inline virtual
Definition at line 96 of file CInteractiveShapeBase.h.
virtual bool iview::CInteractiveShapeBase::IsSelected () const virtual
Check, if this shape is selected.
Implements iview::IInteractiveShape.
virtual bool iview::CInteractiveShapeBase::OnAttached (imod::IModel * modelPtr) virtual
This call back function will be called, if an observable object is about to be attached.
This function returns a true, if observable object is accepted by the implementation logic of the observer, otherwise the function returns a false.
Reimplemented from iview::CShapeBase.
Reimplemented in iview::CParallelogramShape, iview::CTransformableRectangleShape, iview::CLabelShape, iview::CPolygonShape, iview::CAffineTransformation2dShape, iview::CAnnulusShape, iview::CCircleShape, iview::CArrowShape, iview::CLineShape, iview::CRectangleShape, iview::CAnnulusSegmentShape, iview::CPolylineShape, iview::CPinShape, iview::COrientedCircleShape, and iview::CSplineShape.
virtual bool iview::CInteractiveShapeBase::OnDetached (imod::IModel * modelPtr) virtual
This call back function will be called, if an observable object is about to be detached.
Reimplemented from iview::CShapeBase.
virtual bool iview::CInteractiveShapeBase::OnMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag) virtual
It is called, when mouse button is pushed down or up on this object.
Parameters
position - position of mouse pointer on client area (picture coords).
downFlag - true, if mouse button is pushed down, false if pushed up.
Returns
true if this shape should get focus to catch all mouse movements.
Implements iview::IMouseActionObserver.
Reimplemented in iview::CParallelogramShape, iview::CTransformableRectangleShape, iview::CPolygonShape, iview::CTubePolylineShape, iview::CLabelShape, iview::CArrowShape, iview::CLineShape, iview::CRectangleShape, iview::CAnnulusShape, iview::CPinShape, iview::CCenterPinShape, iview::CPolylineShape, iview::CPerspectiveCalibrationBoundsShape, iview::CCircleShape, and iview::CAnnulusSegmentShape.
virtual bool iview::CInteractiveShapeBase::OnMouseMove (istd::CIndex2d position) virtual
It is called, when mouse is moved.
Only objects with focus receive this event.
Parameters
position - position of mouse pointer on client area (picture coords).
Returns
true if this shape should hold focus to catch longer all mouse movements.
Implements iview::IMouseActionObserver.
Reimplemented in iview::CParallelogramShape, iview::CTransformableRectangleShape, iview::CPolygonShape, iview::CTubePolylineShape, iview::CLabelShape, iview::CArrowShape, iview::CLineShape, iview::CRectangleShape, iview::CAnnulusShape, iview::CPinShape, iview::CCenterPinShape, iview::CPerspectiveCalibrationBoundsShape, iview::CCircleShape, and iview::CAnnulusSegmentShape.
virtual void iview::CInteractiveShapeBase::SetDragPosition (const istd::CIndex2d & position) virtual
Set new drag position.
It must be enclosed using BeginDrag() and EndDrag() methods.
Implements iview::IDraggable.
void iview::CInteractiveShapeBase::SetEditablePosition (bool state = true) inline virtual
Definition at line 102 of file CInteractiveShapeBase.h.
virtual void iview::CInteractiveShapeBase::SetLogDragPosition (const i2d::CVector2d & position) protected pure virtual
Implemented in iview::CTransformableRectangleShape, iview::CParallelogramShape, iview::CAffineTransformation2dShape, iview::CPolygonShape, iview::CLineShape, iview::CArrowShape, iview::CRectangleShape, iview::CPinShape, and iview::CPerspectiveCalibrationBoundsShape.
virtual void iview::CInteractiveShapeBase::SetSelected (bool selectFlag = true) virtual
Inform that this object was selected or deselected.
Parameters
selectFlag if true - selection, else deselection.
Implements iview::IInteractiveShape.
void iview::CInteractiveShapeBase::UpdateModelChanges () protected
The documentation for this class was generated from the following file:
Include/iview/CInteractiveShapeBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy