icomp::TSubelementStaticInfo< ComponentType > Class Template Reference
icomp::TSubelementStaticInfo< ComponentType > Class Template Reference
#include <TSubelementStaticInfo.h>
Classes
class Registrator
Public Types
typedef void *(* InterfaceExtractorPtr)(ComponentType &component)
Public Types inherited from icomp::IElementStaticInfo
enum MetaGroupId { MGI_INTERFACES = 0, MGI_SUBELEMENTS, MGI_LAST = MGI_SUBELEMENTS }
typedef QSet< QByteArray > Ids
Public Member Functions
TSubelementStaticInfo (const QByteArray &name, CBaseComponentStaticInfo &owner)
Constructor attaching this subelement info to the component.
virtual void RegisterInterfaceExtractor (const QByteArray &interfaceName, InterfaceExtractorPtr extractorPtr)
Register interface ID for this static component info.
virtual const IElementStaticInfo * GetSubelementInfo (const QByteArray &subcomponentId) const
Return number of interfaces for specific slot.
virtual Ids GetMetaIds (int metaGroupId) const
Get list of meta IDs associated with some meta key.
virtual void * GetComponentInterface (const istd::CClassInfo &interfaceType, IComponent &component, const QByteArray &subId) const
Extract instance implemented specified interface from some component.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Detailed Description
template<class ComponentType>
class icomp::TSubelementStaticInfo< ComponentType >
Definition at line 19 of file TSubelementStaticInfo.h.
Member Typedef Documentation
template<class ComponentType > typedef void*(* icomp::TSubelementStaticInfo< ComponentType >::InterfaceExtractorPtr)(ComponentType &component)
Definition at line 24 of file TSubelementStaticInfo.h.
Constructor & Destructor Documentation
template<class ComponentType > icomp::TSubelementStaticInfo< ComponentType >::TSubelementStaticInfo (const QByteArray & name, CBaseComponentStaticInfo & owner)
Constructor attaching this subelement info to the component.
Definition at line 71 of file TSubelementStaticInfo.h.
References icomp::CBaseComponentStaticInfo::RegisterSubelementInfo().
Member Function Documentation
template<class ComponentType > void * icomp::TSubelementStaticInfo< ComponentType >::GetComponentInterface (const istd::CClassInfo & interfaceType, IComponent & component, const QByteArray & subId) const virtual
Extract instance implemented specified interface from some component.
Implements icomp::IComponentInterfaceExtractor.
Definition at line 113 of file TSubelementStaticInfo.h.
References istd::CClassInfo::GetConstCasted(), istd::CClassInfo::GetName(), istd::CClassInfo::IsConst(), istd::CClassInfo::IsValid(), istd::CClassInfo::IsVoid(), and NULL.
template<class ComponentType > IElementStaticInfo::Ids icomp::TSubelementStaticInfo< ComponentType >::GetMetaIds (int metaGroupId) const virtual
Get list of meta IDs associated with some meta key.
See Also
MetaGroupId
Implements icomp::IElementStaticInfo.
Definition at line 94 of file TSubelementStaticInfo.h.
template<class ComponentType > const IElementStaticInfo * icomp::TSubelementStaticInfo< ComponentType >::GetSubelementInfo (const QByteArray & subcomponentId) const virtual
Return number of interfaces for specific slot.
Parameters
subcomponentId ID of subcomponent.
See Also
GetMetaIds() and MGI_SUBELEMENTS.
Implements icomp::IElementStaticInfo.
Definition at line 87 of file TSubelementStaticInfo.h.
References NULL.
template<class ComponentType > void icomp::TSubelementStaticInfo< ComponentType >::RegisterInterfaceExtractor (const QByteArray & interfaceName, InterfaceExtractorPtr extractorPtr) virtual
Register interface ID for this static component info.
This interface ID is used for static check if this component can be used to resolve reference dependecy of second one.
Definition at line 78 of file TSubelementStaticInfo.h.
Referenced by icomp::TSubelementStaticInfo< ComponentType >::Registrator< InterfaceType >::Registrator().
The documentation for this class was generated from the following file:
Include/icomp/TSubelementStaticInfo.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy