i2d::TMultiPolyline< SegmentData > Class Template Reference
i2d::TMultiPolyline< SegmentData > Class Template Reference
#include <TMultiPolyline.h>
Classes
class CSegment
Public Types
typedef CPolyline BaseClass
Public Member Functions
TMultiPolyline ()
virtual void SetParallelsCount (int count)
Number of parallel pair of lines.
virtual int GetParallelsCount () const
Get number of parallel pair of lines.
virtual void SetParallel (int segmentIndex, int parallelIndex, double width)
Set width of parallel lines.
virtual double GetParallel (int segmentIndex, int parallelIndex) const
Get width of parallel lines.
virtual double GetMaxParallel () const
Get maximal width.
virtual double GetMinParallel () const
virtual void SetSegmentData (int segmentIndex, const SegmentData &data)
virtual const iser::ISerializable & GetSegmentData (int segmentIndex) const
Get segment user data.
virtual bool RemoveSegment (int node, int segment)
Remove node and segment.
virtual void SelectAllSegments (bool selected=true)
Select or deselect all segments.
virtual void SelectSegment (int segmentIndex, bool selected=true)
Select and deselect segment.
virtual bool IsSegmentSelected (int segmentIndex) const
Test if segment is selected.
virtual bool InsertNode (const i2d::CVector2d &node)
Insert a node at the end of node table.
virtual bool InsertNode (int index, const i2d::CVector2d &node)
Insert a node at specified index.
virtual void Clear ()
Removes all nodes.
virtual void SetClosed (bool state=true)
Set polyline to be opened or closed.
virtual bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
Public Attributes
::std::vector< double > m_widthList
bool m_selected
SegmentData m_data
Protected Member Functions
CSegment CalculateAverage (const CSegment &first, const CSegment &second) const
Detailed Description
template<class SegmentData>
class i2d::TMultiPolyline< SegmentData >
Definition at line 21 of file TMultiPolyline.h.
Member Typedef Documentation
template<class SegmentData > typedef CPolyline i2d::TMultiPolyline< SegmentData >::BaseClass
Reimplemented from i2d::CMultiPolylineBase.
Definition at line 24 of file TMultiPolyline.h.
Constructor & Destructor Documentation
template<class SegmentData > i2d::TMultiPolyline< SegmentData >::TMultiPolyline () [inline]
Definition at line 116 of file TMultiPolyline.h.
Member Function Documentation
template<class SegmentData > TMultiPolyline< SegmentData >::CSegment i2d::TMultiPolyline< SegmentData >::CalculateAverage (const CSegment & first, const CSegment & second) const [inline, protected]
Definition at line 123 of file TMultiPolyline.h.
template<class SegmentData > void i2d::TMultiPolyline< SegmentData >::Clear () [inline, virtual]
Removes all nodes.
Reimplemented from i2d::CPolygon.
Definition at line 218 of file TMultiPolyline.h.
template<class SegmentData > double i2d::TMultiPolyline< SegmentData >::GetMaxParallel () const [virtual]
Get maximal width.
Reimplemented from i2d::CMultiPolylineBase.
Definition at line 328 of file TMultiPolyline.h.
template<class SegmentData > double i2d::TMultiPolyline< SegmentData >::GetMinParallel () const [virtual]
Definition at line 349 of file TMultiPolyline.h.
template<class SegmentData > double i2d::TMultiPolyline< SegmentData >::GetParallel (int segmentIndex, int parallelIndex) const [virtual]
Get width of parallel lines.
Implements i2d::CMultiPolylineBase.
Definition at line 273 of file TMultiPolyline.h.
References I_ASSERT.
template<class SegmentData > int i2d::TMultiPolyline< SegmentData >::GetParallelsCount () const [virtual]
Get number of parallel pair of lines.
Implements i2d::CMultiPolylineBase.
Definition at line 253 of file TMultiPolyline.h.
template<class SegmentData > const iser::ISerializable & i2d::TMultiPolyline< SegmentData >::GetSegmentData (int segmentIndex) const [virtual]
Get segment user data.
Implements i2d::CMultiPolylineBase.
Definition at line 292 of file TMultiPolyline.h.
References I_ASSERT.
template<class SegmentData > bool i2d::TMultiPolyline< SegmentData >::InsertNode (const i2d::CVector2d & node) [inline, virtual]
Insert a node at the end of node table.
Reimplemented from i2d::CPolygon.
Definition at line 150 of file TMultiPolyline.h.
template<class SegmentData > bool i2d::TMultiPolyline< SegmentData >::InsertNode (int index, const i2d::CVector2d & node) [inline, virtual]
Insert a node at specified index.
Reimplemented from i2d::CPolygon.
Definition at line 174 of file TMultiPolyline.h.
template<class SegmentData > bool i2d::TMultiPolyline< SegmentData >::IsSegmentSelected (int segmentIndex) const [virtual]
Test if segment is selected.
Implements i2d::CMultiPolylineBase.
Definition at line 319 of file TMultiPolyline.h.
References I_ASSERT.
template<class SegmentData > bool i2d::TMultiPolyline< SegmentData >::RemoveSegment (int node, int segment) [inline, virtual]
Remove node and segment.
Implements i2d::CMultiPolylineBase.
Definition at line 226 of file TMultiPolyline.h.
References I_ASSERT.
template<class SegmentData > void i2d::TMultiPolyline< SegmentData >::SelectAllSegments (bool selected = true) [virtual]
Select or deselect all segments.
Reimplemented from i2d::CMultiPolylineBase.
Definition at line 301 of file TMultiPolyline.h.
template<class SegmentData > void i2d::TMultiPolyline< SegmentData >::SelectSegment (int segmentIndex, bool selected = true) [virtual]
Select and deselect segment.
Implements i2d::CMultiPolylineBase.
Definition at line 310 of file TMultiPolyline.h.
References I_ASSERT.
template<class SegmentData > bool i2d::TMultiPolyline< SegmentData >::Serialize (iser::IArchive & archive) [virtual]
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See also:
iser::IArchive
Reimplemented from i2d::CPolygon.
Definition at line 370 of file TMultiPolyline.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), iser::IArchive::Process(), and i2d::CPolygon::Serialize().
template<class SegmentData > void i2d::TMultiPolyline< SegmentData >::SetClosed (bool state = true) [inline, virtual]
Set polyline to be opened or closed.
Reimplemented from i2d::CPolyline.
Definition at line 130 of file TMultiPolyline.h.
template<class SegmentData > void i2d::TMultiPolyline< SegmentData >::SetParallel (int segmentIndex, int parallelIndex, double width) [virtual]
Set width of parallel lines.
Implements i2d::CMultiPolylineBase.
Definition at line 263 of file TMultiPolyline.h.
References I_ASSERT.
template<class SegmentData > void i2d::TMultiPolyline< SegmentData >::SetParallelsCount (int count) [virtual]
Number of parallel pair of lines.
Implements i2d::CMultiPolylineBase.
Definition at line 241 of file TMultiPolyline.h.
References I_ASSERT.
template<class SegmentData > void i2d::TMultiPolyline< SegmentData >::SetSegmentData (int segmentIndex, const SegmentData & data) [virtual]
Definition at line 283 of file TMultiPolyline.h.
References I_ASSERT.
Member Data Documentation
template<class SegmentData > SegmentData i2d::TMultiPolyline< SegmentData >::m_data
Definition at line 108 of file TMultiPolyline.h.
Referenced by i2d::TMultiPolyline< SegmentData >::CSegment::Serialize().
template<class SegmentData > bool i2d::TMultiPolyline< SegmentData >::m_selected
Definition at line 107 of file TMultiPolyline.h.
Referenced by i2d::TMultiPolyline< SegmentData >::CSegment::Serialize().
template<class SegmentData > ::std::vector<double> i2d::TMultiPolyline< SegmentData >::m_widthList
Definition at line 106 of file TMultiPolyline.h.
Referenced by i2d::TMultiPolyline< SegmentData >::CSegment::operator/=(), and i2d::TMultiPolyline< SegmentData >::CSegment::Serialize().
The documentation for this class was generated from the following file:
Include/i2d/TMultiPolyline.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy