iview::TInteractiveMultiPolylineShape< SegmentData > Class Template Reference
iview::TInteractiveMultiPolylineShape< SegmentData > Class Template Reference
#include <TInteractiveMultiPolylineShape.h>
Public Types
typedef CInteractivePolylineShape BaseClass
Public Member Functions
TInteractiveMultiPolylineShape ()
virtual bool IsAlwaysMovable () const
Check if in all edit modes is this shape draggable.
virtual void SetAlwaysMovable (bool state=true)
Set flag if in all edit modes is this shape draggable.
virtual void CalcBoundingBox (i2d::CRect &result) const
Calculate bounding box.
virtual void SetSelected (bool selectFlag)
Inform that this object was selected or deselected.
virtual bool OnMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag)
It is called, when mouse button is pushed down or up on this object.
virtual TouchState IsTouched (istd::CIndex2d position) const
Check, if any shape is touched.
virtual void OnAttached (imod::IModel *modelPtr)
This call back function will be called, if an observable object is about to be attached.
Protected Member Functions
virtual void DrawCurve (QPainter &drawContext) const
virtual void DrawSelectionElements (QPainter &drawContext) const
virtual bool IsCurveTouched (istd::CIndex2d position) const
bool TrySelectSegments (iview::TMultiPolyline< SegmentData > &polyline, istd::CIndex2d position)
virtual void EnsureValidNodes () const
void CalculateRemovePoints (const iview::TMultiPolyline< SegmentData > &polyline, int segment, i2d::CVector2d &first, i2d::CVector2d &second) const
Detailed Description
template<class SegmentData>
class iview::TInteractiveMultiPolylineShape< SegmentData >
Definition at line 13 of file TInteractiveMultiPolylineShape.h.
Member Typedef Documentation
template<class SegmentData > typedef CInteractivePolylineShape iview::TInteractiveMultiPolylineShape< SegmentData >::BaseClass
Reimplemented from iview::CInteractivePolylineShape.
Definition at line 16 of file TInteractiveMultiPolylineShape.h.
Constructor & Destructor Documentation
template<class SegmentData > iview::TInteractiveMultiPolylineShape< SegmentData >::TInteractiveMultiPolylineShape ()
Definition at line 85 of file TInteractiveMultiPolylineShape.h.
Member Function Documentation
template<class SegmentData > void iview::TInteractiveMultiPolylineShape< SegmentData >::CalcBoundingBox (i2d::CRect & result) const [virtual]
Calculate bounding box.
You have to implement this method in your shapes implementations.
Reimplemented from iview::CInteractivePolygonShape.
Definition at line 764 of file TInteractiveMultiPolylineShape.h.
References i2d::CRect::GetBottom(), i2d::CRect::GetRight(), iview::CScreenTransform::GetScreenPosition(), I_ASSERT, NULL, i2d::CRect::Reset(), and i2d::CRect::Union().
template<class SegmentData > void iview::TInteractiveMultiPolylineShape< SegmentData >::CalculateRemovePoints (const iview::TMultiPolyline< SegmentData > & polyline, int segment, i2d::CVector2d & first, i2d::CVector2d & second) const [protected]
Definition at line 751 of file TInteractiveMultiPolylineShape.h.
template<class SegmentData > void iview::TInteractiveMultiPolylineShape< SegmentData >::DrawCurve (QPainter & drawContext) const [protected, virtual]
Reimplemented from iview::CInteractivePolylineShape.
Definition at line 379 of file TInteractiveMultiPolylineShape.h.
References iview::CScreenTransform::GetScreenPosition(), I_ASSERT, NULL, iview::IColorShema::SP_NORMAL_DASH, and iview::IColorShema::SP_SELECTED_DASH.
template<class SegmentData > void iview::TInteractiveMultiPolylineShape< SegmentData >::DrawSelectionElements (QPainter & drawContext) const [protected, virtual]
Reimplemented from iview::CInteractivePolylineShape.
Definition at line 432 of file TInteractiveMultiPolylineShape.h.
References iview::ISelectable::EM_ADD, iview::ISelectable::EM_MOVE, iview::ISelectable::EM_NONE, iview::ISelectable::EM_REMOVE, iview::CScreenTransform::GetScreenPosition(), I_ASSERT, NULL, iview::IColorShema::TT_DELETE, iview::IColorShema::TT_INSERT, iview::IColorShema::TT_MOVE, and iview::IColorShema::TT_SELECTED_INACTIVE.
template<class SegmentData > void iview::TInteractiveMultiPolylineShape< SegmentData >::EnsureValidNodes () const [protected, virtual]
Reimplemented from iview::CInteractivePolygonShape.
Definition at line 641 of file TInteractiveMultiPolylineShape.h.
References i2d::CAffine2d::GetApply(), i2d::CAffine2d::GetDeformMatrixRef(), imath::TVector< Size, Element >::GetDotProduct(), i2d::CVector2d::GetNormalized(), i2d::CVector2d::GetOrthogonal(), i2d::CVector2d::GetY(), I_ASSERT, NULL, and i2d::CVector2d::SetX().
template<class SegmentData > bool iview::TInteractiveMultiPolylineShape< SegmentData >::IsAlwaysMovable () const [inline, virtual]
Check if in all edit modes is this shape draggable.
Normally it is possible to drag this object only in EM_NONE mode.
Reimplemented from iview::CInteractivePolygonShape.
Definition at line 67 of file TInteractiveMultiPolylineShape.h.
template<class SegmentData > bool iview::TInteractiveMultiPolylineShape< SegmentData >::IsCurveTouched (istd::CIndex2d position) const [protected, virtual]
Reimplemented from iview::CInteractivePolylineShape.
Definition at line 509 of file TInteractiveMultiPolylineShape.h.
References iview::CScreenTransform::GetClientPosition(), i2d::CAffine2d::GetDeformMatrix(), imath::TVector< Size, Element >::GetDotProduct(), i2d::CVector2d::GetOrthogonal(), I_ASSERT, and NULL.
template<class SegmentData > ITouchable::TouchState iview::TInteractiveMultiPolylineShape< SegmentData >::IsTouched (istd::CIndex2d position) const [virtual]
Check, if any shape is touched.
When shape is touched, it return also pointer to this shape.
Returns:
touch state for the shape, or iview::IInteractiveShape::TS_NONE, when nothing found.
Reimplemented from iview::CInteractivePolylineShape.
Definition at line 260 of file TInteractiveMultiPolylineShape.h.
References iview::ISelectable::EM_ADD, iview::ISelectable::EM_MOVE, iview::ISelectable::EM_NONE, iview::ISelectable::EM_REMOVE, iview::CInteractiveTransformableRectangleShape::EnsureValidNodes(), iview::CScreenTransform::GetScreenPosition(), I_ASSERT, i2d::CRect::IsInside(), iview::CInteractiveTransformableRectangleShape::IsParallTouched(), iview::CInteractiveTransformableRectangleShape::IsTickerTouched(), NULL, iview::IColorShema::TT_DELETE, iview::IColorShema::TT_INSERT, and iview::IColorShema::TT_MOVE.
template<class SegmentData > void iview::TInteractiveMultiPolylineShape< SegmentData >::OnAttached (imod::IModel * modelPtr) [virtual]
This call back function will be called, if an observable object is about to be attached.
This function returns a true, if observable object is accepted by the implementation logic of the observer, otherwise the function returns a false.
Reimplemented from iview::CInteractivePolylineShape.
Definition at line 248 of file TInteractiveMultiPolylineShape.h.
References I_ASSERT, and NULL.
template<class SegmentData > bool iview::TInteractiveMultiPolylineShape< SegmentData >::OnMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag) [virtual]
It is called, when mouse button is pushed down or up on this object.
Parameters:
position - position of mouse pointer on client area (picture coords).
downFlag - true, if mouse button is pushed down, false if pushed up.
Returns:
true if this shape should get focus to catch all mouse movements.
Reimplemented from iview::CInteractivePolylineShape.
Definition at line 96 of file TInteractiveMultiPolylineShape.h.
References iview::ISelectable::EM_ADD, iview::ISelectable::EM_MOVE, iview::ISelectable::EM_NONE, iview::ISelectable::EM_REMOVE, iview::CScreenTransform::GetClientPosition(), iview::CScreenTransform::GetScreenPosition(), I_ASSERT, i2d::CRect::IsInside(), NULL, iview::CInteractiveTransformableRectangleShape::OnMouseButton(), iview::IColorShema::TT_INSERT, and iview::IColorShema::TT_MOVE.
template<class SegmentData > void iview::TInteractiveMultiPolylineShape< SegmentData >::SetAlwaysMovable (bool state = true) [inline, virtual]
Set flag if in all edit modes is this shape draggable.
See also:
IsAlwaysMovable()
Reimplemented from iview::CInteractivePolygonShape.
Definition at line 75 of file TInteractiveMultiPolylineShape.h.
template<class SegmentData > void iview::TInteractiveMultiPolylineShape< SegmentData >::SetSelected (bool selectFlag) [virtual]
Inform that this object was selected or deselected.
Parameters:
selectFlag if true - selection, else deselection.
Reimplemented from iview::CInteractiveShapeBase.
Definition at line 812 of file TInteractiveMultiPolylineShape.h.
References I_ASSERT, and NULL.
template<class SegmentData > bool iview::TInteractiveMultiPolylineShape< SegmentData >::TrySelectSegments (iview::TMultiPolyline< SegmentData > & polyline, istd::CIndex2d position) [protected]
Definition at line 558 of file TInteractiveMultiPolylineShape.h.
References iview::CScreenTransform::GetClientPosition(), i2d::CAffine2d::GetDeformMatrix(), imath::TVector< Size, Element >::GetDotProduct(), i2d::CVector2d::GetOrthogonal(), I_ASSERT, and NULL.
The documentation for this class was generated from the following file:
Include/iview/TInteractiveMultiPolylineShape.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy