iview::TFramedViewBase< ViewBase > Class Template Reference
iview::TFramedViewBase< ViewBase > Class Template Reference
#include <TFramedViewBase.h>
Public Types
typedef ViewBase BaseClass
typedef iview::IViewEventObserver BaseClass2
typedef TFrameBase< ViewBase > Frame
Public Member Functions
TFramedViewBase (Frame *framePtr)
template<typename ConstructorParam >
TFramedViewBase (Frame *framePtr, ConstructorParam *param)
virtual ~TFramedViewBase ()
void SetFramework (TFrameBase< ViewBase > *framePtr)
Frame * GetFramePtr () const
void UpdateFitTransform ()
virtual void SetEditMode (int mode)
virtual void SetFitArea (const i2d::CRectangle &area)
int GetPixelPositionExact () const
Get number of digits after point used to display mouse position in pixel.
int GetLogicalPositionExact () const
Get number of digits after point used to display mouse position in logical units.
virtual bool OnSelectChange (const iview::IShapeView &view, const istd::CIndex2d &position, const iview::IInteractiveShape &shape, bool state)
Message handler for selection changes.
virtual bool OnMouseButton (const iview::IShapeView &view, const istd::CIndex2d &position, Qt::MouseButton buttonType, bool state, const iview::IInteractiveShape *shapePtr)
Message handler for mouse button click.
virtual bool OnMouseMove (istd::CIndex2d position)
Protected Member Functions
virtual void SetBackgroundBufferValid (bool state=true)
virtual void OnBoundingBoxChanged ()
virtual void OnResize ()
virtual bool CanBeMoved () const
virtual void CalcBoundingBox () const
virtual void OnAreaInvalidated (const i2d::CRect &beforeBox, const i2d::CRect &afterBox)
Detailed Description
template<class ViewBase>
class iview::TFramedViewBase< ViewBase >
Definition at line 24 of file TFramedViewBase.h.
Member Typedef Documentation
template<class ViewBase > typedef ViewBase iview::TFramedViewBase< ViewBase >::BaseClass
Reimplemented in iview::TCalibratedViewBase< ViewBase >.
Definition at line 29 of file TFramedViewBase.h.
template<class ViewBase > typedef iview::IViewEventObserver iview::TFramedViewBase< ViewBase >::BaseClass2
Definition at line 30 of file TFramedViewBase.h.
template<class ViewBase > typedef TFrameBase<ViewBase> iview::TFramedViewBase< ViewBase >::Frame
Definition at line 32 of file TFramedViewBase.h.
Constructor & Destructor Documentation
template<class ViewBase > iview::TFramedViewBase< ViewBase >::TFramedViewBase (Frame * framePtr)
Definition at line 113 of file TFramedViewBase.h.
References i2d::CRect::Reset().
template<class ViewBase > template<typename ConstructorParam > iview::TFramedViewBase< ViewBase >::TFramedViewBase (Frame * framePtr, ConstructorParam * param) [inline]
Definition at line 36 of file TFramedViewBase.h.
References i2d::CRect::Reset().
template<class ViewBase > iview::TFramedViewBase< ViewBase >::~TFramedViewBase () [virtual]
Definition at line 125 of file TFramedViewBase.h.
References NULL.
Member Function Documentation
template<class ViewBase > void iview::TFramedViewBase< ViewBase >::CalcBoundingBox () const [protected, virtual]
Definition at line 388 of file TFramedViewBase.h.
template<class ViewBase > bool iview::TFramedViewBase< ViewBase >::CanBeMoved () const [protected, virtual]
Definition at line 375 of file TFramedViewBase.h.
References NULL.
template<class ViewBase > TFramedViewBase< ViewBase >::Frame * iview::TFramedViewBase< ViewBase >::GetFramePtr () const
Definition at line 139 of file TFramedViewBase.h.
template<class ViewBase > int iview::TFramedViewBase< ViewBase >::GetLogicalPositionExact () const
Get number of digits after point used to display mouse position in logical units.
template<class ViewBase > int iview::TFramedViewBase< ViewBase >::GetPixelPositionExact () const
Get number of digits after point used to display mouse position in pixel.
template<class ViewBase > void iview::TFramedViewBase< ViewBase >::OnAreaInvalidated (const i2d::CRect & beforeBox, const i2d::CRect & afterBox) [protected, virtual]
Definition at line 410 of file TFramedViewBase.h.
template<class ViewBase > void iview::TFramedViewBase< ViewBase >::OnBoundingBoxChanged () [protected, virtual]
Definition at line 354 of file TFramedViewBase.h.
References NULL.
template<class ViewBase > bool iview::TFramedViewBase< ViewBase >::OnMouseButton (const iview::IShapeView & view, const istd::CIndex2d & position, Qt::MouseButton buttonType, bool state, const iview::IInteractiveShape * shapePtr) [virtual]
Message handler for mouse button click.
Implements iview::IViewEventObserver.
Definition at line 307 of file TFramedViewBase.h.
template<class ViewBase > bool iview::TFramedViewBase< ViewBase >::OnMouseMove (istd::CIndex2d position) [virtual]
Definition at line 188 of file TFramedViewBase.h.
References iview::TFrameBase< ViewBase >::CursorInfo::alpha, iview::TFrameBase< ViewBase >::CursorInfo::blue, iview::IIsomorphicCalibration::GetApplyToLog(), iview::CScreenTransform::GetClientPosition(), iimg::IRasterImage::GetImageSize(), iimg::IBitmap::GetLinePtr(), imod::CSingleModelObserverBase::GetModelPtr(), iimg::IBitmap::GetPixelFormat(), iview::CSingleLayer::GetShapePtr(), istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), iview::TFrameBase< ViewBase >::CursorInfo::green, iview::TFrameBase< ViewBase >::CursorInfo::logicalPos, NULL, iimg::IBitmap::PF_GRAY, iimg::IBitmap::PF_RGB, iimg::IBitmap::PF_RGBA, iview::TFrameBase< ViewBase >::CursorInfo::pixelBrightness, iview::TFrameBase< ViewBase >::CursorInfo::pixelPos, iview::TFrameBase< ViewBase >::CursorInfo::red, and i2d::CVector2d::ToIndex2d().
template<class ViewBase > void iview::TFramedViewBase< ViewBase >::OnResize () [protected, virtual]
Definition at line 363 of file TFramedViewBase.h.
References NULL.
template<class ViewBase > bool iview::TFramedViewBase< ViewBase >::OnSelectChange (const iview::IShapeView & view, const istd::CIndex2d & position, const iview::IInteractiveShape & shape, bool state) [virtual]
Message handler for selection changes.
Implements iview::IViewEventObserver.
Definition at line 296 of file TFramedViewBase.h.
template<class ViewBase > void iview::TFramedViewBase< ViewBase >::SetBackgroundBufferValid (bool state = true) [protected, virtual]
Definition at line 325 of file TFramedViewBase.h.
References iview::TShapeBase< Base >::GetBoundingBox(), iview::CSingleLayer::GetShapePtr(), i2d::CRect::IsEmpty(), NULL, and iview::CViewBase::ZM_RESET.
template<class ViewBase > void iview::TFramedViewBase< ViewBase >::SetEditMode (int mode) [virtual]
Definition at line 270 of file TFramedViewBase.h.
template<class ViewBase > void iview::TFramedViewBase< ViewBase >::SetFitArea (const i2d::CRectangle & area) [virtual]
Definition at line 281 of file TFramedViewBase.h.
template<class ViewBase > void iview::TFramedViewBase< ViewBase >::SetFramework (TFrameBase< ViewBase > * framePtr)
Definition at line 132 of file TFramedViewBase.h.
template<class ViewBase > void iview::TFramedViewBase< ViewBase >::UpdateFitTransform ()
Definition at line 146 of file TFramedViewBase.h.
References iview::CViewBase::ZM_FIT, iview::CViewBase::ZM_FIT_COVER, iview::CViewBase::ZM_FIT_H, iview::CViewBase::ZM_FIT_UNPROP, iview::CViewBase::ZM_FIT_V, and iview::CViewBase::ZM_RESET.
Referenced by iview::TFrameBase< ViewBase >::SetFitMode(), iview::TFrameBase< ViewBase >::SetZoomToFit(), and iview::TFrameBase< ViewBase >::UpdateView().
The documentation for this class was generated from the following file:
Include/iview/TFramedViewBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy