iprm::TParamsPtr< ParameterInterace > Class Template Reference
iprm::TParamsPtr< ParameterInterace > Class Template Reference
Help pointer wrapper for management of a parameter from the parameter set.
#include <TParamsPtr.h>
Public Types
typedef istd::TPointerBase
< const ParameterInterace > BaseClass
Public Member Functions
TParamsPtr (const ParameterInterace *ptr=NULL)
TParamsPtr (const IParamsSet *parameterSetPtr, const QByteArray &parameterId, bool isObligatory=true)
Construct and initialize the pointer with the given parameter set and parameter ID.
TParamsPtr (const IParamsSet *parameterSetPtr, const icomp::TAttributeMember< icomp::CIdAttribute > &parameterIdAttribute, const icomp::TReferenceMember< ParameterInterace > &defaultRef, bool isObligatory=true)
Construct and initialize the pointer with the component parameters.
void Init (const IParamsSet *parameterSetPtr, const QByteArray &parameterId, bool isObligatory=true)
Initialize the pointer with the given parameter set and parameter ID.
void Init (const IParamsSet *parameterSetPtr, const icomp::TAttributeMember< icomp::CIdAttribute > &parameterIdAttribute, const icomp::TReferenceMember< ParameterInterace > &defaultRef, bool isObligatory=true)
Initialize the pointer with the component parameters.
Detailed Description
template<class ParameterInterace>
class iprm::TParamsPtr< ParameterInterace >
Help pointer wrapper for management of a parameter from the parameter set.
Definition at line 24 of file TParamsPtr.h.
Member Typedef Documentation
template<class ParameterInterace > typedef istd::TPointerBase<const ParameterInterace> iprm::TParamsPtr< ParameterInterace >::BaseClass
Definition at line 27 of file TParamsPtr.h.
Constructor & Destructor Documentation
template<class ParameterInterace > iprm::TParamsPtr< ParameterInterace >::TParamsPtr (const ParameterInterace * ptr = NULL)
Definition at line 76 of file TParamsPtr.h.
template<class ParameterInterace > iprm::TParamsPtr< ParameterInterace >::TParamsPtr (const IParamsSet * parameterSetPtr, const QByteArray & parameterId, bool isObligatory = true)
Construct and initialize the pointer with the given parameter set and parameter ID.
Parameters:
parameterSetPtr parameter set, parameter will be taken from this set.
parameterId ID of parameter in the set.
isObligatory indicate, that this parameter is obligatory.
Definition at line 83 of file TParamsPtr.h.
template<class ParameterInterace > iprm::TParamsPtr< ParameterInterace >::TParamsPtr (const IParamsSet * parameterSetPtr, const icomp::TAttributeMember< icomp::CIdAttribute > & parameterIdAttribute, const icomp::TReferenceMember< ParameterInterace > & defaultRef, bool isObligatory = true)
Construct and initialize the pointer with the component parameters.
Parameters:
parameterSetPtr parameter set, parameter will be taken from this set.
parameterIdAttribute component attribute storing ID of parameter in the set.
defaultRef component reference used if parameter is not found in the set.
isObligatory indicate, that this parameter is obligatory.
Definition at line 90 of file TParamsPtr.h.
Member Function Documentation
template<class ParameterInterace > void iprm::TParamsPtr< ParameterInterace >::Init (const IParamsSet * parameterSetPtr, const QByteArray & parameterId, bool isObligatory = true)
Initialize the pointer with the given parameter set and parameter ID.
Parameters:
parameterSetPtr parameter set, parameter will be taken from this set.
parameterId ID of parameter in the set.
isObligatory indicate, that this parameter is obligatory.
template<class ParameterInterace > void iprm::TParamsPtr< ParameterInterace >::Init (const IParamsSet * parameterSetPtr, const icomp::TAttributeMember< icomp::CIdAttribute > & parameterIdAttribute, const icomp::TReferenceMember< ParameterInterace > & defaultRef, bool isObligatory = true)
Initialize the pointer with the component parameters.
Parameters:
parameterSetPtr parameter set, parameter will be taken from this set.
parameterIdAttribute component attribute storing ID of parameter in the set.
defaultRef component reference used if parameter is not found in the set.
isObligatory indicate, that this parameter is obligatory.
Definition at line 128 of file TParamsPtr.h.
References iprm::IParamsSet::GetParameter(), iprm::IParamsSet::GetParamIds(), icomp::TReferenceMember< Interface >::GetPtr(), I_IF_DEBUG, icomp::TReferenceMember< Interface >::IsValid(), icomp::TAttributeMemberBase< Attribute >::IsValid(), and NULL.
The documentation for this class was generated from the following file:
Include/iprm/TParamsPtr.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy