istd::TDelPtr< Type, Accessor > Class Template Reference
istd::TDelPtr< Type, Accessor > Class Template Reference
Main concepts and implementations
Pointer wrapper providing automatic deleting pointed object during destruction.
#include <TDelPtr.h>
Public Types
typedef TPointerBase< Type > BaseClass
Public Member Functions
TDelPtr (Type *ptr=NULL)
Construct and init this pointer.
TDelPtr (const TDelPtr &ptr)
Copy constructor.
~TDelPtr ()
Destructor.
void Reset ()
Remove object pointed by internal pointer and set this pointer to NULL.
void SetPtr (Type *ptr)
Set new value of internal pointer.
Type * PopPtr ()
Reset internal pointer value without deleting instance and return previos value.
void TakeOver (TDelPtr &sourcePtr)
Take internal pointer over.
TDelPtr & operator= (const TDelPtr &ptr)
Assign operator.
TDelPtr & operator= (Type *ptr)
Assign operator.
template<class SourceType >
bool SetCastedOrRemove (SourceType *ptr)
Set internal pointer using casted pointer of other type.
Public Member Functions inherited from istd::TPointerBase< Type >
TPointerBase (Type *ptr=NULL)
Construct and assign internal pointer.
void SetPtr (Type *ptr)
Set value of internal stored pointer.
void Reset ()
Set internal pointer value to NULL.
Type * GetPtr () const
Return access to internal stored pointer.
bool IsValid () const
Check if internal pointer not NULL.
void Swap (TPointerBase &ptr)
Swap two pointers.
Type & operator* () const
Get an access to object pointed at.
template<class CastedType >
CastedType Cast () const
Type * operator-> () const
bool operator== (const TPointerBase< Type > &ptr) const
bool operator!= (const TPointerBase< Type > &ptr) const
bool operator< (const TPointerBase< Type > &ptr) const
bool operator> (const TPointerBase< Type > &ptr) const
bool operator<= (const TPointerBase< Type > &ptr) const
bool operator>= (const TPointerBase< Type > &ptr) const
bool operator== (const Type *ptr) const
bool operator!= (const Type *ptr) const
bool operator< (const Type *ptr) const
bool operator> (const Type *ptr) const
bool operator<= (const Type *ptr) const
bool operator>= (const Type *ptr) const
Protected Member Functions
void Detach ()
Remove referenced object.
Protected Member Functions inherited from istd::TPointerBase< Type >
TPointerBase< Type > & operator= (const TPointerBase< Type > ptr)
Type *& GetPtrRef ()
Detailed Description
template<class Type, class Accessor = DefaultAccessor<Type>>
class istd::TDelPtr< Type, Accessor >
Pointer wrapper providing automatic deleting pointed object during destruction.
Definition at line 19 of file TDelPtr.h.
Member Typedef Documentation
template<class Type, class Accessor = DefaultAccessor<Type>> typedef TPointerBase<Type> istd::TDelPtr< Type, Accessor >::BaseClass
Definition at line 22 of file TDelPtr.h.
Constructor & Destructor Documentation
template<class Type, class Accessor > istd::TDelPtr< Type, Accessor >::TDelPtr (Type * ptr = NULL) inline
Construct and init this pointer.
Parameters
ptr pointer to object.
Definition at line 110 of file TDelPtr.h.
template<class Type, class Accessor = DefaultAccessor<Type>> istd::TDelPtr< Type, Accessor >::TDelPtr (const TDelPtr< Type, Accessor > & ptr)
Copy constructor.
This implementation has no function and is provided only for compatibility with STL. The source pointer must be invalid (NULL).
template<class Type , class Accessor > istd::TDelPtr< Type, Accessor >::~TDelPtr () inline
Destructor.
It calls Reset() to delete pointed object.
Definition at line 125 of file TDelPtr.h.
References istd::TDelPtr< Type, Accessor >::Detach().
Member Function Documentation
template<class Type , class Accessor > void istd::TDelPtr< Type, Accessor >::Detach () protected
Remove referenced object.
Warning: internal pointer will be not changed.
Definition at line 191 of file TDelPtr.h.
References NULL.
Referenced by istd::TDelPtr< Type, Accessor >::~TDelPtr().
template<class Type, class Accessor = DefaultAccessor<Type>> TDelPtr& istd::TDelPtr< Type, Accessor >::operator= (const TDelPtr< Type, Accessor > & ptr)
Assign operator.
This implementation has no function and is provided only for compatibility with STL. The source pointer must be invalid (NULL).
template<class Type, class Accessor > TDelPtr< Type, Accessor > & istd::TDelPtr< Type, Accessor >::operator= (Type * ptr)
Assign operator.
It removes refererenced object before new is assigned.
Parameters
ptr pointer to object.
Definition at line 178 of file TDelPtr.h.
template<class Type , class Accessor > Type * istd::TDelPtr< Type, Accessor >::PopPtr () inline
Reset internal pointer value without deleting instance and return previos value.
Definition at line 148 of file TDelPtr.h.
References NULL.
Referenced by icomp::TComponentCloneWrap< BaseClass >::CloneMe(), iimg::TMultiPageBitmap< BitmapImpl >::CloneMe(), imod::TModelWrap< Base >::CloneMe(), ilog::TExtMessage< Element >::CloneMe(), icomp::TMultiFactoryMember< Interface >::CreateInstance(), icomp::TFactoryMember< Interface >::CreateInstance(), and istd::TDelPtr< Type, Accessor >::TakeOver().
template<class Type , class Accessor > void istd::TDelPtr< Type, Accessor >::Reset () inline
Remove object pointed by internal pointer and set this pointer to NULL.
Definition at line 132 of file TDelPtr.h.
References NULL.
template<class Type, class Accessor = DefaultAccessor<Type>> template<class SourceType > bool istd::TDelPtr< Type, Accessor >::SetCastedOrRemove (SourceType * ptr) inline
Set internal pointer using casted pointer of other type.
If casting is not possible, parameter object will be removed.
Definition at line 82 of file TDelPtr.h.
Referenced by icomp::TComponentCloneWrap< BaseClass >::CloneMe().
template<class Type, class Accessor > void istd::TDelPtr< Type, Accessor >::SetPtr (Type * ptr) inline
Set new value of internal pointer.
If internal pointer wasn't NULL, it will be deleted.
Definition at line 139 of file TDelPtr.h.
Referenced by icomp::CSimComponentContextBase::InsertMultiAttr(), and istd::TDelPtr< i2d::ICalibration2d >::SetCastedOrRemove().
template<class Type , class Accessor > void istd::TDelPtr< Type, Accessor >::TakeOver (TDelPtr< Type, Accessor > & sourcePtr)
Take internal pointer over.
It set pointer from other object and detach it from them.
Definition at line 158 of file TDelPtr.h.
References istd::TDelPtr< Type, Accessor >::PopPtr().
The documentation for this class was generated from the following file:
Include/istd/TDelPtr.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy