ACF: istd::TCachedUpdateManagerWrap< Base > Class Template Reference
istd::TCachedUpdateManagerWrap< Base > Class Template Reference
Help wrapper class supporting of cached parts.
#include <TCachedUpdateManagerWrap.h>
Public Types
typedef TUpdateManagerWrap< Base > BaseClass
Public Member Functions
TCachedUpdateManagerWrap ()
Protected Member Functions
bool EnsureCacheValid () const
Ensures cache is valid.
void InvalidateCache (int changeFlags=0)
Make cache invalid.
void SetCacheValid ()
Say that cache is valid.
virtual bool CalculateCache (int changeFlags)
Calculate cache.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Detailed Description
template<class Base>
class istd::TCachedUpdateManagerWrap< Base >
Help wrapper class supporting of cached parts.
If nested update is started, base class implementation of BeginChanges and EndChanges will be blocked.
Definition at line 17 of file TCachedUpdateManagerWrap.h.
Member Typedef Documentation
template<class Base> typedef TUpdateManagerWrap<Base> istd::TCachedUpdateManagerWrap< Base >::BaseClass
Reimplemented from istd::TUpdateManagerWrap< Base >.
Reimplemented in imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >, imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >, and imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >.
Definition at line 20 of file TCachedUpdateManagerWrap.h.
Constructor & Destructor Documentation
template<class Base > istd::TCachedUpdateManagerWrap< Base >::TCachedUpdateManagerWrap () [inline]
Definition at line 98 of file TCachedUpdateManagerWrap.h.
Member Function Documentation
template<class Base > bool istd::TCachedUpdateManagerWrap< Base >::CalculateCache (int changeFlags) [inline, protected, virtual]
Calculate cache.
It will be called, if cache was not valid and EnsureCacheValid() is called. Default implementation does nothing and is provided to ensure that base class for all derived classes implement this method.
Reimplemented in imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >, iqt::CReflectedBitmapBase, and imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >.
Definition at line 89 of file TCachedUpdateManagerWrap.h.
Referenced by istd::TCachedUpdateManagerWrap< Base >::EnsureCacheValid().
template<class Base > bool istd::TCachedUpdateManagerWrap< Base >::EnsureCacheValid () const [inline, protected]
Ensures cache is valid.
If cache is not valid method CalculateCache will be called to update it.
Definition at line 59 of file TCachedUpdateManagerWrap.h.
References istd::TCachedUpdateManagerWrap< Base >::CalculateCache().
template<class Base > void istd::TCachedUpdateManagerWrap< Base >::InvalidateCache (int changeFlags = 0) [inline, protected]
Make cache invalid.
This is automatically done when model/observer mechanism is used.
Definition at line 72 of file TCachedUpdateManagerWrap.h.
Referenced by istd::TCachedUpdateManagerWrap< Base >::OnEndChanges().
template<class Base > void istd::TCachedUpdateManagerWrap< Base >::OnEndChanges (int changeFlags, istd::IPolymorphic * changeParamsPtr = NULL) [inline, protected, virtual]
Definition at line 107 of file TCachedUpdateManagerWrap.h.
References istd::TCachedUpdateManagerWrap< Base >::InvalidateCache().
template<class Base > void istd::TCachedUpdateManagerWrap< Base >::SetCacheValid () [inline, protected]
Say that cache is valid.
Definition at line 80 of file TCachedUpdateManagerWrap.h.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/istd/TCachedUpdateManagerWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy