ACF: istd::TArray< Element, Dimensions > Class Template Reference
istd::TArray< Element, Dimensions > Class Template Reference
[Main concepts and implementations]
Multidimensional array with fixed number of dimensions.
#include <TArray.h>
Classes
class Iterator
Public Types
typedef TIndex< Dimensions > IndexType
typedef TIndex< Dimensions > SizesType
typedef Element ElementType
Public Member Functions
TArray ()
TArray (const TArray &array)
void Reset ()
Removes all elements and set all sizes to 1.
bool IsEmpty () const
Check if this array has no elements.
bool IsDimensionsCountFixed () const
Check, if number dimensions is fixed.
int GetDimensionsCount () const
Get number of dimensions of this array.
bool SetDimensionsCount (int count)
Set number of dimensions of this array.
const SizesType & GetSizes () const
Get list of all sizes.
bool SetSizes (const SizesType &sizes)
Set list of all sizes.
int GetSize (int dimension) const
Get size of array for specified dimension.
bool SetSize (int dimension, int size)
Set size of array for specified dimension.
const Element & GetAt (const IndexType &index) const
Get element stored at specified index.
Element & GetAtRef (const IndexType &index)
Get reference to element stored at specified index.
void SetAt (const IndexType &index, const Element &value)
Set element at specified index.
Iterator Begin () const
Get begin value of element access iterator.
const Iterator & End () const
Get end value of element access iterator.
const Element & operator[] (const IndexType &index) const
Element & operator[] (const IndexType &index)
Protected Types
typedef std::vector< Element > Elements
Protected Member Functions
int GetElementIndex (const IndexType &index) const
Get index of element in one dimensional array.
void UpdateElementsSize ()
Update size of elements to size changes.
void DeepCopy (const Elements &elements, const SizesType &sizes)
Detailed Description
template<class Element, int Dimensions>
class istd::TArray< Element, Dimensions >
Multidimensional array with fixed number of dimensions.
Definition at line 20 of file TArray.h.
Member Typedef Documentation
template<class Element, int Dimensions> typedef std::vector<Element> istd::TArray< Element, Dimensions >::Elements [protected]
Definition at line 146 of file TArray.h.
template<class Element, int Dimensions> typedef Element istd::TArray< Element, Dimensions >::ElementType
Definition at line 25 of file TArray.h.
template<class Element, int Dimensions> typedef TIndex<Dimensions> istd::TArray< Element, Dimensions >::IndexType
Definition at line 23 of file TArray.h.
template<class Element, int Dimensions> typedef TIndex<Dimensions> istd::TArray< Element, Dimensions >::SizesType
Definition at line 24 of file TArray.h.
Constructor & Destructor Documentation
template<class Element , int Dimensions> istd::TArray< Element, Dimensions >::TArray () [inline]
Definition at line 307 of file TArray.h.
template<class Element , int Dimensions> istd::TArray< Element, Dimensions >::TArray (const TArray< Element, Dimensions > & array) [inline]
Definition at line 316 of file TArray.h.
Member Function Documentation
template<class Element , int Dimensions> TArray< Element, Dimensions >::Iterator istd::TArray< Element, Dimensions >::Begin () const [inline]
Get begin value of element access iterator.
Please refer to general description of ACF iterators, STL iterators or Qt iterators concept.
Definition at line 254 of file TArray.h.
template<class Element , int Dimensions> void istd::TArray< Element, Dimensions >::DeepCopy (const Elements & elements, const SizesType & sizes) [inline, protected]
Definition at line 371 of file TArray.h.
References I_ASSERT.
template<class Element , int Dimensions> const TArray< Element, Dimensions >::Iterator & istd::TArray< Element, Dimensions >::End () const [inline]
Get end value of element access iterator.
Please refer to general description of ACF iterators, STL iterators or Qt iterators concept.
Definition at line 261 of file TArray.h.
template<class Element , int Dimensions> const Element & istd::TArray< Element, Dimensions >::GetAt (const IndexType & index) const [inline]
Get element stored at specified index.
Definition at line 216 of file TArray.h.
References istd::TArray< Element, Dimensions >::GetElementIndex(), I_ASSERT, and istd::TIndex< Dimensions >::IsInside().
Referenced by istd::TArray< Element, Dimensions >::Iterator::operator*(), istd::TArray< Element, Dimensions >::Iterator::operator->(), and istd::TArray< Element, Dimensions >::operator[]().
template<class Element , int Dimensions> Element & istd::TArray< Element, Dimensions >::GetAtRef (const IndexType & index) [inline]
Get reference to element stored at specified index.
Definition at line 228 of file TArray.h.
References istd::TArray< Element, Dimensions >::GetElementIndex(), I_ASSERT, and istd::TIndex< Dimensions >::IsInside().
template<class Element , int Dimensions> int istd::TArray< Element, Dimensions >::GetDimensionsCount () const [inline]
Get number of dimensions of this array.
Definition at line 185 of file TArray.h.
Referenced by istd::TArray< Element, Dimensions >::SetDimensionsCount().
template<class Element , int Dimensions> int istd::TArray< Element, Dimensions >::GetElementIndex (const IndexType & index) const [inline, protected]
Get index of element in one dimensional array.
Definition at line 287 of file TArray.h.
References I_ASSERT.
Referenced by istd::TArray< Element, Dimensions >::GetAt(), istd::TArray< Element, Dimensions >::GetAtRef(), istd::TArray< Element, Dimensions >::operator[](), and istd::TArray< Element, Dimensions >::SetAt().
template<class Element , int Dimensions> int istd::TArray< Element, Dimensions >::GetSize (int dimension) const [inline]
Get size of array for specified dimension.
Definition at line 206 of file TArray.h.
References I_ASSERT.
template<class Element , int Dimensions> const TArray< Element, Dimensions >::SizesType & istd::TArray< Element, Dimensions >::GetSizes () const [inline]
Get list of all sizes.
Definition at line 199 of file TArray.h.
Referenced by istd::TArray< Element, Dimensions >::Iterator::Iterator(), istd::TArray< Element, Dimensions >::Iterator::operator*(), istd::TArray< Element, Dimensions >::Iterator::operator++(), istd::TArray< Element, Dimensions >::Iterator::operator--(), and istd::TArray< Element, Dimensions >::Iterator::operator->().
template<class Element , int Dimensions> bool istd::TArray< Element, Dimensions >::IsDimensionsCountFixed () const [inline]
Check, if number dimensions is fixed.
It is provided for template implementations. It returns always true.
Definition at line 178 of file TArray.h.
template<class Element , int Dimensions> bool istd::TArray< Element, Dimensions >::IsEmpty () const [inline]
Check if this array has no elements.
Definition at line 171 of file TArray.h.
References istd::TIndex< Dimensions >::IsSizeEmpty().
template<class Element , int Dimensions> Element & istd::TArray< Element, Dimensions >::operator[] (const IndexType & index) [inline]
Definition at line 275 of file TArray.h.
References istd::TArray< Element, Dimensions >::GetElementIndex(), and I_ASSERT.
template<class Element , int Dimensions> const Element & istd::TArray< Element, Dimensions >::operator[] (const IndexType & index) const [inline]
Definition at line 268 of file TArray.h.
References istd::TArray< Element, Dimensions >::GetAt().
template<class Element , int Dimensions> void istd::TArray< Element, Dimensions >::Reset () [inline]
Removes all elements and set all sizes to 1.
Definition at line 323 of file TArray.h.
References istd::TIndex< Dimensions >::Reset().
template<class Element, int Dimensions> void istd::TArray< Element, Dimensions >::SetAt (const IndexType & index, const Element & value) [inline]
Set element at specified index.
Definition at line 240 of file TArray.h.
References istd::TArray< Element, Dimensions >::GetElementIndex(), I_ASSERT, and istd::TIndex< Dimensions >::IsInside().
template<class Element , int Dimensions> bool istd::TArray< Element, Dimensions >::SetDimensionsCount (int count) [inline]
Set number of dimensions of this array.
This is only dummy method, to provide methods compatibility with template implementations.
Parameters:
count number of dimensions will be set.
Returns:
true, if number of set dimensions equals template parameter, or false if isn't.
Definition at line 192 of file TArray.h.
References istd::TArray< Element, Dimensions >::GetDimensionsCount().
template<class Element , int Dimensions> bool istd::TArray< Element, Dimensions >::SetSize (int dimension, int size) [inline]
Set size of array for specified dimension.
Please note, that it can make all elements invalid.
Returns:
always true, it is provided for generic implementations.
Definition at line 343 of file TArray.h.
References I_ASSERT, and istd::TArray< Element, Dimensions >::UpdateElementsSize().
template<class Element , int Dimensions> bool istd::TArray< Element, Dimensions >::SetSizes (const SizesType & sizes) [inline]
Set list of all sizes.
Returns:
always true, it is provided for generic implementations.
Definition at line 332 of file TArray.h.
References istd::TArray< Element, Dimensions >::UpdateElementsSize().
template<class Element , int Dimensions> void istd::TArray< Element, Dimensions >::UpdateElementsSize () [inline, protected]
Update size of elements to size changes.
Definition at line 359 of file TArray.h.
Referenced by istd::TArray< Element, Dimensions >::SetSize(), and istd::TArray< Element, Dimensions >::SetSizes().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/istd/TArray.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy