istd::TTransPtr< Type > Class Template Reference
istd::TTransPtr< Type > Class Template Reference
Implementation of data transfer smart pointer.
#include <TTransPtr.h>
Classes
class RefCountBase
Public Member Functions
TTransPtr (const TTransPtr &pointer)
Constructor overtaking the pointer.
~TTransPtr ()
bool IsValid () const
Check, whether the object is in valid state.
const Type * GetPtr () const
Get access to pointed object.
Type * GetPtr ()
Get access to pointed object.
void Reset ()
Set this pointer to NULL.
void Swap (TTransPtr &pointer)
Swap two pointers.
template<class CastedType >
CastedType Cast () const
TTransPtr & operator= (const TTransPtr &pointer)
Copy operator overtaking the pointer.
Type & operator* () const
Type * operator-> () const
Protected Member Functions
TTransPtr ()
void Detach ()
Detach counter object without changing of internal counter pointer.
RefCountBase * GetInternalCounter (const TTransPtr &pointer) const
Get internal counter.
Protected Attributes
RefCountBase * m_counterPtr
Detailed Description
template<class Type>
class istd::TTransPtr< Type >
Implementation of data transfer smart pointer.
It should be used to pointer transfer only, not to store the pointers becouse it overtakes the pointer. Typically it is used as smart pointer return parameters. The adventage against 'normal' smart pointer (istd::TSmartPtr) is that the copy constructor is faster, because it overtakes the pointer.
See Also
istd::TSmartPtr
Definition at line 20 of file TTransPtr.h.
Constructor & Destructor Documentation
template<class Type > istd::TTransPtr< Type >::TTransPtr (const TTransPtr< Type > & pointer)
Constructor overtaking the pointer.
Parameters
pointer pointer to overtake - warning: After this operation this pointer is invalid!
Definition at line 112 of file TTransPtr.h.
References istd::TTransPtr< Type >::m_counterPtr, and NULL.
template<class Type > istd::TTransPtr< Type >::~TTransPtr ()
Definition at line 120 of file TTransPtr.h.
template<class Type > istd::TTransPtr< Type >::TTransPtr () protected
Definition at line 211 of file TTransPtr.h.
Member Function Documentation
template<class Type> template<class CastedType > CastedType istd::TTransPtr< Type >::Cast () const inline
Definition at line 56 of file TTransPtr.h.
template<class Type > void istd::TTransPtr< Type >::Detach () inline protected
Detach counter object without changing of internal counter pointer.
Definition at line 217 of file TTransPtr.h.
References NULL.
template<class Type > TTransPtr< Type >::RefCountBase * istd::TTransPtr< Type >::GetInternalCounter (const TTransPtr< Type > & pointer) const protected
Get internal counter.
Definition at line 226 of file TTransPtr.h.
References istd::TTransPtr< Type >::m_counterPtr.
Referenced by istd::TSmartPtr< Type, Accessor >::TSmartPtr().
template<class Type > const Type * istd::TTransPtr< Type >::GetPtr () const inline
Get access to pointed object.
Definition at line 134 of file TTransPtr.h.
References NULL.
Referenced by ibase::TFactorisableContainer< InterfaceClass >::AddElement(), istd::TTransPtr< istd::IChangeable >::Cast(), ibase::TFactorisableContainer< InterfaceClass >::InsertElement(), and idoc::TMultiPageDocumentWrap< Base >::SerializePage().
template<class Type > Type * istd::TTransPtr< Type >::GetPtr () inline
Get access to pointed object.
Definition at line 146 of file TTransPtr.h.
References NULL.
template<class Type > bool istd::TTransPtr< Type >::IsValid () const
Check, whether the object is in valid state.
Definition at line 127 of file TTransPtr.h.
References NULL.
Referenced by ibase::TFactorisableContainer< InterfaceClass >::AddElement(), and ibase::TFactorisableContainer< InterfaceClass >::InsertElement().
template<class Type > Type & istd::TTransPtr< Type >::operator* () const inline
Definition at line 189 of file TTransPtr.h.
References NULL.
template<class Type > Type * istd::TTransPtr< Type >::operator-> () const inline
Definition at line 199 of file TTransPtr.h.
References NULL.
template<class Type > TTransPtr< Type > & istd::TTransPtr< Type >::operator= (const TTransPtr< Type > & pointer)
Copy operator overtaking the pointer.
Parameters
pointer pointer to overtake - warning: After this operation this pointer is invalid!
Definition at line 174 of file TTransPtr.h.
References istd::TTransPtr< Type >::m_counterPtr, and NULL.
template<class Type > void istd::TTransPtr< Type >::Reset ()
Set this pointer to NULL.
Definition at line 158 of file TTransPtr.h.
References NULL.
template<class Type > void istd::TTransPtr< Type >::Swap (TTransPtr< Type > & pointer)
Swap two pointers.
Definition at line 167 of file TTransPtr.h.
References istd::TTransPtr< Type >::m_counterPtr.
Member Data Documentation
template<class Type> RefCountBase* istd::TTransPtr< Type >::m_counterPtr protected
Definition at line 105 of file TTransPtr.h.
Referenced by istd::TTransPtr< Type >::GetInternalCounter(), istd::TTransPtr< Type >::operator=(), istd::TTransPtr< Type >::Swap(), istd::TSmartPtr< Type, Accessor >::TSmartPtr(), and istd::TTransPtr< Type >::TTransPtr().
The documentation for this class was generated from the following file:
Include/istd/TTransPtr.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy