iview::ISelectable Class Reference
iview::ISelectable Class Reference abstract
#include <ISelectable.h>
Public Types
enum MousePointerMode {
MPM_NONE, MPM_DEFAULT, MPM_DESELECT, MPM_POINTER,
MPM_WAIT, MPM_CROSS, MPM_HAND, MPM_DRAG,
MPM_SCREEN_MOVE, MPM_LAST = MPM_SCREEN_MOVE
}
Defines possible states of mouse pointer.
enum EditMode { EM_NONE = 0, EM_MOVE = 1, EM_ADD = 2, EM_REMOVE = 3 }
Describes standard edit modes.
typedef QSet< IInteractiveShape * > SelectedShapes
Public Types inherited from iview::ITouchable
enum TouchState {
TS_NONE, TS_INACTIVE, TS_TICKER, TS_DRAGGABLE,
TS_OTHER, TS_LAST = TS_OTHER
}
Enumeration for possible shape touch states.
Public Member Functions
virtual int GetSelectedShapesCount () const =0
Get count of selected shapes.
virtual void InsertSelectedShapes (SelectedShapes &result) const =0
Get set of selected shapes.
virtual void DeselectAllShapes ()=0
Set all shapes to be deselected.
virtual int GetKeysState () const =0
Get state of system keys.
virtual int GetEditMode () const =0
Get actual edit mode.
virtual void OnShapeFocused (IInteractiveShape *shapePtr)=0
Called when shape get focus.
virtual void OnShapeDefocused (IInteractiveShape *shapePtr)=0
Called when shape loose focus.
virtual void OnShapeSelected (IInteractiveShape &shape, bool state=true)=0
It is called after change shape selection state.
Public Member Functions inherited from iview::ITouchable
virtual TouchState IsTouched (istd::CIndex2d position) const =0
Check, if any shape is touched.
virtual QString GetShapeDescriptionAt (istd::CIndex2d position) const =0
Get description to shape at specified position.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Detailed Description
Definition at line 21 of file ISelectable.h.
Member Typedef Documentation
typedef QSet<IInteractiveShape*> iview::ISelectable::SelectedShapes
Definition at line 24 of file ISelectable.h.
Member Enumeration Documentation
enum iview::ISelectable::EditMode
Describes standard edit modes.
Enumerator
EM_NONE
EM_MOVE
EM_ADD
EM_REMOVE
Definition at line 46 of file ISelectable.h.
enum iview::ISelectable::MousePointerMode
Defines possible states of mouse pointer.
Enumerator
MPM_NONE
MPM_DEFAULT
MPM_DESELECT
MPM_POINTER
MPM_WAIT
MPM_CROSS
MPM_HAND
MPM_DRAG
MPM_SCREEN_MOVE
MPM_LAST
Definition at line 29 of file ISelectable.h.
Member Function Documentation
virtual void iview::ISelectable::DeselectAllShapes () pure virtual
Set all shapes to be deselected.
Implemented in iview::CViewBase, and iview::CInteractiveViewLayer.
virtual int iview::ISelectable::GetEditMode () const pure virtual
Get actual edit mode.
Implemented in iview::CViewBase, and iview::CInteractiveViewLayer.
Referenced by iview::CInteractiveViewLayer::GetEditMode(), and iview::CInteractiveShapeBase::GetEditMode().
virtual int iview::ISelectable::GetKeysState () const pure virtual
Get state of system keys.
Implemented in iview::CViewBase, and iview::CInteractiveViewLayer.
Referenced by iview::CInteractiveViewLayer::GetKeysState(), and iview::CInteractiveShapeBase::GetKeysState().
virtual int iview::ISelectable::GetSelectedShapesCount () const pure virtual
Get count of selected shapes.
Implemented in iview::CViewBase, and iview::CInteractiveViewLayer.
virtual void iview::ISelectable::InsertSelectedShapes (SelectedShapes & result) const pure virtual
Get set of selected shapes.
Implemented in iview::CViewBase, and iview::CInteractiveViewLayer.
virtual void iview::ISelectable::OnShapeDefocused (IInteractiveShape * shapePtr) pure virtual
Called when shape loose focus.
Implemented in iview::CViewBase, and iview::CInteractiveViewLayer.
virtual void iview::ISelectable::OnShapeFocused (IInteractiveShape * shapePtr) pure virtual
Called when shape get focus.
Implemented in iview::CViewBase, and iview::CInteractiveViewLayer.
virtual void iview::ISelectable::OnShapeSelected (IInteractiveShape & shape, bool state = true) pure virtual
It is called after change shape selection state.
Implemented in iview::CViewBase, and iview::CInteractiveViewLayer.
The documentation for this class was generated from the following file:
Include/iview/ISelectable.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy