ACF: imod::TModelDispatcher< NotifyReceiver > Class Template Reference
imod::TModelDispatcher< NotifyReceiver > Class Template Reference
Generic implementation of a data model changes notifier.
#include <TModelDispatcher.h>
Public Types
typedef
imod::CMultiModelObserverBase BaseClass
Public Member Functions
TModelDispatcher (NotifyReceiver &parent)
~TModelDispatcher ()
bool RegisterModel (imod::IModel *modelPtr, int modelId=0, int relevantFlags=0)
Register the data model to be observed.
void UnregisterModel (int modelId=0)
Unregister the data model object.
void UnregisterAllModels ()
Unregister all observed data objects.
template<class Object >
Object * GetObjectPtr (int modelId) const
Get concrete object instance of the obsered model.
Protected Member Functions
virtual bool OnDetached (imod::IModel *modelPtr)
This call back function will be called, if an observable object is about to be detached.
virtual void OnUpdate (imod::IModel *modelPtr, int changeFlags, istd::IPolymorphic *updateParamsPtr)
Detailed Description
template<class NotifyReceiver>
class imod::TModelDispatcher< NotifyReceiver >
Generic implementation of a data model changes notifier.
You can register several data models objects that you want to observe with RegisterModel method. You will get a notification event on each change in the observed data model via OnModelChanged method call of your notification consumer.
Note:
Notification consumer class must implement the method void OnModelChanged(int modelId, int changeFlags, istd::IPolymorphic* updateParamsPtr) to support the notification callback.
Definition at line 26 of file TModelDispatcher.h.
Member Typedef Documentation
template<class NotifyReceiver> typedef imod::CMultiModelObserverBase imod::TModelDispatcher< NotifyReceiver >::BaseClass
Definition at line 29 of file TModelDispatcher.h.
Constructor & Destructor Documentation
template<class NotifyReceiver> imod::TModelDispatcher< NotifyReceiver >::TModelDispatcher (NotifyReceiver & parent)
Definition at line 83 of file TModelDispatcher.h.
template<class NotifyReceiver > imod::TModelDispatcher< NotifyReceiver >::~TModelDispatcher ()
Definition at line 90 of file TModelDispatcher.h.
Member Function Documentation
template<class NotifyReceiver > template<class Object > Object * imod::TModelDispatcher< NotifyReceiver >::GetObjectPtr (int modelId) const
Get concrete object instance of the obsered model.
Definition at line 149 of file TModelDispatcher.h.
References NULL.
template<class NotifyReceiver > bool imod::TModelDispatcher< NotifyReceiver >::OnDetached (imod::IModel * modelPtr) [protected, virtual]
This call back function will be called, if an observable object is about to be detached.
Reimplemented from imod::CMultiModelObserverBase.
Definition at line 168 of file TModelDispatcher.h.
template<class NotifyReceiver > void imod::TModelDispatcher< NotifyReceiver >::OnUpdate (imod::IModel * modelPtr, int changeFlags, istd::IPolymorphic * updateParamsPtr) [protected, virtual]
Reimplemented from imod::CMultiModelObserverBase.
Definition at line 189 of file TModelDispatcher.h.
template<class NotifyReceiver > bool imod::TModelDispatcher< NotifyReceiver >::RegisterModel (imod::IModel * modelPtr, int modelId = 0, int relevantFlags = 0)
Register the data model to be observed.
If model registration was successfull, the function returns true.
Parameters:
modelPtr Pointer to the data model object, which should be observed.
modelId Logical model ID for possible event filtering in the notification callback.
relefantFlags The notification will only be triggered if the value of relevantFlags matches the model change flags.
Definition at line 97 of file TModelDispatcher.h.
References imod::IModel::AttachObserver().
template<class NotifyReceiver > void imod::TModelDispatcher< NotifyReceiver >::UnregisterAllModels ()
Unregister all observed data objects.
Definition at line 131 of file TModelDispatcher.h.
References imod::IModel::DetachObserver().
template<class NotifyReceiver > void imod::TModelDispatcher< NotifyReceiver >::UnregisterModel (int modelId = 0)
Unregister the data model object.
Parameters:
modelId object ID used at the object registration.
See also:
RegisterModel
Definition at line 114 of file TModelDispatcher.h.
References imod::IModel::DetachObserver().
The documentation for this class was generated from the following file:
C:/Temp/Acf/Include/imod/TModelDispatcher.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy