ACF: icomp::TAttributeMember< Attribute > Class Template Reference
icomp::TAttributeMember< Attribute > Class Template Reference
Pointer to component attribute.
#include <TAttributeMember.h>
Public Types
typedef Attribute AttributeType
typedef void InterfaceType
Public Member Functions
TAttributeMember ()
bool Init (const IComponent *ownerPtr, const IRealAttributeStaticInfo &staticInfo, const IComponent **definitionComponentPtr=NULL)
Initialize this attribute.
bool IsValid () const
Check if this attribute is valid.
const Attribute * GetAttributePtr () const
Access to internal attribute pointer.
const Attribute * operator-> () const
Access to internal attribute pointer.
const Attribute::ValueType & operator* () const
Access to object pointed by internal pointer.
Protected Member Functions
void SetAttribute (const Attribute *attributePtr)
Detailed Description
template<typename Attribute>
class icomp::TAttributeMember< Attribute >
Pointer to component attribute.
Definition at line 19 of file TAttributeMember.h.
Member Typedef Documentation
template<typename Attribute> typedef Attribute icomp::TAttributeMember< Attribute >::AttributeType
Definition at line 22 of file TAttributeMember.h.
template<typename Attribute> typedef void icomp::TAttributeMember< Attribute >::InterfaceType
Reimplemented in icomp::TFactoryMember< Interface >, and icomp::TReferenceMember< Interface >.
Definition at line 23 of file TAttributeMember.h.
Constructor & Destructor Documentation
template<typename Attribute > icomp::TAttributeMember< Attribute >::TAttributeMember () [inline]
Definition at line 69 of file TAttributeMember.h.
Member Function Documentation
template<typename Attribute > const Attribute * icomp::TAttributeMember< Attribute >::GetAttributePtr () const [inline]
Access to internal attribute pointer.
Definition at line 123 of file TAttributeMember.h.
template<typename Attribute > bool icomp::TAttributeMember< Attribute >::Init (const IComponent * ownerPtr, const IRealAttributeStaticInfo & staticInfo, const IComponent ** definitionComponentPtr = NULL) [inline]
Initialize this attribute.
Parameters:
ownerPtr pointer to parent component of this attribute.
staticInfo static info structure creating this attribute.
definitionComponentPtr optional pointer will be set with pointer to component defining this attribute. If this attribute was exported it will differ from parent component.
Definition at line 76 of file TAttributeMember.h.
References icomp::IComponentContext::GetAttribute(), icomp::IRealAttributeStaticInfo::GetAttributeId(), icomp::IComponent::GetComponentContext(), icomp::IComponent::GetParentComponent(), I_ASSERT, and NULL.
template<typename Attribute > bool icomp::TAttributeMember< Attribute >::IsValid () const [inline]
Check if this attribute is valid.
Reimplemented in icomp::TFactoryMember< Interface >, and icomp::TReferenceMember< Interface >.
Definition at line 116 of file TAttributeMember.h.
References NULL.
template<typename Attribute > const Attribute::ValueType & icomp::TAttributeMember< Attribute >::operator* () const [inline]
Access to object pointed by internal pointer.
Definition at line 137 of file TAttributeMember.h.
References I_ASSERT, and NULL.
template<typename Attribute > const Attribute * icomp::TAttributeMember< Attribute >::operator-> () const [inline]
Access to internal attribute pointer.
Reimplemented in icomp::TReferenceMember< Interface >.
Definition at line 130 of file TAttributeMember.h.
template<typename Attribute> void icomp::TAttributeMember< Attribute >::SetAttribute (const Attribute * attributePtr) [inline, protected]
Definition at line 148 of file TAttributeMember.h.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/icomp/TAttributeMember.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy