ACF: iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType > Class Template Reference
iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType > Class Template Reference
#include <TSupplierGuiCompBase.h>
Public Types
typedef
iqt2d::TSceneExtenderCompBase
< iqtgui::TDesignerGuiObserverCompBase
< UI, Model > > BaseClass
Public Member Functions
TSupplierGuiCompBase ()
virtual void AddItemsToScene (iqt2d::ISceneProvider *providerPtr, int flags)
Called when items should be added to specified scene.
virtual void RemoveItemsFromScene (iqt2d::ISceneProvider *providerPtr)
Called when items should be removed from specified scene.
Protected Member Functions
bool AreParamsEditable () const
Check, if parameters are correct connected to GUI and can be editable.
bool IsLoadParamsSupported () const
Check if parameter loading is supported.
bool IsSaveParamsSupported () const
Check if parameter storing is supported.
bool LoadParams ()
Load parameters from external source (file).
bool SaveParams ()
Save parameters for example to file.
bool DoTest ()
Do inspection test.
virtual void OnGuiModelAttached ()
Called when model is attached and GUI is created.
virtual void OnGuiModelDetached ()
Called when model is detached or GUI is destroyed.
virtual void CreateShapes (int sceneId, bool inactiveOnly, Shapes &result)
virtual QWidget * GetParamsWidget () const =0
Get parameters widget object.
Detailed Description
template<class UI, class Model, class WidgetType = QWidget>
class iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >
Definition at line 27 of file TSupplierGuiCompBase.h.
Member Typedef Documentation
template<class UI, class Model, class WidgetType = QWidget> typedef iqt2d::TSceneExtenderCompBase<iqtgui::TDesignerGuiObserverCompBase<UI, Model> > iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >::BaseClass
Reimplemented from iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< UI, Model > >.
Reimplemented in iqtproc::CGeneralSupplierGuiComp.
Definition at line 30 of file TSupplierGuiCompBase.h.
Constructor & Destructor Documentation
template<class UI , class Model , class WidgetType > iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >::TSupplierGuiCompBase () [inline]
Definition at line 106 of file TSupplierGuiCompBase.h.
Member Function Documentation
template<class UI , class Model , class WidgetType > void iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >::AddItemsToScene (iqt2d::ISceneProvider * providerPtr, int flags) [inline, virtual]
Called when items should be added to specified scene.
Reimplemented from iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< UI, Model > >.
Definition at line 115 of file TSupplierGuiCompBase.h.
References iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< UI, Model > >::AddItemsToScene().
template<class UI , class Model , class WidgetType > bool iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >::AreParamsEditable () const [inline, protected]
Check, if parameters are correct connected to GUI and can be editable.
Definition at line 139 of file TSupplierGuiCompBase.h.
template<class UI , class Model , class WidgetType > void iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >::CreateShapes (int sceneId, bool inactiveOnly, Shapes & result) [inline, protected, virtual]
Implements iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< UI, Model > >.
Definition at line 302 of file TSupplierGuiCompBase.h.
template<class UI , class Model , class WidgetType > bool iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >::DoTest () [inline, protected]
Do inspection test.
Definition at line 232 of file TSupplierGuiCompBase.h.
References iproc::ISupplier::EnsureWorkFinished(), imod::TSingleModelObserverBase< Model >::GetObjectPtr(), iproc::ISupplier::GetWorkStatus(), iproc::ISupplier::InvalidateSupplier(), NULL, and iproc::ISupplier::WS_ERROR.
template<class UI, class Model, class WidgetType = QWidget> virtual QWidget* iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >::GetParamsWidget () const [protected, pure virtual]
Get parameters widget object.
Extern paremeters GUI will attach to this widget. This widget should have some layout.
Implemented in iqtproc::CGeneralSupplierGuiComp.
Referenced by iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >::OnGuiModelAttached().
template<class UI , class Model , class WidgetType > bool iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >::IsLoadParamsSupported () const [inline, protected]
Check if parameter loading is supported.
Definition at line 146 of file TSupplierGuiCompBase.h.
References imod::TSingleModelObserverBase< Model >::GetObjectPtr(), NULL, iser::IFileLoader::QF_ANONYMOUS_ONLY, and iser::IFileTypeInfo::QF_NO_SAVING.
template<class UI , class Model , class WidgetType > bool iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >::IsSaveParamsSupported () const [inline, protected]
Check if parameter storing is supported.
Definition at line 166 of file TSupplierGuiCompBase.h.
References imod::TSingleModelObserverBase< Model >::GetObjectPtr(), NULL, iser::IFileLoader::QF_ANONYMOUS_ONLY, and iser::IFileTypeInfo::QF_NO_LOADING.
template<class UI , class Model , class WidgetType > bool iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >::LoadParams () [inline, protected]
Load parameters from external source (file).
Definition at line 186 of file TSupplierGuiCompBase.h.
References imod::TSingleModelObserverBase< Model >::GetObjectPtr(), NULL, and iser::IFileLoader::StateFailed.
template<class UI , class Model , class WidgetType > void iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >::OnGuiModelAttached () [inline, protected, virtual]
Called when model is attached and GUI is created.
Reimplemented from iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< UI, QWidget >, imod::TSingleModelObserverBase< Model > >.
Reimplemented in iqtproc::CGeneralSupplierGuiComp.
Definition at line 249 of file TSupplierGuiCompBase.h.
References imod::IModel::AttachObserver(), imod::TSingleModelObserverBase< Model >::GetObjectPtr(), iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >::GetParamsWidget(), I_ASSERT, NULL, and iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< UI, QWidget >, imod::TSingleModelObserverBase< Model > >::OnGuiModelAttached().
template<class UI , class Model , class WidgetType > void iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >::OnGuiModelDetached () [inline, protected, virtual]
Called when model is detached or GUI is destroyed.
Reimplemented from iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< UI, QWidget >, imod::TSingleModelObserverBase< Model > >.
Definition at line 275 of file TSupplierGuiCompBase.h.
References imod::IModel::DetachObserver(), imod::TSingleModelObserverBase< Model >::GetObjectPtr(), I_ASSERT, imod::IModel::IsAttached(), NULL, and iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< UI, QWidget >, imod::TSingleModelObserverBase< Model > >::OnGuiModelDetached().
template<class UI , class Model , class WidgetType > void iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >::RemoveItemsFromScene (iqt2d::ISceneProvider * providerPtr) [inline, virtual]
Called when items should be removed from specified scene.
Reimplemented from iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< UI, Model > >.
Definition at line 126 of file TSupplierGuiCompBase.h.
References iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< UI, Model > >::RemoveItemsFromScene().
template<class UI , class Model , class WidgetType > bool iqtproc::TSupplierGuiCompBase< UI, Model, WidgetType >::SaveParams () [inline, protected]
Save parameters for example to file.
Definition at line 209 of file TSupplierGuiCompBase.h.
References imod::TSingleModelObserverBase< Model >::GetObjectPtr(), NULL, and iser::IFileLoader::StateFailed.
The documentation for this class was generated from the following file:
E:/Work/Projects/Developement/Acf/Include/iqtproc/TSupplierGuiCompBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy