imath::CVarVector Class Reference
imath::CVarVector Class Reference
Simple implementation of variable-size vector.
#include <CVarVector.h>
Public Types
typedef QVector< double > Elements
Public Member Functions
CVarVector ()
Create the vector without components.
CVarVector (int componentsCount, double value=0)
Create vector and initialize number of components.
CVarVector (const CVarVector &vector)
Copy constructor.
template<int Size>
CVarVector (const TVector< Size, double > &vector)
bool IsEmpty () const
Get true, if the element ist is empty.
int GetElementsCount () const
Get number of elements.
bool SetElementsCount (int count, double value=0)
Set number of elements.
double GetElement (int index) const
Get element at specified index.
double & GetElementRef (int index)
Get reference to element at specified index.
void SetElement (int index, double value)
Set element at specified index.
void Reset ()
Set size to zero.
void Reset (int elementsCount, double value)
Set number of elements and set all elements to specified value.
void Clear ()
Set all coordinates to zero.
void SetElementsFrom (const CVarVector &vector, double expansionValue=0)
Set elemenents from other vector without resizing.
const Elements & GetElements () const
Get read-only access to internal element container.
Elements & GetElementsRef ()
Get access to internal element container.
bool EnsureElementsCount (int count, double value=0)
Ensure, that number of elements is at least the specified value.
void Translate (const CVarVector &vector)
Translate the point.
CVarVector GetTranslated (const CVarVector &vector)
Get translated point.
void GetTranslated (const CVarVector &vector, CVarVector &result)
/overloaded
void ScaledCumulate (const CVarVector &vector, double scale)
Add second vector scaled by specified factor.
bool IsNull (double tolerance=I_BIG_EPSILON) const
Check if this vector is null.
double GetDotProduct (const CVarVector &vector) const
Return dot product of two vectors.
double GetLength2 () const
Return euclidian length square.
double GetLength () const
Return euclidian length.
double GetDistance2 (const CVarVector &vector) const
Return distance square between two vectors.
double GetDistance (const CVarVector &vector) const
Return distance between two vectors.
double GetElementsSum () const
Get simple sum of all elements.
bool Normalize (double length=1.0)
Normalize vector to specified length.
bool GetNormalized (CVarVector &result, double length=1.0) const
Return normalized vector with the same direction and specified length.
void GetMinimal (const CVarVector &vector, CVarVector &result) const
Get vector with minimal elements values.
void GetMaximal (const CVarVector &vector, CVarVector &result) const
Get vector with maximal elements values.
bool Serialize (iser::IArchive &archive)
Serialize this vector to specified archive.
bool operator== (const CVarVector &vector) const
bool operator!= (const CVarVector &vector) const
bool operator< (const CVarVector &vector) const
bool operator> (const CVarVector &vector) const
bool operator<= (const CVarVector &vector) const
bool operator>= (const CVarVector &vector) const
CVarVector operator- () const
CVarVector operator+ (const CVarVector &vector) const
CVarVector operator- (const CVarVector &vector) const
CVarVector operator* (double scalar) const
CVarVector operator/ (double scalar) const
CVarVector & operator+= (const CVarVector &vector)
CVarVector & operator-= (const CVarVector &vector)
CVarVector & operator*= (double scalar)
CVarVector & operator/= (double scalar)
CVarVector & operator= (const CVarVector &vector)
double operator[] (int i) const
double & operator[] (int i)
Detailed Description
Simple implementation of variable-size vector.
Definition at line 26 of file CVarVector.h.
Member Typedef Documentation
typedef QVector<double> imath::CVarVector::Elements
Definition at line 29 of file CVarVector.h.
Constructor & Destructor Documentation
imath::CVarVector::CVarVector () inline
Create the vector without components.
Definition at line 232 of file CVarVector.h.
imath::CVarVector::CVarVector (int componentsCount, double value = 0) inline explicit
Create vector and initialize number of components.
Definition at line 237 of file CVarVector.h.
imath::CVarVector::CVarVector (const CVarVector & vector) inline
Copy constructor.
Definition at line 243 of file CVarVector.h.
template<int Size> imath::CVarVector::CVarVector (const TVector< Size, double > & vector)
Definition at line 627 of file CVarVector.h.
Member Function Documentation
void imath::CVarVector::Clear () inline
Set all coordinates to zero.
Definition at line 303 of file CVarVector.h.
References GetElementsCount().
bool imath::CVarVector::EnsureElementsCount (int count, double value = 0)
Ensure, that number of elements is at least the specified value.
It resize the vector if the new size is bigger than the current one.
Returns
always true, this value is provided for template implementations.
double imath::CVarVector::GetDistance (const CVarVector & vector) const inline
Return distance between two vectors.
Definition at line 407 of file CVarVector.h.
References GetDistance2().
Referenced by icmm::CVarColor::IsSimilar().
double imath::CVarVector::GetDistance2 (const CVarVector & vector) const inline
Return distance square between two vectors.
Definition at line 401 of file CVarVector.h.
Referenced by GetDistance().
double imath::CVarVector::GetDotProduct (const CVarVector & vector) const inline
Return dot product of two vectors.
Definition at line 374 of file CVarVector.h.
References GetElementsCount().
Referenced by GetLength2().
double imath::CVarVector::GetElement (int index) const inline
Get element at specified index.
Definition at line 279 of file CVarVector.h.
References operator[]().
Referenced by icmm::CVarColor::IsNormalized(), icmm::CVarColor::operator*(), and icmm::CVarColor::operator/().
double & imath::CVarVector::GetElementRef (int index) inline
Get reference to element at specified index.
Definition at line 285 of file CVarVector.h.
References operator[]().
const CVarVector::Elements & imath::CVarVector::GetElements () const inline
Get read-only access to internal element container.
Definition at line 322 of file CVarVector.h.
int imath::CVarVector::GetElementsCount () const inline
Get number of elements.
Definition at line 257 of file CVarVector.h.
Referenced by Clear(), GetDotProduct(), icmm::TColorGradient< GradientFunction >::GetValueAt(), icmm::CVarColor::IsNormalized(), icmm::CVarColor::operator*(), operator*=(), operator+=(), operator-(), operator-=(), icmm::CVarColor::operator/(), operator/=(), operator=(), operator[](), ScaledCumulate(), icmm::TComposedColor< Size >::TComposedColor(), and Translate().
CVarVector::Elements & imath::CVarVector::GetElementsRef () inline
Get access to internal element container.
Definition at line 328 of file CVarVector.h.
double imath::CVarVector::GetElementsSum () const
Get simple sum of all elements.
double imath::CVarVector::GetLength () const inline
Return euclidian length.
Definition at line 395 of file CVarVector.h.
References GetLength2().
double imath::CVarVector::GetLength2 () const inline
Return euclidian length square.
Definition at line 389 of file CVarVector.h.
References GetDotProduct().
Referenced by GetLength(), and IsNull().
void imath::CVarVector::GetMaximal (const CVarVector & vector, CVarVector & result) const
Get vector with maximal elements values.
void imath::CVarVector::GetMinimal (const CVarVector & vector, CVarVector & result) const
Get vector with minimal elements values.
bool imath::CVarVector::GetNormalized (CVarVector & result, double length = 1.0) const
Return normalized vector with the same direction and specified length.
Parameters
length new vector length.
Returns
true, if normalization successed.
CVarVector imath::CVarVector::GetTranslated (const CVarVector & vector) inline
Get translated point.
Definition at line 345 of file CVarVector.h.
void imath::CVarVector::GetTranslated (const CVarVector & vector, CVarVector & result) inline
/overloaded
Definition at line 351 of file CVarVector.h.
bool imath::CVarVector::IsEmpty () const inline
Get true, if the element ist is empty.
Definition at line 251 of file CVarVector.h.
bool imath::CVarVector::IsNull (double tolerance = I_BIG_EPSILON) const inline
Check if this vector is null.
Definition at line 368 of file CVarVector.h.
References GetLength2().
bool imath::CVarVector::Normalize (double length = 1.0)
Normalize vector to specified length.
Parameters
length new vector length.
Returns
true, if normalization successed.
bool imath::CVarVector::operator!= (const CVarVector & vector) const inline
Definition at line 421 of file CVarVector.h.
CVarVector imath::CVarVector::operator* (double scalar) const inline
Definition at line 586 of file CVarVector.h.
CVarVector & imath::CVarVector::operator*= (double scalar) inline
Definition at line 521 of file CVarVector.h.
References GetElementsCount().
Referenced by icmm::CVarColor::operator*=().
CVarVector imath::CVarVector::operator+ (const CVarVector & vector) const inline
Definition at line 566 of file CVarVector.h.
CVarVector & imath::CVarVector::operator+= (const CVarVector & vector) inline
Definition at line 495 of file CVarVector.h.
References GetElementsCount().
CVarVector imath::CVarVector::operator- () const inline
Definition at line 552 of file CVarVector.h.
References GetElementsCount().
CVarVector imath::CVarVector::operator- (const CVarVector & vector) const inline
Definition at line 576 of file CVarVector.h.
CVarVector & imath::CVarVector::operator-= (const CVarVector & vector) inline
Definition at line 508 of file CVarVector.h.
References GetElementsCount().
CVarVector imath::CVarVector::operator/ (double scalar) const inline
Definition at line 596 of file CVarVector.h.
CVarVector & imath::CVarVector::operator/= (double scalar) inline
Definition at line 532 of file CVarVector.h.
References GetElementsCount().
Referenced by icmm::CVarColor::operator/=().
bool imath::CVarVector::operator< (const CVarVector & vector) const inline
Definition at line 427 of file CVarVector.h.
bool imath::CVarVector::operator<= (const CVarVector & vector) const inline
Definition at line 461 of file CVarVector.h.
CVarVector & imath::CVarVector::operator= (const CVarVector & vector) inline
Definition at line 543 of file CVarVector.h.
References GetElementsCount(), SetElementsCount(), and SetElementsFrom().
bool imath::CVarVector::operator== (const CVarVector & vector) const inline
Definition at line 415 of file CVarVector.h.
bool imath::CVarVector::operator> (const CVarVector & vector) const inline
Definition at line 444 of file CVarVector.h.
bool imath::CVarVector::operator>= (const CVarVector & vector) const inline
Definition at line 478 of file CVarVector.h.
double imath::CVarVector::operator[] (int i) const inline
Definition at line 606 of file CVarVector.h.
References GetElementsCount().
Referenced by GetElement(), GetElementRef(), and SetElement().
double & imath::CVarVector::operator[] (int i) inline
Definition at line 615 of file CVarVector.h.
References GetElementsCount().
void imath::CVarVector::Reset () inline
Set size to zero.
Definition at line 297 of file CVarVector.h.
void imath::CVarVector::Reset (int elementsCount, double value) inline
Set number of elements and set all elements to specified value.
Definition at line 312 of file CVarVector.h.
void imath::CVarVector::ScaledCumulate (const CVarVector & vector, double scale) inline
Add second vector scaled by specified factor.
It is equal of Translate(vector * scale) but can be faster implemented.
Definition at line 357 of file CVarVector.h.
References GetElementsCount().
bool imath::CVarVector::Serialize (iser::IArchive & archive)
Serialize this vector to specified archive.
void imath::CVarVector::SetElement (int index, double value) inline
Set element at specified index.
Definition at line 291 of file CVarVector.h.
References operator[]().
Referenced by icmm::CVarColor::operator*(), and icmm::CVarColor::operator/().
bool imath::CVarVector::SetElementsCount (int count, double value = 0) inline
Set number of elements.
Returns
always true, this value is provided for template implementations.
Definition at line 263 of file CVarVector.h.
Referenced by operator=().
void imath::CVarVector::SetElementsFrom (const CVarVector & vector, double expansionValue = 0)
Set elemenents from other vector without resizing.
Parameters
vector source of element values will be copied.
expansionValue if actual vector has more elements than vector, rest will be replaced with this value.
Referenced by operator=().
void imath::CVarVector::Translate (const CVarVector & vector) inline
Translate the point.
Definition at line 334 of file CVarVector.h.
References GetElementsCount().
The documentation for this class was generated from the following file:
Include/imath/CVarVector.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy