istd::CString Class Reference
istd::CString Class Reference
Main concepts and implementations
Standard ACF string definition.
#include <CString.h>
Public Types
enum CompareFlags { CF_CASE_INSENSITIVE = 0x01 }
typedef std::wstring BaseClass
Public Member Functions
CString ()
CString (const wchar_t *str)
CString (const char *str)
CString (const std::string &str)
CString (const std::wstring &str)
CString (const CString &str)
const std::string & ToString () const
This function returns standard 8-bit string.
bool IsEmpty () const
This function returns standard 8-bit string.
bool IsEqual (const CString &str, int compareFlags=0) const
Compare two strings.
void Reset ()
This function makes this string empty.
bool operator== (const CString &str) const
bool operator== (const char *str) const
bool operator== (const wchar_t *str) const
bool operator== (const std::string &str) const
bool operator!= (const char *str) const
bool operator!= (const wchar_t *str) const
bool operator!= (const CString &str) const
bool operator!= (const std::string &str) const
CString operator+ (const CString &str) const
CString & operator= (const char *str)
CString & operator= (const wchar_t *str)
CString & operator= (const CString &str)
CString & operator= (const std::string &str)
CString & operator+= (const CString &str)
CString ToUpper () const
CString ToLower () const
std::vector< CString > Split (const CString &separator, bool caseSensitive=true, bool ignoreEmpty=false)
CString & Replace (const CString &before, const CString &after, bool caseSensitive=true)
bool IsEqualNoCase (const CString &str) const
template<typename NumberType >
NumberType ToNumber ()
Static Public Member Functions
static const CString & GetEmpty ()
template<typename NumberType >
static CString FromNumber (NumberType number)
Protected Member Functions
void Copy (const CString &other)
void ConvertToChar () const
Detailed Description
Standard ACF string definition.
This class is a wrapper for wchar_t data type from the standard C-library.
Definition at line 23 of file CString.h.
Member Typedef Documentation
typedef std::wstring istd::CString::BaseClass
Definition at line 30 of file CString.h.
Member Enumeration Documentation
enum istd::CString::CompareFlags
Enumerator:
CF_CASE_INSENSITIVE
Definition at line 26 of file CString.h.
Constructor & Destructor Documentation
istd::CString::CString ()
istd::CString::CString (const wchar_t * str)
istd::CString::CString (const char * str)
istd::CString::CString (const std::string & str)
istd::CString::CString (const std::wstring & str)
istd::CString::CString (const CString & str)
Member Function Documentation
void istd::CString::ConvertToChar () const [protected]
void istd::CString::Copy (const CString & other) [protected]
template<typename NumberType > CString istd::CString::FromNumber (NumberType number) [static]
Definition at line 137 of file CString.h.
Referenced by iser::TXmlStreamReadArchiveBase< StreamClass >::DecorateMessage(), and iproc::TSupplierCompWrap< SupplierInterface, Product >::EnsureWorkFinished().
static const CString& istd::CString::GetEmpty () [static]
Referenced by icomp::CComponentStaticInfoBase::GetDescription(), and icomp::CComponentStaticInfoBase::GetKeywords().
bool istd::CString::IsEmpty () const [inline]
This function returns standard 8-bit string.
Definition at line 108 of file CString.h.
Referenced by ibase::TFileSerializerComp< ReadArchive, WriteArchive >::IsOperationSupported(), iproc::TFileCachedProducerCompBase< Key, CacheObject >::ProduceLockedObject(), and iproc::TFileCachedProducerCompBase< Key, CacheObject >::PushKeyBack().
bool istd::CString::IsEqual (const CString & str, int compareFlags = 0) const
Compare two strings.
Returns:
true, if this strings are equal.
bool istd::CString::IsEqualNoCase (const CString & str) const [inline]
Definition at line 114 of file CString.h.
References ToUpper().
bool istd::CString::operator!= (const char * str) const
bool istd::CString::operator!= (const wchar_t * str) const
bool istd::CString::operator!= (const CString & str) const
bool istd::CString::operator!= (const std::string & str) const
CString istd::CString::operator+ (const CString & str) const
CString& istd::CString::operator+= (const CString & str)
CString& istd::CString::operator= (const char * str)
CString& istd::CString::operator= (const wchar_t * str)
CString& istd::CString::operator= (const CString & str)
CString& istd::CString::operator= (const std::string & str)
bool istd::CString::operator== (const CString & str) const
bool istd::CString::operator== (const char * str) const
bool istd::CString::operator== (const wchar_t * str) const
bool istd::CString::operator== (const std::string & str) const
CString& istd::CString::Replace (const CString & before, const CString & after, bool caseSensitive = true)
void istd::CString::Reset ()
This function makes this string empty.
std::vector<CString> istd::CString::Split (const CString & separator, bool caseSensitive = true, bool ignoreEmpty = false)
CString istd::CString::ToLower () const
Referenced by ibase::TFileSerializerComp< ReadArchive, WriteArchive >::IsOperationSupported().
template<typename NumberType > NumberType istd::CString::ToNumber ()
Definition at line 123 of file CString.h.
References ToString().
const std::string& istd::CString::ToString () const
This function returns standard 8-bit string.
Referenced by ibase::TFileSerializerComp< ReadArchive, WriteArchive >::CheckInputFilePath(), ibase::TFileSerializerComp< ReadArchive, WriteArchive >::CheckTargetDirectory(), iproc::TFileCachedProducerCompBase< Key, CacheObject >::CleanFileList(), and ToNumber().
CString istd::CString::ToUpper () const
Referenced by IsEqualNoCase().
The documentation for this class was generated from the following file:
Include/istd/CString.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy