iview::TFrameBase< ViewBase > Class Template Reference
iview::TFrameBase< ViewBase > Class Template Reference
#include <TFrameBase.h>
Classes
struct CursorInfo
Public Types
enum FitMode {
FM_RESET, FM_BOTH, FM_HORIZONTAL, FM_VERTICAL,
FM_UNPROP, FM_COVER
}
Control fitting mode, to fit area of interest (AOI) to display.
typedef iview::TFramedViewBase
< ViewBase > ViewImpl
Public Member Functions
TFrameBase (QWidget *parent)
bool IsZoomToFit () const
void SetZoomToFit (bool state=true)
FitMode GetFitMode () const
void SetFitMode (FitMode mode)
bool IsGridVisible () const
void SetGridVisible (bool state=true)
bool IsRulerVisible () const
void SetRulerVisible (bool state=true)
bool IsGridInMm () const
void SetGridInMm (bool state=true)
bool IsButtonsPanelVisible () const
void SetButtonsPanelVisible (bool state=true)
bool IsButtonsPanelVertical () const
void SetButtonsPanelVertical (bool state=true)
bool AreScrollbarsVisible () const
void SetScrollbarsVisible (bool state=true)
bool IsStatusVisible () const
void SetStatusVisible (bool state=true)
bool AreZoomsVisible () const
void SetZoomsVisible (bool state=true)
bool IsZoomToFitVisible () const
void SetZoomToFitVisible (bool state=true)
bool ArePolylineButtonsVisible () const
void SetPolylineButtonsVisible (bool state=true)
bool AreUserModeButtonsVisible () const
void SetUserModeButtonsVisible (bool state=true)
bool IsStatusButtonVisible () const
void SetStatusButtonVisible (bool state=true)
bool IsScrollbarsButtonVisible () const
void SetScrollbarsButtonVisible (bool state=true)
bool IsGridButtonVisible () const
void SetGridButtonVisible (bool state=true)
bool IsRulerButtonVisible () const
void SetRulerButtonVisible (bool state=true)
bool IsMmButtonVisible () const
void SetMmButtonVisible (bool state=true)
bool IsUndoButtonVisible () const
void SetUndoButtonVisible (bool state=true)
bool IsPixelPositionVisible () const
void SetPixelPositionVisible (bool state=true)
bool IsPixelValueVisible () const
void SetPixelValueVisible (bool state=true)
bool IsMmPositionVisible () const
void SetMmPositionVisible (bool state=true)
bool IsBackgroundActive () const
Check if background object is present and active.
void UpdateView ()
virtual const ViewImpl & GetView () const =0
Get access to internal view implementation.
virtual ViewImpl & GetViewRef ()=0
Get access to internal view implementation.
virtual void UpdateEditModeButtons ()=0
Update state of edit mode buttons.
virtual void UpdateButtonsState ()=0
Recalculates enabling flags for buttons.
virtual void UpdateComponentsPosition ()=0
Recalculates position of all components.
virtual void SetStatusText (const istd::CString &message)=0
Display specified text in status window.
virtual void UpdateCursorInfo (const CursorInfo &info)=0
Protected Member Functions
virtual bool OnSelectChange (const iview::IShapeView &view, const istd::CIndex2d &position, const iview::IInteractiveShape &shape, bool state)=0
virtual bool OnMouseButton (const iview::IShapeView &view, const istd::CIndex2d &position, Qt::MouseButton buttonType, bool state, const iview::IInteractiveShape *shapePtr)=0
virtual void OnBoundingBoxChanged ()=0
Detailed Description
template<class ViewBase>
class iview::TFrameBase< ViewBase >
Definition at line 24 of file TFrameBase.h.
Member Typedef Documentation
template<class ViewBase> typedef iview::TFramedViewBase<ViewBase> iview::TFrameBase< ViewBase >::ViewImpl
Definition at line 27 of file TFrameBase.h.
Member Enumeration Documentation
template<class ViewBase> enum iview::TFrameBase::FitMode
Control fitting mode, to fit area of interest (AOI) to display.
Enumerator:
FM_RESET
No fitting, frame use always identity transformation.
FM_BOTH
Scale both axes proportional to display biggest, but full visible AOI.
FM_HORIZONTAL
Only horizontal size of AOI will be consider.
FM_VERTICAL
Only vertical size of AOI will be consider.
FM_UNPROP
Both axes will be scaled separately.
FM_COVER
Scale both axes proportional to display smallest AOI, which fully covers display.
Reimplemented in iview::CConsoleGui.
Definition at line 32 of file TFrameBase.h.
Constructor & Destructor Documentation
template<class ViewBase > iview::TFrameBase< ViewBase >::TFrameBase (QWidget * parent)
Definition at line 223 of file TFrameBase.h.
Member Function Documentation
template<class ViewBase > bool iview::TFrameBase< ViewBase >::ArePolylineButtonsVisible () const [inline]
Definition at line 599 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::AreScrollbarsVisible () const [inline]
Definition at line 569 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::AreUserModeButtonsVisible () const [inline]
Definition at line 606 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::AreZoomsVisible () const [inline]
Definition at line 585 of file TFrameBase.h.
template<class ViewBase > TFrameBase< ViewBase >::FitMode iview::TFrameBase< ViewBase >::GetFitMode () const [inline]
Definition at line 523 of file TFrameBase.h.
template<class ViewBase> virtual const ViewImpl& iview::TFrameBase< ViewBase >::GetView () const [pure virtual]
Get access to internal view implementation.
Implemented in iview::CConsoleGui.
template<class ViewBase> virtual ViewImpl& iview::TFrameBase< ViewBase >::GetViewRef () [pure virtual]
Get access to internal view implementation.
Implemented in iview::CConsoleGui.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsBackgroundActive () const [inline]
Check if background object is present and active.
Definition at line 676 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsButtonsPanelVertical () const [inline]
Definition at line 562 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsButtonsPanelVisible () const [inline]
Definition at line 555 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsGridButtonVisible () const [inline]
Definition at line 627 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsGridInMm () const [inline]
Definition at line 545 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsGridVisible () const [inline]
Definition at line 530 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsMmButtonVisible () const [inline]
Definition at line 641 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsMmPositionVisible () const [inline]
Definition at line 669 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsPixelPositionVisible () const [inline]
Definition at line 655 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsPixelValueVisible () const [inline]
Definition at line 662 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsRulerButtonVisible () const [inline]
Definition at line 634 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsRulerVisible () const [inline]
Definition at line 538 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsScrollbarsButtonVisible () const [inline]
Definition at line 620 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsStatusButtonVisible () const [inline]
Definition at line 613 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsStatusVisible () const [inline]
Definition at line 576 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsUndoButtonVisible () const [inline]
Definition at line 648 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsZoomToFit () const [inline]
Definition at line 516 of file TFrameBase.h.
template<class ViewBase > bool iview::TFrameBase< ViewBase >::IsZoomToFitVisible () const [inline]
Definition at line 592 of file TFrameBase.h.
template<class ViewBase> virtual void iview::TFrameBase< ViewBase >::OnBoundingBoxChanged () [protected, pure virtual]
Implemented in iview::CConsoleGui.
template<class ViewBase> virtual bool iview::TFrameBase< ViewBase >::OnMouseButton (const iview::IShapeView & view, const istd::CIndex2d & position, Qt::MouseButton buttonType, bool state, const iview::IInteractiveShape * shapePtr) [protected, pure virtual]
Implemented in iview::CConsoleGui.
template<class ViewBase> virtual bool iview::TFrameBase< ViewBase >::OnSelectChange (const iview::IShapeView & view, const istd::CIndex2d & position, const iview::IInteractiveShape & shape, bool state) [protected, pure virtual]
Implemented in iview::CConsoleGui.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetButtonsPanelVertical (bool state = true)
Definition at line 308 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetButtonsPanelVisible (bool state = true)
Definition at line 298 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetFitMode (FitMode mode)
Definition at line 251 of file TFrameBase.h.
References iview::TFramedViewBase< ViewBase >::UpdateFitTransform().
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetGridButtonVisible (bool state = true)
Definition at line 402 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetGridInMm (bool state = true)
Definition at line 284 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetGridVisible (bool state = true)
Definition at line 265 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetMmButtonVisible (bool state = true)
Definition at line 422 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetMmPositionVisible (bool state = true)
Definition at line 460 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetPixelPositionVisible (bool state = true)
Definition at line 442 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetPixelValueVisible (bool state = true)
Definition at line 451 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetPolylineButtonsVisible (bool state = true)
Definition at line 362 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetRulerButtonVisible (bool state = true)
Definition at line 412 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetRulerVisible (bool state = true)
Definition at line 273 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetScrollbarsButtonVisible (bool state = true)
Definition at line 392 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetScrollbarsVisible (bool state = true)
Definition at line 318 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetStatusButtonVisible (bool state = true)
Definition at line 382 of file TFrameBase.h.
template<class ViewBase> virtual void iview::TFrameBase< ViewBase >::SetStatusText (const istd::CString & message) [pure virtual]
Display specified text in status window.
Implemented in iview::CConsoleGui.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetStatusVisible (bool state = true)
Definition at line 329 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetUndoButtonVisible (bool state = true)
Definition at line 432 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetUserModeButtonsVisible (bool state = true)
Definition at line 372 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetZoomsVisible (bool state = true)
Definition at line 342 of file TFrameBase.h.
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetZoomToFit (bool state = true)
Definition at line 231 of file TFrameBase.h.
References iview::TFramedViewBase< ViewBase >::UpdateFitTransform().
template<class ViewBase > void iview::TFrameBase< ViewBase >::SetZoomToFitVisible (bool state = true)
Definition at line 352 of file TFrameBase.h.
template<class ViewBase> virtual void iview::TFrameBase< ViewBase >::UpdateButtonsState () [pure virtual]
Recalculates enabling flags for buttons.
Implemented in iview::CConsoleGui.
Referenced by iview::TCalibratedViewBase< ViewBase >::ConnectCalibrationShape().
template<class ViewBase> virtual void iview::TFrameBase< ViewBase >::UpdateComponentsPosition () [pure virtual]
Recalculates position of all components.
Implemented in iview::CConsoleGui.
template<class ViewBase> virtual void iview::TFrameBase< ViewBase >::UpdateCursorInfo (const CursorInfo & info) [pure virtual]
template<class ViewBase> virtual void iview::TFrameBase< ViewBase >::UpdateEditModeButtons () [pure virtual]
Update state of edit mode buttons.
Edit mode buttons controls the mode of interaction with objects. For example for polyline nodes: select, move, insert, remove.
See also:
iview::ISelectable::EditMode
Implemented in iview::CConsoleGui.
template<class ViewBase > void iview::TFrameBase< ViewBase >::UpdateView ()
Definition at line 469 of file TFrameBase.h.
References iview::TFramedViewBase< ViewBase >::UpdateFitTransform().
The documentation for this class was generated from the following file:
Include/iview/TFrameBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy