ACF: imod::CMultiModelObserverBase Class Reference
imod::CMultiModelObserverBase Class Reference
Basic implementation of a multiple model observer.
#include <CMultiModelObserverBase.h>
Public Member Functions
virtual ~CMultiModelObserverBase ()
imod::IModel * GetModelPtr (int modelIndex) const
Get access to connected model with the index index.
int GetModelCount () const
Gets the number of connected models.
virtual bool IsModelAttached (const imod::IModel *modelPtr) const
Check if specified model is attached.
virtual bool OnAttached (imod::IModel *modelPtr)
This call back function will be called, if an observable object is about to be attached.
virtual bool OnDetached (imod::IModel *modelPtr)
This call back function will be called, if an observable object is about to be detached.
virtual void BeforeUpdate (imod::IModel *modelPtr, int updateFlags, istd::IPolymorphic *updateParamsPtr)
This function will be called before update of the observer contents occures.
virtual void AfterUpdate (imod::IModel *modelPtr, int updateFlags, istd::IPolymorphic *updateParamsPtr)
This function will be called after update of the observer contents occures.
Protected Member Functions
void EnsureDetached ()
virtual void OnUpdate (imod::IModel *modelPtr, int updateFlags, istd::IPolymorphic *updateParamsPtr)
Detailed Description
Basic implementation of a multiple model observer.
Definition at line 19 of file CMultiModelObserverBase.h.
Constructor & Destructor Documentation
virtual imod::CMultiModelObserverBase::~CMultiModelObserverBase () [virtual]
Member Function Documentation
virtual void imod::CMultiModelObserverBase::AfterUpdate (imod::IModel * modelPtr, int updateFlags, istd::IPolymorphic * updateParamsPtr) [virtual]
This function will be called after update of the observer contents occures.
Implements imod::IObserver.
virtual void imod::CMultiModelObserverBase::BeforeUpdate (imod::IModel * modelPtr, int updateFlags, istd::IPolymorphic * updateParamsPtr) [virtual]
This function will be called before update of the observer contents occures.
Please note, that in some cases no following AfterUpdate can be called.
Implements imod::IObserver.
void imod::CMultiModelObserverBase::EnsureDetached () [protected]
int imod::CMultiModelObserverBase::GetModelCount () const
Gets the number of connected models.
Referenced by imod::TMultiModelObserverBase< ObjectClass >::GetObjectPtr().
imod::IModel* imod::CMultiModelObserverBase::GetModelPtr (int modelIndex) const
Get access to connected model with the index index.
Referenced by imod::TMultiModelObserverBase< ObjectClass >::GetObjectPtr().
virtual bool imod::CMultiModelObserverBase::IsModelAttached (const imod::IModel * modelPtr) const [virtual]
Check if specified model is attached.
pointer to model object. If this pointer is NULL, any model is meaned.
Returns:
true, if modelPtr is attached yet to this observer, false otherwise.
Implements imod::IObserver.
virtual bool imod::CMultiModelObserverBase::OnAttached (imod::IModel * modelPtr) [virtual]
This call back function will be called, if an observable object is about to be attached.
This function returns a true, if observable object is accepted by the implementation logic of the observer, otherwise the function returns a false.
Implements imod::IObserver.
Reimplemented in imod::TMultiModelObserverBase< ObjectClass >.
Referenced by imod::TMultiModelObserverBase< ObjectClass >::OnAttached().
virtual bool imod::CMultiModelObserverBase::OnDetached (imod::IModel * modelPtr) [virtual]
This call back function will be called, if an observable object is about to be detached.
Implements imod::IObserver.
Reimplemented in imod::TModelDispatcher< NotifyReceiver >, and imod::TModelDispatcher< CDocumentProcessingManagerCompBase >.
Referenced by imod::TModelDispatcher< NotifyReceiver >::OnDetached().
virtual void imod::CMultiModelObserverBase::OnUpdate (imod::IModel * modelPtr, int updateFlags, istd::IPolymorphic * updateParamsPtr) [protected, virtual]
Reimplemented in imod::TModelDispatcher< NotifyReceiver >, and imod::TModelDispatcher< CDocumentProcessingManagerCompBase >.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/imod/CMultiModelObserverBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy