ACF: imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree > Class Template Reference
imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree > Class Template Reference
Spline interpolation function using polynomial 3 degree segments.
#include <TSplineGridFunctionBase.h>
Public Types
typedef
TFulcrumGridFunctionBase
< Argument, Result, Fulcrums > BaseClass
typedef Degree DerivativeDegreeType
Public Member Functions
virtual bool GetValueAt (const Argument &argument, Result &result) const
Get function value for specified argument value.
virtual Result GetValueAt (const Argument &argument) const
Get function value for specified argument value.
Protected Member Functions
void CumulateRecursiveValueAt (const Argument &argument, int dimension, const typename BaseClass::FulcrumSizes &sizes, typename BaseClass::FulcrumIndex &index, DerivativeDegreeType &degree, double cumulationFactor, Result &result) const
Cumulate interpolated value or derivative at specified recursion level.
virtual const
BaseClass::ResultType & GetFulcrumDerivativeAtIndex (const typename BaseClass::FulcrumIndex &index, const DerivativeDegreeType &degree) const =0
Get derivative of specified degree at specified index position.
virtual bool IsDerivativeDegreeSupported (const DerivativeDegreeType &degree) const =0
Check, if this or higher degree derrivatives are supported.
Static Protected Member Functions
static double GetValueKernelAt (double alpha)
static double GetDerivativeKernelAt (double alpha)
Detailed Description
template<class Argument, class Result, class Fulcrums, class Degree>
class imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >
Spline interpolation function using polynomial 3 degree segments.
To reduce number of coefficients only precalculated derrivative values for each fulcrum will be stored.
Parameters:
Argument function argument type.
Result function result type.
Fulcrums array type used to stored fulcrums.
See also:
imath::TFulcrumGridFunctionBase.
Parameters:
Degree type of object storing index of derivative degree. It should implement operator[] to access drivative degree for specified dimension.
Definition at line 25 of file TSplineGridFunctionBase.h.
Member Typedef Documentation
template<class Argument , class Result , class Fulcrums , class Degree > typedef TFulcrumGridFunctionBase<Argument, Result, Fulcrums> imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::BaseClass
Reimplemented from imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >.
Definition at line 28 of file TSplineGridFunctionBase.h.
template<class Argument , class Result , class Fulcrums , class Degree > typedef Degree imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::DerivativeDegreeType
Definition at line 30 of file TSplineGridFunctionBase.h.
Member Function Documentation
template<class Argument , class Result , class Fulcrums , class Degree > void imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::CumulateRecursiveValueAt (const Argument & argument, int dimension, const typename BaseClass::FulcrumSizes & sizes, typename BaseClass::FulcrumIndex & index, DerivativeDegreeType & degree, double cumulationFactor, Result & result) const [inline, protected]
Cumulate interpolated value or derivative at specified recursion level.
Parameters:
argument position, where interpolation should be calculated. The elements with index less of equal dimension indicate non grid components (hard to explain). The other components should be taken from index.
sizes size fulcrum grid.
dimension working dimension and recursion level.
index multidimensional index pointing at cuboid element in fulcrum grid. The elements with index greater dimension indicate asked subspace in grid (hard to explain). For the sake of performance it is internal modified, but original state is reverted before this method returns.
degree derivative degree will be taken. For the sake of performance it is internal modified, but original state is reverted before this method returns.
cumulationFactor scaled factor for cumulation.
result object where values are cumulated.
Definition at line 142 of file TSplineGridFunctionBase.h.
References imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::GetDerivativeKernelAt(), imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::GetDimensionsCount(), imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::GetFulcrumDerivativeAtIndex(), imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::GetLayerPosition(), imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::GetValueKernelAt(), I_ASSERT, I_BIG_EPSILON, and imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::IsDerivativeDegreeSupported().
Referenced by imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::GetValueAt().
template<class Argument , class Result , class Fulcrums , class Degree > double imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::GetDerivativeKernelAt (double alpha) [inline, static, protected]
Definition at line 92 of file TSplineGridFunctionBase.h.
Referenced by imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::CumulateRecursiveValueAt().
template<class Argument , class Result , class Fulcrums , class Degree > virtual const BaseClass::ResultType& imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::GetFulcrumDerivativeAtIndex (const typename BaseClass::FulcrumIndex & index, const DerivativeDegreeType & degree) const [protected, pure virtual]
Get derivative of specified degree at specified index position.
Referenced by imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::CumulateRecursiveValueAt().
template<class Argument , class Result , class Fulcrums , class Degree > Result imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::GetValueAt (const Argument & argument) const [inline, virtual]
Get function value for specified argument value.
This overloaded menthod is provided only for convinence.
Parameters:
argument function argument.
Returns:
function value for specified argument.
Implements imath::TIMathFunction< Argument, Result >.
Definition at line 129 of file TSplineGridFunctionBase.h.
References imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::GetValueAt().
template<class Argument , class Result , class Fulcrums , class Degree > bool imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::GetValueAt (const Argument & argument, Result & result) const [inline, virtual]
Get function value for specified argument value.
Parameters:
argument function argument.
result function value for specified argument.
Returns:
true if result was correctly calculated.
Implements imath::TIMathFunction< Argument, Result >.
Definition at line 104 of file TSplineGridFunctionBase.h.
References imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::CumulateRecursiveValueAt(), istd::TCachedUpdateManagerWrap< iser::ISerializable >::EnsureCacheValid(), imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::FindIndices(), imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::GetDimensionsCount(), and imath::TFulcrumGridFunctionBase< Argument, Result, Fulcrums >::GetGridSize().
Referenced by imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::GetValueAt().
template<class Argument , class Result , class Fulcrums , class Degree > double imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::GetValueKernelAt (double alpha) [inline, static, protected]
Definition at line 85 of file TSplineGridFunctionBase.h.
Referenced by imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::CumulateRecursiveValueAt().
template<class Argument , class Result , class Fulcrums , class Degree > virtual bool imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::IsDerivativeDegreeSupported (const DerivativeDegreeType & degree) const [protected, pure virtual]
Check, if this or higher degree derrivatives are supported.
Referenced by imath::TSplineGridFunctionBase< Argument, Result, Fulcrums, Degree >::CumulateRecursiveValueAt().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/imath/TSplineGridFunctionBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy