ACF: iser::TVersionInfoSerializer< VersionInfo > Class Template Reference
iser::TVersionInfoSerializer< VersionInfo > Class Template Reference
[Persistence concept.]
Generic implementation of the version info serializer.
#include <TVersionInfoSerializer.h>
Static Public Member Functions
static bool ReadVersion (VersionInfo *versionInfoPtr, iser::IArchive &archive)
static bool WriteVersion (const VersionInfo *versionInfoPtr, iser::IArchive &archive)
Static Protected Attributes
static CArchiveTag s_headerTag
static CArchiveTag s_versionInfosTag
static CArchiveTag s_versionInfoTag
static CArchiveTag s_versionIdTag
static CArchiveTag s_versionNumberTag
static CArchiveTag s_versionDescriptionTag
Detailed Description
template<class VersionInfo>
class iser::TVersionInfoSerializer< VersionInfo >
Generic implementation of the version info serializer.
Definition at line 21 of file TVersionInfoSerializer.h.
Member Function Documentation
template<class VersionInfo > bool iser::TVersionInfoSerializer< VersionInfo >::ReadVersion (VersionInfo * versionInfoPtr, iser::IArchive & archive) [inline, static]
Definition at line 40 of file TVersionInfoSerializer.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), iser::IArchive::EndTag(), I_ASSERT, iser::IArchive::IsStoring(), NULL, iser::IArchive::Process(), iser::TVersionInfoSerializer< VersionInfo >::s_headerTag, iser::TVersionInfoSerializer< VersionInfo >::s_versionDescriptionTag, iser::TVersionInfoSerializer< VersionInfo >::s_versionIdTag, iser::TVersionInfoSerializer< VersionInfo >::s_versionInfosTag, iser::TVersionInfoSerializer< VersionInfo >::s_versionInfoTag, and iser::TVersionInfoSerializer< VersionInfo >::s_versionNumberTag.
template<class VersionInfo > bool iser::TVersionInfoSerializer< VersionInfo >::WriteVersion (const VersionInfo * versionInfoPtr, iser::IArchive & archive) [inline, static]
Definition at line 94 of file TVersionInfoSerializer.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), iser::IArchive::EndTag(), I_ASSERT, I_IF_DEBUG, iser::IArchive::IsStoring(), NULL, iser::IArchive::Process(), iser::TVersionInfoSerializer< VersionInfo >::s_headerTag, iser::TVersionInfoSerializer< VersionInfo >::s_versionDescriptionTag, iser::TVersionInfoSerializer< VersionInfo >::s_versionIdTag, iser::TVersionInfoSerializer< VersionInfo >::s_versionInfosTag, iser::TVersionInfoSerializer< VersionInfo >::s_versionInfoTag, and iser::TVersionInfoSerializer< VersionInfo >::s_versionNumberTag.
Member Data Documentation
template<class VersionInfo > CArchiveTag iser::TVersionInfoSerializer< VersionInfo >::s_headerTag [inline, static, protected]
Definition at line 28 of file TVersionInfoSerializer.h.
Referenced by iser::TVersionInfoSerializer< VersionInfo >::ReadVersion(), and iser::TVersionInfoSerializer< VersionInfo >::WriteVersion().
template<class VersionInfo > CArchiveTag iser::TVersionInfoSerializer< VersionInfo >::s_versionDescriptionTag [inline, static, protected]
Definition at line 33 of file TVersionInfoSerializer.h.
Referenced by iser::TVersionInfoSerializer< VersionInfo >::ReadVersion(), and iser::TVersionInfoSerializer< VersionInfo >::WriteVersion().
template<class VersionInfo > CArchiveTag iser::TVersionInfoSerializer< VersionInfo >::s_versionIdTag [inline, static, protected]
Definition at line 31 of file TVersionInfoSerializer.h.
Referenced by iser::TVersionInfoSerializer< VersionInfo >::ReadVersion(), and iser::TVersionInfoSerializer< VersionInfo >::WriteVersion().
template<class VersionInfo > CArchiveTag iser::TVersionInfoSerializer< VersionInfo >::s_versionInfosTag [inline, static, protected]
Definition at line 29 of file TVersionInfoSerializer.h.
Referenced by iser::TVersionInfoSerializer< VersionInfo >::ReadVersion(), and iser::TVersionInfoSerializer< VersionInfo >::WriteVersion().
template<class VersionInfo > CArchiveTag iser::TVersionInfoSerializer< VersionInfo >::s_versionInfoTag [inline, static, protected]
Definition at line 30 of file TVersionInfoSerializer.h.
Referenced by iser::TVersionInfoSerializer< VersionInfo >::ReadVersion(), and iser::TVersionInfoSerializer< VersionInfo >::WriteVersion().
template<class VersionInfo > CArchiveTag iser::TVersionInfoSerializer< VersionInfo >::s_versionNumberTag [inline, static, protected]
Definition at line 32 of file TVersionInfoSerializer.h.
Referenced by iser::TVersionInfoSerializer< VersionInfo >::ReadVersion(), and iser::TVersionInfoSerializer< VersionInfo >::WriteVersion().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iser/TVersionInfoSerializer.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy