ACF: icomp::TComponentWrap< Component > Class Template Reference
icomp::TComponentWrap< Component > Class Template Reference
Wrapper of end component implementation used to correct control of component life-cycle.
#include <TComponentWrap.h>
Public Types
typedef Component BaseClass
Public Member Functions
TComponentWrap ()
virtual ~TComponentWrap ()
virtual void SetComponentContext (const IComponentContext *contextPtr, const IComponent *parentPtr, bool isParentOwner)
Detailed Description
template<class Component>
class icomp::TComponentWrap< Component >
Wrapper of end component implementation used to correct control of component life-cycle.
Definition at line 17 of file TComponentWrap.h.
Member Typedef Documentation
template<class Component> typedef Component icomp::TComponentWrap< Component >::BaseClass
Reimplemented in icomp::TSimComponentsFactory< Base >, icomp::TSimComponentWrap< Base >, icomp::TSimComponentWrap< Base >, icomp::TSimComponentWrap< iqt::CPackagesLoaderComp >, and icomp::TSimComponentWrap< XmlFileSerializer >.
Definition at line 20 of file TComponentWrap.h.
Constructor & Destructor Documentation
template<class Component > icomp::TComponentWrap< Component >::TComponentWrap () [inline]
Definition at line 36 of file TComponentWrap.h.
template<class Component > icomp::TComponentWrap< Component >::~TComponentWrap () [inline, virtual]
Definition at line 42 of file TComponentWrap.h.
References NULL, icomp::IComponent::OnSubcomponentDeleted(), and icomp::TComponentWrap< Component >::SetComponentContext().
Member Function Documentation
template<class Component > void icomp::TComponentWrap< Component >::SetComponentContext (const IComponentContext * contextPtr, const IComponent * parentPtr, bool isParentOwner) [inline, virtual]
Definition at line 56 of file TComponentWrap.h.
References NULL.
Referenced by icomp::TComponentWrap< Component >::~TComponentWrap().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/icomp/TComponentWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy