ACF: iimg::IBitmap Class Reference
iimg::IBitmap Class Reference
Definition of single plane bitmap.
#include <IBitmap.h>
Public Member Functions
virtual bool CreateBitmap (const istd::CIndex2d &size, int pixelBitsCount=8, int componentsCount=1)=0
Create bitmap with specified size, number of bits per pixel and components number per pixel.
virtual bool CreateBitmap (const istd::CIndex2d &size, void *dataPtr, bool releaseFlag, int linesDifference=0, int pixelBitsCount=8, int componentsCount=1)=0
Create bitmap using external image buffer.
virtual int GetLineBytesCount () const =0
Number of bytes per single line.
virtual int GetLinesDifference () const =0
Get address difference between next and previos line.
virtual int GetComponentBitsCount (int componentIndex=0) const =0
Get number of bits per single pixel component.
virtual int GetPixelBitsCount () const =0
Get total number of bits per single pixel.
virtual const void * GetLinePtr (int positionY) const =0
Get pointer to buffer for single line.
virtual void * GetLinePtr (int positionY)=0
Get pointer to buffer for single line.
Detailed Description
Definition of single plane bitmap.
Definition at line 15 of file IBitmap.h.
Member Function Documentation
virtual bool iimg::IBitmap::CreateBitmap (const istd::CIndex2d & size, void * dataPtr, bool releaseFlag, int linesDifference = 0, int pixelBitsCount = 8, int componentsCount = 1) [pure virtual]
Create bitmap using external image buffer.
Parameters:
size bitmap size.
dataPtr pointer to external image buffer.
releaseFlag if its true, external buffer will be managed (removed) by this object.
linesDifference address difference between next and previos line. If it equals 0, the value will be taken from size and number of bits per pixel.
pixelBitsCount number of bits per single pixel.
componentsCount number of components per single pixel.
Returns:
true if bitmap was created.
Implemented in iimg::CGeneralBitmap, and iqt::CBitmap.
virtual bool iimg::IBitmap::CreateBitmap (const istd::CIndex2d & size, int pixelBitsCount = 8, int componentsCount = 1) [pure virtual]
Create bitmap with specified size, number of bits per pixel and components number per pixel.
Parameters:
size bitmap size.
pixelBitsCount number of bits per single pixel.
componentsCount number of components per single pixel.
Returns:
true if bitmap was created.
Implemented in iimg::CGeneralBitmap, and iqt::CBitmap.
virtual int iimg::IBitmap::GetComponentBitsCount (int componentIndex = 0) const [pure virtual]
Get number of bits per single pixel component.
Implemented in iimg::CBitmapBase.
virtual int iimg::IBitmap::GetLineBytesCount () const [pure virtual]
Number of bytes per single line.
Implemented in iimg::CBitmapBase.
virtual void* iimg::IBitmap::GetLinePtr (int positionY) [pure virtual]
Get pointer to buffer for single line.
Parameters:
positionY position Y. It must be smaller than bitmap size Y component.
Implemented in iimg::CGeneralBitmap, and iqt::CBitmap.
virtual const void* iimg::IBitmap::GetLinePtr (int positionY) const [pure virtual]
Get pointer to buffer for single line.
Parameters:
positionY position Y. It must be smaller than bitmap size Y component.
Implemented in iimg::CGeneralBitmap, and iqt::CBitmap.
Referenced by iimg::TBitmapIterator< PixelType >::TBitmapIterator(), and iimg::TBitmapIterator2d< PixelType >::TBitmapIterator2d().
virtual int iimg::IBitmap::GetLinesDifference () const [pure virtual]
Get address difference between next and previos line.
Implemented in iimg::CGeneralBitmap, and iqt::CBitmap.
Referenced by iimg::TBitmapIterator< PixelType >::TBitmapIterator(), and iimg::TBitmapIterator2d< PixelType >::TBitmapIterator2d().
virtual int iimg::IBitmap::GetPixelBitsCount () const [pure virtual]
Get total number of bits per single pixel.
Implemented in iimg::CGeneralBitmap, and iqt::CBitmap.
Referenced by iimg::TBitmapIterator< PixelType >::TBitmapIterator().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iimg/IBitmap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy