ACF: iqtgui::TDesignerGuiCompBase< UI, WidgetType > Class Template Reference
iqtgui::TDesignerGuiCompBase< UI, WidgetType > Class Template Reference
Base class for all Qt GUI componentes, which use the Qt designer's UI.
#include <TDesignerGuiCompBase.h>
Public Types
typedef TGuiComponentBase
< WidgetType > BaseClass
Public Member Functions
virtual QWidget * InitWidgetToParent (QWidget *parentPtr)
Create slave widget object.
Protected Member Functions
virtual void OnGuiRetranslate ()
Called from widget event filter when GUI should be retranslated.
Detailed Description
template<class UI, class WidgetType = QWidget>
class iqtgui::TDesignerGuiCompBase< UI, WidgetType >
Base class for all Qt GUI componentes, which use the Qt designer's UI.
Definition at line 21 of file TDesignerGuiCompBase.h.
Member Typedef Documentation
template<class UI, class WidgetType = QWidget> typedef TGuiComponentBase<WidgetType> iqtgui::TDesignerGuiCompBase< UI, WidgetType >::BaseClass
Reimplemented from iqtgui::TGuiComponentBase< WidgetType >.
Reimplemented in icmpstr::CAttributeEditorComp, icmpstr::CPackageOverviewComp, icmpstr::CQuickHelpViewerComp, icmpstr::CRegistryPropEditorComp, iqt2d::CAnnulusParamsGuiComp, iqt2d::CAnnulusSegmentParamsGuiComp, iqt2d::CCircleParamsGuiComp, iqt2d::CLine2dParamsGuiComp, iqt2d::CQuadrangleParamsGuiComp, iqt2d::CRectangleParamsGuiComp, iqt2d::CSceneConnectorGuiComp, iqt2d::CSceneControllerGuiComp, iqt2d::CSceneProviderGuiComp, iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >, iqtgui::CAboutWidgetGuiComp, iqtgui::CFilePersistenceGuiComp, iqtgui::CFileSystemExplorerGuiComp, iqtgui::CImagePropertiesFrameComp, iqtgui::CImagePropertyGuiComp, iqtgui::CLogGuiComp, iqtgui::CLoginGuiComp, iqtgui::CObjectPreviewGuiComp, iqtgui::CSplashScreenGuiComp, iqtgui::TDesignerGuiObserverCompBase< UI, Model, WidgetType >, iqtmm::CPlaybackControllerGuiComp, iqtmm::CVideoPlayerGuiComp, iqtprm::CComposedParamsSetGuiComp, iqtprm::CFileNameParamGuiComp, iqtprm::CParamsManagerGuiComp, iqtprm::CSelectableGuiComp, iqtprm::CSelectableParamsSetGuiComp, iqtprm::CSelectionParamGuiComp, iqtprm::CSelectionParamIndexGuiComp, iqtprm::CVariableParamGuiComp, iqtproc::CProcessorControlGuiComp, iqtproc::CProgressManagerGuiComp, iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui::CQuadrangleParamsGuiComp, i2d::CQuadrangle > >, iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui::CCircleParamsGuiComp, i2d::CCircle > >, iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui::CAnnulusParamsGuiComp, i2d::CAnnulus > >, iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui::CLine2dParamsGuiComp, i2d::CLine2d > >, iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui, ShapeModel > >, iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui::CRectangleParamsGuiComp, i2d::CRectangle > >, iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui::CAnnulusSegmentParamsGuiComp, i2d::CAnnulusSegment > >, iqt2d::TShapeParamsGuiCompBase< Ui::CLine2dParamsGuiComp, iqt2d::CLine2dShape, i2d::CLine2d >, iqt2d::TShapeParamsGuiCompBase< Ui::CCircleParamsGuiComp, iqt2d::CCircleShape, i2d::CCircle >, iqt2d::TShapeParamsGuiCompBase< Ui::CRectangleParamsGuiComp, iqt2d::CRectangleShape, i2d::CRectangle >, iqt2d::TShapeParamsGuiCompBase< Ui::CQuadrangleParamsGuiComp, iqt2d::CQuadrangleShape, i2d::CQuadrangle >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusSegmentParamsGuiComp, iqt2d::CAnnulusSegmentShape, i2d::CAnnulusSegment >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusParamsGuiComp, iqt2d::CAnnulusShape, i2d::CAnnulus >, iqtgui::TDesignerGuiObserverCompBase< Ui::CRectangleParamsGuiComp, i2d::CRectangle >, iqtgui::TDesignerGuiObserverCompBase< Ui::CPackageOverviewComp, IElementSelectionInfo >, iqtgui::TDesignerGuiObserverCompBase< Ui::CAnnulusSegmentParamsGuiComp, i2d::CAnnulusSegment >, iqtgui::TDesignerGuiObserverCompBase< Ui::CFileSystemExplorerGuiComp, iprm::IFileNameParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::CObjectPreviewGuiComp, iprm::IFileNameParam >, iqtgui::TDesignerGuiObserverCompBase< Ui, ShapeModel >, iqtgui::TDesignerGuiObserverCompBase< Ui::CComposedParamsSetGuiComp, iprm::IParamsSet >, iqtgui::TDesignerGuiObserverCompBase< Ui::CPlaybackControllerGuiComp, imm::IVideoController >, iqtgui::TDesignerGuiObserverCompBase< Ui::CLogGuiComp, ibase::IMessageContainer >, iqtgui::TDesignerGuiObserverCompBase< Ui::CFileNameParamGuiComp, iprm::IFileNameParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::CImagePropertiesFrameComp, iimg::IBitmap >, iqtgui::TDesignerGuiObserverCompBase< Ui::CSelectionParamIndexGuiComp, iprm::ISelectionParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::CVariableParamGuiComp, iprm::IVariableParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::CSelectableGuiComp, iprm::ISelectionParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::CRegistryPropEditorComp, icomp::IRegistry >, iqtgui::TDesignerGuiObserverCompBase< Ui::CAnnulusParamsGuiComp, i2d::CAnnulus >, iqtgui::TDesignerGuiObserverCompBase< Ui::CCircleParamsGuiComp, i2d::CCircle >, iqtgui::TDesignerGuiObserverCompBase< Ui::CAttributeEditorComp, IElementSelectionInfo >, iqtgui::TDesignerGuiObserverCompBase< Ui::CLine2dParamsGuiComp, i2d::CLine2d >, iqtgui::TDesignerGuiObserverCompBase< Ui::CSelectionParamGuiComp, iprm::ISelectionParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::CImagePropertyGuiComp, iimg::IBitmap >, iqtgui::TDesignerGuiObserverCompBase< Ui::CQuadrangleParamsGuiComp, i2d::CQuadrangle >, and iqtgui::TDesignerGuiObserverCompBase< Ui::CParamsManagerGuiComp, iprm::IParamsManager >.
Definition at line 24 of file TDesignerGuiCompBase.h.
Member Function Documentation
template<class UI , class WidgetType > QWidget * iqtgui::TDesignerGuiCompBase< UI, WidgetType >::InitWidgetToParent (QWidget * parentPtr) [inline, virtual]
Create slave widget object.
Reimplemented from iqtgui::TGuiComponentBase< WidgetType >.
Definition at line 40 of file TDesignerGuiCompBase.h.
References I_ASSERT, iqtgui::TGuiComponentBase< WidgetType >::InitWidgetToParent(), and iqtgui::CGuiComponentBase::IsGuiCreated().
template<class UI , class WidgetType > void iqtgui::TDesignerGuiCompBase< UI, WidgetType >::OnGuiRetranslate () [inline, protected, virtual]
Called from widget event filter when GUI should be retranslated.
Reimplemented from iqtgui::CGuiComponentBase.
Reimplemented in icmpstr::CPackageOverviewComp, iqtgui::CAboutWidgetGuiComp, and iqtgui::CSplashScreenGuiComp.
Definition at line 57 of file TDesignerGuiCompBase.h.
References iqtgui::CGuiComponentBase::GetWidget(), NULL, and iqtgui::CGuiComponentBase::OnGuiRetranslate().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iqtgui/TDesignerGuiCompBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy