ACF: istd::CIdManipBase Class Reference
istd::CIdManipBase Class Reference
#include <CIdManipBase.h>
Static Public Member Functions
static bool SplitId (const std::string &complexId, std::string &baseId, std::string &subId)
Split component ID into separated ID's.
static std::string JoinId (const std::string &baseId, const std::string &subId)
Join base component ID and sub ID into composed component ID.
Detailed Description
Definition at line 13 of file CIdManipBase.h.
Member Function Documentation
static std::string istd::CIdManipBase::JoinId (const std::string & baseId, const std::string & subId) [static]
Join base component ID and sub ID into composed component ID.
static bool istd::CIdManipBase::SplitId (const std::string & complexId, std::string & baseId, std::string & subId) [static]
Split component ID into separated ID's.
Referenced by icomp::TMultiFactoryMember< Interface >::CreateComponent(), icomp::TFactoryMember< Interface >::CreateComponent(), icomp::TReferenceMember< Interface >::EnsureInitialized(), and icomp::TMultiReferenceMember< Interface >::EnsureInitialized().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/istd/CIdManipBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy