ACF: icomp::TMultiAttributeMember< Attribute > Class Template Reference
icomp::TMultiAttributeMember< Attribute > Class Template Reference
Pointer to component attribute.
#include <TMultiAttributeMember.h>
Public Types
typedef Attribute AttributeType
typedef void InterfaceType
Public Member Functions
TMultiAttributeMember ()
bool Init (const IComponent *ownerPtr, const IRealAttributeStaticInfo &staticInfo, const IComponent **definitionComponentPtr=NULL)
bool IsValid () const
Check if this attribute is valid.
int GetCount () const
Get number of attributes.
const Attribute::ValueType & operator[] (int index) const
Access to object pointed by internal pointer.
Detailed Description
template<typename Attribute>
class icomp::TMultiAttributeMember< Attribute >
Pointer to component attribute.
Definition at line 18 of file TMultiAttributeMember.h.
Member Typedef Documentation
template<typename Attribute> typedef Attribute icomp::TMultiAttributeMember< Attribute >::AttributeType
Definition at line 21 of file TMultiAttributeMember.h.
template<typename Attribute> typedef void icomp::TMultiAttributeMember< Attribute >::InterfaceType
Reimplemented in icomp::TMultiFactoryMember< Interface >, and icomp::TMultiReferenceMember< Interface >.
Definition at line 22 of file TMultiAttributeMember.h.
Constructor & Destructor Documentation
template<typename Attribute > icomp::TMultiAttributeMember< Attribute >::TMultiAttributeMember () [inline]
Definition at line 53 of file TMultiAttributeMember.h.
Member Function Documentation
template<typename Attribute > int icomp::TMultiAttributeMember< Attribute >::GetCount () const [inline]
Get number of attributes.
Definition at line 107 of file TMultiAttributeMember.h.
References NULL.
Referenced by icomp::TMultiAttributeMember< Attribute >::operator[]().
template<typename Attribute > bool icomp::TMultiAttributeMember< Attribute >::Init (const IComponent * ownerPtr, const IRealAttributeStaticInfo & staticInfo, const IComponent ** definitionComponentPtr = NULL) [inline]
Definition at line 60 of file TMultiAttributeMember.h.
References icomp::IComponentContext::GetAttribute(), icomp::IRealAttributeStaticInfo::GetAttributeId(), icomp::IComponent::GetComponentContext(), icomp::IComponent::GetParentComponent(), I_ASSERT, and NULL.
template<typename Attribute > bool icomp::TMultiAttributeMember< Attribute >::IsValid () const [inline]
Check if this attribute is valid.
Reimplemented in icomp::TMultiFactoryMember< Interface >, and icomp::TMultiReferenceMember< Interface >.
Definition at line 100 of file TMultiAttributeMember.h.
References NULL.
template<typename Attribute > const Attribute::ValueType & icomp::TMultiAttributeMember< Attribute >::operator[] (int index) const [inline]
Access to object pointed by internal pointer.
Reimplemented in icomp::TMultiReferenceMember< Interface >.
Definition at line 119 of file TMultiAttributeMember.h.
References icomp::TMultiAttributeMember< Attribute >::GetCount(), I_ASSERT, and NULL.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/icomp/TMultiAttributeMember.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy