iview::CSelectableLayerBase Class Reference
iview::CSelectableLayerBase Class Reference
#include <CSelectableLayerBase.h>
Public Types
typedef TLayerBaseEx
< ISelectableLayer > BaseClass
Public Member Functions
CSelectableLayerBase ()
virtual ~CSelectableLayerBase ()
void CalcBoundingBox (i2d::CRect &result) const
virtual bool ConnectInteractiveShape (IInteractiveShape *shapePtr)
Connect active shape object.
virtual int GetUnselectedShapesCount () const
Get number of unselected shapes.
virtual void DrawFocusedShape (QPainter &drawContext)
Draw only focused shape.
virtual void BeginDrag (const i2d::CVector2d &reference)
Set reference position for dragging for all selected shapes.
virtual void SetDragPosition (const i2d::CVector2d &position)
Set dragging position for all selected shapes.
virtual void EndDrag ()
Called after dragging process.
virtual bool OnMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag)
Called, when mouse button was pushed down or up.
virtual bool OnFocusedMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag)
Called, when this layer has focus, and mouse button was pushed down or up on this object.
virtual bool OnFocusedMouseMove (istd::CIndex2d position)
Called, when this layer has focus, and mouse was moved.
virtual TouchState IsTouched (istd::CIndex2d position, IInteractiveShape **shapePtrPtr=NULL) const
Check, if any shape is touched.
virtual int GetSelectedShapesCount () const
Get count of selected shapes.
virtual void InsertSelectedShapes (SelectedShapes &result) const
Get set of selected shapes.
virtual void DeselectAllShapes ()
Set all shapes to be deselected.
virtual int GetKeysState () const
Get state of system keys.
virtual int GetEditMode () const
Get actual edit mode.
virtual void OnShapeFocused (IInteractiveShape *shapePtr)
Called when shape get focus.
virtual void OnShapeDefocused (IInteractiveShape *shapePtr)
Called when shape loose focus.
virtual void OnShapeSelected (IInteractiveShape &shape, bool state=true)
It is called after change shape selection state.
virtual bool IsShapeConnected (IShape *shapePtr)
Check, if the shape is connected to the layer.
virtual bool ConnectShape (IShape *shapePtr)
Connect shape object to view.
virtual int GetShapesCount () const
Get count of all shapes on this layer.
virtual void UpdateAllShapes (int changeFlag)
Send update to all shapes after view changes.
virtual void DisconnectAllShapes ()
Disconnect all shapes from this layer.
virtual void DrawShapes (QPainter &drawContext)
Draw all shapes using specified draw context.
virtual void OnChangeShape (IShape *shapePtr)
Invalidate a shape.
virtual void DisconnectShape (IShape *shapePtr)
Disconnect shape object from view.
Protected Attributes
ShapeMap m_activeShapes
ShapeMap m_inactiveShapes
IInteractiveShape * m_focusedShapePtr
Detailed Description
Definition at line 14 of file CSelectableLayerBase.h.
Member Typedef Documentation
typedef TLayerBaseEx<ISelectableLayer> iview::CSelectableLayerBase::BaseClass
Reimplemented from iview::TLayerBaseEx< ISelectableLayer >.
Definition at line 17 of file CSelectableLayerBase.h.
Constructor & Destructor Documentation
iview::CSelectableLayerBase::CSelectableLayerBase ()
virtual iview::CSelectableLayerBase::~CSelectableLayerBase () [virtual]
Member Function Documentation
virtual void iview::CSelectableLayerBase::BeginDrag (const i2d::CVector2d & reference) [virtual]
Set reference position for dragging for all selected shapes.
Implements iview::ISelectableLayer.
void iview::CSelectableLayerBase::CalcBoundingBox (i2d::CRect & result) const [virtual]
Implements iview::TLayerBaseEx< ISelectableLayer >.
virtual bool iview::CSelectableLayerBase::ConnectInteractiveShape (IInteractiveShape * shapePtr) [virtual]
Connect active shape object.
Implements iview::ISelectableLayer.
virtual bool iview::CSelectableLayerBase::ConnectShape (IShape * shapePtr) [virtual]
Connect shape object to view.
Parameters:
shape a shape object.
active if true, shape will be active, if false it will be only visible.
Returns:
true, if it was possible to connect this shape.
Implements iview::ILayer.
virtual void iview::CSelectableLayerBase::DeselectAllShapes () [virtual]
Set all shapes to be deselected.
Implements iview::ISelectable.
virtual void iview::CSelectableLayerBase::DisconnectAllShapes () [virtual]
Disconnect all shapes from this layer.
Implements iview::ILayer.
virtual void iview::CSelectableLayerBase::DisconnectShape (IShape * shapePtr) [virtual]
Disconnect shape object from view.
This shape had to be connected using ConnectShape.
Returns:
true, if it was possible to disconnect this shape.
Implements iview::IShapeObserver.
virtual void iview::CSelectableLayerBase::DrawFocusedShape (QPainter & drawContext) [virtual]
Draw only focused shape.
Implements iview::ISelectableLayer.
virtual void iview::CSelectableLayerBase::DrawShapes (QPainter & drawContext) [virtual]
Draw all shapes using specified draw context.
Implements iview::ILayer.
virtual void iview::CSelectableLayerBase::EndDrag () [virtual]
Called after dragging process.
Implements iview::ISelectableLayer.
int iview::CSelectableLayerBase::GetEditMode () const [inline, virtual]
Get actual edit mode.
Implements iview::ISelectable.
Definition at line 80 of file CSelectableLayerBase.h.
References iview::ISelectable::GetEditMode(), iview::TLayerBase< ISelectableLayer, IShapeView >::GetViewPtr(), I_ASSERT, and NULL.
int iview::CSelectableLayerBase::GetKeysState () const [inline, virtual]
Get state of system keys.
Implements iview::ISelectable.
Definition at line 71 of file CSelectableLayerBase.h.
References iview::ISelectable::GetKeysState(), iview::TLayerBase< ISelectableLayer, IShapeView >::GetViewPtr(), I_ASSERT, and NULL.
virtual int iview::CSelectableLayerBase::GetSelectedShapesCount () const [virtual]
Get count of selected shapes.
Implements iview::ISelectable.
virtual int iview::CSelectableLayerBase::GetShapesCount () const [virtual]
Get count of all shapes on this layer.
Implements iview::ILayer.
virtual int iview::CSelectableLayerBase::GetUnselectedShapesCount () const [virtual]
Get number of unselected shapes.
Implements iview::ISelectableLayer.
virtual void iview::CSelectableLayerBase::InsertSelectedShapes (SelectedShapes & result) const [virtual]
Get set of selected shapes.
Implements iview::ISelectable.
virtual bool iview::CSelectableLayerBase::IsShapeConnected (IShape * shapePtr) [virtual]
Check, if the shape is connected to the layer.
Implements iview::ILayer.
virtual TouchState iview::CSelectableLayerBase::IsTouched (istd::CIndex2d position, IInteractiveShape ** shapePtrPtr = NULL) const [virtual]
Check, if any shape is touched.
When shape is touched, it return also pointer to this shape.
Parameters:
shapePtrPtr pointer to shape pointer will be filled if shape is found. It can be equal NULL.
Returns:
touch state for the shape, or iview::IInteractiveShape::TS_NONE, when nothing found.
Implements iview::ISelectableLayer.
virtual void iview::CSelectableLayerBase::OnChangeShape (IShape * shapePtr) [virtual]
Invalidate a shape.
When you call Update, all invalidated shapes will be repainted.
Returns:
true, if it was possible to invalidate this shape.
Implements iview::IShapeObserver.
virtual bool iview::CSelectableLayerBase::OnFocusedMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag) [virtual]
Called, when this layer has focus, and mouse button was pushed down or up on this object.
Returns:
true, if this event was consumed.
Implements iview::ISelectableLayer.
virtual bool iview::CSelectableLayerBase::OnFocusedMouseMove (istd::CIndex2d position) [virtual]
Called, when this layer has focus, and mouse was moved.
Returns:
true, if this event was consumed.
Implements iview::ISelectableLayer.
virtual bool iview::CSelectableLayerBase::OnMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag) [virtual]
Called, when mouse button was pushed down or up.
Returns:
true, if this event was consumed.
Implements iview::ISelectableLayer.
virtual void iview::CSelectableLayerBase::OnShapeDefocused (IInteractiveShape * shapePtr) [virtual]
Called when shape loose focus.
Implements iview::ISelectable.
virtual void iview::CSelectableLayerBase::OnShapeFocused (IInteractiveShape * shapePtr) [virtual]
Called when shape get focus.
Implements iview::ISelectable.
virtual void iview::CSelectableLayerBase::OnShapeSelected (IInteractiveShape & shape, bool state = true) [virtual]
It is called after change shape selection state.
Implements iview::ISelectable.
virtual void iview::CSelectableLayerBase::SetDragPosition (const i2d::CVector2d & position) [virtual]
Set dragging position for all selected shapes.
Implements iview::ISelectableLayer.
virtual void iview::CSelectableLayerBase::UpdateAllShapes (int changeFlag) [virtual]
Send update to all shapes after view changes.
Implements iview::ILayer.
Member Data Documentation
ShapeMap iview::CSelectableLayerBase::m_activeShapes [protected]
Definition at line 60 of file CSelectableLayerBase.h.
IInteractiveShape* iview::CSelectableLayerBase::m_focusedShapePtr [protected]
Definition at line 63 of file CSelectableLayerBase.h.
ShapeMap iview::CSelectableLayerBase::m_inactiveShapes [protected]
Definition at line 61 of file CSelectableLayerBase.h.
The documentation for this class was generated from the following file:
Include/iview/CSelectableLayerBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy