imod::IModel Class Reference
imod::IModel Class Reference
Model/Observer concept
Common interface for model objects, that supports Model/Observer design pattern.
#include <IModel.h>
Public Member Functions
virtual bool AttachObserver (IObserver *observerPtr)=0
Attaches model object to observer observerPtr.
virtual void DetachObserver (IObserver *observerPtr)=0
Detaches model object from observer observerPtr.
virtual void DetachAllObservers ()=0
Detaches all attached observers.
virtual bool IsAttached (const IObserver *observerPtr) const =0
Returns true if observer observer is attached to this model object.
Detailed Description
Common interface for model objects, that supports Model/Observer design pattern.
See also:
IObserver
Definition at line 24 of file IModel.h.
Member Function Documentation
virtual bool imod::IModel::AttachObserver (IObserver * observerPtr) [pure virtual]
Attaches model object to observer observerPtr.
Warning:
Please note, that double call of this function for the same observer will cause an assertion.
Implemented in imod::CModelBase, and imod::CModelProxy.
Referenced by iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::CreateShapes(), and iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::OnAttached().
virtual void imod::IModel::DetachAllObservers () [pure virtual]
Detaches all attached observers.
Implemented in imod::CModelBase, and imod::CModelProxy.
virtual void imod::IModel::DetachObserver (IObserver * observerPtr) [pure virtual]
Detaches model object from observer observerPtr.
Warning:
Please note, that call of this function for the observer which is not attached to the observer observer will cause an assertion. To prevent this, you can use the isAttached() function.
Implemented in imod::CModelBase, and imod::CModelProxy.
Referenced by iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::OnDetached().
virtual bool imod::IModel::IsAttached (const IObserver * observerPtr) const [pure virtual]
Returns true if observer observer is attached to this model object.
Implemented in imod::CModelBase, and imod::CModelProxy.
The documentation for this class was generated from the following file:
Include/imod/IModel.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy