imod::TModelDispatcherWrap< Base > Class Template Reference
imod::TModelDispatcherWrap< Base > Class Template Reference
Generic implementation of a data model changes notifier.
#include <TModelDispatcherWrap.h>
Classes
class ModelObserver
Public Types
typedef Base BaseClass
Public Member Functions
TModelDispatcherWrap ()
~TModelDispatcherWrap ()
bool RegisterModel (imod::IModel *modelPtr, int modelId=0, int relevantFlags=0)
Register the data model to be observed.
void UnregisterModel (int modelId=0)
Unregister the data model object.
void UnregisterAllModels ()
Unregister all observed data objects.
template<class Object >
Object * GetObjectPtr (int modelId) const
Get concrete object instance of the obsered model.
virtual void OnModelChanged (int modelId, int changeFlags, istd::IPolymorphic *updateParamsPtr)=0
Detailed Description
template<class Base>
class imod::TModelDispatcherWrap< Base >
Generic implementation of a data model changes notifier.
You can register several data models objects that you want to observe with RegisterModel method. You will get a notification event on each change in the observed data model via OnModelChanged method call of your notification consumer.
Note:
Notification consumer class must implement the method void OnModelChanged(int modelId, int changeFlags, istd::IPolymorphic* updateParamsPtr) to support the notification callback.
Definition at line 26 of file TModelDispatcherWrap.h.
Member Typedef Documentation
template<class Base> typedef Base imod::TModelDispatcherWrap< Base >::BaseClass
Reimplemented in iqtproc::CDocumentProcessingManagerCompBase, iqtproc::CDocumentProcessingManagerComp, and iqtproc::CDocumentProcessingCommandComp.
Definition at line 29 of file TModelDispatcherWrap.h.
Constructor & Destructor Documentation
template<class Base > imod::TModelDispatcherWrap< Base >::TModelDispatcherWrap ()
Definition at line 98 of file TModelDispatcherWrap.h.
template<class Base > imod::TModelDispatcherWrap< Base >::~TModelDispatcherWrap ()
Definition at line 105 of file TModelDispatcherWrap.h.
Member Function Documentation
template<class Base > template<class Object > Object * imod::TModelDispatcherWrap< Base >::GetObjectPtr (int modelId) const
Get concrete object instance of the obsered model.
Definition at line 164 of file TModelDispatcherWrap.h.
References NULL.
template<class Base> virtual void imod::TModelDispatcherWrap< Base >::OnModelChanged (int modelId, int changeFlags, istd::IPolymorphic * updateParamsPtr) [pure virtual]
Implemented in iqtproc::CDocumentProcessingManagerCompBase.
template<class Base > bool imod::TModelDispatcherWrap< Base >::RegisterModel (imod::IModel * modelPtr, int modelId = 0, int relevantFlags = 0)
Register the data model to be observed.
If model registration was successfull, the function returns true.
Parameters:
modelPtr Pointer to the data model object, which should be observed.
modelId Logical model ID for possible event filtering in the notification callback.
relefantFlags The notification will only be triggered if the value of relevantFlags matches the model change flags.
Definition at line 112 of file TModelDispatcherWrap.h.
References imod::IModel::AttachObserver().
template<class Base > void imod::TModelDispatcherWrap< Base >::UnregisterAllModels ()
Unregister all observed data objects.
Definition at line 146 of file TModelDispatcherWrap.h.
References imod::IModel::DetachObserver().
template<class Base > void imod::TModelDispatcherWrap< Base >::UnregisterModel (int modelId = 0)
Unregister the data model object.
Parameters:
modelId object ID used at the object registration.
See also:
RegisterModel
Definition at line 129 of file TModelDispatcherWrap.h.
References imod::IModel::DetachObserver().
The documentation for this class was generated from the following file:
Include/imod/TModelDispatcherWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy