iqtgui::CSimpleMainWindowGuiComp Class Reference
iqtgui::CSimpleMainWindowGuiComp Class Reference
#include <CSimpleMainWindowGuiComp.h>
Public Types
enum GroupId { GI_SETTINGS = 0x400 }
typedef
iqtgui::TRestorableGuiWrap
< iqtgui::TGuiComponentBase
< QMainWindow > > BaseClass
Public Member Functions
I_ASSIGN_TO (m_workspaceCompPtr, m_workspaceCommandsCompPtr, true)
I_ASSIGN_TO (m_mainWindowComponentsCompPtr, m_mainWindowCommandsCompPtr, false)
CSimpleMainWindowGuiComp ()
virtual void OnTryClose (bool *ignoredPtr=NULL)
Called on trying to close application.
Protected Slots
void OnShowToolbars ()
void OnSettings ()
void OnAbout ()
Protected Member Functions
virtual void UpdateMenuActions ()
virtual void SetupMainWindowComponents (QMainWindow &mainWindow)
virtual void AddMainComponent (iqtgui::IMainWindowComponent *componentPtr)
virtual void RemoveMainComponent (iqtgui::IMainWindowComponent *componentPtr)
virtual void CreateMenuBar ()
virtual void CreateDefaultToolBar ()
virtual int SetupToolbar (const iqtgui::CHierarchicalCommand &command, QToolBar &result, int prevGroupId=ibase::ICommand::GI_NONE) const
virtual void SetToolBarsVisible (bool isVisible=true)
virtual void SetupMenu ()
virtual void UpdateFixedCommands (iqtgui::CHierarchicalCommand &fixedCommands)
virtual void UpdateViewCommands (iqtgui::CHierarchicalCommand &viewCommand)
virtual void UpdateToolsCommands (iqtgui::CHierarchicalCommand &toolsCommand)
virtual void UpdateHelpCommands (iqtgui::CHierarchicalCommand &helpCommand)
virtual void UpdateMenuActions (iqtgui::CHierarchicalCommand &menuCommands)
virtual void OnRestoreSettings (const QSettings &settings)
virtual void OnSaveSettings (QSettings &settings) const
virtual void OnGuiCreated ()
Called just after GUI is initialized.
virtual void OnGuiDestroyed ()
Called just before GUI is released.
virtual void OnRetranslate ()
Called when non-GUI elements (like commands) should be retranslated.
template<class MenuType >
void CreateMenu (const iqtgui::CHierarchicalCommand &command, MenuType &result) const
Protected Attributes
CommandsObserver m_commandsObserver
Detailed Description
Definition at line 30 of file CSimpleMainWindowGuiComp.h.
Member Typedef Documentation
typedef iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase<QMainWindow> > iqtgui::CSimpleMainWindowGuiComp::BaseClass
Reimplemented from iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QMainWindow > >.
Reimplemented in iqtdoc::CMainWindowGuiComp.
Definition at line 37 of file CSimpleMainWindowGuiComp.h.
Member Enumeration Documentation
enum iqtgui::CSimpleMainWindowGuiComp::GroupId
Enumerator:
GI_SETTINGS
Reimplemented in iqtdoc::CMainWindowGuiComp.
Definition at line 54 of file CSimpleMainWindowGuiComp.h.
Constructor & Destructor Documentation
iqtgui::CSimpleMainWindowGuiComp::CSimpleMainWindowGuiComp ()
Member Function Documentation
virtual void iqtgui::CSimpleMainWindowGuiComp::AddMainComponent (iqtgui::IMainWindowComponent * componentPtr) [protected, virtual]
virtual void iqtgui::CSimpleMainWindowGuiComp::CreateDefaultToolBar () [protected, virtual]
template<class MenuType > void iqtgui::CSimpleMainWindowGuiComp::CreateMenu (const iqtgui::CHierarchicalCommand & command, MenuType & result) const [protected]
Definition at line 161 of file CSimpleMainWindowGuiComp.h.
References ibase::ICommand::CF_EXCLUSIVE, ibase::ICommand::CF_GLOBAL_MENU, iqtgui::CHierarchicalCommand::GetChild(), iqtgui::CHierarchicalCommand::GetChildsCount(), iqtgui::CHierarchicalCommand::GetGroupId(), iprm::CNameParam::GetName(), iqtgui::CHierarchicalCommand::GetStaticFlags(), ibase::ICommand::GI_NONE, and NULL.
virtual void iqtgui::CSimpleMainWindowGuiComp::CreateMenuBar () [protected, virtual]
iqtgui::CSimpleMainWindowGuiComp::I_ASSIGN_TO (m_workspaceCompPtr , m_workspaceCommandsCompPtr , true)
iqtgui::CSimpleMainWindowGuiComp::I_ASSIGN_TO (m_mainWindowComponentsCompPtr , m_mainWindowCommandsCompPtr , false)
void iqtgui::CSimpleMainWindowGuiComp::OnAbout () [protected, slot]
virtual void iqtgui::CSimpleMainWindowGuiComp::OnGuiCreated () [protected, virtual]
Called just after GUI is initialized.
Reimplemented from iqtgui::CGuiComponentBase.
Reimplemented in iqtdoc::CMainWindowGuiComp.
virtual void iqtgui::CSimpleMainWindowGuiComp::OnGuiDestroyed () [protected, virtual]
Called just before GUI is released.
Reimplemented from iqtgui::CGuiComponentBase.
Reimplemented in iqtdoc::CMainWindowGuiComp.
virtual void iqtgui::CSimpleMainWindowGuiComp::OnRestoreSettings (const QSettings & settings) [protected, virtual]
Implements iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QMainWindow > >.
virtual void iqtgui::CSimpleMainWindowGuiComp::OnRetranslate () [protected, virtual]
Called when non-GUI elements (like commands) should be retranslated.
Reimplemented from iqtgui::CGuiComponentBase.
Reimplemented in iqtdoc::CMainWindowGuiComp.
virtual void iqtgui::CSimpleMainWindowGuiComp::OnSaveSettings (QSettings & settings) const [protected, virtual]
Implements iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QMainWindow > >.
void iqtgui::CSimpleMainWindowGuiComp::OnSettings () [protected, slot]
void iqtgui::CSimpleMainWindowGuiComp::OnShowToolbars () [protected, slot]
virtual void iqtgui::CSimpleMainWindowGuiComp::OnTryClose (bool * ignoredPtr = NULL) [virtual]
Called on trying to close application.
Parameters:
ignoredPtr if it is not NULL, ignoring of close is allowed. In this case implementation should set pointed value to true.
Reimplemented from iqtgui::CGuiComponentBase.
virtual void iqtgui::CSimpleMainWindowGuiComp::RemoveMainComponent (iqtgui::IMainWindowComponent * componentPtr) [protected, virtual]
virtual void iqtgui::CSimpleMainWindowGuiComp::SetToolBarsVisible (bool isVisible = true) [protected, virtual]
virtual void iqtgui::CSimpleMainWindowGuiComp::SetupMainWindowComponents (QMainWindow & mainWindow) [protected, virtual]
virtual void iqtgui::CSimpleMainWindowGuiComp::SetupMenu () [protected, virtual]
virtual int iqtgui::CSimpleMainWindowGuiComp::SetupToolbar (const iqtgui::CHierarchicalCommand & command, QToolBar & result, int prevGroupId = ibase::ICommand::GI_NONE) const [protected, virtual]
virtual void iqtgui::CSimpleMainWindowGuiComp::UpdateFixedCommands (iqtgui::CHierarchicalCommand & fixedCommands) [protected, virtual]
Reimplemented in iqtdoc::CMainWindowGuiComp.
virtual void iqtgui::CSimpleMainWindowGuiComp::UpdateHelpCommands (iqtgui::CHierarchicalCommand & helpCommand) [protected, virtual]
virtual void iqtgui::CSimpleMainWindowGuiComp::UpdateMenuActions () [protected, virtual]
virtual void iqtgui::CSimpleMainWindowGuiComp::UpdateMenuActions (iqtgui::CHierarchicalCommand & menuCommands) [protected, virtual]
Reimplemented in iqtdoc::CMainWindowGuiComp.
virtual void iqtgui::CSimpleMainWindowGuiComp::UpdateToolsCommands (iqtgui::CHierarchicalCommand & toolsCommand) [protected, virtual]
Reimplemented in iqtdoc::CMainWindowGuiComp.
virtual void iqtgui::CSimpleMainWindowGuiComp::UpdateViewCommands (iqtgui::CHierarchicalCommand & viewCommand) [protected, virtual]
Reimplemented in iqtdoc::CMainWindowGuiComp.
Member Data Documentation
CommandsObserver iqtgui::CSimpleMainWindowGuiComp::m_commandsObserver [protected]
Definition at line 118 of file CSimpleMainWindowGuiComp.h.
The documentation for this class was generated from the following file:
Include/iqtgui/CSimpleMainWindowGuiComp.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy