ACF: iqt2d::ISceneProvider Class Reference
iqt2d::ISceneProvider Class Reference
Interface for GUI objects managing scene.
#include <ISceneProvider.h>
Public Types
enum SceneFlags { SF_FIXED_SIZE = 1, SF_ALIGNED = 2 }
Public Member Functions
virtual int GetSceneId () const =0
Get ID indentifing this scene.
virtual QGraphicsScene * GetScene () const =0
Called when items should be removed from specified scene.
virtual bool GetSceneAlignment (double &distance) const =0
Get parameters of grid alignment.
virtual int GetSceneFlags () const =0
Get scene's paremeter info.
Detailed Description
Interface for GUI objects managing scene.
Definition at line 22 of file ISceneProvider.h.
Member Enumeration Documentation
enum iqt2d::ISceneProvider::SceneFlags
Enumerator:
SF_FIXED_SIZE Scene has a fixed size and cannot be resized by user.
SF_ALIGNED Scene has a grid alignment.
See also:
GetSceneAlignment
Definition at line 26 of file ISceneProvider.h.
Member Function Documentation
virtual QGraphicsScene* iqt2d::ISceneProvider::GetScene () const [pure virtual]
Called when items should be removed from specified scene.
Implemented in iqt2d::CSceneProviderGuiComp.
Referenced by iqt2d::TSceneExtenderCompBase< Base >::AddItemsToScene(), and iqt2d::TSceneExtenderCompBase< Base >::RemoveItemsFromScene().
virtual bool iqt2d::ISceneProvider::GetSceneAlignment (double & distance) const [pure virtual]
Get parameters of grid alignment.
Parameters:
distance distance between nearest alignment positions.
Returns:
true if grid alignment is enabled.
See also:
SceneFlags
Implemented in iqt2d::CSceneProviderGuiComp.
virtual int iqt2d::ISceneProvider::GetSceneFlags () const [pure virtual]
Get scene's paremeter info.
See also:
SceneFlags
Implemented in iqt2d::CSceneProviderGuiComp.
virtual int iqt2d::ISceneProvider::GetSceneId () const [pure virtual]
Get ID indentifing this scene.
Typically this ID is 0 for first scene, 1 for the second etc.
Implemented in iqt2d::CSceneProviderGuiComp.
Referenced by iqt2d::TSceneExtenderCompBase< Base >::AddItemsToScene().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iqt2d/ISceneProvider.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy