i2d::CRect Class Reference
i2d::CRect Class Reference
Simple rectangle with integer bounds.
#include <CRect.h>
Public Member Functions
CRect ()
CRect (const CRect &rect)
CRect (int left, int top, int right, int bottom)
CRect (const istd::CIndex2d &leftTop, const istd::CIndex2d &rightBottom)
CRect (const istd::CIndex2d &leftTop, const ibase::CSize &size)
CRect (const i2d::CRectangle &rect)
CRect (const ibase::CSize &size)
i2d::CRectangle GetRectangle () const
istd::CIndex2d GetLeftTop () const
void SetLeftTop (istd::CIndex2d position)
istd::CIndex2d GetRightTop () const
void SetRightTop (istd::CIndex2d position)
istd::CIndex2d GetLeftBottom () const
void SetLeftBottom (istd::CIndex2d position)
istd::CIndex2d GetRightBottom () const
void SetRightBottom (istd::CIndex2d position)
int GetLeft () const
void SetLeft (int left)
int GetTop () const
void SetTop (int top)
int GetRight () const
void SetRight (int right)
int GetBottom () const
void SetBottom (int bottom)
int GetWidth () const
int GetHeight () const
const istd::CIntRange & GetHorizontalRange () const
istd::CIntRange & GetHorizontalRangeRef ()
void SetHorizontalRange (const istd::CIntRange &range)
const istd::CIntRange & GetVerticalRange () const
istd::CIntRange & GetVerticalRangeRef ()
void SetVerticalRange (const istd::CIntRange &range)
istd::CIndex2d GetCenter () const
bool IsValid () const
Check if rectangle is valid.
bool IsEmpty () const
Check if rectangle is empty.
bool IsValidNonEmpty () const
Return true if the rectangle is valid and it is not empty.
bool IsNull () const
Check if all parameters are 0.
ibase::CSize GetSize () const
Get size of rectangle.
bool IsInside (const istd::CIndex2d &point) const
Check if specified point lies inside.
bool IsInside (const CRect &rect) const
Check if specified rectangle lies inside.
bool IsOutside (const CRect &rect) const
Check if specified rectangle lies fully outside.
void Reset ()
Set all members to 0.
void Union (const CRect &rect)
Calculate union of this and second rectangle and stores result in this object.
void GetUnion (const CRect &rect, CRect &result) const
Get union of two rectangles.
CRect GetUnion (const CRect &rect) const
Get union of two rectangles.
void Union (istd::CIndex2d point)
Calculate union of this rectangle and point.
CRect GetUnion (istd::CIndex2d point) const
Get union of this rectangle and point.
void Expand (const CRect &rect)
Expand rectangle using second rectangle.
CRect GetExpanded (const CRect &rect) const
Get expanded rectangle.
void Intersection (const CRect &rect)
Calculate intersection of this and second rectangle and stores result in this object.
CRect GetIntersection (const CRect &rect) const
Get intersection of two rectangles.
void Translate (istd::CIndex2d point)
Move rectangle.
CRect GetTranslated (istd::CIndex2d point) const
Get moved rectangle.
CRect & operator= (const CRect &rect)
bool operator== (const CRect &rect) const
bool operator!= (const CRect &rect) const
Static Public Member Functions
static const i2d::CRect & GetEmpty ()
Detailed Description
Simple rectangle with integer bounds.
Definition at line 21 of file CRect.h.
Constructor & Destructor Documentation
i2d::CRect::CRect () [inline]
Definition at line 188 of file CRect.h.
References istd::TRange< int >::GetInvalid().
i2d::CRect::CRect (const CRect & rect) [inline]
Definition at line 198 of file CRect.h.
i2d::CRect::CRect (int left, int top, int right, int bottom) [inline]
Definition at line 204 of file CRect.h.
References I_ASSERT, and IsValid().
i2d::CRect::CRect (const istd::CIndex2d & leftTop, const istd::CIndex2d & rightBottom) [inline]
Definition at line 213 of file CRect.h.
References istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), I_ASSERT, and IsValid().
i2d::CRect::CRect (const istd::CIndex2d & leftTop, const ibase::CSize & size) [inline]
Definition at line 222 of file CRect.h.
References istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), I_ASSERT, and IsValid().
i2d::CRect::CRect (const i2d::CRectangle & rect) [inline]
Definition at line 231 of file CRect.h.
References i2d::CRectangle::GetBottom(), i2d::CRectangle::GetLeft(), i2d::CRectangle::GetRight(), i2d::CRectangle::GetTop(), I_ASSERT, and IsValid().
i2d::CRect::CRect (const ibase::CSize & size) [inline, explicit]
Definition at line 240 of file CRect.h.
References istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), I_ASSERT, and IsValid().
Member Function Documentation
void i2d::CRect::Expand (const CRect & rect) [inline]
Expand rectangle using second rectangle.
Expanded rectangle is easy sum of coordinates of both rectangles.
Definition at line 561 of file CRect.h.
References istd::TRange< ValueType >::Expand(), I_ASSERT, and IsValid().
Referenced by GetExpanded().
int i2d::CRect::GetBottom () const [inline]
Definition at line 346 of file CRect.h.
References istd::TRange< ValueType >::GetMaxValue().
Referenced by Union().
istd::CIndex2d i2d::CRect::GetCenter () const [inline]
Definition at line 406 of file CRect.h.
References istd::TRange< ValueType >::GetLength(), and istd::TRange< ValueType >::GetMinValue().
const i2d::CRect & i2d::CRect::GetEmpty () [inline, static]
Definition at line 655 of file CRect.h.
CRect i2d::CRect::GetExpanded (const CRect & rect) const [inline]
Get expanded rectangle.
Expanded rectangle is easy sum of coordinates of both rectangles.
Definition at line 571 of file CRect.h.
References Expand(), I_ASSERT, and IsValid().
int i2d::CRect::GetHeight () const [inline]
Definition at line 364 of file CRect.h.
References istd::TRange< ValueType >::GetLength().
const istd::CIntRange & i2d::CRect::GetHorizontalRange () const [inline]
Definition at line 370 of file CRect.h.
istd::CIntRange & i2d::CRect::GetHorizontalRangeRef () [inline]
Definition at line 376 of file CRect.h.
CRect i2d::CRect::GetIntersection (const CRect & rect) const [inline]
Get intersection of two rectangles.
Definition at line 598 of file CRect.h.
References I_ASSERT, Intersection(), and IsValid().
int i2d::CRect::GetLeft () const [inline]
Definition at line 311 of file CRect.h.
References istd::TRange< ValueType >::GetMinValue().
Referenced by Union().
istd::CIndex2d i2d::CRect::GetLeftBottom () const [inline]
Definition at line 285 of file CRect.h.
References istd::TRange< ValueType >::GetMaxValue(), and istd::TRange< ValueType >::GetMinValue().
istd::CIndex2d i2d::CRect::GetLeftTop () const [inline]
Definition at line 259 of file CRect.h.
References istd::TRange< ValueType >::GetMinValue().
i2d::CRectangle i2d::CRect::GetRectangle () const [inline]
Definition at line 249 of file CRect.h.
References istd::TRange< ValueType >::GetLength(), and istd::TRange< ValueType >::GetMinValue().
int i2d::CRect::GetRight () const [inline]
Definition at line 334 of file CRect.h.
References istd::TRange< ValueType >::GetMaxValue().
Referenced by Union().
istd::CIndex2d i2d::CRect::GetRightBottom () const [inline]
Definition at line 298 of file CRect.h.
References istd::TRange< ValueType >::GetMaxValue().
istd::CIndex2d i2d::CRect::GetRightTop () const [inline]
Definition at line 272 of file CRect.h.
References istd::TRange< ValueType >::GetMaxValue(), and istd::TRange< ValueType >::GetMinValue().
ibase::CSize i2d::CRect::GetSize () const [inline]
Get size of rectangle.
Definition at line 438 of file CRect.h.
References istd::TRange< ValueType >::GetLength().
int i2d::CRect::GetTop () const [inline]
Definition at line 322 of file CRect.h.
References istd::TRange< ValueType >::GetMinValue().
Referenced by Union().
CRect i2d::CRect::GetTranslated (istd::CIndex2d point) const [inline]
Get moved rectangle.
Definition at line 620 of file CRect.h.
References I_ASSERT, IsValid(), and Translate().
void i2d::CRect::GetUnion (const CRect & rect, CRect & result) const [inline]
Get union of two rectangles.
Definition at line 502 of file CRect.h.
References I_ASSERT, IsEmpty(), IsValid(), Reset(), and istd::TRange< ValueType >::Unite().
Referenced by GetUnion().
CRect i2d::CRect::GetUnion (const CRect & rect) const [inline]
Get union of two rectangles.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 522 of file CRect.h.
References GetUnion(), I_ASSERT, and IsValid().
CRect i2d::CRect::GetUnion (istd::CIndex2d point) const [inline]
Get union of this rectangle and point.
Definition at line 549 of file CRect.h.
References I_ASSERT, IsValid(), and Union().
const istd::CIntRange & i2d::CRect::GetVerticalRange () const [inline]
Definition at line 388 of file CRect.h.
istd::CIntRange & i2d::CRect::GetVerticalRangeRef () [inline]
Definition at line 394 of file CRect.h.
int i2d::CRect::GetWidth () const [inline]
Definition at line 358 of file CRect.h.
References istd::TRange< ValueType >::GetLength().
void i2d::CRect::Intersection (const CRect & rect) [inline]
Calculate intersection of this and second rectangle and stores result in this object.
Definition at line 584 of file CRect.h.
References I_ASSERT, istd::TRange< ValueType >::Intersection(), istd::TRange< ValueType >::IsValid(), IsValid(), and Reset().
Referenced by GetIntersection().
bool i2d::CRect::IsEmpty () const [inline]
Check if rectangle is empty.
Definition at line 420 of file CRect.h.
References istd::TRange< ValueType >::IsEmpty().
Referenced by GetUnion(), IsInside(), IsOutside(), and Union().
bool i2d::CRect::IsInside (const istd::CIndex2d & point) const [inline]
Check if specified point lies inside.
Definition at line 444 of file CRect.h.
References istd::TRange< ValueType >::Contains(), istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), I_ASSERT, and IsValid().
bool i2d::CRect::IsInside (const CRect & rect) const [inline]
Check if specified rectangle lies inside.
Definition at line 452 of file CRect.h.
References istd::TRange< ValueType >::Contains(), I_ASSERT, IsEmpty(), and IsValid().
bool i2d::CRect::IsNull () const [inline]
Check if all parameters are 0.
Definition at line 432 of file CRect.h.
References istd::TRange< int >::GetNull().
bool i2d::CRect::IsOutside (const CRect & rect) const [inline]
Check if specified rectangle lies fully outside.
Definition at line 466 of file CRect.h.
References I_ASSERT, IsEmpty(), istd::TRange< ValueType >::IsOutsideOf(), and IsValid().
bool i2d::CRect::IsValid () const [inline]
Check if rectangle is valid.
Definition at line 414 of file CRect.h.
References istd::TRange< ValueType >::IsValid().
Referenced by CRect(), Expand(), GetExpanded(), GetIntersection(), GetTranslated(), GetUnion(), Intersection(), IsInside(), IsOutside(), and Union().
bool i2d::CRect::IsValidNonEmpty () const [inline]
Return true if the rectangle is valid and it is not empty.
Definition at line 426 of file CRect.h.
References istd::TRange< ValueType >::IsValidNonEmpty().
bool i2d::CRect::operator!= (const CRect & rect) const [inline]
Definition at line 647 of file CRect.h.
References operator==().
CRect & i2d::CRect::operator= (const CRect & rect) [inline]
Definition at line 632 of file CRect.h.
bool i2d::CRect::operator== (const CRect & rect) const [inline]
Definition at line 641 of file CRect.h.
Referenced by operator!=().
void i2d::CRect::Reset () [inline]
Set all members to 0.
Definition at line 480 of file CRect.h.
References istd::TRange< ValueType >::Reset().
Referenced by GetUnion(), Intersection(), and iview::CViewBase::ResetInvalidatedBox().
void i2d::CRect::SetBottom (int bottom) [inline]
Definition at line 352 of file CRect.h.
References istd::TRange< ValueType >::SetMaxValue().
void i2d::CRect::SetHorizontalRange (const istd::CIntRange & range) [inline]
Definition at line 382 of file CRect.h.
void i2d::CRect::SetLeft (int left) [inline]
Definition at line 316 of file CRect.h.
References istd::TRange< ValueType >::SetMinValue().
void i2d::CRect::SetLeftBottom (istd::CIndex2d position) [inline]
Definition at line 291 of file CRect.h.
References istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), istd::TRange< ValueType >::SetMaxValue(), and istd::TRange< ValueType >::SetMinValue().
void i2d::CRect::SetLeftTop (istd::CIndex2d position) [inline]
Definition at line 265 of file CRect.h.
References istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), and istd::TRange< ValueType >::SetMinValue().
void i2d::CRect::SetRight (int right) [inline]
Definition at line 340 of file CRect.h.
References istd::TRange< ValueType >::SetMaxValue().
void i2d::CRect::SetRightBottom (istd::CIndex2d position) [inline]
Definition at line 304 of file CRect.h.
References istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), and istd::TRange< ValueType >::SetMaxValue().
void i2d::CRect::SetRightTop (istd::CIndex2d position) [inline]
Definition at line 278 of file CRect.h.
References istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), istd::TRange< ValueType >::SetMaxValue(), and istd::TRange< ValueType >::SetMinValue().
void i2d::CRect::SetTop (int top) [inline]
Definition at line 328 of file CRect.h.
References istd::TRange< ValueType >::SetMinValue().
void i2d::CRect::SetVerticalRange (const istd::CIntRange & range) [inline]
Definition at line 400 of file CRect.h.
void i2d::CRect::Translate (istd::CIndex2d point) [inline]
Move rectangle.
Definition at line 611 of file CRect.h.
References istd::TRange< ValueType >::GetMaxValue(), istd::TRange< ValueType >::GetMinValue(), istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), istd::TRange< ValueType >::SetMaxValue(), and istd::TRange< ValueType >::SetMinValue().
Referenced by GetTranslated().
void i2d::CRect::Union (const CRect & rect) [inline]
Calculate union of this and second rectangle and stores result in this object.
Definition at line 487 of file CRect.h.
References I_ASSERT, IsEmpty(), IsValid(), and istd::TRange< ValueType >::Unite().
Referenced by GetUnion(), and iview::CViewBase::InvalidateBox().
void i2d::CRect::Union (istd::CIndex2d point) [inline]
Calculate union of this rectangle and point.
Result is stored in this object.
Definition at line 535 of file CRect.h.
References GetBottom(), GetLeft(), GetRight(), GetTop(), istd::CIndex2d::GetX(), istd::CIndex2d::GetY(), I_ASSERT, and IsValid().
The documentation for this class was generated from the following file:
Include/i2d/CRect.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy