icomp::TComponentCloneWrap< BaseClass > Class Template Reference
icomp::TComponentCloneWrap< BaseClass > Class Template Reference
#include <TComponentCloneWrap.h>
Public Member Functions
virtual istd::IChangeable * CloneMe (istd::IChangeable::CompatibilityMode mode=BaseClass::CM_WITHOUT_REFS) const
Additional Inherited Members
Static Protected Member Functions inherited from icomp::CInterfaceManipBase
template<class Interface >
static Interface * ExtractInterface (IComponent *componentPtr, const QByteArray &subId="")
Extract interface from component.
Static Protected Member Functions inherited from istd::CIdManipBase
static bool SplitId (const QByteArray &complexId, QByteArray &baseId, QByteArray &subId)
Split component ID into separated ID's.
static QByteArray JoinId (const QByteArray &baseId, const QByteArray &subId)
Join base component ID and sub ID into composed component ID.
Detailed Description
template<class BaseClass>
class icomp::TComponentCloneWrap< BaseClass >
Definition at line 16 of file TComponentCloneWrap.h.
Member Function Documentation
template<class BaseClass > istd::IChangeable * icomp::TComponentCloneWrap< BaseClass >::CloneMe (istd::IChangeable::CompatibilityMode mode = BaseClass::CM_WITHOUT_REFS) const virtual
Definition at line 27 of file TComponentCloneWrap.h.
References icomp::ICompositeComponent::CreateSubcomponent(), icomp::CComponentContext::GetContextId(), istd::TPointerBase< Type >::IsValid(), NULL, istd::TDelPtr< Type, Accessor >::PopPtr(), and istd::TDelPtr< Type, Accessor >::SetCastedOrRemove().
The documentation for this class was generated from the following file:
Include/icomp/TComponentCloneWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy