ibase::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx Class Reference
ibase::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx Class Reference
#include <TFileSerializerComp.h>
Public Types
typedef ReadArchive BaseClass
Public Member Functions
ReadArchiveEx (const QString &filePath, const TFileSerializerComp *loggerPtr)
Protected Member Functions
virtual bool IsLogConsumed (const istd::IInformation::InformationCategory *, const int *flagsPtr=NULL) const
virtual bool SendLogMessage (istd::IInformation::InformationCategory category, int id, const QString &message, const QString &messageSource, int flags=0) const
Detailed Description
template<class ReadArchive, class WriteArchive>
class ibase::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx
Definition at line 61 of file TFileSerializerComp.h.
Member Typedef Documentation
template<class ReadArchive, class WriteArchive> typedef ReadArchive ibase::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx::BaseClass
Definition at line 64 of file TFileSerializerComp.h.
Constructor & Destructor Documentation
template<class ReadArchive, class WriteArchive> ibase::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx::ReadArchiveEx (const QString & filePath, const TFileSerializerComp * loggerPtr) [inline]
Definition at line 66 of file TFileSerializerComp.h.
Member Function Documentation
template<class ReadArchive, class WriteArchive> virtual bool ibase::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx::IsLogConsumed (const istd::IInformation::InformationCategory * , const int * flagsPtr = NULL) const [inline, protected, virtual]
Definition at line 74 of file TFileSerializerComp.h.
References istd::IInformation::IC_INFO, ibase::TLoggerWrap< Base >::IsLogConsumed(), and NULL.
template<class ReadArchive, class WriteArchive> virtual bool ibase::TFileSerializerComp< ReadArchive, WriteArchive >::ReadArchiveEx::SendLogMessage (istd::IInformation::InformationCategory category, int id, const QString & message, const QString & messageSource, int flags = 0) const [inline, protected, virtual]
Definition at line 82 of file TFileSerializerComp.h.
References ibase::TLoggerCompWrap< CFileTypeInfoComp >::DecorateMessage(), istd::IInformation::IC_INFO, NULL, and ibase::TLoggerWrap< Base >::SendLogMessage().
The documentation for this class was generated from the following file:
Include/ibase/TFileSerializerComp.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy