ACF: istd::TVarArray< Element >::Iterator Class Reference
istd::TVarArray< Element >::Iterator Class Reference
#include <TVarArray.h>
Public Types
typedef CVarIndex BaseClass
Public Member Functions
Iterator (const Iterator &iterator)
Element & operator* ()
const Element & operator* () const
Element * operator-> ()
const Element * operator-> () const
Iterator & operator++ ()
Iterator operator++ (int)
Iterator & operator-- ()
Iterator operator-- (int)
Iterator & operator= (const Iterator &iterator)
bool operator== (const Iterator &iterator) const
bool operator!= (const Iterator &iterator) const
Protected Member Functions
Iterator (TVarArray *arrayPtr)
Friends
class TVarArray< Element >
Detailed Description
template<class Element>
class istd::TVarArray< Element >::Iterator
Definition at line 28 of file TVarArray.h.
Member Typedef Documentation
template<class Element > typedef CVarIndex istd::TVarArray< Element >::Iterator::BaseClass
Definition at line 31 of file TVarArray.h.
Constructor & Destructor Documentation
template<class Element > istd::TVarArray< Element >::Iterator::Iterator (const Iterator & iterator) [inline]
Definition at line 347 of file TVarArray.h.
template<class Element > istd::TVarArray< Element >::Iterator::Iterator (TVarArray * arrayPtr) [inline, protected]
Definition at line 471 of file TVarArray.h.
References istd::TVarArray< Element >::GetSizes(), istd::CVarIndex::IsInside(), and NULL.
Member Function Documentation
template<class Element > bool istd::TVarArray< Element >::Iterator::operator!= (const Iterator & iterator) const [inline]
Definition at line 462 of file TVarArray.h.
References istd::TVarArray< Element >::Iterator::operator==().
template<class Element > const Element & istd::TVarArray< Element >::Iterator::operator* () const [inline]
Definition at line 354 of file TVarArray.h.
References istd::TVarArray< Element >::GetAt(), istd::TVarArray< Element >::GetSizes(), I_ASSERT, istd::CVarIndex::IsInside(), and NULL.
template<class Element > Element & istd::TVarArray< Element >::Iterator::operator* () [inline]
Definition at line 364 of file TVarArray.h.
References istd::TVarArray< Element >::GetSizes(), I_ASSERT, istd::CVarIndex::IsInside(), and NULL.
template<class Element > TVarArray< Element >::Iterator istd::TVarArray< Element >::Iterator::operator++ (int) [inline]
Definition at line 405 of file TVarArray.h.
References istd::TVarArray< Element >::GetSizes(), istd::CVarIndex::Increase(), and NULL.
template<class Element > TVarArray< Element >::Iterator & istd::TVarArray< Element >::Iterator::operator++ () [inline]
Definition at line 394 of file TVarArray.h.
References istd::TVarArray< Element >::GetSizes(), istd::CVarIndex::Increase(), and NULL.
template<class Element > TVarArray< Element >::Iterator istd::TVarArray< Element >::Iterator::operator-- (int) [inline]
Definition at line 429 of file TVarArray.h.
References istd::CVarIndex::Decrease(), istd::TVarArray< Element >::GetSizes(), and NULL.
template<class Element > TVarArray< Element >::Iterator & istd::TVarArray< Element >::Iterator::operator-- () [inline]
Definition at line 418 of file TVarArray.h.
References istd::CVarIndex::Decrease(), istd::TVarArray< Element >::GetSizes(), and NULL.
template<class Element > const Element * istd::TVarArray< Element >::Iterator::operator-> () const [inline]
Definition at line 374 of file TVarArray.h.
References istd::TVarArray< Element >::GetAt(), istd::TVarArray< Element >::GetSizes(), I_ASSERT, istd::CVarIndex::IsInside(), and NULL.
template<class Element > Element * istd::TVarArray< Element >::Iterator::operator-> () [inline]
Definition at line 384 of file TVarArray.h.
References istd::TVarArray< Element >::GetSizes(), I_ASSERT, istd::CVarIndex::IsInside(), and NULL.
template<class Element > TVarArray< Element >::Iterator & istd::TVarArray< Element >::Iterator::operator= (const Iterator & iterator) [inline]
Definition at line 442 of file TVarArray.h.
template<class Element > bool istd::TVarArray< Element >::Iterator::operator== (const Iterator & iterator) const [inline]
Definition at line 451 of file TVarArray.h.
References NULL, and istd::CVarIndex::operator==().
Referenced by istd::TVarArray< Element >::Iterator::operator!=().
Friends And Related Function Documentation
template<class Element > friend class TVarArray< Element > [friend]
Definition at line 52 of file TVarArray.h.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/istd/TVarArray.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy