ACF: imath::TVector< Size, Element > Class Template Reference
imath::TVector< Size, Element > Class Template Reference
Implementation of fixed-size mathematical vector with specified type of elements.
#include <TVector.h>
Public Types
typedef Element ElementType
typedef Element Elements [Size]
Public Member Functions
TVector ()
Create an uninitialized point.
TVector (const TVector< Size, Element > &vector)
Copy constructor.
const Element & GetElement (int i) const
Get element at specified i.
Element & GetElementRef (int i)
Get reference to element at specified i.
void SetElement (int i, const Element &value)
Set element at specified i.
void Reset ()
Set all coordinates to zero.
void Clear ()
Set all coordinates to zero.
const TVector< Size, Element >
::Elements & GetElements () const
Get read-only access to internal element container.
TVector< Size, Element >
::Elements & GetElementsRef ()
Get access to internal element container.
void Translate (const TVector< Size, Element > &vector)
Translate the point.
TVector< Size, Element > GetTranslated (const TVector< Size, Element > &vector)
Get translated point.
void GetTranslated (const TVector< Size, Element > &vector, TVector< Size, Element > &result)
/overloaded
void ScaledCumulate (const TVector< Size, Element > &vector, Element scale)
Add second vector scaled by specified factor.
bool IsNull (Element tolerance=I_BIG_EPSILON) const
Check if this vector is null.
Element GetDotProduct (const TVector< Size, Element > &vector) const
Return dot product of two vectors.
Element GetLength2 () const
Return euclidian length square.
Element GetLength () const
Return euclidian length.
Element GetDistance2 (const TVector< Size, Element > &vector) const
Return distance square between two vectors.
Element GetDistance (const TVector< Size, Element > &vector) const
Return distance between two vectors.
Element GetElementsSum () const
Get simple sum of all elements.
bool Normalize (Element length=1.0)
Normalize vector to specified length.
bool GetNormalized (TVector< Size, Element > &result, Element length=1.0) const
Return normalized vector with the same direction and specified length.
void GetMinimal (const TVector< Size, Element > &vector, TVector< Size, Element > &result) const
Get vector with minimal elements values.
void GetMaximal (const TVector< Size, Element > &vector, TVector< Size, Element > &result) const
Get vector with maximal elements values.
bool Serialize (iser::IArchive &archive)
Serialize this vector to specified archive.
bool operator== (const TVector< Size, Element > &vector) const
bool operator!= (const TVector< Size, Element > &vector) const
bool operator< (const TVector< Size, Element > &vector) const
bool operator> (const TVector< Size, Element > &vector) const
bool operator<= (const TVector< Size, Element > &vector) const
bool operator>= (const TVector< Size, Element > &vector) const
TVector< Size, Element > operator- () const
TVector< Size, Element > operator+ (const TVector< Size, Element > &vector) const
TVector< Size, Element > operator- (const TVector< Size, Element > &vector) const
TVector< Size, Element > operator* (Element scalar) const
TVector< Size, Element > operator/ (Element scalar) const
TVector< Size, Element > & operator+= (const TVector< Size, Element > &vector)
TVector< Size, Element > & operator-= (const TVector< Size, Element > &vector)
TVector< Size, Element > & operator*= (Element scalar)
TVector< Size, Element > & operator/= (Element scalar)
const Element & operator[] (int i) const
Element & operator[] (int i)
Static Public Member Functions
static int GetElementsCount ()
Get number of elements.
static bool SetElementsCount (int count)
Set number of elements.
Protected Attributes
Elements m_elements
Detailed Description
template<int Size, class Element = double>
class imath::TVector< Size, Element >
Implementation of fixed-size mathematical vector with specified type of elements.
Definition at line 21 of file TVector.h.
Member Typedef Documentation
template<int Size, class Element = double> typedef Element imath::TVector< Size, Element >::Elements[Size]
Reimplemented in icmm::TComposedColor< Size >, icmm::TComposedColor< 4 >, and icmm::TComposedColor< 3 >.
Definition at line 25 of file TVector.h.
template<int Size, class Element = double> typedef Element imath::TVector< Size, Element >::ElementType
Definition at line 24 of file TVector.h.
Constructor & Destructor Documentation
template<int Size, class Element > imath::TVector< Size, Element >::TVector () [inline]
Create an uninitialized point.
Definition at line 199 of file TVector.h.
template<int Size, class Element> imath::TVector< Size, Element >::TVector (const TVector< Size, Element > & vector) [inline]
Copy constructor.
Definition at line 205 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
Member Function Documentation
template<int Size, class Element > void imath::TVector< Size, Element >::Clear () [inline]
Set all coordinates to zero.
It makes the same as Clear() and is used for compatibility with other vector implementations.
Definition at line 246 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element> Element imath::TVector< Size, Element >::GetDistance (const TVector< Size, Element > & vector) const [inline]
Return distance between two vectors.
Definition at line 342 of file TVector.h.
References imath::TVector< Size, Element >::GetDistance2().
template<int Size, class Element> Element imath::TVector< Size, Element >::GetDistance2 (const TVector< Size, Element > & vector) const [inline]
Return distance square between two vectors.
Definition at line 335 of file TVector.h.
Referenced by imath::TVector< Size, Element >::GetDistance().
template<int Size, class Element> Element imath::TVector< Size, Element >::GetDotProduct (const TVector< Size, Element > & vector) const [inline]
Return dot product of two vectors.
Definition at line 308 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
Referenced by imath::TVector< Size, Element >::GetLength2().
template<int Size, class Element > const Element & imath::TVector< Size, Element >::GetElement (int i) const [inline]
Get element at specified i.
Definition at line 216 of file TVector.h.
References imath::TVector< Size, Element >::operator[]().
Referenced by imath::TVector< Size, Element >::GetMaximal(), imath::TVector< Size, Element >::GetMinimal(), imath::CDouble::operator!=(), imath::CDouble::operator*(), imath::CDouble::operator*=(), imath::CDouble::operator+(), imath::CDouble::operator+=(), imath::CDouble::operator-(), imath::CDouble::operator-=(), imath::CDouble::operator/(), imath::CDouble::operator/=(), imath::CDouble::operator<(), imath::CDouble::operator<=(), imath::CDouble::operator=(), imath::CDouble::operator==(), imath::CDouble::operator>(), and imath::CDouble::operator>=().
template<int Size, class Element > Element & imath::TVector< Size, Element >::GetElementRef (int i) [inline]
Get reference to element at specified i.
Definition at line 223 of file TVector.h.
References imath::TVector< Size, Element >::operator[]().
template<int Size, class Element > const TVector< Size, Element >::Elements & imath::TVector< Size, Element >::GetElements () const [inline]
Get read-only access to internal element container.
Definition at line 255 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element > int imath::TVector< Size, Element >::GetElementsCount () [inline, static]
Get number of elements.
Definition at line 565 of file TVector.h.
template<int Size, class Element > TVector< Size, Element >::Elements & imath::TVector< Size, Element >::GetElementsRef () [inline]
Get access to internal element container.
Definition at line 262 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element > Element imath::TVector< Size, Element >::GetElementsSum () const [inline]
Get simple sum of all elements.
Definition at line 581 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element > Element imath::TVector< Size, Element >::GetLength () const [inline]
Return euclidian length.
Definition at line 328 of file TVector.h.
References imath::TVector< Size, Element >::GetLength2().
Referenced by imath::TVector< Size, Element >::GetNormalized(), and imath::TVector< Size, Element >::Normalize().
template<int Size, class Element > Element imath::TVector< Size, Element >::GetLength2 () const [inline]
Return euclidian length square.
Definition at line 321 of file TVector.h.
References imath::TVector< Size, Element >::GetDotProduct().
Referenced by imath::TVector< Size, Element >::GetLength(), and imath::TVector< Size, Element >::IsNull().
template<int Size, class Element> void imath::TVector< Size, Element >::GetMaximal (const TVector< Size, Element > & vector, TVector< Size, Element > & result) const [inline]
Get vector with maximal elements values.
Definition at line 643 of file TVector.h.
References imath::TVector< Size, Element >::GetElement(), istd::Max(), and imath::TVector< Size, Element >::SetElement().
template<int Size, class Element> void imath::TVector< Size, Element >::GetMinimal (const TVector< Size, Element > & vector, TVector< Size, Element > & result) const [inline]
Get vector with minimal elements values.
Definition at line 634 of file TVector.h.
References imath::TVector< Size, Element >::GetElement(), istd::Min(), and imath::TVector< Size, Element >::SetElement().
template<int Size, class Element> bool imath::TVector< Size, Element >::GetNormalized (TVector< Size, Element > & result, Element length = 1.0) const [inline]
Return normalized vector with the same direction and specified length.
Parameters:
length new vector length.
Returns:
true, if normalization successed.
Definition at line 614 of file TVector.h.
References imath::TVector< Size, Element >::GetLength(), I_BIG_EPSILON, and imath::TVector< Size, Element >::m_elements.
template<int Size, class Element> void imath::TVector< Size, Element >::GetTranslated (const TVector< Size, Element > & vector, TVector< Size, Element > & result) [inline]
/overloaded
Definition at line 285 of file TVector.h.
template<int Size, class Element> TVector< Size, Element > imath::TVector< Size, Element >::GetTranslated (const TVector< Size, Element > & vector) [inline]
Get translated point.
Definition at line 278 of file TVector.h.
template<int Size, class Element> bool imath::TVector< Size, Element >::IsNull (Element tolerance = I_BIG_EPSILON) const [inline]
Check if this vector is null.
Definition at line 301 of file TVector.h.
References imath::TVector< Size, Element >::GetLength2().
template<int Size, class Element> bool imath::TVector< Size, Element >::Normalize (Element length = 1.0) [inline]
Normalize vector to specified length.
Parameters:
length new vector length.
Returns:
true, if normalization successed.
Definition at line 594 of file TVector.h.
References imath::TVector< Size, Element >::GetLength(), I_BIG_EPSILON, and imath::TVector< Size, Element >::m_elements.
template<int Size, class Element> bool imath::TVector< Size, Element >::operator!= (const TVector< Size, Element > & vector) const [inline]
Definition at line 363 of file TVector.h.
References imath::TVector< Size, Element >::operator==().
template<int Size, class Element> TVector< Size, Element > imath::TVector< Size, Element >::operator* (Element scalar) const [inline]
Reimplemented in i2d::CVector2d, i3d::CVector3d, icmm::CCmy, icmm::CCmyk, icmm::CHsv, icmm::CLab, icmm::CRgb, icmm::TComposedColor< Size >, icmm::TComposedColor< 4 >, and icmm::TComposedColor< 3 >.
Definition at line 517 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element> TVector< Size, Element > & imath::TVector< Size, Element >::operator*= (Element scalar) [inline]
Reimplemented in i2d::CVector2d, i3d::CVector3d, icmm::CCmy, icmm::CCmyk, icmm::CHsv, icmm::CLab, icmm::CRgb, icmm::TComposedColor< Size >, icmm::TComposedColor< 4 >, and icmm::TComposedColor< 3 >.
Definition at line 456 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element> TVector< Size, Element > imath::TVector< Size, Element >::operator+ (const TVector< Size, Element > & vector) const [inline]
Definition at line 491 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element> TVector< Size, Element > & imath::TVector< Size, Element >::operator+= (const TVector< Size, Element > & vector) [inline]
Definition at line 434 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element> TVector< Size, Element > imath::TVector< Size, Element >::operator- (const TVector< Size, Element > & vector) const [inline]
Definition at line 504 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element > TVector< Size, Element > imath::TVector< Size, Element >::operator- () const [inline]
Reimplemented in i2d::CVector2d, and i3d::CVector3d.
Definition at line 478 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element> TVector< Size, Element > & imath::TVector< Size, Element >::operator-= (const TVector< Size, Element > & vector) [inline]
Definition at line 445 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element> TVector< Size, Element > imath::TVector< Size, Element >::operator/ (Element scalar) const [inline]
Reimplemented in i2d::CVector2d, i3d::CVector3d, icmm::CCmy, icmm::CCmyk, icmm::CHsv, icmm::CLab, icmm::CRgb, icmm::TComposedColor< Size >, icmm::TComposedColor< 4 >, and icmm::TComposedColor< 3 >.
Definition at line 530 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element> TVector< Size, Element > & imath::TVector< Size, Element >::operator/= (Element scalar) [inline]
Reimplemented in i2d::CVector2d, i3d::CVector3d, icmm::CCmy, icmm::CCmyk, icmm::CHsv, icmm::CLab, icmm::CRgb, icmm::TComposedColor< Size >, icmm::TComposedColor< 4 >, and icmm::TComposedColor< 3 >.
Definition at line 467 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element> bool imath::TVector< Size, Element >::operator< (const TVector< Size, Element > & vector) const [inline]
Definition at line 370 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element> bool imath::TVector< Size, Element >::operator<= (const TVector< Size, Element > & vector) const [inline]
Definition at line 402 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element> bool imath::TVector< Size, Element >::operator== (const TVector< Size, Element > & vector) const [inline]
Definition at line 351 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
Referenced by imath::TVector< Size, Element >::operator!=().
template<int Size, class Element> bool imath::TVector< Size, Element >::operator> (const TVector< Size, Element > & vector) const [inline]
Definition at line 386 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element> bool imath::TVector< Size, Element >::operator>= (const TVector< Size, Element > & vector) const [inline]
Definition at line 418 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element > Element & imath::TVector< Size, Element >::operator[] (int i) [inline]
Definition at line 553 of file TVector.h.
References I_ASSERT, and imath::TVector< Size, Element >::m_elements.
template<int Size, class Element > const Element & imath::TVector< Size, Element >::operator[] (int i) const [inline]
Definition at line 543 of file TVector.h.
References I_ASSERT, and imath::TVector< Size, Element >::m_elements.
Referenced by imath::TVector< Size, Element >::GetElement(), imath::TVector< Size, Element >::GetElementRef(), and imath::TVector< Size, Element >::SetElement().
template<int Size, class Element > void imath::TVector< Size, Element >::Reset () [inline]
Set all coordinates to zero.
It makes the same as Clear() and is used for compatibility with other vector implementations.
Definition at line 237 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element> void imath::TVector< Size, Element >::ScaledCumulate (const TVector< Size, Element > & vector, Element scale) [inline]
Add second vector scaled by specified factor.
It is equal of Translate(vector * scale) but can be faster implemented.
Definition at line 292 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
template<int Size, class Element > bool imath::TVector< Size, Element >::Serialize (iser::IArchive & archive) [inline]
Serialize this vector to specified archive.
Reimplemented in icmm::CCmy, icmm::CCmyk, icmm::CHsv, icmm::CLab, icmm::CRgb, icmm::TComposedColor< Size >, icmm::TComposedColor< 4 >, and icmm::TComposedColor< 3 >.
Definition at line 652 of file TVector.h.
References imath::TVector< Size, Element >::m_elements, and iser::IArchive::Process().
template<int Size, class Element> void imath::TVector< Size, Element >::SetElement (int i, const Element & value) [inline]
Set element at specified i.
Definition at line 230 of file TVector.h.
References imath::TVector< Size, Element >::operator[]().
Referenced by imath::TVector< Size, Element >::GetMaximal(), and imath::TVector< Size, Element >::GetMinimal().
template<int Size, class Element > bool imath::TVector< Size, Element >::SetElementsCount (int count) [inline, static]
Set number of elements.
This method is provided for template implementations.
Parameters:
count number of elements.
Returns:
true, if the number of set elements equals template parameter.
Definition at line 572 of file TVector.h.
template<int Size, class Element> void imath::TVector< Size, Element >::Translate (const TVector< Size, Element > & vector) [inline]
Translate the point.
Definition at line 269 of file TVector.h.
References imath::TVector< Size, Element >::m_elements.
Member Data Documentation
template<int Size, class Element = double> Elements imath::TVector< Size, Element >::m_elements [protected]
Definition at line 192 of file TVector.h.
Referenced by imath::TVector< Size, Element >::Clear(), imath::TVector< Size, Element >::GetDotProduct(), imath::TVector< Size, Element >::GetElements(), imath::TVector< Size, Element >::GetElementsRef(), imath::TVector< Size, Element >::GetElementsSum(), imath::TVector< Size, Element >::GetNormalized(), imath::TVector< Size, Element >::Normalize(), imath::TVector< Size, Element >::operator*(), imath::TVector< Size, Element >::operator*=(), imath::TVector< Size, Element >::operator+(), imath::TVector< Size, Element >::operator+=(), imath::TVector< Size, Element >::operator-(), imath::TVector< Size, Element >::operator-=(), imath::TVector< Size, Element >::operator/(), imath::TVector< Size, Element >::operator/=(), imath::TVector< Size, Element >::operator<(), imath::TVector< Size, Element >::operator<=(), imath::TVector< Size, Element >::operator==(), imath::TVector< Size, Element >::operator>(), imath::TVector< Size, Element >::operator>=(), imath::TVector< Size, Element >::operator[](), imath::TVector< Size, Element >::Reset(), imath::TVector< Size, Element >::ScaledCumulate(), imath::TVector< Size, Element >::Serialize(), imath::TVector< Size, Element >::Translate(), and imath::TVector< Size, Element >::TVector().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/imath/TVector.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy