icomp::CBaseComponentStaticInfo Class Reference
icomp::CBaseComponentStaticInfo Class Reference
Standard implementation of static info for base component classes.
#include <CBaseComponentStaticInfo.h>
Public Types
typedef CComponentStaticInfoBase BaseClass
typedef void *(* InterfaceExtractorPtr)(IComponent &component)
Public Types inherited from icomp::IComponentStaticInfo
enum ComponentType { CT_NONE, CT_REAL, CT_COMPOSITE }
Specify type of the component realization.
enum MetaGroupId { MGI_ATTRIBUTES = IElementStaticInfo::MGI_LAST + 1, MGI_EMBEDDED_COMPONENTS }
Public Types inherited from icomp::IElementStaticInfo
enum MetaGroupId { MGI_INTERFACES = 0, MGI_SUBELEMENTS, MGI_LAST = MGI_SUBELEMENTS }
typedef QSet< QByteArray > Ids
Public Member Functions
CBaseComponentStaticInfo (const IRealComponentStaticInfo *baseComponentPtr=NULL)
virtual void RegisterInterfaceExtractor (const QByteArray &interfaceName, InterfaceExtractorPtr extractorPtr)
Register interface ID for this static component info.
virtual void RegisterAttributeInfo (const QByteArray &attributeId, const IAttributeStaticInfo *attributeInfoPtr)
Register static attribute info.
virtual void RegisterSubelementInfo (const QByteArray &subcomponentId, const IElementStaticInfo *staticInfoPtr)
Register static subcomponent info.
virtual IComponent * CreateComponent () const
Create component instance.
virtual void * GetComponentInterface (const istd::CClassInfo &interfaceType, IComponent &component, const QByteArray &subId) const
Extract instance implemented specified interface from some component.
virtual const
IAttributeStaticInfo * GetAttributeInfo (const QByteArray &attributeId) const
Get set of attributes.
virtual const IElementStaticInfo * GetSubelementInfo (const QByteArray &subcomponentId) const
Return number of interfaces for specific slot.
virtual Ids GetMetaIds (int metaGroupId) const
Get list of meta IDs associated with some meta key.
Public Member Functions inherited from icomp::CComponentStaticInfoBase
virtual int GetComponentType () const
Get information about component type.
virtual const
IComponentStaticInfo * GetEmbeddedComponentInfo (const QByteArray &embeddedId) const
Return number of interfaces for specific slot.
virtual const QString & GetDescription () const
Get human readable description of this component.
virtual const QString & GetKeywords () const
Get keywords for this component.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Detailed Description
Standard implementation of static info for base component classes.
The main difference to 'normal' component static info is, that instances of such components cannot be created.
Definition at line 17 of file CBaseComponentStaticInfo.h.
Member Typedef Documentation
typedef CComponentStaticInfoBase icomp::CBaseComponentStaticInfo::BaseClass
Definition at line 22 of file CBaseComponentStaticInfo.h.
typedef void*(* icomp::CBaseComponentStaticInfo::InterfaceExtractorPtr)(IComponent &component)
Definition at line 24 of file CBaseComponentStaticInfo.h.
Constructor & Destructor Documentation
icomp::CBaseComponentStaticInfo::CBaseComponentStaticInfo (const IRealComponentStaticInfo * baseComponentPtr = NULL)
Member Function Documentation
virtual IComponent* icomp::CBaseComponentStaticInfo::CreateComponent () const virtual
Create component instance.
Returns
pointer to created component or NULL if this component cannot be created.
Implements icomp::IRealComponentStaticInfo.
Reimplemented in icomp::CCompositeComponentStaticInfo, and icomp::TComponentStaticInfo< Component >.
virtual const IAttributeStaticInfo* icomp::CBaseComponentStaticInfo::GetAttributeInfo (const QByteArray & attributeId) const virtual
Get set of attributes.
Reimplemented from icomp::CComponentStaticInfoBase.
virtual void* icomp::CBaseComponentStaticInfo::GetComponentInterface (const istd::CClassInfo & interfaceType, IComponent & component, const QByteArray & subId) const virtual
Extract instance implemented specified interface from some component.
Implements icomp::IComponentInterfaceExtractor.
virtual Ids icomp::CBaseComponentStaticInfo::GetMetaIds (int metaGroupId) const virtual
Get list of meta IDs associated with some meta key.
See Also
MetaGroupId
Reimplemented from icomp::CComponentStaticInfoBase.
virtual const IElementStaticInfo* icomp::CBaseComponentStaticInfo::GetSubelementInfo (const QByteArray & subcomponentId) const virtual
Return number of interfaces for specific slot.
Parameters
subcomponentId ID of subcomponent.
See Also
GetMetaIds() and MGI_SUBELEMENTS.
Reimplemented from icomp::CComponentStaticInfoBase.
virtual void icomp::CBaseComponentStaticInfo::RegisterAttributeInfo (const QByteArray & attributeId, const IAttributeStaticInfo * attributeInfoPtr) virtual
Register static attribute info.
Parameters
attributeId ID of attribute.
attributeInfoPtr static attribute info object used to describe attribute type and as factory. It cannot be NULL.
Referenced by icomp::TAttributeStaticInfo< Attribute >::TAttributeStaticInfo().
virtual void icomp::CBaseComponentStaticInfo::RegisterInterfaceExtractor (const QByteArray & interfaceName, InterfaceExtractorPtr extractorPtr) virtual
Register interface ID for this static component info.
This interface ID is used for static check if this component can be used to resolve reference dependecy of second one.
Referenced by icomp::TInterfaceRegistrator< Interface >::TInterfaceRegistrator().
virtual void icomp::CBaseComponentStaticInfo::RegisterSubelementInfo (const QByteArray & subcomponentId, const IElementStaticInfo * staticInfoPtr) virtual
Register static subcomponent info.
Parameters
subcomponentId ID of this subcomponent.
componentInfoPtr static subcomponent info object used to describe subcomponent type and as factory. It cannot be NULL.
Referenced by icomp::TSubelementStaticInfo< ComponentType >::TSubelementStaticInfo().
The documentation for this class was generated from the following file:
Include/icomp/CBaseComponentStaticInfo.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy