icomp::CComponentContext Class Reference
icomp::CComponentContext Class Reference
Base implementation of component session context.
#include <CComponentContext.h>
Classes
struct AttributeInfo
Public Member Functions
CComponentContext (const IRegistryElement *elementPtr, const IComponentStaticInfo *staticInfoPtr, const IComponentContext *parentPtr, const QByteArray &contextId)
QByteArray GetCompleteContextId () const
virtual const QByteArray & GetContextId () const
Get ID of this component in the context tree.
virtual const IRegistryElement & GetRegistryElement () const
Get access to component registry element object.
virtual const
IComponentStaticInfo & GetStaticInfo () const
Get component static info associated with this context.
virtual const IComponentContext * GetParentContext () const
Get access to parent component context.
virtual const iser::IObject * GetAttribute (const QByteArray &attributeId, int *definitionLevelPtr=NULL) const
Get attribute using its ID.
Static Public Member Functions
static QByteArray GetHierarchyAddress (const IComponentContext *contextPtr)
Get address of this component identifying it in component topology hierarchy.
Protected Member Functions
bool CalcAttributeInfo (const QByteArray &attributeId, AttributeInfo &result) const
Detailed Description
Base implementation of component session context.
This implementation uses icomp::IRegistryElement to generate lilst of attributes. Please note that resolving of exported attribute is done.
Definition at line 25 of file CComponentContext.h.
Constructor & Destructor Documentation
icomp::CComponentContext::CComponentContext (const IRegistryElement * elementPtr, const IComponentStaticInfo * staticInfoPtr, const IComponentContext * parentPtr, const QByteArray & contextId)
Member Function Documentation
bool icomp::CComponentContext::CalcAttributeInfo (const QByteArray & attributeId, AttributeInfo & result) const [protected]
virtual const iser::IObject* icomp::CComponentContext::GetAttribute (const QByteArray & attributeId, int * definitionLevelPtr = NULL) const [virtual]
Get attribute using its ID.
Parameters:
attributeId ID of attribute.
definitionLevelPtr optional return value. This will be set to number parents you have to iterate to get component where this attribute was defined. If this attribute was defined in actual component it equals 0.
Implements icomp::IComponentContext.
QByteArray icomp::CComponentContext::GetCompleteContextId () const
Referenced by ibase::TModelObserverCompWrap< ObserverComponent >::OnComponentCreated().
virtual const QByteArray& icomp::CComponentContext::GetContextId () const [virtual]
Get ID of this component in the context tree.
This should be unique for all elements in the same tree level.
Implements icomp::IComponentContext.
Referenced by icomp::TComponentCloneWrap< BaseClass >::CloneMe(), and ibase::TLoggerCompWrap< Base >::DecorateMessage().
static QByteArray icomp::CComponentContext::GetHierarchyAddress (const IComponentContext * contextPtr) [static]
Get address of this component identifying it in component topology hierarchy.
Referenced by icomp::TAttributeMemberBase< Attribute >::InitInternal().
virtual const IComponentContext* icomp::CComponentContext::GetParentContext () const [virtual]
Get access to parent component context.
Implements icomp::IComponentContext.
virtual const IRegistryElement& icomp::CComponentContext::GetRegistryElement () const [virtual]
Get access to component registry element object.
State of the component context is based on this registry element (part of registry document describing component) and context parent.
Implements icomp::IComponentContext.
virtual const IComponentStaticInfo& icomp::CComponentContext::GetStaticInfo () const [virtual]
Get component static info associated with this context.
Implements icomp::IComponentContext.
The documentation for this class was generated from the following file:
Include/icomp/CComponentContext.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy