i2d::CPolygon Class Reference
i2d::CPolygon Class Reference
Definition of the data model for a polygon.
#include <CPolygon.h>
Public Member Functions
CPolygon ()
virtual void Clear ()
Removes all nodes.
virtual void SetNodesCount (int nodesCount)
Set new nodes count.
virtual int GetNodesCount () const
Return size of node table.
virtual const i2d::CVector2d & GetNode (int index) const
Return node at specified index.
virtual void SetNode (int index, const i2d::CVector2d &node)
Set node at specified index.
virtual bool InsertNode (const i2d::CVector2d &node)
Insert a node at the end of node table.
virtual bool InsertNode (int index, const i2d::CVector2d &node)
Insert a node at specified index.
virtual bool RemoveNode (int index)
Remove a node at specified index.
virtual double GetOutlineLength () const
Get outline length of this polygon.
virtual CVector2d GetCenter () const
Returns center of this 2D-object.
virtual void MoveCenterTo (const CVector2d &position)
Move object to position position.
virtual i2d::CRectangle GetBoundingBox () const
Calculate bounding box (the same as above but returns result directly).
virtual bool Transform (const ITransformation2d &transformation, ITransformation2d::ExactnessMode mode=ITransformation2d::EM_NONE, double *errorFactorPtr=NULL)
Transform this object using some transformation.
virtual bool InvTransform (const ITransformation2d &transformation, ITransformation2d::ExactnessMode mode=ITransformation2d::EM_NONE, double *errorFactorPtr=NULL)
Do inverse transformation of this object.
virtual bool GetTransformed (const ITransformation2d &transformation, IObject2d &result, ITransformation2d::ExactnessMode mode=ITransformation2d::EM_NONE, double *errorFactorPtr=NULL) const
Calulate transformation of the object into second one.
virtual bool GetInvTransformed (const ITransformation2d &transformation, IObject2d &result, ITransformation2d::ExactnessMode mode=ITransformation2d::EM_NONE, double *errorFactorPtr=NULL) const
Calulate inverse transformation of the object into second one.
virtual bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
virtual int GetSupportedOperations () const
Get set of flags for supported operations.
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
virtual istd::IChangeable * CloneMe (CompatibilityMode mode=CM_WITHOUT_REFS) const
Make a copy of this object.
virtual bool IsEqual (const IChangeable &object) const
Public Member Functions inherited from i2d::CObject2dBase
CObject2dBase ()
CObject2dBase (const CObject2dBase &object2d)
virtual const ICalibration2d * GetCalibration () const
Get access to transformation object, which transforms a local logical coordinate system to global one.
virtual void SetCalibration (const ICalibration2d *calibrationPtr, bool releaseFlag=false)
Set calibration of this object.
virtual bool CopyFrom (const istd::IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Copy this object from another one.
Public Member Functions inherited from iser::ISerializable
virtual quint32 GetMinimalVersion (int versionId) const
Get minimal needed version to correct storing of this data.
Public Member Functions inherited from istd::IChangeable
virtual void BeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Starts the change transaction.
virtual void EndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Ends the change transaction.
virtual bool IsEqual (const IChangeable &object) const
Compare this object with another object.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Additional Inherited Members
Public Types inherited from i2d::IObject2d
enum ChangeFlags { CF_OBJECT_POSITION = 1 << 20 }
Public Types inherited from istd::IChangeable
enum ChangeFlags {
CF_ACF_INTERNAL = 1 << 0, CF_MODEL = 1 << 1, CF_ABORTED = 1 << 2, CF_DELEGATED = 1 << 3,
CF_NO_UNDO = 1 << 5
}
enum SupportedOperations {
SO_NONE = 0, SO_OBSERVE = 1, SO_COPY = 2, SO_CLONE = 4,
SO_COMPARE = 8
}
Flags for supported operations.
enum CompatibilityMode { CM_STRICT, CM_WITHOUT_REFS, CM_WITH_REFS, CM_CONVERT }
Control how relationship betweeen objects are interpreted.
Protected Member Functions inherited from istd::IChangeable
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for begin change event.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for end change event.
Detailed Description
Definition of the data model for a polygon.
Definition at line 22 of file CPolygon.h.
Constructor & Destructor Documentation
i2d::CPolygon::CPolygon () inline
Definition at line 137 of file CPolygon.h.
Member Function Documentation
virtual void i2d::CPolygon::Clear () virtual
Removes all nodes.
Reimplemented in i2d::TDataNodePolyline< NodeData >.
virtual istd::IChangeable* i2d::CPolygon::CloneMe (CompatibilityMode mode = CM_WITHOUT_REFS) const virtual
Make a copy of this object.
Returns
new instance or NULL, if this operation is not supported.
Reimplemented from istd::IChangeable.
Reimplemented in i2d::CPolyline, and i2d::CSpline.
virtual bool i2d::CPolygon::CopyFrom (const IChangeable & object, CompatibilityMode mode = CM_WITHOUT_REFS) virtual
Reimplemented in i2d::CPolyline, i2d::TDataNodePolyline< NodeData >, and i2d::CSpline.
Referenced by iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::UpdateModel().
virtual i2d::CRectangle i2d::CPolygon::GetBoundingBox () const virtual
Calculate bounding box (the same as above but returns result directly).
Implements i2d::IObject2d.
virtual CVector2d i2d::CPolygon::GetCenter () const virtual
Returns center of this 2D-object.
Implements i2d::IObject2d.
Referenced by iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnToolsButtonMenuActionTriggered().
virtual bool i2d::CPolygon::GetInvTransformed (const ITransformation2d & transformation, IObject2d & result, ITransformation2d::ExactnessMode mode = ITransformation2d::EM_NONE, double * errorFactorPtr = NULL) const virtual
Calulate inverse transformation of the object into second one.
Please note, that this operation transforms logical coordinates, it means that the calibration will be ignored.
Parameters
mode controls needed transformation exactness.
errorFactorPtr optional output where approximated length of transformation error vector will be stored. Value 0 means that transformation is exactly done.
result result object.
Returns
true, if transformation was done correctly.
Reimplemented from i2d::CObject2dBase.
const i2d::CVector2d & i2d::CPolygon::GetNode (int index) const inline virtual
Return node at specified index.
Parameters
index an index in node table.
Definition at line 150 of file CPolygon.h.
Referenced by i2d::TDataNodePolyline< NodeData >::CopyFrom(), iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnToolsButtonMenuActionTriggered(), and iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::UpdateGui().
int i2d::CPolygon::GetNodesCount () const inline virtual
Return size of node table.
Definition at line 144 of file CPolygon.h.
Referenced by i2d::TDataNodePolyline< NodeData >::CopyFrom(), iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnToolsButtonMenuActionTriggered(), and iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::UpdateGui().
virtual double i2d::CPolygon::GetOutlineLength () const virtual
Get outline length of this polygon.
virtual int i2d::CPolygon::GetSupportedOperations () const virtual
Get set of flags for supported operations.
See Also
SupportedOperations
Reimplemented from istd::IChangeable.
Reimplemented in i2d::CPolyline, and i2d::CSpline.
virtual bool i2d::CPolygon::GetTransformed (const ITransformation2d & transformation, IObject2d & result, ITransformation2d::ExactnessMode mode = ITransformation2d::EM_NONE, double * errorFactorPtr = NULL) const virtual
Calulate transformation of the object into second one.
Please note, that this operation transforms logical coordinates, it means that the calibration will be ignored.
Parameters
mode controls needed transformation exactness.
errorFactorPtr optional output where approximated length of transformation error vector will be stored. Value 0 means that transformation is exactly done.
result result object.
Returns
true, if transformation was done correctly.
Reimplemented from i2d::CObject2dBase.
virtual bool i2d::CPolygon::InsertNode (const i2d::CVector2d & node) virtual
Insert a node at the end of node table.
Reimplemented in i2d::TDataNodePolyline< NodeData >, and i2d::CTubePolylineComp.
Referenced by iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::UpdateModel().
virtual bool i2d::CPolygon::InsertNode (int index, const i2d::CVector2d & node) virtual
Insert a node at specified index.
Reimplemented in i2d::TDataNodePolyline< NodeData >, and i2d::CTubePolylineComp.
virtual bool i2d::CPolygon::InvTransform (const ITransformation2d & transformation, ITransformation2d::ExactnessMode mode = ITransformation2d::EM_NONE, double * errorFactorPtr = NULL) virtual
Do inverse transformation of this object.
Please note, that this operation transforms logical coordinates, it means that the calibration will be ignored.
Parameters
mode controls needed transformation exactness.
errorFactorPtr optional output where approximated length of transformation error vector will be stored. Value 0 means that transformation is exactly done.
Returns
true, if transformation was done correctly.
Reimplemented from i2d::CObject2dBase.
virtual bool i2d::CPolygon::IsEqual (const IChangeable & object) const virtual
Referenced by iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::UpdateModel().
virtual void i2d::CPolygon::MoveCenterTo (const CVector2d & position) virtual
Move object to position position.
Implements i2d::IObject2d.
virtual bool i2d::CPolygon::RemoveNode (int index) virtual
Remove a node at specified index.
Reimplemented in i2d::TDataNodePolyline< NodeData >.
virtual bool i2d::CPolygon::Serialize (iser::IArchive & archive) virtual
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See Also
iser::IArchive
Implements iser::ISerializable.
Reimplemented in i2d::CDataNodePolylineBase.
void i2d::CPolygon::SetNode (int index, const i2d::CVector2d & node) inline virtual
Set node at specified index.
Parameters
index Index in node table.
node New node value.
Definition at line 158 of file CPolygon.h.
Referenced by iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnToolsButtonMenuActionTriggered().
virtual void i2d::CPolygon::SetNodesCount (int nodesCount) virtual
Set new nodes count.
Reimplemented in i2d::TDataNodePolyline< NodeData >, and i2d::CTubePolylineComp.
virtual bool i2d::CPolygon::Transform (const ITransformation2d & transformation, ITransformation2d::ExactnessMode mode = ITransformation2d::EM_NONE, double * errorFactorPtr = NULL) virtual
Transform this object using some transformation.
Please note, that this operation transforms logical coordinates, it means that the calibration will be ignored.
Parameters
mode controls needed transformation exactness.
errorFactorPtr optional output where approximated length of transformation error vector will be stored. Value 0 means that transformation is exactly done.
Returns
true, if transformation was done correctly.
Reimplemented from i2d::CObject2dBase.
Referenced by iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >::OnToolsButtonMenuActionTriggered().
The documentation for this class was generated from the following file:
Include/i2d/CPolygon.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy