ACF: istd::ILogger Class Reference
istd::ILogger Class Reference
Common interface for classes sending some log info.
#include <ILogger.h>
Public Types
enum MessageCategory { MC_INFO, MC_WARNING, MC_ERROR, MC_CRITICAL }
Category of message.
enum MessageFlags { MF_DEBUG = 0x1, MF_SYSTEM = 0x2, MF_USER = 0x4 }
Additionaly message flags.
Protected Member Functions
virtual bool IsLogConsumed (const MessageCategory *categoryPtr=NULL, const int *flagsPtr=NULL) const
Check if any log message is consumed.
virtual bool SendLogMessage (MessageCategory category, int id, const istd::CString &message, const istd::CString &messageSource, int flags=0) const
Send any message to log.
virtual void DecorateMessage (MessageCategory category, int id, int flags, istd::CString &message, istd::CString &messageSource) const
Decorate message parts before outputting.
Detailed Description
Common interface for classes sending some log info.
Default implementation is provided for convinience and it does nothing.
Definition at line 17 of file ILogger.h.
Member Enumeration Documentation
enum istd::ILogger::MessageCategory
Category of message.
Enumerator:
MC_INFO
MC_WARNING
MC_ERROR
MC_CRITICAL
Definition at line 23 of file ILogger.h.
enum istd::ILogger::MessageFlags
Additionaly message flags.
Enumerator:
MF_DEBUG
MF_SYSTEM
MF_USER
Definition at line 34 of file ILogger.h.
Member Function Documentation
void istd::ILogger::DecorateMessage (MessageCategory category, int id, int flags, istd::CString & message, istd::CString & messageSource) const [inline, protected, virtual]
Decorate message parts before outputting.
Reimplemented in ibase::TLoggerCompWrap< Base >, iser::CFileReadArchive, iser::CXmlFileReadArchive, iser::TXmlStreamReadArchiveBase< StreamClass >, ibase::TLoggerCompWrap< CFileTypeInfoComp >, iser::TXmlStreamReadArchiveBase< std::istringstream >, and iser::TXmlStreamReadArchiveBase< std::ifstream >.
Definition at line 94 of file ILogger.h.
Referenced by iser::TXmlStreamReadArchiveBase< StreamClass >::DecorateMessage(), ibase::TLoggerCompWrap< Base >::DecorateMessage(), and ibase::TLoggerWrap< Base >::SendLogMessage().
bool istd::ILogger::IsLogConsumed (const MessageCategory * categoryPtr = NULL, const int * flagsPtr = NULL) const [inline, protected, virtual]
Check if any log message is consumed.
Default implementation retuns false.
Reimplemented in ibase::TLoggerWrap< Base >, ibase::TLoggerWrap< Base >, and ibase::TLoggerWrap< CFileTypeInfoComp >.
Definition at line 80 of file ILogger.h.
bool istd::ILogger::SendLogMessage (MessageCategory category, int id, const istd::CString & message, const istd::CString & messageSource, int flags = 0) const [inline, protected, virtual]
Send any message to log.
Default implementation do nothing.
Parameters:
category message category.
id binary id identifying this message type for automatical processing.
message message text will be send.
messageSource source of the message.
Returns:
true, if it was possible to send this message and it is 'consumed'.
Reimplemented in ibase::TLoggerWrap< Base >, ibase::TLoggerWrap< Base >, and ibase::TLoggerWrap< CFileTypeInfoComp >.
Definition at line 88 of file ILogger.h.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/istd/ILogger.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy