ACF: imath::TVarMatrix< Element > Class Template Reference
imath::TVarMatrix< Element > Class Template Reference
Definition of mathematical matrix.
#include <TVarMatrix.h>
Public Member Functions
TVarMatrix ()
Create empty matrix.
TVarMatrix (const TVarMatrix< Element > &matrix)
Copy constructor.
TVarMatrix (istd::CIndex2d size)
Create matrix with specified size.
TVarMatrix (const TVarVector< Element > &vector, bool isTransposed=false)
Create matrix from vector.
virtual void Clear ()
Set all matrix cells to zero.
virtual void InitToIdentity (int size)
Create identity matrix.
Element GetMaxElement () const
Element GetMinElement () const
void GetNegated (TVarMatrix< Element > &result)
Get result matrix with negated all elements.
void GetAdded (const TVarMatrix< Element > &matrix, TVarMatrix< Element > &result) const
Get sum of two matrices.
void GetSubstracted (const TVarMatrix< Element > &matrix, TVarMatrix< Element > &result) const
Get result of substraction of two matrices.
void GetMultiplied (const TVarMatrix< Element > &matrix, TVarMatrix< Element > &result) const
Get result of multiplication of two matrices.
void GetScaled (Element value, TVarMatrix< Element > &result) const
Get result of multiplication of this matrix with scalar value.
void GetTransposed (TVarMatrix< Element > &result) const
Get transposed matrix.
TVarMatrix< Element > GetTransposed () const
Get transposed matrix.
void Transpose ()
Transpose matrix.
double GetEuclideanNorm2 () const
double GetEuclideanNorm () const
bool GetTriangleDecomposed (TVarMatrix< Element > &result, const TVarMatrix< Element > *matrix2Ptr=NULL, TVarMatrix< Element > *result2Ptr=NULL, int maxColumns=-1, Element minHhNorm=I_BIG_EPSILON) const
Transform matrix to upper triangle form using method of Householder reflexions.
bool TransformR (int firstPartWidth)
Transform this matrix in place.
bool GetSolvedTriangle (const TVarMatrix< Element > &vector, TVarMatrix< Element > &result, Element accuracy=I_BIG_EPSILON) const
Solving of linear system with triangle matrix.
bool GetSolvedLSP (const TVarMatrix< Element > &vector, TVarMatrix< Element > &result, Element minHhNorm=I_BIG_EPSILON) const
Solve 'Least Square Problem'.
void GetColumnVector (int columnIndex, TVarVector< Element > &result)
Get single column as vector.
void GetRowVector (int rowIndex, TVarVector< Element > &result)
Get single row as vector.
bool Serialize (iser::IArchive &archive)
TVarMatrix< Element > operator+ (const TVarMatrix< Element > &b) const
TVarMatrix< Element > operator- (const TVarMatrix< Element > &b) const
TVarMatrix< Element > operator- ()
TVarMatrix< Element > operator* (const TVarMatrix< Element > &b) const
TVarMatrix< Element > operator* (Element value) const
bool operator== (const TVarMatrix< Element > &matrix) const
bool operator!= (const TVarMatrix< Element > &matrix) const
Detailed Description
template<class Element>
class imath::TVarMatrix< Element >
Definition of mathematical matrix.
Definition at line 22 of file TVarMatrix.h.
Constructor & Destructor Documentation
template<class Element > imath::TVarMatrix< Element >::TVarMatrix () [inline]
Create empty matrix.
Definition at line 251 of file TVarMatrix.h.
template<class Element > imath::TVarMatrix< Element >::TVarMatrix (const TVarMatrix< Element > & matrix) [inline]
Copy constructor.
Definition at line 257 of file TVarMatrix.h.
template<class Element > imath::TVarMatrix< Element >::TVarMatrix (istd::CIndex2d size) [inline]
Create matrix with specified size.
Definition at line 264 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::SetSizes().
template<class Element > imath::TVarMatrix< Element >::TVarMatrix (const TVarVector< Element > & vector, bool isTransposed = false) [inline]
Create matrix from vector.
Definition at line 271 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::DeepCopy(), imath::TVarVector< Element >::GetElements(), and imath::TVarVector< Element >::GetElementsCount().
Member Function Documentation
template<class Element > void imath::TVarMatrix< Element >::Clear () [inline, virtual]
Set all matrix cells to zero.
Definition at line 285 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::GetSizes(), and istd::TArray< Element, 2 >::SetAt().
Referenced by imath::TVarMatrix< Element >::InitToIdentity().
template<class Element > void imath::TVarMatrix< Element >::GetAdded (const TVarMatrix< Element > & matrix, TVarMatrix< Element > & result) const [inline]
Get sum of two matrices.
Definition at line 376 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::GetAt(), istd::TArray< Element, 2 >::GetSizes(), I_ASSERT, istd::TArray< Element, 2 >::SetAt(), and istd::TArray< Element, 2 >::SetSizes().
Referenced by imath::TVarMatrix< Element >::operator+().
template<class Element > void imath::TVarMatrix< Element >::GetColumnVector (int columnIndex, TVarVector< Element > & result) [inline]
Get single column as vector.
Definition at line 642 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::GetAt(), I_ASSERT, and imath::TVarVector< Element >::SetElementsCount().
template<class Element > double imath::TVarMatrix< Element >::GetEuclideanNorm () const [inline]
Definition at line 495 of file TVarMatrix.h.
References imath::TVarMatrix< Element >::GetEuclideanNorm2().
template<class Element > double imath::TVarMatrix< Element >::GetEuclideanNorm2 () const [inline]
Definition at line 479 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::GetAt().
Referenced by imath::TVarMatrix< Element >::GetEuclideanNorm().
template<class Element > Element imath::TVarMatrix< Element >::GetMaxElement () const [inline]
Definition at line 312 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::GetAt().
template<class Element > Element imath::TVarMatrix< Element >::GetMinElement () const [inline]
Definition at line 336 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::GetAt().
template<class Element > void imath::TVarMatrix< Element >::GetMultiplied (const TVarMatrix< Element > & matrix, TVarMatrix< Element > & result) const [inline]
Get result of multiplication of two matrices.
Definition at line 410 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::GetAt(), istd::TArray< Element, 2 >::GetSizes(), I_ASSERT, istd::TArray< Element, 2 >::SetAt(), and istd::TArray< Element, 2 >::SetSizes().
Referenced by imath::TVarMatrix< Element >::operator*().
template<class Element > void imath::TVarMatrix< Element >::GetNegated (TVarMatrix< Element > & result) [inline]
Get result matrix with negated all elements.
Definition at line 360 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::GetAt(), istd::TArray< Element, 2 >::GetSizes(), istd::TArray< Element, 2 >::SetAt(), and istd::TArray< Element, 2 >::SetSizes().
Referenced by imath::TVarMatrix< Element >::operator-().
template<class Element > void imath::TVarMatrix< Element >::GetRowVector (int rowIndex, TVarVector< Element > & result) [inline]
Get single row as vector.
Definition at line 657 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::GetAt(), I_ASSERT, and imath::TVarVector< Element >::SetElementsCount().
template<class Element > void imath::TVarMatrix< Element >::GetScaled (Element value, TVarMatrix< Element > & result) const [inline]
Get result of multiplication of this matrix with scalar value.
Definition at line 443 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::GetAt(), istd::TArray< Element, 2 >::GetSizes(), istd::TArray< Element, 2 >::SetAt(), and istd::TArray< Element, 2 >::SetSizes().
Referenced by imath::TVarMatrix< Element >::operator*().
template<class Element > bool imath::TVarMatrix< Element >::GetSolvedLSP (const TVarMatrix< Element > & vector, TVarMatrix< Element > & result, Element minHhNorm = I_BIG_EPSILON) const [inline]
Solve 'Least Square Problem'.
Solve linear Least Square Problem for equation Ax = y, where A is a N * M matrix, N >= M.
Definition at line 628 of file TVarMatrix.h.
References imath::TVarMatrix< Element >::GetSolvedTriangle(), and imath::TVarMatrix< Element >::GetTriangleDecomposed().
template<class Element > bool imath::TVarMatrix< Element >::GetSolvedTriangle (const TVarMatrix< Element > & vector, TVarMatrix< Element > & result, Element accuracy = I_BIG_EPSILON) const [inline]
Solving of linear system with triangle matrix.
Rx = y, result = x.
Returns:
true if linear equation system was solved.
Definition at line 596 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::GetAt(), istd::TArray< Element, 2 >::GetSize(), istd::TArray< Element, 2 >::GetSizes(), I_ASSERT, istd::TArray< Element, 2 >::SetAt(), and istd::TArray< Element, 2 >::SetSizes().
Referenced by imath::TVarMatrix< Element >::GetSolvedLSP().
template<class Element > void imath::TVarMatrix< Element >::GetSubstracted (const TVarMatrix< Element > & matrix, TVarMatrix< Element > & result) const [inline]
Get result of substraction of two matrices.
Definition at line 393 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::GetAt(), istd::TArray< Element, 2 >::GetSizes(), I_ASSERT, istd::TArray< Element, 2 >::SetAt(), and istd::TArray< Element, 2 >::SetSizes().
Referenced by imath::TVarMatrix< Element >::operator-().
template<class Element> TVarMatrix<Element> imath::TVarMatrix< Element >::GetTransposed () const
Get transposed matrix.
Referenced by imath::TVarMatrix< Element >::Transpose().
template<class Element > void imath::TVarMatrix< Element >::GetTransposed (TVarMatrix< Element > & result) const [inline]
Get transposed matrix.
Definition at line 459 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::GetAt(), istd::TArray< Element, 2 >::GetSizes(), istd::TArray< Element, 2 >::SetAt(), and istd::TArray< Element, 2 >::SetSizes().
template<class Element > bool imath::TVarMatrix< Element >::GetTriangleDecomposed (TVarMatrix< Element > & result, const TVarMatrix< Element > * matrix2Ptr = NULL, TVarMatrix< Element > * result2Ptr = NULL, int maxColumns = -1, Element minHhNorm = I_BIG_EPSILON) const [inline]
Transform matrix to upper triangle form using method of Householder reflexions.
Parameters:
result triangle matrix.
matrix2Ptr optional source matrix will be transformed using the same reflexions. To realize QR decomposition you can use identity matrix.
result2Ptr optional result object storing transformation of matrix2Ptr.
maxColumns optional maximal number of transformed columns. If it is negative value whole matrix will be transformed.
minHhNorm minimal Hausholder reflexion vector length. If any reflexion vector is shorter this method fails.
Returns:
true if success.
Definition at line 502 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::GetAt(), istd::TArray< Element, 2 >::GetAtRef(), istd::TArray< Element, 2 >::GetSize(), istd::TArray< Element, 2 >::GetSizes(), I_ASSERT, istd::Min(), NULL, and istd::TArray< Element, 2 >::SetAt().
Referenced by imath::TVarMatrix< Element >::GetSolvedLSP().
template<class Element > void imath::TVarMatrix< Element >::InitToIdentity (int size) [inline, virtual]
Create identity matrix.
Definition at line 299 of file TVarMatrix.h.
References imath::TVarMatrix< Element >::Clear(), istd::TArray< Element, 2 >::SetAt(), and istd::TArray< Element, 2 >::SetSizes().
template<class Element> bool imath::TVarMatrix< Element >::operator!= (const TVarMatrix< Element > & matrix) const
template<class Element > TVarMatrix< Element > imath::TVarMatrix< Element >::operator* (Element value) const [inline]
Definition at line 231 of file TVarMatrix.h.
References imath::TVarMatrix< Element >::GetScaled().
template<class Element > TVarMatrix< Element > imath::TVarMatrix< Element >::operator* (const TVarMatrix< Element > & b) const [inline]
Definition at line 220 of file TVarMatrix.h.
References imath::TVarMatrix< Element >::GetMultiplied().
template<class Element > TVarMatrix< Element > imath::TVarMatrix< Element >::operator+ (const TVarMatrix< Element > & b) const [inline]
Definition at line 187 of file TVarMatrix.h.
References imath::TVarMatrix< Element >::GetAdded().
template<class Element > TVarMatrix< Element > imath::TVarMatrix< Element >::operator- () [inline]
Definition at line 209 of file TVarMatrix.h.
References imath::TVarMatrix< Element >::GetNegated().
template<class Element > TVarMatrix< Element > imath::TVarMatrix< Element >::operator- (const TVarMatrix< Element > & b) const [inline]
Definition at line 198 of file TVarMatrix.h.
References imath::TVarMatrix< Element >::GetSubstracted().
template<class Element> bool imath::TVarMatrix< Element >::operator== (const TVarMatrix< Element > & matrix) const
template<class Element > bool imath::TVarMatrix< Element >::Serialize (iser::IArchive & archive) [inline]
Definition at line 672 of file TVarMatrix.h.
References istd::TArray< Element, 2 >::Begin(), iser::IArchive::BeginTag(), istd::TArray< Element, 2 >::End(), iser::IArchive::EndTag(), istd::TArray< Element, 2 >::GetSizes(), iser::IArchive::IsStoring(), and istd::TArray< Element, 2 >::SetSizes().
template<class Element> bool imath::TVarMatrix< Element >::TransformR (int firstPartWidth)
Transform this matrix in place.
template<class Element > void imath::TVarMatrix< Element >::Transpose () [inline]
Transpose matrix.
Definition at line 176 of file TVarMatrix.h.
References imath::TVarMatrix< Element >::GetTransposed().
The documentation for this class was generated from the following file:
E:/Work/Projects/Developement/Acf/Include/imath/TVarMatrix.h