ACF: istd::TOptPointerVector< Pointer > Class Template Reference
istd::TOptPointerVector< Pointer > Class Template Reference
Implementation of a special pointer container, which controls the live cycle of the pointer object, but allows optional pointer removing.
#include <TOptPointerVector.h>
Public Types
typedef TPointerVector
< Pointer, TOptDeleteAdapter
< Pointer > > BaseClass
Public Member Functions
void SetAt (int index, Pointer *pointer, bool releaseFlag=false)
void PushBack (Pointer *pointer, bool releaseFlag=false)
void InsertAt (int index, Pointer *pointer, bool releaseFlag=false)
Detailed Description
template<typename Pointer>
class istd::TOptPointerVector< Pointer >
Implementation of a special pointer container, which controls the live cycle of the pointer object, but allows optional pointer removing.
Definition at line 49 of file TOptPointerVector.h.
Member Typedef Documentation
template<typename Pointer> typedef TPointerVector<Pointer, TOptDeleteAdapter<Pointer> > istd::TOptPointerVector< Pointer >::BaseClass
Definition at line 52 of file TOptPointerVector.h.
Member Function Documentation
template<typename Pointer> void istd::TOptPointerVector< Pointer >::InsertAt (int index, Pointer * pointer, bool releaseFlag = false) [inline]
Definition at line 85 of file TOptPointerVector.h.
References istd::TPointerVector< Pointer, TOptDeleteAdapter< Pointer > >::InsertElementAt(), istd::TOptDeleteAdapter< Pointer >::ElementType::pointer, and istd::TOptDeleteAdapter< Pointer >::ElementType::releaseFlag.
template<typename Pointer> void istd::TOptPointerVector< Pointer >::PushBack (Pointer * pointer, bool releaseFlag = false) [inline]
Definition at line 74 of file TOptPointerVector.h.
References istd::TOptDeleteAdapter< Pointer >::ElementType::pointer, istd::TPointerVector< Pointer, TOptDeleteAdapter< Pointer > >::PushBack(), and istd::TOptDeleteAdapter< Pointer >::ElementType::releaseFlag.
template<typename Pointer> void istd::TOptPointerVector< Pointer >::SetAt (int index, Pointer * pointer, bool releaseFlag = false) [inline]
Definition at line 63 of file TOptPointerVector.h.
References istd::TOptDeleteAdapter< Pointer >::ElementType::pointer, istd::TOptDeleteAdapter< Pointer >::ElementType::releaseFlag, and istd::TPointerVector< Pointer, TOptDeleteAdapter< Pointer > >::SetElementAt().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/istd/TOptPointerVector.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy