istd::TRanges< ValueType > Class Template Reference
istd::TRanges< ValueType > Class Template Reference
Set of ranges.
#include <TRanges.h>
Public Types
typedef QList< TRange
< ValueType > > RangeList
typedef std::set< ValueType > SwitchPoints
Public Member Functions
TRanges ()
Default constructor initializing this set to be empty.
void Reset ()
Set this set to be empty.
bool IsEmpty () const
Check if this set is empty.
const SwitchPoints & GetSwitchPoints () const
Get stored switch points.
SwitchPoints & GetSwitchPointsRef ()
Allows access to stored switch points.
void InsertSwitchPoint (ValueType point)
Insert new switch point.
bool GetBeginState () const
Get begin state.
void SetBeginState (bool state)
Set begin state.
bool IsInside (ValueType point) const
Check if some point belongs to set.
bool IsInside (const TRange< ValueType > &range) const
Check if some range belongs to set.
bool IsInside (const TRanges< ValueType > &rangesList) const
Check if some other set belongs to this set.
TRanges< ValueType > GetUnion (const TRanges< ValueType > &rangesList) const
Get union of two range list.
void GetUnion (const TRanges< ValueType > &rangesList, TRanges< ValueType > &result) const
Get union of two range lists.
void Union (const TRanges< ValueType > &rangesList)
Calculate union of this range list and the other one.
void Union (const TRange< ValueType > &range, bool isInverted=false)
Calculate union of this range list and some range.
TRanges< ValueType > GetIntersection (const TRanges< ValueType > &rangesList) const
Get intersection of two range list.
void GetIntersection (const TRanges< ValueType > &rangesList, TRanges< ValueType > &result) const
Get intersection of two range lists.
void Intersection (const TRanges< ValueType > &rangesList)
Calculate intersection of this range list and the other one.
void Intersection (const TRange< ValueType > &range, bool isInverted=false)
Calculate intersection of this range list and some range.
void Erosion (ValueType value)
Calculate erosion of this range list.
void Dilatation (ValueType value)
Calculate dilatation of this range list.
void RemoveGaps (ValueType value, bool gapState=false)
Remove gaps with some length.
void ShiftRanges (ValueType offset)
ShiftRanges all points in this set using specified offset.
void GetAsList (const TRange< ValueType > &range, RangeList &result) const
Get this set as list of istd::TRange objects.
Detailed Description
template<typename ValueType>
class istd::TRanges< ValueType >
Set of ranges.
This set is defined by initial begin state (state of minuns infinity) and list of state switch points. Example given, set [10, 20) is represented as begin state false, and two switch points: at 10 and 20.
Definition at line 25 of file TRanges.h.
Member Typedef Documentation
template<typename ValueType> typedef QList< TRange<ValueType> > istd::TRanges< ValueType >::RangeList
Definition at line 28 of file TRanges.h.
template<typename ValueType> typedef std::set<ValueType> istd::TRanges< ValueType >::SwitchPoints
Definition at line 29 of file TRanges.h.
Constructor & Destructor Documentation
template<typename ValueType > istd::TRanges< ValueType >::TRanges ()
Default constructor initializing this set to be empty.
Definition at line 177 of file TRanges.h.
Member Function Documentation
template<typename ValueType > void istd::TRanges< ValueType >::Dilatation (ValueType value)
Calculate dilatation of this range list.
Erosion prolongs the ends of each range with some value. Result is stored in this object.
Definition at line 704 of file TRanges.h.
template<typename ValueType > void istd::TRanges< ValueType >::Erosion (ValueType value)
Calculate erosion of this range list.
Erosion shortens the ends of each range with some value. Result is stored in this object.
Definition at line 646 of file TRanges.h.
template<typename ValueType > void istd::TRanges< ValueType >::GetAsList (const TRange< ValueType > & range, RangeList & result) const
Get this set as list of istd::TRange objects.
Parameters:
range enclosing range. Must be provided becouse this set can represent values inclusive infinities.
Definition at line 738 of file TRanges.h.
References istd::TRange< ValueType >::GetMaxValue(), and istd::TRange< ValueType >::GetMinValue().
template<typename ValueType > bool istd::TRanges< ValueType >::GetBeginState () const
Get begin state.
It is true, if values before first switch point belongs to set or not.
Definition at line 223 of file TRanges.h.
template<typename ValueType > TRanges< ValueType > istd::TRanges< ValueType >::GetIntersection (const TRanges< ValueType > & rangesList) const
Get intersection of two range list.
Definition at line 507 of file TRanges.h.
template<typename ValueType > void istd::TRanges< ValueType >::GetIntersection (const TRanges< ValueType > & rangesList, TRanges< ValueType > & result) const
Get intersection of two range lists.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 518 of file TRanges.h.
template<typename ValueType > const TRanges< ValueType >::SwitchPoints & istd::TRanges< ValueType >::GetSwitchPoints () const
Get stored switch points.
Definition at line 199 of file TRanges.h.
template<typename ValueType > TRanges< ValueType >::SwitchPoints & istd::TRanges< ValueType >::GetSwitchPointsRef ()
Allows access to stored switch points.
Definition at line 206 of file TRanges.h.
template<typename ValueType > TRanges< ValueType > istd::TRanges< ValueType >::GetUnion (const TRanges< ValueType > & rangesList) const
Get union of two range list.
Definition at line 324 of file TRanges.h.
template<typename ValueType > void istd::TRanges< ValueType >::GetUnion (const TRanges< ValueType > & rangesList, TRanges< ValueType > & result) const
Get union of two range lists.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 335 of file TRanges.h.
template<typename ValueType > void istd::TRanges< ValueType >::InsertSwitchPoint (ValueType point)
Insert new switch point.
It add the new switch point or remove it, if such switch point exist. Considering interpretation of switch points, it inverts the sets in range (point, infinity).
Definition at line 213 of file TRanges.h.
template<typename ValueType > void istd::TRanges< ValueType >::Intersection (const TRanges< ValueType > & rangesList)
Calculate intersection of this range list and the other one.
Result is stored in this object.
Definition at line 575 of file TRanges.h.
template<typename ValueType > void istd::TRanges< ValueType >::Intersection (const TRange< ValueType > & range, bool isInverted = false)
Calculate intersection of this range list and some range.
Result is stored in this object.
Definition at line 635 of file TRanges.h.
template<typename ValueType > bool istd::TRanges< ValueType >::IsEmpty () const
Check if this set is empty.
This set is empty if no point belongs him.
Definition at line 192 of file TRanges.h.
template<typename ValueType > bool istd::TRanges< ValueType >::IsInside (ValueType point) const
Check if some point belongs to set.
Definition at line 237 of file TRanges.h.
template<typename ValueType > bool istd::TRanges< ValueType >::IsInside (const TRange< ValueType > & range) const
Check if some range belongs to set.
Definition at line 255 of file TRanges.h.
References istd::TRange< ValueType >::GetMaxValue(), and istd::TRange< ValueType >::GetMinValue().
template<typename ValueType > bool istd::TRanges< ValueType >::IsInside (const TRanges< ValueType > & rangesList) const
Check if some other set belongs to this set.
Definition at line 281 of file TRanges.h.
template<typename ValueType > void istd::TRanges< ValueType >::RemoveGaps (ValueType value, bool gapState = false)
Remove gaps with some length.
Parameters:
gapState state interpreted as a gape. If it is false the morphological closing is done, otherwhile the morphological opening.
Definition at line 711 of file TRanges.h.
template<typename ValueType > void istd::TRanges< ValueType >::Reset ()
Set this set to be empty.
Definition at line 184 of file TRanges.h.
template<typename ValueType > void istd::TRanges< ValueType >::SetBeginState (bool state)
Set begin state.
Begin state is true, if values before first switch point belongs to set or not. Changing of begin state inverts the set.
Definition at line 230 of file TRanges.h.
template<typename ValueType > void istd::TRanges< ValueType >::ShiftRanges (ValueType offset)
ShiftRanges all points in this set using specified offset.
Definition at line 725 of file TRanges.h.
template<typename ValueType > void istd::TRanges< ValueType >::Union (const TRanges< ValueType > & rangesList)
Calculate union of this range list and the other one.
Result is stored in this object.
Definition at line 392 of file TRanges.h.
template<typename ValueType > void istd::TRanges< ValueType >::Union (const TRange< ValueType > & range, bool isInverted = false)
Calculate union of this range list and some range.
Result is stored in this object.
Definition at line 452 of file TRanges.h.
References istd::TRange< ValueType >::GetMaxValue(), istd::TRange< ValueType >::GetMinValue(), and istd::TRange< ValueType >::IsEmpty().
The documentation for this class was generated from the following file:
Include/istd/TRanges.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy