ACF: iqt2d::TScenographerCompBase< Observer > Class Template Reference
iqt2d::TScenographerCompBase< Observer > Class Template Reference
#include <TScenographerCompBase.h>
Public Types
typedef icomp::CComponentBase BaseClass
typedef Observer BaseClass2
Public Member Functions
TScenographerCompBase ()
void SetIgnoreChanges (int ignoreUpdateFlags)
Specifiy the flags that will be ignored by the update logic of the scene.
void SetAcceptedMimeTypes (const QStringList &mimeTypes)
Set accepted mime types.
virtual QStringList GetAcceptedMimeIds () const
Get the list of the possible mime IDs, which are accepted by the consumer.
virtual void OnDropFinished (const QMimeData &mimeData, QEvent *eventPtr)
Notification about drop action finish.
virtual void AfterUpdate (imod::IModel *modelPtr, int updateFlags, istd::IPolymorphic *updateParamsPtr)
Protected Member Functions
virtual bool OnDropObject (const QMimeData &data, QGraphicsSceneDragDropEvent *eventPtr)
Event handler for the drop action.
virtual void UpdateScene (int updateFlags)
Update scene according to made changes.
virtual void OnComponentCreated ()
virtual void OnComponentDestroyed ()
Protected Attributes
QGraphicsScene * m_scenePtr
bool m_isUpdating
int m_ignoreUpdateFlags
QStringList m_acceptedMimeTypes
Detailed Description
template<class Observer>
class iqt2d::TScenographerCompBase< Observer >
Definition at line 24 of file TScenographerCompBase.h.
Member Typedef Documentation
template<class Observer> typedef icomp::CComponentBase iqt2d::TScenographerCompBase< Observer >::BaseClass
Reimplemented in icmpstr::CVisualRegistryScenographerComp.
Definition at line 31 of file TScenographerCompBase.h.
template<class Observer> typedef Observer iqt2d::TScenographerCompBase< Observer >::BaseClass2
Definition at line 32 of file TScenographerCompBase.h.
Constructor & Destructor Documentation
template<class Observer > iqt2d::TScenographerCompBase< Observer >::TScenographerCompBase () [inline]
Definition at line 96 of file TScenographerCompBase.h.
Member Function Documentation
template<class Observer > void iqt2d::TScenographerCompBase< Observer >::AfterUpdate (imod::IModel * modelPtr, int updateFlags, istd::IPolymorphic * updateParamsPtr) [inline, virtual]
Definition at line 141 of file TScenographerCompBase.h.
References iqt2d::TScenographerCompBase< Observer >::m_ignoreUpdateFlags, iqt2d::TScenographerCompBase< Observer >::m_isUpdating, iqt2d::TScenographerCompBase< Observer >::m_scenePtr, NULL, and iqt2d::TScenographerCompBase< Observer >::UpdateScene().
template<class Observer > QStringList iqt2d::TScenographerCompBase< Observer >::GetAcceptedMimeIds () const [inline, virtual]
Get the list of the possible mime IDs, which are accepted by the consumer.
Implements iqtgui::IDropConsumer.
Definition at line 122 of file TScenographerCompBase.h.
References iqt2d::TScenographerCompBase< Observer >::m_acceptedMimeTypes.
template<class Observer > void iqt2d::TScenographerCompBase< Observer >::OnComponentCreated () [inline, protected, virtual]
Reimplemented from icomp::CComponentBase.
Reimplemented in icmpstr::CVisualRegistryScenographerComp.
Definition at line 179 of file TScenographerCompBase.h.
References I_ASSERT, iqt2d::TScenographerCompBase< Observer >::m_scenePtr, NULL, and icomp::CComponentBase::OnComponentCreated().
template<class Observer > void iqt2d::TScenographerCompBase< Observer >::OnComponentDestroyed () [inline, protected, virtual]
Reimplemented from icomp::CComponentBase.
Reimplemented in icmpstr::CVisualRegistryScenographerComp.
Definition at line 192 of file TScenographerCompBase.h.
References iqt2d::TScenographerCompBase< Observer >::m_scenePtr, and NULL.
template<class Observer > void iqt2d::TScenographerCompBase< Observer >::OnDropFinished (const QMimeData & mimeData, QEvent * eventPtr) [inline, virtual]
Notification about drop action finish.
Implements iqtgui::IDropConsumer.
Definition at line 129 of file TScenographerCompBase.h.
References NULL, and iqt2d::TScenographerCompBase< Observer >::OnDropObject().
template<class Observer > bool iqt2d::TScenographerCompBase< Observer >::OnDropObject (const QMimeData & data, QGraphicsSceneDragDropEvent * eventPtr) [inline, protected, virtual]
Event handler for the drop action.
Default implementation does nothing.
Reimplemented in icmpstr::CVisualRegistryScenographerComp.
Definition at line 164 of file TScenographerCompBase.h.
Referenced by iqt2d::TScenographerCompBase< Observer >::OnDropFinished().
template<class Observer > void iqt2d::TScenographerCompBase< Observer >::SetAcceptedMimeTypes (const QStringList & mimeTypes) [inline]
Set accepted mime types.
For this types drag'n'drop functionality is enabled.
Definition at line 113 of file TScenographerCompBase.h.
References iqt2d::TScenographerCompBase< Observer >::m_acceptedMimeTypes.
template<class Observer > void iqt2d::TScenographerCompBase< Observer >::SetIgnoreChanges (int ignoreUpdateFlags) [inline]
Specifiy the flags that will be ignored by the update logic of the scene.
Definition at line 106 of file TScenographerCompBase.h.
References iqt2d::TScenographerCompBase< Observer >::m_ignoreUpdateFlags.
template<class Observer > void iqt2d::TScenographerCompBase< Observer >::UpdateScene (int updateFlags) [inline, protected, virtual]
Update scene according to made changes.
Default implementation does nothing.
Reimplemented in icmpstr::CVisualRegistryScenographerComp.
Definition at line 171 of file TScenographerCompBase.h.
Referenced by iqt2d::TScenographerCompBase< Observer >::AfterUpdate().
Member Data Documentation
template<class Observer> QStringList iqt2d::TScenographerCompBase< Observer >::m_acceptedMimeTypes [protected]
Definition at line 88 of file TScenographerCompBase.h.
Referenced by iqt2d::TScenographerCompBase< Observer >::GetAcceptedMimeIds(), and iqt2d::TScenographerCompBase< Observer >::SetAcceptedMimeTypes().
template<class Observer> int iqt2d::TScenographerCompBase< Observer >::m_ignoreUpdateFlags [protected]
Definition at line 86 of file TScenographerCompBase.h.
Referenced by iqt2d::TScenographerCompBase< Observer >::AfterUpdate(), and iqt2d::TScenographerCompBase< Observer >::SetIgnoreChanges().
template<class Observer> bool iqt2d::TScenographerCompBase< Observer >::m_isUpdating [protected]
Definition at line 84 of file TScenographerCompBase.h.
Referenced by iqt2d::TScenographerCompBase< Observer >::AfterUpdate().
template<class Observer> QGraphicsScene* iqt2d::TScenographerCompBase< Observer >::m_scenePtr [protected]
Definition at line 82 of file TScenographerCompBase.h.
Referenced by iqt2d::TScenographerCompBase< Observer >::AfterUpdate(), iqt2d::TScenographerCompBase< Observer >::OnComponentCreated(), and iqt2d::TScenographerCompBase< Observer >::OnComponentDestroyed().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iqt2d/TScenographerCompBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy