icomp::IComponentContext Class Reference
icomp::IComponentContext Class Reference abstract
Component concept
Provide session context of component.
#include <IComponentContext.h>
Public Member Functions
virtual const QByteArray & GetContextId () const =0
Get ID of this component in the context tree.
virtual const IRegistryElement & GetRegistryElement () const =0
Get access to component registry element object.
virtual const
IComponentStaticInfo & GetStaticInfo () const =0
Get component static info associated with this context.
virtual const IComponentContext * GetParentContext () const =0
Get access to parent component context.
virtual const iser::IObject * GetAttribute (const QByteArray &attributeId, int *definitionLevelPtr=NULL) const =0
Get attribute using its ID.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Detailed Description
Provide session context of component.
The session contexts has one parent and they build a tree, where the root of this tree describes main component of framework. Session context provides individual set of attributes generated from icomp::IRegistryElement objects. For static components each component instance has own context object. For dynamic components all components using the same factory have the same session context instance.
Definition at line 33 of file IComponentContext.h.
Member Function Documentation
virtual const iser::IObject* icomp::IComponentContext::GetAttribute (const QByteArray & attributeId, int * definitionLevelPtr = NULL) const pure virtual
Get attribute using its ID.
Parameters
attributeId ID of attribute.
definitionLevelPtr optional return value. This will be set to number parents you have to iterate to get component where this attribute was defined. If this attribute was defined in actual component it equals 0.
Implemented in icomp::CSimComponentContextBase, and icomp::CComponentContext.
Referenced by icomp::TMultiAttributeMemberBase< Attribute >::InitInternal(), and icomp::TAttributeMemberBase< Attribute >::InitInternal().
virtual const QByteArray& icomp::IComponentContext::GetContextId () const pure virtual
Get ID of this component in the context tree.
This should be unique for all elements in the same tree level.
Implemented in icomp::TSimComponentWrap< Base >, and icomp::CComponentContext.
Referenced by ibase::TModelObserverCompWrap< ObserverComponent >::OnComponentCreated().
virtual const IComponentContext* icomp::IComponentContext::GetParentContext () const pure virtual
Get access to parent component context.
Implemented in icomp::CSimComponentContextBase, and icomp::CComponentContext.
virtual const IRegistryElement& icomp::IComponentContext::GetRegistryElement () const pure virtual
Get access to component registry element object.
State of the component context is based on this registry element (part of registry document describing component) and context parent.
Implemented in icomp::CSimComponentContextBase, and icomp::CComponentContext.
virtual const IComponentStaticInfo& icomp::IComponentContext::GetStaticInfo () const pure virtual
Get component static info associated with this context.
Implemented in icomp::CSimComponentContextBase, and icomp::CComponentContext.
The documentation for this class was generated from the following file:
Include/icomp/IComponentContext.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy