imath::CComplexDoubleManip Class Reference
imath::CComplexDoubleManip Class Reference
#include <CComplexDoubleManip.h>
Public Types
typedef CFixedPointManip BaseClass
Public Types inherited from imath::CFixedPointManip
enum RoundingType { RT_NORMAL, RT_FLOOR, RT_CEIL, RT_LAST = RT_CEIL + 1 }
typedef CDoubleManip BaseClass
Public Member Functions
CComplexDoubleManip (int precision=1, RoundingType roundingType=RT_NORMAL, double scaleFactor=1.0, double offset=0.0, const istd::CRange &range=istd::CRange(std::numeric_limits< double >::min(), std::numeric_limits< double >::max()))
const istd::CRange & GetRange () const
void SetRange (const istd::CRange &range)
double GetScaleFactor () const
void SetScaleFactor (double value)
double GetOffset () const
void SetOffset (double value)
void SetPrecision (int precision)
virtual QString GetString (const double &value) const
Get this value as string.
virtual bool GetParsed (const QString &text, double &result) const
Get value converted from string.
Public Member Functions inherited from imath::CFixedPointManip
CFixedPointManip (int precision=1, RoundingType roundingType=RT_NORMAL)
void SetPrecision (int precision)
Set fixed point precision.
RoundingType GetRoundingType () const
Get type of rounding.
void SetRoundingType (RoundingType roundingType)
Set type of rounding.
virtual int GetPrecision () const
Get number of digits after point.
virtual double GetRounded (const double &value) const
Get the nearest value rounded used this arithmetik.
virtual bool IsEqual (const double &value1, const double &value2) const
Compare two values and check, if there are equal.
virtual bool IsSmaller (const double &value1, const double &value2) const
Compare two values and check, if first one is smaller as the second.
virtual bool IsSmallerEqual (const double &value1, const double &value2) const
Compare two values and check, if first one is smaller or equal as the second.
virtual double GetSmallerValue (const double &value) const
Return biggest value smaller that specified one.
virtual double GetBiggerValue (const double &value) const
Return smallest value bigger that specified one.
Public Member Functions inherited from imath::CDoubleManip
CDoubleManip ()
char GetPointChar () const
Get point character.
void SetPointChar (char pointChar)
Set point character.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Protected Member Functions
virtual qint32 GetInternalValue (double value) const
Protected Member Functions inherited from imath::CFixedPointManip
virtual double GetNormalValue (qint32 intValue) const
QString GetString (const double &value, int precision) const
Additional Inherited Members
Protected Types inherited from imath::CFixedPointManip
typedef int(* RoundingFuntionPtr)(qreal value)
Protected Types inherited from imath::CDoubleManip
enum { PRECISION = 6 }
Detailed Description
Definition at line 18 of file CComplexDoubleManip.h.
Member Typedef Documentation
typedef CFixedPointManip imath::CComplexDoubleManip::BaseClass
Definition at line 21 of file CComplexDoubleManip.h.
Constructor & Destructor Documentation
imath::CComplexDoubleManip::CComplexDoubleManip (int precision = 1, RoundingType roundingType = RT_NORMAL, double scaleFactor = 1.0, double offset = 0.0, const istd::CRange & range = istd::CRange(std::numeric_limits< double >::min(), std::numeric_limits< double >::max()))
Member Function Documentation
virtual qint32 imath::CComplexDoubleManip::GetInternalValue (double value) const protected virtual
Reimplemented from imath::CFixedPointManip.
double imath::CComplexDoubleManip::GetOffset () const inline
Definition at line 87 of file CComplexDoubleManip.h.
virtual bool imath::CComplexDoubleManip::GetParsed (const QString & text, double & result) const virtual
Get value converted from string.
Parameters
text input string.
result result value.
Returns
true if success.
Reimplemented from imath::CFixedPointManip.
const istd::CRange & imath::CComplexDoubleManip::GetRange () const inline
Definition at line 61 of file CComplexDoubleManip.h.
double imath::CComplexDoubleManip::GetScaleFactor () const inline
Definition at line 73 of file CComplexDoubleManip.h.
virtual QString imath::CComplexDoubleManip::GetString (const double & value) const virtual
Get this value as string.
Parameters
value value will be converted.
Reimplemented from imath::CFixedPointManip.
void imath::CComplexDoubleManip::SetOffset (double value) inline
Definition at line 93 of file CComplexDoubleManip.h.
void imath::CComplexDoubleManip::SetPrecision (int precision) inline
Definition at line 101 of file CComplexDoubleManip.h.
References imath::CFixedPointManip::GetPrecision(), and imath::CFixedPointManip::SetPrecision().
void imath::CComplexDoubleManip::SetRange (const istd::CRange & range) inline
Definition at line 67 of file CComplexDoubleManip.h.
void imath::CComplexDoubleManip::SetScaleFactor (double value) inline
Definition at line 79 of file CComplexDoubleManip.h.
References imath::CFixedPointManip::GetPrecision().
The documentation for this class was generated from the following file:
Include/imath/CComplexDoubleManip.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy