ACF: imod::TModelWrap< Base > Class Template Reference
imod::TModelWrap< Base > Class Template Reference
[Model/Observer concept, Set of helper classes.]
This model wrapper provides a simple connection between a concrete istd::IChangeable implementation and a model.
#include <TModelWrap.h>
Public Types
typedef
iser::TCopySerializedWrap
< Base > BaseClass
typedef imod::CModelBase BaseClass2
Public Member Functions
void SetBaseObject (const Base &baseObject)
virtual int GetSupportedOperations () const
virtual istd::IChangeable * CloneMe () const
Protected Member Functions
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Detailed Description
template<class Base>
class imod::TModelWrap< Base >
This model wrapper provides a simple connection between a concrete istd::IChangeable implementation and a model.
Definition at line 25 of file TModelWrap.h.
Member Typedef Documentation
template<class Base > typedef iser::TCopySerializedWrap<Base> imod::TModelWrap< Base >::BaseClass
Reimplemented from iser::TCopySerializedWrap< Base >.
Reimplemented in icomp::TModelCompWrap< Base >.
Definition at line 28 of file TModelWrap.h.
template<class Base > typedef imod::CModelBase imod::TModelWrap< Base >::BaseClass2
Definition at line 29 of file TModelWrap.h.
Member Function Documentation
template<class Base > istd::IChangeable * imod::TModelWrap< Base >::CloneMe () const [inline, virtual]
Reimplemented in icomp::TComponentCloneWrap< imod::TModelWrap< Base > >.
Definition at line 70 of file TModelWrap.h.
References NULL, and istd::TDelPtr< Type, Accessor >::PopPtr().
template<class Base > int imod::TModelWrap< Base >::GetSupportedOperations () const [inline, virtual]
Definition at line 56 of file TModelWrap.h.
References istd::IChangeable::SO_CLONE, istd::IChangeable::SO_COPY, and istd::IChangeable::SO_OBSERVE.
template<class Base > void imod::TModelWrap< Base >::OnBeginChanges (int changeFlags, istd::IPolymorphic * changeParamsPtr) [inline, protected, virtual]
Definition at line 87 of file TModelWrap.h.
References imod::CModelBase::NotifyBeforeUpdate().
template<class Base > void imod::TModelWrap< Base >::OnEndChanges (int changeFlags, istd::IPolymorphic * changeParamsPtr) [inline, protected, virtual]
Definition at line 96 of file TModelWrap.h.
References imod::CModelBase::NotifyAfterUpdate().
template<class Base > void imod::TModelWrap< Base >::SetBaseObject (const Base & baseObject) [inline]
Definition at line 47 of file TModelWrap.h.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/imod/TModelWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy