ibase::TFactorisableContainer< InterfaceClass > Class Template Reference
ibase::TFactorisableContainer< InterfaceClass > Class Template Reference
Specific container implementation for factorisable items.
#include <TFactorisableContainer.h>
Public Types
typedef QPair< istd::TSmartPtr
< InterfaceClass >, QByteArray > ItemClass
typedef
ibase::TSerializableContainer
< ItemClass > BaseClass
Public Types inherited from ibase::TSerializableContainer< QPair< istd::TSmartPtr< InterfaceClass >, QByteArray > >
typedef TContainer< QPair
< istd::TSmartPtr
< InterfaceClass >, QByteArray > > BaseClass
Public Types inherited from ibase::TContainer< QPair< istd::TSmartPtr< InterfaceClass >, QByteArray > >
enum ChangeFlags
Public Types inherited from istd::IChangeable
enum ChangeFlags {
CF_ACF_INTERNAL = 1 << 0, CF_MODEL = 1 << 1, CF_ABORTED = 1 << 2, CF_DELEGATED = 1 << 3,
CF_NO_UNDO = 1 << 5
}
enum SupportedOperations {
SO_NONE = 0, SO_OBSERVE = 1, SO_COPY = 2, SO_CLONE = 4,
SO_COMPARE = 8
}
Flags for supported operations.
enum CompatibilityMode { CM_STRICT, CM_WITHOUT_REFS, CM_WITH_REFS, CM_CONVERT }
Control how relationship betweeen objects are interpreted.
Public Member Functions
TFactorisableContainer ()
virtual ~TFactorisableContainer ()
InterfaceClass * InsertElement (int index, const QByteArray &elementFactoryKey)
Insert an element into the container at given index.
InterfaceClass * AddElement (const QByteArray &elementFactoryKey)
Add an element to the container.
InterfaceClass * GetElement (int elementIndex) const
Gets an element with given index elementIndex from the container.
int GetElementIndex (const InterfaceClass &elementRef) const
Gets the index of given element from the container.
QByteArray GetElementKey (int elementIndex) const
Gets the element key associated with the element with given elementIndex from the container.
void RegisterItemFactory (istd::TIFactory< InterfaceClass > *itemFactoryPtr)
bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
Public Member Functions inherited from ibase::TContainer< QPair< istd::TSmartPtr< InterfaceClass >, QByteArray > >
const QPair< istd::TSmartPtr
< InterfaceClass >, QByteArray > & GetAt (int index) const
QPair< istd::TSmartPtr
< InterfaceClass >, QByteArray > & GetAt (int index)
QPair< istd::TSmartPtr
< InterfaceClass >, QByteArray > & PushBack (const QPair< istd::TSmartPtr< InterfaceClass >, QByteArray > &item)
QPair< istd::TSmartPtr
< InterfaceClass >, QByteArray > & PushFront (const QPair< istd::TSmartPtr< InterfaceClass >, QByteArray > &item)
QPair< istd::TSmartPtr
< InterfaceClass >, QByteArray > & InsertAt (const QPair< istd::TSmartPtr< InterfaceClass >, QByteArray > &item, int index)
void PopBack ()
void PopFront ()
void RemoveAt (int index)
virtual void Reset ()
TContainer & operator= (const TContainer &container)
virtual int GetItemsCount () const
Returns number of elements in the container.
virtual bool IsEmpty () const
Returns a true if container is empty, otherwise a false.
virtual bool IsIndexValid (int index) const
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Public Member Functions inherited from istd::IChangeable
virtual void BeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Starts the change transaction.
virtual void EndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Ends the change transaction.
virtual int GetSupportedOperations () const
Get set of flags for supported operations.
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Copy this object from another one.
virtual bool IsEqual (const IChangeable &object) const
Compare this object with another object.
virtual IChangeable * CloneMe (CompatibilityMode mode=CM_WITHOUT_REFS) const
Make a copy of this object.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Public Member Functions inherited from iser::ISerializable
virtual quint32 GetMinimalVersion (int versionId) const
Get minimal needed version to correct storing of this data.
Protected Member Functions
virtual InterfaceClass * CreateElement (const QByteArray &itemKey)
virtual void OnElementCreated (InterfaceClass *elementPtr)
virtual bool SerializeItem (ItemClass &item, iser::IArchive &archive)
Serialize a single item in the container.
Protected Member Functions inherited from istd::IChangeable
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for begin change event.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for end change event.
Protected Attributes
istd::TIFactory< InterfaceClass > * m_itemFactoryPtr
Protected Attributes inherited from ibase::TContainer< QPair< istd::TSmartPtr< InterfaceClass >, QByteArray > >
Items m_items
Additional Inherited Members
Protected Types inherited from ibase::TContainer< QPair< istd::TSmartPtr< InterfaceClass >, QByteArray > >
typedef QList< QPair
< istd::TSmartPtr
< InterfaceClass >, QByteArray > > Items
Detailed Description
template<class InterfaceClass>
class ibase::TFactorisableContainer< InterfaceClass >
Specific container implementation for factorisable items.
This container implementation supports following features:
Automatic memory management for created items
Serialization mechanism with automatic item allocation.
Definition at line 27 of file TFactorisableContainer.h.
Member Typedef Documentation
template<class InterfaceClass > typedef ibase::TSerializableContainer<ItemClass> ibase::TFactorisableContainer< InterfaceClass >::BaseClass
Definition at line 33 of file TFactorisableContainer.h.
template<class InterfaceClass > typedef QPair<istd::TSmartPtr<InterfaceClass>, QByteArray> ibase::TFactorisableContainer< InterfaceClass >::ItemClass
Definition at line 32 of file TFactorisableContainer.h.
Constructor & Destructor Documentation
template<class InterfaceClass > ibase::TFactorisableContainer< InterfaceClass >::TFactorisableContainer ()
Definition at line 83 of file TFactorisableContainer.h.
References NULL.
template<class InterfaceClass > ibase::TFactorisableContainer< InterfaceClass >::~TFactorisableContainer () virtual
Definition at line 90 of file TFactorisableContainer.h.
Member Function Documentation
template<class InterfaceClass > InterfaceClass * ibase::TFactorisableContainer< InterfaceClass >::AddElement (const QByteArray & elementFactoryKey)
Add an element to the container.
Definition at line 97 of file TFactorisableContainer.h.
References istd::TTransPtr< Type >::GetPtr(), and istd::TTransPtr< Type >::IsValid().
template<class InterfaceClass > InterfaceClass * ibase::TFactorisableContainer< InterfaceClass >::CreateElement (const QByteArray & itemKey) protected virtual
Definition at line 227 of file TFactorisableContainer.h.
References NULL.
template<class InterfaceClass > InterfaceClass * ibase::TFactorisableContainer< InterfaceClass >::GetElement (int elementIndex) const
Gets an element with given index elementIndex from the container.
You will need this function, because the GetAt() returns an ItemClass instance, which is not usable.
Definition at line 121 of file TFactorisableContainer.h.
References NULL.
template<class InterfaceClass > int ibase::TFactorisableContainer< InterfaceClass >::GetElementIndex (const InterfaceClass & elementRef) const
Gets the index of given element from the container.
Definition at line 132 of file TFactorisableContainer.h.
template<class InterfaceClass > QByteArray ibase::TFactorisableContainer< InterfaceClass >::GetElementKey (int elementIndex) const
Gets the element key associated with the element with given elementIndex from the container.
Definition at line 146 of file TFactorisableContainer.h.
template<class InterfaceClass > InterfaceClass * ibase::TFactorisableContainer< InterfaceClass >::InsertElement (int index, const QByteArray & elementFactoryKey)
Insert an element into the container at given index.
Definition at line 109 of file TFactorisableContainer.h.
References istd::TTransPtr< Type >::GetPtr(), and istd::TTransPtr< Type >::IsValid().
template<class InterfaceClass > void ibase::TFactorisableContainer< InterfaceClass >::OnElementCreated (InterfaceClass * elementPtr) protected virtual
Definition at line 251 of file TFactorisableContainer.h.
template<class InterfaceClass > void ibase::TFactorisableContainer< InterfaceClass >::RegisterItemFactory (istd::TIFactory< InterfaceClass > * itemFactoryPtr)
Definition at line 157 of file TFactorisableContainer.h.
template<class InterfaceClass > bool ibase::TFactorisableContainer< InterfaceClass >::Serialize (iser::IArchive & archive) virtual
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See Also
iser::IArchive
Reimplemented from ibase::TSerializableContainer< QPair< istd::TSmartPtr< InterfaceClass >, QByteArray > >.
Definition at line 166 of file TFactorisableContainer.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), NULL, and iser::IArchive::Process().
template<class InterfaceClass > bool ibase::TFactorisableContainer< InterfaceClass >::SerializeItem (ItemClass & item, iser::IArchive & archive) protected virtual
Serialize a single item in the container.
Implements ibase::TSerializableContainer< QPair< istd::TSmartPtr< InterfaceClass >, QByteArray > >.
Definition at line 259 of file TFactorisableContainer.h.
References NULL, and iser::ISerializable::Serialize().
Member Data Documentation
template<class InterfaceClass > istd::TIFactory<InterfaceClass>* ibase::TFactorisableContainer< InterfaceClass >::m_itemFactoryPtr protected
Definition at line 78 of file TFactorisableContainer.h.
The documentation for this class was generated from the following file:
Include/ibase/TFactorisableContainer.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy