ACF: ibase::TMessageContainerWrap< Base > Class Template Reference
ibase::TMessageContainerWrap< Base > Class Template Reference
Basic implementation of a message container.
#include <TMessageContainerWrap.h>
Public Types
typedef
ibase::THierarchicalBase< Base > BaseClass
Public Member Functions
TMessageContainerWrap ()
virtual ~TMessageContainerWrap ()
virtual void AddChildContainer (ibase::IMessageContainer *childContainerPtr)
virtual bool Serialize (iser::IArchive &archive)
virtual void SetMaxMessageCount (int maxMessageCount=-1)
virtual void SetMaxLiveTime (int maxLiveTime=-1)
virtual int GetWorstCategory () const
virtual
ibase::IMessageContainer::Messages GetMessages () const
virtual void ClearMessages ()
virtual bool IsMessageSupported (int messageCategory=-1, int messageId=-1, const IMessage *messagePtr=NULL) const
virtual void AddMessage (const ibase::IMessageContainer::MessagePtr &messagePtr)
virtual int GetChildsCount () const
virtual ibase::IMessageContainer * GetChild (int index) const
Protected Types
typedef std::list
< ibase::IMessageContainer::MessagePtr > MessageList
Protected Attributes
MessageList m_messages
int m_worstCategory
Detailed Description
template<class Base>
class ibase::TMessageContainerWrap< Base >
Basic implementation of a message container.
Definition at line 28 of file TMessageContainerWrap.h.
Member Typedef Documentation
template<class Base > typedef ibase::THierarchicalBase<Base> ibase::TMessageContainerWrap< Base >::BaseClass
Reimplemented from ibase::THierarchicalBase< Base >.
Reimplemented in ibase::CLogComp.
Definition at line 31 of file TMessageContainerWrap.h.
template<class Base > typedef std::list<ibase::IMessageContainer::MessagePtr> ibase::TMessageContainerWrap< Base >::MessageList [protected]
Definition at line 60 of file TMessageContainerWrap.h.
Constructor & Destructor Documentation
template<class Base > ibase::TMessageContainerWrap< Base >::TMessageContainerWrap () [inline]
Definition at line 77 of file TMessageContainerWrap.h.
template<class Base > ibase::TMessageContainerWrap< Base >::~TMessageContainerWrap () [inline, virtual]
Definition at line 86 of file TMessageContainerWrap.h.
References ibase::TMessageContainerWrap< Base >::ClearMessages().
Member Function Documentation
template<class Base > void ibase::TMessageContainerWrap< Base >::AddChildContainer (ibase::IMessageContainer * childContainerPtr) [inline, virtual]
Definition at line 93 of file TMessageContainerWrap.h.
References I_ASSERT, and NULL.
template<class Base > void ibase::TMessageContainerWrap< Base >::AddMessage (const ibase::IMessageContainer::MessagePtr & messagePtr) [inline, virtual]
Definition at line 230 of file TMessageContainerWrap.h.
References ibase::IMessageContainer::CF_MESSAGE_ADDED, ibase::IMessageContainer::CF_MESSAGE_REMOVED, istd::TTransPtr< Type >::GetPtr(), I_ASSERT, istd::TTransPtr< Type >::IsValid(), ibase::TMessageContainerWrap< Base >::m_messages, and ibase::TMessageContainerWrap< Base >::m_worstCategory.
template<class Base > void ibase::TMessageContainerWrap< Base >::ClearMessages () [inline, virtual]
Definition at line 275 of file TMessageContainerWrap.h.
References ibase::IMessageContainer::CF_RESET, ibase::TMessageContainerWrap< Base >::m_messages, and ibase::TMessageContainerWrap< Base >::m_worstCategory.
Referenced by ibase::TMessageContainerWrap< Base >::~TMessageContainerWrap().
template<class Base > ibase::IMessageContainer * ibase::TMessageContainerWrap< Base >::GetChild (int index) const [inline, virtual]
Reimplemented from ibase::THierarchicalBase< Base >.
Definition at line 295 of file TMessageContainerWrap.h.
References I_ASSERT.
Referenced by ibase::TMessageContainerWrap< Base >::GetMessages(), and ibase::TMessageContainerWrap< Base >::GetWorstCategory().
template<class Base > int ibase::TMessageContainerWrap< Base >::GetChildsCount () const [inline, virtual]
Reimplemented from ibase::THierarchicalBase< Base >.
Definition at line 288 of file TMessageContainerWrap.h.
Referenced by ibase::TMessageContainerWrap< Base >::GetMessages(), and ibase::TMessageContainerWrap< Base >::GetWorstCategory().
template<class Base > ibase::IMessageContainer::Messages ibase::TMessageContainerWrap< Base >::GetMessages () const [inline, virtual]
Definition at line 193 of file TMessageContainerWrap.h.
References ibase::TMessageContainerWrap< Base >::GetChild(), ibase::TMessageContainerWrap< Base >::GetChildsCount(), ibase::IMessageContainer::GetMessages(), I_ASSERT, ibase::TMessageContainerWrap< Base >::m_messages, and NULL.
template<class Base > int ibase::TMessageContainerWrap< Base >::GetWorstCategory () const [inline, virtual]
Definition at line 158 of file TMessageContainerWrap.h.
References ibase::TMessageContainerWrap< Base >::GetChild(), ibase::TMessageContainerWrap< Base >::GetChildsCount(), ibase::IMessageContainer::GetWorstCategory(), ibase::TMessageContainerWrap< Base >::m_messages, ibase::TMessageContainerWrap< Base >::m_worstCategory, and NULL.
template<class Base > bool ibase::TMessageContainerWrap< Base >::IsMessageSupported (int messageCategory = -1, int messageId = -1, const IMessage * messagePtr = NULL) const [inline, virtual]
Definition at line 220 of file TMessageContainerWrap.h.
template<class Base > bool ibase::TMessageContainerWrap< Base >::Serialize (iser::IArchive & archive) [inline, virtual]
Definition at line 104 of file TMessageContainerWrap.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), iser::IArchive::EndTag(), istd::TTransPtr< Type >::GetPtr(), iser::IArchive::IsStoring(), and ibase::TMessageContainerWrap< Base >::m_messages.
template<class Base > void ibase::TMessageContainerWrap< Base >::SetMaxLiveTime (int maxLiveTime = -1) [inline, virtual]
Definition at line 151 of file TMessageContainerWrap.h.
template<class Base > void ibase::TMessageContainerWrap< Base >::SetMaxMessageCount (int maxMessageCount = -1) [inline, virtual]
Definition at line 142 of file TMessageContainerWrap.h.
References I_ASSERT.
Member Data Documentation
template<class Base > MessageList ibase::TMessageContainerWrap< Base >::m_messages [protected]
Definition at line 61 of file TMessageContainerWrap.h.
Referenced by ibase::TMessageContainerWrap< Base >::AddMessage(), ibase::TMessageContainerWrap< Base >::ClearMessages(), ibase::TMessageContainerWrap< Base >::GetMessages(), ibase::TMessageContainerWrap< Base >::GetWorstCategory(), and ibase::TMessageContainerWrap< Base >::Serialize().
template<class Base > int ibase::TMessageContainerWrap< Base >::m_worstCategory [protected]
Definition at line 63 of file TMessageContainerWrap.h.
Referenced by ibase::TMessageContainerWrap< Base >::AddMessage(), ibase::TMessageContainerWrap< Base >::ClearMessages(), and ibase::TMessageContainerWrap< Base >::GetWorstCategory().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/ibase/TMessageContainerWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy