imath::TWeightedNumber< ValueT, WeightT > Class Template Reference
imath::TWeightedNumber< ValueT, WeightT > Class Template Reference
This class implements number with a weight and related arithmetic operations.
#include <TWeightedNumber.h>
Public Types
typedef ValueT ValueType
typedef WeightT WeightType
Public Member Functions
TWeightedNumber ()
TWeightedNumber (const TWeightedNumber< ValueT, WeightT > &value)
TWeightedNumber (const ValueType &sum, const WeightType &weight=1)
void Reset ()
Set this value to unimportant state (weight to 0)
bool IsImportant () const
Checks if this value is importantant.
const ValueType & GetSum () const
Get a sum part of weighted number.
void SetSum (const ValueType &sum)
const WeightType & GetWeight () const
Get a weight part of this number.
void SetWeight (const WeightType &weight)
ValueType GetValue () const
Get a real value of this number.
void Normalize (const WeightType &weight=1)
Set new weight, without change represented value.
TWeightedNumber< ValueT, WeightT > GetNormalized (const WeightType &weight=1) const
void GetNormalized (const WeightType &weight, TWeightedNumber< ValueT, WeightT > &result) const
void Scale (double scale)
TWeightedNumber< ValueT, WeightT > GetScaled (double scale) const
void GetScaled (double scale, TWeightedNumber< ValueT, WeightT > &result) const
void AddSum (ValueType value)
Add a value to sum part.
void AddWeight (WeightType weight)
Add a value to weight part.
void SubSum (ValueType value)
Subtract a value to sum part.
void SubWeight (WeightType weight)
Subtract a value to weight part.
void SimpleAdd (const TWeightedNumber< ValueT, WeightT > &value)
Simple add operation.
TWeightedNumber< ValueT, WeightT > GetSimpleAdd (const TWeightedNumber< ValueT, WeightT > &value) const
Get simple sum.
void GetSimpleAdd (const TWeightedNumber< ValueT, WeightT > &value, TWeightedNumber< ValueT, WeightT > &result) const
Get simple sum.
void SimpleSub (const TWeightedNumber< ValueT, WeightT > &value)
Simple subtraction operation.
TWeightedNumber< ValueT, WeightT > GetSimpleSub (const TWeightedNumber< ValueT, WeightT > &value) const
Get simple sum.
void GetSimpleSub (const TWeightedNumber< ValueT, WeightT > &value, TWeightedNumber< ValueT, WeightT > &result) const
Get simple sum.
void Add (const TWeightedNumber< ValueT, WeightT > &value)
Do addition.
TWeightedNumber< ValueT, WeightT > GetAdd (const TWeightedNumber< ValueT, WeightT > &value) const
Get result of addition.
void GetAdd (const TWeightedNumber< ValueT, WeightT > &value, TWeightedNumber< ValueT, WeightT > &result) const
Get result of addition.
void Sub (const TWeightedNumber< ValueT, WeightT > &value)
Do Subtraction.
TWeightedNumber< ValueT, WeightT > GetSub (const TWeightedNumber< ValueT, WeightT > &value) const
Get result of addition.
void GetSub (const TWeightedNumber< ValueT, WeightT > &value, TWeightedNumber< ValueT, WeightT > &result) const
Get result of addition.
TWeightedNumber< ValueT, WeightT > operator+ (const TWeightedNumber< ValueT, WeightT > &value) const
Calculate simple sum of coefficients.
TWeightedNumber< ValueT, WeightT > operator- (const TWeightedNumber< ValueT, WeightT > &value) const
Calculate simple difference of coefficients.
TWeightedNumber< ValueT, WeightT > operator* (const TWeightedNumber< ValueT, WeightT > &value) const
Calculate simple multiplication of coefficients.
TWeightedNumber< ValueT, WeightT > operator/ (const TWeightedNumber< ValueT, WeightT > &value) const
Calculate simple divide of coefficients.
const TWeightedNumber< ValueT,
WeightT > & operator= (const TWeightedNumber< ValueT, WeightT > &value)
const TWeightedNumber< ValueT,
WeightT > & operator+= (const TWeightedNumber< ValueT, WeightT > &value)
Calculate simple sum of coefficients.
const TWeightedNumber< ValueT,
WeightT > & operator-= (const TWeightedNumber< ValueT, WeightT > &value)
Calculate simple difference of coefficients.
const TWeightedNumber< ValueT,
WeightT > & operator*= (const TWeightedNumber< ValueT, WeightT > &value)
Calculate simple multiplication of coefficients.
const TWeightedNumber< ValueT,
WeightT > & operator/= (const TWeightedNumber< ValueT, WeightT > &value)
Calculate simple divide of coefficients.
bool operator== (const TWeightedNumber< ValueT, WeightT > &number) const
bool operator!= (const TWeightedNumber< ValueT, WeightT > &number) const
TWeightedNumber< ValueT, WeightT > operator+ (ValueType scalar) const
TWeightedNumber< ValueT, WeightT > operator- (ValueType scalar) const
TWeightedNumber< ValueT, WeightT > operator* (double scalar) const
TWeightedNumber< ValueT, WeightT > operator/ (double scalar) const
Detailed Description
template<class ValueT, class WeightT = ValueT>
class imath::TWeightedNumber< ValueT, WeightT >
This class implements number with a weight and related arithmetic operations.
Definition at line 16 of file TWeightedNumber.h.
Member Typedef Documentation
template<class ValueT, class WeightT = ValueT> typedef ValueT imath::TWeightedNumber< ValueT, WeightT >::ValueType
Definition at line 19 of file TWeightedNumber.h.
template<class ValueT, class WeightT = ValueT> typedef WeightT imath::TWeightedNumber< ValueT, WeightT >::WeightType
Definition at line 20 of file TWeightedNumber.h.
Constructor & Destructor Documentation
template<class ValueT , class WeightT > imath::TWeightedNumber< ValueT, WeightT >::TWeightedNumber () [inline]
Definition at line 227 of file TWeightedNumber.h.
template<class ValueT , class WeightT > imath::TWeightedNumber< ValueT, WeightT >::TWeightedNumber (const TWeightedNumber< ValueT, WeightT > & value) [inline]
Definition at line 233 of file TWeightedNumber.h.
template<class ValueT , class WeightT > imath::TWeightedNumber< ValueT, WeightT >::TWeightedNumber (const ValueType & sum, const WeightType & weight = 1) [inline, explicit]
Definition at line 240 of file TWeightedNumber.h.
Member Function Documentation
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::Add (const TWeightedNumber< ValueT, WeightT > & value) [inline]
Do addition.
Please note, that operator+= calculte only simple sum of coefficients.
Definition at line 413 of file TWeightedNumber.h.
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::AddSum (ValueType value) [inline]
Add a value to sum part.
Definition at line 331 of file TWeightedNumber.h.
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::AddWeight (WeightType weight) [inline]
Add a value to weight part.
Definition at line 338 of file TWeightedNumber.h.
template<class ValueT , class WeightT > TWeightedNumber< ValueT, WeightT > imath::TWeightedNumber< ValueT, WeightT >::GetAdd (const TWeightedNumber< ValueT, WeightT > & value) const [inline]
Get result of addition.
Please note, that operator+ calculte only simple sum of coefficients.
Definition at line 421 of file TWeightedNumber.h.
References imath::TWeightedNumber< ValueT, WeightT >::Normalize().
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::GetAdd (const TWeightedNumber< ValueT, WeightT > & value, TWeightedNumber< ValueT, WeightT > & result) const [inline]
Get result of addition.
Please note, that operator+ calculte only simple sum of coefficients.
Definition at line 433 of file TWeightedNumber.h.
References imath::TWeightedNumber< ValueT, WeightT >::Normalize().
template<class ValueT , class WeightT > TWeightedNumber< ValueT, WeightT > imath::TWeightedNumber< ValueT, WeightT >::GetNormalized (const WeightType & weight = 1) const
Definition at line 203 of file TWeightedNumber.h.
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::GetNormalized (const WeightType & weight, TWeightedNumber< ValueT, WeightT > & result) const [inline]
Definition at line 307 of file TWeightedNumber.h.
template<class ValueT , class WeightT > TWeightedNumber< ValueT, WeightT > imath::TWeightedNumber< ValueT, WeightT >::GetScaled (double scale) const
Definition at line 214 of file TWeightedNumber.h.
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::GetScaled (double scale, TWeightedNumber< ValueT, WeightT > & result) const [inline]
Definition at line 323 of file TWeightedNumber.h.
template<class ValueT , class WeightT > TWeightedNumber< ValueT, WeightT > imath::TWeightedNumber< ValueT, WeightT >::GetSimpleAdd (const TWeightedNumber< ValueT, WeightT > & value) const [inline]
Get simple sum.
Please read notes to GetSimpleAdd.
Definition at line 367 of file TWeightedNumber.h.
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::GetSimpleAdd (const TWeightedNumber< ValueT, WeightT > & value, TWeightedNumber< ValueT, WeightT > & result) const [inline]
Get simple sum.
Please read notes to GetSimpleAdd.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 378 of file TWeightedNumber.h.
template<class ValueT , class WeightT > TWeightedNumber< ValueT, WeightT > imath::TWeightedNumber< ValueT, WeightT >::GetSimpleSub (const TWeightedNumber< ValueT, WeightT > & value) const
Get simple sum.
Please read notes to GetSimpleAdd.
Definition at line 394 of file TWeightedNumber.h.
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::GetSimpleSub (const TWeightedNumber< ValueT, WeightT > & value, TWeightedNumber< ValueT, WeightT > & result) const
Get simple sum.
Please read notes to GetSimpleAdd.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 405 of file TWeightedNumber.h.
template<class ValueT , class WeightT > TWeightedNumber< ValueT, WeightT > imath::TWeightedNumber< ValueT, WeightT >::GetSub (const TWeightedNumber< ValueT, WeightT > & value) const [inline]
Get result of addition.
Please note, that operator- calculte only simple sum of coefficients.
Definition at line 449 of file TWeightedNumber.h.
References imath::TWeightedNumber< ValueT, WeightT >::Normalize().
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::GetSub (const TWeightedNumber< ValueT, WeightT > & value, TWeightedNumber< ValueT, WeightT > & result) const [inline]
Get result of addition.
Please note, that operator- calculte only simple sum of coefficients.
Definition at line 461 of file TWeightedNumber.h.
References imath::TWeightedNumber< ValueT, WeightT >::Normalize().
template<class ValueT , class WeightT > const ValueT & imath::TWeightedNumber< ValueT, WeightT >::GetSum () const
Get a sum part of weighted number.
You should to get weight part too, to calculate real value.
Definition at line 263 of file TWeightedNumber.h.
template<class ValueT , class WeightT > TWeightedNumber< ValueT, WeightT >::ValueType imath::TWeightedNumber< ValueT, WeightT >::GetValue () const
Get a real value of this number.
Definition at line 291 of file TWeightedNumber.h.
References I_ASSERT.
template<class ValueT , class WeightT > const TWeightedNumber< ValueT, WeightT >::WeightType & imath::TWeightedNumber< ValueT, WeightT >::GetWeight () const
Get a weight part of this number.
Definition at line 277 of file TWeightedNumber.h.
template<class ValueT , class WeightT > bool imath::TWeightedNumber< ValueT, WeightT >::IsImportant () const [inline]
Checks if this value is importantant.
It is true, of weight is bigger than imath_EPSYLON.
Definition at line 256 of file TWeightedNumber.h.
References I_EPSILON.
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::Normalize (const WeightType & weight = 1) [inline]
Set new weight, without change represented value.
Definition at line 300 of file TWeightedNumber.h.
Referenced by imath::TWeightedNumber< ValueT, WeightT >::GetAdd(), and imath::TWeightedNumber< ValueT, WeightT >::GetSub().
template<class ValueT , class WeightT > bool imath::TWeightedNumber< ValueT, WeightT >::operator!= (const TWeightedNumber< ValueT, WeightT > & number) const [inline]
Definition at line 477 of file TWeightedNumber.h.
template<class ValueT , class WeightT > TWeightedNumber< ValueT, WeightT > imath::TWeightedNumber< ValueT, WeightT >::operator* (const TWeightedNumber< ValueT, WeightT > & value) const [inline]
Calculate simple multiplication of coefficients.
Definition at line 499 of file TWeightedNumber.h.
template<class ValueT , class WeightT > TWeightedNumber< ValueT, WeightT > imath::TWeightedNumber< ValueT, WeightT >::operator* (double scalar) const [inline]
Definition at line 577 of file TWeightedNumber.h.
template<class ValueT , class WeightT > const TWeightedNumber< ValueT, WeightT > & imath::TWeightedNumber< ValueT, WeightT >::operator*= (const TWeightedNumber< ValueT, WeightT > & value) [inline]
Calculate simple multiplication of coefficients.
Definition at line 543 of file TWeightedNumber.h.
template<class ValueT , class WeightT > TWeightedNumber< ValueT, WeightT > imath::TWeightedNumber< ValueT, WeightT >::operator+ (const TWeightedNumber< ValueT, WeightT > & value) const [inline]
Calculate simple sum of coefficients.
Definition at line 485 of file TWeightedNumber.h.
template<class ValueT , class WeightT > imath::TWeightedNumber< ValueT, WeightT > imath::TWeightedNumber< ValueT, WeightT >::operator+ (ValueType scalar) const [inline]
Definition at line 563 of file TWeightedNumber.h.
template<class ValueT , class WeightT > const TWeightedNumber< ValueT, WeightT > & imath::TWeightedNumber< ValueT, WeightT >::operator+= (const TWeightedNumber< ValueT, WeightT > & value) [inline]
Calculate simple sum of coefficients.
Definition at line 523 of file TWeightedNumber.h.
template<class ValueT , class WeightT > TWeightedNumber< ValueT, WeightT > imath::TWeightedNumber< ValueT, WeightT >::operator- (const TWeightedNumber< ValueT, WeightT > & value) const [inline]
Calculate simple difference of coefficients.
Definition at line 492 of file TWeightedNumber.h.
template<class ValueT , class WeightT > imath::TWeightedNumber< ValueT, WeightT > imath::TWeightedNumber< ValueT, WeightT >::operator- (ValueType scalar) const [inline]
Definition at line 570 of file TWeightedNumber.h.
template<class ValueT , class WeightT > const TWeightedNumber< ValueT, WeightT > & imath::TWeightedNumber< ValueT, WeightT >::operator-= (const TWeightedNumber< ValueT, WeightT > & value) [inline]
Calculate simple difference of coefficients.
Definition at line 533 of file TWeightedNumber.h.
template<class ValueT , class WeightT > TWeightedNumber< ValueT, WeightT > imath::TWeightedNumber< ValueT, WeightT >::operator/ (const TWeightedNumber< ValueT, WeightT > & value) const [inline]
Calculate simple divide of coefficients.
Definition at line 506 of file TWeightedNumber.h.
template<class ValueT , class WeightT > imath::TWeightedNumber< ValueT, WeightT > imath::TWeightedNumber< ValueT, WeightT >::operator/ (double scalar) const [inline]
Definition at line 584 of file TWeightedNumber.h.
template<class ValueT , class WeightT > const TWeightedNumber< ValueT, WeightT > & imath::TWeightedNumber< ValueT, WeightT >::operator/= (const TWeightedNumber< ValueT, WeightT > & value) [inline]
Calculate simple divide of coefficients.
Definition at line 553 of file TWeightedNumber.h.
template<class ValueT , class WeightT > const TWeightedNumber< ValueT, WeightT > & imath::TWeightedNumber< ValueT, WeightT >::operator= (const TWeightedNumber< ValueT, WeightT > & value) [inline]
Definition at line 513 of file TWeightedNumber.h.
template<class ValueT , class WeightT > bool imath::TWeightedNumber< ValueT, WeightT >::operator== (const TWeightedNumber< ValueT, WeightT > & number) const [inline]
Definition at line 469 of file TWeightedNumber.h.
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::Reset ()
Set this value to unimportant state (weight to 0)
Definition at line 248 of file TWeightedNumber.h.
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::Scale (double scale) [inline]
Definition at line 315 of file TWeightedNumber.h.
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::SetSum (const ValueType & sum)
Definition at line 270 of file TWeightedNumber.h.
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::SetWeight (const WeightType & weight)
Definition at line 284 of file TWeightedNumber.h.
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::SimpleAdd (const TWeightedNumber< ValueT, WeightT > & value) [inline]
Simple add operation.
Difference between operator+ and this method is, that operator+ return a value with weight which sum of weights is, but this method is faster and returns value with undefined weight, but correct real value. It means, when you are interested only in real value, than you can use this method.
Definition at line 359 of file TWeightedNumber.h.
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::SimpleSub (const TWeightedNumber< ValueT, WeightT > & value)
Simple subtraction operation.
Difference between operator- and this method is, that operator- return a value with weight which sum of weights is, but this is faster and returns value with undefined weight, but correct real value. It means, when you are interested only in real value, than you can use this method.
Definition at line 386 of file TWeightedNumber.h.
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::Sub (const TWeightedNumber< ValueT, WeightT > & value) [inline]
Do Subtraction.
Please note, that operator-= calculte only simple difference of coefficients.
Definition at line 441 of file TWeightedNumber.h.
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::SubSum (ValueType value) [inline]
Subtract a value to sum part.
Definition at line 345 of file TWeightedNumber.h.
template<class ValueT , class WeightT > void imath::TWeightedNumber< ValueT, WeightT >::SubWeight (WeightType weight) [inline]
Subtract a value to weight part.
Definition at line 352 of file TWeightedNumber.h.
The documentation for this class was generated from the following file:
Include/imath/TWeightedNumber.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy