ACF: icomp::TMultiReferenceMember< Interface > Class Template Reference
icomp::TMultiReferenceMember< Interface > Class Template Reference
Pointer to list of referenced component objects.
#include <TMultiReferenceMember.h>
Public Types
typedef TMultiAttributeMember
< CMultiReferenceAttribute > BaseClass
typedef CInterfaceManipBase BaseClass2
typedef Interface InterfaceType
Public Member Functions
TMultiReferenceMember ()
void Init (const IComponent *ownerPtr, const IRealAttributeStaticInfo &staticInfo)
bool IsValid () const
Check if this reference can be resolved.
Interface * operator[] (int index) const
Access to interface of component at specified index.
Protected Member Functions
TMultiReferenceMember (const TMultiReferenceMember &ptr)
bool EnsureInitialized () const
Detailed Description
template<class Interface>
class icomp::TMultiReferenceMember< Interface >
Pointer to list of referenced component objects.
Don't use direct this class, use macros I_MULTI_REF and I_ASSIGN_MULTI_* instead.
Definition at line 19 of file TMultiReferenceMember.h.
Member Typedef Documentation
template<class Interface > typedef TMultiAttributeMember<CMultiReferenceAttribute> icomp::TMultiReferenceMember< Interface >::BaseClass
Definition at line 22 of file TMultiReferenceMember.h.
template<class Interface > typedef CInterfaceManipBase icomp::TMultiReferenceMember< Interface >::BaseClass2
Definition at line 23 of file TMultiReferenceMember.h.
template<class Interface > typedef Interface icomp::TMultiReferenceMember< Interface >::InterfaceType
Reimplemented from icomp::TMultiAttributeMember< CMultiReferenceAttribute >.
Definition at line 24 of file TMultiReferenceMember.h.
Constructor & Destructor Documentation
template<class Interface > icomp::TMultiReferenceMember< Interface >::TMultiReferenceMember () [inline]
Definition at line 58 of file TMultiReferenceMember.h.
template<class Interface > icomp::TMultiReferenceMember< Interface >::TMultiReferenceMember (const TMultiReferenceMember< Interface > & ptr) [inline, protected]
Definition at line 96 of file TMultiReferenceMember.h.
Member Function Documentation
template<class Interface > bool icomp::TMultiReferenceMember< Interface >::EnsureInitialized () const [inline, protected]
Definition at line 106 of file TMultiReferenceMember.h.
References icomp::TMultiAttributeMember< CMultiReferenceAttribute >::GetCount(), icomp::IComponent::GetParentComponent(), icomp::IComponent::GetSubcomponent(), icomp::TMultiAttributeMember< CMultiReferenceAttribute >::IsValid(), NULL, icomp::TMultiAttributeMember< CMultiReferenceAttribute >::operator[](), and istd::CIdManipBase::SplitId().
Referenced by icomp::TMultiReferenceMember< Interface >::IsValid(), and icomp::TMultiReferenceMember< Interface >::operator[]().
template<class Interface > void icomp::TMultiReferenceMember< Interface >::Init (const IComponent * ownerPtr, const IRealAttributeStaticInfo & staticInfo) [inline]
Definition at line 65 of file TMultiReferenceMember.h.
References icomp::TMultiAttributeMember< CMultiReferenceAttribute >::Init().
template<class Interface > bool icomp::TMultiReferenceMember< Interface >::IsValid () const [inline]
Check if this reference can be resolved.
Reimplemented from icomp::TMultiAttributeMember< CMultiReferenceAttribute >.
Definition at line 74 of file TMultiReferenceMember.h.
References icomp::TMultiReferenceMember< Interface >::EnsureInitialized().
template<class Interface > Interface * icomp::TMultiReferenceMember< Interface >::operator[] (int index) const [inline]
Access to interface of component at specified index.
Returns:
pointer to interface or NULL if there is no associated object at this index.
Reimplemented from icomp::TMultiAttributeMember< CMultiReferenceAttribute >.
Definition at line 81 of file TMultiReferenceMember.h.
References icomp::TMultiReferenceMember< Interface >::EnsureInitialized(), and I_ASSERT.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/icomp/TMultiReferenceMember.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy