iqt2d::TViewExtenderCompBase< Base > Class Template Reference
iqt2d::TViewExtenderCompBase< Base > Class Template Reference
#include <TViewExtenderCompBase.h>
Public Types
typedef Base BaseClass
Public Member Functions
TViewExtenderCompBase ()
virtual void AddItemsToScene (IViewProvider *providerPtr, int flags)
Called when items should be added to specified scene.
virtual void RemoveItemsFromScene (IViewProvider *providerPtr)
Called when items should be removed from specified scene.
Protected Types
enum ExtenderMode { EM_COMBINE, EM_SLAVE_DIRECT_ONLY, EM_OWN_SHAPES_INDIRECT, EM_SLAVE_DIRECT_ONLY_OWN_SHAPES_INDIRECT }
typedef istd::TPointerVector
< iview::IShape > Shapes
typedef QMap< IViewProvider
*, Shapes > ShapesMap
Protected Member Functions
bool IsViewIdSupported (int viewId) const
const ShapesMap & GetShapesMap () const
void UpdateAllViews ()
virtual void CreateShapes (int viewId, Shapes &result)=0
Create shapes for the view.
Detailed Description
template<class Base>
class iqt2d::TViewExtenderCompBase< Base >
Definition at line 20 of file TViewExtenderCompBase.h.
Member Typedef Documentation
template<class Base> typedef Base iqt2d::TViewExtenderCompBase< Base >::BaseClass
Reimplemented in iqt2d::TPolygonBasedParamsGuiComp< PolygonBasedShape, PolygonBasedModel >, iqt2d::TPolygonBasedParamsGuiComp< iview::CTubePolylineShape, i2d::CTubePolyline >, iqt2d::TPolygonBasedParamsGuiComp< iview::CPolygonShape, i2d::CPolygon >, iqt2d::TPolygonBasedParamsGuiComp< iview::CPolylineShape, i2d::CPolyline >, iqt2d::CAnnulusParamsGuiComp, iqt2d::CAnnulusSegmentParamsGuiComp, iqt2d::CLine2dParamsGuiComp, iqt2d::CQuadrangleParamsGuiComp, iqt2d::CCircleParamsGuiComp, iqt2d::COrientedCircleEditorComp, iqt2d::CRectangleParamsGuiComp, iqt2d::CAffineTransformationParamsGuiComp, iqt2d::CPolylineParamsGuiComp, iqt2d::CTubePolylineParamsGuiComp, iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >, iqt2d::TShapeParamsGuiCompBase< Ui::CAffineTransformationParamsGui, iview::CAffineTransformation2dShape, i2d::CAffineTransformation2d >, iqt2d::TShapeParamsGuiCompBase< Ui::CLine2dParamsGuiComp, iview::CLineShape, i2d::CLine2d >, iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, iview::CTubePolylineShape, i2d::CTubePolyline >, iqt2d::TShapeParamsGuiCompBase< Ui::CRectangleParamsGuiComp, iview::CRectangleShape, i2d::CRectangle >, iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, PolygonBasedShape, PolygonBasedModel >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusParamsGuiComp, iview::CAnnulusShape, i2d::CAnnulus >, iqt2d::TShapeParamsGuiCompBase< Ui::COrientedCircleEditorComp, iview::COrientedCircleShape, i2d::COrientedCircle >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusSegmentParamsGuiComp, iview::CAnnulusSegmentShape, i2d::CAnnulusSegment >, iqt2d::TShapeParamsGuiCompBase< Ui::CCircleParamsGuiComp, iview::CCircleShape, i2d::CCircle >, iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, iview::CPolygonShape, i2d::CPolygon >, iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, iview::CPolylineShape, i2d::CPolyline >, iqt2d::TShapeParamsGuiCompBase< Ui::CQuadrangleParamsGuiComp, iview::CParallelogramShape, i2d::CQuadrangle >, and iqt2d::CPolygonParamsGuiComp.
Definition at line 23 of file TViewExtenderCompBase.h.
template<class Base> typedef istd::TPointerVector<iview::IShape> iqt2d::TViewExtenderCompBase< Base >::Shapes [protected]
Reimplemented in iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >, iqt2d::TShapeParamsGuiCompBase< Ui::CAffineTransformationParamsGui, iview::CAffineTransformation2dShape, i2d::CAffineTransformation2d >, iqt2d::TShapeParamsGuiCompBase< Ui::CLine2dParamsGuiComp, iview::CLineShape, i2d::CLine2d >, iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, iview::CTubePolylineShape, i2d::CTubePolyline >, iqt2d::TShapeParamsGuiCompBase< Ui::CRectangleParamsGuiComp, iview::CRectangleShape, i2d::CRectangle >, iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, PolygonBasedShape, PolygonBasedModel >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusParamsGuiComp, iview::CAnnulusShape, i2d::CAnnulus >, iqt2d::TShapeParamsGuiCompBase< Ui::COrientedCircleEditorComp, iview::COrientedCircleShape, i2d::COrientedCircle >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusSegmentParamsGuiComp, iview::CAnnulusSegmentShape, i2d::CAnnulusSegment >, iqt2d::TShapeParamsGuiCompBase< Ui::CCircleParamsGuiComp, iview::CCircleShape, i2d::CCircle >, iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, iview::CPolygonShape, i2d::CPolygon >, iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, iview::CPolylineShape, i2d::CPolyline >, and iqt2d::TShapeParamsGuiCompBase< Ui::CQuadrangleParamsGuiComp, iview::CParallelogramShape, i2d::CQuadrangle >.
Definition at line 47 of file TViewExtenderCompBase.h.
template<class Base> typedef QMap<IViewProvider*, Shapes> iqt2d::TViewExtenderCompBase< Base >::ShapesMap [protected]
Reimplemented in iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >, iqt2d::TShapeParamsGuiCompBase< Ui::CAffineTransformationParamsGui, iview::CAffineTransformation2dShape, i2d::CAffineTransformation2d >, iqt2d::TShapeParamsGuiCompBase< Ui::CLine2dParamsGuiComp, iview::CLineShape, i2d::CLine2d >, iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, iview::CTubePolylineShape, i2d::CTubePolyline >, iqt2d::TShapeParamsGuiCompBase< Ui::CRectangleParamsGuiComp, iview::CRectangleShape, i2d::CRectangle >, iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, PolygonBasedShape, PolygonBasedModel >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusParamsGuiComp, iview::CAnnulusShape, i2d::CAnnulus >, iqt2d::TShapeParamsGuiCompBase< Ui::COrientedCircleEditorComp, iview::COrientedCircleShape, i2d::COrientedCircle >, iqt2d::TShapeParamsGuiCompBase< Ui::CAnnulusSegmentParamsGuiComp, iview::CAnnulusSegmentShape, i2d::CAnnulusSegment >, iqt2d::TShapeParamsGuiCompBase< Ui::CCircleParamsGuiComp, iview::CCircleShape, i2d::CCircle >, iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, iview::CPolygonShape, i2d::CPolygon >, iqt2d::TShapeParamsGuiCompBase< Ui::CPolygonParamsGuiComp, iview::CPolylineShape, i2d::CPolyline >, and iqt2d::TShapeParamsGuiCompBase< Ui::CQuadrangleParamsGuiComp, iview::CParallelogramShape, i2d::CQuadrangle >.
Definition at line 48 of file TViewExtenderCompBase.h.
Member Enumeration Documentation
template<class Base> enum iqt2d::TViewExtenderCompBase::ExtenderMode [protected]
Enumerator:
EM_COMBINE
EM_SLAVE_DIRECT_ONLY
EM_OWN_SHAPES_INDIRECT
EM_SLAVE_DIRECT_ONLY_OWN_SHAPES_INDIRECT
Definition at line 39 of file TViewExtenderCompBase.h.
Constructor & Destructor Documentation
template<class Base > iqt2d::TViewExtenderCompBase< Base >::TViewExtenderCompBase ()
Definition at line 77 of file TViewExtenderCompBase.h.
Member Function Documentation
template<class Base > void iqt2d::TViewExtenderCompBase< Base >::AddItemsToScene (IViewProvider * providerPtr, int flags) [virtual]
Called when items should be added to specified scene.
Implements iqt2d::IViewExtender.
Definition at line 86 of file TViewExtenderCompBase.h.
References iview::CShapeBase::AssignToLayer(), iview::IShapeView::ConnectShape(), istd::TPointerVector< Pointer, AccessAdapter >::GetAt(), istd::TPointerVector< Pointer, AccessAdapter >::GetCount(), iview::IShape::GetLayerType(), iqt2d::IViewProvider::GetView(), iqt2d::IViewProvider::GetViewId(), iview::IViewLayer::LT_BACKGROUND, iview::IViewLayer::LT_INACTIVE, and NULL.
template<class Base> virtual void iqt2d::TViewExtenderCompBase< Base >::CreateShapes (int viewId, Shapes & result) [protected, pure virtual]
Create shapes for the view.
Parameters:
Implemented in iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >.
template<class Base > const TViewExtenderCompBase< Base >::ShapesMap & iqt2d::TViewExtenderCompBase< Base >::GetShapesMap () const [protected]
Definition at line 207 of file TViewExtenderCompBase.h.
template<class Base > bool iqt2d::TViewExtenderCompBase< Base >::IsViewIdSupported (int viewId) const [protected]
Definition at line 188 of file TViewExtenderCompBase.h.
template<class Base > void iqt2d::TViewExtenderCompBase< Base >::RemoveItemsFromScene (IViewProvider * providerPtr) [virtual]
Called when items should be removed from specified scene.
Implements iqt2d::IViewExtender.
Definition at line 154 of file TViewExtenderCompBase.h.
References iview::IShapeObserver::DisconnectShape(), istd::TPointerVector< Pointer, AccessAdapter >::GetAt(), istd::TPointerVector< Pointer, AccessAdapter >::GetCount(), iqt2d::IViewProvider::GetView(), and NULL.
template<class Base > void iqt2d::TViewExtenderCompBase< Base >::UpdateAllViews () [protected]
Definition at line 214 of file TViewExtenderCompBase.h.
References iqt2d::IViewProvider::GetView(), NULL, and iview::IShapeView::Update().
The documentation for this class was generated from the following file:
Include/iqt2d/TViewExtenderCompBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy