ACF: istd::TPointerVector< Pointer, AccessAdapter > Class Template Reference
istd::TPointerVector< Pointer, AccessAdapter > Class Template Reference
Implementation of a pointer container, which controls the live cycle of the pointer object.
#include <TPointerVector.h>
Public Types
enum { InvalidIndex = -1 }
typedef AccessAdapter::ElementType ElementType
Public Member Functions
TPointerVector ()
TPointerVector (const TPointerVector &)
~TPointerVector ()
bool IsEmpty () const
Check if there is element stored in this set.
int GetCount () const
Get number of stored elements.
void SetCount (int count)
Set number of elements.
void Reset ()
Remove all elements.
int HasElement (const Pointer *elementPtr) const
Check if some element is stored in this vector and return the index of the element, if anyone exists, otherwise return InvalidIndex.
Pointer * GetAt (int index) const
Get pointer at specified index.
const ElementType & GetElementAt (int index) const
Get element at specified index.
void SetElementAt (int index, const ElementType &element)
Set element at specified index.
void RemoveAt (int index)
Remove element at specified index.
bool Remove (Pointer *elementPtr)
Remove element elementPtr.
Pointer * PopAt (int index)
Pop element at specified index.
void PushBack (const ElementType &element)
Add new element at the end of collection.
void InsertElementAt (int index, const ElementType &element)
Insert element at specified position.
Detailed Description
template<typename Pointer, class AccessAdapter = TDeleteAdapter<Pointer>>
class istd::TPointerVector< Pointer, AccessAdapter >
Implementation of a pointer container, which controls the live cycle of the pointer object.
Definition at line 49 of file TPointerVector.h.
Member Typedef Documentation
template<typename Pointer, class AccessAdapter = TDeleteAdapter<Pointer>> typedef AccessAdapter::ElementType istd::TPointerVector< Pointer, AccessAdapter >::ElementType
Definition at line 52 of file TPointerVector.h.
Member Enumeration Documentation
template<typename Pointer, class AccessAdapter = TDeleteAdapter<Pointer>> anonymous enum
Enumerator:
InvalidIndex Invalid index in the vector.
Definition at line 54 of file TPointerVector.h.
Constructor & Destructor Documentation
template<typename Pointer , class AccessAdapter > istd::TPointerVector< Pointer, AccessAdapter >::TPointerVector () [inline]
Definition at line 150 of file TPointerVector.h.
template<typename Pointer, class AccessAdapter = TDeleteAdapter<Pointer>> istd::TPointerVector< Pointer, AccessAdapter >::TPointerVector (const TPointerVector< Pointer, AccessAdapter > &)
template<typename Pointer , class AccessAdapter > istd::TPointerVector< Pointer, AccessAdapter >::~TPointerVector () [inline]
Definition at line 179 of file TPointerVector.h.
References istd::TPointerVector< Pointer, AccessAdapter >::Reset().
Member Function Documentation
template<typename Pointer , class AccessAdapter > Pointer * istd::TPointerVector< Pointer, AccessAdapter >::GetAt (int index) const [inline]
Get pointer at specified index.
Definition at line 222 of file TPointerVector.h.
References I_ASSERT.
Referenced by iqt2d::TSceneExtenderCompBase< Base >::AddItemsToScene(), iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::OnAttached(), iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::OnDetached(), and iqt2d::TSceneExtenderCompBase< Base >::RemoveItemsFromScene().
template<typename Pointer , class AccessAdapter > int istd::TPointerVector< Pointer, AccessAdapter >::GetCount () const [inline]
Get number of stored elements.
Definition at line 170 of file TPointerVector.h.
Referenced by iqt2d::TSceneExtenderCompBase< Base >::AddItemsToScene(), istd::TPointerVector< Pointer, AccessAdapter >::HasElement(), istd::TPointerVector< Pointer, AccessAdapter >::InsertElementAt(), iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::OnAttached(), iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::OnDetached(), istd::TPointerVector< Pointer, AccessAdapter >::Remove(), and iqt2d::TSceneExtenderCompBase< Base >::RemoveItemsFromScene().
template<typename Pointer , class AccessAdapter > const TPointerVector< Pointer, AccessAdapter >::ElementType & istd::TPointerVector< Pointer, AccessAdapter >::GetElementAt (int index) const [inline]
Get element at specified index.
Dependent on implementation of AccessAdapter it can differ from GetAt().
Definition at line 232 of file TPointerVector.h.
References I_ASSERT.
template<typename Pointer, class AccessAdapter > int istd::TPointerVector< Pointer, AccessAdapter >::HasElement (const Pointer * elementPtr) const [inline]
Check if some element is stored in this vector and return the index of the element, if anyone exists, otherwise return InvalidIndex.
Definition at line 206 of file TPointerVector.h.
References istd::TPointerVector< Pointer, AccessAdapter >::GetCount(), and istd::TPointerVector< Pointer, AccessAdapter >::InvalidIndex.
Referenced by istd::TPointerVector< Pointer, AccessAdapter >::InsertElementAt().
template<typename Pointer , class AccessAdapter > void istd::TPointerVector< Pointer, AccessAdapter >::InsertElementAt (int index, const ElementType & element) [inline]
Insert element at specified position.
Definition at line 302 of file TPointerVector.h.
References istd::TPointerVector< Pointer, AccessAdapter >::GetCount(), istd::TPointerVector< Pointer, AccessAdapter >::HasElement(), I_ASSERT, and istd::TPointerVector< Pointer, AccessAdapter >::InvalidIndex.
template<typename Pointer , class AccessAdapter > bool istd::TPointerVector< Pointer, AccessAdapter >::IsEmpty () const [inline]
Check if there is element stored in this set.
Definition at line 163 of file TPointerVector.h.
template<typename Pointer , class AccessAdapter > Pointer * istd::TPointerVector< Pointer, AccessAdapter >::PopAt (int index) [inline]
Pop element at specified index.
It does't delete pointed object, it removes it only from the vector.
Definition at line 281 of file TPointerVector.h.
References I_ASSERT.
template<typename Pointer , class AccessAdapter > void istd::TPointerVector< Pointer, AccessAdapter >::PushBack (const ElementType & element) [inline]
Add new element at the end of collection.
Definition at line 295 of file TPointerVector.h.
Referenced by iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::CreateShapes().
template<typename Pointer, class AccessAdapter > bool istd::TPointerVector< Pointer, AccessAdapter >::Remove (Pointer * elementPtr) [inline]
Remove element elementPtr.
The element will be deleted and removed from this vector. It means after call of this method number of elements will be decreased if pointer is found.
Returns:
true, if element was removed, false elsewhere.
Definition at line 263 of file TPointerVector.h.
References istd::TPointerVector< Pointer, AccessAdapter >::GetCount(), and istd::TPointerVector< Pointer, AccessAdapter >::RemoveAt().
template<typename Pointer , class AccessAdapter > void istd::TPointerVector< Pointer, AccessAdapter >::RemoveAt (int index) [inline]
Remove element at specified index.
The element will be deleted and removed from this vector. It means after call of this method number of elements will be decreased.
Definition at line 249 of file TPointerVector.h.
References I_ASSERT.
Referenced by istd::TPointerVector< Pointer, AccessAdapter >::Remove().
template<typename Pointer , class AccessAdapter > void istd::TPointerVector< Pointer, AccessAdapter >::Reset () [inline]
Remove all elements.
Definition at line 193 of file TPointerVector.h.
Referenced by istd::TPointerVector< Pointer, AccessAdapter >::~TPointerVector().
template<typename Pointer , class AccessAdapter > void istd::TPointerVector< Pointer, AccessAdapter >::SetCount (int count) [inline]
Set number of elements.
Definition at line 186 of file TPointerVector.h.
template<typename Pointer , class AccessAdapter > void istd::TPointerVector< Pointer, AccessAdapter >::SetElementAt (int index, const ElementType & element) [inline]
Set element at specified index.
Definition at line 242 of file TPointerVector.h.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/istd/TPointerVector.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy