iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel > Class Template Reference
iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel > Class Template Reference
#include <TShapeParamsGuiCompBase.h>
Public Types
typedef
iqt2d::TViewExtenderCompBase
< iqtgui::TDesignerGuiObserverCompBase
< Ui, ShapeModel > > BaseClass
Public Types inherited from iqtgui::TGuiComponentBase< QWidget >
typedef CGuiComponentBase BaseClass
Public Types inherited from iqtgui::CGuiComponentBase
typedef icomp::CComponentBase BaseClass
Public Types inherited from imod::TSingleModelObserverBase< ShapeModel >
typedef CSingleModelObserverBase BaseClass
typedef ShapeModel ModelType
Public Types inherited from imod::CSingleModelObserverBase
typedef imod::IModel ModelType
Public Types inherited from imod::IModelEditor
enum ChangeFlags { CF_INIT_EDITOR = 1 << 4 }
Public Types inherited from iqt2d::IViewExtender
enum SceneFlags { SF_BACKGROUND = 1, SF_DIRECT = 2 }
Standard flags for items .
Public Member Functions
virtual bool OnAttached (imod::IModel *modelPtr)
This call back function will be called, if an observable object is about to be attached.
virtual bool OnDetached (imod::IModel *modelPtr)
This call back function will be called, if an observable object is about to be detached.
Public Member Functions inherited from iqtgui::TGuiComponentBase< QWidget >
TGuiComponentBase ()
virtual QWidget * GetQtWidget () const
Public Member Functions inherited from iqtgui::CGuiComponentBase
I_REGISTER_SUBELEMENT (VisualStatus)
I_REGISTER_SUBELEMENT_INTERFACE_T (VisualStatus, IVisualStatus, ExtractVisualStatus)
I_REGISTER_SUBELEMENT_INTERFACE_T (VisualStatus, istd::IChangeable, ExtractVisualStatus)
I_REGISTER_SUBELEMENT_INTERFACE_T (VisualStatus, imod::IModel, ExtractVisualStatus)
CGuiComponentBase ()
bool IsGuiShown () const
virtual bool IsGuiCreated () const
Inform if GUI was initilized.
virtual bool CreateGui (QWidget *parentPtr)
Initialize GUI and connect it to the parent.
virtual bool DestroyGui ()
Release GUI and disconnect it from parent.
virtual QWidget * GetWidget () const
Get access to internal QWidget object.
virtual void OnTryClose (bool *ignoredPtr=NULL)
Called on trying to close application.
Public Member Functions inherited from icomp::CComponentBase
CComponentBase ()
Create component and assign it to specific context.
virtual const ICompositeComponent * GetParentComponent (bool ownerOnly=false) const
Get parent of this component.
virtual void * GetInterface (const istd::CClassInfo &interfaceType, const QByteArray &subId="")
Get access to specified component interface.
virtual const IComponentContext * GetComponentContext () const
Get access to component context describing all application-specified component information loaded from components registry.
virtual void SetComponentContext (const icomp::IComponentContext *contextPtr, const ICompositeComponent *parentPtr, bool isParentOwner)
Set component context of this component.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Public Member Functions inherited from imod::TSingleModelObserverBase< ShapeModel >
TSingleModelObserverBase ()
ShapeModel * GetObjectPtr () const
bool AttachOrSetObject (ShapeModel *objectPtr)
Attach to model of object or set object pointer, if no connection is possible.
Public Member Functions inherited from imod::CSingleModelObserverBase
CSingleModelObserverBase ()
virtual ~CSingleModelObserverBase ()
imod::IModel * GetModelPtr () const
Get access to observed model.
void EnsureModelDetached ()
Make sure this observer is detached.
virtual bool IsModelAttached (const imod::IModel *modelPtr=NULL) const
Check if specified model is attached.
virtual void BeforeUpdate (imod::IModel *modelPtr, int updateFlags, istd::IPolymorphic *updateParamsPtr)
This function will be called before update of the observer contents occures.
Protected Types
typedef BaseClass::Shapes Shapes
typedef BaseClass::ShapesMap ShapesMap
Protected Member Functions
QString GetUnitName () const
virtual Shape * CreateShape () const
virtual void CreateShapes (int sceneId, Shapes &result)
Create shapes for the view.
Protected Member Functions inherited from iqtgui::CGuiComponentBase
virtual bool OnKeyPressed (QKeyEvent *event)
Called from widget event filter when key is pressed.
virtual void OnRetranslate ()
Called when non-GUI elements (like commands) should be retranslated.
void SetStatusIcon (const QIcon &icon)
Set status icon;.
void SetStatusText (const QString &text)
Set status text;.
virtual bool eventFilter (QObject *sourcePtr, QEvent *eventPtr)
Protected Member Functions inherited from icomp::CComponentBase
bool IsComponentActive () const
Check if component is active.
virtual const
icomp::IRealComponentStaticInfo & GetComponentStaticInfo () const =0
Get access to static info of this component.
Protected Member Functions inherited from imod::TSingleModelObserverBase< ShapeModel >
virtual ShapeModel * CastFromModel (imod::IModel *modelPtr) const
Protected Member Functions inherited from imod::CSingleModelObserverBase
void SetModelPtr (imod::IModel *modelPtr)
Set internal model pointer to specified value.
virtual void OnUpdate (int updateFlags, istd::IPolymorphic *updateParamsPtr)
Additional Inherited Members
Static Protected Member Functions inherited from icomp::CComponentBase
static const
icomp::IRealComponentStaticInfo & InitStaticInfo (IComponent *componentPtr)
static QByteArray GetComponentId (const icomp::IComponentContext *componentContextPtr, const QByteArray &contextId=QByteArray())
Protected Attributes inherited from iqtgui::CGuiComponentBase
imod::TModelWrap< VisualStatus > m_visualStatus
Detailed Description
template<class Ui, class Shape, class ShapeModel>
class iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >
Definition at line 17 of file TShapeParamsGuiCompBase.h.
Member Typedef Documentation
template<class Ui, class Shape, class ShapeModel> typedef iqt2d::TViewExtenderCompBase<iqtgui::TDesignerGuiObserverCompBase<Ui, ShapeModel> > iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::BaseClass
Definition at line 22 of file TShapeParamsGuiCompBase.h.
template<class Ui, class Shape, class ShapeModel> typedef BaseClass::Shapes iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::Shapes protected
Definition at line 34 of file TShapeParamsGuiCompBase.h.
template<class Ui, class Shape, class ShapeModel> typedef BaseClass::ShapesMap iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::ShapesMap protected
Definition at line 35 of file TShapeParamsGuiCompBase.h.
Member Function Documentation
template<class Ui , class Shape , class ShapeModel > Shape * iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::CreateShape () const protected virtual
Reimplemented in iqt2d::CPolylineParamsGuiComp.
Definition at line 138 of file TShapeParamsGuiCompBase.h.
template<class Ui , class Shape , class ShapeModel > void iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::CreateShapes (int viewId, Shapes & result) protected virtual
Create shapes for the view.
Parameters
Implements iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui, ShapeModel > >.
Reimplemented in iqt2d::CAffineTransformationParamsGuiComp.
Definition at line 147 of file TShapeParamsGuiCompBase.h.
References imod::IModel::AttachObserver(), NULL, and istd::TPointerVector< Pointer, AccessAdapter >::PushBack().
template<class Ui , class Shape , class ShapeModel > QString iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::GetUnitName () const protected
Definition at line 114 of file TShapeParamsGuiCompBase.h.
References i2d::ICalibration2d::GetArgumentUnitInfo(), i2d::ICalibrationProvider::GetCalibration(), imath::IUnitInfo::GetUnitName(), and NULL.
template<class Ui , class Shape , class ShapeModel > bool iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::OnAttached (imod::IModel * modelPtr) virtual
This call back function will be called, if an observable object is about to be attached.
This function returns a true, if observable object is accepted by the implementation logic of the observer, otherwise the function returns a false.
Reimplemented from iqtgui::TGuiObserverWrap< iqtgui::TDesignerGuiCompBase< Ui, QWidget >, imod::TSingleModelObserverBase< ShapeModel > >.
Definition at line 54 of file TShapeParamsGuiCompBase.h.
References imod::IModel::AttachObserver(), istd::TPointerVector< Pointer, AccessAdapter >::GetAt(), istd::TPointerVector< Pointer, AccessAdapter >::GetCount(), and NULL.
template<class Ui , class Shape , class ShapeModel > bool iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::OnDetached (imod::IModel * modelPtr) virtual
This call back function will be called, if an observable object is about to be detached.
Reimplemented from iqtgui::TGuiObserverWrap< iqtgui::TDesignerGuiCompBase< Ui, QWidget >, imod::TSingleModelObserverBase< ShapeModel > >.
Definition at line 82 of file TShapeParamsGuiCompBase.h.
References imod::IModel::DetachObserver(), istd::TPointerVector< Pointer, AccessAdapter >::GetAt(), istd::TPointerVector< Pointer, AccessAdapter >::GetCount(), imod::IModel::IsAttached(), and NULL.
The documentation for this class was generated from the following file:
Include/iqt2d/TShapeParamsGuiCompBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy