iview::CArrowShape Class Reference
iview::CArrowShape Class Reference
#include <CArrowShape.h>
Public Types
typedef CInteractiveShapeBase BaseClass
Public Member Functions
CArrowShape ()
virtual void InvalidateBoundingBox ()
Invalidate bounding box.
virtual TouchState IsTouched (istd::CIndex2d position) const
Check, if any shape is touched.
virtual void Draw (QPainter &drawContext) const
Draw this shape using draw context.
virtual bool OnAttached (imod::IModel *modelPtr)
This call back function will be called, if an observable object is about to be attached.
virtual bool OnMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag)
It is called, when mouse button is pushed down or up on this object.
virtual bool OnMouseMove (istd::CIndex2d position)
It is called, when mouse is moved.
Protected Member Functions
void EnsurePointsAreValid () const
void EnsurePointsAreValid (const i2d::CLine2d &line) const
void CalcPoints (const i2d::CLine2d &line) const
void ResetPoints () const
virtual i2d::CRect CalcBoundingBox () const
Calculate bounding box.
virtual void BeginLogDrag (const i2d::CVector2d &reference)
virtual void SetLogDragPosition (const i2d::CVector2d &position)
Static Protected Member Functions
static bool CheckLine (const istd::CIndex2d &firstPoint, const istd::CIndex2d &secondPoint, const istd::CIndex2d &point, double maxDistance)
Protected Attributes
i2d::CVector2d m_referencePosition
double m_arrowLinesProportion
double m_maxArrowLines
int m_referenceIndex
istd::CIndex2d m_points [4]
bool m_arePointsValid
Detailed Description
Definition at line 15 of file CArrowShape.h.
Member Typedef Documentation
typedef CInteractiveShapeBase iview::CArrowShape::BaseClass
Reimplemented from iview::CInteractiveShapeBase.
Definition at line 18 of file CArrowShape.h.
Constructor & Destructor Documentation
iview::CArrowShape::CArrowShape ()
Member Function Documentation
virtual void iview::CArrowShape::BeginLogDrag (const i2d::CVector2d & reference) [protected, virtual]
Implements iview::CInteractiveShapeBase.
virtual i2d::CRect iview::CArrowShape::CalcBoundingBox () const [protected, virtual]
Calculate bounding box.
You have to implement this method in your shapes implementations.
Implements iview::CShapeBase.
void iview::CArrowShape::CalcPoints (const i2d::CLine2d & line) const [protected]
Referenced by EnsurePointsAreValid().
static bool iview::CArrowShape::CheckLine (const istd::CIndex2d & firstPoint, const istd::CIndex2d & secondPoint, const istd::CIndex2d & point, double maxDistance) [static, protected]
virtual void iview::CArrowShape::Draw (QPainter & drawContext) const [virtual]
Draw this shape using draw context.
Implements iview::IVisualizable.
void iview::CArrowShape::EnsurePointsAreValid () const [inline, protected]
Definition at line 69 of file CArrowShape.h.
References CalcPoints(), imod::CSingleModelObserverBase::GetModelPtr(), m_arePointsValid, NULL, and ResetPoints().
void iview::CArrowShape::EnsurePointsAreValid (const i2d::CLine2d & line) const [inline, protected]
Definition at line 84 of file CArrowShape.h.
References CalcPoints(), and m_arePointsValid.
virtual void iview::CArrowShape::InvalidateBoundingBox () [virtual]
Invalidate bounding box.
You can overload this method to provide validation of your internal attributes, because this method is called from Invalidate(int) and OnDisplayChange(int) methods. Please don't forget base method call in your implementations.
Reimplemented from iview::CShapeBase.
virtual TouchState iview::CArrowShape::IsTouched (istd::CIndex2d position) const [virtual]
Check, if any shape is touched.
When shape is touched, it return also pointer to this shape.
Returns:
touch state for the shape, or iview::IInteractiveShape::TS_NONE, when nothing found.
Reimplemented from iview::CShapeBase.
virtual bool iview::CArrowShape::OnAttached (imod::IModel * modelPtr) [virtual]
This call back function will be called, if an observable object is about to be attached.
This function returns a true, if observable object is accepted by the implementation logic of the observer, otherwise the function returns a false.
Reimplemented from iview::CInteractiveShapeBase.
virtual bool iview::CArrowShape::OnMouseButton (istd::CIndex2d position, Qt::MouseButton buttonType, bool downFlag) [virtual]
It is called, when mouse button is pushed down or up on this object.
Parameters:
position - position of mouse pointer on client area (picture coords).
downFlag - true, if mouse button is pushed down, false if pushed up.
Returns:
true if this shape should get focus to catch all mouse movements.
Reimplemented from iview::CInteractiveShapeBase.
virtual bool iview::CArrowShape::OnMouseMove (istd::CIndex2d position) [virtual]
It is called, when mouse is moved.
Only objects with focus receive this event.
Parameters:
position - position of mouse pointer on client area (picture coords).
Returns:
true if this shape should hold focus to catch longer all mouse movements.
Reimplemented from iview::CInteractiveShapeBase.
void iview::CArrowShape::ResetPoints () const [protected]
Referenced by EnsurePointsAreValid().
virtual void iview::CArrowShape::SetLogDragPosition (const i2d::CVector2d & position) [protected, virtual]
Implements iview::CInteractiveShapeBase.
Member Data Documentation
bool iview::CArrowShape::m_arePointsValid [mutable, protected]
Definition at line 63 of file CArrowShape.h.
Referenced by EnsurePointsAreValid().
double iview::CArrowShape::m_arrowLinesProportion [protected]
Definition at line 59 of file CArrowShape.h.
double iview::CArrowShape::m_maxArrowLines [protected]
Definition at line 60 of file CArrowShape.h.
istd::CIndex2d iview::CArrowShape::m_points[4] [mutable, protected]
Definition at line 62 of file CArrowShape.h.
int iview::CArrowShape::m_referenceIndex [protected]
Definition at line 61 of file CArrowShape.h.
i2d::CVector2d iview::CArrowShape::m_referencePosition [protected]
Definition at line 58 of file CArrowShape.h.
The documentation for this class was generated from the following file:
Include/iview/CArrowShape.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy