i2d::CRectangle Class Reference
i2d::CRectangle Class Reference
Definition of rectangle area orthogonal to axis of coordination system.
#include <CRectangle.h>
Public Member Functions
CRectangle ()
CRectangle (double left, double top, double width, double height)
CRectangle (const CVector2d &topLeft, const CVector2d &bottomRight)
CRectangle (const istd::CRange &horizontalRange, const istd::CRange &verticalRange)
CRectangle (const i2d::CRect &rect)
CRectangle (const istd::CIndex2d &size)
bool IsValid () const
Return true if the rectangle is valid.
bool IsEmpty () const
Return true if the rectangle is empty.
bool IsValidNonEmpty () const
Return true if the rectangle is valid and it is not empty.
void Reset ()
Make rectangle empty.
double GetLeft () const
Get value of left boundary.
void SetLeft (double left)
Set value of left boundary.
double GetTop () const
Get value of top boundary.
void SetTop (double top)
Set value of top boundary.
double GetRight () const
Get value of right boundary.
void SetRight (double right)
Set value of right boundary.
double GetBottom () const
Get value of bottom boundary.
void SetBottom (double bottom)
Set value of bottom boundary.
const istd::CRange & GetHorizontalRange () const
Get values of horizontal boundaries.
istd::CRange & GetHorizontalRangeRef ()
Get values of horizontal boundaries as reference.
void SetHorizontalRange (const istd::CRange &range)
Set values of horizontal boundaries.
const istd::CRange & GetVerticalRange () const
Get values of vertical boundaries.
istd::CRange & GetVerticalRangeRef ()
Get values of vertical boundaries as reference.
void SetVerticalRange (const istd::CRange &range)
Set values of vertical boundaries.
CVector2d GetLeftTop () const
Get left-top point of this rectangle.
void SetTopLeft (const CVector2d &topLeft)
Set left-top point of this rectangle.
CVector2d GetRightTop () const
Get right-top point of this rectangle.
void SetTopRight (const CVector2d &topRight)
Set right-top point of this rectangle.
CVector2d GetLeftBottom () const
Get left-bottom point of this rectangle.
void SetBottomLeft (const CVector2d &bottomLeft)
Set left-bottom point of this rectangle.
CVector2d GetRightBottom () const
Get right-bottom point of this rectangle.
void SetBottomRight (const CVector2d &bottomRight)
Set right-bottom point of this rectangle.
bool Contains (const CVector2d &point) const
Check if some point is contained in this rectangle.
bool Contains (const istd::CIndex2d &point) const
Check if some point is contained in this rectangle.
bool Contains (const CRectangle &rect) const
Check if some rectangle is fully contained in this rectangle.
double GetWidth () const
Get width of this rectangle.
double GetHeight () const
Get height of this rectangle.
CVector2d GetSize () const
Get size of this rectangle.
bool IsIntersectedBy (const CRectangle &rect) const
Returns true, if this rectangle is intersected by the other rectangle rect.
bool IsIntersectedBy (const CLine2d &line) const
Returns true, if this rectangle is intersected by the line rect.
CRectangle GetIntersection (const CRectangle &rect) const
Get resulting rectangle of the intersection of this rectangle with rect.
CLine2d GetIntersection (const CLine2d &line) const
Get resulting line of the intersection of this rectangle with the line line.
void Intersect (const CRectangle &rectangle)
Set new rectangle as intersection of the current rectangle with a given one.
CRectangle GetUnion (const CRectangle &rect) const
Get union of two rectangles.
void Unite (const CRectangle &rect)
Set this rectangle to union of two rectangles.
CRectangle GetUnion (const i2d::CVector2d &position) const
Get union of this rectangle and point.
void Unite (const i2d::CVector2d &position)
Set this rectangle to union of rectangle and point.
CRectangle GetExpanded (const CRectangle &rect) const
Get expanded rectangle (simple sum of boundary values).
void Expand (const CRectangle &rect)
Expand rectangle.
double GetDistance (const CVector2d &position) const
Get distance from nearest point of this rectangle to specified position.
double GetMaxDistance (const CVector2d &position) const
Get maximal distance from points of this rectangle to specified position.
CVector2d GetNearestPointTo (const CVector2d &point) const
Get the nearest point in the rectangle for the some given point.
void Translate (const i2d::CVector2d &delta)
CRectangle GetTranslated (const i2d::CVector2d &delta) const
bool operator== (const CRectangle &rect) const
bool operator!= (const CRectangle &rect) const
operator QRectF () const
virtual CVector2d GetCenter () const
Returns center of this 2D-object.
virtual void MoveCenterTo (const CVector2d &position)
Move object to position position.
virtual CRectangle GetBoundingBox () const
Get bounding box of this shape.
virtual bool Transform (const ITransformation2d &transformation, ITransformation2d::ExactnessMode mode=ITransformation2d::EM_NONE, double *errorFactorPtr=NULL)
Transform this object using some transformation.
virtual bool InvTransform (const ITransformation2d &transformation, ITransformation2d::ExactnessMode mode=ITransformation2d::EM_NONE, double *errorFactorPtr=NULL)
Do inverse transformation of this object.
virtual bool GetTransformed (const ITransformation2d &transformation, IObject2d &result, ITransformation2d::ExactnessMode mode=ITransformation2d::EM_NONE, double *errorFactorPtr=NULL) const
Calulate transformation of the object into second one.
virtual bool GetInvTransformed (const ITransformation2d &transformation, IObject2d &result, ITransformation2d::ExactnessMode mode=ITransformation2d::EM_NONE, double *errorFactorPtr=NULL) const
Calulate inverse transformation of the object into second one.
virtual int GetSupportedOperations () const
Get set of flags for supported operations.
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
virtual istd::IChangeable * CloneMe (CompatibilityMode mode=CM_WITHOUT_REFS) const
Make a copy of this object.
virtual bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
Public Member Functions inherited from i2d::CObject2dBase
CObject2dBase ()
CObject2dBase (const CObject2dBase &object2d)
virtual const ICalibration2d * GetCalibration () const
Get access to transformation object, which transforms a local logical coordinate system to global one.
virtual void SetCalibration (const ICalibration2d *calibrationPtr, bool releaseFlag=false)
Set calibration of this object.
virtual bool CopyFrom (const istd::IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Copy this object from another one.
Public Member Functions inherited from iser::ISerializable
virtual quint32 GetMinimalVersion (int versionId) const
Get minimal needed version to correct storing of this data.
Public Member Functions inherited from istd::IChangeable
virtual void BeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Starts the change transaction.
virtual void EndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr=NULL)
Ends the change transaction.
virtual bool IsEqual (const IChangeable &object) const
Compare this object with another object.
virtual bool ResetData (CompatibilityMode mode=CM_WITHOUT_REFS)
Reset data to its default state.
Public Member Functions inherited from istd::IPolymorphic
virtual ~IPolymorphic ()
Static Public Member Functions
static const i2d::CRectangle & GetEmpty ()
Additional Inherited Members
Public Types inherited from i2d::IObject2d
enum ChangeFlags { CF_OBJECT_POSITION = 1 << 20 }
Public Types inherited from istd::IChangeable
enum ChangeFlags {
CF_ACF_INTERNAL = 1 << 0, CF_MODEL = 1 << 1, CF_ABORTED = 1 << 2, CF_DELEGATED = 1 << 3,
CF_NO_UNDO = 1 << 5
}
enum SupportedOperations {
SO_NONE = 0, SO_OBSERVE = 1, SO_COPY = 2, SO_CLONE = 4,
SO_COMPARE = 8
}
Flags for supported operations.
enum CompatibilityMode { CM_STRICT, CM_WITHOUT_REFS, CM_WITH_REFS, CM_CONVERT }
Control how relationship betweeen objects are interpreted.
Protected Member Functions inherited from istd::IChangeable
virtual void OnBeginChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for begin change event.
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Callback function for end change event.
Detailed Description
Definition of rectangle area orthogonal to axis of coordination system.
Definition at line 26 of file CRectangle.h.
Constructor & Destructor Documentation
i2d::CRectangle::CRectangle ()
i2d::CRectangle::CRectangle (double left, double top, double width, double height)
i2d::CRectangle::CRectangle (const CVector2d & topLeft, const CVector2d & bottomRight)
i2d::CRectangle::CRectangle (const istd::CRange & horizontalRange, const istd::CRange & verticalRange)
i2d::CRectangle::CRectangle (const i2d::CRect & rect)
i2d::CRectangle::CRectangle (const istd::CIndex2d & size) explicit
Member Function Documentation
virtual istd::IChangeable* i2d::CRectangle::CloneMe (CompatibilityMode mode = CM_WITHOUT_REFS) const virtual
Make a copy of this object.
Returns
new instance or NULL, if this operation is not supported.
Reimplemented from istd::IChangeable.
bool i2d::CRectangle::Contains (const CVector2d & point) const
Check if some point is contained in this rectangle.
bool i2d::CRectangle::Contains (const istd::CIndex2d & point) const
Check if some point is contained in this rectangle.
bool i2d::CRectangle::Contains (const CRectangle & rect) const
Check if some rectangle is fully contained in this rectangle.
The calibration will be ignored.
virtual bool i2d::CRectangle::CopyFrom (const IChangeable & object, CompatibilityMode mode = CM_WITHOUT_REFS) virtual
void i2d::CRectangle::Expand (const CRectangle & rect)
Expand rectangle.
This expanded rectangle is simple sum of boundary values.
double i2d::CRectangle::GetBottom () const inline
Get value of bottom boundary.
Definition at line 323 of file CRectangle.h.
References istd::TRange< ValueType >::GetMaxValue().
Referenced by i2d::CRect::CRect().
virtual CRectangle i2d::CRectangle::GetBoundingBox () const virtual
Get bounding box of this shape.
Please note, this bounding box is in logical units, the calibration will not be considered.
Implements i2d::IObject2d.
virtual CVector2d i2d::CRectangle::GetCenter () const virtual
Returns center of this 2D-object.
Implements i2d::IObject2d.
double i2d::CRectangle::GetDistance (const CVector2d & position) const
Get distance from nearest point of this rectangle to specified position.
const i2d::CRectangle & i2d::CRectangle::GetEmpty () inline static
Definition at line 355 of file CRectangle.h.
CRectangle i2d::CRectangle::GetExpanded (const CRectangle & rect) const
Get expanded rectangle (simple sum of boundary values).
double i2d::CRectangle::GetHeight () const
Get height of this rectangle.
const istd::CRange & i2d::CRectangle::GetHorizontalRange () const inline
Get values of horizontal boundaries.
Definition at line 329 of file CRectangle.h.
istd::CRange & i2d::CRectangle::GetHorizontalRangeRef () inline
Get values of horizontal boundaries as reference.
Please use update notificators (like istd::CChangeNotifier) to be sure that obervers will be updated correctly.
Definition at line 335 of file CRectangle.h.
CRectangle i2d::CRectangle::GetIntersection (const CRectangle & rect) const
Get resulting rectangle of the intersection of this rectangle with rect.
CLine2d i2d::CRectangle::GetIntersection (const CLine2d & line) const
Get resulting line of the intersection of this rectangle with the line line.
virtual bool i2d::CRectangle::GetInvTransformed (const ITransformation2d & transformation, IObject2d & result, ITransformation2d::ExactnessMode mode = ITransformation2d::EM_NONE, double * errorFactorPtr = NULL) const virtual
Calulate inverse transformation of the object into second one.
Please note, that this operation transforms logical coordinates, it means that the calibration will be ignored.
Parameters
mode controls needed transformation exactness.
errorFactorPtr optional output where approximated length of transformation error vector will be stored. Value 0 means that transformation is exactly done.
result result object.
Returns
true, if transformation was done correctly.
Reimplemented from i2d::CObject2dBase.
double i2d::CRectangle::GetLeft () const inline
Get value of left boundary.
Definition at line 305 of file CRectangle.h.
References istd::TRange< ValueType >::GetMinValue().
Referenced by i2d::CRect::CRect().
CVector2d i2d::CRectangle::GetLeftBottom () const
Get left-bottom point of this rectangle.
CVector2d i2d::CRectangle::GetLeftTop () const
Get left-top point of this rectangle.
double i2d::CRectangle::GetMaxDistance (const CVector2d & position) const
Get maximal distance from points of this rectangle to specified position.
CVector2d i2d::CRectangle::GetNearestPointTo (const CVector2d & point) const
Get the nearest point in the rectangle for the some given point.
double i2d::CRectangle::GetRight () const inline
Get value of right boundary.
Definition at line 317 of file CRectangle.h.
References istd::TRange< ValueType >::GetMaxValue().
Referenced by i2d::CRect::CRect().
CVector2d i2d::CRectangle::GetRightBottom () const
Get right-bottom point of this rectangle.
CVector2d i2d::CRectangle::GetRightTop () const
Get right-top point of this rectangle.
CVector2d i2d::CRectangle::GetSize () const
Get size of this rectangle.
virtual int i2d::CRectangle::GetSupportedOperations () const virtual
Get set of flags for supported operations.
See Also
SupportedOperations
Reimplemented from istd::IChangeable.
double i2d::CRectangle::GetTop () const inline
Get value of top boundary.
Definition at line 311 of file CRectangle.h.
References istd::TRange< ValueType >::GetMinValue().
Referenced by i2d::CRect::CRect().
virtual bool i2d::CRectangle::GetTransformed (const ITransformation2d & transformation, IObject2d & result, ITransformation2d::ExactnessMode mode = ITransformation2d::EM_NONE, double * errorFactorPtr = NULL) const virtual
Calulate transformation of the object into second one.
Please note, that this operation transforms logical coordinates, it means that the calibration will be ignored.
Parameters
mode controls needed transformation exactness.
errorFactorPtr optional output where approximated length of transformation error vector will be stored. Value 0 means that transformation is exactly done.
result result object.
Returns
true, if transformation was done correctly.
Reimplemented from i2d::CObject2dBase.
CRectangle i2d::CRectangle::GetTranslated (const i2d::CVector2d & delta) const
CRectangle i2d::CRectangle::GetUnion (const CRectangle & rect) const
Get union of two rectangles.
Union of rectangles is the smallest rectangle containing both. The calibration will be ignored.
CRectangle i2d::CRectangle::GetUnion (const i2d::CVector2d & position) const
Get union of this rectangle and point.
This is the smallest rectangle containing both elements.
const istd::CRange & i2d::CRectangle::GetVerticalRange () const inline
Get values of vertical boundaries.
Definition at line 341 of file CRectangle.h.
istd::CRange & i2d::CRectangle::GetVerticalRangeRef () inline
Get values of vertical boundaries as reference.
Please use update notificators (like istd::CChangeNotifier) to be sure that obervers will be updated correctly.
Definition at line 347 of file CRectangle.h.
double i2d::CRectangle::GetWidth () const
Get width of this rectangle.
void i2d::CRectangle::Intersect (const CRectangle & rectangle)
Set new rectangle as intersection of the current rectangle with a given one.
virtual bool i2d::CRectangle::InvTransform (const ITransformation2d & transformation, ITransformation2d::ExactnessMode mode = ITransformation2d::EM_NONE, double * errorFactorPtr = NULL) virtual
Do inverse transformation of this object.
Please note, that this operation transforms logical coordinates, it means that the calibration will be ignored.
Parameters
mode controls needed transformation exactness.
errorFactorPtr optional output where approximated length of transformation error vector will be stored. Value 0 means that transformation is exactly done.
Returns
true, if transformation was done correctly.
Reimplemented from i2d::CObject2dBase.
bool i2d::CRectangle::IsEmpty () const
Return true if the rectangle is empty.
bool i2d::CRectangle::IsIntersectedBy (const CRectangle & rect) const
Returns true, if this rectangle is intersected by the other rectangle rect.
bool i2d::CRectangle::IsIntersectedBy (const CLine2d & line) const
Returns true, if this rectangle is intersected by the line rect.
Rectangle is intersected, if there is any point belonging to line and rectangle (filled).
bool i2d::CRectangle::IsValid () const
Return true if the rectangle is valid.
bool i2d::CRectangle::IsValidNonEmpty () const
Return true if the rectangle is valid and it is not empty.
virtual void i2d::CRectangle::MoveCenterTo (const CVector2d & position) virtual
Move object to position position.
Implements i2d::IObject2d.
i2d::CRectangle::operator QRectF () const
bool i2d::CRectangle::operator!= (const CRectangle & rect) const
bool i2d::CRectangle::operator== (const CRectangle & rect) const
void i2d::CRectangle::Reset ()
Make rectangle empty.
virtual bool i2d::CRectangle::Serialize (iser::IArchive & archive) virtual
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See Also
iser::IArchive
Implements iser::ISerializable.
void i2d::CRectangle::SetBottom (double bottom)
Set value of bottom boundary.
void i2d::CRectangle::SetBottomLeft (const CVector2d & bottomLeft)
Set left-bottom point of this rectangle.
void i2d::CRectangle::SetBottomRight (const CVector2d & bottomRight)
Set right-bottom point of this rectangle.
void i2d::CRectangle::SetHorizontalRange (const istd::CRange & range)
Set values of horizontal boundaries.
void i2d::CRectangle::SetLeft (double left)
Set value of left boundary.
void i2d::CRectangle::SetRight (double right)
Set value of right boundary.
void i2d::CRectangle::SetTop (double top)
Set value of top boundary.
void i2d::CRectangle::SetTopLeft (const CVector2d & topLeft)
Set left-top point of this rectangle.
void i2d::CRectangle::SetTopRight (const CVector2d & topRight)
Set right-top point of this rectangle.
void i2d::CRectangle::SetVerticalRange (const istd::CRange & range)
Set values of vertical boundaries.
virtual bool i2d::CRectangle::Transform (const ITransformation2d & transformation, ITransformation2d::ExactnessMode mode = ITransformation2d::EM_NONE, double * errorFactorPtr = NULL) virtual
Transform this object using some transformation.
Please note, that this operation transforms logical coordinates, it means that the calibration will be ignored.
Parameters
mode controls needed transformation exactness.
errorFactorPtr optional output where approximated length of transformation error vector will be stored. Value 0 means that transformation is exactly done.
Returns
true, if transformation was done correctly.
Reimplemented from i2d::CObject2dBase.
void i2d::CRectangle::Translate (const i2d::CVector2d & delta)
void i2d::CRectangle::Unite (const CRectangle & rect)
Set this rectangle to union of two rectangles.
The calibration will be ignored.
void i2d::CRectangle::Unite (const i2d::CVector2d & position)
Set this rectangle to union of rectangle and point.
This union is the smallest rectangle containing both elements.
The documentation for this class was generated from the following file:
Include/i2d/CRectangle.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy