istd::TOptDelPtr< Type, DelArray > Class Template Reference
istd::TOptDelPtr< Type, DelArray > Class Template Reference
Pointer wrapper providing automatic deleting pointed object during destruction.
#include <TOptDelPtr.h>
Public Types
typedef TPointerBase< Type > BaseClass
Public Member Functions
TOptDelPtr (Type *ptr=NULL, bool releaseFlag=false)
Construct and init this pointer.
TOptDelPtr (const TOptDelPtr &ptr)
Copy constructor.
~TOptDelPtr ()
Destructor.
bool IsToRelase () const
Get state of release flag.
void Reset ()
Remove object pointed by internal pointer and set this pointer to NULL.
void SetPtr (Type *ptr, bool releaseFlag=false)
Set new value of internal pointer.
Type * PopPtr ()
Reset internal pointer value without deleting instance and return previos value.
void TakeOver (TOptDelPtr &sourcePtr)
Take internal pointer over.
TOptDelPtr & operator= (const TOptDelPtr &ptr)
Assign operator.
TOptDelPtr & operator= (Type *ptr)
Assign operator.
template<class SourceType >
bool SetCastedOrRemove (SourceType *ptr, bool releaseFlag=false)
Set internal pointer using casted pointer of other type.
Public Member Functions inherited from istd::TPointerBase< Type >
TPointerBase (Type *ptr=NULL)
Construct and assign internal pointer.
void SetPtr (Type *ptr)
Set value of internal stored pointer.
void Reset ()
Set internal pointer value to NULL.
Type * GetPtr () const
Return access to internal stored pointer.
bool IsValid () const
Check if internal pointer not NULL.
void Swap (TPointerBase &ptr)
Swap two pointers.
Type & operator* () const
Get an access to object pointed at.
template<class CastedType >
CastedType Cast () const
Type * operator-> () const
bool operator== (const TPointerBase< Type > &ptr) const
bool operator!= (const TPointerBase< Type > &ptr) const
bool operator< (const TPointerBase< Type > &ptr) const
bool operator> (const TPointerBase< Type > &ptr) const
bool operator<= (const TPointerBase< Type > &ptr) const
bool operator>= (const TPointerBase< Type > &ptr) const
bool operator== (const Type *ptr) const
bool operator!= (const Type *ptr) const
bool operator< (const Type *ptr) const
bool operator> (const Type *ptr) const
bool operator<= (const Type *ptr) const
bool operator>= (const Type *ptr) const
Protected Member Functions
void Detach ()
Remove referenced object.
Protected Member Functions inherited from istd::TPointerBase< Type >
TPointerBase< Type > & operator= (const TPointerBase< Type > ptr)
Type *& GetPtrRef ()
Detailed Description
template<class Type, bool DelArray = false>
class istd::TOptDelPtr< Type, DelArray >
Pointer wrapper providing automatic deleting pointed object during destruction.
Definition at line 16 of file TOptDelPtr.h.
Member Typedef Documentation
template<class Type, bool DelArray = false> typedef TPointerBase<Type> istd::TOptDelPtr< Type, DelArray >::BaseClass
Definition at line 19 of file TOptDelPtr.h.
Constructor & Destructor Documentation
template<class Type, bool DelArray> istd::TOptDelPtr< Type, DelArray >::TOptDelPtr (Type * ptr = NULL, bool releaseFlag = false) inline
Construct and init this pointer.
Parameters
ptr pointer to object.
releaseFlag if true, pointed object will be automatically released.
Definition at line 120 of file TOptDelPtr.h.
template<class Type, bool DelArray> istd::TOptDelPtr< Type, DelArray >::TOptDelPtr (const TOptDelPtr< Type, DelArray > & ptr) inline
Copy constructor.
This implementation has no function and is provided only for compatibility with STL. The source pointer must be invalid (NULL).
Definition at line 127 of file TOptDelPtr.h.
References istd::TPointerBase< Type >::GetPtr(), NULL, and istd::TOptDelPtr< Type, DelArray >::SetPtr().
template<class Type , bool DelArray> istd::TOptDelPtr< Type, DelArray >::~TOptDelPtr () inline
Destructor.
It calls Reset() to delete pointed object.
Definition at line 141 of file TOptDelPtr.h.
Member Function Documentation
template<class Type , bool DelArray> void istd::TOptDelPtr< Type, DelArray >::Detach () protected
Remove referenced object.
Warning: internal pointer will be not changed.
Definition at line 218 of file TOptDelPtr.h.
References NULL.
template<class Type , bool DelArray> bool istd::TOptDelPtr< Type, DelArray >::IsToRelase () const inline
Get state of release flag.
If this flag is true, pointed object will be automatically removed from memory. If this pointer isn't valid, returned value has no meaning.
Definition at line 155 of file TOptDelPtr.h.
template<class Type, bool DelArray = false> TOptDelPtr& istd::TOptDelPtr< Type, DelArray >::operator= (const TOptDelPtr< Type, DelArray > & ptr)
Assign operator.
This implementation has no function and is provided only for compatibility with STL. The source pointer must be invalid (NULL).
template<class Type, bool DelArray> TOptDelPtr< Type, DelArray > & istd::TOptDelPtr< Type, DelArray >::operator= (Type * ptr)
Assign operator.
It removes refererenced object before new is assigned.
Parameters
ptr pointer to object.
Definition at line 205 of file TOptDelPtr.h.
template<class Type , bool DelArray> Type * istd::TOptDelPtr< Type, DelArray >::PopPtr () inline
Reset internal pointer value without deleting instance and return previos value.
Definition at line 173 of file TOptDelPtr.h.
References NULL.
Referenced by istd::TOptDelPtr< Type, DelArray >::TakeOver().
template<class Type , bool DelArray> void istd::TOptDelPtr< Type, DelArray >::Reset () inline
Remove object pointed by internal pointer and set this pointer to NULL.
Definition at line 148 of file TOptDelPtr.h.
References NULL.
template<class Type, bool DelArray = false> template<class SourceType > bool istd::TOptDelPtr< Type, DelArray >::SetCastedOrRemove (SourceType * ptr, bool releaseFlag = false) inline
Set internal pointer using casted pointer of other type.
If casting is not possible, parameter object will be removed.
Parameters
releaseFlag if true, pointed object will be automatically released.
Definition at line 89 of file TOptDelPtr.h.
template<class Type, bool DelArray> void istd::TOptDelPtr< Type, DelArray >::SetPtr (Type * ptr, bool releaseFlag = false) inline
Set new value of internal pointer.
If internal pointer wasn't NULL, it will be deleted.
Parameters
releaseFlag if true, pointed object will be automatically released.
Definition at line 162 of file TOptDelPtr.h.
Referenced by istd::TOptDelPtr< const i2d::ICalibration2d >::SetCastedOrRemove(), and istd::TOptDelPtr< Type, DelArray >::TOptDelPtr().
template<class Type , bool DelArray> void istd::TOptDelPtr< Type, DelArray >::TakeOver (TOptDelPtr< Type, DelArray > & sourcePtr)
Take internal pointer over.
It set pointer from other object and detach it from them.
Definition at line 183 of file TOptDelPtr.h.
References istd::TOptDelPtr< Type, DelArray >::PopPtr().
The documentation for this class was generated from the following file:
Include/istd/TOptDelPtr.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy