iview::CShapeControl Class Reference
iview::CShapeControl Class Reference
#include <CShapeControl.h>
Public Types
enum ShapeTransformMode { STM_VIEW, STM_SHAPE, STM_COMBINE }
Describe how shape tranformation is interpreted.
Public Member Functions
CShapeControl ()
virtual const i2d::CAffine2d & GetShapeTransform () const
Get a transform from logical units to view units.
virtual void SetShapeTransform (const i2d::CAffine2d &transform)
Set a transform from logical units to view units.
virtual bool IsVisible () const
Check if this shape is visible.
virtual void SetVisible (bool state=true)
Make this shape visible.
ShapeTransformMode GetTransformMode () const
Get shape transformation mode.
void SetTransformMode (ShapeTransformMode mode)
Set shape transformation mode.
virtual const i2d::CAffine2d & GetLogToViewTransform () const
Get logical units to view transformation.
virtual const
iview::CScreenTransform & GetLogToScreenTransform () const
Get a direct transformation from logical units to screen pixels.
Protected Member Functions
void InvalidateTransforms ()
bool AreTransformsValid () const
void CalcTransforms () const
Calculate internal transformations.
virtual const
iview::CScreenTransform & GetViewToScreenTransform () const =0
Get a transform from view units to screen units It can be called only when display is connected.
virtual void Invalidate (int changeFlags=0)=0
Force this shape to repaint by next image update.
virtual IDisplay * GetDisplayPtr () const =0
Get access to display object.
Detailed Description
Definition at line 15 of file CShapeControl.h.
Member Enumeration Documentation
enum iview::CShapeControl::ShapeTransformMode
Describe how shape tranformation is interpreted.
Enumerator:
STM_VIEW
Shape transformation will be ignored, view transformation will be used.
STM_SHAPE
View transformation will be ignored, shape transformation will be used.
STM_COMBINE
Both transformation will be used, shape transformation will be used as local transformation.
Definition at line 23 of file CShapeControl.h.
Constructor & Destructor Documentation
iview::CShapeControl::CShapeControl ()
Member Function Documentation
bool iview::CShapeControl::AreTransformsValid () const [inline, protected]
Definition at line 183 of file CShapeControl.h.
Referenced by GetLogToScreenTransform(), and GetLogToViewTransform().
void iview::CShapeControl::CalcTransforms () const [protected]
Calculate internal transformations.
See also:
GetLogToViewTransform(), GetLogToScreenTransform() It can be called only when display is connected
IsDisplayConnected().
Referenced by GetLogToScreenTransform(), and GetLogToViewTransform().
virtual IDisplay* iview::CShapeControl::GetDisplayPtr () const [protected, pure virtual]
Get access to display object.
Implemented in iview::TShapeBase< Base >, iview::TShapeBase< IShape >, and iview::TShapeBase< IInteractiveShape >.
const iview::CScreenTransform & iview::CShapeControl::GetLogToScreenTransform () const [inline, virtual]
Get a direct transformation from logical units to screen pixels.
Implements iview::ILogicalCoords.
Definition at line 165 of file CShapeControl.h.
References AreTransformsValid(), and CalcTransforms().
const i2d::CAffine2d & iview::CShapeControl::GetLogToViewTransform () const [inline, virtual]
Get logical units to view transformation.
This transformation converts logical units to view coordinate system. Please note, that it is only affine transformation, not a calibration. You can use it as a calibration only, when linear transformation is enough. To get transformation to convert logical units to screen pixel, use GetLogToScreenTransform().
Implements iview::ILogicalCoords.
Definition at line 155 of file CShapeControl.h.
References AreTransformsValid(), and CalcTransforms().
Referenced by iview::CInteractiveShapeBase::BeginDrag(), and iview::CInteractiveShapeBase::SetDragPosition().
const i2d::CAffine2d & iview::CShapeControl::GetShapeTransform () const [inline, virtual]
Get a transform from logical units to view units.
Definition at line 116 of file CShapeControl.h.
CShapeControl::ShapeTransformMode iview::CShapeControl::GetTransformMode () const [inline]
Get shape transformation mode.
This mode describes which transformation will be used to display shape.
Definition at line 132 of file CShapeControl.h.
virtual const iview::CScreenTransform& iview::CShapeControl::GetViewToScreenTransform () const [protected, pure virtual]
Get a transform from view units to screen units It can be called only when display is connected.
See also:
IsDisplayConnected().
Implemented in iview::TShapeBase< Base >, iview::TShapeBase< IShape >, and iview::TShapeBase< IInteractiveShape >.
virtual void iview::CShapeControl::Invalidate (int changeFlags = 0) [protected, pure virtual]
Force this shape to repaint by next image update.
Implemented in iview::TShapeBase< Base >, iview::TShapeBase< IShape >, iview::TShapeBase< IInteractiveShape >, and iview::CPerspectiveCalibrationShape.
Referenced by SetShapeTransform(), and SetVisible().
void iview::CShapeControl::InvalidateTransforms () [inline, protected]
Definition at line 177 of file CShapeControl.h.
Referenced by SetShapeTransform().
bool iview::CShapeControl::IsVisible () const [inline, virtual]
Check if this shape is visible.
Reimplemented in iview::TShapeBase< Base >, iview::TShapeBase< IShape >, and iview::TShapeBase< IInteractiveShape >.
Definition at line 138 of file CShapeControl.h.
void iview::CShapeControl::SetShapeTransform (const i2d::CAffine2d & transform) [inline, virtual]
Set a transform from logical units to view units.
Definition at line 122 of file CShapeControl.h.
References iview::CS_CONSOLE, Invalidate(), InvalidateTransforms(), and STM_VIEW.
void iview::CShapeControl::SetTransformMode (ShapeTransformMode mode)
Set shape transformation mode.
This mode describes which transformation will be used to display shape.
void iview::CShapeControl::SetVisible (bool state = true) [inline, virtual]
Make this shape visible.
Definition at line 144 of file CShapeControl.h.
References iview::CS_CONSOLE, and Invalidate().
Referenced by iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::CreateShapes(), iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::OnAttached(), and iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::OnDetached().
The documentation for this class was generated from the following file:
Include/iview/CShapeControl.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy