ACF: ibase::TFileSerializerComp< ReadArchive, WriteArchive > Class Template Reference
ibase::TFileSerializerComp< ReadArchive, WriteArchive > Class Template Reference
Template implementation of file serializer using loading and storing archive implementation.
#include <TFileSerializerComp.h>
Classes
class ReadArchiveEx
class WriteArchiveEx
Public Types
enum MessageId { MI_BAD_EXTENSION = 0xac10, MI_UNSUPPORTED_VERSION }
List of possible message ids used in context of this interface.
typedef ibase::TLoggerCompWrap
< CFileTypeInfoComp > BaseClass
Public Member Functions
virtual bool IsOperationSupported (const istd::IChangeable *dataObjectPtr, const istd::CString *filePathPtr=NULL, int flags=0, bool beQuiet=true) const
Returns true if object dataObject can be loaded/saved.
virtual int LoadFromFile (istd::IChangeable &data, const istd::CString &filePath=istd::CString()) const
This function loads data data from file filePath.
virtual int SaveToFile (const istd::IChangeable &data, const istd::CString &filePath=istd::CString()) const
This function saves data data to file filePath.
Protected Member Functions
virtual const iser::IVersionInfo * GetVersionInfo () const
Get working version info.
virtual void OnReadError (const ReadArchive &archive, const istd::IChangeable &data, const istd::CString &filePath) const
Called if read error is occured.
bool CheckMinimalVersion (const iser::ISerializable &object, const iser::IVersionInfo &versionInfo) const
Check if minimal version of some serializable object is supported by version info.
bool CheckInputFilePath (const istd::CString filePath) const
bool CheckTargetDirectory (const istd::CString dirPath) const
Detailed Description
template<class ReadArchive, class WriteArchive>
class ibase::TFileSerializerComp< ReadArchive, WriteArchive >
Template implementation of file serializer using loading and storing archive implementation.
Definition at line 27 of file TFileSerializerComp.h.
Member Typedef Documentation
template<class ReadArchive, class WriteArchive> typedef ibase::TLoggerCompWrap<CFileTypeInfoComp> ibase::TFileSerializerComp< ReadArchive, WriteArchive >::BaseClass
Reimplemented from ibase::TLoggerCompWrap< CFileTypeInfoComp >.
Reimplemented in icmpstr::CRegistryLoaderComp.
Definition at line 33 of file TFileSerializerComp.h.
Member Enumeration Documentation
template<class ReadArchive, class WriteArchive> enum ibase::TFileSerializerComp::MessageId
List of possible message ids used in context of this interface.
Enumerator:
MI_BAD_EXTENSION
MI_UNSUPPORTED_VERSION
Reimplemented from iser::IFileLoader.
Reimplemented in icmpstr::CRegistryLoaderComp.
Definition at line 35 of file TFileSerializerComp.h.
Member Function Documentation
template<class ReadArchive , class WriteArchive > bool ibase::TFileSerializerComp< ReadArchive, WriteArchive >::CheckInputFilePath (const istd::CString filePath) const [inline, protected]
Definition at line 316 of file TFileSerializerComp.h.
References isys::IFileSystem::IsPresent(), iser::IFileLoader::MI_CANNOT_LOAD, NULL, ibase::TLoggerWrap< CFileTypeInfoComp >::SendWarningMessage(), and istd::CString::ToString().
Referenced by ibase::TFileSerializerComp< ReadArchive, WriteArchive >::LoadFromFile().
template<class ReadArchive , class WriteArchive > bool ibase::TFileSerializerComp< ReadArchive, WriteArchive >::CheckMinimalVersion (const iser::ISerializable & object, const iser::IVersionInfo & versionInfo) const [inline, protected]
Check if minimal version of some serializable object is supported by version info.
Definition at line 292 of file TFileSerializerComp.h.
References iser::IVersionInfo::GetVersionIds(), and iser::IVersionInfo::GetVersionNumber().
Referenced by ibase::TFileSerializerComp< ReadArchive, WriteArchive >::SaveToFile().
template<class ReadArchive , class WriteArchive > bool ibase::TFileSerializerComp< ReadArchive, WriteArchive >::CheckTargetDirectory (const istd::CString dirPath) const [inline, protected]
Definition at line 336 of file TFileSerializerComp.h.
References isys::IFileSystem::GetDirPath(), isys::IFileSystem::IsPresent(), iser::IFileLoader::MI_CANNOT_SAVE, NULL, ibase::TLoggerWrap< CFileTypeInfoComp >::SendWarningMessage(), and istd::CString::ToString().
Referenced by ibase::TFileSerializerComp< ReadArchive, WriteArchive >::SaveToFile().
template<class ReadArchive , class WriteArchive > const iser::IVersionInfo * ibase::TFileSerializerComp< ReadArchive, WriteArchive >::GetVersionInfo () const [inline, protected, virtual]
Get working version info.
Definition at line 278 of file TFileSerializerComp.h.
Referenced by ibase::TFileSerializerComp< ReadArchive, WriteArchive >::SaveToFile().
template<class ReadArchive , class WriteArchive > bool ibase::TFileSerializerComp< ReadArchive, WriteArchive >::IsOperationSupported (const istd::IChangeable * dataObjectPtr, const istd::CString * filePathPtr = NULL, int flags = 0, bool beQuiet = true) const [inline, virtual]
Returns true if object dataObject can be loaded/saved.
Parameters:
dataObjectPtr optional pointer to data object should be loaded/stored. It can be NULL if any object is meant.
filePathPtr optional pointer to file should be loaded/stored. It can be NULL if any file is meant. If it points at empty string, anonymous loading is mean.
flags combination of flags defined in QueryFlags and iser::IFileTypeInfo::QueryFlags.
beQuiet if true, no user message output is allowed.
Implements iser::IFileLoader.
Definition at line 164 of file TFileSerializerComp.h.
References iser::IFileTypeInfo::GetFileExtensions(), istd::CString::IsEmpty(), isys::IFileSystem::IsPresent(), ibase::TFileSerializerComp< ReadArchive, WriteArchive >::MI_BAD_EXTENSION, iser::IFileLoader::MI_BAD_OBJECT_TYPE, NULL, iser::IFileLoader::QF_ANONYMOUS_ONLY, iser::IFileLoader::QF_DIRECTORY_ONLY, iser::IFileTypeInfo::QF_NO_SAVING, ibase::TLoggerWrap< CFileTypeInfoComp >::SendInfoMessage(), and istd::CString::ToLower().
Referenced by ibase::TFileSerializerComp< ReadArchive, WriteArchive >::LoadFromFile(), and ibase::TFileSerializerComp< ReadArchive, WriteArchive >::SaveToFile().
template<class ReadArchive , class WriteArchive > int ibase::TFileSerializerComp< ReadArchive, WriteArchive >::LoadFromFile (istd::IChangeable & data, const istd::CString & filePath = istd::CString()) const [inline, virtual]
This function loads data data from file filePath.
Returns:
serialization state.
See also:
SerializationState
Implements iser::IFileLoader.
Reimplemented in icmpstr::CRegistryLoaderComp.
Definition at line 215 of file TFileSerializerComp.h.
References istd::IChangeable::CF_MODEL, ibase::TFileSerializerComp< ReadArchive, WriteArchive >::CheckInputFilePath(), I_ASSERT, ibase::TFileSerializerComp< ReadArchive, WriteArchive >::IsOperationSupported(), NULL, ibase::TFileSerializerComp< ReadArchive, WriteArchive >::OnReadError(), iser::IFileTypeInfo::QF_NO_SAVING, istd::TChangeNotifier< Changeable >::SetPtr(), iser::IFileLoader::StateFailed, and iser::IFileLoader::StateOk.
template<class ReadArchive, class WriteArchive > void ibase::TFileSerializerComp< ReadArchive, WriteArchive >::OnReadError (const ReadArchive & archive, const istd::IChangeable & data, const istd::CString & filePath) const [inline, protected, virtual]
Called if read error is occured.
Reimplemented in icmpstr::CRegistryLoaderComp.
Definition at line 285 of file TFileSerializerComp.h.
References iser::IFileLoader::MI_CANNOT_LOAD, and ibase::TLoggerWrap< CFileTypeInfoComp >::SendWarningMessage().
Referenced by ibase::TFileSerializerComp< ReadArchive, WriteArchive >::LoadFromFile().
template<class ReadArchive , class WriteArchive > int ibase::TFileSerializerComp< ReadArchive, WriteArchive >::SaveToFile (const istd::IChangeable & data, const istd::CString & filePath = istd::CString()) const [inline, virtual]
This function saves data data to file filePath.
Returns:
serialization state.
See also:
SerializationState
Implements iser::IFileLoader.
Reimplemented in icmpstr::CRegistryLoaderComp.
Definition at line 246 of file TFileSerializerComp.h.
References ibase::TFileSerializerComp< ReadArchive, WriteArchive >::CheckMinimalVersion(), ibase::TFileSerializerComp< ReadArchive, WriteArchive >::CheckTargetDirectory(), ibase::TFileSerializerComp< ReadArchive, WriteArchive >::GetVersionInfo(), I_ASSERT, ibase::TFileSerializerComp< ReadArchive, WriteArchive >::IsOperationSupported(), iser::IFileLoader::MI_CANNOT_SAVE, ibase::TFileSerializerComp< ReadArchive, WriteArchive >::MI_UNSUPPORTED_VERSION, NULL, iser::IFileTypeInfo::QF_NO_LOADING, ibase::TLoggerWrap< CFileTypeInfoComp >::SendInfoMessage(), ibase::TLoggerWrap< CFileTypeInfoComp >::SendWarningMessage(), iser::IFileLoader::StateFailed, and iser::IFileLoader::StateOk.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/ibase/TFileSerializerComp.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy