ACF: icmm::CCmy Class Reference
icmm::CCmy Class Reference
Primitive for representation of CMY color value.
#include <CCmy.h>
Public Types
enum ComponentIndex { CI_CYAN, CI_MAGENTA, CI_YELLOW, CI_LAST = CI_YELLOW }
typedef TComposedColor< 3 > BaseClass
Public Member Functions
CCmy (double c=0.0, double m=0.0, double y=0.0)
CCmy (const CCmy &color)
double GetC () const
void SetC (double value)
double GetM () const
void SetM (double value)
double GetY () const
void SetY (double value)
bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
CCmy operator+ (const CCmy &color) const
CCmy operator- (const CCmy &color) const
CCmy operator* (const CCmy &color) const
CCmy operator/ (const CCmy &color) const
CCmy operator* (double value) const
CCmy operator/ (double value) const
const CCmy & operator= (const CCmy &color)
const CCmy & operator+= (const CCmy &color)
const CCmy & operator-= (const CCmy &color)
const CCmy & operator*= (const CCmy &color)
const CCmy & operator/= (const CCmy &color)
const CCmy & operator*= (double value)
const CCmy & operator/= (double value)
Detailed Description
Primitive for representation of CMY color value.
Please note, that normal components values are in range [0, 1].
Definition at line 18 of file CCmy.h.
Member Typedef Documentation
typedef TComposedColor<3> icmm::CCmy::BaseClass
Reimplemented from icmm::TComposedColor< 3 >.
Definition at line 21 of file CCmy.h.
Member Enumeration Documentation
enum icmm::CCmy::ComponentIndex
Enumerator:
CI_CYAN
CI_MAGENTA
CI_YELLOW
CI_LAST
Definition at line 23 of file CCmy.h.
Constructor & Destructor Documentation
icmm::CCmy::CCmy (double c = 0.0, double m = 0.0, double y = 0.0) [inline]
Definition at line 67 of file CCmy.h.
References CI_CYAN, CI_MAGENTA, CI_YELLOW, and imath::TVector< Size >::SetElement().
icmm::CCmy::CCmy (const CCmy & color) [inline]
Definition at line 75 of file CCmy.h.
Member Function Documentation
double icmm::CCmy::GetC () const [inline]
Definition at line 83 of file CCmy.h.
References CI_CYAN, and imath::TVector< Size >::GetElement().
double icmm::CCmy::GetM () const [inline]
Definition at line 95 of file CCmy.h.
References CI_MAGENTA, and imath::TVector< Size >::GetElement().
double icmm::CCmy::GetY () const [inline]
Definition at line 107 of file CCmy.h.
References CI_YELLOW, and imath::TVector< Size >::GetElement().
CCmy icmm::CCmy::operator* (double value) const
Reimplemented from icmm::TComposedColor< 3 >.
CCmy icmm::CCmy::operator* (const CCmy & color) const
const CCmy & icmm::CCmy::operator*= (double value) [inline]
Reimplemented from icmm::TComposedColor< 3 >.
Definition at line 161 of file CCmy.h.
References icmm::TComposedColor< 3 >::operator*=().
const CCmy & icmm::CCmy::operator*= (const CCmy & color) [inline]
Definition at line 145 of file CCmy.h.
References icmm::TComposedColor< 3 >::operator*=().
CCmy icmm::CCmy::operator+ (const CCmy & color) const
const CCmy & icmm::CCmy::operator+= (const CCmy & color) [inline]
Definition at line 129 of file CCmy.h.
References icmm::TComposedColor< 3 >::operator+=().
CCmy icmm::CCmy::operator- (const CCmy & color) const
const CCmy & icmm::CCmy::operator-= (const CCmy & color) [inline]
Definition at line 137 of file CCmy.h.
References icmm::TComposedColor< 3 >::operator-=().
CCmy icmm::CCmy::operator/ (double value) const
Reimplemented from icmm::TComposedColor< 3 >.
CCmy icmm::CCmy::operator/ (const CCmy & color) const
const CCmy & icmm::CCmy::operator/= (double value) [inline]
Reimplemented from icmm::TComposedColor< 3 >.
Definition at line 169 of file CCmy.h.
References icmm::TComposedColor< 3 >::operator/=().
const CCmy & icmm::CCmy::operator/= (const CCmy & color) [inline]
Definition at line 153 of file CCmy.h.
References icmm::TComposedColor< 3 >::operator/=().
const CCmy & icmm::CCmy::operator= (const CCmy & color) [inline]
Definition at line 121 of file CCmy.h.
References icmm::TComposedColor< 3 >::operator=().
bool icmm::CCmy::Serialize (iser::IArchive & archive) [virtual]
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See also:
iser::IArchive
Reimplemented from icmm::TComposedColor< 3 >.
void icmm::CCmy::SetC (double value) [inline]
Definition at line 89 of file CCmy.h.
References CI_CYAN, and imath::TVector< Size >::SetElement().
void icmm::CCmy::SetM (double value) [inline]
Definition at line 101 of file CCmy.h.
References CI_MAGENTA, and imath::TVector< Size >::SetElement().
void icmm::CCmy::SetY (double value) [inline]
Definition at line 113 of file CCmy.h.
References CI_YELLOW, and imath::TVector< Size >::SetElement().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/icmm/CCmy.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy