iqtgui::CCommandTools Class Reference
iqtgui::CCommandTools Class Reference
Helper class to manage menu and toolbar using CHierarchicalCommand.
#include <CCommandTools.h>
Static Public Member Functions
template<class MenuType >
static void CreateMenu (const iqtgui::CHierarchicalCommand &command, MenuType &result)
static int SetupToolbar (const iqtgui::CHierarchicalCommand &command, QToolBar &result, int prevGroupId=ibase::ICommand::GI_NONE)
Detailed Description
Helper class to manage menu and toolbar using CHierarchicalCommand.
Definition at line 25 of file CCommandTools.h.
Member Function Documentation
template<class MenuType > void iqtgui::CCommandTools::CreateMenu (const iqtgui::CHierarchicalCommand & command, MenuType & result) [static]
Definition at line 38 of file CCommandTools.h.
References ibase::ICommand::CF_EXCLUSIVE, ibase::ICommand::CF_GLOBAL_MENU, iqtgui::CHierarchicalCommand::GetChild(), iqtgui::CHierarchicalCommand::GetChildsCount(), iqtgui::CHierarchicalCommand::GetGroupId(), iprm::CNameParam::GetName(), iqtgui::CHierarchicalCommand::GetStaticFlags(), ibase::ICommand::GI_NONE, and NULL.
static int iqtgui::CCommandTools::SetupToolbar (const iqtgui::CHierarchicalCommand & command, QToolBar & result, int prevGroupId = ibase::ICommand::GI_NONE) [static]
The documentation for this class was generated from the following file:
Include/iqtgui/CCommandTools.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy