ACF: icmm::TComposedColor< Size > Class Template Reference
icmm::TComposedColor< Size > Class Template Reference
Generic color implementation.
#include <TComposedColor.h>
Public Types
typedef imath::TVector< Size > BaseClass
typedef BaseClass::Elements Elements
Public Member Functions
TComposedColor ()
TComposedColor (const BaseClass &value)
TComposedColor (const imath::CVarVector &vector)
void GetRounded (const imath::IDoubleManip &manipulator, TComposedColor< Size > &result)
Get color after components value rounding with specified precision.
bool IsRoundedEqual (const TComposedColor< Size > &color, const imath::IDoubleManip &manipulator) const
Check if two values are equal after rounding.
bool IsSimilar (const TComposedColor< Size > &color, double tolerance=I_BIG_EPSILON) const
Allows to compare two colors with tolerance.
bool IsNormalized () const
Check if this color value is normalized.
void Normalize ()
Make this color to be normalized.
void GetNormalized (TComposedColor< Size > &result) const
Get normalized color.
TComposedColor< Size > operator+ (const TComposedColor< Size > &color) const
TComposedColor< Size > operator- (const TComposedColor< Size > &color) const
TComposedColor< Size > operator* (const TComposedColor< Size > &color) const
TComposedColor< Size > operator/ (const TComposedColor< Size > &color) const
TComposedColor< Size > operator* (double value) const
TComposedColor< Size > operator/ (double value) const
const TComposedColor< Size > & operator= (const TComposedColor< Size > &color)
const TComposedColor< Size > & operator= (double colorValue)
const TComposedColor< Size > & operator+= (const TComposedColor< Size > &color)
const TComposedColor< Size > & operator-= (const TComposedColor< Size > &color)
const TComposedColor< Size > & operator*= (const TComposedColor< Size > &color)
const TComposedColor< Size > & operator/= (const TComposedColor< Size > &color)
const TComposedColor< Size > & operator*= (double value)
const TComposedColor< Size > & operator/= (double value)
bool Serialize (iser::IArchive &archive)
Load or store state of this object as a archive stream.
Detailed Description
template<int Size>
class icmm::TComposedColor< Size >
Generic color implementation.
Definition at line 28 of file TComposedColor.h.
Member Typedef Documentation
template<int Size> typedef imath::TVector<Size> icmm::TComposedColor< Size >::BaseClass
Reimplemented in icmm::CCmy, icmm::CCmyk, icmm::CHsv, icmm::CLab, and icmm::CRgb.
Definition at line 31 of file TComposedColor.h.
template<int Size> typedef BaseClass::Elements icmm::TComposedColor< Size >::Elements
Reimplemented from imath::TVector< Size >.
Definition at line 32 of file TComposedColor.h.
Constructor & Destructor Documentation
template<int Size> icmm::TComposedColor< Size >::TComposedColor () [inline]
Definition at line 102 of file TComposedColor.h.
template<int Size> icmm::TComposedColor< Size >::TComposedColor (const BaseClass & value) [inline]
Definition at line 108 of file TComposedColor.h.
template<int Size> icmm::TComposedColor< Size >::TComposedColor (const imath::CVarVector & vector) [inline, explicit]
Definition at line 115 of file TComposedColor.h.
References imath::CVarVector::GetElementsCount(), imath::TVector< Size >::GetElementsRef(), istd::Min(), and imath::TVector< Size >::SetElement().
Member Function Documentation
template<int Size> void icmm::TComposedColor< Size >::GetNormalized (TComposedColor< Size > & result) const [inline]
Get normalized color.
Normalized values have all components in the range [0, 1].
Definition at line 356 of file TComposedColor.h.
References icmm::TComposedColor< Size >::Normalize().
template<int Size> void icmm::TComposedColor< Size >::GetRounded (const imath::IDoubleManip & manipulator, TComposedColor< Size > & result) [inline]
Get color after components value rounding with specified precision.
Parameters:
manipulator manipulator object used to round single components.
result result object.
Definition at line 317 of file TComposedColor.h.
References imath::TVector< Size >::GetElement(), and imath::TIValueManip< ValueType >::GetRounded().
template<int Size> bool icmm::TComposedColor< Size >::IsNormalized () const [inline]
Check if this color value is normalized.
Normalized values have all components in the range [0, 1].
Definition at line 138 of file TComposedColor.h.
References imath::TVector< Size >::GetElement().
template<int Size> bool icmm::TComposedColor< Size >::IsRoundedEqual (const TComposedColor< Size > & color, const imath::IDoubleManip & manipulator) const [inline]
Check if two values are equal after rounding.
Parameters:
color second color to comparision.
manipulator value manipulator used to round single components.
Definition at line 326 of file TComposedColor.h.
References imath::TVector< Size >::GetElement(), and imath::TIValueManip< ValueType >::IsEqual().
template<int Size> bool icmm::TComposedColor< Size >::IsSimilar (const TComposedColor< Size > & color, double tolerance = I_BIG_EPSILON) const [inline]
Allows to compare two colors with tolerance.
Definition at line 131 of file TComposedColor.h.
References imath::TVector< Size >::GetDistance().
template<int Size> void icmm::TComposedColor< Size >::Normalize () [inline]
Make this color to be normalized.
Normalized values have all components in the range [0, 1].
Definition at line 339 of file TComposedColor.h.
References imath::TVector< Size >::GetElementsRef().
Referenced by icmm::TComposedColor< Size >::GetNormalized().
template<int Size> TComposedColor< Size > icmm::TComposedColor< Size >::operator* (double value) const [inline]
Reimplemented from imath::TVector< Size >.
Reimplemented in icmm::CCmy, icmm::CCmyk, icmm::CHsv, icmm::CLab, and icmm::CRgb.
Definition at line 205 of file TComposedColor.h.
References imath::TVector< Size >::GetElement().
template<int Size> TComposedColor< Size > icmm::TComposedColor< Size >::operator* (const TComposedColor< Size > & color) const [inline]
Definition at line 179 of file TComposedColor.h.
References imath::TVector< Size >::GetElement().
template<int Size> const TComposedColor< Size > & icmm::TComposedColor< Size >::operator*= (double value) [inline]
Reimplemented from imath::TVector< Size >.
Reimplemented in icmm::CCmy, icmm::CCmyk, icmm::CHsv, icmm::CLab, and icmm::CRgb.
Definition at line 297 of file TComposedColor.h.
References imath::TVector< Size >::operator*=().
template<int Size> const TComposedColor< Size > & icmm::TComposedColor< Size >::operator*= (const TComposedColor< Size > & color) [inline]
Definition at line 271 of file TComposedColor.h.
References imath::TVector< Size >::GetElementsRef().
template<int Size> TComposedColor< Size > icmm::TComposedColor< Size >::operator+ (const TComposedColor< Size > & color) const [inline]
Definition at line 153 of file TComposedColor.h.
References imath::TVector< Size >::GetElement().
template<int Size> const TComposedColor< Size > & icmm::TComposedColor< Size >::operator+= (const TComposedColor< Size > & color) [inline]
Definition at line 253 of file TComposedColor.h.
References imath::TVector< Size >::operator+=().
template<int Size> TComposedColor< Size > icmm::TComposedColor< Size >::operator- (const TComposedColor< Size > & color) const [inline]
Definition at line 166 of file TComposedColor.h.
References imath::TVector< Size >::GetElement().
template<int Size> const TComposedColor< Size > & icmm::TComposedColor< Size >::operator-= (const TComposedColor< Size > & color) [inline]
Definition at line 262 of file TComposedColor.h.
References imath::TVector< Size >::operator-=().
template<int Size> TComposedColor< Size > icmm::TComposedColor< Size >::operator/ (double value) const [inline]
Reimplemented from imath::TVector< Size >.
Reimplemented in icmm::CCmy, icmm::CCmyk, icmm::CHsv, icmm::CLab, and icmm::CRgb.
Definition at line 218 of file TComposedColor.h.
References imath::TVector< Size >::GetElement().
template<int Size> TComposedColor< Size > icmm::TComposedColor< Size >::operator/ (const TComposedColor< Size > & color) const [inline]
Definition at line 192 of file TComposedColor.h.
References imath::TVector< Size >::GetElement().
template<int Size> const TComposedColor< Size > & icmm::TComposedColor< Size >::operator/= (double value) [inline]
Reimplemented from imath::TVector< Size >.
Reimplemented in icmm::CCmy, icmm::CCmyk, icmm::CHsv, icmm::CLab, and icmm::CRgb.
Definition at line 306 of file TComposedColor.h.
References imath::TVector< Size >::operator/=().
template<int Size> const TComposedColor< Size > & icmm::TComposedColor< Size >::operator/= (const TComposedColor< Size > & color) [inline]
Definition at line 284 of file TComposedColor.h.
References imath::TVector< Size >::GetElementsRef().
template<int Size> const TComposedColor< Size > & icmm::TComposedColor< Size >::operator= (double colorValue) [inline]
Definition at line 242 of file TComposedColor.h.
References imath::TVector< Size >::GetElementsRef(), and imath::TVector< Size >::SetElement().
template<int Size> const TComposedColor< Size > & icmm::TComposedColor< Size >::operator= (const TComposedColor< Size > & color) [inline]
Definition at line 231 of file TComposedColor.h.
References imath::TVector< Size >::SetElement().
template<int Size> bool icmm::TComposedColor< Size >::Serialize (iser::IArchive & archive) [inline, virtual]
Load or store state of this object as a archive stream.
Type of operation is depending on archive type.
See also:
iser::IArchive
Implements iser::ISerializable.
Reimplemented in icmm::CCmy, icmm::CCmyk, icmm::CHsv, icmm::CLab, and icmm::CRgb.
Definition at line 367 of file TComposedColor.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), iser::IArchive::EndTag(), imath::TVector< Size >::GetElementRef(), imath::TVector< Size >::GetElementsCount(), iser::IArchive::IsStoring(), and iser::IArchive::Process().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/icmm/TComposedColor.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy