iview::IShapeView Class Reference
iview::IShapeView Class Reference
Common interface for a general shape view implementations.
#include <IShapeView.h>
Public Types
enum LayerType { LT_NONE = 0, LT_BACKGROUND = 1, LT_INACTIVE = 2, LT_ACTIVE = 4 }
typedef IShapeObserver BaseClass
Public Member Functions
virtual void SetTransform (const i2d::CAffine2d &transform)=0
Set a screen transformation.
virtual void Update ()=0
Updates all invalidates shapes.
virtual void SetEditMode (int mode)=0
Changes the edit mode.
virtual bool IsViewDraggable () const =0
Check if is draggable mode.
virtual bool IsMultiselectable () const =0
Check, if it is possible to select more than one shape.
virtual void UpdateMousePointer ()=0
Update mouse pointer.
virtual int InsertLayer (ILayer *layerPtr, int index=-1, int layerType=LT_NONE)=0
Insert layer to view.
virtual int GetLayerIndex (const ILayer &layer) const =0
Get index of layer.
virtual void RemoveLayer (int index)=0
Remove layer from view.
virtual int GetLayersCount () const =0
Get count of layer in this view.
virtual ILayer & GetLayer (int index) const =0
Get layer with the given index.
virtual void ConnectShape (IShape *shapePtr, int layerIndex=-1)=0
Connect shape object to view.
virtual void ConnectBackgroundShape (iview::IShape *shapePtr)=0
Connect shape to default background layer.
virtual void ConnectInactiveShape (iview::IShape *shapePtr)=0
Connect shape to default inactive layer.
virtual void ConnectActiveShape (iview::IInteractiveShape *shapePtr)=0
Connect shape to default active layer.
virtual ISelectableLayer * GetFocusedLayerPtr () const =0
Get focused layer.
virtual void OnShapeFocused (IInteractiveShape *shapePtr, ISelectableLayer *layerPtr)=0
Called when shape in layer get focus.
virtual void OnShapeDefocused (IInteractiveShape *shapePtr, ISelectableLayer *layerPtr)=0
Called when shape in layer loose focus.
virtual void OnLayerInvalidated (const ILayer &layer, const i2d::CRect &prevArea, const i2d::CRect &newArea)=0
Inform that layer was invalidated.
virtual void OnShapeFocused (IInteractiveShape *)
Called when shape get focus.
virtual void OnShapeDefocused (IInteractiveShape *)
Called when shape loose focus.
Detailed Description
Common interface for a general shape view implementations.
Definition at line 28 of file IShapeView.h.
Member Typedef Documentation
typedef IShapeObserver iview::IShapeView::BaseClass
Reimplemented in iview::CCalibratedViewBase, iview::CViewBase, and iview::CViewport.
Definition at line 33 of file IShapeView.h.
Member Enumeration Documentation
enum iview::IShapeView::LayerType
Enumerator:
LT_NONE
LT_BACKGROUND
LT_INACTIVE
LT_ACTIVE
Definition at line 35 of file IShapeView.h.
Member Function Documentation
virtual void iview::IShapeView::ConnectActiveShape (iview::IInteractiveShape * shapePtr) [pure virtual]
Connect shape to default active layer.
Implemented in iview::CViewBase.
virtual void iview::IShapeView::ConnectBackgroundShape (iview::IShape * shapePtr) [pure virtual]
Connect shape to default background layer.
Implemented in iview::CViewBase.
virtual void iview::IShapeView::ConnectInactiveShape (iview::IShape * shapePtr) [pure virtual]
Connect shape to default inactive layer.
Implemented in iview::CViewBase.
Referenced by iqt2d::TSceneExtenderCompBase< Base >::AddItemsToScene().
virtual void iview::IShapeView::ConnectShape (IShape * shapePtr, int layerIndex = -1) [pure virtual]
Connect shape object to view.
Parameters:
shape a shape object.
Returns:
true, if it was possible to connect this shape.
Implemented in iview::CViewBase.
Referenced by iqt2d::TSceneExtenderCompBase< Base >::AddItemsToScene().
virtual ISelectableLayer* iview::IShapeView::GetFocusedLayerPtr () const [pure virtual]
Get focused layer.
Implemented in iview::CViewBase.
virtual ILayer& iview::IShapeView::GetLayer (int index) const [pure virtual]
Get layer with the given index.
Implemented in iview::CViewBase.
virtual int iview::IShapeView::GetLayerIndex (const ILayer & layer) const [pure virtual]
Get index of layer.
Returns:
layer index, or -1 if not found.
Implemented in iview::CViewBase.
virtual int iview::IShapeView::GetLayersCount () const [pure virtual]
Get count of layer in this view.
Implemented in iview::CViewBase.
virtual int iview::IShapeView::InsertLayer (ILayer * layerPtr, int index = -1, int layerType = LT_NONE) [pure virtual]
Insert layer to view.
Parameters:
layerPtr pointer to inserted layer.
index index of inserted layer. If equals -1, layer will be inserted after layst existing layer.
layerType used to set standard layers.
See also:
iview::IShapeView::LayerType
Returns:
index of this layer.
Implemented in iview::CViewBase, and iview::CCalibratedViewBase.
virtual bool iview::IShapeView::IsMultiselectable () const [pure virtual]
Check, if it is possible to select more than one shape.
Implemented in iview::CViewBase.
virtual bool iview::IShapeView::IsViewDraggable () const [pure virtual]
Check if is draggable mode.
If this function return true, user can move a view by dragging.
Implemented in iview::CViewBase.
virtual void iview::IShapeView::OnLayerInvalidated (const ILayer & layer, const i2d::CRect & prevArea, const i2d::CRect & newArea) [pure virtual]
Inform that layer was invalidated.
Implemented in iview::CViewBase.
virtual void iview::IShapeView::OnShapeDefocused (IInteractiveShape * shapePtr, ISelectableLayer * layerPtr) [pure virtual]
Called when shape in layer loose focus.
Implemented in iview::CViewBase.
virtual void iview::IShapeView::OnShapeDefocused (IInteractiveShape * shapePtr) [inline, virtual]
Called when shape loose focus.
Implements iview::ISelectable.
Definition at line 150 of file IShapeView.h.
virtual void iview::IShapeView::OnShapeFocused (IInteractiveShape * shapePtr, ISelectableLayer * layerPtr) [pure virtual]
Called when shape in layer get focus.
Implemented in iview::CViewBase.
virtual void iview::IShapeView::OnShapeFocused (IInteractiveShape * shapePtr) [inline, virtual]
Called when shape get focus.
Implements iview::ISelectable.
Definition at line 149 of file IShapeView.h.
virtual void iview::IShapeView::RemoveLayer (int index) [pure virtual]
Remove layer from view.
Implemented in iview::CViewBase, and iview::CCalibratedViewBase.
virtual void iview::IShapeView::SetEditMode (int mode) [pure virtual]
Changes the edit mode.
Implemented in iview::CViewBase, and iview::CViewport.
virtual void iview::IShapeView::SetTransform (const i2d::CAffine2d & transform) [pure virtual]
Set a screen transformation.
See also:
GetTransform()
Implemented in iview::CViewBase.
virtual void iview::IShapeView::Update () [pure virtual]
Updates all invalidates shapes.
Implemented in iview::CViewBase.
Referenced by iqt2d::TSceneExtenderCompBase< Base >::UpdateAllViews(), and iqt2d::TShapeParamsGuiCompBase< Ui, Shape, ShapeModel >::UpdateShapeView().
virtual void iview::IShapeView::UpdateMousePointer () [pure virtual]
Update mouse pointer.
Implemented in iview::CViewBase.
The documentation for this class was generated from the following file:
Include/iview/IShapeView.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy