istd::TPointerBase< Type > Class Template Reference
istd::TPointerBase< Type > Class Template Reference
Implementation of pointer wrapper.
#include <TPointerBase.h>
Public Member Functions
TPointerBase (Type *ptr=0)
Construct and assign internal pointer.
void SetPtr (Type *ptr)
Set value of internal stored pointer.
void Reset ()
Set internal pointer value to NULL.
Type * GetPtr () const
Return access to internal stored pointer.
bool IsValid () const
Check if internal pointer not NULL.
void Swap (TPointerBase &ptr)
Swap two pointers.
Type & operator* () const
Get an access to object pointed at.
template<class CastedType >
CastedType Cast () const
Type * operator-> () const
bool operator== (const TPointerBase< Type > &ptr) const
bool operator!= (const TPointerBase< Type > &ptr) const
bool operator< (const TPointerBase< Type > &ptr) const
bool operator> (const TPointerBase< Type > &ptr) const
bool operator<= (const TPointerBase< Type > &ptr) const
bool operator>= (const TPointerBase< Type > &ptr) const
bool operator== (const Type *ptr) const
bool operator!= (const Type *ptr) const
bool operator< (const Type *ptr) const
bool operator> (const Type *ptr) const
bool operator<= (const Type *ptr) const
bool operator>= (const Type *ptr) const
Protected Member Functions
TPointerBase< Type > & operator= (const TPointerBase< Type > ptr)
Type *& GetPtrRef ()
Detailed Description
template<class Type>
class istd::TPointerBase< Type >
Implementation of pointer wrapper.
Definition at line 52 of file TPointerBase.h.
Constructor & Destructor Documentation
template<class Type> istd::TPointerBase< Type >::TPointerBase (Type * ptr = 0) [inline]
Construct and assign internal pointer.
Definition at line 255 of file TPointerBase.h.
Member Function Documentation
template<class Type> template<class CastedType > CastedType istd::TPointerBase< Type >::Cast () const [inline]
Definition at line 91 of file TPointerBase.h.
template<class Type > Type * istd::TPointerBase< Type >::GetPtr () const [inline]
Return access to internal stored pointer.
Definition at line 132 of file TPointerBase.h.
Referenced by istd::TPointerBase< i2d::ICalibration2d >::Cast(), icomp::TMultiFactoryMember< Interface >::CreateInstance(), icomp::TFactoryMember< Interface >::CreateInstance(), icomp::CSimComponentContextBase::InsertMultiAttr(), istd::TSmartPtr< Type, Accessor >::RefCounter::OnDetached(), and istd::TOptDelPtr< Type, DelArray >::TOptDelPtr().
template<class Type > Type *& istd::TPointerBase< Type >::GetPtrRef () [inline, protected]
Definition at line 278 of file TPointerBase.h.
template<class Type > bool istd::TPointerBase< Type >::IsValid () const [inline]
Check if internal pointer not NULL.
Returns:
true, if internal pointer not NULL and can be used to access pointed members.
Definition at line 139 of file TPointerBase.h.
References NULL.
Referenced by icomp::TComponentCloneWrap< BaseClass >::CloneMe(), icomp::TMultiFactoryMember< Interface >::CreateInstance(), icomp::TFactoryMember< Interface >::CreateInstance(), iview::CDrawBuffer::GetDrawContext(), icomp::CSimComponentContextBase::InsertMultiAttr(), istd::TSmartPtr< Type, Accessor >::RefCounter::OnAttached(), and istd::TSmartPtr< Type, Accessor >::RefCounter::OnDetached().
template<class Type> bool istd::TPointerBase< Type >::operator!= (const TPointerBase< Type > & ptr) const [inline]
Definition at line 176 of file TPointerBase.h.
template<class Type> bool istd::TPointerBase< Type >::operator!= (const Type * ptr) const [inline]
Definition at line 218 of file TPointerBase.h.
template<class Type > Type & istd::TPointerBase< Type >::operator* () const [inline]
Get an access to object pointed at.
Definition at line 153 of file TPointerBase.h.
References NULL.
template<class Type > Type * istd::TPointerBase< Type >::operator-> () const [inline]
Reimplemented in istd::TChangeNotifier< Changeable >.
Definition at line 162 of file TPointerBase.h.
template<class Type> bool istd::TPointerBase< Type >::operator< (const TPointerBase< Type > & ptr) const [inline]
Definition at line 183 of file TPointerBase.h.
template<class Type> bool istd::TPointerBase< Type >::operator< (const Type * ptr) const
Definition at line 225 of file TPointerBase.h.
template<class Type> bool istd::TPointerBase< Type >::operator<= (const TPointerBase< Type > & ptr) const [inline]
Definition at line 197 of file TPointerBase.h.
template<class Type> bool istd::TPointerBase< Type >::operator<= (const Type * ptr) const
Definition at line 239 of file TPointerBase.h.
template<class Type> TPointerBase< Type > & istd::TPointerBase< Type >::operator= (const TPointerBase< Type > ptr) [inline, protected]
Definition at line 269 of file TPointerBase.h.
template<class Type> bool istd::TPointerBase< Type >::operator== (const TPointerBase< Type > & ptr) const [inline]
Definition at line 169 of file TPointerBase.h.
template<class Type> bool istd::TPointerBase< Type >::operator== (const Type * ptr) const [inline]
Definition at line 211 of file TPointerBase.h.
template<class Type> bool istd::TPointerBase< Type >::operator> (const TPointerBase< Type > & ptr) const [inline]
Definition at line 190 of file TPointerBase.h.
template<class Type> bool istd::TPointerBase< Type >::operator> (const Type * ptr) const
Definition at line 232 of file TPointerBase.h.
template<class Type> bool istd::TPointerBase< Type >::operator>= (const TPointerBase< Type > & ptr) const [inline]
Definition at line 204 of file TPointerBase.h.
template<class Type> bool istd::TPointerBase< Type >::operator>= (const Type * ptr) const
Definition at line 246 of file TPointerBase.h.
template<class Type > void istd::TPointerBase< Type >::Reset () [inline]
Set internal pointer value to NULL.
Reimplemented in istd::TOptDelPtr< Type, DelArray >, istd::TOptDelPtr< iser::ISerializable >, istd::TOptDelPtr< const IColorSchema >, istd::TOptDelPtr< istd::IPolymorphic >, istd::TOptDelPtr< const ICalibration2d >, istd::TOptDelPtr< quint8, true >, istd::TDelPtr< Type, Accessor >, istd::TDelPtr< iser::CMemoryWriteArchive >, istd::TDelPtr< QSettings >, istd::TDelPtr< QWidget >, istd::TDelPtr< QPainter >, istd::TDelPtr< ImageModel >, istd::TDelPtr< icomp::CCompositeComponentStaticInfo >, istd::TDelPtr< QMenuBar >, istd::TDelPtr< QLabel >, istd::TDelPtr< PositionModel >, istd::TDelPtr< icomp::CCompositePackageStaticInfo >, istd::TDelPtr< iser::ISerializable >, istd::TDelPtr< IParamsSet >, istd::TDelPtr< QFrame >, istd::TDelPtr< icomp::IComponentStaticInfo >, istd::TDelPtr< icomp::IComponentContext >, istd::TDelPtr< istd::IPolymorphic >, istd::TDelPtr< idoc::IUndoManager >, istd::TDelPtr< IRegistryElement >, istd::TDelPtr< iser::IObject >, istd::TDelPtr< QMainWindow >, istd::TDelPtr< CCompositePackageStaticInfo >, istd::TDelPtr< QApplication >, istd::TDelPtr< BitmapShape >, istd::TDelPtr< Shape >, istd::TDelPtr< icomp::IComponent >, istd::TDelPtr< QTextBrowser >, istd::TDelPtr< QToolBar >, istd::TDelPtr< QSharedMemory >, istd::TDelPtr< istd::IChangeable >, istd::TDelPtr< i2d::ICalibration2d >, and istd::TChangeNotifier< Changeable >.
Definition at line 125 of file TPointerBase.h.
References NULL.
template<class Type> void istd::TPointerBase< Type >::SetPtr (Type * ptr) [inline]
Set value of internal stored pointer.
Reimplemented in istd::TDelPtr< Type, Accessor >, istd::TDelPtr< iser::CMemoryWriteArchive >, istd::TDelPtr< QSettings >, istd::TDelPtr< QWidget >, istd::TDelPtr< QPainter >, istd::TDelPtr< ImageModel >, istd::TDelPtr< icomp::CCompositeComponentStaticInfo >, istd::TDelPtr< QMenuBar >, istd::TDelPtr< QLabel >, istd::TDelPtr< PositionModel >, istd::TDelPtr< icomp::CCompositePackageStaticInfo >, istd::TDelPtr< iser::ISerializable >, istd::TDelPtr< IParamsSet >, istd::TDelPtr< QFrame >, istd::TDelPtr< icomp::IComponentStaticInfo >, istd::TDelPtr< icomp::IComponentContext >, istd::TDelPtr< istd::IPolymorphic >, istd::TDelPtr< idoc::IUndoManager >, istd::TDelPtr< IRegistryElement >, istd::TDelPtr< iser::IObject >, istd::TDelPtr< QMainWindow >, istd::TDelPtr< CCompositePackageStaticInfo >, istd::TDelPtr< QApplication >, istd::TDelPtr< BitmapShape >, istd::TDelPtr< Shape >, istd::TDelPtr< icomp::IComponent >, istd::TDelPtr< QTextBrowser >, istd::TDelPtr< QToolBar >, istd::TDelPtr< QSharedMemory >, istd::TDelPtr< istd::IChangeable >, istd::TDelPtr< i2d::ICalibration2d >, and istd::TChangeNotifier< Changeable >.
Definition at line 262 of file TPointerBase.h.
template<class Type > void istd::TPointerBase< Type >::Swap (TPointerBase< Type > & ptr)
Swap two pointers.
Definition at line 146 of file TPointerBase.h.
The documentation for this class was generated from the following file:
Include/istd/TPointerBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy