ACF: icomp::IComponent Class Reference
icomp::IComponent Class Reference
[Component concept]
Main component interface.
#include <IComponent.h>
Public Member Functions
virtual const IComponent * GetParentComponent (bool ownerOnly=false) const =0
Get parent of this component.
virtual void * GetInterface (const istd::CClassInfo &interfaceType, const std::string &subId="")=0
Get access to specified component interface.
virtual const IComponentContext * GetComponentContext () const =0
Get access to component context describing all application-specified component information loaded from components registry.
virtual void SetComponentContext (const icomp::IComponentContext *contextPtr, const IComponent *parentPtr, bool isParentOwner)=0
Set component context of this component.
virtual IComponent * GetSubcomponent (const std::string &componentId) const =0
Get access to subcomponent using its ID.
virtual const IComponentContext * GetSubcomponentContext (const std::string &componentId) const =0
Get access to context of subcomponent using its ID.
virtual IComponent * CreateSubcomponent (const std::string &componentId) const =0
Create instance of subcomponent using its ID.
virtual void OnSubcomponentDeleted (const IComponent *subcomponentPtr)=0
Called if subcomponent is removed from memory.
Detailed Description
Main component interface.
Definition at line 28 of file IComponent.h.
Member Function Documentation
virtual IComponent* icomp::IComponent::CreateSubcomponent (const std::string & componentId) const [pure virtual]
Create instance of subcomponent using its ID.
Implemented in icomp::CComponentBase, and icomp::CCompositeComponent.
Referenced by icomp::TComponentCloneWrap< BaseClass >::CloneMe(), icomp::TMultiFactoryMember< Interface >::CreateComponent(), and icomp::TFactoryMember< Interface >::CreateComponent().
virtual const IComponentContext* icomp::IComponent::GetComponentContext () const [pure virtual]
Get access to component context describing all application-specified component information loaded from components registry.
Implemented in icomp::CComponentBase, and icomp::CCompositeComponent.
Referenced by icomp::TMultiAttributeMember< Attribute >::Init(), and icomp::TAttributeMember< Attribute >::Init().
virtual void* icomp::IComponent::GetInterface (const istd::CClassInfo & interfaceType, const std::string & subId = "") [pure virtual]
Get access to specified component interface.
Implemented in icomp::CComponentBase, and icomp::CCompositeComponent.
Referenced by CompCastPtr(), and icomp::CInterfaceManipBase::ExtractInterface().
virtual const IComponent* icomp::IComponent::GetParentComponent (bool ownerOnly = false) const [pure virtual]
Get parent of this component.
Parent is component who created this component. Parent component can be also owner of this component. It means manages life time of this componenent.
Parameters:
ownerOnly indicate, that parent should be returned only if it owns this component.
Returns:
pointer to parent component or NULL if parent is not accessible.
Implemented in icomp::CComponentBase, and icomp::CCompositeComponent.
Referenced by CompCastPtr(), icomp::TMultiFactoryMember< Interface >::CreateComponent(), icomp::TFactoryMember< Interface >::CreateComponent(), icomp::TReferenceMember< Interface >::EnsureInitialized(), icomp::TMultiReferenceMember< Interface >::EnsureInitialized(), icomp::TMultiAttributeMember< Attribute >::Init(), and icomp::TAttributeMember< Attribute >::Init().
virtual IComponent* icomp::IComponent::GetSubcomponent (const std::string & componentId) const [pure virtual]
Get access to subcomponent using its ID.
Implemented in icomp::CComponentBase, and icomp::CCompositeComponent.
Referenced by icomp::TReferenceMember< Interface >::EnsureInitialized(), and icomp::TMultiReferenceMember< Interface >::EnsureInitialized().
virtual const IComponentContext* icomp::IComponent::GetSubcomponentContext (const std::string & componentId) const [pure virtual]
Get access to context of subcomponent using its ID.
Please note, that this does'n create component instance.
Implemented in icomp::CComponentBase, and icomp::CCompositeComponent.
virtual void icomp::IComponent::OnSubcomponentDeleted (const IComponent * subcomponentPtr) [pure virtual]
Called if subcomponent is removed from memory.
Parameters:
subcomponentPtr pointer to component beeing removed. It cannot be NULL.
Implemented in icomp::CComponentBase, and icomp::CCompositeComponent.
Referenced by icomp::TComponentWrap< Component >::~TComponentWrap().
virtual void icomp::IComponent::SetComponentContext (const icomp::IComponentContext * contextPtr, const IComponent * parentPtr, bool isParentOwner) [pure virtual]
Set component context of this component.
Parameters:
contextPtr new value of component context. It can be also NULL. Please avoid to use this method, it is designed for internal use only.
parentPtr pointer to parent component, or NULL if this component has no parent.
isParentOwner indicate, that life cycle of this component is controller by its parent.
Implemented in icomp::CComponentBase, and icomp::CCompositeComponent.
Referenced by icomp::TSimComponentsFactory< Base >::CreateInstance().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/icomp/IComponent.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy