icomp::TMultiAttributeMemberBase< Attribute > Class Template Reference
icomp::TMultiAttributeMemberBase< Attribute > Class Template Reference
Pointer to component attribute.
#include <TMultiAttributeMember.h>
Public Types
typedef Attribute AttributeType
typedef Attribute::ValueType AttributeValueType
typedef void InterfaceType
Public Member Functions
TMultiAttributeMemberBase ()
bool Init (const IComponent *ownerPtr, const IRealAttributeStaticInfo &staticInfo, const IComponent **definitionComponentPtr=NULL)
bool IsValid () const
Check if this attribute is valid.
int GetCount () const
Get number of attributes.
const AttributeValueType & operator[] (int index) const
Access to object pointed by internal pointer.
Detailed Description
template<typename Attribute>
class icomp::TMultiAttributeMemberBase< Attribute >
Pointer to component attribute.
Definition at line 20 of file TMultiAttributeMember.h.
Member Typedef Documentation
template<typename Attribute> typedef Attribute icomp::TMultiAttributeMemberBase< Attribute >::AttributeType
Definition at line 23 of file TMultiAttributeMember.h.
template<typename Attribute> typedef Attribute::ValueType icomp::TMultiAttributeMemberBase< Attribute >::AttributeValueType
Definition at line 24 of file TMultiAttributeMember.h.
template<typename Attribute> typedef void icomp::TMultiAttributeMemberBase< Attribute >::InterfaceType
Reimplemented in icomp::TMultiFactoryMember< Interface >, and icomp::TMultiReferenceMember< Interface >.
Definition at line 25 of file TMultiAttributeMember.h.
Constructor & Destructor Documentation
template<typename Attribute > icomp::TMultiAttributeMemberBase< Attribute >::TMultiAttributeMemberBase ()
Definition at line 56 of file TMultiAttributeMember.h.
Member Function Documentation
template<typename Attribute > int icomp::TMultiAttributeMemberBase< Attribute >::GetCount () const
Get number of attributes.
Definition at line 110 of file TMultiAttributeMember.h.
References NULL.
template<typename Attribute > bool icomp::TMultiAttributeMemberBase< Attribute >::Init (const IComponent * ownerPtr, const IRealAttributeStaticInfo & staticInfo, const IComponent ** definitionComponentPtr = NULL)
Definition at line 63 of file TMultiAttributeMember.h.
References icomp::IComponentContext::GetAttribute(), icomp::IRealAttributeStaticInfo::GetAttributeId(), icomp::IComponent::GetComponentContext(), icomp::IComponent::GetParentComponent(), I_ASSERT, and NULL.
template<typename Attribute > bool icomp::TMultiAttributeMemberBase< Attribute >::IsValid () const
Check if this attribute is valid.
Reimplemented in icomp::TMultiFactoryMember< Interface >, and icomp::TMultiReferenceMember< Interface >.
Definition at line 103 of file TMultiAttributeMember.h.
References NULL.
template<typename Attribute > const TMultiAttributeMemberBase< Attribute >::AttributeValueType & icomp::TMultiAttributeMemberBase< Attribute >::operator[] (int index) const
Access to object pointed by internal pointer.
Reimplemented in icomp::TMultiAttributeMember< TMultiAttribute< QString > >, and icomp::TMultiReferenceMember< Interface >.
Definition at line 122 of file TMultiAttributeMember.h.
References I_ASSERT, and NULL.
The documentation for this class was generated from the following file:
Include/icomp/TMultiAttributeMember.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy