ACF: iqtgui::CGuiComponentBase Class Reference
iqtgui::CGuiComponentBase Class Reference
Base class for classes implementing interface iqtgui::IGuiObject.
#include <CGuiComponentBase.h>
Public Types
typedef icomp::CComponentBase BaseClass
Public Member Functions
CGuiComponentBase ()
bool IsGuiShown () const
virtual bool IsGuiCreated () const
Inform if GUI was initilized.
virtual bool CreateGui (QWidget *parentPtr)
Initialize GUI and connect it to the parent.
virtual bool DestroyGui ()
Release GUI and disconnect it from parent.
virtual QWidget * GetWidget () const
Get access to internal QWidget object.
virtual void OnTryClose (bool *ignoredPtr=NULL)
Called on trying to close application.
Protected Member Functions
virtual bool OnKeyPressed (QKeyEvent *event)
Called from widget event filter when key is pressed.
virtual void OnGuiShown ()
Called from widget event filter when slave widget is shown.
virtual void OnGuiHidden ()
Called from widget event filter when slave widget is hidden.
virtual void OnRetranslate ()
Called when non-GUI elements (like commands) should be retranslated.
virtual void OnGuiRetranslate ()
Called from widget event filter when GUI should be retranslated.
virtual void OnGuiCreated ()
Called just after GUI is initialized.
virtual void OnGuiDestroyed ()
Called just before GUI is released.
virtual bool eventFilter (QObject *sourcePtr, QEvent *eventPtr)
virtual void OnComponentCreated ()
virtual QWidget * InitWidgetToParent (QWidget *parentPtr)=0
Create slave widget object.
Detailed Description
Base class for classes implementing interface iqtgui::IGuiObject.
Definition at line 18 of file CGuiComponentBase.h.
Member Typedef Documentation
typedef icomp::CComponentBase iqtgui::CGuiComponentBase::BaseClass
Reimplemented in icmpstr::CAttributeEditorComp, icmpstr::CPackageOverviewComp, icmpstr::CQuickHelpViewerComp, icmpstr::CRegistryPropEditorComp, iqt2d::CAnnulusParamsGuiComp, iqt2d::CAnnulusSegmentParamsGuiComp, iqt2d::CCircleParamsGuiComp, iqt2d::CLine2dParamsGuiComp, iqt2d::CQuadrangleParamsGuiComp, iqt2d::CRectangleParamsGuiComp, iqt2d::CSceneConnectorGuiComp, iqt2d::CSceneControllerGuiComp, iqt2d::CSceneProviderGuiComp, iqtdoc::CHtmlHelpViewerComp, iqtdoc::CMainWindowGuiComp, iqtdoc::CMultiDocumentWorkspaceGuiComp, iqtdoc::CSingleDocumentWorkspaceGuiComp, iqtgui::CAboutWidgetGuiComp, iqtgui::CComposedGuiComp, iqtgui::CDockWidgetGuiComp, iqtgui::CFilePersistenceGuiComp, iqtgui::CFileSystemExplorerGuiComp, iqtgui::CImagePropertiesFrameComp, iqtgui::CImagePropertyGuiComp, iqtgui::CLogGuiComp, iqtgui::CLoginGuiComp, iqtgui::CObjectPreviewGuiComp, iqtgui::CSimpleMainWindowGuiComp, iqtgui::CSplashScreenGuiComp, iqtgui::CTabbedMultiViewGuiComp, iqtgui::CTabContainerGuiComp, iqtgui::CToolBarWidgetGuiComp, iqtgui::TDesignerGuiCompBase< UI, WidgetType >, iqtgui::TDesignerGuiObserverCompBase< UI, Model, WidgetType >, iqtgui::TGuiComponentBase< WidgetType >, iqtmm::CPhononVideoViewGuiComp, iqtmm::CPlaybackControllerGuiComp, iqtmm::CVideoPlayerGuiComp, iqtprm::CComposedParamsSetGuiComp, iqtprm::CFileNameParamGuiComp, iqtprm::CParamsManagerGuiComp, iqtprm::CSelectableGuiComp, iqtprm::CSelectionParamGuiComp, iqtprm::CSelectionParamIndexGuiComp, iqtprm::CVariableParamGuiComp, iqtproc::CProcessorControlGuiComp, iqtproc::CProgressManagerGuiComp, iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui::CAnnulusSegmentParamsGuiComp, i2d::CAnnulusSegment > >, iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui::CAnnulusParamsGuiComp, i2d::CAnnulus > >, iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui::CCircleParamsGuiComp, i2d::CCircle > >, iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui::CLine2dParamsGuiComp, i2d::CLine2d > >, iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui::CQuadrangleParamsGuiComp, i2d::CQuadrangle > >, iqt2d::TSceneExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< Ui::CRectangleParamsGuiComp, i2d::CRectangle > >, iqtgui::TDesignerGuiCompBase< Ui::CImagePropertiesFrameComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSelectionParamGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSceneProviderGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CFileSystemExplorerGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CObjectPreviewGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CParamsManagerGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CFileNameParamGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CQuadrangleParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CAnnulusParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CVariableParamGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CVideoPlayerGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CSelectionParamIndexGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CAttributeEditorComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CLogGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSelectableGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CLine2dParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CPlaybackControllerGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSceneControllerGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CProgressManagerGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CLoginGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CFilePersistenceGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CRectangleParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CProcessorControlGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CAboutWidgetGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CAnnulusSegmentParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CPackageOverviewComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSceneConnectorGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CCircleParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSplashScreenGuiComp, QSplashScreen >, iqtgui::TDesignerGuiCompBase< Ui::CRegistryPropEditorComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CComposedParamsSetGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CImagePropertyGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CQuickHelpViewerComp >, iqtgui::TDesignerGuiObserverCompBase< Ui::CRectangleParamsGuiComp, i2d::CRectangle >, iqtgui::TDesignerGuiObserverCompBase< Ui::CPackageOverviewComp, IElementSelectionInfo >, iqtgui::TDesignerGuiObserverCompBase< Ui::CAnnulusSegmentParamsGuiComp, i2d::CAnnulusSegment >, iqtgui::TDesignerGuiObserverCompBase< Ui::CFileSystemExplorerGuiComp, iprm::IFileNameParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::CObjectPreviewGuiComp, iprm::IFileNameParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::CComposedParamsSetGuiComp, iprm::IParamsSet >, iqtgui::TDesignerGuiObserverCompBase< Ui::CPlaybackControllerGuiComp, imm::IVideoController >, iqtgui::TDesignerGuiObserverCompBase< Ui::CLogGuiComp, ibase::IMessageContainer >, iqtgui::TDesignerGuiObserverCompBase< Ui::CFileNameParamGuiComp, iprm::IFileNameParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::CImagePropertiesFrameComp, iimg::IBitmap >, iqtgui::TDesignerGuiObserverCompBase< Ui::CSelectionParamIndexGuiComp, iprm::ISelectionParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::CVariableParamGuiComp, iprm::IVariableParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::CSelectableGuiComp, iprm::ISelectionParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::CRegistryPropEditorComp, icomp::IRegistry >, iqtgui::TDesignerGuiObserverCompBase< Ui::CAnnulusParamsGuiComp, i2d::CAnnulus >, iqtgui::TDesignerGuiObserverCompBase< Ui::CCircleParamsGuiComp, i2d::CCircle >, iqtgui::TDesignerGuiObserverCompBase< Ui::CAttributeEditorComp, IElementSelectionInfo >, iqtgui::TDesignerGuiObserverCompBase< Ui::CLine2dParamsGuiComp, i2d::CLine2d >, iqtgui::TDesignerGuiObserverCompBase< Ui::CSelectionParamGuiComp, iprm::ISelectionParam >, iqtgui::TDesignerGuiObserverCompBase< Ui::CImagePropertyGuiComp, iimg::IBitmap >, iqtgui::TDesignerGuiObserverCompBase< Ui::CQuadrangleParamsGuiComp, i2d::CQuadrangle >, iqtgui::TDesignerGuiObserverCompBase< Ui::CParamsManagerGuiComp, iprm::IParamsManager >, iqtgui::TGuiComponentBase< QTextBrowser >, iqtgui::TGuiComponentBase< QWidget >, iqtgui::TGuiComponentBase< QTabWidget >, iqtgui::TGuiComponentBase< Phonon::VideoWidget >, iqtgui::TGuiComponentBase< QToolBar >, iqtgui::TGuiComponentBase< QDockWidget >, iqtgui::TGuiComponentBase< QMdiArea >, iqtgui::TGuiComponentBase< WidgetType >, iqtgui::TGuiComponentBase< QMainWindow >, iqtgui::TGuiComponentBase< QSplashScreen >, iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QMainWindow > >, iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QWidget > >, and iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QMdiArea > >.
Definition at line 24 of file CGuiComponentBase.h.
Constructor & Destructor Documentation
iqtgui::CGuiComponentBase::CGuiComponentBase ()
Member Function Documentation
virtual bool iqtgui::CGuiComponentBase::CreateGui (QWidget * parentPtr) [virtual]
Initialize GUI and connect it to the parent.
Returns:
true if initialization successed.
Implements iqtgui::IGuiObject.
Reimplemented in iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QMainWindow > >, iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QWidget > >, and iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QMdiArea > >.
virtual bool iqtgui::CGuiComponentBase::DestroyGui () [virtual]
Release GUI and disconnect it from parent.
Returns:
true if this operation successed.
Implements iqtgui::IGuiObject.
Reimplemented in iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QMainWindow > >, iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QWidget > >, and iqtgui::TRestorableGuiWrap< iqtgui::TGuiComponentBase< QMdiArea > >.
virtual bool iqtgui::CGuiComponentBase::eventFilter (QObject * sourcePtr, QEvent * eventPtr) [protected, virtual]
Reimplemented in icmpstr::CPackageOverviewComp, iqt2d::CSceneProviderGuiComp, iqtdoc::CMainWindowGuiComp, and iqtdoc::CMultiDocumentWorkspaceGuiComp.
QWidget * iqtgui::CGuiComponentBase::GetWidget () const [inline, virtual]
Get access to internal QWidget object.
Implements iqtgui::IGuiObject.
Definition at line 109 of file CGuiComponentBase.h.
Referenced by iqtgui::TGuiComponentBase< WidgetType >::GetQtWidget(), and iqtgui::TDesignerGuiCompBase< UI, WidgetType >::OnRetranslate().
virtual QWidget* iqtgui::CGuiComponentBase::InitWidgetToParent (QWidget * parentPtr) [protected, pure virtual]
Create slave widget object.
Implemented in iqtgui::TDesignerGuiCompBase< UI, WidgetType >, iqtgui::TGuiComponentBase< WidgetType >, iqtgui::TDesignerGuiCompBase< Ui::CImagePropertiesFrameComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSelectionParamGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSceneProviderGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CFileSystemExplorerGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CObjectPreviewGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CParamsManagerGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CFileNameParamGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CQuadrangleParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CAnnulusParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CVariableParamGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CVideoPlayerGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CSelectionParamIndexGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CAttributeEditorComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CLogGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSelectableGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CLine2dParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CPlaybackControllerGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSceneControllerGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CProgressManagerGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CLoginGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CFilePersistenceGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CRectangleParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CProcessorControlGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CAboutWidgetGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CAnnulusSegmentParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CPackageOverviewComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSceneConnectorGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CCircleParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSplashScreenGuiComp, QSplashScreen >, iqtgui::TDesignerGuiCompBase< Ui::CRegistryPropEditorComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CComposedParamsSetGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CImagePropertyGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CQuickHelpViewerComp >, iqtgui::TGuiComponentBase< QTextBrowser >, iqtgui::TGuiComponentBase< QWidget >, iqtgui::TGuiComponentBase< QTabWidget >, iqtgui::TGuiComponentBase< Phonon::VideoWidget >, iqtgui::TGuiComponentBase< QToolBar >, iqtgui::TGuiComponentBase< QDockWidget >, iqtgui::TGuiComponentBase< QMdiArea >, iqtgui::TGuiComponentBase< WidgetType >, iqtgui::TGuiComponentBase< QMainWindow >, and iqtgui::TGuiComponentBase< QSplashScreen >.
virtual bool iqtgui::CGuiComponentBase::IsGuiCreated () const [virtual]
Inform if GUI was initilized.
Implements iqtgui::IGuiObject.
Referenced by iqtgui::TDesignerGuiCompBase< UI, WidgetType >::InitWidgetToParent().
bool iqtgui::CGuiComponentBase::IsGuiShown () const [inline]
Definition at line 101 of file CGuiComponentBase.h.
virtual void iqtgui::CGuiComponentBase::OnComponentCreated () [protected, virtual]
Reimplemented from icomp::CComponentBase.
Reimplemented in iqt2d::CSceneConnectorGuiComp, iqt2d::CSceneProviderGuiComp, iqtdoc::CMainWindowGuiComp, iqtdoc::CMultiDocumentWorkspaceGuiComp, iqtdoc::CSingleDocumentWorkspaceGuiComp, iqtmm::CPlaybackControllerGuiComp, iqtmm::CVideoPlayerGuiComp, and iqtproc::CProcessorControlGuiComp.
virtual void iqtgui::CGuiComponentBase::OnGuiCreated () [protected, virtual]
Called just after GUI is initialized.
Reimplemented in icmpstr::CAttributeEditorComp, icmpstr::CPackageOverviewComp, icmpstr::CQuickHelpViewerComp, icmpstr::CRegistryPropEditorComp, iqt2d::CAnnulusParamsGuiComp, iqt2d::CAnnulusSegmentParamsGuiComp, iqt2d::CSceneConnectorGuiComp, iqt2d::CSceneControllerGuiComp, iqt2d::CSceneProviderGuiComp, iqtdoc::CMainWindowGuiComp, iqtdoc::CMultiDocumentWorkspaceGuiComp, iqtdoc::CSingleDocumentWorkspaceGuiComp, iqtgui::CAboutWidgetGuiComp, iqtgui::CComposedGuiComp, iqtgui::CDockWidgetGuiComp, iqtgui::CFilePersistenceGuiComp, iqtgui::CFileSystemExplorerGuiComp, iqtgui::CLogGuiComp, iqtgui::CLoginGuiComp, iqtgui::CObjectPreviewGuiComp, iqtgui::CSimpleMainWindowGuiComp, iqtgui::CSplashScreenGuiComp, iqtgui::CTabContainerGuiComp, iqtgui::CToolBarWidgetGuiComp, iqtmm::CPhononVideoViewGuiComp, iqtmm::CPlaybackControllerGuiComp, iqtmm::CVideoPlayerGuiComp, iqtprm::CComposedParamsSetGuiComp, iqtprm::CFileNameParamGuiComp, iqtprm::CSelectableGuiComp, iqtprm::CSelectionParamGuiComp, iqtprm::CVariableParamGuiComp, iqtproc::CProcessorControlGuiComp, iqtproc::CProgressManagerGuiComp, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CSelectableGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::ISelectionParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CCircleParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CCircle > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CFileSystemExplorerGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IFileNameParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CAttributeEditorComp, QWidget >, imod::TSingleModelObserverBase< IElementSelectionInfo > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CRegistryPropEditorComp, QWidget >, imod::TSingleModelObserverBase< icomp::IRegistry > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CObjectPreviewGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IFileNameParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CAnnulusSegmentParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CAnnulusSegment > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CFileNameParamGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IFileNameParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CPackageOverviewComp, QWidget >, imod::TSingleModelObserverBase< IElementSelectionInfo > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< UI, WidgetType >, imod::TSingleModelObserverBase< Model > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CVariableParamGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IVariableParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CRectangleParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CRectangle > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CParamsManagerGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IParamsManager > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CSelectionParamIndexGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::ISelectionParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CComposedParamsSetGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IParamsSet > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CPlaybackControllerGuiComp, QWidget >, imod::TSingleModelObserverBase< imm::IVideoController > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CSelectionParamGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::ISelectionParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CLogGuiComp, QWidget >, imod::TSingleModelObserverBase< ibase::IMessageContainer > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CAnnulusParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CAnnulus > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CLine2dParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CLine2d > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CImagePropertiesFrameComp, QWidget >, imod::TSingleModelObserverBase< iimg::IBitmap > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CImagePropertyGuiComp, QWidget >, imod::TSingleModelObserverBase< iimg::IBitmap > >, and iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CQuadrangleParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CQuadrangle > >.
virtual void iqtgui::CGuiComponentBase::OnGuiDestroyed () [protected, virtual]
Called just before GUI is released.
Reimplemented in icmpstr::CAttributeEditorComp, iqt2d::CAnnulusParamsGuiComp, iqt2d::CAnnulusSegmentParamsGuiComp, iqt2d::CSceneConnectorGuiComp, iqt2d::CSceneControllerGuiComp, iqt2d::CSceneProviderGuiComp, iqtdoc::CMainWindowGuiComp, iqtdoc::CMultiDocumentWorkspaceGuiComp, iqtdoc::CSingleDocumentWorkspaceGuiComp, iqtgui::CDockWidgetGuiComp, iqtgui::CObjectPreviewGuiComp, iqtgui::CSimpleMainWindowGuiComp, iqtgui::CTabContainerGuiComp, iqtgui::CToolBarWidgetGuiComp, iqtmm::CPhononVideoViewGuiComp, iqtmm::CVideoPlayerGuiComp, iqtprm::CComposedParamsSetGuiComp, iqtprm::CSelectionParamGuiComp, iqtprm::CVariableParamGuiComp, iqtproc::CProcessorControlGuiComp, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CSelectableGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::ISelectionParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CCircleParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CCircle > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CFileSystemExplorerGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IFileNameParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CAttributeEditorComp, QWidget >, imod::TSingleModelObserverBase< IElementSelectionInfo > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CRegistryPropEditorComp, QWidget >, imod::TSingleModelObserverBase< icomp::IRegistry > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CObjectPreviewGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IFileNameParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CAnnulusSegmentParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CAnnulusSegment > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CFileNameParamGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IFileNameParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CPackageOverviewComp, QWidget >, imod::TSingleModelObserverBase< IElementSelectionInfo > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< UI, WidgetType >, imod::TSingleModelObserverBase< Model > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CVariableParamGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IVariableParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CRectangleParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CRectangle > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CParamsManagerGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IParamsManager > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CSelectionParamIndexGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::ISelectionParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CComposedParamsSetGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IParamsSet > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CPlaybackControllerGuiComp, QWidget >, imod::TSingleModelObserverBase< imm::IVideoController > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CSelectionParamGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::ISelectionParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CLogGuiComp, QWidget >, imod::TSingleModelObserverBase< ibase::IMessageContainer > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CAnnulusParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CAnnulus > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CLine2dParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CLine2d > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CImagePropertiesFrameComp, QWidget >, imod::TSingleModelObserverBase< iimg::IBitmap > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CImagePropertyGuiComp, QWidget >, imod::TSingleModelObserverBase< iimg::IBitmap > >, and iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CQuadrangleParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CQuadrangle > >.
virtual void iqtgui::CGuiComponentBase::OnGuiHidden () [protected, virtual]
Called from widget event filter when slave widget is hidden.
Reimplemented in iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CSelectableGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::ISelectionParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CCircleParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CCircle > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CFileSystemExplorerGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IFileNameParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CAttributeEditorComp, QWidget >, imod::TSingleModelObserverBase< IElementSelectionInfo > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CRegistryPropEditorComp, QWidget >, imod::TSingleModelObserverBase< icomp::IRegistry > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CObjectPreviewGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IFileNameParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CAnnulusSegmentParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CAnnulusSegment > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CFileNameParamGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IFileNameParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CPackageOverviewComp, QWidget >, imod::TSingleModelObserverBase< IElementSelectionInfo > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< UI, WidgetType >, imod::TSingleModelObserverBase< Model > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CVariableParamGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IVariableParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CRectangleParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CRectangle > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CParamsManagerGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IParamsManager > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CSelectionParamIndexGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::ISelectionParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CComposedParamsSetGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IParamsSet > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CPlaybackControllerGuiComp, QWidget >, imod::TSingleModelObserverBase< imm::IVideoController > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CSelectionParamGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::ISelectionParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CLogGuiComp, QWidget >, imod::TSingleModelObserverBase< ibase::IMessageContainer > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CAnnulusParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CAnnulus > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CLine2dParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CLine2d > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CImagePropertiesFrameComp, QWidget >, imod::TSingleModelObserverBase< iimg::IBitmap > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CImagePropertyGuiComp, QWidget >, imod::TSingleModelObserverBase< iimg::IBitmap > >, and iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CQuadrangleParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CQuadrangle > >.
virtual void iqtgui::CGuiComponentBase::OnGuiRetranslate () [protected, virtual]
Called from widget event filter when GUI should be retranslated.
Reimplemented in iqtgui::CDockWidgetGuiComp.
virtual void iqtgui::CGuiComponentBase::OnGuiShown () [protected, virtual]
Called from widget event filter when slave widget is shown.
Reimplemented in iqtdoc::CHtmlHelpViewerComp, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CSelectableGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::ISelectionParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CCircleParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CCircle > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CFileSystemExplorerGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IFileNameParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CAttributeEditorComp, QWidget >, imod::TSingleModelObserverBase< IElementSelectionInfo > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CRegistryPropEditorComp, QWidget >, imod::TSingleModelObserverBase< icomp::IRegistry > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CObjectPreviewGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IFileNameParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CAnnulusSegmentParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CAnnulusSegment > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CFileNameParamGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IFileNameParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CPackageOverviewComp, QWidget >, imod::TSingleModelObserverBase< IElementSelectionInfo > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< UI, WidgetType >, imod::TSingleModelObserverBase< Model > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CVariableParamGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IVariableParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CRectangleParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CRectangle > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CParamsManagerGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IParamsManager > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CSelectionParamIndexGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::ISelectionParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CComposedParamsSetGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::IParamsSet > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CPlaybackControllerGuiComp, QWidget >, imod::TSingleModelObserverBase< imm::IVideoController > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CSelectionParamGuiComp, QWidget >, imod::TSingleModelObserverBase< iprm::ISelectionParam > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CLogGuiComp, QWidget >, imod::TSingleModelObserverBase< ibase::IMessageContainer > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CAnnulusParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CAnnulus > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CLine2dParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CLine2d > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CImagePropertiesFrameComp, QWidget >, imod::TSingleModelObserverBase< iimg::IBitmap > >, iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CImagePropertyGuiComp, QWidget >, imod::TSingleModelObserverBase< iimg::IBitmap > >, and iqtgui::TGuiObserverWrap< TDesignerGuiCompBase< Ui::CQuadrangleParamsGuiComp, QWidget >, imod::TSingleModelObserverBase< i2d::CQuadrangle > >.
virtual bool iqtgui::CGuiComponentBase::OnKeyPressed (QKeyEvent * event) [protected, virtual]
Called from widget event filter when key is pressed.
Returns:
if event was consumed returns true, otherwise false.
virtual void iqtgui::CGuiComponentBase::OnRetranslate () [protected, virtual]
Called when non-GUI elements (like commands) should be retranslated.
Reimplemented in icmpstr::CPackageOverviewComp, iqtdoc::CMainWindowGuiComp, iqtdoc::CMultiDocumentWorkspaceGuiComp, iqtgui::CSimpleMainWindowGuiComp, iqtgui::TDesignerGuiCompBase< UI, WidgetType >, iqtgui::TDesignerGuiCompBase< Ui::CImagePropertiesFrameComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSelectionParamGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSceneProviderGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CFileSystemExplorerGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CObjectPreviewGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CParamsManagerGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CFileNameParamGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CQuadrangleParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CAnnulusParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CVariableParamGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CVideoPlayerGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CSelectionParamIndexGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CAttributeEditorComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CLogGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSelectableGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CLine2dParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CPlaybackControllerGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSceneControllerGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CProgressManagerGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CLoginGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CFilePersistenceGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CRectangleParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CProcessorControlGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CAboutWidgetGuiComp >, iqtgui::TDesignerGuiCompBase< Ui::CAnnulusSegmentParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CPackageOverviewComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSceneConnectorGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CCircleParamsGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CSplashScreenGuiComp, QSplashScreen >, iqtgui::TDesignerGuiCompBase< Ui::CRegistryPropEditorComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CComposedParamsSetGuiComp, QWidget >, iqtgui::TDesignerGuiCompBase< Ui::CImagePropertyGuiComp, QWidget >, and iqtgui::TDesignerGuiCompBase< Ui::CQuickHelpViewerComp >.
Referenced by iqtgui::TDesignerGuiCompBase< UI, WidgetType >::OnRetranslate().
virtual void iqtgui::CGuiComponentBase::OnTryClose (bool * ignoredPtr = NULL) [virtual]
Called on trying to close application.
Parameters:
ignoredPtr if it is not NULL, ignoring of close is allowed. In this case implementation should set pointed value to true.
Implements iqtgui::IGuiObject.
Reimplemented in iqtdoc::CMultiDocumentWorkspaceGuiComp, iqtdoc::CSingleDocumentWorkspaceGuiComp, and iqtgui::CSimpleMainWindowGuiComp.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/iqtgui/CGuiComponentBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy