istd::TSmartPtr< Type, Accessor >::RefCounter Class Reference
istd::TSmartPtr< Type, Accessor >::RefCounter Class Reference
#include <TSmartPtr.h>
Public Types
typedef RefCountBase BaseClass
Public Types inherited from istd::TTransPtr< Type >::RefCountBase
typedef TPointerBase< Type > BaseClass
Public Member Functions
RefCounter (Type *pointer)
virtual void OnAttached ()
Called if new pointer is attached to this internal handler.
virtual void OnDetached ()
Called if pointer is detached from this internal handler.
Public Member Functions inherited from istd::TTransPtr< Type >::RefCountBase
RefCountBase (Type *pointer)
virtual ~RefCountBase ()
Public Member Functions inherited from istd::TPointerBase< Type >
TPointerBase (Type *ptr=NULL)
Construct and assign internal pointer.
void SetPtr (Type *ptr)
Set value of internal stored pointer.
void Reset ()
Set internal pointer value to NULL.
Type * GetPtr () const
Return access to internal stored pointer.
bool IsValid () const
Check if internal pointer not NULL.
void Swap (TPointerBase &ptr)
Swap two pointers.
Type & operator* () const
Get an access to object pointed at.
template<class CastedType >
CastedType Cast () const
Type * operator-> () const
bool operator== (const TPointerBase< Type > &ptr) const
bool operator!= (const TPointerBase< Type > &ptr) const
bool operator< (const TPointerBase< Type > &ptr) const
bool operator> (const TPointerBase< Type > &ptr) const
bool operator<= (const TPointerBase< Type > &ptr) const
bool operator>= (const TPointerBase< Type > &ptr) const
bool operator== (const Type *ptr) const
bool operator!= (const Type *ptr) const
bool operator< (const Type *ptr) const
bool operator> (const Type *ptr) const
bool operator<= (const Type *ptr) const
bool operator>= (const Type *ptr) const
Additional Inherited Members
Protected Member Functions inherited from istd::TPointerBase< Type >
TPointerBase< Type > & operator= (const TPointerBase< Type > ptr)
Type *& GetPtrRef ()
Detailed Description
template<class Type, class Accessor = DefaultAccessor<Type>>
class istd::TSmartPtr< Type, Accessor >::RefCounter
Definition at line 64 of file TSmartPtr.h.
Member Typedef Documentation
template<class Type, class Accessor = DefaultAccessor<Type>> typedef RefCountBase istd::TSmartPtr< Type, Accessor >::RefCounter::BaseClass
Definition at line 67 of file TSmartPtr.h.
Constructor & Destructor Documentation
template<class Type, class Accessor = DefaultAccessor<Type>> istd::TSmartPtr< Type, Accessor >::RefCounter::RefCounter (Type * pointer) inline
Definition at line 69 of file TSmartPtr.h.
Member Function Documentation
template<class Type, class Accessor = DefaultAccessor<Type>> virtual void istd::TSmartPtr< Type, Accessor >::RefCounter::OnAttached () inline virtual
Called if new pointer is attached to this internal handler.
Implements istd::TTransPtr< Type >::RefCountBase.
Definition at line 76 of file TSmartPtr.h.
References istd::TPointerBase< Type >::IsValid().
template<class Type, class Accessor = DefaultAccessor<Type>> virtual void istd::TSmartPtr< Type, Accessor >::RefCounter::OnDetached () inline virtual
Called if pointer is detached from this internal handler.
Implements istd::TTransPtr< Type >::RefCountBase.
Definition at line 84 of file TSmartPtr.h.
References istd::TPointerBase< Type >::GetPtr(), and istd::TPointerBase< Type >::IsValid().
The documentation for this class was generated from the following file:
Include/istd/TSmartPtr.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy