ACF: icmm::TColorGradient< GradientFunction > Class Template Reference
icmm::TColorGradient< GradientFunction > Class Template Reference
Simple implementation of gradient based on interpolation beetween the start und end colors.
#include <TColorGradient.h>
Public Types
typedef
IColorTransformation::ResultType GradientColor
Public Member Functions
TColorGradient (const GradientColor &startColor, const GradientColor &endColor)
virtual bool GetValueAt (const ArgumentType &argument, ResultType &result) const
Get function value for specified argument value.
virtual ResultType GetValueAt (const ArgumentType &argument) const
Get function value for specified argument value.
Detailed Description
template<class GradientFunction>
class icmm::TColorGradient< GradientFunction >
Simple implementation of gradient based on interpolation beetween the start und end colors.
Definition at line 28 of file TColorGradient.h.
Member Typedef Documentation
template<class GradientFunction > typedef IColorTransformation::ResultType icmm::TColorGradient< GradientFunction >::GradientColor
Definition at line 31 of file TColorGradient.h.
Constructor & Destructor Documentation
template<class GradientFunction > icmm::TColorGradient< GradientFunction >::TColorGradient (const GradientColor & startColor, const GradientColor & endColor) [inline]
Definition at line 46 of file TColorGradient.h.
Member Function Documentation
template<class GradientFunction > TColorGradient< GradientFunction >::ResultType icmm::TColorGradient< GradientFunction >::GetValueAt (const ArgumentType & argument) const [inline, virtual]
Get function value for specified argument value.
This overloaded menthod is provided only for convinence.
Parameters:
argument function argument.
Returns:
function value for specified argument.
Implements imath::TIMathFunction< icmm::CVarColor, icmm::CVarColor >.
Definition at line 84 of file TColorGradient.h.
References imath::CVarVector::GetElementsCount(), and icmm::TColorGradient< GradientFunction >::GetValueAt().
template<class GradientFunction > bool icmm::TColorGradient< GradientFunction >::GetValueAt (const ArgumentType & argument, ResultType & result) const [inline, virtual]
Get function value for specified argument value.
Parameters:
argument function argument.
result function value for specified argument.
Returns:
true if result was correctly calculated.
Implements imath::TIMathFunction< icmm::CVarColor, icmm::CVarColor >.
Definition at line 56 of file TColorGradient.h.
References imath::CVarVector::GetElementsCount(), and I_ASSERT.
Referenced by icmm::TColorGradient< GradientFunction >::GetValueAt().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/Acf/Include/icmm/TColorGradient.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy