ACF: Main concepts and implementations
Main concepts and implementations
[ACF]
If you can learn how to use ACF you should begin with elements defined in this module.
Classes
class ibase::CSize
Definition of simple 2D size based on integer values.
class ibase::IApplication
Main entry point of component-based application.
class ibase::IApplicationInfo
This interface provides some information about the application.
class ibase::IMessageConsumer
Common interface for a message container consuming message objects.
class ibase::IProcessExecutor
Main entry point of component-based application.
class icomp::CComponentBase
Base class for component implementation.
class iser::IArchive
Represent input/output persistence archive.
class iser::ISerializable
Common class for all classes which objects can be archived or restored from archive.
class istd::CClassInfo
Represents platform independent type info and provide set of static class manipulation functions.
class istd::CRange
Implementation of a abstract range defined by two values - minimum and maximum.
class istd::CString
Standard ACF string definition.
class istd::IPolymorphic
Base interface for all used interfaces and implementations.
class istd::TArray< Element, Dimensions >
Multidimensional array with fixed number of dimensions.
class istd::TChangeNotifier< Changeable >
Help class which provides the automatic update mechanism of the model.
class istd::TDelPtr< Type, Accessor >
Pointer wrapper providing automatic deleting pointed object during destruction.
class istd::TSmartPtr< Type, Accessor >
Implementation of a smart pointer.
Namespaces
namespace icomp
Package with interfaces and class used for components concept.
namespace imath
Package with mathematical functions and algebraical primitives.
namespace imod
This namespace containes basic implementation of Model/Observer design pattern This package is system independent.
namespace iser
Contains general persistence mechanism with basic archives implementations.
namespace istd
Standard library.
Typedefs
typedef TLoggerCompWrap
< icomp::CComponentBase > ibase::CLoggerComponentBase
Type defininig base class for simple components outputing log messages.
Functions
template<typename T >
const T & istd::Min (const T &value1, const T &value2)
Define own min function to avoid conflicts between STL and Microsoft macros.
template<typename T >
const T & istd::Max (const T &value1, const T &value2)
Define own max function to avoid conflicts between STL and Microsoft macros.
Variables
static const double I_PI = 3.14159265358979323846
Mathematical constant value PI.
static const double I_2PI = 6.2831853071795864769
Mathematical constant value 2 * PI.
Detailed Description
If you can learn how to use ACF you should begin with elements defined in this module.
Typedef Documentation
typedef TLoggerCompWrap<icomp::CComponentBase> ibase::CLoggerComponentBase
Type defininig base class for simple components outputing log messages.
Definition at line 93 of file TLoggerCompWrap.h.
Function Documentation
template<typename T > const T& istd::Max (const T & value1, const T & value2) [inline]
Define own max function to avoid conflicts between STL and Microsoft macros.
Definition at line 41 of file istd.h.
Referenced by iproc::TMemCachedProducerComp< Key, CacheObject >::CleanElementList(), imath::TVector< Size, Element >::GetMaximal(), imath::TFastVector< MaxSize, Element >::GetMaximal(), istd::IsBeetween(), istd::Max3(), and istd::Max4().
template<typename T > const T& istd::Min (const T & value1, const T & value2) [inline]
Define own min function to avoid conflicts between STL and Microsoft macros.
Definition at line 24 of file istd.h.
Referenced by imath::TMathVectorWrap< Base >::GetDotProduct(), imath::TFastVector< MaxSize, Element >::GetDotProduct(), istd::TVarArray< Element >::GetElementIndex(), imath::TFastVector< MaxSize, Element >::GetMaximal(), imath::TVector< Size, Element >::GetMinimal(), imath::TFastVector< MaxSize, Element >::GetMinimal(), imath::TMatrix< Width, Height, Element >::GetTriangleDecomposed(), istd::IsBeetween(), imath::TMathVectorWrap< Base >::operator+(), imath::TMathVectorWrap< Base >::operator+=(), imath::TMathVectorWrap< Base >::operator-(), imath::TMathVectorWrap< Base >::operator-=(), imath::TMathVectorWrap< Base >::operator<(), imath::TFastVector< MaxSize, Element >::operator<(), imath::TMathVectorWrap< Base >::operator<=(), imath::TFastVector< MaxSize, Element >::operator<=(), imath::TMathVectorWrap< Base >::operator>(), imath::TFastVector< MaxSize, Element >::operator>(), imath::TMathVectorWrap< Base >::operator>=(), imath::TFastVector< MaxSize, Element >::operator>=(), imath::TFastVector< MaxSize, Element >::SetElementsFrom(), icmm::TComposedColor< Size >::TComposedColor(), imath::TMathVectorWrap< Base >::Translate(), and imath::TFastVector< MaxSize, Element >::Translate().
Variable Documentation
const double I_2PI = 6.2831853071795864769 [static]
Mathematical constant value 2 * PI.
Definition at line 20 of file imath.h.
const double I_PI = 3.14159265358979323846 [static]
Mathematical constant value PI.
Definition at line 13 of file imath.h.
Referenced by imath::GetDegreeFromRadian(), and imath::GetRadianFromDegree().
© 2007-2011 Witold Gantzke and Kirill Lepskiy