istd Namespace Reference
istd Namespace Reference
Main concepts and implementations
Standard library.
Classes
class CBase64
Base64 converter.
class CBitManip
class CChangeDelegator
Delegates calls of IChangeable methods to the given slave.
class CClassInfo
Represents platform independent type info and provide set of static class manipulation functions.
class CCrcCalculator
class CFastBinaryIndex
class CIdManipBase
class CIndex2d
class CRandomNumber
class CRange
Implementation of a abstract range defined by two values - minimum and maximum.
class CStaticServicesProvider
Manage list of global services.
class CString
Standard ACF string definition.
class CVarIndex
Multidimensional index used to addressing index.
class IChangeable
Common interface for model objects, which can be changed.
class IChangeDelegator
Common interface for all classes that supports delegation of their updates to another class.
class IContainerInfo
Common interface for all container implementations.
class IFactoryInfo
Base interface providing info about factorisable objects.
class ILocalizer
Common interface for a simple string localization.
class ILogger
Common interface for classes sending some log info.
class IPolymorphic
Base interface for all used interfaces and implementations.
class IServicesProvider
Allow access to service implementation.
class CGroupRegistrator
class ITrace
Provide system logging.
class TArray
Multidimensional array with fixed number of dimensions.
class TCachedUpdateManagerWrap
Help wrapper class supporting of cached parts.
class TCascadedMap
Helper class used to manage list of many connected in cascade maps.
class TChangeBinder
Binder of two istd::IChangeable implementations.
class TChangeDelegator
Binder of some istd::IChangeable implementation and changing delegator.
class TChangeNotifier
Help class which provides the automatic update mechanism of the model.
class TComposedFactory
Standard generic implementation of the composed factory.
class TDelPtr
Pointer wrapper providing automatic deleting pointed object during destruction.
class TIFactory
Common interface for a factory implementation.
class TIHierarchical
Common interface to define the hierarchical graph structures.
class TIMap
class TIndex
Multidimensional index used to addressing fixed-size array.
class TOptDelPtr
Pointer wrapper providing automatic deleting pointed object during destruction.
class TOptDeleteAdapter
Optional delete adapter.
class TOptPointerVector
Implementation of a special pointer container, which controls the live cycle of the pointer object, but allows optional pointer removing.
class DefaultAccessor
class ArrayAccessor
class TPointerBase
Implementation of pointer wrapper.
class TDeleteAdapter
Default delete adapter.
class TPointerVector
Implementation of a pointer container, which controls the live cycle of the pointer object.
class TSingleFactory
Template based object factory interface.
class TSmartPtr
Implementation of a smart pointer.
class TTransPtr
Implementation of data transfer smart pointer.
class TUpdateManagerWrap
Help wrapper class allowing to reduce nested update notifying by counting of changes.
class TVarArray
Multidimensional array with fixed number of dimensions.
Typedefs
typedef std::vector< CString > CStringList
typedef TChangeNotifier
< IChangeable > CChangeNotifier
Basic change notifier for unspecified type.
typedef TIFactory< void > IVoidFactory
typedef TIFactory
< istd::IPolymorphic > IFactory
typedef TIHierarchical
< IPolymorphic > IHierarchical
typedef TVarArray< double > CVarArray
Enumerations
enum RepositoryState { RS_ORIGINAL_VERSION = 2099, RS_DIRTY_FLAG = 0, RS_USE_VERSION = RS_ORIGINAL_VERSION + RS_DIRTY_FLAG }
enum TraceLevel { InfoLevel, WarningLevel, ErrorLevel, CriticalLevel }
Functions
template<typename Service >
Service * GetService ()
Allow to access some global service from anywhere.
template<typename Service >
TTransPtr< Service > CreateService ()
Allow to create a new service instance from anywhere.
template<typename T >
const T & Min (const T &value1, const T &value2)
Define own min function to avoid conflicts between STL and Microsoft macros.
template<typename T >
const T & Max (const T &value1, const T &value2)
Define own max function to avoid conflicts between STL and Microsoft macros.
template<typename T >
const T & Max3 (const T &value1, const T &value2, const T &value3)
template<typename T >
const T & Max4 (const T &value1, const T &value2, const T &value3, const T &value4)
template<typename T >
bool IsBeetween (const T &value, const T &value1, const T &value2)
Returns true, if the value value is in intervall (value1, value2) or (value2, value1).
void OnSoftwareError (const char *fileName, int line)
bool CheckTraceEnabled (TraceLevel level, const char *groupId)
void SendTraceMessage (TraceLevel level, const char *groupId, const char *message, const char *fileName, int line)
Detailed Description
Standard library.
Contains the system indenendent primitives and basic implementations.
Typedef Documentation
typedef std::vector<CString> istd::CStringList
Definition at line 146 of file CString.h.
typedef TVarArray<double> istd::CVarArray
Definition at line 485 of file TVarArray.h.
typedef TIFactory<istd::IPolymorphic> istd::IFactory
Definition at line 31 of file TIFactory.h.
typedef TIHierarchical<IPolymorphic> istd::IHierarchical
Definition at line 61 of file TIHierarchical.h.
typedef TIFactory<void> istd::IVoidFactory
Definition at line 30 of file TIFactory.h.
Enumeration Type Documentation
enum istd::RepositoryState
Enumerator:
RS_ORIGINAL_VERSION
RS_DIRTY_FLAG
RS_USE_VERSION
Definition at line 9 of file AcfVersion.h.
enum istd::TraceLevel
Enumerator:
InfoLevel
WarningLevel
ErrorLevel
CriticalLevel
Definition at line 87 of file istd.h.
Function Documentation
bool istd::CheckTraceEnabled (TraceLevel level, const char * groupId)
template<typename T > bool istd::IsBeetween (const T & value, const T & value1, const T & value2) [inline]
Returns true, if the value value is in intervall (value1, value2) or (value2, value1).
Definition at line 70 of file istd.h.
References Max(), and Min().
template<typename T > const T& istd::Max3 (const T & value1, const T & value2, const T & value3) [inline]
Definition at line 53 of file istd.h.
References Max().
Referenced by Max4().
template<typename T > const T& istd::Max4 (const T & value1, const T & value2, const T & value3, const T & value4) [inline]
Definition at line 60 of file istd.h.
References Max(), and Max3().
void istd::OnSoftwareError (const char * fileName, int line)
void istd::SendTraceMessage (TraceLevel level, const char * groupId, const char * message, const char * fileName, int line)
© 2007-2011 Witold Gantzke and Kirill Lepskiy