ACF: iqt Namespace Reference
iqt Namespace Reference
This namespace contains standard classes based on Qt.
Classes
class CApplicationSettingsProviderComp
class CBitmap
Bitmap implementation based on Qt QImage.
class CBitmapLoaderComp
Bitmap loader component implementing interfaces iser::IFileLoader.
class CBitmapSurface
Bitmap implementation based on Qt QImage.
class CClipboardSerializerComp
class CCopyProcessorComp
Copy files from one directory to another one.
class CCriticalSection
class CDateTime
Implementation of isys::IDateTime interface based on Qt.
class CDefaultRegistryLoaderProvider
Loads component packages from dynamic link libraries.
class CDefaultServicesProvider
Default services provider for qt based services.
class CDirList
This class serves for creation of the list of directories in a given root directory.
class CDllFunctionsProvider
Provide access to public functions in DLL.
class CFileInfoCopyComp
Copy of text files with some tags substitution and optional license attachment.
class CFileList
This class serves for creation of the list of files in a given root directory.
class CFileListProviderComp
Provide list of file pathes using recursive search of some file directory.
class CFileSystem
Implementation of file system information based on QT.
class CIniSettingsProviderComp
Provides settings from INI file.
class CLocalizer
An timer implementation for Qt library.
class CNetworkWriteArchive
class CPackagesLoaderComp
Loads component packages from dynamic link libraries.
class CProcessEnvironment
Qt-based implementation of application environment information.
class CProcessExecutorComp
Component for execution of an external application.
class CReflectedBitmapBase
Implementation of bitmap storing internal additionaly QImage object reflecting state of main bitmap after conversion to Qt formats.
class CRegistriesManagerComp
Loads component packages from dynamic link libraries.
class CRenderedObjectFileLoaderComp
class CSafeNotifier
Implementation of model changes notification between different threads.
class NotificationTarget
class CSettingsArchiveBase
class CSettingsReadArchive
class CSettingsSerializerComp
Store and load parameter as global settings.
class CSettingsWriteArchive
Archive class for serialization based on QSettings implementation.
class CSignalBlocker
Simple helper class blocking Qt signals of specified QObject.
class CSystemEnvironment
System implementation of ISystemEnvironment interface on Qt plattform.
class CTimer
An timer implementation for Qt library.
class CTrace
class CTranslationManagerComp
class CXmlFileReadArchive
Qt-based implementation of archive reading from XML file.
class CXmlFileWriteArchive
Qt-based implementation of archive for writing in XML format.
class CXslSerializerComp
Template implementation of file serializer using loading and storing archive implementation.
class CXslTransformationReadArchive
Qt-based implementation of archive reading from XML file.
class CXslTransformationWriteArchive
Qt-based implementation of archive for writing in XML format.
class IQImageProvider
class ISettingsProvider
Interface for access the application settings object.
class ITranslationManager
Functions
QString GetQString (const istd::CString &string)
istd::CString GetCString (const QString &string)
QStringList GetQStringList (const istd::CStringList &stringList)
istd::CStringList GetCStringList (const QStringList &stringList)
QSize GetQSize (const istd::CIndex2d &size)
istd::CIndex2d GetCIndex2d (const QSize &size)
QPoint GetQPoint (const istd::CIndex2d &position)
istd::CIndex2d GetCIndex2d (const QPoint &position)
QPointF GetQPointF (const i2d::CVector2d &position)
i2d::CVector2d GetCVector2d (const QPointF &position)
QRectF GetQRectF (const i2d::CRectangle &rect)
i2d::CRectangle GetCRectangle (const QRectF &rect)
i2d::CLine2d GetCLine2d (const QLine &line)
QLine GetQLine (const i2d::CLine2d &line)
i2d::CLine2d GetCLine2d (const QLineF &line)
QLineF GetQLineF (const i2d::CLine2d &line)
isys::CFileInfo GetCFileInfo (const QFileInfo &fileInfo)
QFileInfo GetQFileInfo (const isys::CFileInfo &fileInfo)
QDateTime GetQDateTime (const isys::IDateTime &dateTime)
isys::CSimpleDateTime GetCSimpleDateTime (const QDateTime &dateTime)
Detailed Description
This namespace contains standard classes based on Qt.
Function Documentation
isys::CFileInfo iqt::GetCFileInfo (const QFileInfo & fileInfo)
istd::CIndex2d iqt::GetCIndex2d (const QSize & size)
Referenced by iqt2d::CImageShape::GetSize().
istd::CIndex2d iqt::GetCIndex2d (const QPoint & position)
i2d::CLine2d iqt::GetCLine2d (const QLine & line)
i2d::CLine2d iqt::GetCLine2d (const QLineF & line)
i2d::CRectangle iqt::GetCRectangle (const QRectF & rect)
Referenced by iqt2d::TShapeBase< GraphicsItemClass >::itemChange().
isys::CSimpleDateTime iqt::GetCSimpleDateTime (const QDateTime & dateTime)
istd::CString iqt::GetCString (const QString & string)
Referenced by iqtdoc::TQtDocumentManagerWrap< Base, Gui >::GetSaveFilePath().
istd::CStringList iqt::GetCStringList (const QStringList & stringList)
i2d::CVector2d iqt::GetCVector2d (const QPointF & position)
Referenced by iqt2d::TShapeBase< GraphicsItemClass >::GetPosFromLocal(), iqt2d::TShapeBase< GraphicsItemClass >::itemChange(), and iqt2d::TObjectShapeBase< GraphicsItemClass, ObjectClass >::OnPositionChanged().
QDateTime iqt::GetQDateTime (const isys::IDateTime & dateTime)
QFileInfo iqt::GetQFileInfo (const isys::CFileInfo & fileInfo)
QLine iqt::GetQLine (const i2d::CLine2d & line)
QLineF iqt::GetQLineF (const i2d::CLine2d & line)
QPoint iqt::GetQPoint (const istd::CIndex2d & position)
QPointF iqt::GetQPointF (const i2d::CVector2d & position)
Referenced by iqt2d::TShapeBase< GraphicsItemClass >::GetLocalFromPos(), and iqt2d::TShapeBase< GraphicsItemClass >::itemChange().
QRectF iqt::GetQRectF (const i2d::CRectangle & rect)
QSize iqt::GetQSize (const istd::CIndex2d & size)
QString iqt::GetQString (const istd::CString & string)
Referenced by iqtgui::CSimpleMainWindowGuiComp::CreateMenu(), and iqtdoc::CMainWindowGuiComp::SerializeRecentFiles().
QStringList iqt::GetQStringList (const istd::CStringList & stringList)
© 2007-2011 Witold Gantzke and Kirill Lepskiy