find_package(QT NAMES Qt6 Qt5 COMPONENTS Core REQUIRED)

macro(subdirlist result curdir)
	file(GLOB children RELATIVE ${curdir} ${curdir}/*)
	set(dirlist "")
	foreach(child ${children})
		IF(IS_DIRECTORY ${curdir}/${child})
		LIST(APPEND dirlist ${child})
		ENDIF()
	endforeach()
	set(${result} ${dirlist})
endmacro()

macro(get_target_name target_name)
	set(COMPILER_NAME "Clang")
	if(${MSVC})
		if(${MSVC_TOOLSET_VERSION} STREQUAL 100)
			set(COMPILER_NAME "VC10")
		endif()
		if(${MSVC_TOOLSET_VERSION} STREQUAL 110)
			set(COMPILER_NAME "VC11")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 120)
			set(COMPILER_NAME}"VC12")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 140)
			set(COMPILER_NAME "VC14")
		endif()
		if(${MSVC_TOOLSET_VERSION} STREQUAL 141)
			set(COMPILER_NAME "VC15")
		endif()
		if(${MSVC_TOOLSET_VERSION} STREQUAL 142)
			set(COMPILER_NAME "VC16")
		endif()

		if(${CMAKE_CL_64} STREQUAL 1)
			set(COMPILER_NAME "${COMPILER_NAME}_64")
		endif()
	elseif(${ANDROID})
		set(COMPILER_NAME "${COMPILER_NAME}Android_${CMAKE_ANDROID_ARCH_ABI}")
		add_compile_definitions(COMPILER_NAME=ClangAndroid)
		add_compile_definitions(PLATFORM_CODE=${CMAKE_ANDROID_ARCH_ABI})
	elseif(${APPLE})

		if("${CMAKE_OSX_ARCHITECTURES}" STREQUAL "arm64")
			set(COMPILER_NAME "${COMPILER_NAME}OSX_arm64")
			add_compile_definitions(COMPILER_NAME=ClangOSX)
			add_compile_definitions(PLATFORM_CODE=arm64)
		else()
			set(COMPILER_NAME "${COMPILER_NAME}OSX_64")
			add_compile_definitions(COMPILER_NAME=ClangOSX)
			add_compile_definitions(PLATFORM_CODE=x64)
		endif()

	elseif("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")

		if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
			set(COMPILER_NAME "GCCLinux_64")
		else()
			set(COMPILER_NAME "${COMPILER_NAME}_64")
		endif()
	endif()

	set(${target_name} "${COMPILER_NAME}")
endmacro()
