iproc::TSupplierCompWrap< Product > Class Template Reference
iproc::TSupplierCompWrap< Product > Class Template Reference
Standard implementation of interface iproc::ISupplier with preparation for component implementation.
#include <TSupplierCompWrap.h>
Classes
class Timer
Public Types
enum MessageId { MI_DURATION_TIME = 0x077a1b }
typedef ilog::CLoggerComponentBase BaseClass
typedef Product ProductType
Public Member Functions
I_REGISTER_SUBELEMENT (TaskLog)
I_REGISTER_SUBELEMENT_INTERFACE (TaskLog, ilog::IMessageConsumer, ExtractTaskLog)
I_REGISTER_SUBELEMENT_INTERFACE (TaskLog, istd::IPolymorphic, ExtractTaskLog)
I_ASSIGN_TO (m_paramsSetModelCompPtr, m_paramsSetCompPtr, false)
TSupplierCompWrap ()
virtual int GetWorkStatus () const
Get status of last work.
virtual void InvalidateSupplier ()
Called to signalize that this supplier is invalid.
virtual void EnsureWorkInitialized ()
Force the supplier to initialize its work.
virtual void EnsureWorkFinished ()
Ensure that all objects are produced.
virtual void ClearWorkResults ()
Remove all stored work results.
virtual const
ilog::IMessageContainer * GetWorkMessages () const
Get messages outputted by this work.
virtual iprm::IParamsSet * GetModelParametersSet () const
Get parameter set using by this supplier.
Protected Member Functions
virtual bool InitializeWork ()
Called if the new work should be initialized.
virtual void OnParametersChanged ()
Called if the supplier parameters was changed.
const Product * GetWorkProduct () const
Get current work product, if work was done correctly.
virtual void RegisterSupplierInput (imod::IModel *modelPtr, ISupplier *supplierPtr=NULL)
Register supplier input.
virtual void UnregisterSupplierInput (imod::IModel *modelPtr)
Unregister supplier input.
virtual void AddMessage (const ilog::CMessage *messagePtr) const
Add ilog::CMessage to the internal message container (also from const functions).
virtual int ProduceObject (Product &result) const =0
Produce single object.
virtual bool IsMessageSupported (int messageCategory=-1, int messageId=-1, const istd::IInformationProvider *messagePtr=NULL) const
virtual void AddMessage (const MessagePtr &messagePtr)
virtual void OnComponentCreated ()
virtual void OnComponentDestroyed ()
Protected Attributes
istd::TDelPtr< Product > m_productPtr
int m_workStatus
Detailed Description
template<class Product>
class iproc::TSupplierCompWrap< Product >
Standard implementation of interface iproc::ISupplier with preparation for component implementation.
During component initialization you should call RegisterSupplierInput for all suppliers used by this component as a input.
Definition at line 32 of file TSupplierCompWrap.h.
Member Typedef Documentation
template<class Product> typedef ilog::CLoggerComponentBase iproc::TSupplierCompWrap< Product >::BaseClass
Reimplemented from ilog::TLoggerCompWrap< Base >.
Reimplemented in iipr::CPositionFromImageSupplierComp, icam::CMultiCameraBitmapSupplierComp, icam::CSelectableBitmapSupplierComp, icam::CSnapBitmapSupplierComp, iedge::CEdgeBasedFeaturesSupplierComp, iipr::CColorPatternComparatorComp, iipr::CSearchBasedFeaturesSupplierComp, iipr::CEdgeDistancesSupplierComp, iipr::CImageHistogramSupplierComp, iipr::CColorBitmapSeparatorSupplierComp, iipr::CLineProjectionSupplierComp, iipr::CBitmapJoinerSupplierComp, iedge::CExtractedEdgeLinesSupplierComp, iipr::CDifferenceBitmapSupplierComp, iipr::CMultiLineProjectionSupplierComp, iipr::CProcessedBitmapSupplierComp, iipr::CMultiLineSupplierCompBase, iedge::CProcessedEdgeLinesSupplierComp, and iipr::CTubeProjectionLinesProviderComp.
Definition at line 39 of file TSupplierCompWrap.h.
template<class Product> typedef Product iproc::TSupplierCompWrap< Product >::ProductType
Definition at line 40 of file TSupplierCompWrap.h.
Member Enumeration Documentation
template<class Product> enum iproc::TSupplierCompWrap::MessageId
Enumerator:
MI_DURATION_TIME
Definition at line 42 of file TSupplierCompWrap.h.
Constructor & Destructor Documentation
template<class Product > iproc::TSupplierCompWrap< Product >::TSupplierCompWrap ()
Definition at line 197 of file TSupplierCompWrap.h.
References NULL.
Member Function Documentation
template<class Product > void iproc::TSupplierCompWrap< Product >::AddMessage (const ilog::CMessage * messagePtr) const [protected, virtual]
Add ilog::CMessage to the internal message container (also from const functions).
Definition at line 364 of file TSupplierCompWrap.h.
References NULL.
template<class Product > void iproc::TSupplierCompWrap< Product >::AddMessage (const MessagePtr & messagePtr) [protected, virtual]
Implements ilog::IMessageConsumer.
Definition at line 384 of file TSupplierCompWrap.h.
template<class Product > void iproc::TSupplierCompWrap< Product >::ClearWorkResults () [virtual]
Remove all stored work results.
This set also work state to WS_INIT.
Implements iproc::ISupplier.
Definition at line 279 of file TSupplierCompWrap.h.
template<class Product > void iproc::TSupplierCompWrap< Product >::EnsureWorkFinished () [virtual]
Ensure that all objects are produced.
Implements iproc::ISupplier.
Definition at line 261 of file TSupplierCompWrap.h.
template<class Product > void iproc::TSupplierCompWrap< Product >::EnsureWorkInitialized () [virtual]
Force the supplier to initialize its work.
First if work is initialized, new calculation can be done.
Implements iproc::ISupplier.
Definition at line 228 of file TSupplierCompWrap.h.
References iproc::ISupplier::EnsureWorkInitialized().
template<class Product > iprm::IParamsSet * iproc::TSupplierCompWrap< Product >::GetModelParametersSet () const [virtual]
Get parameter set using by this supplier.
The pointed object will not be relocated - no reconnect is needed if it is observed. If the supplier doesn't support parameters, it returns NULL.
Implements iproc::ISupplier.
Definition at line 303 of file TSupplierCompWrap.h.
template<class Product > const ilog::IMessageContainer * iproc::TSupplierCompWrap< Product >::GetWorkMessages () const [virtual]
Get messages outputted by this work.
The pointed object will not be relocated - no reconnect is needed if it is observed. If the supplier doesn't support list of messages, it returns NULL.
Implements iproc::ISupplier.
Definition at line 296 of file TSupplierCompWrap.h.
template<class Product > const Product * iproc::TSupplierCompWrap< Product >::GetWorkProduct () const [protected]
Get current work product, if work was done correctly.
Definition at line 325 of file TSupplierCompWrap.h.
References NULL.
template<class Product > int iproc::TSupplierCompWrap< Product >::GetWorkStatus () const [virtual]
Get status of last work.
Please note, that this status is not a part of supplier model and can be changed without any notification.
Returns:
work status defined in iproc::ISupplier::WorkStatus.
Implements iproc::ISupplier.
Definition at line 210 of file TSupplierCompWrap.h.
template<class Product> iproc::TSupplierCompWrap< Product >::I_ASSIGN_TO (m_paramsSetModelCompPtr , m_paramsSetCompPtr , false)
template<class Product> iproc::TSupplierCompWrap< Product >::I_REGISTER_SUBELEMENT (TaskLog)
template<class Product> iproc::TSupplierCompWrap< Product >::I_REGISTER_SUBELEMENT_INTERFACE (TaskLog , ilog::IMessageConsumer , ExtractTaskLog)
template<class Product> iproc::TSupplierCompWrap< Product >::I_REGISTER_SUBELEMENT_INTERFACE (TaskLog , istd::IPolymorphic , ExtractTaskLog)
template<class Product > bool iproc::TSupplierCompWrap< Product >::InitializeWork () [protected, virtual]
Called if the new work should be initialized.
Default implementation do nothing. It is dedicated to be overridden.
Reimplemented in iedge::CEdgeBasedFeaturesSupplierComp, iipr::CSearchBasedFeaturesSupplierComp, icam::CMultiCameraBitmapSupplierComp, and icam::CSnapBitmapSupplierComp.
Definition at line 312 of file TSupplierCompWrap.h.
template<class Product > void iproc::TSupplierCompWrap< Product >::InvalidateSupplier () [virtual]
Called to signalize that this supplier is invalid.
This signal will be transfered to all supplier which are registered as output.
Returns:
true, if initialization could be done.
Implements iproc::ISupplier.
Definition at line 217 of file TSupplierCompWrap.h.
template<class Product > bool iproc::TSupplierCompWrap< Product >::IsMessageSupported (int messageCategory = -1, int messageId = -1, const istd::IInformationProvider * messagePtr = NULL) const [protected, virtual]
Implements ilog::IMessageConsumer.
Definition at line 374 of file TSupplierCompWrap.h.
template<class Product > void iproc::TSupplierCompWrap< Product >::OnComponentCreated () [protected, virtual]
Reimplemented from ilog::TLoggerCompWrap< Base >.
Reimplemented in iedge::CEdgeBasedFeaturesSupplierComp, iipr::CSearchBasedFeaturesSupplierComp, iipr::CColorPatternComparatorComp, iipr::CPositionFromImageSupplierComp, icam::CSelectableBitmapSupplierComp, iipr::CColorBitmapSeparatorSupplierComp, iipr::CDifferenceBitmapSupplierComp, iipr::CBitmapJoinerSupplierComp, iipr::CEdgeDistancesSupplierComp, iipr::CMultiLineProjectionSupplierComp, iipr::CProcessedBitmapSupplierComp, iedge::CExtractedEdgeLinesSupplierComp, iipr::CImageHistogramSupplierComp, iipr::CLineProjectionSupplierComp, iedge::CProcessedEdgeLinesSupplierComp, and iipr::CTubeProjectionLinesProviderComp.
Definition at line 393 of file TSupplierCompWrap.h.
References NULL.
template<class Product > void iproc::TSupplierCompWrap< Product >::OnComponentDestroyed () [protected, virtual]
Reimplemented in iedge::CEdgeBasedFeaturesSupplierComp, iipr::CSearchBasedFeaturesSupplierComp, iipr::CColorPatternComparatorComp, icam::CSelectableBitmapSupplierComp, iipr::CImageHistogramSupplierComp, and iipr::CTubeProjectionLinesProviderComp.
Definition at line 416 of file TSupplierCompWrap.h.
template<class Product > void iproc::TSupplierCompWrap< Product >::OnParametersChanged () [protected, virtual]
Called if the supplier parameters was changed.
Default implementation do nothing. It is dedicated to be overridden.
Definition at line 319 of file TSupplierCompWrap.h.
template<class Product> virtual int iproc::TSupplierCompWrap< Product >::ProduceObject (Product & result) const [protected, pure virtual]
Produce single object.
Returns:
work status.
See also:
iproc::WorkStatus
Implemented in iedge::CEdgeBasedFeaturesSupplierComp, iipr::CColorPatternComparatorComp, iipr::CPositionFromImageSupplierComp, iipr::CColorBitmapSeparatorSupplierComp, iipr::CDifferenceBitmapSupplierComp, iipr::CBitmapJoinerSupplierComp, iipr::CMultiLineProjectionSupplierComp, iipr::CProcessedBitmapSupplierComp, iipr::CImageHistogramSupplierComp, iipr::CLineProjectionSupplierComp, and iipr::CTubeProjectionLinesProviderComp.
template<class Product > void iproc::TSupplierCompWrap< Product >::RegisterSupplierInput (imod::IModel * modelPtr, ISupplier * supplierPtr = NULL) [protected, virtual]
Register supplier input.
Changes of supplier input will force this supplier invalidate. All registered inputs will be unregistered during component destruction (OnComponentDestryed method).
Definition at line 339 of file TSupplierCompWrap.h.
References imod::IModel::AttachObserver(), and NULL.
template<class Product > void iproc::TSupplierCompWrap< Product >::UnregisterSupplierInput (imod::IModel * modelPtr) [protected, virtual]
Unregister supplier input.
Changes of this input will no more invalidate this supplier.
Definition at line 352 of file TSupplierCompWrap.h.
References imod::IModel::DetachObserver(), and NULL.
Member Data Documentation
template<class Product> istd::TDelPtr<Product> iproc::TSupplierCompWrap< Product >::m_productPtr [protected]
Definition at line 135 of file TSupplierCompWrap.h.
template<class Product> int iproc::TSupplierCompWrap< Product >::m_workStatus [protected]
Definition at line 136 of file TSupplierCompWrap.h.
The documentation for this class was generated from the following file:
Include/iproc/TSupplierCompWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy