ACF-Solutions: imeas::TDiscrSamplesSequence< Element > Class Template Reference
imeas::TDiscrSamplesSequence< Element > Class Template Reference
#include <TDiscrSamplesSequence.h>
Public Member Functions
TDiscrSamplesSequence ()
virtual bool CreateDiscrSequence (int timeSamplesCount, void *dataPtr, bool releaseFlag, int sampleDiff, int channelDiff, int sampleDepth, int channelsCount=1)
Create container for sample sequence using external samples buffer.
virtual int GetSampleDepth () const
Get number of bits used to represent single sample.
virtual I_DWORD GetDiscrSample (int position, int channel=0) const
Get discrete sample at specified position.
virtual bool SetDiscrSample (int position, int channel, I_DWORD sample)
Set discrete sample at specified position.
virtual bool CreateSequence (int timeSamplesCount, int channelsCount=1)
Create container for sample sequence with specified number of samples, channels and sample depth.
virtual bool IsEmpty () const
Return true if this sequence has no sample.
virtual void ResetSequence ()
Reset this sequence.
virtual int GetTimeSamplesCount () const
Get size of this raster sequence.
virtual int GetChannelsCount () const
Get number of color components.
virtual double GetSamplingPeriod () const
Get sampling period of this sequence.
virtual void SetSamplingPeriod (double value)
Set sampling period of this sequence.
virtual double GetSample (int index, int channel=0) const
Get sample value at specified index.
virtual void SetSample (int index, int channel, double value)
Set sample value at specified index.
virtual bool Serialize (iser::IArchive &archive)
virtual bool CopyFrom (const istd::IChangeable &object)
Detailed Description
template<typename Element>
class imeas::TDiscrSamplesSequence< Element >
Definition at line 18 of file TDiscrSamplesSequence.h.
Constructor & Destructor Documentation
template<typename Element > imeas::TDiscrSamplesSequence< Element >::TDiscrSamplesSequence () [inline]
Definition at line 69 of file TDiscrSamplesSequence.h.
Member Function Documentation
template<typename Element > bool imeas::TDiscrSamplesSequence< Element >::CopyFrom (const istd::IChangeable & object) [inline, virtual]
Reimplemented from istd::IChangeable.
Definition at line 286 of file TDiscrSamplesSequence.h.
References imeas::TDiscrSamplesSequence< Element >::CreateSequence(), imeas::ISamplesSequence::GetChannelsCount(), istd::TPointer< Type >::GetPtr(), imeas::ISamplesSequence::GetSample(), imeas::ISamplesSequence::GetSamplingPeriod(), imeas::ISamplesSequence::GetTimeSamplesCount(), istd::TPointer< Type >::IsValid(), NULL, istd::TOptDelPtr< Type, DelArray >::Reset(), imeas::TDiscrSamplesSequence< Element >::ResetSequence(), istd::TOptDelPtr< Type, DelArray >::SetPtr(), imeas::TDiscrSamplesSequence< Element >::SetSample(), and imeas::TDiscrSamplesSequence< Element >::SetSamplingPeriod().
template<typename Element > bool imeas::TDiscrSamplesSequence< Element >::CreateDiscrSequence (int samplesCount, void * dataPtr, bool releaseFlag, int sampleDiff, int channelDiff, int sampleDepth, int channelsCount = 1) [inline, virtual]
Create container for sample sequence using external samples buffer.
Parameters:
samplesCount number of samples.
dataPtr pointer to external buffer.
releaseFlag if its true, external buffer will be managed (removed) by this object.
sampleDiff address difference between next and previos sample. If it equals 0, the value will be taken from number of samples, number of channels and channelDiff.
channelDiff address difference between next and previos sample. If it equals 0, the value will be calculated from number of bits per single sample.
channelsCount number of channels.
Returns:
true if sample sequence was created correctly.
Implements imeas::IDiscrSamplesSequence.
Definition at line 83 of file TDiscrSamplesSequence.h.
References istd::TOptDelPtr< Type, DelArray >::SetPtr().
template<typename Element > bool imeas::TDiscrSamplesSequence< Element >::CreateSequence (int timeSamplesCount, int channelsCount = 1) [inline, virtual]
Create container for sample sequence with specified number of samples, channels and sample depth.
Parameters:
samplesCount number of samples.
channelsCount number of channels.
Returns:
true if sample sequence was created correctly.
Implements imeas::ISamplesSequence.
Definition at line 138 of file TDiscrSamplesSequence.h.
References istd::TOptDelPtr< Type, DelArray >::SetPtr().
Referenced by imeas::TDiscrSamplesSequence< Element >::CopyFrom(), and imeas::TDiscrSamplesSequence< Element >::Serialize().
template<typename Element > int imeas::TDiscrSamplesSequence< Element >::GetChannelsCount () const [inline, virtual]
Get number of color components.
Implements imeas::ISamplesSequence.
Definition at line 180 of file TDiscrSamplesSequence.h.
Referenced by imeas::TDiscrSamplesSequence< Element >::Serialize().
template<typename Element > I_DWORD imeas::TDiscrSamplesSequence< Element >::GetDiscrSample (int position, int channel = 0) const [inline, virtual]
Get discrete sample at specified position.
Parameters:
position position, must be inside of returned size.
Implements imeas::IDiscrSamplesSequence.
Definition at line 116 of file TDiscrSamplesSequence.h.
References istd::TPointer< Type >::GetPtr().
Referenced by imeas::TDiscrSamplesSequence< Element >::Serialize().
template<typename Element > double imeas::TDiscrSamplesSequence< Element >::GetSample (int index, int channel = 0) const [inline, virtual]
Get sample value at specified index.
Implements imeas::ISamplesSequence.
Definition at line 203 of file TDiscrSamplesSequence.h.
References istd::TPointer< Type >::GetPtr().
template<typename Element > int imeas::TDiscrSamplesSequence< Element >::GetSampleDepth () const [inline, virtual]
Get number of bits used to represent single sample.
Implements imeas::IDiscrSamplesSequence.
Definition at line 109 of file TDiscrSamplesSequence.h.
template<typename Element > double imeas::TDiscrSamplesSequence< Element >::GetSamplingPeriod () const [inline, virtual]
Get sampling period of this sequence.
Sampling period is time difference between samples. If returned value is not positive, no period is known.
Implements imeas::ISamplesSequence.
Definition at line 187 of file TDiscrSamplesSequence.h.
template<typename Element > int imeas::TDiscrSamplesSequence< Element >::GetTimeSamplesCount () const [inline, virtual]
Get size of this raster sequence.
Implements imeas::ISamplesSequence.
Definition at line 173 of file TDiscrSamplesSequence.h.
Referenced by imeas::TDiscrSamplesSequence< Element >::Serialize().
template<typename Element > bool imeas::TDiscrSamplesSequence< Element >::IsEmpty () const [inline, virtual]
Return true if this sequence has no sample.
Implements imeas::ISamplesSequence.
Definition at line 157 of file TDiscrSamplesSequence.h.
template<typename Element > void imeas::TDiscrSamplesSequence< Element >::ResetSequence () [inline, virtual]
Reset this sequence.
After this operation sequence is set to initial state.
Implements imeas::ISamplesSequence.
Definition at line 164 of file TDiscrSamplesSequence.h.
References istd::TOptDelPtr< Type, DelArray >::Reset().
Referenced by imeas::TDiscrSamplesSequence< Element >::CopyFrom().
template<typename Element > bool imeas::TDiscrSamplesSequence< Element >::Serialize (iser::IArchive & archive) [inline, virtual]
Implements iser::ISerializable.
Definition at line 223 of file TDiscrSamplesSequence.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), imeas::TDiscrSamplesSequence< Element >::CreateSequence(), iser::IArchive::EndTag(), imeas::TDiscrSamplesSequence< Element >::GetChannelsCount(), imeas::TDiscrSamplesSequence< Element >::GetDiscrSample(), imeas::TDiscrSamplesSequence< Element >::GetTimeSamplesCount(), iser::IArchive::IsStoring(), NULL, iser::IArchive::Process(), imeas::TDiscrSamplesSequence< Element >::SetDiscrSample(), and istd::TChangeNotifier< Changeable >::SetPtr().
template<typename Element > bool imeas::TDiscrSamplesSequence< Element >::SetDiscrSample (int position, int channel, I_DWORD sample) [inline, virtual]
Set discrete sample at specified position.
Parameters:
position position, must be inside of returned size.
channel sample channel.
sample sample value will be set.
Returns:
true, if sample was changed.
Implements imeas::IDiscrSamplesSequence.
Definition at line 125 of file TDiscrSamplesSequence.h.
References istd::TPointer< Type >::GetPtr().
Referenced by imeas::TDiscrSamplesSequence< Element >::Serialize().
template<typename Element > void imeas::TDiscrSamplesSequence< Element >::SetSample (int index, int channel, double value) [inline, virtual]
Set sample value at specified index.
Implements imeas::ISamplesSequence.
Definition at line 212 of file TDiscrSamplesSequence.h.
References istd::TPointer< Type >::GetPtr().
Referenced by imeas::TDiscrSamplesSequence< Element >::CopyFrom().
template<typename Element > void imeas::TDiscrSamplesSequence< Element >::SetSamplingPeriod (double value) [inline, virtual]
Set sampling period of this sequence.
Sampling period is time difference between samples. If value is not positive, it means no period is known.
Implements imeas::ISamplesSequence.
Definition at line 194 of file TDiscrSamplesSequence.h.
Referenced by imeas::TDiscrSamplesSequence< Element >::CopyFrom().
The documentation for this class was generated from the following file:
E:/Work/Projects/Developement/AcfSln/Include/imeas/TDiscrSamplesSequence.h