iqtinsp::TSupplierGuiCompBase< UI, WidgetType > Class Template Reference
iqtinsp::TSupplierGuiCompBase< UI, WidgetType > Class Template Reference
#include <TSupplierGuiCompBase.h>
Classes
class ParamsObserver
Public Types
typedef
iqt2d::TViewExtenderCompBase
< iqtgui::TDesignerGuiObserverCompBase
< UI, iproc::ISupplier > > BaseClass
Public Member Functions
I_ASSIGN_TO (m_paramsSetObserverCompPtr, m_paramsSetGuiCompPtr, false)
I_ASSIGN_TO (m_paramsSetExtenderCompPtr, m_paramsSetGuiCompPtr, false)
TSupplierGuiCompBase ()
virtual void AddItemsToScene (iqt2d::IViewProvider *providerPtr, int flags)
virtual void RemoveItemsFromScene (iqt2d::IViewProvider *providerPtr)
virtual const i2d::ICalibration2d * GetCalibration () const
Protected Types
typedef BaseClass::Shapes Shapes
Protected Member Functions
bool AreParamsEditable () const
Check, if parameters are correct connected to GUI and can be editable.
bool IsLoadParamsSupported () const
Check if parameter loading is supported.
bool IsSaveParamsSupported () const
Check if parameter storing is supported.
bool LoadParams ()
Load parameters from external source (file).
bool SaveParams ()
Save parameters for example to file.
bool DoTest ()
Do inspection test.
virtual void OnSupplierParamsChanged ()
Method will be called every time if the parameter set of the supplier has been changed.
virtual void OnGuiModelAttached ()
virtual void OnGuiModelDetached ()
virtual void CreateShapes (int sceneId, Shapes &result)
virtual void AfterUpdate (imod::IModel *modelPtr, int updateFlags, istd::IPolymorphic *updateParamsPtr)
virtual QWidget * GetParamsWidget () const =0
Get parameters widget object.
Protected Attributes
ParamsObserver m_paramsObserver
Detailed Description
template<class UI, class WidgetType = QWidget>
class iqtinsp::TSupplierGuiCompBase< UI, WidgetType >
Definition at line 27 of file TSupplierGuiCompBase.h.
Member Typedef Documentation
template<class UI, class WidgetType = QWidget> typedef iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase<UI, iproc::ISupplier> > iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::BaseClass
Reimplemented from iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< UI, iproc::ISupplier > >.
Reimplemented in iqtipr::CLineProjectionSupplierGuiComp, iedgegui::CEdgeLinesSupplierGuiComp, iqtipr::CSearchBasedFeaturesSupplierGuiComp, iqtipr::CValueSupplierGuiComp, iqtipr::CColorPatternComparatorGuiComp, iqtipr::CMultiLineSupplierGuiComp, iqtcam::CMultiBitmapSupplierGuiComp, iqtipr::CMultiLineProjectionSupplierGuiComp, and iqtinsp::CGeneralSupplierGuiComp.
Definition at line 34 of file TSupplierGuiCompBase.h.
template<class UI, class WidgetType = QWidget> typedef BaseClass::Shapes iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::Shapes [protected]
Reimplemented from iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< UI, iproc::ISupplier > >.
Definition at line 56 of file TSupplierGuiCompBase.h.
Constructor & Destructor Documentation
template<class UI , class WidgetType > iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::TSupplierGuiCompBase ()
Definition at line 172 of file TSupplierGuiCompBase.h.
Member Function Documentation
template<class UI , class WidgetType > void iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::AddItemsToScene (iqt2d::IViewProvider * providerPtr, int flags) [virtual]
Reimplemented from iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< UI, iproc::ISupplier > >.
Reimplemented in iqtipr::CSearchBasedFeaturesSupplierGuiComp.
Definition at line 182 of file TSupplierGuiCompBase.h.
References i2d::ICalibrationProvider::GetCalibration(), iqt2d::IViewProvider::GetView(), NULL, iview::CCalibratedViewBase::SetDisplayCalibration(), and iqt2d::IViewExtender::SF_DIRECT.
template<class UI , class WidgetType > void iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::AfterUpdate (imod::IModel * modelPtr, int updateFlags, istd::IPolymorphic * updateParamsPtr) [protected, virtual]
Reimplemented in iedgegui::CEdgeLinesSupplierGuiComp.
Definition at line 427 of file TSupplierGuiCompBase.h.
References istd::IInformationProvider::GetInformationCategory(), iproc::ISupplier::GetWorkStatus(), istd::IInformationProvider::IC_ERROR, istd::IInformationProvider::IC_WARNING, NULL, iproc::ISupplier::WS_CANCELED, iproc::ISupplier::WS_CRITICAL, iproc::ISupplier::WS_ERROR, iproc::ISupplier::WS_LOCKED, and iproc::ISupplier::WS_OK.
template<class UI , class WidgetType > bool iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::AreParamsEditable () const [protected]
Check, if parameters are correct connected to GUI and can be editable.
Definition at line 233 of file TSupplierGuiCompBase.h.
template<class UI , class WidgetType > void iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::CreateShapes (int sceneId, Shapes & result) [protected, virtual]
Implements iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< UI, iproc::ISupplier > >.
Reimplemented in iqtcam::CMultiBitmapSupplierGuiComp, iqtipr::CLineProjectionSupplierGuiComp, iedgegui::CEdgeLinesSupplierGuiComp, iqtipr::CMultiLineSupplierGuiComp, and iqtipr::CValueSupplierGuiComp.
Definition at line 419 of file TSupplierGuiCompBase.h.
template<class UI , class WidgetType > bool iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::DoTest () [protected]
Do inspection test.
Definition at line 326 of file TSupplierGuiCompBase.h.
References iproc::ISupplier::EnsureWorkFinished(), iproc::ISupplier::EnsureWorkInitialized(), iproc::ISupplier::GetWorkStatus(), iproc::ISupplier::InvalidateSupplier(), NULL, and iproc::ISupplier::WS_ERROR.
template<class UI , class WidgetType > const i2d::ICalibration2d * iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::GetCalibration () const [virtual]
Implements i2d::ICalibrationProvider.
Definition at line 219 of file TSupplierGuiCompBase.h.
References i2d::ICalibrationProvider::GetCalibration(), and NULL.
template<class UI, class WidgetType = QWidget> virtual QWidget* iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::GetParamsWidget () const [protected, pure virtual]
Get parameters widget object.
Extern paremeters GUI will attach to this widget. This widget should have some layout.
Implemented in iqtipr::CSearchBasedFeaturesSupplierGuiComp, iqtipr::CMultiLineProjectionSupplierGuiComp, iqtcam::CMultiBitmapSupplierGuiComp, iqtipr::CLineProjectionSupplierGuiComp, iqtipr::CColorPatternComparatorGuiComp, iedgegui::CEdgeLinesSupplierGuiComp, iqtipr::CMultiLineSupplierGuiComp, iqtipr::CValueSupplierGuiComp, and iqtinsp::CGeneralSupplierGuiComp.
template<class UI, class WidgetType = QWidget> iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::I_ASSIGN_TO (m_paramsSetObserverCompPtr , m_paramsSetGuiCompPtr , false)
template<class UI, class WidgetType = QWidget> iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::I_ASSIGN_TO (m_paramsSetExtenderCompPtr , m_paramsSetGuiCompPtr , false)
template<class UI , class WidgetType > bool iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::IsLoadParamsSupported () const [protected]
Check if parameter loading is supported.
Definition at line 240 of file TSupplierGuiCompBase.h.
References iproc::ISupplier::GetModelParametersSet(), NULL, iser::IFileTypeInfo::QF_ANONYMOUS, and iser::IFileTypeInfo::QF_LOAD.
template<class UI , class WidgetType > bool iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::IsSaveParamsSupported () const [protected]
Check if parameter storing is supported.
Definition at line 260 of file TSupplierGuiCompBase.h.
References iproc::ISupplier::GetModelParametersSet(), NULL, iser::IFileTypeInfo::QF_ANONYMOUS, and iser::IFileTypeInfo::QF_SAVE.
template<class UI , class WidgetType > bool iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::LoadParams () [protected]
Load parameters from external source (file).
Definition at line 280 of file TSupplierGuiCompBase.h.
References iproc::ISupplier::GetModelParametersSet(), NULL, and iser::IFileLoader::StateFailed.
template<class UI , class WidgetType > void iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::OnGuiModelAttached () [protected, virtual]
Reimplemented in iqtipr::CSearchBasedFeaturesSupplierGuiComp, iqtcam::CMultiBitmapSupplierGuiComp, iqtipr::CLineProjectionSupplierGuiComp, iedgegui::CEdgeLinesSupplierGuiComp, iqtipr::CValueSupplierGuiComp, iqtipr::CMultiLineProjectionSupplierGuiComp, iqtipr::CColorPatternComparatorGuiComp, and iqtinsp::CGeneralSupplierGuiComp.
Definition at line 350 of file TSupplierGuiCompBase.h.
References imod::IModel::AttachObserver(), iproc::ISupplier::GetModelParametersSet(), and NULL.
template<class UI , class WidgetType > void iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::OnGuiModelDetached () [protected, virtual]
Reimplemented in iqtipr::CMultiLineProjectionSupplierGuiComp, and iqtipr::CColorPatternComparatorGuiComp.
Definition at line 390 of file TSupplierGuiCompBase.h.
References imod::IModel::DetachObserver(), iproc::ISupplier::GetModelParametersSet(), imod::IModel::IsAttached(), and NULL.
template<class UI , class WidgetType > void iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::OnSupplierParamsChanged () [protected, virtual]
Method will be called every time if the parameter set of the supplier has been changed.
Default implementation does nothing.
Reimplemented in iqtipr::CSearchBasedFeaturesSupplierGuiComp, iqtipr::CMultiLineProjectionSupplierGuiComp, iedgegui::CEdgeLinesSupplierGuiComp, iqtipr::CColorPatternComparatorGuiComp, iqtipr::CMultiLineSupplierGuiComp, iqtipr::CValueSupplierGuiComp, and iqtinsp::CGeneralSupplierGuiComp.
Definition at line 342 of file TSupplierGuiCompBase.h.
Referenced by iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::ParamsObserver::OnUpdate().
template<class UI , class WidgetType > void iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::RemoveItemsFromScene (iqt2d::IViewProvider * providerPtr) [virtual]
Reimplemented from iqt2d::TViewExtenderCompBase< iqtgui::TDesignerGuiObserverCompBase< UI, iproc::ISupplier > >.
Reimplemented in iqtipr::CSearchBasedFeaturesSupplierGuiComp.
Definition at line 206 of file TSupplierGuiCompBase.h.
template<class UI , class WidgetType > bool iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::SaveParams () [protected]
Save parameters for example to file.
Definition at line 303 of file TSupplierGuiCompBase.h.
References iproc::ISupplier::GetModelParametersSet(), NULL, and iser::IFileLoader::StateFailed.
Member Data Documentation
template<class UI, class WidgetType = QWidget> ParamsObserver iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::m_paramsObserver [protected]
Definition at line 130 of file TSupplierGuiCompBase.h.
The documentation for this class was generated from the following file:
Include/iqtinsp/TSupplierGuiCompBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy