imeas::TDiscreteDataSequence< Element > Class Template Reference
imeas::TDiscreteDataSequence< Element > Class Template Reference
#include <TDiscreteDataSequence.h>
Public Member Functions
TDiscreteDataSequence ()
virtual bool CreateDiscreteSequence (int samplesCount, void *dataPtr, bool releaseFlag, int sampleDiff, int channelDiff, int sampleDepth, int channelsCount=1)
Create container for sample sequence using external samples buffer.
virtual bool CreateDiscreteSequenceWithInfo (const istd::TTransPtr< const IDataSequenceInfo > &infoPtr, int samplesCount, void *dataPtr, bool releaseFlag, int sampleDiff, int channelDiff, int sampleDepth, int channelsCount=1)
Create container for sample sequence with additional sequence info using external samples buffer.
virtual int GetSampleDepth () const
Get number of bits used to represent single sample.
virtual quint32 GetDiscreteSample (int position, int channel=0) const
Get discrete sample at specified position.
virtual bool SetDiscreteSample (int position, int channel, quint32 sample)
Set discrete sample at specified position.
virtual bool CreateSequence (int samplesCount, int channelsCount=1)
Create container for sample sequence with specified number of samples, channels and sample depth.
virtual bool CreateSequenceWithInfo (const istd::TTransPtr< const IDataSequenceInfo > &infoPtr, int samplesCount=-1, int channelsCount=-1)
Create sequence and set the info object.
virtual const IDataSequenceInfo * GetSequenceInfo () const
Get additional information about this sequence.
virtual bool IsEmpty () const
Return true if this sequence has no sample.
virtual void ResetSequence ()
Reset this sequence.
virtual int GetSamplesCount () const
Get size of this raster sequence.
virtual int GetChannelsCount () const
Get number of channels.
virtual double GetSample (int index, int channel=0) const
Get sample value at specified index.
virtual void SetSample (int index, int channel, double value)
Set sample value at specified index.
virtual bool Serialize (iser::IArchive &archive)
virtual bool CopyFrom (const istd::IChangeable &object, CompatibilityMode mode=CM_WITHOUT_REFS)
Detailed Description
template<typename Element>
class imeas::TDiscreteDataSequence< Element >
Definition at line 26 of file TDiscreteDataSequence.h.
Constructor & Destructor Documentation
template<typename Element > imeas::TDiscreteDataSequence< Element >::TDiscreteDataSequence ()
Definition at line 91 of file TDiscreteDataSequence.h.
Member Function Documentation
template<typename Element > bool imeas::TDiscreteDataSequence< Element >::CopyFrom (const istd::IChangeable & object, CompatibilityMode mode = CM_WITHOUT_REFS) [virtual]
Reimplemented from istd::IChangeable.
Definition at line 350 of file TDiscreteDataSequence.h.
References imeas::IDataSequence::GetChannelsCount(), istd::TPointerBase< Type >::GetPtr(), imeas::IDataSequence::GetSample(), imeas::IDataSequence::GetSamplesCount(), and NULL.
template<typename Element > bool imeas::TDiscreteDataSequence< Element >::CreateDiscreteSequence (int samplesCount, void * dataPtr, bool releaseFlag, int sampleDiff, int channelDiff, int sampleDepth, int channelsCount = 1) [virtual]
Create container for sample sequence using external samples buffer.
Parameters:
samplesCount number of samples.
dataPtr pointer to external buffer.
releaseFlag if its true, external buffer will be managed (removed) by this object.
sampleDiff address difference between next and previos sample. If it equals 0, the value will be taken from number of samples, number of channels and channelDiff.
channelDiff address difference between next and previos sample. If it equals 0, the value will be calculated from number of bits per single sample.
sampleDepth number of bits used for representation of a single sample.
channelsCount number of channels.
Returns:
true if sample sequence was created correctly.
Implements imeas::IDiscreteDataSequence.
Definition at line 105 of file TDiscreteDataSequence.h.
template<typename Element > bool imeas::TDiscreteDataSequence< Element >::CreateDiscreteSequenceWithInfo (const istd::TTransPtr< const IDataSequenceInfo > & infoPtr, int samplesCount, void * dataPtr, bool releaseFlag, int sampleDiff, int channelDiff, int sampleDepth, int channelsCount = 1) [virtual]
Create container for sample sequence with additional sequence info using external samples buffer.
Parameters:
infoPtr sequence info object.
samplesCount number of samples.
dataPtr pointer to external buffer.
releaseFlag if its true, external buffer will be managed (removed) by this object.
sampleDiff address difference between next and previos sample. If it equals 0, the value will be taken from number of samples, number of channels and channelDiff.
channelDiff address difference between next and previos sample. If it equals 0, the value will be calculated from number of bits per single sample.
sampleDepth number of bits used for representation of a single sample.
channelsCount number of channels.
Returns:
true if sample sequence was created correctly.
Implements imeas::IDiscreteDataSequence.
Definition at line 131 of file TDiscreteDataSequence.h.
template<typename Element > bool imeas::TDiscreteDataSequence< Element >::CreateSequence (int samplesCount, int channelsCount = 1) [virtual]
Create container for sample sequence with specified number of samples, channels and sample depth.
Parameters:
samplesCount number of samples.
channelsCount number of channels.
Returns:
true if sample sequence was created correctly.
Implements imeas::IDataSequence.
Definition at line 177 of file TDiscreteDataSequence.h.
References imeas::IDataSequenceInfo::SIF_CHANNELS_COUNT_FIXED, and imeas::IDataSequenceInfo::SIF_SAMPLES_COUNT_FIXED.
template<typename Element > bool imeas::TDiscreteDataSequence< Element >::CreateSequenceWithInfo (const istd::TTransPtr< const IDataSequenceInfo > & infoPtr, int samplesCount = -1, int channelsCount = -1) [virtual]
Create sequence and set the info object.
Parameters:
infoPtr sequence info object.
samplesCount number of samples. If it is negative, default value will be taken.
channelsCount number of channels. If it is negative, default value will be taken.
Implements imeas::IDataSequence.
Definition at line 218 of file TDiscreteDataSequence.h.
template<typename Element > int imeas::TDiscreteDataSequence< Element >::GetChannelsCount () const [virtual]
Get number of channels.
Implements imeas::IDataSequence.
Definition at line 260 of file TDiscreteDataSequence.h.
template<typename Element > quint32 imeas::TDiscreteDataSequence< Element >::GetDiscreteSample (int position, int channel = 0) const [virtual]
Get discrete sample at specified position.
Parameters:
position position, must be inside of returned size.
Implements imeas::IDiscreteDataSequence.
Definition at line 155 of file TDiscreteDataSequence.h.
template<typename Element > double imeas::TDiscreteDataSequence< Element >::GetSample (int index, int channel = 0) const [virtual]
Get sample value at specified index.
Implements imeas::IDataSequence.
Definition at line 267 of file TDiscreteDataSequence.h.
template<typename Element > int imeas::TDiscreteDataSequence< Element >::GetSampleDepth () const [virtual]
Get number of bits used to represent single sample.
Implements imeas::IDiscreteDataSequence.
Definition at line 148 of file TDiscreteDataSequence.h.
template<typename Element > int imeas::TDiscreteDataSequence< Element >::GetSamplesCount () const [virtual]
Get size of this raster sequence.
Implements imeas::IDataSequence.
Definition at line 253 of file TDiscreteDataSequence.h.
template<typename Element > const IDataSequenceInfo * imeas::TDiscreteDataSequence< Element >::GetSequenceInfo () const [virtual]
Get additional information about this sequence.
Implements imeas::IDataSequence.
Definition at line 230 of file TDiscreteDataSequence.h.
template<typename Element > bool imeas::TDiscreteDataSequence< Element >::IsEmpty () const [virtual]
Return true if this sequence has no sample.
Implements imeas::IDataSequence.
Definition at line 237 of file TDiscreteDataSequence.h.
template<typename Element > void imeas::TDiscreteDataSequence< Element >::ResetSequence () [virtual]
Reset this sequence.
After this operation sequence is set to initial state.
Implements imeas::IDataSequence.
Definition at line 244 of file TDiscreteDataSequence.h.
template<typename Element > bool imeas::TDiscreteDataSequence< Element >::Serialize (iser::IArchive & archive) [virtual]
Implements iser::ISerializable.
Definition at line 287 of file TDiscreteDataSequence.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), NULL, iser::IArchive::Process(), and istd::TChangeNotifier< class >::SetPtr().
template<typename Element > bool imeas::TDiscreteDataSequence< Element >::SetDiscreteSample (int position, int channel, quint32 sample) [virtual]
Set discrete sample at specified position.
Parameters:
position position, must be inside of returned size.
channel sample channel.
sample sample value will be set.
Returns:
true, if sample was changed.
Implements imeas::IDiscreteDataSequence.
Definition at line 164 of file TDiscreteDataSequence.h.
template<typename Element > void imeas::TDiscreteDataSequence< Element >::SetSample (int index, int channel, double value) [virtual]
Set sample value at specified index.
Implements imeas::IDataSequence.
Definition at line 276 of file TDiscreteDataSequence.h.
The documentation for this class was generated from the following file:
Include/imeas/TDiscreteDataSequence.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy