icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass > Class Template Reference
icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass > Class Template Reference
#include <TObjectShapeBase.h>
Public Types
typedef TShapeBase
< GraphicsItemClass > BaseClass
typedef
imod::TSingleModelObserverBase
< ObjectClass > BaseClass2
Public Member Functions
TObjectShapeBase (bool isEditable=false, const ISceneProvider *providerPtr=NULL)
Protected Member Functions
virtual void OnSelectionChanged (bool isSelected)
virtual void OnPositionChanged (const QPointF &position)
virtual QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
virtual void mousePressEvent (QGraphicsSceneMouseEvent *eventPtr)
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *eventPtr)
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *eventPtr)
virtual void AfterUpdate (imod::IModel *modelPtr, int updateFlags, istd::IPolymorphic *updateParamsPtr)
virtual void UpdateGraphicsItem (const ObjectClass &object)=0
Detailed Description
template<class GraphicsItemClass, class ObjectClass>
class icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >
Definition at line 23 of file TObjectShapeBase.h.
Member Typedef Documentation
template<class GraphicsItemClass, class ObjectClass> typedef TShapeBase<GraphicsItemClass> icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >::BaseClass
Reimplemented from icmpstr::TShapeBase< GraphicsItemClass >.
Reimplemented in icmpstr::CRegistryElementShape.
Definition at line 28 of file TObjectShapeBase.h.
template<class GraphicsItemClass, class ObjectClass> typedef imod::TSingleModelObserverBase<ObjectClass> icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >::BaseClass2
Definition at line 29 of file TObjectShapeBase.h.
Constructor & Destructor Documentation
template<class GraphicsItemClass , class ObjectClass > icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >::TObjectShapeBase (bool isEditable = false, const ISceneProvider * providerPtr = NULL)
Definition at line 63 of file TObjectShapeBase.h.
References icmpstr::TShapeBase< GraphicsItemClass >::EditableColor, icmpstr::TShapeBase< GraphicsItemClass >::InactiveColor, NULL, icmpstr::TShapeBase< GraphicsItemClass >::SelectedColor, icmpstr::TShapeBase< GraphicsItemClass >::SetPen(), and icmpstr::TShapeBase< GraphicsItemClass >::SwitchColorSheme().
Member Function Documentation
template<class GraphicsItemClass , class ObjectClass > void icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >::AfterUpdate (imod::IModel * modelPtr, int updateFlags, istd::IPolymorphic * updateParamsPtr) [protected, virtual]
Reimplemented from imod::CSingleModelObserverBase.
Definition at line 173 of file TObjectShapeBase.h.
References NULL.
template<class GraphicsItemClass , class ObjectClass > QVariant icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >::itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant & value) [protected, virtual]
Reimplemented from icmpstr::TShapeBase< GraphicsItemClass >.
Definition at line 123 of file TObjectShapeBase.h.
template<class GraphicsItemClass , class ObjectClass > void icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * eventPtr) [protected, virtual]
Reimplemented in icmpstr::CRegistryElementShape.
Definition at line 162 of file TObjectShapeBase.h.
template<class GraphicsItemClass , class ObjectClass > void icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >::mousePressEvent (QGraphicsSceneMouseEvent * eventPtr) [protected, virtual]
Definition at line 134 of file TObjectShapeBase.h.
template<class GraphicsItemClass , class ObjectClass > void icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >::mouseReleaseEvent (QGraphicsSceneMouseEvent * eventPtr) [protected, virtual]
Definition at line 148 of file TObjectShapeBase.h.
template<class GraphicsItemClass , class ObjectClass > void icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >::OnPositionChanged (const QPointF & position) [protected, virtual]
Reimplemented from icmpstr::TShapeBase< GraphicsItemClass >.
Definition at line 106 of file TObjectShapeBase.h.
References i2d::IObject2d::GetCenter(), i2d::IObject2d::MoveCenterTo(), and NULL.
template<class GraphicsItemClass , class ObjectClass > void icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >::OnSelectionChanged (bool isSelected) [protected, virtual]
Reimplemented from icmpstr::TShapeBase< GraphicsItemClass >.
Reimplemented in icmpstr::CRegistryElementShape.
Definition at line 89 of file TObjectShapeBase.h.
template<class GraphicsItemClass, class ObjectClass> virtual void icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >::UpdateGraphicsItem (const ObjectClass & object) [protected, pure virtual]
Implemented in icmpstr::CRegistryElementShape.
The documentation for this class was generated from the following file:
Include/icmpstr/TObjectShapeBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy