icmpstr::TShapeBase< GraphicsItemClass > Class Template Reference
icmpstr::TShapeBase< GraphicsItemClass > Class Template Reference
#include <TShapeBase.h>
Public Types
enum ColorSheme { SelectedColor, EditableColor, InactiveColor, DefaultColor = InactiveColor }
typedef GraphicsItemClass BaseClass
Public Member Functions
TShapeBase (bool isEditable=false, const ISceneProvider *providerPtr=NULL)
virtual void SetPen (int colorSheme, const QPen &pen)
virtual QPen GetPen (int colorSheme) const
virtual void SetBrush (int colorSheme, const QBrush &pen)
virtual QBrush GetBrush (int colorSheme) const
virtual void SwitchColorSheme (int colorSheme)
bool IsEditable () const
void SetEditable (bool isEditable)
const ISceneProvider * GetSceneProvider () const
Protected Member Functions
i2d::CVector2d GetPosFromLocal (const QPointF &position) const
Map position from local graphics item coordinates.
QPointF GetLocalFromPos (const i2d::CVector2d &position) const
Map position from local graphics item coordinates.
virtual void OnSelectionChanged (bool isSelected)
virtual void OnPositionChanged (const QPointF &position)
virtual QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=NULL)
template<>
void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *)
template<>
void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *)
Detailed Description
template<class GraphicsItemClass>
class icmpstr::TShapeBase< GraphicsItemClass >
Definition at line 26 of file TShapeBase.h.
Member Typedef Documentation
template<class GraphicsItemClass> typedef GraphicsItemClass icmpstr::TShapeBase< GraphicsItemClass >::BaseClass
Reimplemented in icmpstr::CRegistryElementShape, icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >, and icmpstr::TObjectShapeBase< QGraphicsRectItem, CVisualRegistryElement >.
Definition at line 29 of file TShapeBase.h.
Member Enumeration Documentation
template<class GraphicsItemClass> enum icmpstr::TShapeBase::ColorSheme
Enumerator:
SelectedColor
Color for a selected shape.
EditableColor
Color for a shape, that can be edited on the graphics view.
InactiveColor
Color for a shape, that can not be edited on the graphics view.
DefaultColor
Standard shape color.
Definition at line 31 of file TShapeBase.h.
Constructor & Destructor Documentation
template<class GraphicsItemClass > icmpstr::TShapeBase< GraphicsItemClass >::TShapeBase (bool isEditable = false, const ISceneProvider * providerPtr = NULL)
Definition at line 102 of file TShapeBase.h.
Member Function Documentation
template<class GraphicsItemClass > QBrush icmpstr::TShapeBase< GraphicsItemClass >::GetBrush (int colorSheme) const [virtual]
Definition at line 150 of file TShapeBase.h.
template<class GraphicsItemClass > QPointF icmpstr::TShapeBase< GraphicsItemClass >::GetLocalFromPos (const i2d::CVector2d & position) const [protected]
Map position from local graphics item coordinates.
Definition at line 218 of file TShapeBase.h.
template<class GraphicsItemClass > QPen icmpstr::TShapeBase< GraphicsItemClass >::GetPen (int colorSheme) const [virtual]
Definition at line 125 of file TShapeBase.h.
template<class GraphicsItemClass > i2d::CVector2d icmpstr::TShapeBase< GraphicsItemClass >::GetPosFromLocal (const QPointF & position) const [protected]
Map position from local graphics item coordinates.
Definition at line 211 of file TShapeBase.h.
template<class GraphicsItemClass > const ISceneProvider * icmpstr::TShapeBase< GraphicsItemClass >::GetSceneProvider () const
Definition at line 202 of file TShapeBase.h.
template<class GraphicsItemClass > void icmpstr::TShapeBase< GraphicsItemClass >::hoverEnterEvent (QGraphicsSceneHoverEvent * event) [protected, virtual]
Definition at line 290 of file TShapeBase.h.
template<class GraphicsItemClass > void icmpstr::TShapeBase< GraphicsItemClass >::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) [protected, virtual]
Definition at line 299 of file TShapeBase.h.
template<class GraphicsItemClass > bool icmpstr::TShapeBase< GraphicsItemClass >::IsEditable () const
Definition at line 182 of file TShapeBase.h.
template<class GraphicsItemClass > QVariant icmpstr::TShapeBase< GraphicsItemClass >::itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant & value) [protected, virtual]
Reimplemented in icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >, and icmpstr::TObjectShapeBase< QGraphicsRectItem, CVisualRegistryElement >.
Definition at line 245 of file TShapeBase.h.
References iqt::GetCRectangle(), i2d::CRectangle::GetNearestPointTo(), i2d::CVector2d::GetX(), i2d::CVector2d::GetY(), NULL, and icmpstr::ISceneProvider::SF_FIXED_SIZE.
template<class GraphicsItemClass > void icmpstr::TShapeBase< GraphicsItemClass >::OnPositionChanged (const QPointF & position) [protected, virtual]
Reimplemented in icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >, and icmpstr::TObjectShapeBase< QGraphicsRectItem, CVisualRegistryElement >.
Definition at line 237 of file TShapeBase.h.
template<class GraphicsItemClass > void icmpstr::TShapeBase< GraphicsItemClass >::OnSelectionChanged (bool isSelected) [protected, virtual]
Reimplemented in icmpstr::CRegistryElementShape, icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >, and icmpstr::TObjectShapeBase< QGraphicsRectItem, CVisualRegistryElement >.
Definition at line 225 of file TShapeBase.h.
template<class GraphicsItemClass > void icmpstr::TShapeBase< GraphicsItemClass >::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = NULL) [protected, virtual]
Reimplemented in icmpstr::CRegistryElementShape.
Definition at line 308 of file TShapeBase.h.
References NULL.
template<> void icmpstr::TShapeBase< QGraphicsItem >::paint (QPainter * , const QStyleOptionGraphicsItem * , QWidget *) [inline, protected]
Definition at line 328 of file TShapeBase.h.
template<> void icmpstr::TShapeBase< QAbstractGraphicsShapeItem >::paint (QPainter * , const QStyleOptionGraphicsItem * , QWidget *) [inline, protected]
Definition at line 334 of file TShapeBase.h.
template<class GraphicsItemClass > void icmpstr::TShapeBase< GraphicsItemClass >::SetBrush (int colorSheme, const QBrush & pen) [virtual]
Definition at line 136 of file TShapeBase.h.
template<class GraphicsItemClass > void icmpstr::TShapeBase< GraphicsItemClass >::SetEditable (bool isEditable)
Definition at line 189 of file TShapeBase.h.
template<class GraphicsItemClass > void icmpstr::TShapeBase< GraphicsItemClass >::SetPen (int colorSheme, const QPen & pen) [virtual]
Definition at line 111 of file TShapeBase.h.
Referenced by icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >::TObjectShapeBase().
template<class GraphicsItemClass > void icmpstr::TShapeBase< GraphicsItemClass >::SwitchColorSheme (int colorSheme) [virtual]
Definition at line 161 of file TShapeBase.h.
References NULL.
Referenced by icmpstr::TObjectShapeBase< GraphicsItemClass, ObjectClass >::TObjectShapeBase().
The documentation for this class was generated from the following file:
Include/icmpstr/TShapeBase.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy