ACF-Solutions: iwin::TComPtr< Type > Class Template Reference
iwin::TComPtr< Type > Class Template Reference
Pointer wrapper providing access to Windows COM objects.
#include <TComPtr.h>
Public Types
typedef istd::TPointerBase< Type > BaseClass
Public Member Functions
TComPtr (Type *ptr=NULL, bool addRef=true)
Set new value of internal pointer.
TComPtr (const TComPtr &ptr)
Copy constructor.
~TComPtr ()
Destructor.
bool CoCreateInstance (REFCLSID rclsid, IUnknown *outerPtr=NULL, I_DWORD clsContext=CLSCTX_ALL)
Create instance of COM object using its CLSID.
void Reset ()
It decreses COM reference pointer and set this pointer to NULL.
void SetPtr (Type *ptr, bool addRef=true)
Set new value of internal pointer.
Type * PopPtr ()
Reset internal pointer value without decreasing of reference counter.
void TakeOver (TComPtr &sourcePtr)
Take internal pointer over.
void IncRef ()
Increase reference counter.
void DecRef ()
Decrease reference counter.
TComPtr & operator= (const TComPtr &ptr)
Assign operator.
Type ** operator& ()
Address operator.
Detailed Description
template<class Type>
class iwin::TComPtr< Type >
Pointer wrapper providing access to Windows COM objects.
Definition at line 20 of file TComPtr.h.
Member Typedef Documentation
template<class Type> typedef istd::TPointerBase<Type> iwin::TComPtr< Type >::BaseClass
Definition at line 23 of file TComPtr.h.
Constructor & Destructor Documentation
template<class Type > iwin::TComPtr< Type >::TComPtr (Type * ptr = NULL, bool addRef = true) [inline]
Set new value of internal pointer.
Definition at line 90 of file TComPtr.h.
References iwin::TComPtr< Type >::IncRef().
template<class Type > iwin::TComPtr< Type >::TComPtr (const TComPtr< Type > & ptr) [inline]
Copy constructor.
It increase COM reference pointer.
Definition at line 100 of file TComPtr.h.
References iwin::TComPtr< Type >::IncRef().
template<class Type > iwin::TComPtr< Type >::~TComPtr () [inline]
Destructor.
It decreses COM reference pointer.
Definition at line 108 of file TComPtr.h.
References iwin::TComPtr< Type >::DecRef().
Member Function Documentation
template<class Type > bool iwin::TComPtr< Type >::CoCreateInstance (REFCLSID rclsid, IUnknown * outerPtr = NULL, I_DWORD clsContext = CLSCTX_ALL) [inline]
Create instance of COM object using its CLSID.
Definition at line 161 of file TComPtr.h.
References iwin::TComPtr< Type >::Reset().
template<class Type > void iwin::TComPtr< Type >::DecRef () [inline]
Decrease reference counter.
Definition at line 182 of file TComPtr.h.
References istd::TPointerBase< Type >::GetPtr(), and NULL.
Referenced by iwin::TComPtr< Type >::SetPtr(), and iwin::TComPtr< Type >::~TComPtr().
template<class Type > void iwin::TComPtr< Type >::IncRef () [inline]
Increase reference counter.
Definition at line 170 of file TComPtr.h.
References istd::TPointerBase< Type >::GetPtr(), and NULL.
Referenced by iwin::TComPtr< Type >::SetPtr(), and iwin::TComPtr< Type >::TComPtr().
template<class Type > Type ** iwin::TComPtr< Type >::operator& () [inline]
Address operator.
Definition at line 152 of file TComPtr.h.
References istd::TPointerBase< Type >::GetPtrRef().
template<class Type > TComPtr< Type > & iwin::TComPtr< Type >::operator= (const TComPtr< Type > & ptr) [inline]
Assign operator.
Definition at line 194 of file TComPtr.h.
References istd::TPointerBase< Type >::GetPtr(), and iwin::TComPtr< Type >::SetPtr().
template<class Type > Type * iwin::TComPtr< Type >::PopPtr () [inline]
Reset internal pointer value without decreasing of reference counter.
Definition at line 135 of file TComPtr.h.
References istd::TPointerBase< Type >::GetPtr(), NULL, and istd::TPointerBase< Type >::SetPtr().
Referenced by iwin::TComPtr< Type >::TakeOver().
template<class Type > void iwin::TComPtr< Type >::Reset () [inline]
It decreses COM reference pointer and set this pointer to NULL.
Reimplemented from istd::TPointerBase< Type >.
Definition at line 115 of file TComPtr.h.
References NULL, and iwin::TComPtr< Type >::SetPtr().
Referenced by iwin::TComPtr< Type >::CoCreateInstance().
template<class Type > void iwin::TComPtr< Type >::SetPtr (Type * ptr, bool addRef = true) [inline]
Set new value of internal pointer.
Definition at line 122 of file TComPtr.h.
References iwin::TComPtr< Type >::DecRef(), iwin::TComPtr< Type >::IncRef(), and istd::TPointerBase< Type >::SetPtr().
Referenced by iwin::TComPtr< Type >::operator=(), iwin::TComPtr< Type >::Reset(), and iwin::TComPtr< Type >::TakeOver().
template<class Type > void iwin::TComPtr< Type >::TakeOver (TComPtr< Type > & sourcePtr) [inline]
Take internal pointer over.
It set pointer from other object and detach it from them.
Definition at line 145 of file TComPtr.h.
References iwin::TComPtr< Type >::PopPtr(), and iwin::TComPtr< Type >::SetPtr().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/AcfSln/Include/iwin/TComPtr.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy