ACF-Solutions: imeas::TDiscrDataSequence< Element > Class Template Reference
imeas::TDiscrDataSequence< Element > Class Template Reference
#include <TDiscrDataSequence.h>
Public Member Functions
TDiscrDataSequence ()
virtual bool CreateDiscrSequence (int samplesCount, void *dataPtr, bool releaseFlag, int sampleDiff, int channelDiff, int sampleDepth, int channelsCount=1)
Create container for sample sequence using external samples buffer.
virtual int GetSampleDepth () const
Get number of bits used to represent single sample.
virtual I_DWORD GetDiscrSample (int position, int channel=0) const
Get discrete sample at specified position.
virtual bool SetDiscrSample (int position, int channel, I_DWORD sample)
Set discrete sample at specified position.
virtual bool CreateSequence (int samplesCount, int channelsCount=1)
Create container for sample sequence with specified number of samples, channels and sample depth.
virtual bool CreateSequenceWithInfo (istd::TTransPtr< const IDataSequenceInfo > infoPtr, int samplesCount=-1, int channelsCount=-1)
Create sequence and set the info object.
virtual const IDataSequenceInfo * GetSequenceInfo () const
Get additional information about this sequence.
virtual bool IsEmpty () const
Return true if this sequence has no sample.
virtual void ResetSequence ()
Reset this sequence.
virtual int GetSamplesCount () const
Get size of this raster sequence.
virtual int GetChannelsCount () const
Get number of channels.
virtual double GetSample (int index, int channel=0) const
Get sample value at specified index.
virtual void SetSample (int index, int channel, double value)
Set sample value at specified index.
virtual bool Serialize (iser::IArchive &archive)
virtual bool CopyFrom (const istd::IChangeable &object)
Detailed Description
template<typename Element>
class imeas::TDiscrDataSequence< Element >
Definition at line 24 of file TDiscrDataSequence.h.
Constructor & Destructor Documentation
template<typename Element > imeas::TDiscrDataSequence< Element >::TDiscrDataSequence () [inline]
Definition at line 79 of file TDiscrDataSequence.h.
Member Function Documentation
template<typename Element > bool imeas::TDiscrDataSequence< Element >::CopyFrom (const istd::IChangeable & object) [inline, virtual]
Reimplemented from istd::IChangeable.
Definition at line 321 of file TDiscrDataSequence.h.
References imeas::TDiscrDataSequence< Element >::CreateSequence(), imeas::IDataSequence::GetChannelsCount(), istd::TPointerBase< Type >::GetPtr(), imeas::IDataSequence::GetSample(), imeas::IDataSequence::GetSamplesCount(), I_ASSERT, istd::TPointerBase< Type >::IsValid(), NULL, istd::TOptDelPtr< Type, DelArray >::Reset(), imeas::TDiscrDataSequence< Element >::ResetSequence(), istd::TOptDelPtr< Type, DelArray >::SetPtr(), and imeas::TDiscrDataSequence< Element >::SetSample().
template<typename Element > bool imeas::TDiscrDataSequence< Element >::CreateDiscrSequence (int samplesCount, void * dataPtr, bool releaseFlag, int sampleDiff, int channelDiff, int sampleDepth, int channelsCount = 1) [inline, virtual]
Create container for sample sequence using external samples buffer.
Parameters:
samplesCount number of samples.
dataPtr pointer to external buffer.
releaseFlag if its true, external buffer will be managed (removed) by this object.
sampleDiff address difference between next and previos sample. If it equals 0, the value will be taken from number of samples, number of channels and channelDiff.
channelDiff address difference between next and previos sample. If it equals 0, the value will be calculated from number of bits per single sample.
sampleDepth number of bits used for representation of a single sample.
channelsCount number of channels.
Returns:
true if sample sequence was created correctly.
Implements imeas::IDiscrDataSequence.
Definition at line 93 of file TDiscrDataSequence.h.
References istd::TOptDelPtr< Type, DelArray >::SetPtr().
template<typename Element > bool imeas::TDiscrDataSequence< Element >::CreateSequence (int samplesCount, int channelsCount = 1) [inline, virtual]
Create container for sample sequence with specified number of samples, channels and sample depth.
Parameters:
samplesCount number of samples.
channelsCount number of channels.
Returns:
true if sample sequence was created correctly.
Implements imeas::IDataSequence.
Definition at line 148 of file TDiscrDataSequence.h.
References istd::TTransPtr< Type >::IsValid(), istd::TOptDelPtr< Type, DelArray >::SetPtr(), imeas::IDataSequenceInfo::SIF_CHANNELS_COUNT_FIXED, and imeas::IDataSequenceInfo::SIF_SAMPLES_COUNT_FIXED.
Referenced by imeas::TDiscrDataSequence< Element >::CopyFrom(), imeas::TDiscrDataSequence< Element >::CreateSequenceWithInfo(), and imeas::TDiscrDataSequence< Element >::Serialize().
template<typename Element > bool imeas::TDiscrDataSequence< Element >::CreateSequenceWithInfo (istd::TTransPtr< const IDataSequenceInfo > infoPtr, int samplesCount = -1, int channelsCount = -1) [inline, virtual]
Create sequence and set the info object.
Parameters:
infoPtr sequence info object.
samplesCount number of samples. If it is negative, default value will be taken.
channelsCount number of channels. If it is negative, default value will be taken.
Implements imeas::IDataSequence.
Definition at line 189 of file TDiscrDataSequence.h.
References imeas::TDiscrDataSequence< Element >::CreateSequence().
template<typename Element > int imeas::TDiscrDataSequence< Element >::GetChannelsCount () const [inline, virtual]
Get number of channels.
Implements imeas::IDataSequence.
Definition at line 231 of file TDiscrDataSequence.h.
Referenced by imeas::TDiscrDataSequence< Element >::Serialize().
template<typename Element > I_DWORD imeas::TDiscrDataSequence< Element >::GetDiscrSample (int position, int channel = 0) const [inline, virtual]
Get discrete sample at specified position.
Parameters:
position position, must be inside of returned size.
Implements imeas::IDiscrDataSequence.
Definition at line 126 of file TDiscrDataSequence.h.
References istd::TPointerBase< Type >::GetPtr().
Referenced by imeas::TDiscrDataSequence< Element >::Serialize().
template<typename Element > double imeas::TDiscrDataSequence< Element >::GetSample (int index, int channel = 0) const [inline, virtual]
Get sample value at specified index.
Implements imeas::IDataSequence.
Definition at line 238 of file TDiscrDataSequence.h.
References istd::TPointerBase< Type >::GetPtr().
template<typename Element > int imeas::TDiscrDataSequence< Element >::GetSampleDepth () const [inline, virtual]
Get number of bits used to represent single sample.
Implements imeas::IDiscrDataSequence.
Definition at line 119 of file TDiscrDataSequence.h.
template<typename Element > int imeas::TDiscrDataSequence< Element >::GetSamplesCount () const [inline, virtual]
Get size of this raster sequence.
Implements imeas::IDataSequence.
Definition at line 224 of file TDiscrDataSequence.h.
Referenced by imeas::TDiscrDataSequence< Element >::Serialize().
template<typename Element > const IDataSequenceInfo * imeas::TDiscrDataSequence< Element >::GetSequenceInfo () const [inline, virtual]
Get additional information about this sequence.
Implements imeas::IDataSequence.
Definition at line 201 of file TDiscrDataSequence.h.
References istd::TTransPtr< Type >::GetPtr().
template<typename Element > bool imeas::TDiscrDataSequence< Element >::IsEmpty () const [inline, virtual]
Return true if this sequence has no sample.
Implements imeas::IDataSequence.
Definition at line 208 of file TDiscrDataSequence.h.
template<typename Element > void imeas::TDiscrDataSequence< Element >::ResetSequence () [inline, virtual]
Reset this sequence.
After this operation sequence is set to initial state.
Implements imeas::IDataSequence.
Definition at line 215 of file TDiscrDataSequence.h.
References istd::TOptDelPtr< Type, DelArray >::Reset().
Referenced by imeas::TDiscrDataSequence< Element >::CopyFrom().
template<typename Element > bool imeas::TDiscrDataSequence< Element >::Serialize (iser::IArchive & archive) [inline, virtual]
Implements iser::ISerializable.
Definition at line 258 of file TDiscrDataSequence.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), imeas::TDiscrDataSequence< Element >::CreateSequence(), iser::IArchive::EndTag(), imeas::TDiscrDataSequence< Element >::GetChannelsCount(), imeas::TDiscrDataSequence< Element >::GetDiscrSample(), imeas::TDiscrDataSequence< Element >::GetSamplesCount(), iser::IArchive::IsStoring(), NULL, iser::IArchive::Process(), imeas::TDiscrDataSequence< Element >::SetDiscrSample(), and istd::TChangeNotifier< Changeable >::SetPtr().
template<typename Element > bool imeas::TDiscrDataSequence< Element >::SetDiscrSample (int position, int channel, I_DWORD sample) [inline, virtual]
Set discrete sample at specified position.
Parameters:
position position, must be inside of returned size.
channel sample channel.
sample sample value will be set.
Returns:
true, if sample was changed.
Implements imeas::IDiscrDataSequence.
Definition at line 135 of file TDiscrDataSequence.h.
References istd::TPointerBase< Type >::GetPtr().
Referenced by imeas::TDiscrDataSequence< Element >::Serialize().
template<typename Element > void imeas::TDiscrDataSequence< Element >::SetSample (int index, int channel, double value) [inline, virtual]
Set sample value at specified index.
Implements imeas::IDataSequence.
Definition at line 247 of file TDiscrDataSequence.h.
References istd::TPointerBase< Type >::GetPtr().
Referenced by imeas::TDiscrDataSequence< Element >::CopyFrom().
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/AcfSln/Include/imeas/TDiscrDataSequence.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy