ACF-Solutions: imeas::ISamplesSequence Class Reference
imeas::ISamplesSequence Class Reference
General definition of sequence contains samples in regular time grid.
#include <ISamplesSequence.h>
Public Member Functions
virtual bool CreateSequence (int timeSamplesCount, int channelsCount=1)=0
Create container for sample sequence with specified number of samples, channels and sample depth.
virtual bool IsEmpty () const =0
Return true if this sequence has no sample.
virtual void ResetSequence ()=0
Reset this sequence.
virtual int GetTimeSamplesCount () const =0
Get size of this raster sequence.
virtual int GetChannelsCount () const =0
Get number of color components.
virtual double GetSamplingPeriod () const =0
Get sampling period of this sequence.
virtual void SetSamplingPeriod (double value)=0
Set sampling period of this sequence.
virtual double GetSample (int index, int channel=0) const =0
Get sample value at specified index.
virtual void SetSample (int index, int channel, double value)=0
Set sample value at specified index.
Detailed Description
General definition of sequence contains samples in regular time grid.
All samples has the same number of channels components.
Definition at line 18 of file ISamplesSequence.h.
Member Function Documentation
virtual bool imeas::ISamplesSequence::CreateSequence (int timeSamplesCount, int channelsCount = 1) [pure virtual]
Create container for sample sequence with specified number of samples, channels and sample depth.
Parameters:
samplesCount number of samples.
channelsCount number of channels.
Returns:
true if sample sequence was created correctly.
Implemented in imeas::CGeneralSamplesSequence, and imeas::TDiscrSamplesSequence< Element >.
virtual int imeas::ISamplesSequence::GetChannelsCount () const [pure virtual]
Get number of color components.
Implemented in imeas::CGeneralSamplesSequence, and imeas::TDiscrSamplesSequence< Element >.
Referenced by imeas::TDiscrSamplesSequence< Element >::CopyFrom().
virtual double imeas::ISamplesSequence::GetSample (int index, int channel = 0) const [pure virtual]
Get sample value at specified index.
Implemented in imeas::CGeneralSamplesSequence, and imeas::TDiscrSamplesSequence< Element >.
Referenced by imeas::TDiscrSamplesSequence< Element >::CopyFrom().
virtual double imeas::ISamplesSequence::GetSamplingPeriod () const [pure virtual]
Get sampling period of this sequence.
Sampling period is time difference between samples. If returned value is not positive, no period is known.
Implemented in imeas::CGeneralSamplesSequence, and imeas::TDiscrSamplesSequence< Element >.
Referenced by imeas::TDiscrSamplesSequence< Element >::CopyFrom().
virtual int imeas::ISamplesSequence::GetTimeSamplesCount () const [pure virtual]
Get size of this raster sequence.
Implemented in imeas::CGeneralSamplesSequence, and imeas::TDiscrSamplesSequence< Element >.
Referenced by imeas::TDiscrSamplesSequence< Element >::CopyFrom().
virtual bool imeas::ISamplesSequence::IsEmpty () const [pure virtual]
Return true if this sequence has no sample.
Implemented in imeas::CGeneralSamplesSequence, and imeas::TDiscrSamplesSequence< Element >.
virtual void imeas::ISamplesSequence::ResetSequence () [pure virtual]
Reset this sequence.
After this operation sequence is set to initial state.
Implemented in imeas::CGeneralSamplesSequence, and imeas::TDiscrSamplesSequence< Element >.
virtual void imeas::ISamplesSequence::SetSample (int index, int channel, double value) [pure virtual]
Set sample value at specified index.
Implemented in imeas::CGeneralSamplesSequence, and imeas::TDiscrSamplesSequence< Element >.
virtual void imeas::ISamplesSequence::SetSamplingPeriod (double value) [pure virtual]
Set sampling period of this sequence.
Sampling period is time difference between samples. If value is not positive, it means no period is known.
Implemented in imeas::CGeneralSamplesSequence, and imeas::TDiscrSamplesSequence< Element >.
The documentation for this class was generated from the following file:
E:/Work/Projects/Developement/AcfSln/Include/imeas/ISamplesSequence.h