ACF-Solutions: imeas::IDataSequence Class Reference
imeas::IDataSequence Class Reference
General definition of sequence contains samples in regular time grid.
#include <IDataSequence.h>
Public Member Functions
virtual bool CreateSequence (int samplesCount, int channelsCount=1)=0
Create container for sample sequence with specified number of samples, channels and sample depth.
virtual bool CreateSequenceWithInfo (istd::TTransPtr< const IDataSequenceInfo > infoPtr, int samplesCount=-1, int channelsCount=-1)=0
Create sequence and set the info object.
virtual const IDataSequenceInfo * GetSequenceInfo () const =0
Get additional information about this sequence.
virtual bool IsEmpty () const =0
Return true if this sequence has no sample.
virtual void ResetSequence ()=0
Reset this sequence.
virtual int GetSamplesCount () const =0
Get size of this raster sequence.
virtual int GetChannelsCount () const =0
Get number of channels.
virtual double GetSample (int index, int channel=0) const =0
Get sample value at specified index.
virtual void SetSample (int index, int channel, double value)=0
Set sample value at specified index.
Detailed Description
General definition of sequence contains samples in regular time grid.
All samples has the same number of channels components.
Definition at line 20 of file IDataSequence.h.
Member Function Documentation
virtual bool imeas::IDataSequence::CreateSequence (int samplesCount, int channelsCount = 1) [pure virtual]
Create container for sample sequence with specified number of samples, channels and sample depth.
Parameters:
samplesCount number of samples.
channelsCount number of channels.
Returns:
true if sample sequence was created correctly.
Implemented in imeas::CGeneralDataSequence, and imeas::TDiscrDataSequence< Element >.
virtual bool imeas::IDataSequence::CreateSequenceWithInfo (istd::TTransPtr< const IDataSequenceInfo > infoPtr, int samplesCount = -1, int channelsCount = -1) [pure virtual]
Create sequence and set the info object.
Parameters:
infoPtr sequence info object.
samplesCount number of samples. If it is negative, default value will be taken.
channelsCount number of channels. If it is negative, default value will be taken.
Implemented in imeas::CGeneralDataSequence, and imeas::TDiscrDataSequence< Element >.
virtual int imeas::IDataSequence::GetChannelsCount () const [pure virtual]
Get number of channels.
Implemented in imeas::CGeneralDataSequence, and imeas::TDiscrDataSequence< Element >.
Referenced by imeas::TDiscrDataSequence< Element >::CopyFrom().
virtual double imeas::IDataSequence::GetSample (int index, int channel = 0) const [pure virtual]
Get sample value at specified index.
Implemented in imeas::CGeneralDataSequence, and imeas::TDiscrDataSequence< Element >.
Referenced by imeas::TDiscrDataSequence< Element >::CopyFrom().
virtual int imeas::IDataSequence::GetSamplesCount () const [pure virtual]
Get size of this raster sequence.
Implemented in imeas::CGeneralDataSequence, and imeas::TDiscrDataSequence< Element >.
Referenced by imeas::TDiscrDataSequence< Element >::CopyFrom().
virtual const IDataSequenceInfo* imeas::IDataSequence::GetSequenceInfo () const [pure virtual]
Get additional information about this sequence.
Implemented in imeas::CGeneralDataSequence, and imeas::TDiscrDataSequence< Element >.
virtual bool imeas::IDataSequence::IsEmpty () const [pure virtual]
Return true if this sequence has no sample.
Implemented in imeas::CGeneralDataSequence, and imeas::TDiscrDataSequence< Element >.
virtual void imeas::IDataSequence::ResetSequence () [pure virtual]
Reset this sequence.
After this operation sequence is set to initial state.
Implemented in imeas::CGeneralDataSequence, and imeas::TDiscrDataSequence< Element >.
virtual void imeas::IDataSequence::SetSample (int index, int channel, double value) [pure virtual]
Set sample value at specified index.
Implemented in imeas::CGeneralDataSequence, and imeas::TDiscrDataSequence< Element >.
The documentation for this class was generated from the following file:
E:/Work/Projects/Development/AcfSln/Include/imeas/IDataSequence.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy