iedge::CEdgeLine Class Reference
iedge::CEdgeLine Class Reference
#include <CEdgeLine.h>
Public Types
typedef i2d::CObject2dBase BaseClass
Public Member Functions
CEdgeLine ()
CEdgeLine (const CEdgeLine &edgeLine)
void Clear ()
const CEdgeNode & GetNode (int index) const
Return node at specified index.
CEdgeNode & GetNodeRef (int index)
Return reference to node at specified index.
void SetNode (int index, const CEdgeNode &node)
Set node at specified index.
bool IsClosed () const
void SetClosed (bool state=true)
int GetNodesCount () const
int GetSegmentsCount () const
double GetTotalLength () const
double GetMinWeight () const
double GetMaxWeight () const
bool InsertNode (const CEdgeNode &node)
void CopyFromPolyline (const i2d::CPolyline &polyline, double weight=1.0, const i2d::CAffine2d *transformPtr=NULL)
Create this line using polyline object.
void CopyToPolyline (i2d::CPolyline &polyline, const i2d::CAffine2d *transformPtr=NULL) const
Copy this line to polyline.
virtual i2d::CVector2d GetCenter () const
virtual void MoveCenterTo (const i2d::CVector2d &position)
virtual i2d::CRectangle GetBoundingBox () const
virtual bool Transform (const i2d::ITransformation2d &transformation, i2d::ITransformation2d::ExactnessMode mode=i2d::ITransformation2d::EM_NONE, double *errorFactorPtr=NULL)
virtual bool InvTransform (const i2d::ITransformation2d &transformation, i2d::ITransformation2d::ExactnessMode mode=i2d::ITransformation2d::EM_NONE, double *errorFactorPtr=NULL)
virtual bool GetTransformed (const i2d::ITransformation2d &transformation, IObject2d &result, i2d::ITransformation2d::ExactnessMode mode=i2d::ITransformation2d::EM_NONE, double *errorFactorPtr=NULL) const
virtual bool GetInvTransformed (const i2d::ITransformation2d &transformation, IObject2d &result, i2d::ITransformation2d::ExactnessMode mode=i2d::ITransformation2d::EM_NONE, double *errorFactorPtr=NULL) const
virtual bool Serialize (iser::IArchive &archive)
Public Member Functions inherited from i2d::CObject2dBase
virtual bool Transform (const ITransformation2d &transformation, ITransformation2d::ExactnessMode mode=ITransformation2d::EM_NONE, double *errorFactorPtr=NULL)
virtual bool InvTransform (const ITransformation2d &transformation, ITransformation2d::ExactnessMode mode=ITransformation2d::EM_NONE, double *errorFactorPtr=NULL)
virtual bool GetTransformed (const ITransformation2d &transformation, IObject2d &result, ITransformation2d::ExactnessMode mode=ITransformation2d::EM_NONE, double *errorFactorPtr=NULL) const
virtual bool GetInvTransformed (const ITransformation2d &transformation, IObject2d &result, ITransformation2d::ExactnessMode mode=ITransformation2d::EM_NONE, double *errorFactorPtr=NULL) const
virtual bool Serialize (IArchive &archive)=0
Public Member Functions inherited from i2d::IObject2d
virtual void SetCalibration (const ICalibration2d *calibrationPtr, bool releaseFlag=false)=0
Public Member Functions inherited from i2d::ICalibrationProvider
virtual const ICalibration2d * GetCalibration () const =0
Protected Member Functions
void EnsureVolatileValid () const
Make sure, that all volatile values are calculated and valid.
virtual void CalcVolatile () const
virtual void OnEndChanges (int changeFlags, istd::IPolymorphic *changeParamsPtr)
Detailed Description
Definition at line 19 of file CEdgeLine.h.
Member Typedef Documentation
typedef i2d::CObject2dBase iedge::CEdgeLine::BaseClass
Definition at line 22 of file CEdgeLine.h.
Constructor & Destructor Documentation
iedge::CEdgeLine::CEdgeLine ()
iedge::CEdgeLine::CEdgeLine (const CEdgeLine & edgeLine)
Member Function Documentation
virtual void iedge::CEdgeLine::CalcVolatile () const protected virtual
Referenced by EnsureVolatileValid().
void iedge::CEdgeLine::Clear ()
void iedge::CEdgeLine::CopyFromPolyline (const i2d::CPolyline & polyline, double weight = 1.0, const i2d::CAffine2d * transformPtr = NULL)
Create this line using polyline object.
Please note, that no calibration will be copied.
Parameters
polyline source polyline object.
weight weight used for all nodes.
transformPtr optional transformation used to convert node positions.
void iedge::CEdgeLine::CopyToPolyline (i2d::CPolyline & polyline, const i2d::CAffine2d * transformPtr = NULL) const
Copy this line to polyline.
Please note, that no calibration will be copied.
Parameters
polyline result polyline object.
transformPtr optional transformation used to convert node positions.
void iedge::CEdgeLine::EnsureVolatileValid () const inline protected
Make sure, that all volatile values are calculated and valid.
Definition at line 174 of file CEdgeLine.h.
References CalcVolatile().
Referenced by GetMaxWeight(), GetMinWeight(), and GetTotalLength().
virtual i2d::CRectangle iedge::CEdgeLine::GetBoundingBox () const virtual
Implements i2d::CObject2dBase.
virtual i2d::CVector2d iedge::CEdgeLine::GetCenter () const virtual
Implements i2d::CObject2dBase.
virtual bool iedge::CEdgeLine::GetInvTransformed (const i2d::ITransformation2d & transformation, IObject2d & result, i2d::ITransformation2d::ExactnessMode mode = i2d::ITransformation2d::EM_NONE, double * errorFactorPtr = NULL) const virtual
double iedge::CEdgeLine::GetMaxWeight () const inline
Definition at line 158 of file CEdgeLine.h.
References EnsureVolatileValid().
double iedge::CEdgeLine::GetMinWeight () const inline
Definition at line 150 of file CEdgeLine.h.
References EnsureVolatileValid().
const CEdgeNode& iedge::CEdgeLine::GetNode (int index) const
Return node at specified index.
Parameters
index an index in node table.
CEdgeNode& iedge::CEdgeLine::GetNodeRef (int index)
Return reference to node at specified index.
Parameters
index an index in node table.
int iedge::CEdgeLine::GetNodesCount () const inline
Definition at line 130 of file CEdgeLine.h.
int iedge::CEdgeLine::GetSegmentsCount () const inline
Definition at line 136 of file CEdgeLine.h.
double iedge::CEdgeLine::GetTotalLength () const inline
Definition at line 142 of file CEdgeLine.h.
References EnsureVolatileValid().
virtual bool iedge::CEdgeLine::GetTransformed (const i2d::ITransformation2d & transformation, IObject2d & result, i2d::ITransformation2d::ExactnessMode mode = i2d::ITransformation2d::EM_NONE, double * errorFactorPtr = NULL) const virtual
bool iedge::CEdgeLine::InsertNode (const CEdgeNode & node)
virtual bool iedge::CEdgeLine::InvTransform (const i2d::ITransformation2d & transformation, i2d::ITransformation2d::ExactnessMode mode = i2d::ITransformation2d::EM_NONE, double * errorFactorPtr = NULL) virtual
bool iedge::CEdgeLine::IsClosed () const inline
Definition at line 166 of file CEdgeLine.h.
virtual void iedge::CEdgeLine::MoveCenterTo (const i2d::CVector2d & position) virtual
Implements i2d::CObject2dBase.
virtual void iedge::CEdgeLine::OnEndChanges (int changeFlags, istd::IPolymorphic * changeParamsPtr) protected virtual
virtual bool iedge::CEdgeLine::Serialize (iser::IArchive & archive) virtual
void iedge::CEdgeLine::SetClosed (bool state = true)
void iedge::CEdgeLine::SetNode (int index, const CEdgeNode & node)
Set node at specified index.
Parameters
index index in node table.
node new node position.
virtual bool iedge::CEdgeLine::Transform (const i2d::ITransformation2d & transformation, i2d::ITransformation2d::ExactnessMode mode = i2d::ITransformation2d::EM_NONE, double * errorFactorPtr = NULL) virtual
The documentation for this class was generated from the following file:
Include/iedge/CEdgeLine.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy