iprop::TMultiProperty< Value, Container > Class Template Reference
iprop::TMultiProperty< Value, Container > Class Template Reference
Template implementation of multiple property.
#include <TMultiProperty.h>
Public Types
typedef Value ValueType
typedef CPropertyBase BaseClass
typedef Container ValueList
typedef ValueList::iterator iterator
typedef ValueList::const_iterator const_iterator
Public Member Functions
TMultiProperty ()
Default constructor.
TMultiProperty (IPropertiesManager *propertyOwnerPtr, const QByteArray &propertyId, const QByteArray &propertyDescription, int propertyFlags, int changeFlags=0, int elementsCount=0, Value *valuesPtr=NULL)
Constructor.
void SetValues (const ValueList &valueList)
template<class ContainerImpl >
void SetValues (typename ContainerImpl::const_iterator begin, typename ContainerImpl::const_iterator end)
Set value list to the property.
const ValueList & GetValues () const
Get all values.
virtual int GetValuesCount () const
Get number of values in the multi property.
virtual Value GetValueAt (int index) const
Get value at the index index.
virtual void SetValueAt (int index, const Value &value)
Set value at the index index to new value value.
virtual void InsertValue (const Value &value)
Insert new value into container.
virtual void ResetValues ()
Remove all values from the container.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
QByteArray GetFactoryId () const
virtual bool Serialize (iser::IArchive &archive)
Static Public Member Functions
static const QByteArray & GetTypeName ()
Protected Attributes
Container m_values
Detailed Description
template<typename Value, class Container = QVector<Value>>
class iprop::TMultiProperty< Value, Container >
Template implementation of multiple property.
Definition at line 31 of file TMultiProperty.h.
Member Typedef Documentation
template<typename Value, class Container = QVector<Value>> typedef CPropertyBase iprop::TMultiProperty< Value, Container >::BaseClass
Reimplemented from iser::TCopySerializedWrap< IProperty >.
Definition at line 35 of file TMultiProperty.h.
template<typename Value, class Container = QVector<Value>> typedef ValueList::const_iterator iprop::TMultiProperty< Value, Container >::const_iterator
Definition at line 38 of file TMultiProperty.h.
template<typename Value, class Container = QVector<Value>> typedef ValueList::iterator iprop::TMultiProperty< Value, Container >::iterator
Definition at line 37 of file TMultiProperty.h.
template<typename Value, class Container = QVector<Value>> typedef Container iprop::TMultiProperty< Value, Container >::ValueList
Definition at line 36 of file TMultiProperty.h.
template<typename Value, class Container = QVector<Value>> typedef Value iprop::TMultiProperty< Value, Container >::ValueType
Definition at line 34 of file TMultiProperty.h.
Constructor & Destructor Documentation
template<typename Value , class Container > iprop::TMultiProperty< Value, Container >::TMultiProperty ()
Default constructor.
Definition at line 127 of file TMultiProperty.h.
template<typename Value , class Container > iprop::TMultiProperty< Value, Container >::TMultiProperty (IPropertiesManager * propertyOwnerPtr, const QByteArray & propertyId, const QByteArray & propertyDescription, int propertyFlags, int changeFlags = 0, int elementsCount = 0, Value * valuesPtr = NULL)
Constructor.
Parameters:
propertyOwnerPtr Owner of the attrbiute.
propertyId Unique ID of the attrbiute.
propertyId Property description.
changeFlags Change flags for model update notification.
elementsCount Number of elements stored at valuesPtr.
valuesPtr Pointer to array of elements.
Definition at line 133 of file TMultiProperty.h.
References iprop::TMultiProperty< Value, Container >::m_values.
Member Function Documentation
template<typename Value , class Container > TMultiProperty< Value, Container >::iterator iprop::TMultiProperty< Value, Container >::begin ()
Definition at line 229 of file TMultiProperty.h.
template<typename Value , class Container > TMultiProperty< Value, Container >::const_iterator iprop::TMultiProperty< Value, Container >::begin () const
Definition at line 236 of file TMultiProperty.h.
template<typename Value , class Container > TMultiProperty< Value, Container >::iterator iprop::TMultiProperty< Value, Container >::end ()
Definition at line 243 of file TMultiProperty.h.
template<typename Value , class Container > TMultiProperty< Value, Container >::const_iterator iprop::TMultiProperty< Value, Container >::end () const
Definition at line 250 of file TMultiProperty.h.
template<typename Value , class Container > QByteArray iprop::TMultiProperty< Value, Container >::GetFactoryId () const
Definition at line 259 of file TMultiProperty.h.
template<typename Value , class Container > const QByteArray & iprop::TMultiProperty< Value, Container >::GetTypeName () [static]
Definition at line 312 of file TMultiProperty.h.
template<typename Value , class Container > Value iprop::TMultiProperty< Value, Container >::GetValueAt (int index) const [virtual]
Get value at the index index.
Definition at line 187 of file TMultiProperty.h.
References I_ASSERT.
template<typename Value , class Container > const TMultiProperty< Value, Container >::ValueList & iprop::TMultiProperty< Value, Container >::GetValues () const
Get all values.
Definition at line 173 of file TMultiProperty.h.
template<typename Value , class Container > int iprop::TMultiProperty< Value, Container >::GetValuesCount () const [virtual]
Get number of values in the multi property.
Definition at line 180 of file TMultiProperty.h.
template<typename Value , class Container > void iprop::TMultiProperty< Value, Container >::InsertValue (const Value & value) [virtual]
Insert new value into container.
Definition at line 211 of file TMultiProperty.h.
template<typename Value , class Container > void iprop::TMultiProperty< Value, Container >::ResetValues () [virtual]
Remove all values from the container.
Definition at line 218 of file TMultiProperty.h.
template<typename Value , class Container > bool iprop::TMultiProperty< Value, Container >::Serialize (iser::IArchive & archive) [virtual]
Definition at line 268 of file TMultiProperty.h.
References iser::IArchive::BeginMultiTag(), iser::IArchive::BeginTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), NULL, and iser::IArchive::Process().
template<typename Value , class Container > void iprop::TMultiProperty< Value, Container >::SetValueAt (int index, const Value & value) [virtual]
Set value at the index index to new value value.
Definition at line 197 of file TMultiProperty.h.
References I_ASSERT.
template<typename Value , class Container > void iprop::TMultiProperty< Value, Container >::SetValues (const ValueList & valueList)
Definition at line 150 of file TMultiProperty.h.
template<typename Value , class Container > template<class ContainerImpl > void iprop::TMultiProperty< Value, Container >::SetValues (typename ContainerImpl::const_iterator begin, typename ContainerImpl::const_iterator end)
Set value list to the property.
Definition at line 158 of file TMultiProperty.h.
Member Data Documentation
template<typename Value, class Container = QVector<Value>> Container iprop::TMultiProperty< Value, Container >::m_values [protected]
Definition at line 117 of file TMultiProperty.h.
Referenced by iprop::TMultiProperty< Value, Container >::TMultiProperty().
The documentation for this class was generated from the following file:
Include/iprop/TMultiProperty.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy