iproc::ISupplier Class Reference
iproc::ISupplier Class Reference
Base interface for suppliers providing synchrone processing of single object with "pull data" model.
#include <ISupplier.h>
Public Types
enum WorkStatus {
WS_INVALID, WS_INIT, WS_LOCKED, WS_OK,
WS_CANCELED, WS_ERROR, WS_CRITICAL
}
enum ChangeFlags { CF_SUPPLIER_RESULTS = 1 << 22 }
enum WorkMessageType { WMT_TEMP, WMT_RESULTS }
Public Member Functions
virtual int GetWorkStatus () const =0
Get status of last work.
virtual void InvalidateSupplier ()=0
Called to signalize that this supplier is invalid.
virtual void EnsureWorkInitialized ()=0
Force the supplier to initialize its work.
virtual void EnsureWorkFinished ()=0
Ensure that all objects are produced.
virtual void ClearWorkResults ()=0
Remove all stored work results.
virtual const
ilog::IMessageContainer * GetWorkMessages (int messageType) const =0
Get messages outputted by this work.
virtual iprm::IParamsSet * GetModelParametersSet () const =0
Get parameter set using by this supplier.
Detailed Description
Base interface for suppliers providing synchrone processing of single object with "pull data" model.
Additional interfaces (providers) should provide access to intern stored produced objects. For example image provider should provide method {const i2d::CRectangle* GetAoi() const}. The internal stored object should be created on demand.
Definition at line 22 of file ISupplier.h.
Member Enumeration Documentation
enum iproc::ISupplier::ChangeFlags
Enumerator:
CF_SUPPLIER_RESULTS
Supplier result changed.
Reimplemented from istd::IChangeable.
Definition at line 57 of file ISupplier.h.
enum iproc::ISupplier::WorkMessageType
Enumerator:
WMT_TEMP
WMT_RESULTS
Definition at line 65 of file ISupplier.h.
enum iproc::ISupplier::WorkStatus
Enumerator:
WS_INVALID
Supplier is invalidated and will produce new result on demand.
WS_INIT
New work is initialized.
WS_LOCKED
Supplier is locked becouse it is doing processing step.
WS_OK
Work was done correctly and no error occure.
WS_CANCELED
Work was canceled.
WS_ERROR
Work was done, but there were errors.
WS_CRITICAL
Work cannot be done.
Definition at line 25 of file ISupplier.h.
Member Function Documentation
virtual void iproc::ISupplier::ClearWorkResults () [pure virtual]
Remove all stored work results.
This set also work state to WS_INIT.
Implemented in iinsp::CInspectionTaskComp, iproc::TSupplierCompWrap< Product >, iproc::TSupplierCompWrap< istd::TPointerVector< iimg::IBitmap > >, iproc::TSupplierCompWrap< imeas::CGeneralDataSequence >, iproc::TSupplierCompWrap< QVector< i2d::CLine2d > >, iproc::TSupplierCompWrap< istd::TPointerVector< const iimg::IBitmap > >, iproc::TSupplierCompWrap< QPair< i2d::ITransformation2d *, istd::TDelPtr< iimg::IBitmap > > >, iproc::TSupplierCompWrap< CEdgeLineContainer >, iproc::TSupplierCompWrap< QPair< iipr::CFeaturesContainer, QVector< i2d::CAffineTransformation2d > > >, iproc::TSupplierCompWrap< imath::CVarVector >, iproc::TSupplierCompWrap< imeas::CSimpleNumericValue >, iproc::TSupplierCompWrap< imod::TModelWrap< imeas::CSimpleSamplesSequence32 > >, iproc::TSupplierCompWrap< QVector< imeas::CGeneralDataSequence > >, iproc::TSupplierCompWrap< CFeaturesContainer >, iproc::TSupplierCompWrap< istd::TDelPtr< iimg::IBitmap > >, iproc::TSupplierCompWrap< QPair< i2d::ICalibration2d *, istd::TDelPtr< iimg::IBitmap > > >, iproc::TSupplierCompWrap< QPair< istd::TDelPtr< const i2d::ICalibration2d >, istd::TDelPtr< iimg::IBitmap > > >, and iipr::CDelegatedBitmapSupplierComp.
virtual void iproc::ISupplier::EnsureWorkFinished () [pure virtual]
Ensure that all objects are produced.
Implemented in iinsp::CInspectionTaskComp, iproc::TSupplierCompWrap< Product >, iproc::TSupplierCompWrap< istd::TPointerVector< iimg::IBitmap > >, iproc::TSupplierCompWrap< imeas::CGeneralDataSequence >, iproc::TSupplierCompWrap< QVector< i2d::CLine2d > >, iproc::TSupplierCompWrap< istd::TPointerVector< const iimg::IBitmap > >, iproc::TSupplierCompWrap< QPair< i2d::ITransformation2d *, istd::TDelPtr< iimg::IBitmap > > >, iproc::TSupplierCompWrap< CEdgeLineContainer >, iproc::TSupplierCompWrap< QPair< iipr::CFeaturesContainer, QVector< i2d::CAffineTransformation2d > > >, iproc::TSupplierCompWrap< imath::CVarVector >, iproc::TSupplierCompWrap< imeas::CSimpleNumericValue >, iproc::TSupplierCompWrap< imod::TModelWrap< imeas::CSimpleSamplesSequence32 > >, iproc::TSupplierCompWrap< QVector< imeas::CGeneralDataSequence > >, iproc::TSupplierCompWrap< CFeaturesContainer >, iproc::TSupplierCompWrap< istd::TDelPtr< iimg::IBitmap > >, iproc::TSupplierCompWrap< QPair< i2d::ICalibration2d *, istd::TDelPtr< iimg::IBitmap > > >, iproc::TSupplierCompWrap< QPair< istd::TDelPtr< const i2d::ICalibration2d >, istd::TDelPtr< iimg::IBitmap > > >, and iipr::CDelegatedBitmapSupplierComp.
Referenced by iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::DoTest().
virtual void iproc::ISupplier::EnsureWorkInitialized () [pure virtual]
Force the supplier to initialize its work.
First if work is initialized, new calculation can be done.
Implemented in iinsp::CInspectionTaskComp, iproc::TSupplierCompWrap< Product >, iproc::TSupplierCompWrap< istd::TPointerVector< iimg::IBitmap > >, iproc::TSupplierCompWrap< imeas::CGeneralDataSequence >, iproc::TSupplierCompWrap< QVector< i2d::CLine2d > >, iproc::TSupplierCompWrap< istd::TPointerVector< const iimg::IBitmap > >, iproc::TSupplierCompWrap< QPair< i2d::ITransformation2d *, istd::TDelPtr< iimg::IBitmap > > >, iproc::TSupplierCompWrap< CEdgeLineContainer >, iproc::TSupplierCompWrap< QPair< iipr::CFeaturesContainer, QVector< i2d::CAffineTransformation2d > > >, iproc::TSupplierCompWrap< imath::CVarVector >, iproc::TSupplierCompWrap< imeas::CSimpleNumericValue >, iproc::TSupplierCompWrap< imod::TModelWrap< imeas::CSimpleSamplesSequence32 > >, iproc::TSupplierCompWrap< QVector< imeas::CGeneralDataSequence > >, iproc::TSupplierCompWrap< CFeaturesContainer >, iproc::TSupplierCompWrap< istd::TDelPtr< iimg::IBitmap > >, iproc::TSupplierCompWrap< QPair< i2d::ICalibration2d *, istd::TDelPtr< iimg::IBitmap > > >, iproc::TSupplierCompWrap< QPair< istd::TDelPtr< const i2d::ICalibration2d >, istd::TDelPtr< iimg::IBitmap > > >, and iipr::CDelegatedBitmapSupplierComp.
Referenced by iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::DoTest(), and iproc::TSupplierCompWrap< Product >::EnsureWorkInitialized().
virtual iprm::IParamsSet* iproc::ISupplier::GetModelParametersSet () const [pure virtual]
Get parameter set using by this supplier.
The pointed object will not be relocated - no reconnect is needed if it is observed. If the supplier doesn't support parameters, it returns NULL.
Implemented in iinsp::CInspectionTaskComp, iproc::TSupplierCompWrap< Product >, iproc::TSupplierCompWrap< istd::TPointerVector< iimg::IBitmap > >, iproc::TSupplierCompWrap< imeas::CGeneralDataSequence >, iproc::TSupplierCompWrap< QVector< i2d::CLine2d > >, iproc::TSupplierCompWrap< istd::TPointerVector< const iimg::IBitmap > >, iproc::TSupplierCompWrap< QPair< i2d::ITransformation2d *, istd::TDelPtr< iimg::IBitmap > > >, iproc::TSupplierCompWrap< CEdgeLineContainer >, iproc::TSupplierCompWrap< QPair< iipr::CFeaturesContainer, QVector< i2d::CAffineTransformation2d > > >, iproc::TSupplierCompWrap< imath::CVarVector >, iproc::TSupplierCompWrap< imeas::CSimpleNumericValue >, iproc::TSupplierCompWrap< imod::TModelWrap< imeas::CSimpleSamplesSequence32 > >, iproc::TSupplierCompWrap< QVector< imeas::CGeneralDataSequence > >, iproc::TSupplierCompWrap< CFeaturesContainer >, iproc::TSupplierCompWrap< istd::TDelPtr< iimg::IBitmap > >, iproc::TSupplierCompWrap< QPair< i2d::ICalibration2d *, istd::TDelPtr< iimg::IBitmap > > >, iproc::TSupplierCompWrap< QPair< istd::TDelPtr< const i2d::ICalibration2d >, istd::TDelPtr< iimg::IBitmap > > >, and iipr::CDelegatedBitmapSupplierComp.
Referenced by iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::IsLoadParamsSupported(), iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::IsSaveParamsSupported(), iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::LoadParams(), iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::OnGuiModelAttached(), iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::OnGuiModelDetached(), and iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::SaveParams().
virtual const ilog::IMessageContainer* iproc::ISupplier::GetWorkMessages (int messageType) const [pure virtual]
Get messages outputted by this work.
The pointed object will not be relocated - no reconnect is needed if it is observed. If the supplier doesn't support list of messages, it returns NULL.
Parameters:
messageType type of message,
See also:
WorkMessageType.
Implemented in iinsp::CInspectionTaskComp, iproc::TSupplierCompWrap< Product >, iproc::TSupplierCompWrap< istd::TPointerVector< iimg::IBitmap > >, iproc::TSupplierCompWrap< imeas::CGeneralDataSequence >, iproc::TSupplierCompWrap< QVector< i2d::CLine2d > >, iproc::TSupplierCompWrap< istd::TPointerVector< const iimg::IBitmap > >, iproc::TSupplierCompWrap< QPair< i2d::ITransformation2d *, istd::TDelPtr< iimg::IBitmap > > >, iproc::TSupplierCompWrap< CEdgeLineContainer >, iproc::TSupplierCompWrap< QPair< iipr::CFeaturesContainer, QVector< i2d::CAffineTransformation2d > > >, iproc::TSupplierCompWrap< imath::CVarVector >, iproc::TSupplierCompWrap< imeas::CSimpleNumericValue >, iproc::TSupplierCompWrap< imod::TModelWrap< imeas::CSimpleSamplesSequence32 > >, iproc::TSupplierCompWrap< QVector< imeas::CGeneralDataSequence > >, iproc::TSupplierCompWrap< CFeaturesContainer >, iproc::TSupplierCompWrap< istd::TDelPtr< iimg::IBitmap > >, iproc::TSupplierCompWrap< QPair< i2d::ICalibration2d *, istd::TDelPtr< iimg::IBitmap > > >, iproc::TSupplierCompWrap< QPair< istd::TDelPtr< const i2d::ICalibration2d >, istd::TDelPtr< iimg::IBitmap > > >, and iipr::CDelegatedBitmapSupplierComp.
virtual int iproc::ISupplier::GetWorkStatus () const [pure virtual]
Get status of last work.
Please note, that this status is not a part of supplier model and can be changed without any notification.
Returns:
work status defined in iproc::ISupplier::WorkStatus.
Implemented in iinsp::CInspectionTaskComp, iproc::TSupplierCompWrap< Product >, iproc::TSupplierCompWrap< istd::TPointerVector< iimg::IBitmap > >, iproc::TSupplierCompWrap< imeas::CGeneralDataSequence >, iproc::TSupplierCompWrap< QVector< i2d::CLine2d > >, iproc::TSupplierCompWrap< istd::TPointerVector< const iimg::IBitmap > >, iproc::TSupplierCompWrap< QPair< i2d::ITransformation2d *, istd::TDelPtr< iimg::IBitmap > > >, iproc::TSupplierCompWrap< CEdgeLineContainer >, iproc::TSupplierCompWrap< QPair< iipr::CFeaturesContainer, QVector< i2d::CAffineTransformation2d > > >, iproc::TSupplierCompWrap< imath::CVarVector >, iproc::TSupplierCompWrap< imeas::CSimpleNumericValue >, iproc::TSupplierCompWrap< imod::TModelWrap< imeas::CSimpleSamplesSequence32 > >, iproc::TSupplierCompWrap< QVector< imeas::CGeneralDataSequence > >, iproc::TSupplierCompWrap< CFeaturesContainer >, iproc::TSupplierCompWrap< istd::TDelPtr< iimg::IBitmap > >, iproc::TSupplierCompWrap< QPair< i2d::ICalibration2d *, istd::TDelPtr< iimg::IBitmap > > >, iproc::TSupplierCompWrap< QPair< istd::TDelPtr< const i2d::ICalibration2d >, istd::TDelPtr< iimg::IBitmap > > >, and iipr::CDelegatedBitmapSupplierComp.
Referenced by iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::AfterUpdate(), and iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::DoTest().
virtual void iproc::ISupplier::InvalidateSupplier () [pure virtual]
Called to signalize that this supplier is invalid.
This signal will be transfered to all supplier which are registered as output.
Returns:
true, if initialization could be done.
Implemented in iinsp::CInspectionTaskComp, iproc::TSupplierCompWrap< Product >, iproc::TSupplierCompWrap< istd::TPointerVector< iimg::IBitmap > >, iproc::TSupplierCompWrap< imeas::CGeneralDataSequence >, iproc::TSupplierCompWrap< QVector< i2d::CLine2d > >, iproc::TSupplierCompWrap< istd::TPointerVector< const iimg::IBitmap > >, iproc::TSupplierCompWrap< QPair< i2d::ITransformation2d *, istd::TDelPtr< iimg::IBitmap > > >, iproc::TSupplierCompWrap< CEdgeLineContainer >, iproc::TSupplierCompWrap< QPair< iipr::CFeaturesContainer, QVector< i2d::CAffineTransformation2d > > >, iproc::TSupplierCompWrap< imath::CVarVector >, iproc::TSupplierCompWrap< imeas::CSimpleNumericValue >, iproc::TSupplierCompWrap< imod::TModelWrap< imeas::CSimpleSamplesSequence32 > >, iproc::TSupplierCompWrap< QVector< imeas::CGeneralDataSequence > >, iproc::TSupplierCompWrap< CFeaturesContainer >, iproc::TSupplierCompWrap< istd::TDelPtr< iimg::IBitmap > >, iproc::TSupplierCompWrap< QPair< i2d::ICalibration2d *, istd::TDelPtr< iimg::IBitmap > > >, iproc::TSupplierCompWrap< QPair< istd::TDelPtr< const i2d::ICalibration2d >, istd::TDelPtr< iimg::IBitmap > > >, and iipr::CDelegatedBitmapSupplierComp.
Referenced by iqtinsp::TSupplierGuiCompBase< UI, WidgetType >::DoTest().
The documentation for this class was generated from the following file:
Include/iproc/ISupplier.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy