iipr::TWeightedFeatureWrap< BaseObject > Class Template Reference
iipr::TWeightedFeatureWrap< BaseObject > Class Template Reference
Wrapper allowing to create feature object from some another serializable one.
#include <TWeightedFeatureWrap.h>
Public Types
typedef imeas::CSimpleNumericValue BaseClass
typedef BaseObject BaseClass2
Public Member Functions
TWeightedFeatureWrap (double weight=1.0)
double GetWeight () const
void SetWeight (double weight)
virtual bool Serialize (iser::IArchive &archive)
virtual bool CopyFrom (const IChangeable &object, CompatibilityMode mode)
Protected Attributes
double m_weight
Detailed Description
template<class BaseObject>
class iipr::TWeightedFeatureWrap< BaseObject >
Wrapper allowing to create feature object from some another serializable one.
Definition at line 20 of file TWeightedFeatureWrap.h.
Member Typedef Documentation
template<class BaseObject> typedef imeas::CSimpleNumericValue iipr::TWeightedFeatureWrap< BaseObject >::BaseClass
Reimplemented in iipr::CSearchFeature, and iipr::CCaliperDistanceFeature.
Definition at line 25 of file TWeightedFeatureWrap.h.
template<class BaseObject> typedef BaseObject iipr::TWeightedFeatureWrap< BaseObject >::BaseClass2
Definition at line 26 of file TWeightedFeatureWrap.h.
Constructor & Destructor Documentation
template<class BaseObject > iipr::TWeightedFeatureWrap< BaseObject >::TWeightedFeatureWrap (double weight = 1.0)
Definition at line 47 of file TWeightedFeatureWrap.h.
Member Function Documentation
template<class BaseObject > bool iipr::TWeightedFeatureWrap< BaseObject >::CopyFrom (const IChangeable & object, CompatibilityMode mode) [virtual]
Reimplemented from imeas::CSimpleNumericValue.
Reimplemented in iipr::CSearchFeature.
Definition at line 91 of file TWeightedFeatureWrap.h.
References iipr::TWeightedFeatureWrap< BaseObject >::GetWeight(), and NULL.
template<class BaseObject > double iipr::TWeightedFeatureWrap< BaseObject >::GetWeight () const
Definition at line 54 of file TWeightedFeatureWrap.h.
Referenced by iipr::TWeightedFeatureWrap< BaseObject >::CopyFrom().
template<class BaseObject > bool iipr::TWeightedFeatureWrap< BaseObject >::Serialize (iser::IArchive & archive) [virtual]
Reimplemented from imeas::CSimpleNumericValue.
Reimplemented in iipr::CSearchFeature.
Definition at line 70 of file TWeightedFeatureWrap.h.
References iser::IArchive::BeginTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), NULL, and iser::IArchive::Process().
template<class BaseObject > void iipr::TWeightedFeatureWrap< BaseObject >::SetWeight (double weight)
Definition at line 61 of file TWeightedFeatureWrap.h.
Member Data Documentation
template<class BaseObject> double iipr::TWeightedFeatureWrap< BaseObject >::m_weight [protected]
Definition at line 40 of file TWeightedFeatureWrap.h.
The documentation for this class was generated from the following file:
Include/iipr/TWeightedFeatureWrap.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy