iprop::TProperty< Value > Class Template Reference
iprop::TProperty< Value > Class Template Reference
Template implementation of an atomic property.
#include <TProperty.h>
Public Types
typedef Value ValueType
typedef TProperty< Value > PropertyType
typedef CPropertyBase BaseClass
Public Member Functions
TProperty ()
TProperty (IPropertiesManager *propertyOwnerPtr, const QByteArray &propertyName, const QByteArray &propertyDescription, int propertyFlags, int changeFlags=0, const ValueType &defaultValue=ValueType())
const Value & GetValue () const
void SetValue (const Value &value)
void ResetValue ()
virtual const iser::IObject * GetDefaultPropertyPtr () const
virtual QByteArray GetFactoryId () const
virtual bool Serialize (iser::IArchive &archive)
Static Public Member Functions
static QByteArray GetTypeName ()
Protected Attributes
Value m_value
istd::TDelPtr< PropertyType > m_defaultPropertyValuePtr
Detailed Description
template<typename Value>
class iprop::TProperty< Value >
Template implementation of an atomic property.
The type of the template argument must be supported by archive implementation.
See also:
IArchive::Process If you want to define a property of the complex, already serializable object type, please use TObjectProperty class
Definition at line 25 of file TProperty.h.
Member Typedef Documentation
template<typename Value > typedef CPropertyBase iprop::TProperty< Value >::BaseClass
Reimplemented from iser::TCopySerializedWrap< IProperty >.
Definition at line 30 of file TProperty.h.
template<typename Value > typedef TProperty<Value> iprop::TProperty< Value >::PropertyType
Definition at line 29 of file TProperty.h.
template<typename Value > typedef Value iprop::TProperty< Value >::ValueType
Definition at line 28 of file TProperty.h.
Constructor & Destructor Documentation
template<typename Value > iprop::TProperty< Value >::TProperty ()
Definition at line 68 of file TProperty.h.
template<typename Value > iprop::TProperty< Value >::TProperty (IPropertiesManager * propertyOwnerPtr, const QByteArray & propertyName, const QByteArray & propertyDescription, int propertyFlags, int changeFlags = 0, const ValueType & defaultValue = ValueType())
Definition at line 75 of file TProperty.h.
References istd::TPointerBase< Type >::IsValid(), iprop::TProperty< Value >::m_defaultPropertyValuePtr, and istd::TDelPtr< Type, Accessor >::SetPtr().
Member Function Documentation
template<typename Value > const iser::IObject * iprop::TProperty< Value >::GetDefaultPropertyPtr () const [virtual]
Definition at line 123 of file TProperty.h.
template<typename Value > QByteArray iprop::TProperty< Value >::GetFactoryId () const [virtual]
Definition at line 132 of file TProperty.h.
template<typename Value > QByteArray iprop::TProperty< Value >::GetTypeName () [static]
Definition at line 160 of file TProperty.h.
template<typename Value > const Value & iprop::TProperty< Value >::GetValue () const
Definition at line 94 of file TProperty.h.
template<typename Value > void iprop::TProperty< Value >::ResetValue ()
Definition at line 112 of file TProperty.h.
template<typename Value > bool iprop::TProperty< Value >::Serialize (iser::IArchive & archive) [virtual]
Definition at line 141 of file TProperty.h.
References iser::IArchive::BeginTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), NULL, and iser::IArchive::Process().
template<typename Value > void iprop::TProperty< Value >::SetValue (const Value & value)
Definition at line 101 of file TProperty.h.
Member Data Documentation
template<typename Value > istd::TDelPtr<PropertyType> iprop::TProperty< Value >::m_defaultPropertyValuePtr [mutable, protected]
Definition at line 61 of file TProperty.h.
Referenced by iprop::TProperty< Value >::TProperty().
template<typename Value > Value iprop::TProperty< Value >::m_value [protected]
Definition at line 59 of file TProperty.h.
The documentation for this class was generated from the following file:
Include/iprop/TProperty.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy