iprop::TObjectProperty< Value > Class Template Reference
iprop::TObjectProperty< Value > Class Template Reference
Property implementation for serializable objects.
#include <TObjectProperty.h>
Public Types
typedef Value ValueType
typedef TObjectProperty< Value > PropertyType
typedef CPropertyBase BaseClass
Public Member Functions
TObjectProperty ()
TObjectProperty (IPropertiesManager *propertyOwnerPtr, const QByteArray &propertyName, const QByteArray &propertyDescription, int propertyFlags, int changeFlags=0, const ValueType &defaultValue=ValueType())
const Value & GetValue () const
bool SetValue (const Value &value)
void ResetValue ()
virtual const iser::IObject * GetDefaultPropertyPtr () const
virtual QByteArray GetFactoryId () const
virtual bool Serialize (iser::IArchive &archive)
Static Public Member Functions
static QByteArray GetTypeName ()
Protected Attributes
iser::TCopySerializedWrap< Value > m_value
istd::TDelPtr< PropertyType > m_defaultPropertyValuePtr
Detailed Description
template<typename Value>
class iprop::TObjectProperty< Value >
Property implementation for serializable objects.
This implementation can be also interpreted as a property "wrapper" for any serializeable object.
Definition at line 24 of file TObjectProperty.h.
Member Typedef Documentation
template<typename Value > typedef CPropertyBase iprop::TObjectProperty< Value >::BaseClass
Reimplemented from iser::TCopySerializedWrap< IProperty >.
Definition at line 29 of file TObjectProperty.h.
template<typename Value > typedef TObjectProperty<Value> iprop::TObjectProperty< Value >::PropertyType
Definition at line 28 of file TObjectProperty.h.
template<typename Value > typedef Value iprop::TObjectProperty< Value >::ValueType
Definition at line 27 of file TObjectProperty.h.
Constructor & Destructor Documentation
template<typename Value > iprop::TObjectProperty< Value >::TObjectProperty ()
Definition at line 67 of file TObjectProperty.h.
template<typename Value > iprop::TObjectProperty< Value >::TObjectProperty (IPropertiesManager * propertyOwnerPtr, const QByteArray & propertyName, const QByteArray & propertyDescription, int propertyFlags, int changeFlags = 0, const ValueType & defaultValue = ValueType())
Definition at line 74 of file TObjectProperty.h.
References iprop::TObjectProperty< Value >::m_defaultPropertyValuePtr, istd::TDelPtr< Type, Accessor >::SetPtr(), and iprop::TObjectProperty< Value >::SetValue().
Member Function Documentation
template<typename Value > const iser::IObject * iprop::TObjectProperty< Value >::GetDefaultPropertyPtr () const [virtual]
Definition at line 121 of file TObjectProperty.h.
template<typename Value > QByteArray iprop::TObjectProperty< Value >::GetFactoryId () const [virtual]
Definition at line 130 of file TObjectProperty.h.
template<typename Value > QByteArray iprop::TObjectProperty< Value >::GetTypeName () [static]
Definition at line 158 of file TObjectProperty.h.
template<typename Value > const Value & iprop::TObjectProperty< Value >::GetValue () const
Definition at line 92 of file TObjectProperty.h.
template<typename Value > void iprop::TObjectProperty< Value >::ResetValue ()
Definition at line 110 of file TObjectProperty.h.
template<typename Value > bool iprop::TObjectProperty< Value >::Serialize (iser::IArchive & archive) [virtual]
Definition at line 139 of file TObjectProperty.h.
References iser::IArchive::BeginTag(), iser::IArchive::EndTag(), iser::IArchive::IsStoring(), and NULL.
template<typename Value > bool iprop::TObjectProperty< Value >::SetValue (const Value & value)
Definition at line 99 of file TObjectProperty.h.
Referenced by iprop::TObjectProperty< Value >::TObjectProperty().
Member Data Documentation
template<typename Value > istd::TDelPtr<PropertyType> iprop::TObjectProperty< Value >::m_defaultPropertyValuePtr [mutable, protected]
Definition at line 60 of file TObjectProperty.h.
Referenced by iprop::TObjectProperty< Value >::TObjectProperty().
template<typename Value > iser::TCopySerializedWrap<Value> iprop::TObjectProperty< Value >::m_value [protected]
Definition at line 58 of file TObjectProperty.h.
The documentation for this class was generated from the following file:
Include/iprop/TObjectProperty.h
© 2007-2011 Witold Gantzke and Kirill Lepskiy